const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/hashmap.json",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/manifest.json",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/favicon.ico",
"/ran/pagefind/fragment/zh-cn_d061705.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/en_edda142.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e30b897.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_825c3ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5e36d54.pf_fragment",
"/ran/pagefind/fragment/zh-cn_abc0ed3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f8f3f2e.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a24d3b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9772d78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f1b1627.pf_fragment",
"/ran/pagefind/fragment/en_dccebd7.pf_fragment",
"/ran/pagefind/fragment/en_78f477e.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_a00cdc4.pf_fragment",
"/ran/pagefind/fragment/en_6b4c4a9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a667797.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_af4a67a.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4d88531.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_3541bef.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_63f4b5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_e314ccd.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/en_21928ae.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1054af3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_7fffa0e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_316ec63.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_86379d5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/en_1f28c1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/en_83d923f.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_324b2ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_388baec.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_bd64a1d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_da4953d.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b1b57a3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/en_f575e71.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_aab3547.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.zh-cn_1047c47a22644.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.en_5b6932948b.pf_meta",
"/ran/pagefind/index/zh-cn_36f18f8.pf_index",
"/ran/pagefind/index/en_6f446a6.pf_index",
"/ran/pagefind/index/zh-cn_2314426.pf_index",
"/ran/pagefind/index/en_eb558a5.pf_index",
"/ran/pagefind/index/zh-cn_34cf86b.pf_index",
"/ran/pagefind/index/en_a96803f.pf_index",
"/ran/pagefind/index/zh-cn_8bbd46c.pf_index",
"/ran/index.html",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BDpy0Vxj.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DGTfxkhL.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranui_message_index.md.D5g3E_HL.lean.js",
"/ran/assets/cn_src_article_babel.md.BK5ERUqt.js",
"/ran/assets/src_article_astParse_tokenizer.md.DlQ1pPXF.js",
"/ran/assets/src_article_imagemin.md.DWAek4mX.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BDpy0Vxj.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Cw7KskDw.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_article_sort_bucket_index.md.PzVQLCoL.js",
"/ran/assets/cn_src_types_TS类型.md.DUqbHUmP.js",
"/ran/assets/src_article_sort_index.md.CBieyPxR.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranuts_mode_subscribe.md.CrGLQrX1.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.Bn2g427w.lean.js",
"/ran/assets/src_ranui_radar_index.md.DBEmjnlQ.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_fileInfo.md.DPJh572w.js",
"/ran/assets/src_article_sort_heap_index.md.D8BCrZDU.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/style.CqLoqpUb.css",
"/ran/assets/cn_index.md.BiRb8cft.js",
"/ran/assets/src_article_typescript_calculate.md.BZWocCYG.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.k0o8x5pa.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.D56c7sXv.lean.js",
"/ran/assets/src_article_sort_count_index.md.DKSIR0HP.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranui_checkbox_index.md.WA4xwGRD.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_article_sort_bucket_index.md.CxciXbP8.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.ClV-2oq4.lean.js",
"/ran/assets/src_ranui_radar_index.md.DBEmjnlQ.js",
"/ran/assets/src_article_bundle.md.C3vB5v5M.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.wqdYnmjy.js",
"/ran/assets/cn_src_ranui_input_index.md.Dsw2MS7v.js",
"/ran/assets/src_ranui_input_index.md.BQ45EICI.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_merge_index.md.Dn1TynpU.lean.js",
"/ran/assets/src_ranui_icon_index.md.CI-DjEmZ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.rdEi5y-8.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.k0o8x5pa.lean.js",
"/ran/assets/index.md.CwKEKKA5.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.vfoLaoky.js",
"/ran/assets/cn_src_ranuts_index.md.0zb5eBTJ.lean.js",
"/ran/assets/src_ranui_button_index.md.B6OjPMbF.js",
"/ran/assets/cn_src_types_TS类型.md.DUqbHUmP.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.AQZUIkzL.js",
"/ran/assets/src_ranui_skeleton_index.md.BErdAWpH.js",
"/ran/assets/src_article_sort_quick_index.md.DyA-o09T.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Be8pdec_.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.BYsbT9Z8.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.cCtjMIts.js",
"/ran/assets/src_ranuts_file_readFile.md.209aGZHb.lean.js",
"/ran/assets/src_article_sort_quick_index.md.DyA-o09T.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.ClV-2oq4.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BktcyayI.lean.js",
"/ran/assets/src_ranui_image_index.md.D69oaSBW.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_sort_merge_index.md.Dn1TynpU.js",
"/ran/assets/src_article_typescript_unionType.md.BzDTeGSt.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BZWocCYG.js",
"/ran/assets/src_article_imagemin.md.DWAek4mX.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CL52wqLB.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_article_sort_bucket_index.md.CxciXbP8.lean.js",
"/ran/assets/src_ranuts_utils_task.md.NEsb6FzG.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DsDQTlM9.js",
"/ran/assets/index.md.CwKEKKA5.lean.js",
"/ran/assets/src_ranui_image_index.md.D69oaSBW.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_bundler_index.md.D7DtEVpq.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.D56c7sXv.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_player_index.md.Bv1CU1AC.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CXBuI3Cq.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranui_select_index.md.BV1d-Y-9.lean.js",
"/ran/assets/src_article_sort_count_index.md.DKSIR0HP.lean.js",
"/ran/assets/cn_src_ranui_index.md.C9lby2dv.js",
"/ran/assets/cn_src_article_sort_select_index.md.CUSFIDPK.js",
"/ran/assets/src_article_javascript_domLoad.md.Bn2g427w.js",
"/ran/assets/cn_src_article_sort_quick_index.md.z8M6bYBB.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.SK7SqTIL.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Bmp3BpPJ.js",
"/ran/assets/cn_src_article_sort_quick_index.md.z8M6bYBB.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_types_高级类型.md.BtLg22ID.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CXBuI3Cq.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CE7lSPHO.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BM_lIkqQ.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CdeIy-Ix.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.3uC99od8.js",
"/ran/assets/src_article_sort_index.md.CBieyPxR.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CDSdLSh2.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.ckhDqP_Y.lean.js",
"/ran/assets/src_ranuts_index.md.BKjmoISt.js",
"/ran/assets/src_article_sort_select_index.md.DGtVaHgt.js",
"/ran/assets/src_ranui_skeleton_index.md.BErdAWpH.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.B5K9j8iV.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.DGmCU43H.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_file_readDir.md.cCtjMIts.lean.js",
"/ran/assets/cn_src_article_babel.md.BK5ERUqt.lean.js",
"/ran/assets/app.Sw3Z33Rx.js",
"/ran/assets/cn_src_article_sort_shell_index.md.B1kndr6S.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D1JrLr7X.js",
"/ran/assets/src_article_typescript_recursion.md.BdCL53Aj.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BFruKyLY.js",
"/ran/assets/cn_src_ranui_preview_index.md.C1R8FooD.lean.js",
"/ran/assets/src_article_bundle.md.C3vB5v5M.js",
"/ran/assets/cn_src_ranui_popover_index.md.BdmNYcZz.js",
"/ran/assets/src_types_TS类型.md.Cf65FCgY.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BFruKyLY.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_types_类型运算.md.BwdwL4cx.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CE7lSPHO.js",
"/ran/assets/cn_src_ranui_message_index.md.CQZNPxTQ.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CkHr0M1l.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.vfoLaoky.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.B9CZMBhG.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranui_icon_index.md.CI-DjEmZ.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Cg4oI1tD.lean.js",
"/ran/assets/cn_src_article_designMode.md.CE1rEgJa.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_sort_heap_index.md.DiQctKga.js",
"/ran/assets/cn_src_article_typescript_recursion.md.rdEi5y-8.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CQmtOBdY.lean.js",
"/ran/assets/cn_src_ranui_index.md.C9lby2dv.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.CAnKCzc3.lean.js",
"/ran/assets/src_article_sort_select_index.md.DGtVaHgt.lean.js",
"/ran/assets/src_article_designMode.md.D_9df7DT.lean.js",
"/ran/assets/src_ranui_index.md.DVCHDhr8.js",
"/ran/assets/src_ranuts_utils_getCookie.md.B9CZMBhG.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DGPmOLu6.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_types_类型运算.md.BBvSEXNK.js",
"/ran/assets/src_article_typescript_index.md.CIip00SD.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_article_sort_insert_index.md.CHJ80-zj.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.D6OASU_y.lean.js",
"/ran/assets/src_article_sort_heap_index.md.D8BCrZDU.lean.js",
"/ran/assets/src_article_typescript_pattern.md.lOPTaTcI.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.D6AHE85M.lean.js",
"/ran/assets/src_ranui_preview_index.md.zdak1Qrq.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_article_babel.md.Br2okB4w.lean.js",
"/ran/assets/cn_index.md.BiRb8cft.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Cg4oI1tD.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_types_高级类型.md.Dz5xk0BT.js",
"/ran/assets/cn_src_ranui_modal_index.md.D3yLw0V4.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.B1kndr6S.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BtLg22ID.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CdeIy-Ix.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranui_tab_index.md.AQZUIkzL.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.D7DtEVpq.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.B0ns_-XC.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_typescript_calculate.md.Dvlismgs.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CG3Bbv0f.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.OrsoDutC.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.B8ZyG_aK.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BnBh46Qg.js",
"/ran/assets/src_ranuts_index.md.BKjmoISt.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_article_sort_heap_index.md.DiQctKga.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.B5yXoMYq.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CI5H-mV0.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CQmtOBdY.js",
"/ran/assets/src_ranui_index.md.DVCHDhr8.lean.js",
"/ran/assets/src_ranui_tabs_index.md.D5oxoXCE.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BS9heB3W.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_preview_index.md.C1R8FooD.js",
"/ran/assets/cn_src_article_typescript_unionType.md.Dxpjkh95.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranuts_file_writeFile.md.BYsbT9Z8.js",
"/ran/assets/cn_src_ranui_icon_index.md.3uC99od8.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CjDOqT-_.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_article_typescript_recursion.md.BdCL53Aj.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_functionalProgramming.md.BUw9BKVH.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BXQQElUr.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/theme.DKDhNblM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/index.Bol6qi2P.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/index-DUQ13h42.c6D3EbfT.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index-DSFfwC9e.RkPMzg7f.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/pdf-B2a6ll8f.CmK-CylF.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/pwa-install.es.BZyo4fnY.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/docx-CChZ5Ycr.NiVSZbPW.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/framework.DU63L2vM.js",
"/ran/assets/chunks/jszip.min-DD9Dc6z4.BsDI-Ugu.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_astParse_tokenizer.md.DlQ1pPXF.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.BvqITGrG.js",
"/ran/assets/src_ranuts_utils_formatJson.md.B0ns_-XC.js",
"/ran/assets/src_ranui_popover_index.md.D1YqckOh.js",
"/ran/assets/src_article_typescript_pattern.md.lOPTaTcI.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_sort_index.md.Tbm_u-8c.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_bundle.md.AZIHcp-C.js",
"/ran/assets/cn_src_ranui_progress_index.md.DGTfxkhL.js",
"/ran/assets/src_ranui_progress_index.md.BCguKss8.lean.js",
"/ran/assets/src_ranui_tabs_index.md.D5oxoXCE.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Dd5ww8Gt.lean.js",
"/ran/assets/src_ranui_tab_index.md.B36RPY5l.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.209aGZHb.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D1JrLr7X.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BVwDPR0m.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CkHr0M1l.js",
"/ran/assets/cn_src_ranui_image_index.md.CwhZnocM.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Imo2l5rk.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.B5K9j8iV.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DGPmOLu6.js",
"/ran/assets/cn_src_ranui_player_index.md.BXQQElUr.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Be8pdec_.js",
"/ran/assets/src_types_类型运算.md.BwdwL4cx.js",
"/ran/assets/src_ranui_checkbox_index.md.WA4xwGRD.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CL52wqLB.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.Dsw2MS7v.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BVwDPR0m.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranui_skeleton_index.md.DP6lJasn.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Bmp3BpPJ.lean.js",
"/ran/assets/src_ranuts_utils_task.md.NEsb6FzG.js",
"/ran/assets/src_article_babel.md.Br2okB4w.js",
"/ran/assets/cn_src_article_imagemin.md.CjDOqT-_.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.BvqITGrG.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_sort_bubble_index.md.DDXHeMZa.js",
"/ran/assets/src_article_sort_radix_index.md.Dpb8KrFl.lean.js",
"/ran/assets/src_ranui_progress_index.md.BCguKss8.js",
"/ran/assets/cn_src_article_sort_merge_index.md.D6AHE85M.js",
"/ran/assets/src_types_模式匹配.md.BaphUUnU.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BktcyayI.js",
"/ran/assets/src_ranui_modal_index.md.CXFD6ppa.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.Dvlismgs.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.PzVQLCoL.lean.js",
"/ran/assets/src_article_sort_shell_index.md.Ch-_D4R4.js",
"/ran/assets/src_article_sort_bubble_index.md.DDXHeMZa.lean.js",
"/ran/assets/src_ranui_modal_index.md.CXFD6ppa.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_article_designMode.md.D_9df7DT.js",
"/ran/assets/src_ranui_input_index.md.BQ45EICI.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.wqdYnmjy.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CrGLQrX1.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BS9heB3W.lean.js",
"/ran/assets/src_types_模式匹配.md.BaphUUnU.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_button_index.md.B6OjPMbF.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CG3Bbv0f.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.SK7SqTIL.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DsDQTlM9.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Imo2l5rk.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CI5H-mV0.js",
"/ran/assets/src_article_functionalProgramming.md.BUw9BKVH.js",
"/ran/assets/cn_src_article_sort_select_index.md.CUSFIDPK.lean.js",
"/ran/assets/src_ranui_message_index.md.D5g3E_HL.js",
"/ran/assets/cn_src_types_类型运算.md.BBvSEXNK.lean.js",
"/ran/assets/src_article_typescript_index.md.CIip00SD.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.D6OASU_y.js",
"/ran/assets/cn_src_article_designMode.md.CE1rEgJa.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_types_TS类型.md.Cf65FCgY.js",
"/ran/assets/src_ranuts_file_appendFile.md.BT1I1ut0.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CDSdLSh2.js",
"/ran/assets/cn_src_article_sort_count_index.md.hoe_wqoo.js",
"/ran/assets/cn_src_article_sort_count_index.md.hoe_wqoo.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranui_modal_index.md.D3yLw0V4.js",
"/ran/assets/cn_src_article_typescript_unionType.md.Dxpjkh95.js",
"/ran/assets/src_article_sort_shell_index.md.Ch-_D4R4.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranuts_file_fileInfo.md.DPJh572w.lean.js",
"/ran/assets/cn_src_article_sort_index.md.Tbm_u-8c.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Dd5ww8Gt.js",
"/ran/assets/src_ranui_select_index.md.BV1d-Y-9.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.OrsoDutC.js",
"/ran/assets/cn_src_ranui_image_index.md.CwhZnocM.js",
"/ran/assets/src_types_高级类型.md.Dz5xk0BT.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Cw7KskDw.js",
"/ran/assets/cn_src_article_bundle.md.AZIHcp-C.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BnBh46Qg.lean.js",
"/ran/assets/src_article_typescript_unionType.md.BzDTeGSt.js",
"/ran/assets/src_ranuts_file_watchFile.md.CAnKCzc3.js",
"/ran/assets/cn_src_article_sort_insert_index.md.ckhDqP_Y.js",
"/ran/assets/src_article_sort_insert_index.md.CHJ80-zj.lean.js",
"/ran/assets/src_ranui_player_index.md.Bv1CU1AC.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.B8ZyG_aK.lean.js",
"/ran/assets/cn_src_ranuts_index.md.0zb5eBTJ.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DP6lJasn.lean.js",
"/ran/assets/src_ranui_popover_index.md.D1YqckOh.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CQZNPxTQ.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranui_tab_index.md.B36RPY5l.js",
"/ran/assets/src_ranuts_file_appendFile.md.BT1I1ut0.js",
"/ran/assets/src_ranui_preview_index.md.zdak1Qrq.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.B5yXoMYq.js",
"/ran/assets/cn_src_ranui_popover_index.md.BdmNYcZz.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_button_index.md.BM_lIkqQ.js",
"/ran/assets/src_article_sort_radix_index.md.Dpb8KrFl.js",
"/ran/assets/src_ranuts_utils_ocr.md.DGmCU43H.lean.js",
"/ran/sw.js",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/icon_48.png",
"/ran/icon.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/bundle.html",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/bundle.html",
"/ran/icon_144.png",
];
const VERSION = "1715524705";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
    // google 上报不需要缓存
    'google',
    // 插件请求不用缓存
    'chrome-extension',
    // 百度的请求不用缓存
    'baidu.com',
    'blob:',
    'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
    GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
    SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
    INSTALL: 'install',
    FETCH: 'fetch',
    ACTIVATE: 'activate',
    MESSAGE: 'message',
    SYNC: 'sync',
    PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url } = request
    const { status } = fetchedResponse
    // 只缓存状态码为 200 的请求
    if (status !== RESPONSE_STATUS.SUCCESS) return
    if (filterRequest(request)) {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service worker update cache error:', error, request)
        })
    }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
    const { url, method } = request
    return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const { url } = request
        const responseFromCache = await caches.match(url);
        // 如果缓存中有，返回已经缓存的资源
        if (responseFromCache) return responseFromCache
        // 如果缓存中没有，就从网络中请求，并更新到缓存中
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        // 当缓存中也没有，请求也不可用的时候
        // 始终需要一个一个响应
        // 甚至可以设置回落的请求，在catch中继续发起请求
        console.log('service worker cacheFirst error:', error, request)
        return new Response("Network error happened", {
            status: 408,
            headers: { "Content-Type": "text/plain" },
        });
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('service worker deleteCache error:', error, key)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
    }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
            // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
            // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service worker fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service worker self installed error:', url, error);
                })
            )
        })
    );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
    // 拦截请求
    try {
        const { request } = event
        // 忽略 IGNORE_REQUEST_LIST 中的请求，不进行拦截
        if (filterRequest(request)) {
            const responseFromServer = cacheFirst(request)
            if (responseFromServer?.clone) {
                event.respondWith(responseFromServer);
            }
        }
    } catch (error) {
        console.log('service worker self fetch error:', error, event)
    }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
    event.waitUntil(deleteOldCaches());
});



