const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/404.html",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/index.html",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_192.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/babel.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/pagefind/pagefind.zh-cn_2aba5a9a2a67e.pf_meta",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_86caad9.pf_fragment",
"/ran/pagefind/fragment/en_4c54dcd.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4aa3033.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_21aa409.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1d676ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e8d7fb5.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_56bf7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2320816.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7135acd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9bb27f9.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e712c2f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9919be9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bb4f399.pf_fragment",
"/ran/pagefind/fragment/zh-cn_63cce06.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7404f9.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5cb0744.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7785c3.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2186e18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fca9594.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a91af19.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ae66cea.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_a4c51e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cc13270.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b736c83.pf_fragment",
"/ran/pagefind/fragment/zh-cn_90c7194.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e85c0d6.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1404275.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62c4e29.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5995.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_cbc1448.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6e3ea19.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b5d6ea8.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48a39a0.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_16fb727.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac43f88.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c5b442.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2e59c37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3130d28.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_578e3e5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9e1b73b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9ceec36.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6d2c22.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f8b7d53.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f521899.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_519fac2.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/index/zh-cn_c898f54.pf_index",
"/ran/pagefind/index/zh-cn_d1e1a37.pf_index",
"/ran/pagefind/index/en_a02c658.pf_index",
"/ran/pagefind/index/en_b5f91c4.pf_index",
"/ran/pagefind/index/zh-cn_5521b2b.pf_index",
"/ran/pagefind/index/en_71df5cf.pf_index",
"/ran/pagefind/index/zh-cn_c43020e.pf_index",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.en_16ebb4a51e.pf_meta",
"/ran/pagefind/pagefind.js",
"/ran/icon_96.png",
"/ran/icon_48.png",
"/ran/assets/src_ranui_select_index.md.DFWBaIiq.lean.js",
"/ran/assets/cn_src_article_designMode.md.CCKx6A_h.js",
"/ran/assets/src_ranuts_utils_str2xml.md.GHtRrzQL.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DkjKkhVw.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.dyyL6SXC.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.C7JmNnIG.js",
"/ran/assets/src_ranuts_utils_getCookie.md.CikYi1fN.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BMvnsEqO.js",
"/ran/assets/cn_src_article_imagemin.md.BCerIzsj.lean.js",
"/ran/assets/src_types_高级类型.md.DxPwL0n4.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.DUmJDGts.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.s8TtRWtS.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.5LjmoPg7.js",
"/ran/assets/src_ranui_radar_index.md.CykEjYyI.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DCwawyw3.js",
"/ran/assets/src_ranui_tabs_index.md.CW939GxX.js",
"/ran/assets/src_ranui_message_index.md.Btu0aq3b.lean.js",
"/ran/assets/cn_src_ranui_index.md.ZqgBy25h.js",
"/ran/assets/inter-roman-latin.Bu8hRsVA.woff2",
"/ran/assets/inter-italic-latin-ext.BGcWXLrn.woff2",
"/ran/assets/src_article_typescript_calculate.md.C0thaQOM.js",
"/ran/assets/cn_src_article_sort_shell_index.md.ekUhbEQz.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BijmgDR2.js",
"/ran/assets/cn_src_article_imagemin.md.BCerIzsj.js",
"/ran/assets/src_ranui_tabs_index.md.CW939GxX.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DUEmKGyn.js",
"/ran/assets/cn_src_article_bundle.md.DHu-Batd.js",
"/ran/assets/cn_src_article_designMode.md.CCKx6A_h.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BN9kJw8E.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranuts_file_watchFile.md.DLXmd6ot.lean.js",
"/ran/assets/src_article_functionalProgramming.md.DWaI1-WW.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CJqM5IfO.js",
"/ran/assets/src_ranuts_binaryTree_index.md.DGjkamBC.lean.js",
"/ran/assets/src_article_sort_shell_index.md.6TPXyRiQ.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CrY_N2D_.js",
"/ran/assets/src_ranui_popover_index.md.KuYIYlyZ.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C-w3rk5V.lean.js",
"/ran/assets/inter-italic-cyrillic.D6csxwjC.woff2",
"/ran/assets/src_article_sort_index.md.iB4qzHMk.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CSG2ovaz.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranui_skeleton_index.md.uhvbrnSF.js",
"/ran/assets/cn_src_article_sort_index.md.Ba-gWbpG.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C-w3rk5V.js",
"/ran/assets/cn_src_ranuts_index.md.BlIiPi11.js",
"/ran/assets/src_ranui_preview_index.md.DsdPQ5JF.lean.js",
"/ran/assets/src_ranui_image_index.md.ChcUsy_8.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C2LZ3jQV.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DQ7YUoZn.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DpnjF7lg.js",
"/ran/assets/src_article_sort_quick_index.md.Dq5Mwvbi.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CBEF6VYR.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranuts_utils_task.md.Daaf5rFe.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.BwKNGAht.js",
"/ran/assets/cn_src_article_sort_select_index.md.BmYJ2kSo.js",
"/ran/assets/cn_src_ranui_select_index.md.CFuezBAx.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Da6HnW_B.lean.js",
"/ran/assets/src_article_sort_heap_index.md.DUVkl6fy.js",
"/ran/assets/cn_src_ranui_radar_index.md.DLIxdWad.lean.js",
"/ran/assets/src_types_模式匹配.md.80KOUr-B.js",
"/ran/assets/src_article_imagemin.md.ChoyNt2j.lean.js",
"/ran/assets/src_article_sort_count_index.md.ec2i8FTY.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.dyyL6SXC.lean.js",
"/ran/assets/src_ranui_preview_index.md.DsdPQ5JF.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CJqM5IfO.lean.js",
"/ran/assets/src_types_模式匹配.md.80KOUr-B.lean.js",
"/ran/assets/src_article_designMode.md.DZc_qX7W.js",
"/ran/assets/src_ranui_player_index.md.DnEcoSqt.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.zG0GHeMZ.js",
"/ran/assets/cn_src_ranui_modal_index.md.BbiHElLB.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_ranuts_mimeType_mimeType.md.Doiui4gr.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BgCRrxSA.lean.js",
"/ran/assets/src_ranui_tab_index.md.Dd1ZmTtM.lean.js",
"/ran/assets/src_article_sort_radix_index.md.C3pf0lvW.js",
"/ran/assets/cn_src_ranui_modal_index.md.BbiHElLB.lean.js",
"/ran/assets/cn_index.md.DhNyCcIk.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranui_input_index.md.B7n1D35J.lean.js",
"/ran/assets/src_article_bundle.md.8AISrT5w.js",
"/ran/assets/src_ranui_tab_index.md.Dd1ZmTtM.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BGA6GfLu.js",
"/ran/assets/cn_index.md.DhNyCcIk.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.BT5PjgDa.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.ZOjaQ8kE.js",
"/ran/assets/inter-italic-greek.9J96vYpw.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.BDnbh4Ig.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Cvr4_7Ny.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CBEF6VYR.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.nlElx6aN.lean.js",
"/ran/assets/src_ranui_popover_index.md.KuYIYlyZ.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_index.md.C8BaH4NK.js",
"/ran/assets/src_ranuts_file_writeFile.md.lAAZywfh.lean.js",
"/ran/assets/src_ranui_radar_index.md.CykEjYyI.js",
"/ran/assets/cn_src_ranui_tabs_index.md.De7qV2j0.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CjgoBpyi.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BDVFLg-8.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.De7qV2j0.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_mode_subscribe.md.D9JsfYHY.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BqFYNzyP.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Cvr4_7Ny.lean.js",
"/ran/assets/src_ranui_icon_index.md.BeDCvfqD.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BKx8Y37h.js",
"/ran/assets/cn_src_ranui_radar_index.md.DLIxdWad.js",
"/ran/assets/src_article_sort_select_index.md.d89JL8gX.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BoDvX4bW.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.B-j9raPf.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.nlElx6aN.js",
"/ran/assets/src_article_typescript_unionType.md.Ba_cMdnJ.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.B-j9raPf.js",
"/ran/assets/cn_src_article_typescript_calculate.md.B_tNxbNu.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CcSnE0KD.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CrY_N2D_.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DQ7YUoZn.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.IMlCXJOQ.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranui_tab_index.md.aIpqikr3.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.B7n1D35J.js",
"/ran/assets/src_ranui_button_index.md.DL5ZIoL0.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BoDvX4bW.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.ClJShK2W.lean.js",
"/ran/assets/src_article_sort_select_index.md.d89JL8gX.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CkrtEsVw.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BLLP6LMH.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Bph69-YC.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranui_select_index.md.CFuezBAx.js",
"/ran/assets/inter-italic-vietnamese.DHNAd7Wr.woff2",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.VQHgC_fs.js",
"/ran/assets/src_types_类型运算.md.l5WnSfrB.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.TrSN98r_.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_article_babel.md.DUhZBNuh.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DpnjF7lg.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.IMlCXJOQ.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D9nwZ5Lv.js",
"/ran/assets/cn_src_article_sort_radix_index.md.s8TtRWtS.js",
"/ran/assets/src_article_typescript_unionType.md.Ba_cMdnJ.js",
"/ran/assets/src_ranuts_file_watchFile.md.DLXmd6ot.js",
"/ran/assets/src_ranui_image_index.md.ChcUsy_8.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.C7JmNnIG.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BCuRCRyh.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranui_button_index.md.8p_V_S66.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_sort_quick_index.md.Dq5Mwvbi.js",
"/ran/assets/cn_src_article_sort_shell_index.md.ekUhbEQz.js",
"/ran/assets/cn_src_article_bundle.md.DHu-Batd.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.D9JsfYHY.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.VQHgC_fs.lean.js",
"/ran/assets/src_article_sort_insert_index.md.BHQlNywR.lean.js",
"/ran/assets/src_types_TS类型.md.Dcr0lgJF.js",
"/ran/assets/cn_src_article_sort_index.md.Ba-gWbpG.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_javascript_domLoad.md.BT5PjgDa.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.5LjmoPg7.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CkrtEsVw.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CecdOuNh.js",
"/ran/assets/cn_src_ranui_button_index.md.8p_V_S66.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.BwKNGAht.lean.js",
"/ran/assets/index.md.BUsNCYHo.lean.js",
"/ran/assets/src_ranui_icon_index.md.BeDCvfqD.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/inter-roman-greek-ext.D0mI3NpI.woff2",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_count_index.md.ec2i8FTY.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BlIiPi11.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.ClJShK2W.js",
"/ran/assets/src_article_typescript_index.md.CpKXKUeo.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BN9kJw8E.js",
"/ran/assets/src_ranui_checkbox_index.md.Da6HnW_B.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BDiDE7p0.js",
"/ran/assets/cn_src_ranui_tab_index.md.aIpqikr3.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BKx8Y37h.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.BjMvDtBF.js",
"/ran/assets/src_article_typescript_index.md.CpKXKUeo.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_sort_index.md.iB4qzHMk.js",
"/ran/assets/cn_src_article_babel.md.DUhZBNuh.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.BmYJ2kSo.lean.js",
"/ran/assets/src_article_typescript_recursion.md.C6vDbISu.js",
"/ran/assets/cn_src_ranuts_utils_task.md.C8u3cm1i.lean.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/index.DKC1-TWx.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/index-ByJ7zZdQ.CdmPRwUT.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/pdf-B2a6ll8f.D2F7oUQU.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/framework.A_XI1Ui1.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/theme.C0RVR3fa.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/index-CZlEoE62.DjYDx5Id.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranui_progress_index.md.iM8d1Mm9.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BDiDE7p0.lean.js",
"/ran/assets/src_ranui_input_index.md.74Z45fSE.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BUZx_CKG.js",
"/ran/assets/src_ranui_select_index.md.DFWBaIiq.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_designMode.md.DZc_qX7W.lean.js",
"/ran/assets/src_article_sort_insert_index.md.BHQlNywR.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/inter-roman-cyrillic.CMhn1ESj.woff2",
"/ran/assets/src_article_sort_bubble_index.md.CHdFUNWp.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BGA6GfLu.lean.js",
"/ran/assets/src_ranuts_index.md.CQrK6RIi.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C2LZ3jQV.lean.js",
"/ran/assets/src_types_TS类型.md.Dcr0lgJF.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.401mbwtD.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_mimeType_mimeType.md.Doiui4gr.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CjgoBpyi.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_typescript_recursion.md.BDnbh4Ig.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BJ06sNLj.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.lAAZywfh.js",
"/ran/assets/cn_src_ranui_player_index.md.BLoHB1qs.js",
"/ran/assets/src_ranui_button_index.md.DL5ZIoL0.js",
"/ran/assets/src_article_sort_merge_index.md.DEiprtIg.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Daaf5rFe.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_sort_shell_index.md.6TPXyRiQ.js",
"/ran/assets/cn_src_types_高级类型.md.DCwawyw3.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.BjMvDtBF.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_sort_heap_index.md.DUVkl6fy.lean.js",
"/ran/assets/src_ranui_index.md.C8BaH4NK.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BMvnsEqO.lean.js",
"/ran/assets/src_ranui_progress_index.md.iM8d1Mm9.lean.js",
"/ran/assets/src_article_imagemin.md.ChoyNt2j.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BdxzocGs.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_ranuts_utils_getCookie.md.CikYi1fN.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CSG2ovaz.js",
"/ran/assets/src_types_高级类型.md.DxPwL0n4.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_modal_index.md.SleG_ote.js",
"/ran/assets/app.BnS6E7Av.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_typescript_pattern.md.BgCRrxSA.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DwUE8AFe.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_message_index.md.Btu0aq3b.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DkjKkhVw.lean.js",
"/ran/assets/src_types_类型运算.md.l5WnSfrB.js",
"/ran/assets/src_ranuts_file_readFile.md.o-37w93d.js",
"/ran/assets/cn_src_ranui_icon_index.md.FZIHPwc9.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.CLMb_OWn.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DwUE8AFe.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.ZOjaQ8kE.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.D_eY14qz.js",
"/ran/assets/cn_src_ranui_progress_index.md.BijmgDR2.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Bph69-YC.js",
"/ran/assets/src_article_sort_bubble_index.md.CHdFUNWp.lean.js",
"/ran/assets/style.CtNi5NRP.css",
"/ran/assets/src_article_typescript_calculate.md.C0thaQOM.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CecdOuNh.lean.js",
"/ran/assets/inter-roman-latin-ext.ZlYT4o7i.woff2",
"/ran/assets/inter-roman-greek.JvnBZ4YD.woff2",
"/ran/assets/src_article_babel.md.D1zTdcrI.js",
"/ran/assets/src_article_typescript_recursion.md.C6vDbISu.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DFRlfk0K.js",
"/ran/assets/src_ranui_modal_index.md.SleG_ote.lean.js",
"/ran/assets/src_ranui_input_index.md.74Z45fSE.js",
"/ran/assets/cn_src_types_模式匹配.md.D_eY14qz.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranuts_binaryTree_index.md.DGjkamBC.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BdxzocGs.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D9nwZ5Lv.lean.js",
"/ran/assets/src_article_functionalProgramming.md.DWaI1-WW.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_icon_index.md.FZIHPwc9.js",
"/ran/assets/cn_src_types_类型运算.md.BGFfSz3k.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_article_typescript_calculate.md.B_tNxbNu.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BqFYNzyP.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BJ06sNLj.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BDVFLg-8.js",
"/ran/assets/cn_src_ranui_index.md.ZqgBy25h.lean.js",
"/ran/assets/inter-italic-latin.DbsTr1gm.woff2",
"/ran/assets/src_ranui_skeleton_index.md.uhvbrnSF.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_bundle.md.8AISrT5w.lean.js",
"/ran/assets/src_article_sort_radix_index.md.C3pf0lvW.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.C8u3cm1i.js",
"/ran/assets/cn_src_types_类型运算.md.BGFfSz3k.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DUEmKGyn.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.zG0GHeMZ.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.TrSN98r_.js",
"/ran/assets/inter-roman-cyrillic-ext.DxP3Awbn.woff2",
"/ran/assets/src_article_sort_bucket_index.md.BUZx_CKG.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.CLMb_OWn.js",
"/ran/assets/cn_src_article_typescript_index.md.DUmJDGts.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BCuRCRyh.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/inter-italic-greek-ext.CHOfFY1k.woff2",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_sort_merge_index.md.CcSnE0KD.js",
"/ran/assets/inter-roman-vietnamese.ClpjcLMQ.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.GHtRrzQL.js",
"/ran/assets/src_ranuts_file_readFile.md.o-37w93d.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.5XJwZIOp.woff2",
"/ran/assets/cn_src_ranui_player_index.md.BLoHB1qs.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DEiprtIg.js",
"/ran/assets/src_article_babel.md.D1zTdcrI.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BLLP6LMH.js",
"/ran/assets/index.md.BUsNCYHo.js",
"/ran/assets/src_ranui_player_index.md.DnEcoSqt.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_index.md.CQrK6RIi.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.401mbwtD.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DFRlfk0K.lean.js",
"/ran/screenshots_748x1340.jpg",
"/ran/home.svg",
"/ran/icon_144.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/manifest.json",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/icon.png",
"/ran/icon_72.png",
"/ran/sw.js",
"/ran/icon_168.png",
"/ran/hashmap.json",
];
const VERSION = "1711713526";
const CACHE_NAME = 'chaxus_ran_' + VERSION

/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url, method } = request
    const { status } = fetchedResponse
    const ignoreRequest = [
        // google 上报不需要缓存
        'google',
        // 插件请求不用缓存
        'chrome-extension',
        // 百度的请求不用缓存
        'baidu.com',
        'blob:',
    ]
    // 只缓存状态码为 200 的请求
    if(status !== 200) return
    // 只缓存 get 请求
    if (!ignoreRequest.some(item => url.includes(item)) && method === 'GET') {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service work update cache error:', error, request)
        })
    }
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const responseFromCache = await caches.match(request);
        // 如果缓存中有，依然去请求，异步更新缓存资源，同步返回已经缓存的资源
        if (responseFromCache) {
            // fetch(request).then(fetchedResponse => {
            //     updateCache(fetchedResponse, request)
            // }).catch(error => {
            //     console.log('cache first fetch error:', error);
            // })
            return responseFromCache
        }
        // 如果缓存中没有，就从网络中请求
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        console.log('cacheFirst', error)
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('deleteCache', error)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('deleteOldCaches', deleteOldCaches)
    }

};

this.addEventListener('install', function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败
            // 可以使用 cache.add
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service work fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service work fetch error:', url, error);
                })
            )
        })
    );
});

this.addEventListener("fetch", (event) => {
    // 拦截请求
    try {
        const responseFromServer = cacheFirst(event.request)
        if (responseFromServer?.clone) {
            event.respondWith(responseFromServer);
        }
    } catch (error) {
        console.log('service work self fetch error:', error, event)
    }
});

this.addEventListener("activate", (event) => {
    event.waitUntil(deleteOldCaches());
});



