const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/404.html",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/index.html",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_192.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/babel.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_86caad9.pf_fragment",
"/ran/pagefind/fragment/en_4c54dcd.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c5c948b.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4aa3033.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_21aa409.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1d676ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e8d7fb5.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_56bf7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2320816.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7135acd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9bb27f9.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e712c2f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9919be9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bb4f399.pf_fragment",
"/ran/pagefind/fragment/zh-cn_63cce06.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7404f9.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5cb0744.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7785c3.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2186e18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fca9594.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a91af19.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ae66cea.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_a4c51e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cc13270.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b736c83.pf_fragment",
"/ran/pagefind/fragment/zh-cn_90c7194.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e85c0d6.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1404275.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62c4e29.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5995.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6e3ea19.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b5d6ea8.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48a39a0.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_16fb727.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac43f88.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c5b442.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2e59c37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3130d28.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_578e3e5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9e1b73b.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6d2c22.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f8b7d53.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f521899.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_519fac2.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/index/en_ffacaef.pf_index",
"/ran/pagefind/index/en_3470995.pf_index",
"/ran/pagefind/index/zh-cn_5a8e9e2.pf_index",
"/ran/pagefind/index/zh-cn_af68a82.pf_index",
"/ran/pagefind/index/zh-cn_5521b2b.pf_index",
"/ran/pagefind/index/zh-cn_1d413b7.pf_index",
"/ran/pagefind/index/en_cb49e1f.pf_index",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind.en_432fc5d0c0.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.zh-cn_196dccd3f9a37.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.js",
"/ran/icon_96.png",
"/ran/icon_48.png",
"/ran/assets/src_ranui_image_index.md.CqYXG1ub.js",
"/ran/assets/cn_src_article_imagemin.md.D5TbdHWr.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BS11Kdu3.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CHZSdBUB.lean.js",
"/ran/assets/src_ranui_icon_index.md.De5RZWlQ.lean.js",
"/ran/assets/cn_src_article_bundle.md.xCZLV54M.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DZq1e6N9.js",
"/ran/assets/src_article_sort_count_index.md.CadxIM-3.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.DrEpEiln.lean.js",
"/ran/assets/src_ranui_radar_index.md.DQ5tQfQd.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Ce_Fi4fj.js",
"/ran/assets/src_article_typescript_recursion.md.D1oyPfL3.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.B3yeNjWF.js",
"/ran/assets/src_ranui_preview_index.md.DIiZSxQM.lean.js",
"/ran/assets/inter-roman-latin.Bu8hRsVA.woff2",
"/ran/assets/inter-italic-latin-ext.BGcWXLrn.woff2",
"/ran/assets/cn_src_ranui_player_index.md.CTjsgXbB.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C7KEaWAk.js",
"/ran/assets/src_article_sort_quick_index.md.BabFmUsw.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_sort_heap_index.md.GKhI_SeO.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Ocx3jrYD.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D2eFPASQ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.CQcZ5QHc.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.JYMIsOOS.js",
"/ran/assets/src_article_typescript_reconstruction.md.1GxCm8RJ.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DT4jxXKO.lean.js",
"/ran/assets/inter-italic-cyrillic.D6csxwjC.woff2",
"/ran/assets/src_types_TS类型.md.CMcQx3U-.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DhhYR5wa.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Be41hmAp.lean.js",
"/ran/assets/src_article_typescript_unionType.md.Debw_i4j.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.Dp8B1w06.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BmBCYgKI.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C4QpcicG.lean.js",
"/ran/assets/cn_src_article_imagemin.md.D5TbdHWr.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.CbkKcUjN.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.XopTgcML.js",
"/ran/assets/cn_src_ranui_select_index.md.DbGbHus8.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BRr7nHQ_.js",
"/ran/assets/cn_src_article_sort_select_index.md.CGLqCXq9.js",
"/ran/assets/src_article_typescript_reconstruction.md.1GxCm8RJ.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CzNKb2q0.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CsCvDeoR.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.CWB4X3Cs.js",
"/ran/assets/cn_src_ranui_message_index.md.CsJ6g1BM.lean.js",
"/ran/assets/src_article_typescript_index.md.C_dp_Ja0.js",
"/ran/assets/src_ranuts_index.md.51x9P6Ph.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.COShYYn7.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Dxcj-9W9.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.DjdRLejS.js",
"/ran/assets/src_types_类型运算.md.D0uC7WSR.js",
"/ran/assets/src_ranui_preview_index.md.DIiZSxQM.js",
"/ran/assets/src_ranui_tabs_index.md.DltfdQG_.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.C4h6GmbV.js",
"/ran/assets/cn_src_ranui_input_index.md.D-hTWuSy.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_babel.md.EqozUDjO.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C7HAk_5F.lean.js",
"/ran/assets/src_types_模式匹配.md.DUIxufJn.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BwGQKC14.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CVqDoc5J.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BdighuBY.js",
"/ran/assets/src_ranuts_file_watchFile.md.B4BCu4dV.js",
"/ran/assets/src_article_sort_heap_index.md.Cvfwhblb.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_button_index.md.DhMKQfw5.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_designMode.md.BUWhJ8ym.js",
"/ran/assets/src_ranuts_utils_task.md.DyzD1b5C.js",
"/ran/assets/inter-italic-greek.9J96vYpw.woff2",
"/ran/assets/src_ranuts_file_writeFile.md.4LMlq8HF.js",
"/ran/assets/cn_src_types_类型运算.md.CQcZ5QHc.js",
"/ran/assets/src_ranui_message_index.md.CWZ3g9da.js",
"/ran/assets/src_article_sort_merge_index.md.BMr3Ydz4.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_sort_heap_index.md.Cvfwhblb.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DvT8yH7y.js",
"/ran/assets/cn_src_article_sort_index.md.C20fx4Ur.js",
"/ran/assets/app.DcMofxVa.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_sort_insert_index.md.Cx8T5hiR.lean.js",
"/ran/assets/src_ranui_progress_index.md.DBv2yo0O.js",
"/ran/assets/src_article_sort_insert_index.md.Cx8T5hiR.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DhhYR5wa.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.QmNVGc9Q.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C7KEaWAk.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C4QpcicG.js",
"/ran/assets/src_article_sort_merge_index.md.BMr3Ydz4.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DaHLDnn4.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.DiO46q_N.js",
"/ran/assets/src_article_sort_shell_index.md.BJvXSUUn.js",
"/ran/assets/src_ranuts_file_appendFile.md.BwhFe_Is.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranui_player_index.md.Ucade6Ub.lean.js",
"/ran/assets/index.md.D3UlMiai.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C09IL4pC.js",
"/ran/assets/cn_src_ranui_icon_index.md.DS-Z8PuJ.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CnZOnY_f.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Ocx3jrYD.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C7hq7l2f.js",
"/ran/assets/src_ranuts_file_appendFile.md.BwhFe_Is.js",
"/ran/assets/src_types_模式匹配.md.DUIxufJn.lean.js",
"/ran/assets/src_article_sort_quick_index.md.BabFmUsw.lean.js",
"/ran/assets/src_ranui_button_index.md.DhMKQfw5.lean.js",
"/ran/assets/cn_src_ranui_index.md.DuGHWjOh.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DOiBqdQX.lean.js",
"/ran/assets/src_ranui_icon_index.md.De5RZWlQ.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_article_typescript_pattern.md.D0fthn_o.js",
"/ran/assets/inter-italic-vietnamese.DHNAd7Wr.woff2",
"/ran/assets/src_ranuts_file_watchFile.md.B4BCu4dV.lean.js",
"/ran/assets/src_article_functionalProgramming.md.CFviMWKs.js",
"/ran/assets/src_ranui_image_index.md.CqYXG1ub.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CGLqCXq9.lean.js",
"/ran/assets/src_ranui_progress_index.md.DBv2yo0O.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DJ1Q7KAr.js",
"/ran/assets/src_ranuts_utils_getCookie.md.XbM2sQnP.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DT4jxXKO.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_article_sort_select_index.md.BRHLiyk-.js",
"/ran/assets/cn_src_ranui_popover_index.md.CMhgMfqj.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Be41hmAp.js",
"/ran/assets/src_ranuts_bundler_index.md.DJ1Q7KAr.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BS11Kdu3.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranui_icon_index.md.DS-Z8PuJ.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_types_TS类型.md.ty_FuwJh.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CDK2GmuZ.js",
"/ran/assets/src_article_sort_index.md.CwtMIewb.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.-nkktJ6s.js",
"/ran/assets/src_ranui_index.md.DLMsClTF.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.C4h6GmbV.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_article_typescript_calculate.md.C09IL4pC.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_sort_bucket_index.md._IS3Ro9Z.js",
"/ran/assets/src_ranuts_utils_filterObj.md.hV-6cDcx.js",
"/ran/assets/src_article_imagemin.md.BJSrRWAM.js",
"/ran/assets/src_ranui_skeleton_index.md.kkAF2BRC.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranui_select_index.md.jBwPbgTC.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranui_popover_index.md.D4S33uDf.js",
"/ran/assets/src_ranui_input_index.md.BtoANsFy.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.B3yeNjWF.lean.js",
"/ran/assets/src_article_babel.md.C0vHbAiQ.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_article_typescript_recursion.md.D1oyPfL3.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.ZzbyFat1.js",
"/ran/assets/inter-roman-greek-ext.D0mI3NpI.woff2",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_functionalProgramming.md.CFviMWKs.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DaHLDnn4.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BwGQKC14.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DvT8yH7y.lean.js",
"/ran/assets/src_article_sort_index.md.CwtMIewb.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranui_skeleton_index.md.kkAF2BRC.lean.js",
"/ran/assets/src_article_imagemin.md.BJSrRWAM.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.DhaY28RT.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DZq1e6N9.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Ce_Fi4fj.lean.js",
"/ran/assets/cn_src_ranui_index.md.DuGHWjOh.lean.js",
"/ran/assets/src_article_typescript_pattern.md.D0fthn_o.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.C08DJD6I.js",
"/ran/assets/cn_src_ranui_input_index.md.D-hTWuSy.lean.js",
"/ran/assets/src_article_sort_select_index.md.BRHLiyk-.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranui_index.md.DLMsClTF.js",
"/ran/assets/src_ranui_message_index.md.CWZ3g9da.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BJvXSUUn.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.CWB4X3Cs.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.Dnr48zMU.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.C-XtgvkN.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CsCvDeoR.js",
"/ran/assets/cn_src_article_sort_merge_index.md.ujNup3Az.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CsJ6g1BM.js",
"/ran/assets/cn_src_ranui_image_index.md.DRDPffeE.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BDIOTjDY.lean.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/pdf-B2a6ll8f.Be-ad9qj.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/theme.DmfopMFz.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/framework.A_XI1Ui1.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/index.CZ1tdOOT.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/index-ByJ7zZdQ.yYIBMgFO.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/index-CZlEoE62.DjYDx5Id.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.CbkKcUjN.js",
"/ran/assets/src_ranuts_index.md.51x9P6Ph.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.BNKNlU1X.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.Dnr48zMU.lean.js",
"/ran/assets/src_ranui_tab_index.md.BRTGh1lK.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_checkbox_index.md.6ihzTra9.js",
"/ran/assets/src_types_TS类型.md.CMcQx3U-.js",
"/ran/assets/cn_index.md.DNLX5nQq.lean.js",
"/ran/assets/inter-roman-cyrillic.CMhn1ESj.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.QmNVGc9Q.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BRr7nHQ_.lean.js",
"/ran/assets/src_article_babel.md.C0vHbAiQ.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DOiBqdQX.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranui_checkbox_index.md.COShYYn7.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_article_typescript_unionType.md.Debw_i4j.js",
"/ran/assets/cn_src_types_模式匹配.md.DiO46q_N.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_designMode.md.BUWhJ8ym.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.r_W0E1cB.lean.js",
"/ran/assets/cn_src_article_designMode.md.CCoG6oun.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_javascript_domLoad.md.BCYnIfYk.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CHeheyrQ.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D2eFPASQ.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.r_W0E1cB.js",
"/ran/assets/src_ranui_radar_index.md.DQ5tQfQd.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_checkbox_index.md.6ihzTra9.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C7hq7l2f.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DQV_b0j_.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_utils_task.md.DQV_b0j_.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C7HAk_5F.js",
"/ran/assets/cn_src_ranuts_index.md.CbBcSJw4.lean.js",
"/ran/assets/src_ranui_input_index.md.BtoANsFy.lean.js",
"/ran/assets/src_ranui_modal_index.md.CVURiiLJ.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.311-HUJI.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.XbM2sQnP.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CnZOnY_f.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_article_astParse_tokenizer.md.DS_zA4RM.js",
"/ran/assets/cn_src_ranui_tabs_index.md.C08DJD6I.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.XopTgcML.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BmBCYgKI.js",
"/ran/assets/cn_src_ranui_radar_index.md.ZzbyFat1.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CHeheyrQ.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DCGX1WXX.js",
"/ran/assets/src_ranuts_file_readDir.md.DhaY28RT.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CVqDoc5J.js",
"/ran/assets/cn_src_article_sort_merge_index.md.ujNup3Az.js",
"/ran/assets/cn_src_ranui_button_index.md.BdighuBY.lean.js",
"/ran/assets/style.CtNi5NRP.css",
"/ran/assets/cn_src_types_高级类型.md.DCGX1WXX.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.xaLtRcX7.js",
"/ran/assets/inter-roman-latin-ext.ZlYT4o7i.woff2",
"/ran/assets/src_ranuts_binaryTree_index.md.CHZSdBUB.js",
"/ran/assets/inter-roman-greek.JvnBZ4YD.woff2",
"/ran/assets/src_article_sort_radix_index.md.eVVV3LPu.js",
"/ran/assets/src_article_typescript_index.md.C_dp_Ja0.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranuts_file_writeFile.md.4LMlq8HF.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_index.md.DNLX5nQq.js",
"/ran/assets/src_ranui_popover_index.md.D4S33uDf.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.C-XtgvkN.lean.js",
"/ran/assets/src_types_高级类型.md.ESdhcYls.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.xaLtRcX7.lean.js",
"/ran/assets/src_ranui_modal_index.md.CVURiiLJ.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_sort_bubble_index.md.311-HUJI.js",
"/ran/assets/cn_src_ranui_popover_index.md.CMhgMfqj.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.BCYnIfYk.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.Dp8B1w06.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DS_zA4RM.lean.js",
"/ran/assets/src_types_类型运算.md.D0uC7WSR.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Dxcj-9W9.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BDIOTjDY.js",
"/ran/assets/src_article_typescript_calculate.md.Cnfm-azN.lean.js",
"/ran/assets/cn_src_article_babel.md.EqozUDjO.js",
"/ran/assets/cn_src_article_sort_index.md.C20fx4Ur.lean.js",
"/ran/assets/src_ranui_tabs_index.md.DltfdQG_.js",
"/ran/assets/inter-italic-latin.DbsTr1gm.woff2",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranuts_utils_task.md.DyzD1b5C.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CzNKb2q0.js",
"/ran/assets/src_article_bundle.md.BATnqkJM.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.hV-6cDcx.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CTjsgXbB.lean.js",
"/ran/assets/index.md.D3UlMiai.js",
"/ran/assets/cn_src_article_sort_heap_index.md.GKhI_SeO.lean.js",
"/ran/assets/src_article_typescript_calculate.md.Cnfm-azN.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/inter-roman-cyrillic-ext.DxP3Awbn.woff2",
"/ran/assets/cn_src_ranuts_index.md.CbBcSJw4.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DLslkbXR.js",
"/ran/assets/src_types_高级类型.md.ESdhcYls.js",
"/ran/assets/cn_src_article_bundle.md.xCZLV54M.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DA0nHw-j.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_image_index.md.DRDPffeE.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.JYMIsOOS.lean.js",
"/ran/assets/src_ranui_player_index.md.Ucade6Ub.js",
"/ran/assets/src_article_sort_count_index.md.CadxIM-3.js",
"/ran/assets/src_ranui_select_index.md.jBwPbgTC.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DLslkbXR.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_article_sort_bucket_index.md._IS3Ro9Z.lean.js",
"/ran/assets/inter-italic-greek-ext.CHOfFY1k.woff2",
"/ran/assets/cn_src_article_designMode.md.CCoG6oun.lean.js",
"/ran/assets/cn_src_types_TS类型.md.ty_FuwJh.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/inter-roman-vietnamese.ClpjcLMQ.woff2",
"/ran/assets/src_ranuts_utils_formatJson.md.CDK2GmuZ.lean.js",
"/ran/assets/src_ranui_tab_index.md.BRTGh1lK.js",
"/ran/assets/src_ranuts_file_readFile.md.-nkktJ6s.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.5XJwZIOp.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.DrEpEiln.js",
"/ran/assets/cn_src_ranui_preview_index.md.DjdRLejS.lean.js",
"/ran/assets/src_article_sort_radix_index.md.eVVV3LPu.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.DbGbHus8.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_sort_insert_index.md.DA0nHw-j.js",
"/ran/assets/src_article_bundle.md.BATnqkJM.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.BNKNlU1X.lean.js",
"/ran/screenshots_748x1340.jpg",
"/ran/home.svg",
"/ran/icon_144.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/manifest.json",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/icon.png",
"/ran/icon_72.png",
"/ran/sw.js",
"/ran/icon_168.png",
"/ran/hashmap.json",
];
const VERSION = "1711791936";
const CACHE_NAME = 'chaxus_ran_' + VERSION

/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url, method } = request
    const { status } = fetchedResponse
    const ignoreRequest = [
        // google 上报不需要缓存
        'google',
        // 插件请求不用缓存
        'chrome-extension',
        // 百度的请求不用缓存
        'baidu.com',
        'blob:',
    ]
    // 只缓存状态码为 200 的请求
    if(status !== 200) return
    // 只缓存 get 请求
    if (!ignoreRequest.some(item => url.includes(item)) && method === 'GET') {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service work update cache error:', error, request)
        })
    }
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const responseFromCache = await caches.match(request);
        // 如果缓存中有，依然去请求，异步更新缓存资源，同步返回已经缓存的资源
        if (responseFromCache) {
            // fetch(request).then(fetchedResponse => {
            //     updateCache(fetchedResponse, request)
            // }).catch(error => {
            //     console.log('cache first fetch error:', error);
            // })
            return responseFromCache
        }
        // 如果缓存中没有，就从网络中请求
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        console.log('cacheFirst', error, request)
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('deleteCache', error)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('deleteOldCaches', deleteOldCaches)
    }

};

this.addEventListener('install', function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败
            // 可以使用 cache.add
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service work fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service work fetch error:', url, error);
                })
            )
        })
    );
});

this.addEventListener("fetch", (event) => {
    // 拦截请求
    try {
        const responseFromServer = cacheFirst(event.request)
        if (responseFromServer?.clone) {
            event.respondWith(responseFromServer);
        }
    } catch (error) {
        console.log('service work self fetch error:', error, event)
    }
});

this.addEventListener("activate", (event) => {
    event.waitUntil(deleteOldCaches());
});



