const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_192.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/icon_96.png",
"/ran/hashmap.json",
"/ran/sw1732978960.js",
"/ran/icon.png",
"/ran/screenshots_748x1340.jpg",
"/ran/assets/src_ranuts_mode_subscribe.md.DJ-QdIcQ.js",
"/ran/assets/cn_src_article_typescript_index.md.Bs6EHCbO.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.B21tBdQl.lean.js",
"/ran/assets/cn_src_article_visual.md.D2tMhxfk.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranuts_utils_filterObj.md.BiDNKxra.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DP4YWWzG.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DCmqE5E6.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranuts_bundler_index.md.5w-rzSsv.js",
"/ran/assets/src_ranui_icon_index.md.BOiA2emr.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BRWJ-Asm.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.xw1bfdK5.lean.js",
"/ran/assets/cn_src_article_video.md.Bzzgzd1w.js",
"/ran/assets/src_ranui_preview_index.md.A38Vx8wt.lean.js",
"/ran/assets/cn_index.md.p2v_-Oc5.js",
"/ran/assets/cn_src_ranui_input_index.md.DCmqE5E6.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BS4kqcwk.lean.js",
"/ran/assets/src_ranui_loading_index.md.B_57KT0D.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CC_ojfok.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_utils_filterObj.md.BiDNKxra.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DiY0_Kvg.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.B5NvmwaQ.lean.js",
"/ran/assets/src_ranui_button_index.md.D7FTyhTe.js",
"/ran/assets/src_article_sort_heap_index.md.C7kpb1ew.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BRWJ-Asm.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.C7P05JKS.js",
"/ran/assets/src_ranui_checkbox_index.md.Bk073CYh.js",
"/ran/assets/src_article_babel.md.Cgq1ifix.js",
"/ran/assets/cn_src_ranui_popover_index.md.DN_tVX7Q.lean.js",
"/ran/assets/cn_src_article_babel.md.BWkHVdRp.js",
"/ran/assets/src_ranui_icon_index.md.BOiA2emr.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.JJuJsKBY.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_article_javascript_domLoad.md.ZhFbf1VB.js",
"/ran/assets/src_article_sort_select_index.md.ByKKVqRW.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranui_modal_index.md.BpD_5pjb.lean.js",
"/ran/assets/src_ranuts_utils_task.md.zsN8wfCt.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.6TupNgia.js",
"/ran/assets/src_article_designMode.md.tPDe0q1u.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BG4LuUZl.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/app.iA4TEdI6.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DP4YWWzG.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CHcnlxrj.lean.js",
"/ran/assets/src_ranui_input_index.md.B9H_PF51.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B6yWYRqS.lean.js",
"/ran/assets/src_article_functionalProgramming.md.BGfpOoJ6.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranui_image_index.md.BeKIY6Zz.js",
"/ran/assets/src_article_typescript_calculate.md.B2Mlxf47.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_file_readFile.md.Dwhqoh-X.lean.js",
"/ran/assets/src_article_sort_count_index.md.BEMJUCY0.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.JJuJsKBY.lean.js",
"/ran/assets/cn_index.md.p2v_-Oc5.lean.js",
"/ran/assets/style.Cf0GkCW3.css",
"/ran/assets/src_article_typescript_recursion.md.B9Y9ytFS.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranuts_file_readDir.md.Bwnrzpn_.js",
"/ran/assets/src_ranui_math_index.md.DkUqkya_.js",
"/ran/assets/src_ranuts_utils_task.md.zsN8wfCt.js",
"/ran/assets/src_types_高级类型.md.BRuDmkR9.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_ranui_popover_index.md.DSEY3Ihy.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.GY07Gd4J.lean.js",
"/ran/assets/src_article_sort_merge_index.md.dy2dA5_4.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DeOE5BME.js",
"/ran/assets/src_article_sort_bubble_index.md.DdUWL6cu.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CdfZ0j0z.js",
"/ran/assets/src_ranui_checkbox_index.md.Bk073CYh.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.Tn4YAM93.lean.js",
"/ran/assets/src_article_typescript_recursion.md.B9Y9ytFS.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D4kOsLLP.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_ranui_modal_index.md.BpD_5pjb.js",
"/ran/assets/src_article_typescript_unionType.md.BaK8c9Pn.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_article_javascript_domLoad.md.yswrZQgf.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_sort_radix_index.md.CITw1xTb.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.Bs6EHCbO.js",
"/ran/assets/src_types_类型运算.md.C9Y5moRj.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.uGnU60Fp.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.DmCvjBxR.js",
"/ran/assets/cn_src_types_高级类型.md.D-0PfmOh.lean.js",
"/ran/assets/src_ranui_select_index.md.CeuhI6As.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CvxPDg-v.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranuts_file_writeFile.md.CrmbwIYg.lean.js",
"/ran/assets/src_types_模式匹配.md.DoUhVDCY.js",
"/ran/assets/cn_src_ranui_progress_index.md.xPxo2foG.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_article_javascript_domLoad.md.yswrZQgf.lean.js",
"/ran/assets/cn_src_article_docPreview.md.DP39twp2.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CJ_j4icw.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.m6dRhxQR.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CJ-nl2Af.js",
"/ran/assets/src_article_sort_quick_index.md.tcDfqetl.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.FCy2s1fU.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_bundler_index.md.CdLDqcju.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BGjs-3Ud.lean.js",
"/ran/assets/src_article_babel.md.Cgq1ifix.lean.js",
"/ran/assets/cn_src_types_TS类型.md.DjwHvO2J.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_heap_index.md.C7oPwjm2.js",
"/ran/assets/src_ranui_input_index.md.B9H_PF51.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DJ-QdIcQ.lean.js",
"/ran/assets/src_ranui_select_index.md.CeuhI6As.js",
"/ran/assets/cn_src_article_imagemin.md.Db78BBAe.js",
"/ran/assets/src_article_typescript_index.md.DabKujUa.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranuts_file_watchFile.md.D8HyM05Z.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DkLVe1oB.lean.js",
"/ran/assets/src_article_imagemin.md.DQU6uCZ_.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BBmiGAgY.js",
"/ran/assets/src_types_模式匹配.md.DoUhVDCY.lean.js",
"/ran/assets/cn_src_note_docker.md.DkcjGhjN.js",
"/ran/assets/src_article_imagemin.md.DQU6uCZ_.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_functionalProgramming.md.BGfpOoJ6.js",
"/ran/assets/cn_src_ranui_player_index.md.iunjbuxu.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_ranui_image_index.md.CNzEOgqD.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DZBrq7DD.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranui_radar_index.md.xRFjNAdB.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.Bns3Q-xD.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Den7Escp.lean.js",
"/ran/assets/src_ranui_player_index.md.U6BXHlCz.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.CU_6X3qX.js",
"/ran/assets/cn_src_article_video.md.Bzzgzd1w.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranuts_utils_getCookie.md.D8TQUX9X.js",
"/ran/assets/cn_src_article_typescript_unionType.md.ei98ah_E.js",
"/ran/assets/src_article_typescript_reconstruction.md.B21tBdQl.js",
"/ran/assets/src_ranuts_file_appendFile.md.WUPbkov0.js",
"/ran/assets/src_ranui_button_index.md.D7FTyhTe.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranui_message_index.md.CIJo0qDv.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CvxPDg-v.lean.js",
"/ran/assets/cn_src_types_高级类型.md.D-0PfmOh.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.FHn44HaZ.js",
"/ran/assets/cn_src_article_sort_select_index.md.GY07Gd4J.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B56eUGEY.js",
"/ran/assets/cn_src_ranui_loading_index.md.4521sPfY.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CdfZ0j0z.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.Bns3Q-xD.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_typescript_calculate.md.DkLVe1oB.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.B9cnIYe1.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_article_sort_index.md.CZn-_bxI.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.D8TQUX9X.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DiY0_Kvg.js",
"/ran/assets/src_ranui_tab_index.md.C0K71N_5.js",
"/ran/assets/cn_src_ranuts_index.md.C-ae9a1_.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.BxFL6eyB.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.D_AVJkP4.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.35rLwsiK.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CCMK4Od2.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_icon_index.md.BIAlu3fE.js",
"/ran/assets/cn_src_ranui_radar_index.md.DizboFr-.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CBDjYrE1.js",
"/ran/assets/src_article_sort_radix_index.md.D4oPwi-u.lean.js",
"/ran/assets/cn_src_article_bundle.md.CjX9buXL.js",
"/ran/assets/src_ranuts_utils_formatJson.md.1uBK37jq.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Blt4SINR.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CC_ojfok.lean.js",
"/ran/assets/src_types_高级类型.md.BRuDmkR9.lean.js",
"/ran/assets/cn_src_ranui_index.md.Doketeqt.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_sort_radix_index.md.D4oPwi-u.js",
"/ran/assets/cn_src_types_TS类型.md.DjwHvO2J.lean.js",
"/ran/assets/cn_src_article_imagemin.md.Db78BBAe.lean.js",
"/ran/assets/src_ranui_modal_index.md.N7gC74eU.js",
"/ran/assets/cn_src_article_babel.md.BWkHVdRp.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_article_sort_index.md.B36sgS0L.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_types_模式匹配.md.BvtdrSBn.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_types_TS类型.md.DdczaFUx.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.VHIW0NZH.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_heap_index.md.C7kpb1ew.js",
"/ran/assets/src_article_bundle.md.vesWHFDE.js",
"/ran/assets/cn_src_article_typescript_unionType.md.ei98ah_E.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.D8HyM05Z.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BxFL6eyB.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cj9xnhAo.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_sort_bucket_index.md.BTKGK7Nk.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CHcnlxrj.js",
"/ran/assets/src_ranui_popover_index.md.DSEY3Ihy.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CITw1xTb.js",
"/ran/assets/cn_src_ranui_index.md.Doketeqt.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_bundler_index.md.CdLDqcju.js",
"/ran/assets/src_ranui_progress_index.md.BKC6yTxp.js",
"/ran/assets/src_ranuts_index.md.BLqcrepc.js",
"/ran/assets/src_ranui_player_index.md.U6BXHlCz.js",
"/ran/assets/src_ranui_tabs_index.md.86Hf45HN.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_sort_heap_index.md.C7oPwjm2.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.Dwhqoh-X.js",
"/ran/assets/src_article_sort_merge_index.md.dy2dA5_4.js",
"/ran/assets/cn_src_article_sort_index.md.CZn-_bxI.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_index.md.DabKujUa.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.B9cnIYe1.lean.js",
"/ran/assets/src_article_typescript_calculate.md.B2Mlxf47.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_bundle.md.CjX9buXL.lean.js",
"/ran/assets/src_article_sort_count_index.md.BEMJUCY0.js",
"/ran/assets/src_article_astParse_tokenizer.md.CU_6X3qX.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CmTWQZZh.js",
"/ran/assets/src_article_sort_insert_index.md.BZ_btJFB.js",
"/ran/assets/cn_src_note_centos.md.LVHpEJ2P.js",
"/ran/assets/cn_src_ranui_math_index.md.FCy2s1fU.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranui_radar_index.md.xRFjNAdB.js",
"/ran/assets/src_ranui_progress_index.md.BKC6yTxp.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D_AVJkP4.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_index.md.BLqcrepc.lean.js",
"/ran/assets/src_article_bundle.md.vesWHFDE.lean.js",
"/ran/assets/index.md.CtAMyOAr.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BairM8Ym.lean.js",
"/ran/assets/cn_src_article_visual.md.D2tMhxfk.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/index.md.CtAMyOAr.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CCMK4Od2.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BS4kqcwk.js",
"/ran/assets/src_article_sort_select_index.md.ByKKVqRW.js",
"/ran/assets/cn_src_note_docker.md.DkcjGhjN.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_note_ubuntu.md.Blt4SINR.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranui_player_index.md.iunjbuxu.js",
"/ran/assets/src_ranui_image_index.md.BeKIY6Zz.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.6TupNgia.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.VtPsIxPR.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CmTWQZZh.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.VHIW0NZH.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cj9xnhAo.js",
"/ran/assets/cn_src_article_sort_count_index.md.DeOE5BME.lean.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/pwa-install.es.DxPypONK.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/VPLocalSearchBox.DVPCGrL1.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/@localSearchIndexcn.C418tsNc.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.D_QMH63x.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/theme.D0kvJ-tr.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/index-Co9E57uv.CiCYG7iV.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index.C-Vyx4L7.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/@localSearchIndexroot.CtCQ-DCf.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/framework.BV76-6_x.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/index-Ba501-HG.BSa37V-A.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.BFSOJ_Dg.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_types_TS类型.md.DdczaFUx.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.VtPsIxPR.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D4kOsLLP.js",
"/ran/assets/src_article_sort_bubble_index.md.DdUWL6cu.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B56eUGEY.lean.js",
"/ran/assets/cn_src_ranuts_index.md.C-ae9a1_.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BG4LuUZl.js",
"/ran/assets/cn_src_ranui_icon_index.md.BIAlu3fE.lean.js",
"/ran/assets/src_ranui_math_index.md.DkUqkya_.lean.js",
"/ran/assets/src_ranui_preview_index.md.A38Vx8wt.js",
"/ran/assets/cn_src_ranui_progress_index.md.xPxo2foG.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.C7P05JKS.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.fjlEHNSA.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.m6dRhxQR.js",
"/ran/assets/src_article_typescript_pattern.md.CIxoWe3N.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CJ-nl2Af.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.BJykMunn.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_index.md.3vzIjrb3.js",
"/ran/assets/src_article_typescript_unionType.md.BaK8c9Pn.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_ranui_popover_index.md.DN_tVX7Q.js",
"/ran/assets/src_article_sort_shell_index.md.PhX545pQ.js",
"/ran/assets/cn_src_ranui_select_index.md.CJ_j4icw.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BairM8Ym.js",
"/ran/assets/src_ranui_message_index.md.Ba94Rfn4.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranui_checkbox_index.md.FHn44HaZ.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_article_typescript_pattern.md.CIxoWe3N.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_article_functionalProgramming.md.fjlEHNSA.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranui_tab_index.md.CNqDrjpu.lean.js",
"/ran/assets/src_article_sort_shell_index.md.PhX545pQ.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.35rLwsiK.lean.js",
"/ran/assets/src_ranui_tab_index.md.C0K71N_5.lean.js",
"/ran/assets/src_article_designMode.md.tPDe0q1u.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DmCvjBxR.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BGjs-3Ud.js",
"/ran/assets/src_ranui_loading_index.md.B_57KT0D.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_ranui_radar_index.md.DizboFr-.lean.js",
"/ran/assets/src_ranui_tabs_index.md.86Hf45HN.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BTKGK7Nk.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Den7Escp.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_article_docPreview.md.DP39twp2.js",
"/ran/assets/cn_src_note_centos.md.LVHpEJ2P.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B6yWYRqS.js",
"/ran/assets/src_ranuts_file_readDir.md.Bwnrzpn_.lean.js",
"/ran/assets/src_article_sort_insert_index.md.BZ_btJFB.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BJykMunn.js",
"/ran/assets/cn_src_ranui_tab_index.md.CNqDrjpu.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_fileInfo.md.Tn4YAM93.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DZBrq7DD.lean.js",
"/ran/assets/cn_src_article_designMode.md.DS7vFoU0.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_modal_index.md.N7gC74eU.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.uGnU60Fp.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BBmiGAgY.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.4521sPfY.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BvtdrSBn.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.C9Dm1YAG.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.C9Dm1YAG.js",
"/ran/assets/src_article_javascript_domLoad.md.ZhFbf1VB.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.xw1bfdK5.js",
"/ran/assets/cn_src_article_designMode.md.DS7vFoU0.js",
"/ran/assets/src_types_类型运算.md.C9Y5moRj.js",
"/ran/assets/cn_src_ranui_image_index.md.CNzEOgqD.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.B5NvmwaQ.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CBDjYrE1.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CIJo0qDv.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_sort_index.md.B36sgS0L.js",
"/ran/assets/src_ranuts_utils_formatJson.md.1uBK37jq.js",
"/ran/assets/src_ranuts_file_writeFile.md.CrmbwIYg.js",
"/ran/assets/src_ranuts_bundler_index.md.5w-rzSsv.lean.js",
"/ran/assets/src_article_sort_quick_index.md.tcDfqetl.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranui_index.md.3vzIjrb3.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranuts_file_appendFile.md.WUPbkov0.lean.js",
"/ran/assets/src_ranui_message_index.md.Ba94Rfn4.js",
"/ran/screenshots_2560x1440.jpg",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/manifest.json",
"/ran/favicon.ico",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/icon_72.png",
"/ran/cn/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/icon_168.png",
"/ran/home.svg",
"/ran/vp-icons.css",
"/ran/icon_48.png",
"/ran/404.html",
];
const VERSION = "1732978960";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



