const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_192.png",
"/ran/icon_168.png",
"/ran/404.html",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/logo.png",
"/ran/manifest.json",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/icon.png",
"/ran/icon_96.png",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/article/bundle.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/assets/cn_src_article_bundle.md.rUVOr53S.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranui_input_index.md.rH4TfsRS.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.C9zJXhmE.lean.js",
"/ran/assets/src_article_sort_heap_index.md.DNtic4w0.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.bhsJMHkJ.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CIK-8K_Q.lean.js",
"/ran/assets/index.md.DsYHKJP0.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.utXIpdse.lean.js",
"/ran/assets/src_article_design_mode.md.BtAIwVE6.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BUYn-sVQ.js",
"/ran/assets/src_article_sort_heap_index.md.DNtic4w0.js",
"/ran/assets/src_ranui_radar_index.md.DSlJJ4DI.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/src_ranui_input_index.md.DVX5kU92.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.59eP1mjb.js",
"/ran/assets/src_ranui_input_index.md.DVX5kU92.js",
"/ran/assets/src_ranuts_file_read_dir.md.CSDGB7M2.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_ranui_skeleton_index.md.dkM6yC13.js",
"/ran/assets/cn_src_article_typescript_calculate.md.56WA4K6A.js",
"/ran/assets/cn_src_ranui_loading_index.md.BzajAx9E.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.vXa0OGNR.js",
"/ran/assets/cn_src_ranui_preview_index.md.utXIpdse.js",
"/ran/assets/src_article_typescript_pattern.md.PSizvAF6.js",
"/ran/assets/src_ranui_tabs_index.md.DpUInJOa.lean.js",
"/ran/assets/cn_src_article_video.md.CPuJFAt2.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranuts_file_write_file.md.BwdR76QJ.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_count_index.md.C9UCPMSE.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_article_typescript_reconstruction.md.BeOhEPqb.js",
"/ran/assets/src_ranuts_file_watch_file.md.B67yXxRk.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Yv_4EPPI.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BpcU-8qb.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranuts_utils_task.md.CbSkkiP5.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.Ceu_QHzA.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_message_index.md.DVn5Sn4X.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_article_typescript_calculate.md.56WA4K6A.lean.js",
"/ran/assets/cn_src_blockchain_index.md.CiJGbs1K.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.BjWXK24o.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/cn_src_ranui_popover_index.md.0rkjPfOz.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_file_read_file.md.DxdTzGpa.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Blq4YiAl.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranuts_file_watch_file.md.B67yXxRk.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/src_ranui_math_index.md.B29R5oPp.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.2wb7EbpC.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.l0Fiar7o.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Des-SHeZ.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ch9L_Ypx.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.l49mMOvw.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DYVMkZF6.js",
"/ran/assets/src_ranui_popover_index.md.Dp5uJyc2.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.U-XO9wCR.js",
"/ran/assets/src_ranuts_binary_tree_index.md.C6GiWOtj.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranuts_file_write_file.md.BwdR76QJ.lean.js",
"/ran/assets/src_article_sort_quick_index.md.B20pJOqT.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.B8VW2MqT.lean.js",
"/ran/assets/src_types_类型运算.md.ByIPG_4N.lean.js",
"/ran/assets/cn_src_note_docker.md.Bk5XpuXJ.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ar-3GcQa.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B9wKrxw9.lean.js",
"/ran/assets/src_types_模式匹配.md.C1BEnFaI.lean.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/cn_src_article_sort_merge_index.md.SUXo7ybM.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DIMJdzF3.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_article_typescript_pattern.md.PSizvAF6.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_note_ubuntu.md.Cqo3AhRh.lean.js",
"/ran/assets/src_article_typescript_calculate.md.mQQ3tQNa.js",
"/ran/assets/cn_src_types_模式匹配.md.nghWtCUQ.js",
"/ran/assets/cn_src_ranui_index.md.2pJmogqB.js",
"/ran/assets/cn_src_article_imagemin.md.nJy02C4d.js",
"/ran/assets/cn_src_ranui_message_index.md.DVn5Sn4X.js",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.U-XO9wCR.lean.js",
"/ran/assets/src_ranui_player_index.md.55B6bV2I.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_typescript_index.md.CE46FjS7.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.rH4TfsRS.js",
"/ran/assets/cn_src_ranui_modal_index.md.0CeSKWRc.js",
"/ran/assets/src_ranui_button_index.md.DJEdIvtH.js",
"/ran/assets/cn_src_article_sort_count_index.md.DjwBE2-Q.js",
"/ran/assets/src_article_sort_shell_index.md.By9AbWyX.js",
"/ran/assets/src_types_TS类型.md.CvTf2Shz.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_article_sort_select_index.md.lkr_3slD.lean.js",
"/ran/assets/src_ranui_modal_index.md.DHYTSHVU.lean.js",
"/ran/assets/src_ranui_popover_index.md.Dp5uJyc2.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_tab_index.md.CI4wPrlS.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CvYRi7yc.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.btoe4lE8.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/src_ranui_image_index.md.DhQO7r9P.js",
"/ran/assets/cn_src_article_visual.md.DqlmaKEV.lean.js",
"/ran/assets/cn_src_blockchain_index.md.CiJGbs1K.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CyZq5oC3.js",
"/ran/assets/src_ranui_skeleton_index.md.dkM6yC13.lean.js",
"/ran/assets/src_ranuts_utils_task.md.D1ihyZT9.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranui_index.md.2pJmogqB.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.szS8nVTz.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_ranui_math_index.md.B29R5oPp.lean.js",
"/ran/assets/cn_src_types_高级类型.md.ETYRzD8X.lean.js",
"/ran/assets/src_article_design_mode.md.BtAIwVE6.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CpMeV2uN.lean.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/src_ranui_index.md.NDB-QgKU.lean.js",
"/ran/assets/cn_src_article_video.md.CPuJFAt2.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Djzl2Y_G.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BOlts_vt.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_sort_bubble_index.md.C-v2Ep66.js",
"/ran/assets/src_article_sort_merge_index.md.Dr6jqn-_.lean.js",
"/ran/assets/src_ranui_preview_index.md.5PZpuis5.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DsB5Z_BL.js",
"/ran/assets/cn_src_ranui_modal_index.md.0CeSKWRc.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.COOyQdRP.js",
"/ran/assets/src_article_sort_shell_index.md.By9AbWyX.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Djzl2Y_G.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_sort_insert_index.md.DeYUWaYK.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.C9zJXhmE.js",
"/ran/assets/cn_src_ranui_radar_index.md.CblOnKKb.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/cn_src_ranui_image_index.md.DYjiYGBV.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.DxdTzGpa.js",
"/ran/assets/app.eKADgU3w.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.btoe4lE8.lean.js",
"/ran/assets/src_article_sort_count_index.md.C9UCPMSE.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.i0NY2xzw.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.i0NY2xzw.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DeYUWaYK.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_typescript_index.md.CE46FjS7.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CzZr6Ohe.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.B4iflbcr.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.C37vSxNQ.lean.js",
"/ran/assets/src_article_sort_select_index.md.BWyyJ1jw.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BjWXK24o.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.Ceu_QHzA.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DsB5Z_BL.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_types_TS类型.md.CDYaAJoC.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.B4iflbcr.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_article_imagemin.md.nJy02C4d.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_utils_task.md.D1ihyZT9.js",
"/ran/assets/cn_index.md.BTR0o6ZF.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.Des-SHeZ.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranui_tabs_index.md.DpUInJOa.js",
"/ran/assets/cn_src_types_模式匹配.md.nghWtCUQ.lean.js",
"/ran/assets/cn_src_article_babel.md.C6-ulPc9.js",
"/ran/assets/cn_src_article_design_mode.md.C2kiGglL.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranuts_index.md.D_oXvo10.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.rxbz3aOw.js",
"/ran/assets/src_types_TS类型.md.CvTf2Shz.js",
"/ran/assets/cn_src_ranui_icon_index.md.CZH6M9pI.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DYVMkZF6.lean.js",
"/ran/assets/src_ranui_tab_index.md.y6OQsadS.js",
"/ran/assets/src_ranui_player_index.md.55B6bV2I.js",
"/ran/assets/src_ranui_modal_index.md.DHYTSHVU.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BOlts_vt.js",
"/ran/assets/src_ranui_tab_index.md.y6OQsadS.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.D9KaYrXk.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranuts_file_append_file.md.j1ZHCVG6.js",
"/ran/assets/src_ranuts_file_file_info.md.DzGmKi28.js",
"/ran/assets/src_ranuts_utils_str2xml.md.mL7eGbra.js",
"/ran/assets/cn_src_ranui_select_index.md.DAinVcr0.js",
"/ran/assets/src_article_babel.md.CA3HgmEI.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BviNBj_H.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Dr6jqn-_.js",
"/ran/assets/cn_src_types_TS类型.md.CDYaAJoC.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BpcU-8qb.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.0rkjPfOz.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CIK-8K_Q.js",
"/ran/assets/cn_src_blockchain_web3.md.q4-ouNg6.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.3Hjg6e91.js",
"/ran/assets/src_article_sort_bucket_index.md.GT223uRo.js",
"/ran/assets/cn_src_article_sort_index.md.D0C9fP5p.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.D1sQ4Rlg.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BT48ycdk.js",
"/ran/assets/src_article_typescript_calculate.md.mQQ3tQNa.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_system_design.md.C09bkF-1.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.DkewJntN.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_ranui_icon_index.md.CZH6M9pI.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_article_sort_radix_index.md.COOyQdRP.lean.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.CvYRi7yc.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CpMeV2uN.js",
"/ran/assets/src_ranui_select_index.md.CUtRfV3C.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.59eP1mjb.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.0WMkVd7X.js",
"/ran/assets/cn_src_article_functional_programming.md.CvhVhqq4.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/src_ranui_message_index.md.fUAKibwd.js",
"/ran/assets/cn_src_article_typescript_index.md.DGNxFa0e.js",
"/ran/assets/src_ranui_button_index.md.DJEdIvtH.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.C37vSxNQ.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_index.md.D_oXvo10.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_index.md.BT48ycdk.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/src_ranui_checkbox_index.md.l49mMOvw.lean.js",
"/ran/assets/src_article_typescript_recursion.md.BAz8HSMJ.lean.js",
"/ran/assets/src_ranui_image_index.md.DhQO7r9P.lean.js",
"/ran/assets/cn_src_note_centos.md.H7sL35D5.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CbSkkiP5.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BUYn-sVQ.lean.js",
"/ran/assets/cn_src_note_docker.md.Bk5XpuXJ.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.0WMkVd7X.lean.js",
"/ran/assets/cn_src_note_centos.md.H7sL35D5.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ar-3GcQa.js",
"/ran/assets/style.CemZ0LdT.css",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.3Hjg6e91.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DzGmKi28.lean.js",
"/ran/assets/index.md.DsYHKJP0.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/src_ranuts_file_read_dir.md.CSDGB7M2.lean.js",
"/ran/assets/cn_src_types_高级类型.md.ETYRzD8X.js",
"/ran/assets/cn_src_ranui_button_index.md.dptjcjM5.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.WVsJVY0n.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.rxbz3aOw.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranui_select_index.md.DAinVcr0.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_index.md.CNM2SgVr.js",
"/ran/assets/src_article_sort_radix_index.md.DTSwUccw.js",
"/ran/assets/cn_src_article_bundle.md.rUVOr53S.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_select_index.md.CUtRfV3C.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.WVsJVY0n.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DTSwUccw.lean.js",
"/ran/assets/src_ranui_icon_index.md.CmjXHTDd.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/cn_src_article_system_design.md.C09bkF-1.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CO0XTi7Z.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DjwBE2-Q.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BcgB0CIV.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_sort_bubble_index.md.C-v2Ep66.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DkewJntN.lean.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.C6GiWOtj.lean.js",
"/ran/assets/src_article_sort_index.md.CNM2SgVr.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B7Ow2Agf.lean.js",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/src_article_ast_parse_tokenizer.md.CjDMmgu2.lean.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/cn_src_article_visual.md.DqlmaKEV.js",
"/ran/assets/src_article_imagemin.md.DdKWll_Y.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BZ-D3UbC.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Cqo3AhRh.js",
"/ran/assets/src_ranui_index.md.NDB-QgKU.js",
"/ran/assets/src_ranuts_file_append_file.md.j1ZHCVG6.lean.js",
"/ran/assets/cn_index.md.BTR0o6ZF.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.BYSLjdz9.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ch9L_Ypx.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.CjDMmgu2.js",
"/ran/assets/src_article_functional_programming.md.SmZOtOBZ.js",
"/ran/assets/cn_src_article_typescript_union_type.md.bhsJMHkJ.js",
"/ran/assets/src_ranui_progress_index.md.DKBY7X3-.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.mL7eGbra.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DIMJdzF3.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CzZr6Ohe.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BzajAx9E.js",
"/ran/assets/src_article_typescript_union_type.md.fbJqCJSj.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_bundler_index.md.vXa0OGNR.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CI4wPrlS.lean.js",
"/ran/assets/src_article_bundle.md.B-ALBkAS.js",
"/ran/assets/src_article_sort_quick_index.md.B20pJOqT.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.BYSLjdz9.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B7Ow2Agf.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_sort_index.md.D0C9fP5p.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DYjiYGBV.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CO0XTi7Z.js",
"/ran/assets/cn_src_article_doc_preview.md.D9KaYrXk.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/VPLocalSearchBox.B6_fZlQi.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Cranjoik.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/pwa-install.es.CbrFrHao.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/framework.C-CuVyxx.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/chunks/@localSearchIndexcn.CV53DHNr.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/@localSearchIndexroot.DY9x2IRV.js",
"/ran/assets/chunks/index.YnwqpBk7.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/theme.rDmCZ0Go.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/pdf-NSMtd33u.BC6F2X3M.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/index.CMLHYzfC.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/cn_src_ranui_button_index.md.dptjcjM5.js",
"/ran/assets/src_ranui_radar_index.md.DSlJJ4DI.js",
"/ran/assets/src_article_babel.md.CA3HgmEI.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_types_类型运算.md.BZ-D3UbC.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_article_typescript_index.md.DGNxFa0e.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.D1sQ4Rlg.js",
"/ran/assets/src_ranuts_utils_format_json.md.BcgB0CIV.lean.js",
"/ran/assets/src_ranui_loading_index.md.DT2UtONg.lean.js",
"/ran/assets/src_article_bundle.md.B-ALBkAS.lean.js",
"/ran/assets/src_article_imagemin.md.DdKWll_Y.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CyZq5oC3.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.B8VW2MqT.js",
"/ran/assets/cn_src_ranui_player_index.md.CfDysjuj.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_progress_index.md.DKBY7X3-.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CfDysjuj.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.szS8nVTz.js",
"/ran/assets/src_types_类型运算.md.ByIPG_4N.js",
"/ran/assets/cn_src_article_sort_select_index.md.lkr_3slD.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_sort_select_index.md.BWyyJ1jw.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_math_linear_algebra.md.Yv_4EPPI.js",
"/ran/assets/cn_src_ranui_radar_index.md.CblOnKKb.lean.js",
"/ran/assets/cn_src_article_design_mode.md.C2kiGglL.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_typescript_reconstruction.md.BeOhEPqb.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.BviNBj_H.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_blockchain_web3.md.q4-ouNg6.lean.js",
"/ran/assets/src_ranui_icon_index.md.CmjXHTDd.js",
"/ran/assets/cn_src_article_functional_programming.md.CvhVhqq4.lean.js",
"/ran/assets/src_types_高级类型.md.CWZZ2cyL.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.l0Fiar7o.js",
"/ran/assets/cn_src_article_sort_merge_index.md.SUXo7ybM.lean.js",
"/ran/assets/cn_src_article_babel.md.C6-ulPc9.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Blq4YiAl.lean.js",
"/ran/assets/src_ranui_message_index.md.fUAKibwd.lean.js",
"/ran/assets/src_ranui_loading_index.md.DT2UtONg.js",
"/ran/assets/src_ranui_preview_index.md.5PZpuis5.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_functional_programming.md.SmZOtOBZ.lean.js",
"/ran/assets/src_article_typescript_union_type.md.fbJqCJSj.js",
"/ran/assets/src_types_模式匹配.md.C1BEnFaI.js",
"/ran/assets/src_article_typescript_recursion.md.BAz8HSMJ.js",
"/ran/assets/src_types_高级类型.md.CWZZ2cyL.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B9wKrxw9.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranuts_file_file_info.md.2wb7EbpC.js",
"/ran/assets/src_article_sort_bucket_index.md.GT223uRo.lean.js",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/favicon.ico",
"/ran/screenshots_2560x1440.jpg",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/index.html",
"/ran/icon_48.png",
"/ran/sw1757297011.js",
"/ran/screenshots_748x1340.jpg",
"/ran/vp-icons.css",
"/ran/icon_144.png",
"/ran/home.svg",
"/ran/index.html",
"/ran/icon_72.png",
];
const VERSION = "1757297011";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



