const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/sw1742099864.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranui_radar_index.md.Bcs5xl48.js",
"/ran/assets/src_ranui_tab_index.md.A-fhfe8v.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_utils_ocr.md.BQpggGk7.js",
"/ran/assets/cn_src_article_sort_select_index.md.BFK-GlCN.js",
"/ran/assets/src_types_模式匹配.md.Pe-qJYXj.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BXqtrqVJ.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranuts_utils_format_json.md.D7sOi1io.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DJgG5lev.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.k_L6ZK9R.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_select_index.md.CCyu9FC2.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.KRTbUSXv.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DKyckMdr.js",
"/ran/assets/cn_src_article_typescript_index.md.Cz03MqDw.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.BFK-GlCN.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_tabs_index.md.DcwkCjnn.js",
"/ran/assets/cn_src_types_类型运算.md.DadVYavy.js",
"/ran/assets/cn_src_article_system_design.md.BlOALnsH.js",
"/ran/assets/cn_src_ranui_player_index.md.DyvyEqdi.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_babel.md.DllFZ6t1.js",
"/ran/assets/src_ranuts_utils_str2xml.md.KRTbUSXv.js",
"/ran/assets/src_article_bundle.md.7UkN56la.js",
"/ran/assets/cn_src_ranui_preview_index.md.hZszD_MR.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_visual.md.Sq7907K2.lean.js",
"/ran/assets/src_ranui_loading_index.md.B35GGcBB.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMITBh7l.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bbr0gm9h.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.B5T3riaF.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_typescript_index.md.Cz03MqDw.js",
"/ran/assets/cn_src_types_高级类型.md.BDwznyCz.js",
"/ran/assets/src_article_sort_quick_index.md.7qCMQ8DF.lean.js",
"/ran/assets/src_ranui_image_index.md.BXqwDBs8.lean.js",
"/ran/assets/index.md.UqISdNG0.lean.js",
"/ran/assets/cn_src_note_docker.md.CfWXVmAo.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.C-kMm30X.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_article_sort_index.md.ZDr11QdS.lean.js",
"/ran/assets/src_ranuts_utils_task.md.CFJohCg9.js",
"/ran/assets/src_ranuts_file_read_file.md.ClREP06a.js",
"/ran/assets/cn_src_article_doc_preview.md.ChJxNpgE.lean.js",
"/ran/assets/src_ranui_tab_index.md.A-fhfe8v.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_system_design.md.BlOALnsH.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.B39JW7Tm.js",
"/ran/assets/cn_src_ranui_modal_index.md.CYX7AITZ.js",
"/ran/assets/src_article_design_mode.md.CmCtiBPR.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.B5T3riaF.js",
"/ran/assets/src_ranuts_file_watch_file.md.Bl-zl21w.js",
"/ran/assets/src_article_sort_index.md.OkivyaqF.js",
"/ran/assets/cn_src_ranui_index.md.DaPbHIaC.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.B-g5inbN.js",
"/ran/assets/cn_index.md.CzklHcHC.js",
"/ran/assets/cn_src_note_centos.md.DYdga6TY.js",
"/ran/assets/src_ranui_skeleton_index.md.Cf9SGJN4.lean.js",
"/ran/assets/src_ranuts_utils_task.md.CFJohCg9.lean.js",
"/ran/assets/src_ranui_image_index.md.BXqwDBs8.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.uRQEOu4w.lean.js",
"/ran/assets/src_ranui_icon_index.md.DKUzV8ey.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_doc_preview.md.ChJxNpgE.js",
"/ran/assets/src_article_sort_radix_index.md.CHIhNNtm.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.CctTninx.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.ClREP06a.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BTvSXiiE.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DZ1ZIfAG.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranuts_utils_ocr.md.BQpggGk7.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CKmDuHpP.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.lvA-V47p.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_sort_bucket_index.md.B4RhzufV.js",
"/ran/assets/src_ranui_index.md.CX84g1CT.lean.js",
"/ran/assets/src_types_类型运算.md.BakYwWSG.js",
"/ran/assets/cn_src_types_TS类型.md.CdXusyI1.lean.js",
"/ran/assets/cn_src_note_docker.md.CfWXVmAo.js",
"/ran/assets/src_types_高级类型.md.CmQjuusp.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.oifgmr8-.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.T5WLgTDh.js",
"/ran/assets/cn_src_ranui_image_index.md.Ck3hJSwN.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.Ci0MFbeD.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.0AxR2mFY.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_radar_index.md.ClIUBcq1.js",
"/ran/assets/src_ranui_input_index.md.CGagHEQE.js",
"/ran/assets/cn_src_ranui_icon_index.md.DGqSBUhh.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.2JTczzgA.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.D2ecK_lt.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.dzcYLBxy.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DM3UhOXa.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranuts_binary_tree_index.md.tuuCtmRT.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.oifgmr8-.lean.js",
"/ran/assets/src_ranui_select_index.md.D_lzNOgk.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_design_mode.md.B2BLDsx-.js",
"/ran/assets/cn_src_article_bundle.md.BzIih902.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DGqSBUhh.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BLDcs4ZM.js",
"/ran/assets/cn_src_article_typescript_union_type.md.QHWqCii7.js",
"/ran/assets/src_types_模式匹配.md.Pe-qJYXj.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranui_math_index.md.COk_u2QW.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B3l1nzCZ.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_typescript_reconstruction.md.aZGjIvsI.js",
"/ran/assets/src_ranui_input_index.md.CGagHEQE.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.QHWqCii7.lean.js",
"/ran/assets/src_article_babel.md.DllFZ6t1.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BTvSXiiE.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.BVuDlpCN.js",
"/ran/assets/src_ranui_player_index.md.B2dkWw1q.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CH1ehUck.lean.js",
"/ran/assets/cn_src_article_sort_index.md.ZDr11QdS.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CKmDuHpP.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.BVuDlpCN.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.B39JW7Tm.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_functional_programming.md.BBh99y3M.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B5TNTu9D.lean.js",
"/ran/assets/src_ranui_modal_index.md.DFdOhLgz.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DnaMtvfw.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.B5W3J56F.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.BqzjcN08.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.2JTczzgA.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BRCbsOP7.lean.js",
"/ran/assets/src_ranui_preview_index.md.CMb2gvkk.js",
"/ran/assets/cn_src_ranui_message_index.md.Bx-ofwus.js",
"/ran/assets/cn_src_ranuts_index.md.7Nffl2I9.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.B-g5inbN.lean.js",
"/ran/assets/src_ranui_select_index.md.D_lzNOgk.lean.js",
"/ran/assets/src_types_TS类型.md.DSYuN5ps.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BpIQuco7.lean.js",
"/ran/assets/src_article_bundle.md.7UkN56la.lean.js",
"/ran/assets/app.BpKc9tlD.js",
"/ran/assets/src_article_sort_merge_index.md.BzRR8Uie.js",
"/ran/assets/cn_src_ranui_preview_index.md.hZszD_MR.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B5TNTu9D.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_ranui_math_index.md.DCEbP2se.lean.js",
"/ran/assets/src_ranui_button_index.md.Bihv5e-V.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DJgG5lev.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BLDcs4ZM.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BPQxOsuO.js",
"/ran/assets/src_ranuts_utils_format_json.md.0AxR2mFY.js",
"/ran/assets/src_article_typescript_union_type.md.DutJev-b.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_index.md.8E_4mOmJ.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.C5PLmuqJ.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranuts_file_read_dir.md.lvA-V47p.lean.js",
"/ran/assets/src_article_typescript_calculate.md.Df8XA53H.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.TR7axgmz.js",
"/ran/assets/src_article_typescript_index.md.B0fbNW6E.js",
"/ran/assets/cn_src_article_functional_programming.md.BqzjcN08.js",
"/ran/assets/src_ranui_radar_index.md.Bcs5xl48.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_progress_index.md.BOHBbuXl.lean.js",
"/ran/assets/src_article_sort_count_index.md.BP9_YpSJ.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_types_高级类型.md.BDwznyCz.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.B5W3J56F.js",
"/ran/assets/cn_src_article_sort_radix_index.md.TR7axgmz.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Cw3qWx2o.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_types_类型运算.md.DadVYavy.lean.js",
"/ran/assets/src_article_sort_insert_index.md.CJ-MOFh4.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.D7sOi1io.js",
"/ran/assets/src_ranuts_file_file_info.md.dzcYLBxy.js",
"/ran/assets/cn_src_ranui_button_index.md.BPOX_VN3.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DNUdML-7.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BRCbsOP7.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_babel.md.Ja02O26R.lean.js",
"/ran/assets/src_types_高级类型.md.CmQjuusp.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.C5PLmuqJ.js",
"/ran/assets/cn_src_ranui_image_index.md.Ck3hJSwN.js",
"/ran/assets/cn_src_types_TS类型.md.CdXusyI1.js",
"/ran/assets/cn_src_ranui_player_index.md.DyvyEqdi.js",
"/ran/assets/src_article_sort_index.md.OkivyaqF.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_typescript_reconstruction.md.aZGjIvsI.lean.js",
"/ran/assets/cn_src_article_video.md.CShTbeHt.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranui_math_index.md.COk_u2QW.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BPOX_VN3.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_note_centos.md.DYdga6TY.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BpIQuco7.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.C9-IRJj5.js",
"/ran/assets/cn_src_article_sort_quick_index.md.k_L6ZK9R.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.Hxlocf0Q.js",
"/ran/assets/cn_src_ranui_message_index.md.Bx-ofwus.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Hxlocf0Q.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.gKiGqR33.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DKyckMdr.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.uGiloPWs.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.o-C74_13.lean.js",
"/ran/assets/cn_src_ranuts_index.md.7Nffl2I9.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.tjBq3ElJ.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.-tyHRo5m.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_preview_index.md.CMb2gvkk.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.B4RhzufV.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranuts_file_read_file.md.D2ecK_lt.js",
"/ran/assets/src_ranuts_bundler_index.md.BaNNrabi.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CzTmzeEn.js",
"/ran/assets/src_ranuts_file_watch_file.md.Bl-zl21w.lean.js",
"/ran/assets/src_article_design_mode.md.CmCtiBPR.lean.js",
"/ran/assets/src_ranui_progress_index.md.BOHBbuXl.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CH1ehUck.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.C1fDre_Y.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_ranui_button_index.md.Bihv5e-V.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_sort_merge_index.md.BzRR8Uie.lean.js",
"/ran/assets/src_ranui_modal_index.md.DFdOhLgz.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_binary_tree_index.md.tuuCtmRT.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Che-nxj6.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_imagemin.md.DzBz114K.js",
"/ran/assets/src_ranui_math_index.md.DCEbP2se.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.-tyHRo5m.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.B-1hkghj.js",
"/ran/assets/src_ranui_icon_index.md.DKUzV8ey.js",
"/ran/assets/cn_src_article_bundle.md.BzIih902.js",
"/ran/assets/src_article_sort_quick_index.md.7qCMQ8DF.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.BPQxOsuO.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.Ci0MFbeD.js",
"/ran/assets/src_ranui_loading_index.md.B35GGcBB.js",
"/ran/assets/src_ranuts_file_read_dir.md.B4fhZx86.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.uGiloPWs.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DNUdML-7.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.tjBq3ElJ.js",
"/ran/assets/cn_src_note_ubuntu.md.Cw3qWx2o.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.CY422gW0.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_typescript_calculate.md.Df8XA53H.js",
"/ran/assets/src_ranui_checkbox_index.md.gKiGqR33.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_sort_count_index.md.BP9_YpSJ.js",
"/ran/assets/src_article_sort_insert_index.md.CJ-MOFh4.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DIMXL2gU.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.BzfckpWe.js",
"/ran/assets/cn_src_ranui_tab_index.md.CRZqKaaz.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.uRQEOu4w.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_typescript_recursion.md.DRX5Z_3B.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_types_类型运算.md.BakYwWSG.lean.js",
"/ran/assets/src_ranui_player_index.md.B2dkWw1q.js",
"/ran/assets/cn_src_ranui_tab_index.md.CRZqKaaz.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.B-1hkghj.lean.js",
"/ran/assets/cn_src_article_visual.md.Sq7907K2.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DnaMtvfw.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_functional_programming.md.BBh99y3M.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.skdcyV3Q.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.D-gvCK5R.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_ranuts_utils_task.md.Che-nxj6.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/@localSearchIndexcn.BFiepz5V.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DQYwnIkK.js",
"/ran/assets/chunks/theme.BSpVPtYv.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/@localSearchIndexroot.BpxnTsCp.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/index.Fx_mSIZ8.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/VPLocalSearchBox.BOflMpML.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/src_ranuts_file_append_file.md.DIMXL2gU.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.C9-IRJj5.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_article_sort_bubble_index.md.skdcyV3Q.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_index.md.CzklHcHC.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.T5WLgTDh.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DcwkCjnn.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.B6IzZkGy.js",
"/ran/assets/cn_src_ranui_input_index.md.14N-Zc-T.lean.js",
"/ran/assets/src_article_imagemin.md.DzBz114K.lean.js",
"/ran/assets/src_article_sort_select_index.md.CCyu9FC2.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DM3UhOXa.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bbr0gm9h.js",
"/ran/assets/cn_src_ranui_select_index.md.B6IzZkGy.lean.js",
"/ran/assets/cn_src_article_video.md.CShTbeHt.js",
"/ran/assets/src_article_typescript_index.md.B0fbNW6E.lean.js",
"/ran/assets/src_ranui_message_index.md.CsS9Gnzy.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B3l1nzCZ.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CzTmzeEn.lean.js",
"/ran/assets/src_ranuts_index.md.8E_4mOmJ.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DeWtUdrS.js",
"/ran/assets/src_article_sort_shell_index.md.3kF_F39K.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_design_mode.md.B2BLDsx-.lean.js",
"/ran/assets/src_types_TS类型.md.DSYuN5ps.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_typescript_reconstruction.md.D-gvCK5R.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.CctTninx.js",
"/ran/assets/src_ranui_popover_index.md.DqL4-u_s.lean.js",
"/ran/assets/src_article_sort_radix_index.md.CHIhNNtm.js",
"/ran/assets/cn_src_ranui_input_index.md.14N-Zc-T.js",
"/ran/assets/src_ranuts_file_write_file.md.iRwh58bV.lean.js",
"/ran/assets/style.zTfaa9RN.css",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.BXqtrqVJ.js",
"/ran/assets/src_ranui_popover_index.md.DqL4-u_s.js",
"/ran/assets/src_article_javascript_dom_load.md.BzfckpWe.lean.js",
"/ran/assets/cn_src_ranui_index.md.DaPbHIaC.js",
"/ran/assets/src_ranui_skeleton_index.md.Cf9SGJN4.js",
"/ran/assets/src_ranuts_bundler_index.md.BaNNrabi.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_sort_count_index.md.CY422gW0.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.C-kMm30X.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_file_write_file.md.iRwh58bV.js",
"/ran/assets/src_article_typescript_recursion.md.DRX5Z_3B.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMITBh7l.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/index.md.UqISdNG0.js",
"/ran/assets/src_ranui_message_index.md.CsS9Gnzy.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CYX7AITZ.lean.js",
"/ran/assets/src_ranui_index.md.CX84g1CT.js",
"/ran/assets/cn_src_article_babel.md.Ja02O26R.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranui_radar_index.md.ClIUBcq1.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranuts_mode_subscribe.md.DZ1ZIfAG.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.o-C74_13.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_popover_index.md.SpRYX8xI.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DeWtUdrS.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.SpRYX8xI.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.C1fDre_Y.js",
"/ran/assets/src_article_typescript_union_type.md.DutJev-b.js",
"/ran/assets/src_article_sort_shell_index.md.3kF_F39K.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranuts_file_read_dir.md.B4fhZx86.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1742099864";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



