const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/home.svg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/manifest.json",
"/ran/vp-icons.css",
"/ran/icon.png",
"/ran/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_96.png",
"/ran/sw1759195981.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Jgd4_VsD.lean.js",
"/ran/assets/src_ranui_progress_index.md.7BBd1FSD.js",
"/ran/assets/src_article_typescript_recursion.md.1lcwoZiR.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_types_类型运算.md.D2kIuLCr.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BtBCQAhk.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_article_sort_count_index.md.QTnn51Ym.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranui_radar_index.md.BRlr202d.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.B22qLinC.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BdTKL3IP.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.BweN7RVw.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.D99sNXWw.js",
"/ran/assets/src_ranuts_bundler_index.md.C2Vc0fGN.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Bd7dlAly.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_video.md.KT3pxo3Y.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_types_TS类型.md.DFSWQ3t_.js",
"/ran/assets/src_ranuts_file_read_dir.md.WOTjOayk.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/cn_src_ranui_math_index.md.CrB0PUhP.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.QweUuHUT.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md._-l-qrRO.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CtFnOquH.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CyKKeLF4.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BKC9fUWz.js",
"/ran/assets/cn_src_ranui_player_index.md.ClnzhPru.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CCCi2yKz.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cl7P-Tg1.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranui_input_index.md.949aTMuR.js",
"/ran/assets/src_ranuts_file_read_file.md.Iat7aSvc.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CH3vDVRy.js",
"/ran/assets/src_article_typescript_calculate.md.Bx0G7Grd.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.B-_921gn.lean.js",
"/ran/assets/src_ranui_math_index.md.ppKdehR8.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.B22qLinC.lean.js",
"/ran/assets/src_article_bundle.md.CdXE2lE2.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B1bJQN56.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/index.md.bTsWiLOq.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.B48vninQ.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BkKEsPr4.lean.js",
"/ran/assets/cn_index.md.COApkdMz.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_index.md.WcdK2T_J.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_tab_index.md.CH3vDVRy.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_sort_bucket_index.md.Bd7dlAly.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.WFpH6-Km.lean.js",
"/ran/assets/src_ranui_select_index.md.DIMxsVKV.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranui_player_index.md.ClnzhPru.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md._lHeDGVu.js",
"/ran/assets/cn_src_article_visual.md.BY3gEdrR.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CNARNdlv.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_typescript_pattern.md.hjcmCuJV.lean.js",
"/ran/assets/cn_src_blockchain_web3.md.MXFU8quO.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranui_message_index.md.DU7_pMaW.js",
"/ran/assets/cn_src_article_doc_preview.md.CfQvC97f.lean.js",
"/ran/assets/src_ranui_tab_index.md.CsMgXbJt.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.DAkrTMjb.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.PmXtSWUO.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_preview_index.md.N7rDCZVb.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_article_bundle.md.BttLU7YC.lean.js",
"/ran/assets/cn_src_article_system_design.md.DsHGppyU.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Co2HP0ba.lean.js",
"/ran/assets/src_ranui_loading_index.md.howoIlfe.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.mNRmom33.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DbdNdMX5.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DMV25i7h.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_types_TS类型.md.D2YM3Pbw.lean.js",
"/ran/assets/src_article_typescript_recursion.md.1lcwoZiR.lean.js",
"/ran/assets/cn_src_blockchain_index.md.BYe69Oh4.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CISVwiC_.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BS1Z1opb.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CPGhkCj4.lean.js",
"/ran/assets/src_ranui_button_index.md.B2N8onBz.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.ir4JJOC5.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md._lHeDGVu.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BOdU80vj.js",
"/ran/assets/src_ranui_radar_index.md.BRlr202d.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.C1KmRtQX.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BdTKL3IP.js",
"/ran/assets/src_article_sort_bubble_index.md.CEEJclXN.js",
"/ran/assets/cn_src_article_video.md.KT3pxo3Y.lean.js",
"/ran/assets/src_ranui_modal_index.md.DUUUjR_m.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DbdNdMX5.lean.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_ranui_math_index.md.CrB0PUhP.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_imagemin.md.DzQSjz-2.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CLXYVqwM.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/index.md.bTsWiLOq.lean.js",
"/ran/assets/src_ranui_tab_index.md.CsMgXbJt.js",
"/ran/assets/src_article_babel.md.DMpZynSi.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_binary_tree_index.md.CGe4R2P1.js",
"/ran/assets/src_types_类型运算.md.eR8Inyno.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_article_sort_select_index.md.D6VUctVX.js",
"/ran/assets/src_types_模式匹配.md.Bk9Hs34J.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_sort_heap_index.md.BEdqlVqa.lean.js",
"/ran/assets/src_article_typescript_union_type.md.D_Z9RrBH.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranui_select_index.md.DIMxsVKV.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DAALSwrC.lean.js",
"/ran/assets/src_ranui_progress_index.md.7BBd1FSD.lean.js",
"/ran/assets/src_article_typescript_index.md.DLF64Lg6.js",
"/ran/assets/cn_src_ranui_input_index.md.ByX-7qtH.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.BULdleeL.js",
"/ran/assets/cn_src_ranui_image_index.md.DWgyUpP-.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.N7rDCZVb.js",
"/ran/assets/src_ranuts_file_file_info.md.jbMXx6-K.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.B0RijBgL.js",
"/ran/assets/cn_src_types_模式匹配.md.BQpLc399.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C3XSpADE.js",
"/ran/assets/src_article_sort_index.md.VAsQGedD.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_image_index.md.DWgyUpP-.js",
"/ran/assets/cn_src_ranui_message_index.md.BweN7RVw.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.D99sNXWw.lean.js",
"/ran/assets/src_types_类型运算.md.eR8Inyno.js",
"/ran/assets/cn_src_types_TS类型.md.DFSWQ3t_.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CkrWSk6W.lean.js",
"/ran/assets/src_article_sort_merge_index.md.BklCq1VO.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BQpLc399.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_input_index.md.ByX-7qtH.js",
"/ran/assets/cn_src_ranui_loading_index.md.Dp1iCtUk.lean.js",
"/ran/assets/src_article_sort_merge_index.md.BklCq1VO.js",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/src_ranui_icon_index.md.CGl3ahjg.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/chunks/pdf-NSMtd33u.Dke-8FVR.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DMwXyWY5.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/@localSearchIndexroot.ycBrHFNs.js",
"/ran/assets/chunks/index.B-cu4OtV.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/framework.D6J8Bmr0.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index.AgBORXSY.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/pwa-install.es.CbrFrHao.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/@localSearchIndexcn.RWhu3UDT.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/theme.CgJ8XUm_.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/VPLocalSearchBox.DzR59SON.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/cn_src_article_babel.md.AgMOCYSI.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.mNRmom33.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.C4su2-3a.js",
"/ran/assets/cn_src_note_ubuntu.md.bA_e7pwr.js",
"/ran/assets/src_types_模式匹配.md.Bk9Hs34J.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_sort_shell_index.md.D9DEvmpT.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_sort_insert_index.md.BkKEsPr4.js",
"/ran/assets/src_ranuts_file_read_dir.md.WOTjOayk.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.FfuaHFIA.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.Iat7aSvc.js",
"/ran/assets/cn_src_article_sort_select_index.md.C4su2-3a.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.CJ7Q1wmj.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.WFpH6-Km.js",
"/ran/assets/cn_src_types_类型运算.md.D2kIuLCr.js",
"/ran/assets/src_ranui_icon_index.md.CGl3ahjg.js",
"/ran/assets/cn_index.md.COApkdMz.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CeItoVWb.lean.js",
"/ran/assets/src_article_sort_count_index.md.D2bWu1v7.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CiniWn6O.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_design_mode.md.ChUjt1v0.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CNARNdlv.lean.js",
"/ran/assets/src_ranui_button_index.md.B2N8onBz.js",
"/ran/assets/cn_src_ranui_button_index.md.ZCtCVP5x.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_typescript_calculate.md.Bx0G7Grd.lean.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/cn_src_ranui_modal_index.md.CgFvLtRN.lean.js",
"/ran/assets/cn_src_note_docker.md.Coo6acBj.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.HKt6w_Sn.js",
"/ran/assets/src_article_sort_quick_index.md.DhUD3oog.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DH6Nct6X.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/src_article_sort_index.md.VAsQGedD.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.FfuaHFIA.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BtBCQAhk.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DNgI1nen.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.Ezsf3V4W.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BwktGP_y.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CLXYVqwM.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.kmrv3w9m.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.DesdElt1.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.DAkrTMjb.js",
"/ran/assets/src_article_sort_quick_index.md.DhUD3oog.js",
"/ran/assets/cn_src_article_doc_preview.md.CfQvC97f.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranui_math_index.md.ppKdehR8.js",
"/ran/assets/src_article_sort_count_index.md.D2bWu1v7.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BM4zk315.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/src_types_高级类型.md.jwGw8T2b.lean.js",
"/ran/assets/src_article_imagemin.md.FCKe7gn-.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.bA_e7pwr.lean.js",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.CISVwiC_.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.B0RijBgL.lean.js",
"/ran/assets/src_ranuts_index.md.WcdK2T_J.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.QTnn51Ym.js",
"/ran/assets/cn_src_article_system_design.md.DsHGppyU.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.B-_921gn.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_radar_index.md._-l-qrRO.js",
"/ran/assets/cn_src_blockchain_index.md.BYe69Oh4.lean.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/src_ranui_player_index.md.CbRcKU3-.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranuts_utils_get_cookie.md.BZXpl4sB.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CeItoVWb.js",
"/ran/assets/cn_src_article_functional_programming.md.Ezsf3V4W.js",
"/ran/assets/cn_src_article_sort_index.md.DmoechFc.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CyKKeLF4.js",
"/ran/assets/src_article_sort_select_index.md.D6VUctVX.lean.js",
"/ran/assets/src_ranui_tabs_index.md.0CmB1mxT.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CYl0xFyn.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/src_types_TS类型.md.D2YM3Pbw.js",
"/ran/assets/src_ranui_message_index.md.DU7_pMaW.lean.js",
"/ran/assets/cn_src_note_centos.md.B_ZOpBr7.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CPGhkCj4.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.BZXpl4sB.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DNgI1nen.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_ranui_index.md.CSARLC_T.lean.js",
"/ran/assets/cn_src_ranui_index.md.DyIHtdFb.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_article_typescript_union_type.md.D_Z9RrBH.lean.js",
"/ran/assets/src_article_design_mode.md.CZLuvINc.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_sort_bubble_index.md.CEEJclXN.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.ZCtCVP5x.js",
"/ran/assets/src_article_imagemin.md.FCKe7gn-.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_ast_parse_tokenizer.md.Jgd4_VsD.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_types_高级类型.md.jwGw8T2b.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CYl0xFyn.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranuts_utils_task.md.DHO1lTmu.js",
"/ran/assets/src_article_sort_shell_index.md.D9DEvmpT.js",
"/ran/assets/cn_src_article_sort_index.md.DmoechFc.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DAALSwrC.js",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/src_article_functional_programming.md.BdccMaTL.js",
"/ran/assets/src_ranui_tabs_index.md.0CmB1mxT.js",
"/ran/assets/cn_src_ranui_popover_index.md.XQ9d5JLV.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BnfJ7qQ2.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B1bJQN56.lean.js",
"/ran/assets/src_ranui_modal_index.md.DUUUjR_m.lean.js",
"/ran/assets/src_ranui_popover_index.md.D8q4Cr5M.js",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/cn_src_types_高级类型.md.BKC9fUWz.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranuts_utils_task.md.DHO1lTmu.lean.js",
"/ran/assets/cn_src_article_babel.md.AgMOCYSI.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_blockchain_web3.md.MXFU8quO.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_javascript_dom_load.md.Dt1WiRAx.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.HKt6w_Sn.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.E1uK8uD5.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DH6Nct6X.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.uB9C8ygM.js",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_ranui_progress_index.md.BOdU80vj.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.DesdElt1.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CkrWSk6W.js",
"/ran/assets/src_ranuts_utils_format_json.md.CJ7Q1wmj.js",
"/ran/assets/src_article_sort_radix_index.md.BjEV96C0.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.E1uK8uD5.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_sort_insert_index.md.t50yJui0.js",
"/ran/assets/src_ranui_index.md.CSARLC_T.js",
"/ran/assets/style.DcaDrUTr.css",
"/ran/assets/src_ranuts_file_file_info.md.jbMXx6-K.js",
"/ran/assets/src_ranuts_utils_ocr.md.C1KmRtQX.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_skeleton_index.md.QweUuHUT.js",
"/ran/assets/cn_src_ranui_modal_index.md.CgFvLtRN.js",
"/ran/assets/app.CiTbNTTZ.js",
"/ran/assets/src_ranuts_bundler_index.md.C2Vc0fGN.js",
"/ran/assets/cn_src_article_typescript_pattern.md.hjcmCuJV.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.B29WJ5mF.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.PmXtSWUO.js",
"/ran/assets/src_article_sort_heap_index.md.BEdqlVqa.js",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_visual.md.BY3gEdrR.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_design_mode.md.ChUjt1v0.js",
"/ran/assets/src_article_functional_programming.md.BdccMaTL.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.ckg6KFg5.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BM4zk315.js",
"/ran/assets/cn_src_ranui_select_index.md.uB9C8ygM.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BltMV5KC.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cl7P-Tg1.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CKVNRlRe.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_imagemin.md.DzQSjz-2.js",
"/ran/assets/src_ranui_input_index.md.949aTMuR.lean.js",
"/ran/assets/src_article_babel.md.DMpZynSi.js",
"/ran/assets/src_ranui_checkbox_index.md.B3euvR1l.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.B29WJ5mF.js",
"/ran/assets/cn_src_note_centos.md.B_ZOpBr7.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_index.md.CiniWn6O.lean.js",
"/ran/assets/src_ranui_loading_index.md.howoIlfe.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/src_ranui_popover_index.md.D8q4Cr5M.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BS1Z1opb.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/src_article_typescript_pattern.md.BltMV5KC.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.CGe4R2P1.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/src_ranui_player_index.md.CbRcKU3-.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C3XSpADE.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.B48vninQ.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_typescript_index.md.DLF64Lg6.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_article_typescript_reconstruction.md.jUjNCBo_.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.ckg6KFg5.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.BULdleeL.lean.js",
"/ran/assets/src_article_bundle.md.CdXE2lE2.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BwktGP_y.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranui_image_index.md.Cu7-gxrl.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CCCi2yKz.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.CKVNRlRe.lean.js",
"/ran/assets/src_ranui_preview_index.md.Csro6tdw.js",
"/ran/assets/cn_src_article_typescript_index.md.kmrv3w9m.lean.js",
"/ran/assets/src_article_sort_insert_index.md.t50yJui0.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BjEV96C0.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Dp1iCtUk.js",
"/ran/assets/src_ranui_image_index.md.Cu7-gxrl.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Co2HP0ba.js",
"/ran/assets/cn_src_ranui_popover_index.md.XQ9d5JLV.lean.js",
"/ran/assets/cn_src_article_bundle.md.BttLU7YC.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.ir4JJOC5.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BnfJ7qQ2.js",
"/ran/assets/src_article_javascript_dom_load.md.Dt1WiRAx.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/src_ranui_preview_index.md.Csro6tdw.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.jUjNCBo_.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_article_design_mode.md.CZLuvINc.lean.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_note_docker.md.Coo6acBj.js",
"/ran/assets/cn_src_ranui_index.md.DyIHtdFb.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranuts_utils_str2xml.md.DMV25i7h.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_checkbox_index.md.B3euvR1l.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CtFnOquH.lean.js",
"/ran/icon_144.png",
"/ran/icon_72.png",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/example.m3u8",
"/ran/cn/index.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/system_design.html",
"/ran/logo.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/favicon.ico",
"/ran/icon_48.png",
"/ran/404.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/babel.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/bundle.html",
"/ran/src/article/imagemin.html",
"/ran/icon_168.png",
"/ran/icon_192.png",
];
const VERSION = "1759195981";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



