const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/src_article_functional_programming.md.rI-KK5XB.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_sort_bubble_index.md.DV_aizHb.js",
"/ran/assets/cn_src_article_system_design.md.B9JmZUCZ.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_index.md.DKkvYVoN.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DsZEPXfB.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Brllerj2.js",
"/ran/assets/src_article_sort_insert_index.md.U_pR929p.js",
"/ran/assets/src_ranuts_file_file_info.md.fVDOxooU.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.CIBXuGEQ.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CrzMVfPT.js",
"/ran/assets/src_ranui_loading_index.md.Bw9uj6Jt.lean.js",
"/ran/assets/src_article_bundle.md.tFweQiBn.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_types_高级类型.md.BqrQq15S.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_sort_merge_index.md.C1lg1_Rd.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_article_babel.md.BStQB2qj.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BZuyJTSE.js",
"/ran/assets/src_article_typescript_reconstruction.md.C9h344Uc.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranuts_file_append_file.md.Dm0l7oHm.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BJNQuxGq.js",
"/ran/assets/src_ranui_button_index.md.B2r0f_6o.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_typescript_recursion.md.CHV-AG-7.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.HVrFY_x9.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_article_typescript_index.md.CuG44IM6.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.B8ewcvyh.js",
"/ran/assets/cn_src_article_typescript_recursion.md.lCRGEKZ2.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_ast_parse_tokenizer.md.DtfLiEtb.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.B9Y1sq4t.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CweWCIbe.js",
"/ran/assets/src_types_模式匹配.md.Dmsc7J_Z.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DAvtAW_2.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.XBG3mlRt.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CUsGU3FT.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.qZFgVTp_.js",
"/ran/assets/src_types_类型运算.md.jXSOIllB.js",
"/ran/assets/src_article_typescript_calculate.md.BVp530bd.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_tabs_index.md.DA_nuVnY.js",
"/ran/assets/src_ranui_player_index.md.BwUEpWsJ.js",
"/ran/assets/src_ranui_checkbox_index.md.DNSY6Fa2.lean.js",
"/ran/assets/src_article_sort_count_index.md.B9l6SksZ.lean.js",
"/ran/assets/src_ranui_progress_index.md.CZQD9jik.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DO0lR0hj.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.B5ju0vFE.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CS7vcdpQ.js",
"/ran/assets/src_ranuts_file_read_file.md.BWCHqKrZ.js",
"/ran/assets/cn_src_ranui_math_index.md.B3qB2-PA.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CurnDiCd.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.BHcJjo-R.lean.js",
"/ran/assets/src_article_typescript_index.md.CWAW2829.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_types_TS类型.md.Cee53SwZ.js",
"/ran/assets/src_article_sort_quick_index.md.DOmXM_Rf.js",
"/ran/assets/cn_src_ranui_message_index.md.krnyOxzP.js",
"/ran/assets/cn_src_article_sort_select_index.md.BHcJjo-R.js",
"/ran/assets/src_article_sort_select_index.md.Bz1_V0Ch.js",
"/ran/assets/cn_index.md.CIl3gvLP.lean.js",
"/ran/assets/cn_src_article_visual.md.D4yJLltw.js",
"/ran/assets/cn_src_types_类型运算.md.Cac-vSNu.js",
"/ran/assets/cn_src_ranui_button_index.md.COZWNAd-.lean.js",
"/ran/assets/src_ranui_icon_index.md.D4z2gopG.lean.js",
"/ran/assets/src_article_typescript_index.md.CWAW2829.js",
"/ran/assets/src_ranui_skeleton_index.md.BTPC6u_l.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.C4EU-REa.lean.js",
"/ran/assets/src_article_sort_heap_index.md.B1nrky0L.js",
"/ran/assets/cn_src_article_sort_merge_index.md.C1lg1_Rd.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BWnfHS8l.js",
"/ran/assets/cn_src_types_类型运算.md.Cac-vSNu.lean.js",
"/ran/assets/src_article_design_mode.md.CefHovfv.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_babel.md.DgcP1xxF.lean.js",
"/ran/assets/style.CVPVLIRO.css",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DIEgvz0w.js",
"/ran/assets/cn_src_article_typescript_index.md.CuG44IM6.js",
"/ran/assets/cn_src_ranui_popover_index.md.d2nYUksd.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DqDgR6X4.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CNIOfALe.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.C4EU-REa.js",
"/ran/assets/src_ranuts_utils_format_json.md.CTqtbNx2.lean.js",
"/ran/assets/cn_src_article_design_mode.md.DBmx8sAg.js",
"/ran/assets/src_article_functional_programming.md.rI-KK5XB.lean.js",
"/ran/assets/src_ranui_select_index.md.LPArSVl8.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_loading_index.md.DFYgi8gn.lean.js",
"/ran/assets/src_article_sort_heap_index.md.B1nrky0L.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DBVPp5J1.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Bq_ZFP9Q.js",
"/ran/assets/index.md.BkhGsd1y.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_article_sort_quick_index.md.DOmXM_Rf.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_doc_preview.md.upBPIaZd.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.qZFgVTp_.lean.js",
"/ran/assets/cn_src_note_docker.md.BXeELXRv.lean.js",
"/ran/assets/cn_src_note_docker.md.BXeELXRv.js",
"/ran/assets/src_article_javascript_dom_load.md.CaVF3Y6z.js",
"/ran/assets/cn_src_ranui_image_index.md.CrEQuV5x.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.XBG3mlRt.js",
"/ran/assets/src_ranuts_file_write_file.md.CshsnO00.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_imagemin.md.DIiGveg0.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_article_video.md.DpFB8GY8.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranui_index.md.B9hDr23O.js",
"/ran/assets/src_article_design_mode.md.CefHovfv.lean.js",
"/ran/assets/src_types_TS类型.md.B9B4gxb4.lean.js",
"/ran/assets/src_article_sort_index.md.DXG1JGFq.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DsZEPXfB.js",
"/ran/assets/src_ranui_tabs_index.md.DA_nuVnY.lean.js",
"/ran/assets/src_article_sort_radix_index.md.CF2HE5FW.js",
"/ran/assets/src_ranui_checkbox_index.md.DNSY6Fa2.js",
"/ran/assets/src_ranui_image_index.md.CiNuxYq8.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CpTvlhxE.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranui_image_index.md.CiNuxYq8.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranuts_index.md.BwWdErLe.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CBewSTd1.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_math_linear_algebra.md.ao_lzkEw.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_file_watch_file.md.W8fEVDLY.lean.js",
"/ran/assets/cn_src_article_video.md.DpFB8GY8.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.UQRy-cob.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.D71czu4F.lean.js",
"/ran/assets/app.ClXBa_p6.js",
"/ran/assets/cn_src_ranui_tab_index.md.C06O4096.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Dmpnd_Qk.js",
"/ran/assets/src_ranuts_file_file_info.md.fVDOxooU.js",
"/ran/assets/src_ranuts_file_write_file.md.CshsnO00.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Bq_ZFP9Q.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DgCfHPnO.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.DV_aizHb.lean.js",
"/ran/assets/src_ranui_message_index.md.DIOULVBe.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DiV75BRk.js",
"/ran/assets/cn_src_ranui_preview_index.md.C_-I6vPI.lean.js",
"/ran/assets/src_ranui_progress_index.md.CZQD9jik.js",
"/ran/assets/src_ranui_skeleton_index.md.BTPC6u_l.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_article_system_design.md.B9JmZUCZ.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_types_TS类型.md.B9B4gxb4.js",
"/ran/assets/cn_src_ranui_math_index.md.B3qB2-PA.js",
"/ran/assets/cn_src_ranui_progress_index.md.oPM9zWiR.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DqDgR6X4.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_types_模式匹配.md.lBoKnLPf.js",
"/ran/assets/cn_src_ranui_icon_index.md.DK4owY2I.js",
"/ran/assets/src_ranui_player_index.md.BwUEpWsJ.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.B5ju0vFE.js",
"/ran/assets/cn_src_ranui_input_index.md.D71czu4F.js",
"/ran/assets/src_article_sort_count_index.md.B9l6SksZ.js",
"/ran/assets/src_ranui_input_index.md.Cd7PdeW3.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.d2nYUksd.js",
"/ran/assets/src_ranui_button_index.md.B2r0f_6o.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_file_file_info.md.C9YvVu1c.lean.js",
"/ran/assets/src_article_sort_index.md.DXG1JGFq.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DIEgvz0w.lean.js",
"/ran/assets/src_ranuts_index.md.BMeRHo9q.js",
"/ran/assets/src_article_imagemin.md.DIiGveg0.js",
"/ran/assets/cn_src_ranui_select_index.md.BTaBwjgm.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_preview_index.md.DVa8SR9n.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_file_append_file.md.DOKVVkB6.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BBYfJLaf.js",
"/ran/assets/cn_src_note_ubuntu.md.DO0lR0hj.lean.js",
"/ran/assets/src_article_sort_merge_index.md.rHtshxUw.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BBYfJLaf.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.DW1KS3FT.js",
"/ran/assets/src_ranui_select_index.md.LPArSVl8.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_sort_radix_index.md.CF2HE5FW.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_imagemin.md.BE8lUaAc.js",
"/ran/assets/cn_src_note_centos.md.D6BqL6yI.js",
"/ran/assets/src_ranui_popover_index.md.C6oqnDyk.js",
"/ran/assets/cn_src_ranui_preview_index.md.C_-I6vPI.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_ranui_checkbox_index.md.DqxHJHxB.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_article_babel.md.DgcP1xxF.js",
"/ran/assets/cn_src_ranui_modal_index.md.DW1KS3FT.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.2h1UGvLf.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CweWCIbe.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md._a687jqa.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_bundle.md.tFweQiBn.lean.js",
"/ran/assets/src_types_高级类型.md.BPS2YIJ4.js",
"/ran/assets/src_ranui_message_index.md.DIOULVBe.js",
"/ran/assets/cn_src_ranuts_index.md.BwWdErLe.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.lBoKnLPf.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.BF8jT1_E.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BJNQuxGq.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.3PmBFPrr.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CcCRiaMg.js",
"/ran/assets/src_article_sort_select_index.md.Bz1_V0Ch.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Dmpnd_Qk.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.3tJOsYLF.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_types_TS类型.md.Cee53SwZ.lean.js",
"/ran/assets/src_article_sort_merge_index.md.rHtshxUw.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.Dm0l7oHm.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranuts_file_read_dir.md.3tJOsYLF.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DtfLiEtb.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CBewSTd1.lean.js",
"/ran/assets/src_ranui_math_index.md.DOjCmCn6.js",
"/ran/assets/cn_src_ranui_tab_index.md.C06O4096.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Dq4uOonx.js",
"/ran/assets/src_ranuts_utils_task.md.CfYSUnaj.js",
"/ran/assets/src_ranui_popover_index.md.C6oqnDyk.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranuts_file_read_file.md.BWCHqKrZ.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_ranuts_utils_str2xml.md.BWnfHS8l.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.V0ZKac5k.js",
"/ran/assets/src_ranui_tab_index.md.CrOSC13N.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_types_高级类型.md.BqrQq15S.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.COclyNJT.js",
"/ran/assets/cn_src_article_functional_programming.md.BF8jT1_E.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CS7vcdpQ.lean.js",
"/ran/assets/src_article_sort_shell_index.md.D4C8gm9i.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_progress_index.md.oPM9zWiR.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DBVPp5J1.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CuVK-nge.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_types_类型运算.md.jXSOIllB.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BZuyJTSE.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.krnyOxzP.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/index.md.BkhGsd1y.js",
"/ran/assets/src_article_typescript_union_type.md.CdnaIDVS.lean.js",
"/ran/assets/src_ranui_index.md.B9hDr23O.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DiV75BRk.lean.js",
"/ran/assets/src_ranui_modal_index.md.zemssxsW.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.Dj1fCNPE.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.Dj1fCNPE.js",
"/ran/assets/src_ranuts_utils_task.md.CfYSUnaj.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_loading_index.md.DFYgi8gn.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DAvtAW_2.js",
"/ran/assets/cn_src_ranui_radar_index.md.Brllerj2.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CIBXuGEQ.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CUsGU3FT.js",
"/ran/assets/src_ranui_modal_index.md.zemssxsW.lean.js",
"/ran/assets/src_ranui_radar_index.md.x4ujlUGd.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Dq4uOonx.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DHrCQlz5.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.CaVF3Y6z.lean.js",
"/ran/assets/src_ranui_preview_index.md.DVa8SR9n.lean.js",
"/ran/assets/src_ranui_tab_index.md.CrOSC13N.lean.js",
"/ran/assets/src_types_高级类型.md.BPS2YIJ4.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_typescript_union_type.md.CdnaIDVS.js",
"/ran/assets/src_article_sort_insert_index.md.U_pR929p.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.i0yzt-Cb.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.UQRy-cob.js",
"/ran/assets/src_ranui_radar_index.md.x4ujlUGd.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_article_visual.md.D4yJLltw.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_file_append_file.md.DOKVVkB6.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.GbegWsZW.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.ByhsGXFk.js",
"/ran/assets/src_article_typescript_recursion.md.CHV-AG-7.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.B8ewcvyh.lean.js",
"/ran/assets/cn_src_note_centos.md.D6BqL6yI.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_input_index.md.Cd7PdeW3.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/jszip.min--o3_SgQz.CiS0z4ab.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/framework.CSxOtPmm.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/@localSearchIndexcn.Bt3YtaGs.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/index-CVkJ_Xlh.Bu3VHk1l.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Cet4OUP8.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/docx-D5t6JtVt.BnsCdyQq.js",
"/ran/assets/chunks/@localSearchIndexroot.BjD44Pto.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/theme.DKz-XFPF.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.3YBIgQHd.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-HhqG7SJg.B9lKsKkd.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/index.B3hz0EmE.js",
"/ran/assets/chunks/index-D6nXg_bb.DfDkVgUX.js",
"/ran/assets/chunks/VPLocalSearchBox.CdH8NzgN.js",
"/ran/assets/cn_src_article_typescript_pattern.md.COclyNJT.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.C9YvVu1c.js",
"/ran/assets/src_ranuts_file_watch_file.md.W8fEVDLY.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_article_bundle.md.DrNwIOdo.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranui_math_index.md.DOjCmCn6.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CcCRiaMg.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BVp530bd.js",
"/ran/assets/cn_src_ranui_select_index.md.BTaBwjgm.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.ao_lzkEw.js",
"/ran/assets/src_article_sort_bubble_index.md.DgCfHPnO.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CurnDiCd.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md._a687jqa.lean.js",
"/ran/assets/src_ranui_loading_index.md.Bw9uj6Jt.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.3PmBFPrr.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.yeQwS9dK.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DHrCQlz5.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CpTvlhxE.js",
"/ran/assets/src_types_模式匹配.md.Dmsc7J_Z.js",
"/ran/assets/cn_src_article_typescript_recursion.md.lCRGEKZ2.js",
"/ran/assets/cn_src_ranui_image_index.md.CrEQuV5x.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranui_player_index.md.2h1UGvLf.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.CTqtbNx2.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_icon_index.md.D4z2gopG.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.yeQwS9dK.js",
"/ran/assets/cn_src_ranui_button_index.md.COZWNAd-.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DqxHJHxB.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CuVK-nge.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_ranui_index.md.DKkvYVoN.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CNIOfALe.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_index.md.CIl3gvLP.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.i0yzt-Cb.lean.js",
"/ran/assets/cn_src_article_design_mode.md.DBmx8sAg.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.upBPIaZd.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.GbegWsZW.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_sort_shell_index.md.D4C8gm9i.lean.js",
"/ran/assets/cn_src_article_babel.md.BStQB2qj.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CatAOrmm.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_bucket_index.md.B9Y1sq4t.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CatAOrmm.lean.js",
"/ran/assets/src_ranuts_index.md.BMeRHo9q.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.C9h344Uc.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_typescript_union_type.md.V0ZKac5k.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranui_icon_index.md.DK4owY2I.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CrzMVfPT.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.HVrFY_x9.lean.js",
"/ran/assets/cn_src_article_bundle.md.DrNwIOdo.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_article_imagemin.md.BE8lUaAc.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_article_typescript_calculate.md.ByhsGXFk.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/sw1740844066.js",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1740844066";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



