const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/assets/cn_src_ranui_modal_index.md.CmqVB1bD.js",
"/ran/assets/cn_src_article_imagemin.md.DhBkyc5i.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/src_ranui_progress_index.md.DRoczc5_.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.D5kUnoOL.js",
"/ran/assets/cn_src_article_typescript_index.md.CqlMAu2d.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranui_radar_index.md.jybyrWZt.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_functional_programming.md.B_-sZZ5r.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CRu0AZId.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.D7bf3lcH.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CSP0QHtm.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.3cbWZnZk.lean.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/src_ranuts_utils_format_json.md.Cpu6umCz.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.PFbYFhuP.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BRDOStQm.js",
"/ran/assets/src_ranuts_utils_task.md.oustb6nw.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.D5JNDt2c.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CywGLTuK.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_file_watch_file.md.D7bf3lcH.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.CQmwboJh.js",
"/ran/assets/src_ranuts_mode_subscribe.md.EFHTdstP.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BZ8yoJ_l.js",
"/ran/assets/cn_src_ranui_select_index.md.nQbi59dQ.lean.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.uD_W7RBc.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_sort_merge_index.md.C7e0tvsy.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CFD289YU.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_input_index.md.BqEKc_RM.lean.js",
"/ran/assets/src_ranui_index.md.DVBM6xGc.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_babel.md.DUgtx5Xt.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CziigFmx.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.Bn6xWRZT.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.7B-YYOxd.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.DIteSCg5.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CqlMAu2d.lean.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/cn_src_ranui_button_index.md.nqPweoW9.js",
"/ran/assets/src_ranui_popover_index.md.CRURN1--.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_article_typescript_index.md.BZicyQNj.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CdLvFyf3.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CFD289YU.js",
"/ran/assets/src_article_sort_shell_index.md.COT9GuFi.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bjq0znPJ.js",
"/ran/assets/src_article_functional_programming.md.xHGMP0xf.lean.js",
"/ran/assets/src_article_typescript_pattern.md.B8zSgo39.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_bundle.md.DFGg_CVL.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_file_write_file.md.Dnef04fE.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CApLSYMz.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.DSL9eD3e.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.EFHTdstP.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.DXwI0o8W.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_bundler_index.md.CRu0AZId.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D4SHtwPY.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Ly0hpMNB.lean.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_javascript_dom_load.md.Bx0FCAZz.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B-nO4E2C.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.UO1ISw5Q.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/src_article_imagemin.md.ek2uEXQF.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.DIteSCg5.js",
"/ran/assets/src_ranui_checkbox_index.md.x5p4aJ9B.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CO1Khi2O.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Cs7nBZrI.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranui_index.md.DVBM6xGc.js",
"/ran/assets/src_article_typescript_calculate.md.BHH9f89l.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.BnwdgA9-.js",
"/ran/assets/cn_index.md.B41sdfEy.js",
"/ran/assets/src_ranuts_index.md.Jtnn9hFc.lean.js",
"/ran/assets/src_ranui_image_index.md.37wpFQRJ.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/src_ranui_tab_index.md.CR4lByo4.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BxQvv0hZ.lean.js",
"/ran/assets/cn_src_note_docker.md.DCTV0j5x.js",
"/ran/assets/src_ranuts_file_append_file.md.3cbWZnZk.js",
"/ran/assets/cn_src_ranui_loading_index.md.Dtile9Bj.lean.js",
"/ran/assets/cn_src_ranui_index.md.dE2_X-Bs.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.BOMIrHXZ.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BxQvv0hZ.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranui_loading_index.md.BemKKwye.lean.js",
"/ran/assets/src_ranui_button_index.md.LXtH29Hx.lean.js",
"/ran/assets/index.md.nP0wcpVa.lean.js",
"/ran/assets/src_types_模式匹配.md.xfJHnrIA.js",
"/ran/assets/src_article_babel.md.GG4v84W1.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/cn_src_article_typescript_calculate.md.CApLSYMz.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.D6v_nuKx.lean.js",
"/ran/assets/src_article_design_mode.md.DzaQ5z9k.lean.js",
"/ran/assets/app.B2Mf3vDZ.js",
"/ran/assets/src_types_TS类型.md.fO_mWF1K.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_article_sort_insert_index.md.D2F0s337.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bjq0znPJ.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BM7XisPW.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.B98Ft4G_.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.D3dQlpz1.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DAzzi7Zg.js",
"/ran/assets/index.md.nP0wcpVa.js",
"/ran/assets/cn_src_ranui_tab_index.md.DjL_REJu.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BRDOStQm.lean.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_types_高级类型.md.CSnZruaU.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/cn_src_article_system_design.md.DKJXaovG.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.BMDYxeiE.js",
"/ran/assets/cn_src_note_centos.md.K-cGddwo.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_article_doc_preview.md.DQ7x5N0X.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DqYJeb0N.js",
"/ran/assets/src_article_sort_merge_index.md.C7e0tvsy.js",
"/ran/assets/cn_src_article_design_mode.md.RBi4vUXN.js",
"/ran/assets/cn_src_article_system_design.md.DKJXaovG.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_article_sort_select_index.md.ca9BFrow.js",
"/ran/assets/cn_src_types_模式匹配.md.Ej4xRbG7.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CO1Khi2O.js",
"/ran/assets/src_ranui_skeleton_index.md.BVmdITVA.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C_HqS2EW.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DU8JHNPn.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.uD_W7RBc.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DXwI0o8W.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/src_ranui_image_index.md.37wpFQRJ.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.jybyrWZt.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.5k40rR8F.js",
"/ran/assets/cn_src_ranui_message_index.md.BUPEZ_41.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_functional_programming.md.B_-sZZ5r.js",
"/ran/assets/cn_src_note_docker.md.DCTV0j5x.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DhgoNaQD.js",
"/ran/assets/src_ranuts_utils_ocr.md.BnwdgA9-.lean.js",
"/ran/assets/src_article_typescript_pattern.md.B8zSgo39.lean.js",
"/ran/assets/cn_src_note_centos.md.K-cGddwo.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranui_select_index.md.C8g00JEu.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranui_preview_index.md.048rgY1e.lean.js",
"/ran/assets/src_ranui_message_index.md.p5xu5RSs.lean.js",
"/ran/assets/cn_src_types_类型运算.md.D2NmVaeN.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranui_math_index.md.Bme3Kqqd.js",
"/ran/assets/src_ranui_progress_index.md.DRoczc5_.js",
"/ran/assets/src_types_类型运算.md.jDU2XsX1.js",
"/ran/assets/cn_src_ranui_preview_index.md.5k40rR8F.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Cs7nBZrI.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CqwXhw8q.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BFqgWub2.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_types_模式匹配.md.Ej4xRbG7.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranui_tab_index.md.CR4lByo4.js",
"/ran/assets/src_article_sort_shell_index.md.COT9GuFi.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.Bn6xWRZT.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.pq09c6gM.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BFqgWub2.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/src_ranui_input_index.md.BqEKc_RM.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.ChoXiv55.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.XXHacmeo.lean.js",
"/ran/assets/cn_src_ranui_index.md.dE2_X-Bs.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranui_modal_index.md.HpFPZxJT.lean.js",
"/ran/assets/cn_src_article_video.md.CVeUnKtN.js",
"/ran/assets/cn_src_ranui_message_index.md.BUPEZ_41.js",
"/ran/assets/cn_src_ranui_tabs_index.md.XXHacmeo.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranui_icon_index.md.FoI2VQUo.lean.js",
"/ran/assets/src_ranui_math_index.md.Bme3Kqqd.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DmYSt__M.lean.js",
"/ran/assets/src_types_类型运算.md.jDU2XsX1.lean.js",
"/ran/assets/src_article_typescript_union_type.md.CGNGwys2.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_types_高级类型.md.CSnZruaU.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CywGLTuK.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/style.B51h211J.css",
"/ran/assets/src_ranuts_file_file_info.md.DmYSt__M.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DNPX2Iqz.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C_HqS2EW.lean.js",
"/ran/assets/src_article_sort_index.md.afrr2O58.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BHH9f89l.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DU8JHNPn.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CdLvFyf3.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.pq09c6gM.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_popover_index.md.CRURN1--.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/cn_src_article_imagemin.md.DhBkyc5i.js",
"/ran/assets/src_ranui_select_index.md.C8g00JEu.js",
"/ran/assets/src_ranui_modal_index.md.HpFPZxJT.js",
"/ran/assets/src_ranui_icon_index.md.BXIZ8fEZ.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BTFcxfc5.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_preview_index.md.048rgY1e.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DhgoNaQD.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_article_imagemin.md.ek2uEXQF.js",
"/ran/assets/src_article_typescript_union_type.md.CGNGwys2.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranui_image_index.md.-p3fCffF.lean.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/cn_src_ranui_popover_index.md.dmVIl5T3.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/framework.CQmC_4em.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/theme.Bd5Krcvf.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/@localSearchIndexroot.BR8RYtms.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/pdf-DRw1818j.CDLbKYIq.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/pwa-install.es.CyliIjjp.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/index.vUljFQlm.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/VPLocalSearchBox.BO_67nD_.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/@localSearchIndexcn.CWKF9Hj8.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CUKnpuHM.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/index.GTQyCuNX.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_video.md.CVeUnKtN.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CSP0QHtm.js",
"/ran/assets/src_article_sort_insert_index.md.DZMCMw3e.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.UO1ISw5Q.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/cn_src_ranui_input_index.md.DIKLUACe.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_math_linear_algebra.md.D6v_nuKx.js",
"/ran/assets/src_ranuts_utils_format_json.md.Cpu6umCz.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BavifThu.js",
"/ran/assets/cn_src_blockchain_index.md.Bs90CGVY.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_sort_select_index.md.ca9BFrow.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.C1BXoTaU.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranui_tabs_index.md.BGQfztYO.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.Bx0FCAZz.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranui_radar_index.md.C51GBN0P.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.D5kUnoOL.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.BZnwNpfs.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DIKLUACe.lean.js",
"/ran/assets/src_article_typescript_recursion.md.D8PvxRAX.lean.js",
"/ran/assets/src_article_bundle.md.D1wUNSjZ.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_design_mode.md.DzaQ5z9k.js",
"/ran/assets/cn_src_ranuts_index.md.BZ8yoJ_l.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.D_6lOuKJ.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.FoI2VQUo.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranui_modal_index.md.CmqVB1bD.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.B98Ft4G_.lean.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/src_article_ast_parse_tokenizer.md.Ly0hpMNB.js",
"/ran/assets/src_article_sort_radix_index.md.DY2rBZ5e.js",
"/ran/assets/cn_src_article_babel.md.DUgtx5Xt.js",
"/ran/assets/cn_src_ranui_popover_index.md.dmVIl5T3.lean.js",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/src_article_bundle.md.D1wUNSjZ.js",
"/ran/assets/cn_index.md.B41sdfEy.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BgNovzWV.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_types_高级类型.md.DWNgeK1u.js",
"/ran/assets/src_ranui_checkbox_index.md.x5p4aJ9B.js",
"/ran/assets/src_article_typescript_recursion.md.D8PvxRAX.js",
"/ran/assets/src_article_sort_quick_index.md.BpesYv1k.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.DQ7x5N0X.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BM7XisPW.js",
"/ran/assets/cn_src_blockchain_web3.md.BN2EqqXP.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_article_typescript_index.md.BZicyQNj.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BgNovzWV.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/src_ranui_loading_index.md.BemKKwye.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.DgROemsE.lean.js",
"/ran/assets/src_ranui_player_index.md.CK3yfmsK.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.DqYJeb0N.lean.js",
"/ran/assets/cn_src_article_visual.md.BVRA5iCl.lean.js",
"/ran/assets/cn_src_types_类型运算.md.D2NmVaeN.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.2VYBp59A.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DY2rBZ5e.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CYi3thfV.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.2VYBp59A.js",
"/ran/assets/cn_src_types_TS类型.md.DX8mlCoa.js",
"/ran/assets/src_article_sort_index.md.afrr2O58.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_note_ubuntu.md.BMDYxeiE.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_visual.md.BVRA5iCl.js",
"/ran/assets/src_article_babel.md.GG4v84W1.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BG4TL5ss.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.DSL9eD3e.js",
"/ran/assets/cn_src_ranui_tab_index.md.DjL_REJu.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CYi3thfV.js",
"/ran/assets/src_ranuts_file_read_file.md.DgKy-2FC.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B-nO4E2C.lean.js",
"/ran/assets/src_ranui_player_index.md.CK3yfmsK.lean.js",
"/ran/assets/src_ranui_message_index.md.p5xu5RSs.js",
"/ran/assets/src_ranui_skeleton_index.md.BVmdITVA.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.C1BXoTaU.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Um3fJxaq.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Dtile9Bj.js",
"/ran/assets/cn_src_types_高级类型.md.DWNgeK1u.lean.js",
"/ran/assets/src_ranui_icon_index.md.BXIZ8fEZ.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranuts_utils_get_cookie.md.D5JNDt2c.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CziigFmx.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BG4TL5ss.js",
"/ran/assets/src_ranuts_file_watch_file.md.BTFcxfc5.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_sort_index.md.DM2wqQWG.lean.js",
"/ran/assets/src_ranuts_utils_task.md.oustb6nw.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D4SHtwPY.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DgROemsE.js",
"/ran/assets/src_article_sort_bubble_index.md.DAzzi7Zg.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.ChoXiv55.js",
"/ran/assets/src_types_模式匹配.md.xfJHnrIA.lean.js",
"/ran/assets/src_types_TS类型.md.fO_mWF1K.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.D_6lOuKJ.js",
"/ran/assets/src_ranuts_binary_tree_index.md.7B-YYOxd.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BZnwNpfs.js",
"/ran/assets/src_ranui_button_index.md.LXtH29Hx.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CQmwboJh.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BavifThu.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.YtFcezpC.js",
"/ran/assets/cn_src_ranui_math_index.md.BOMIrHXZ.lean.js",
"/ran/assets/cn_src_types_TS类型.md.DX8mlCoa.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DM2wqQWG.js",
"/ran/assets/src_ranui_radar_index.md.C51GBN0P.js",
"/ran/assets/src_ranui_tabs_index.md.BGQfztYO.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_article_sort_count_index.md.BNwPlgze.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.YtFcezpC.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.nqPweoW9.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.DNPX2Iqz.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.DgKy-2FC.lean.js",
"/ran/assets/cn_src_article_bundle.md.DFGg_CVL.js",
"/ran/assets/src_article_sort_count_index.md.BNwPlgze.js",
"/ran/assets/cn_src_ranui_select_index.md.nQbi59dQ.js",
"/ran/assets/src_article_sort_quick_index.md.BpesYv1k.js",
"/ran/assets/cn_src_article_sort_select_index.md.CqwXhw8q.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_insert_index.md.DZMCMw3e.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.Um3fJxaq.js",
"/ran/assets/cn_src_article_sort_insert_index.md.D2F0s337.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_ranui_image_index.md.-p3fCffF.js",
"/ran/assets/cn_src_blockchain_web3.md.BN2EqqXP.js",
"/ran/assets/cn_src_ranui_progress_index.md.PFbYFhuP.lean.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.D3dQlpz1.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_ranuts_index.md.Jtnn9hFc.js",
"/ran/assets/cn_src_article_design_mode.md.RBi4vUXN.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_functional_programming.md.xHGMP0xf.js",
"/ran/assets/src_ranuts_file_write_file.md.Dnef04fE.js",
"/ran/assets/cn_src_blockchain_index.md.Bs90CGVY.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/babel.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/index.html",
"/ran/icon_168.png",
"/ran/manifest.json",
"/ran/icon.png",
"/ran/icon_96.png",
"/ran/icon_192.png",
"/ran/icon_48.png",
"/ran/sw1753084649.js",
"/ran/404.html",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/example.m3u8",
"/ran/home.svg",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_144.png",
"/ran/logo.png",
"/ran/vp-icons.css",
"/ran/icon_72.png",
"/ran/hashmap.json",
"/ran/screenshots_748x1340.jpg",
];
const VERSION = "1753084649";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



