const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/home.svg",
"/ran/logo.png",
"/ran/vp-icons.css",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/assets/cn_src_ranui_select_index.md.BwRPKFHi.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_index.md.DMrdOt-M.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.BGgArQVo.js",
"/ran/assets/src_ranuts_file_watchFile.md.ThlkRAUd.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.BRxzHAiB.js",
"/ran/assets/cn_src_article_sort_index.md.B4WraEPv.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.COQjAtiq.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BwzmrdxA.js",
"/ran/assets/src_article_typescript_calculate.md.DiXMwdQC.js",
"/ran/assets/src_article_typescript_index.md.DdDI5-1_.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_typescript_calculate.md.DBVfIKDm.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranuts_utils_task.md.Cmp7_q9k.js",
"/ran/assets/cn_src_article_sort_count_index.md.CxqG3x_S.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_typescript_unionType.md.DiH_05Yv.js",
"/ran/assets/cn_src_ranui_icon_index.md.D75anbPd.js",
"/ran/assets/src_ranui_checkbox_index.md.CVLyJeuX.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_index.md.BcKuZXWA.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.DIkvxyiH.lean.js",
"/ran/assets/cn_src_note_docker.md.zkpzRI3H.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.COQjAtiq.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DUxZ4ODh.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_types_类型运算.md.DMIRI4U6.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranuts_file_readFile.md.B-ujJkiV.js",
"/ran/assets/cn_src_types_高级类型.md.CT73cZp-.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.XYSeW7I2.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BOHguIBY.js",
"/ran/assets/cn_src_ranui_message_index.md.DTa8b8gm.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.WDo6gt9J.js",
"/ran/assets/src_ranui_radar_index.md.CjWUWBEA.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BGxXiVnE.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_astParse_tokenizer.md.nVTBKaJ6.js",
"/ran/assets/src_ranui_popover_index.md.DpgLeA3q.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.Ch8vPG8B.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DwBX2FBo.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_sort_quick_index.md.Ds778skW.js",
"/ran/assets/cn_src_ranui_radar_index.md.yzf_4OfI.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_ranui_progress_index.md.DQzzMr6E.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BwzmrdxA.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BovNbgRH.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.D7vmehO9.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_index.md.rBQOqhOT.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BMJTHEzc.lean.js",
"/ran/assets/cn_src_article_docPreview.md.B1iSgVQJ.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CKGrX206.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranuts_utils_formatJson.md.DUTsysY5.lean.js",
"/ran/assets/cn_src_article_babel.md.DNZCk45D.js",
"/ran/assets/src_types_TS类型.md.CYzk2GXI.js",
"/ran/assets/src_ranuts_utils_getCookie.md.CX2aN8oM.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CSu7FprC.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CdT_JyMc.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.B1JN8yD2.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.C3tGsJpu.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.B1JN8yD2.js",
"/ran/assets/cn_src_types_TS类型.md.BZtjraqB.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.B5J3bygY.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.guwH0FIT.js",
"/ran/assets/src_ranui_progress_index.md.BHjZk3eC.js",
"/ran/assets/src_article_typescript_calculate.md.DiXMwdQC.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CHrVDG8c.lean.js",
"/ran/assets/src_ranui_modal_index.md.ByFYusic.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C3A8joMA.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_docPreview.md.B1iSgVQJ.js",
"/ran/assets/src_article_typescript_pattern.md.B-8fvRuk.js",
"/ran/assets/src_ranui_skeleton_index.md.Due2tRm0.js",
"/ran/assets/src_article_sort_count_index.md.BQIKgMqw.lean.js",
"/ran/assets/cn_src_article_video.md.qDqUV1sT.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranuts_file_writeFile.md.CY5cao8F.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.RPUhsRBD.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_player_index.md.NdJW3fyv.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BkvglZPn.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_utils_task.md.BfKbmkeb.js",
"/ran/assets/cn_src_article_sort_index.md.B4WraEPv.js",
"/ran/assets/src_ranuts_index.md.CvCGMERr.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CYBcXwKO.lean.js",
"/ran/assets/cn_index.md.rBQOqhOT.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_babel.md.CmMTCSXZ.js",
"/ran/assets/src_article_babel.md.CmMTCSXZ.lean.js",
"/ran/assets/src_ranui_input_index.md.DTz-REBq.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.5wToaOKk.js",
"/ran/assets/src_article_sort_shell_index.md.CpIkr2bx.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.141-_eXS.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CHrVDG8c.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_article_designMode.md.sbOGQIYX.js",
"/ran/assets/src_ranuts_utils_getCookie.md.CX2aN8oM.lean.js",
"/ran/assets/src_ranui_preview_index.md.J5hsoaCP.js",
"/ran/assets/cn_src_types_高级类型.md.CT73cZp-.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CLfHt9-d.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_ranui_tab_index.md.Tz1dzZqT.js",
"/ran/assets/cn_src_ranui_popover_index.md.DWQCWvt3.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CPwyQOCO.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BMJTHEzc.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BGxXiVnE.js",
"/ran/assets/cn_src_article_bundle.md.BEamy8cI.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DUTsysY5.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BK5sHVfM.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranui_checkbox_index.md.CVLyJeuX.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DOrOBpuJ.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_article_sort_select_index.md.CcN1gRJP.js",
"/ran/assets/src_article_typescript_reconstruction.md.Do5PCwb6.js",
"/ran/assets/cn_src_ranui_image_index.md.guwH0FIT.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CPwyQOCO.js",
"/ran/assets/src_ranui_progress_index.md.BHjZk3eC.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_article_sort_merge_index.md.XpITSeBB.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.DrXskuIx.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Cw6HI2-D.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_file_readDir.md.DIkvxyiH.js",
"/ran/assets/cn_src_article_designMode.md.sbOGQIYX.lean.js",
"/ran/assets/src_article_sort_radix_index.md.CqrfxyVm.lean.js",
"/ran/assets/src_article_sort_insert_index.md.Bk1VSahv.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_types_模式匹配.md.CWlCYFQl.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranui_modal_index.md.DVfi_7OV.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranui_math_index.md.DxkY8GCe.js",
"/ran/assets/cn_src_ranui_radar_index.md.yzf_4OfI.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranui_skeleton_index.md.Due2tRm0.lean.js",
"/ran/assets/cn_src_article_bundle.md.BEamy8cI.js",
"/ran/assets/src_ranui_image_index.md.Cdmka4mF.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.BN-II_nu.js",
"/ran/assets/cn_src_ranui_message_index.md.DTa8b8gm.js",
"/ran/assets/src_ranui_message_index.md.BD84rLau.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_article_sort_merge_index.md.XpITSeBB.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_insert_index.md.Bk1VSahv.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_file_fileInfo.md.CusOY1o5.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DYQdKNy-.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_types_模式匹配.md.CWlCYFQl.lean.js",
"/ran/assets/src_types_高级类型.md.D5K8KEXm.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_preview_index.md.P3pNQjQi.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.C3tGsJpu.js",
"/ran/assets/cn_src_note_docker.md.zkpzRI3H.js",
"/ran/assets/cn_src_ranui_select_index.md.BwRPKFHi.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranui_tabs_index.md.BkvglZPn.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BsXKwSb4.js",
"/ran/assets/cn_src_note_ubuntu.md.BHk5ynSW.lean.js",
"/ran/assets/cn_src_note_centos.md.Rn915VHN.js",
"/ran/assets/index.md.R0Wj8jaQ.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_index.md.DMrdOt-M.js",
"/ran/assets/cn_src_note_ubuntu.md.BHk5ynSW.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_note_centos.md.Rn915VHN.lean.js",
"/ran/assets/style.Cf0GkCW3.css",
"/ran/assets/src_types_高级类型.md.D5K8KEXm.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BWAIci8c.lean.js",
"/ran/assets/src_article_sort_shell_index.md.CpIkr2bx.js",
"/ran/assets/cn_src_ranuts_index.md.CH1CBt-z.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.DrXskuIx.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BOHguIBY.lean.js",
"/ran/assets/src_types_类型运算.md.DOeb1cz9.js",
"/ran/assets/src_ranui_math_index.md.CF8ptnU2.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_types_类型运算.md.DOeb1cz9.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.BN-II_nu.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_typescript_pattern.md.CSu7FprC.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_article_typescript_pattern.md.B-8fvRuk.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.CxqG3x_S.js",
"/ran/assets/cn_src_ranui_math_index.md.DxkY8GCe.lean.js",
"/ran/assets/cn_src_article_babel.md.DNZCk45D.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_select_index.md.BgfAY0oa.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_typescript_index.md.DdDI5-1_.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.CZ21xDmb.js",
"/ran/assets/cn_src_article_video.md.qDqUV1sT.js",
"/ran/assets/src_article_imagemin.md.DcC7ctUb.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DBVfIKDm.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.oubZ80K9.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CYBcXwKO.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CsrdLzOJ.js",
"/ran/assets/src_ranuts_utils_ocr.md.BRxzHAiB.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DUxZ4ODh.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.Ch8vPG8B.js",
"/ran/assets/src_article_sort_bubble_index.md.Bs0IcWw3.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/pwa-install.es.DxPypONK.js",
"/ran/assets/chunks/VPLocalSearchBox.QaAnUBD4.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.F0Y_ijJs.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/@localSearchIndexroot.B20ppTyZ.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/@localSearchIndexcn.CNvb_k4_.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/docx-CL2eLEAy.CeFn4yDE.js",
"/ran/assets/chunks/framework.BV76-6_x.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/index.DhHms-Bb.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Dv4uRPfl.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/jszip.min-BYe1vsVj.gZt8O5Et.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/theme.CoHafcWD.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/index-C4uw_AYE.PHIOAX6e.js",
"/ran/assets/chunks/index-016PY8Cn.CYTW0v9U.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/src_article_bundle.md.D86y3659.js",
"/ran/assets/src_ranui_modal_index.md.ByFYusic.js",
"/ran/assets/cn_src_article_typescript_recursion.md.AetEuKEK.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CsrdLzOJ.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CH1CBt-z.js",
"/ran/assets/src_article_sort_heap_index.md.cCvKr3Es.js",
"/ran/assets/cn_src_article_visual.md.DE7a7mlO.lean.js",
"/ran/assets/app.DlIyBf1s.js",
"/ran/assets/cn_src_ranui_button_index.md.BRfmqboi.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DqdEGl5f.js",
"/ran/assets/src_ranui_radar_index.md.CjWUWBEA.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranui_player_index.md.BahFo-Ly.js",
"/ran/assets/src_article_typescript_unionType.md.Dg6adliI.js",
"/ran/assets/src_ranui_message_index.md.BD84rLau.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_article_typescript_reconstruction.md.Do5PCwb6.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Cw6HI2-D.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BovNbgRH.js",
"/ran/assets/src_ranuts_utils_task.md.Cmp7_q9k.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DMIRI4U6.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_astParse_tokenizer.md.nVTBKaJ6.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CdT_JyMc.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.Tz1dzZqT.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CusOY1o5.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.CDqRX2mJ.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_skeleton_index.md.DYQdKNy-.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.xJUMkFuY.js",
"/ran/assets/index.md.R0Wj8jaQ.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.xJUMkFuY.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BRfmqboi.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BsXKwSb4.lean.js",
"/ran/assets/src_ranui_player_index.md.NdJW3fyv.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_article_visual.md.DE7a7mlO.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_ranui_player_index.md.BahFo-Ly.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DwBX2FBo.js",
"/ran/assets/src_ranui_loading_index.md.GelLwpRp.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.B3V5Bh-t.js",
"/ran/assets/src_ranui_button_index.md.CCc6Fali.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_file_writeFile.md.CY5cao8F.js",
"/ran/assets/src_ranui_popover_index.md.DpgLeA3q.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DOrOBpuJ.lean.js",
"/ran/assets/src_ranui_icon_index.md.Cvk4mUbv.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Die3dUAz.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CKGrX206.lean.js",
"/ran/assets/src_article_designMode.md.CKyD-CZA.js",
"/ran/assets/src_ranuts_file_readFile.md.B-ujJkiV.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.oubZ80K9.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_readDir.md.Cii79SSs.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C3A8joMA.js",
"/ran/assets/src_article_sort_count_index.md.BQIKgMqw.js",
"/ran/assets/src_ranuts_bundler_index.md.CZ21xDmb.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DbgJtPrx.js",
"/ran/assets/cn_src_ranui_tabs_index.md.RPUhsRBD.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DbgJtPrx.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Die3dUAz.lean.js",
"/ran/assets/src_ranui_tab_index.md.BAHoJ_wJ.js",
"/ran/assets/src_ranui_loading_index.md.GelLwpRp.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_article_typescript_recursion.md.DL1iMkb8.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CDqRX2mJ.lean.js",
"/ran/assets/src_ranui_select_index.md.y3rAqsD2.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_sort_select_index.md.BgfAY0oa.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_preview_index.md.P3pNQjQi.js",
"/ran/assets/src_ranuts_file_watchFile.md.ThlkRAUd.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_article_sort_select_index.md.CcN1gRJP.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BK5sHVfM.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BWAIci8c.js",
"/ran/assets/src_article_imagemin.md.DcC7ctUb.js",
"/ran/assets/src_ranui_tab_index.md.BAHoJ_wJ.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DjtY1D_G.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DjtY1D_G.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranui_modal_index.md.DVfi_7OV.lean.js",
"/ran/assets/src_article_sort_heap_index.md.cCvKr3Es.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Cj5-G90t.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_image_index.md.Cdmka4mF.js",
"/ran/assets/src_article_typescript_unionType.md.Dg6adliI.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.D7vmehO9.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.Cii79SSs.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.5wToaOKk.lean.js",
"/ran/assets/src_article_sort_index.md.1tut_RBb.js",
"/ran/assets/src_article_sort_bubble_index.md.Bs0IcWw3.lean.js",
"/ran/assets/src_article_bundle.md.D86y3659.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_index.md.BcKuZXWA.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_math_index.md.CF8ptnU2.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.CZPeZdyr.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.AetEuKEK.js",
"/ran/assets/cn_src_article_sort_shell_index.md.XYSeW7I2.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Cj5-G90t.js",
"/ran/assets/cn_src_article_imagemin.md.Dq0UL9Cc.js",
"/ran/assets/cn_src_article_imagemin.md.Dq0UL9Cc.lean.js",
"/ran/assets/src_article_sort_radix_index.md.CqrfxyVm.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.B5J3bygY.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranuts_index.md.CvCGMERr.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranui_input_index.md.DTz-REBq.js",
"/ran/assets/src_article_sort_quick_index.md.Ds778skW.lean.js",
"/ran/assets/src_article_sort_index.md.1tut_RBb.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DL1iMkb8.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DiH_05Yv.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DqdEGl5f.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranui_popover_index.md.DWQCWvt3.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_loading_index.md.CZPeZdyr.js",
"/ran/assets/cn_src_types_模式匹配.md.B3V5Bh-t.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranui_select_index.md.y3rAqsD2.js",
"/ran/assets/src_ranui_icon_index.md.Cvk4mUbv.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BfKbmkeb.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranui_button_index.md.CCc6Fali.js",
"/ran/assets/src_ranui_preview_index.md.J5hsoaCP.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.BGgArQVo.lean.js",
"/ran/assets/src_types_TS类型.md.CYzk2GXI.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.D75anbPd.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_types_TS类型.md.BZtjraqB.js",
"/ran/assets/src_article_functionalProgramming.md.WnWjuOKA.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_article_typescript_index.md.141-_eXS.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_functionalProgramming.md.WnWjuOKA.js",
"/ran/assets/src_article_javascript_domLoad.md.WDo6gt9J.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CLfHt9-d.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DQzzMr6E.lean.js",
"/ran/assets/src_article_designMode.md.CKyD-CZA.lean.js",
"/ran/404.html",
"/ran/manifest.json",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/babel.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/bundle.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/TS类型.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/icon_168.png",
"/ran/icon_48.png",
"/ran/sw1734091548.js",
"/ran/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/icon.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/icon_192.png",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/index.html",
"/ran/icon_144.png",
];
const VERSION = "1734091548";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



