const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.LCUiF4xV.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_merge_index.md.CZBK-hqq.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B-4NqS_1.lean.js",
"/ran/assets/src_article_typescript_union_type.md.B90kg2r6.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_ranuts_file_append_file.md.Dxtmp-o_.js",
"/ran/assets/cn_src_ranuts_index.md.FsrxuKjt.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BHe8R_3f.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_preview_index.md.BBmGzi0J.js",
"/ran/assets/cn_src_ranui_progress_index.md.BFDhRaEQ.js",
"/ran/assets/cn_src_ranui_math_index.md.DeB8yN6p.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_functional_programming.md.DYSIXLMG.js",
"/ran/assets/cn_src_types_模式匹配.md.BtkSm0cT.lean.js",
"/ran/assets/cn_src_types_类型运算.md.jhmGr85R.js",
"/ran/assets/src_article_imagemin.md.Cc9A61fA.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranuts_utils_str2xml.md.CKhpvrMH.js",
"/ran/assets/src_ranui_button_index.md.BzXGsnoO.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Q66LnHKh.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.Nwi6Vp0g.js",
"/ran/assets/src_ranui_math_index.md.B6VNOW4k.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BT0DqW8g.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_types_高级类型.md.Cg7vfN9E.js",
"/ran/assets/src_ranui_modal_index.md.DPIMJzJq.js",
"/ran/assets/src_article_sort_insert_index.md.Dh2V58IR.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Co35PmFK.lean.js",
"/ran/assets/src_ranui_message_index.md.CsEzfGKR.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DY1Y04nK.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.CKhpvrMH.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.B1odsqIG.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Dw_bOSsD.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_functional_programming.md.Dd6A_THF.lean.js",
"/ran/assets/cn_src_types_类型运算.md.jhmGr85R.lean.js",
"/ran/assets/src_ranui_math_index.md.B6VNOW4k.js",
"/ran/assets/src_ranuts_utils_format_json.md.FUtBSs6m.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.McaPolxi.js",
"/ran/assets/src_article_typescript_calculate.md.t59j3hUI.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.C8QtIeCw.js",
"/ran/assets/index.md.Cirq16VA.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Bu8CeSpt.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_article_sort_select_index.md.AeMOpBvP.js",
"/ran/assets/src_ranui_skeleton_index.md.CHS3glwH.js",
"/ran/assets/src_ranuts_binary_tree_index.md.T-4iuT8C.js",
"/ran/assets/src_ranuts_utils_task.md.B-AtjYt8.lean.js",
"/ran/assets/src_article_typescript_recursion.md.Ddf5A42I.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.Bv62yI-R.js",
"/ran/assets/cn_src_ranui_index.md.CJqVbvKI.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_radar_index.md.BJZp3hP0.lean.js",
"/ran/assets/index.md.Cirq16VA.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.znBIolUD.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_ranui_message_index.md.B1odsqIG.js",
"/ran/assets/src_article_sort_bubble_index.md.DJT_0bzj.lean.js",
"/ran/assets/src_article_sort_count_index.md.CmJDf14U.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CClZ7V_g.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.T-4iuT8C.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.1VX9CmFo.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BbzDvR_K.js",
"/ran/assets/cn_src_article_system_design.md.Clyx5r7w.js",
"/ran/assets/src_article_sort_count_index.md.CmJDf14U.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CP3sq7Ws.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CZBK-hqq.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_tab_index.md.BFyEMqiH.js",
"/ran/assets/src_ranui_tab_index.md.M9AZPU0I.js",
"/ran/assets/src_article_sort_heap_index.md.Cj--1vc1.js",
"/ran/assets/src_article_sort_index.md.C_o70C0j.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BfAORPaQ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BqmySsq1.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cr94mnSa.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.C8ZFeoUe.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranui_radar_index.md.BHk8oVg9.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D8eP6lD3.js",
"/ran/assets/src_ranuts_file_write_file.md.Dd6dCxvE.js",
"/ran/assets/src_ranui_progress_index.md.D-iGh0Sw.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_typescript_calculate.md.DfQ0O7kx.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranuts_file_file_info.md.EuTJIfI8.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DorzGUF7.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DPr932tg.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DorzGUF7.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.G2WT47fC.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_article_imagemin.md.B4-S3h48.js",
"/ran/assets/src_ranui_loading_index.md.CsurOKAJ.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.qLMvkroB.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranuts_index.md.FsrxuKjt.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_babel.md.WoJDJkAq.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DJT_0bzj.js",
"/ran/assets/src_article_typescript_recursion.md.Ddf5A42I.js",
"/ran/assets/src_article_sort_shell_index.md.nsWSAr2x.js",
"/ran/assets/cn_src_article_sort_count_index.md.DgmE68YF.js",
"/ran/assets/src_ranuts_file_read_dir.md.BqkxhXwv.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranui_modal_index.md.BccwThh4.lean.js",
"/ran/assets/src_article_sort_quick_index.md.B4kAA1i1.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranuts_file_read_file.md.CP3sq7Ws.js",
"/ran/assets/src_ranui_select_index.md.BCbi_HrW.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DTsQ3-26.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranuts_file_file_info.md.Bjhpt1M3.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_index.md.C-6dLaEf.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DgmE68YF.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_functional_programming.md.DYSIXLMG.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.ydE0NDXl.lean.js",
"/ran/assets/cn_src_note_docker.md.DVnJf-lb.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.1HCJDrTp.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CxVePGG5.lean.js",
"/ran/assets/cn_src_article_video.md.BJVOEBnF.js",
"/ran/assets/src_ranui_player_index.md.DCKPq5Wr.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DbToGPsI.lean.js",
"/ran/assets/src_article_design_mode.md.CGsFZdSp.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DZePFkPu.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.AaQ6uk8C.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BJZp3hP0.js",
"/ran/assets/src_ranui_index.md.Cu2fWPfu.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.EQgvUMdz.js",
"/ran/assets/src_ranui_tabs_index.md.BfAORPaQ.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CjsxEm78.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BnwGDNnG.lean.js",
"/ran/assets/cn_src_note_centos.md.DKk95_UA.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.Drz2Dv91.js",
"/ran/assets/src_article_sort_insert_index.md.Dh2V58IR.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_sort_radix_index.md.BbzDvR_K.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.C8QtIeCw.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BHe8R_3f.js",
"/ran/assets/cn_src_ranui_popover_index.md.D-LySrRb.js",
"/ran/assets/src_article_sort_shell_index.md.nsWSAr2x.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_index.md.BOuI-UQn.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BqmySsq1.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.Dd6A_THF.js",
"/ran/assets/cn_src_article_imagemin.md.B4-S3h48.lean.js",
"/ran/assets/cn_src_article_sort_index.md.CNuWa4wN.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.PU9MLvKa.js",
"/ran/assets/src_ranuts_index.md.C-6dLaEf.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_sort_heap_index.md.Cj--1vc1.lean.js",
"/ran/assets/src_article_imagemin.md.Cc9A61fA.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CmkDCEj2.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.CgsZ4w3D.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.B70adaZL.lean.js",
"/ran/assets/src_types_类型运算.md.DiLZaa1H.js",
"/ran/assets/cn_src_ranui_index.md.CJqVbvKI.js",
"/ran/assets/src_article_typescript_union_type.md.B90kg2r6.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.f1Vt3sde.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranui_index.md.Cu2fWPfu.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.D-LySrRb.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DfQ0O7kx.lean.js",
"/ran/assets/cn_src_article_sort_index.md.CNuWa4wN.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.ydE0NDXl.js",
"/ran/assets/cn_src_article_sort_select_index.md.Cb1jg-BP.js",
"/ran/assets/cn_src_article_sort_select_index.md.Cb1jg-BP.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.1HCJDrTp.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.Nwi6Vp0g.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.BFDhRaEQ.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CIB8Y5km.lean.js",
"/ran/assets/src_ranui_image_index.md.CzIMNfte.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CNXirrHE.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.Cb25Nbex.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_article_javascript_dom_load.md.DDdAfL9r.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.qLMvkroB.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_typescript_pattern.md.EQgvUMdz.lean.js",
"/ran/assets/src_article_sort_quick_index.md.B4kAA1i1.lean.js",
"/ran/assets/style.CfDWePi6.css",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_design_mode.md.CGsFZdSp.js",
"/ran/assets/src_article_sort_index.md.C_o70C0j.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_ranui_tab_index.md.M9AZPU0I.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Bu8CeSpt.js",
"/ran/assets/src_ranui_icon_index.md.iFEFpM7i.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B-4NqS_1.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.f1Vt3sde.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BiVsAeXx.js",
"/ran/assets/src_ranuts_file_read_file.md.CgsZ4w3D.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Bad7277S.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_checkbox_index.md.Csy3pNpC.js",
"/ran/assets/src_ranuts_file_write_file.md.Dd6dCxvE.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.McaPolxi.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_pattern.md.Cpaliwyv.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.B8ZJIueO.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.BccwThh4.js",
"/ran/assets/cn_src_types_模式匹配.md.BtkSm0cT.js",
"/ran/assets/cn_src_article_typescript_index.md.1VX9CmFo.js",
"/ran/assets/src_article_typescript_pattern.md.Cpaliwyv.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CjsxEm78.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Q66LnHKh.js",
"/ran/assets/src_ranui_preview_index.md.DmMALrgj.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_typescript_index.md.DDKLXi5p.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_bundle.md.FLh7ZiEr.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.znBIolUD.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_utils_task.md.B-AtjYt8.js",
"/ran/assets/cn_src_types_TS类型.md.DtQpzl0Q.js",
"/ran/assets/cn_src_note_docker.md.DVnJf-lb.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BHSIkowo.lean.js",
"/ran/assets/src_types_TS类型.md.DQ6q4kJe.js",
"/ran/assets/src_ranui_modal_index.md.DPIMJzJq.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_index.md.BOuI-UQn.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CwCAS8qh.js",
"/ran/assets/src_ranuts_utils_ocr.md.Cb25Nbex.js",
"/ran/assets/cn_src_note_centos.md.DKk95_UA.js",
"/ran/assets/src_ranui_select_index.md.BCbi_HrW.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_button_index.md.BzXGsnoO.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.C8ZFeoUe.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CNXirrHE.lean.js",
"/ran/assets/cn_src_article_design_mode.md.T0eGG9ui.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DZePFkPu.js",
"/ran/assets/src_article_typescript_calculate.md.t59j3hUI.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.DeB8yN6p.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.DbToGPsI.js",
"/ran/assets/cn_src_article_bundle.md.Do20E_Ld.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CClZ7V_g.js",
"/ran/assets/cn_src_article_doc_preview.md.BT0DqW8g.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.AaQ6uk8C.js",
"/ran/assets/cn_src_ranui_select_index.md.CIB8Y5km.js",
"/ran/assets/src_ranui_popover_index.md.uenjJEhU.lean.js",
"/ran/assets/src_article_sort_select_index.md.AeMOpBvP.lean.js",
"/ran/assets/src_ranui_image_index.md.CzIMNfte.lean.js",
"/ran/assets/src_ranui_progress_index.md.D-iGh0Sw.js",
"/ran/assets/src_ranui_player_index.md.DCKPq5Wr.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_types_高级类型.md.Cg7vfN9E.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CBI1D2BY.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_typescript_index.md.DDKLXi5p.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DY1Y04nK.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.Dxtmp-o_.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.sdcgnvf-.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.EuTJIfI8.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranui_loading_index.md.D45Han3R.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DTsQ3-26.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_system_design.md.Clyx5r7w.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DaGiio8a.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_video.md.BJVOEBnF.lean.js",
"/ran/assets/cn_src_article_design_mode.md.T0eGG9ui.lean.js",
"/ran/assets/cn_src_article_visual.md.Ct_8ZG6L.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CmkDCEj2.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D8eP6lD3.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_bundle.md.FLh7ZiEr.js",
"/ran/assets/src_types_模式匹配.md.BksTaIcC.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.COTOEVCX.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/VPLocalSearchBox.DNlcFe-l.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/index.BXHq4Ba_.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/@localSearchIndexcn.BnlXLVK-.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/theme.ZMe2Ue56.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/pwa-install.es._Hs-QQNl.js",
"/ran/assets/chunks/@localSearchIndexroot.WfzqsJXi.js",
"/ran/assets/src_types_模式匹配.md.BksTaIcC.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BHSIkowo.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/app.9w7NeT8I.js",
"/ran/assets/src_article_typescript_reconstruction.md.B8ZJIueO.js",
"/ran/assets/cn_src_ranui_tab_index.md.BFyEMqiH.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BGz5z6f6.js",
"/ran/assets/src_ranui_checkbox_index.md.Csy3pNpC.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DaGiio8a.js",
"/ran/assets/src_types_高级类型.md.C6paSL1Y.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CwCAS8qh.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.FUtBSs6m.js",
"/ran/assets/cn_src_types_TS类型.md.DtQpzl0Q.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.D45Han3R.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cr94mnSa.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Bad7277S.js",
"/ran/assets/cn_src_article_babel.md.BnFgn4C7.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.BqkxhXwv.lean.js",
"/ran/assets/src_types_类型运算.md.DiLZaa1H.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BBmGzi0J.lean.js",
"/ran/assets/src_ranui_input_index.md.BEcpULxd.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_article_bundle.md.Do20E_Ld.js",
"/ran/assets/src_ranui_preview_index.md.DmMALrgj.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_types_高级类型.md.C6paSL1Y.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.B70adaZL.js",
"/ran/assets/cn_src_ranui_button_index.md.DmETmAIO.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranui_popover_index.md.uenjJEhU.js",
"/ran/assets/src_article_babel.md.WoJDJkAq.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DPr932tg.js",
"/ran/assets/cn_src_ranui_button_index.md.DmETmAIO.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_article_sort_shell_index.md.BTEiA8wI.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_javascript_dom_load.md.DDdAfL9r.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.Bjhpt1M3.js",
"/ran/assets/src_types_TS类型.md.DQ6q4kJe.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.CxVePGG5.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.PU9MLvKa.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.G2WT47fC.lean.js",
"/ran/assets/src_ranui_input_index.md.BEcpULxd.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.LCUiF4xV.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CHS3glwH.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_typescript_union_type.md.BnwGDNnG.js",
"/ran/assets/cn_src_article_visual.md.Ct_8ZG6L.js",
"/ran/assets/cn_src_article_babel.md.BnFgn4C7.js",
"/ran/assets/src_ranui_loading_index.md.CsurOKAJ.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_message_index.md.CsEzfGKR.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Dw_bOSsD.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Co35PmFK.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CBI1D2BY.js",
"/ran/assets/cn_src_ranui_image_index.md.Drz2Dv91.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranuts_file_watch_file.md.DzyyNckB.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_article_sort_shell_index.md.BTEiA8wI.js",
"/ran/assets/cn_src_ranui_player_index.md.BGz5z6f6.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.Bv62yI-R.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BiVsAeXx.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_skeleton_index.md.sdcgnvf-.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_file_watch_file.md.DzyyNckB.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_radar_index.md.BHk8oVg9.lean.js",
"/ran/assets/src_ranui_icon_index.md.iFEFpM7i.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/sw1744956957.js",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1744956957";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



