const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_merge_index.md.Cn4s7FCS.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.NfxQzHzh.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BhsZ5UnC.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DlhtxHIh.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_typescript_union_type.md.CKY5wfkO.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.aqXLaMIL.js",
"/ran/assets/src_ranui_input_index.md.Bu7mzQN_.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranuts_index.md.B0BpypW9.lean.js",
"/ran/assets/src_ranui_button_index.md.8-yCMYhb.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DWp06ClF.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_typescript_calculate.md.tlfH2rGV.js",
"/ran/assets/cn_src_article_sort_heap_index.md.D8Stz9-S.js",
"/ran/assets/src_ranui_popover_index.md.Dw30yoxT.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranui_loading_index.md.D9-0lRYI.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Dv4VD_zy.lean.js",
"/ran/assets/src_article_imagemin.md.D3PHD-Pt.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_types_模式匹配.md.D9Tx5Vxt.js",
"/ran/assets/src_ranui_preview_index.md.Cm__YtK6.js",
"/ran/assets/src_article_sort_heap_index.md.qGs7SdOQ.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CzarTtvp.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DinPS3-F.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_index.md.D1TGxaU0.js",
"/ran/assets/cn_src_note_centos.md.BPHXk6bx.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.Cestl4F9.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DDwPnk_L.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Dv4VD_zy.js",
"/ran/assets/src_ranui_progress_index.md.CY4qUTxW.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.Cm4mn3aK.js",
"/ran/assets/cn_src_note_docker.md.BJD-He5c.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C-R4Wh1-.js",
"/ran/assets/src_article_typescript_pattern.md.BjHZNVZb.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_visual.md.C2AwrUHj.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.U1Jh6XXE.js",
"/ran/assets/cn_src_article_typescript_index.md.B_8mRm0A.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BjHZNVZb.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B5K7hgi9.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DSuCPCrQ.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.N4uLNFFP.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.B7NFqsq-.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.BaYK2V35.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.ClKeeS1F.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Bd8fpM6g.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CpM1DFoJ.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.Bksr1wfa.lean.js",
"/ran/assets/src_ranui_loading_index.md.BOBoujqQ.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CFTc3Q0g.js",
"/ran/assets/cn_src_article_sort_quick_index.md.eEEdOZFH.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.R8arn3lL.js",
"/ran/assets/src_ranui_image_index.md.CV5pTiyW.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_types_TS类型.md.CTKjmyYM.js",
"/ran/assets/src_article_babel.md.CYnDfBKG.js",
"/ran/assets/cn_src_article_typescript_index.md.B_8mRm0A.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranui_message_index.md.t0VQUkCF.js",
"/ran/assets/cn_src_article_sort_index.md.CXUSsJmZ.js",
"/ran/assets/cn_src_article_doc_preview.md.CekLLtFP.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DSuCPCrQ.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B2VmeOZY.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BrLA-z5h.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.1MvZOeO_.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DKBmtUX0.js",
"/ran/assets/src_ranuts_utils_task.md.EErFDnNF.js",
"/ran/assets/cn_src_ranui_modal_index.md.BL1Z3pig.lean.js",
"/ran/assets/src_article_babel.md.CYnDfBKG.lean.js",
"/ran/assets/src_ranui_icon_index.md.CFGOdKXo.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.qtCjmma7.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DkNAYd72.js",
"/ran/assets/src_ranui_select_index.md.Bh5bXfXy.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.C-OmWDXh.js",
"/ran/assets/src_article_sort_radix_index.md.DrzCmgNK.js",
"/ran/assets/src_ranui_radar_index.md.C11mDNR_.js",
"/ran/assets/style.CVPVLIRO.css",
"/ran/assets/src_ranui_button_index.md.8-yCMYhb.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.dGM11CVF.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BuVpreFX.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DKBmtUX0.lean.js",
"/ran/assets/cn_src_ranui_index.md.D1TGxaU0.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_index.md.CyXmKzEO.js",
"/ran/assets/src_ranuts_file_read_dir.md.ji9IcK3n.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BNmuxd0p.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.R8arn3lL.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Bxqb6UhX.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DDwPnk_L.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranui_button_index.md.DeYUts2x.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.Cestl4F9.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CQB8Ht4I.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BZmiO8MM.js",
"/ran/assets/src_ranui_icon_index.md.CFGOdKXo.js",
"/ran/assets/cn_src_ranui_select_index.md.DNeFXIE7.lean.js",
"/ran/assets/src_article_typescript_union_type.md.CKY5wfkO.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.9fEtNlse.js",
"/ran/assets/cn_src_ranui_tab_index.md.B9BhdzGz.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_typescript_calculate.md.c2vewJZg.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_article_imagemin.md.B9f2Ry16.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranui_progress_index.md.CY4qUTxW.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DTYBaBC3.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CWfMWQzQ.js",
"/ran/assets/src_ranui_message_index.md.t0VQUkCF.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Bd8fpM6g.lean.js",
"/ran/assets/src_article_typescript_recursion.md.D9GkmjQ1.js",
"/ran/assets/cn_src_types_模式匹配.md.Bksr1wfa.js",
"/ran/assets/src_article_sort_index.md.IHg1sAQS.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.CAzDi3q7.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BZmiO8MM.lean.js",
"/ran/assets/src_ranui_preview_index.md.Cm__YtK6.lean.js",
"/ran/assets/src_article_design_mode.md.CshMN-rP.js",
"/ran/assets/src_ranuts_file_file_info.md.DXYOKQce.lean.js",
"/ran/assets/src_ranui_index.md.BvH1TSZ3.js",
"/ran/assets/src_ranui_popover_index.md.Dw30yoxT.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_article_functional_programming.md.C8MPkZzd.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DeYUts2x.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DrzCmgNK.lean.js",
"/ran/assets/src_article_typescript_index.md.D7wMzHSh.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.Ci_7K7y6.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.D9-0lRYI.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_sort_heap_index.md.qGs7SdOQ.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_file_write_file.md.BRHNLvaT.js",
"/ran/assets/cn_src_article_typescript_calculate.md.tlfH2rGV.lean.js",
"/ran/assets/cn_src_article_imagemin.md.B9f2Ry16.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.8iPmgq9I.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.1v1xNd7T.js",
"/ran/assets/cn_src_ranui_icon_index.md.DTYBaBC3.lean.js",
"/ran/assets/cn_src_types_TS类型.md.CTKjmyYM.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_visual.md.C2AwrUHj.lean.js",
"/ran/assets/app.Dq-AyH-s.js",
"/ran/assets/src_ranui_math_index.md.B8eeValz.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.D-ZNp4Re.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_sort_count_index.md.kUGa0eyU.lean.js",
"/ran/assets/cn_src_article_design_mode.md.BeI5nshP.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranui_modal_index.md.DAJsf5Rm.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.dGM11CVF.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C_0xmoc2.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CEUGxUed.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.C7J1JrN_.js",
"/ran/assets/src_ranui_loading_index.md.BOBoujqQ.js",
"/ran/assets/src_article_javascript_dom_load.md.BuS1SzoV.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BNmuxd0p.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.Bxqb6UhX.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.BOYh6uFG.lean.js",
"/ran/assets/cn_src_article_bundle.md.D--9E8K4.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Ca_GuzGH.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.1v1xNd7T.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.eEEdOZFH.js",
"/ran/assets/cn_src_ranui_input_index.md.CGzKkDEb.js",
"/ran/assets/cn_src_article_functional_programming.md.CGNfB86_.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BWqDU3ub.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_sort_shell_index.md.wupfbyiu.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.3o7NSbi_.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C-R4Wh1-.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.B7WHoJwI.js",
"/ran/assets/cn_src_article_video.md.CPY2tlUl.lean.js",
"/ran/assets/src_ranui_image_index.md.CV5pTiyW.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Cm4mn3aK.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_article_sort_select_index.md.HyO0tmrq.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CwBWnW9n.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BDEulRkK.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.Ci_7K7y6.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C_0xmoc2.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CwBWnW9n.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranui_select_index.md.Bh5bXfXy.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranui_radar_index.md.CGiUYTL-.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.B7NFqsq-.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.aqXLaMIL.lean.js",
"/ran/assets/src_article_sort_quick_index.md.D-Oft3e5.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.j85RvZJ1.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_article_math_linear_algebra.md.ClKeeS1F.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_tab_index.md.BQuxA06h.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_article_typescript_index.md.D7wMzHSh.js",
"/ran/assets/cn_src_ranui_select_index.md.DNeFXIE7.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_radar_index.md.CGiUYTL-.js",
"/ran/assets/cn_src_article_sort_select_index.md.-2MlIngK.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BfI2-bNS.js",
"/ran/assets/src_types_类型运算.md.BXZmJEbH.lean.js",
"/ran/assets/src_article_functional_programming.md.C8MPkZzd.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Ca_GuzGH.js",
"/ran/assets/cn_src_article_babel.md.BHtH4ffc.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.EfJtsrIS.lean.js",
"/ran/assets/src_ranui_math_index.md.B8eeValz.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_functional_programming.md.CGNfB86_.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_video.md.CPY2tlUl.js",
"/ran/assets/src_ranuts_file_read_file.md.NfxQzHzh.js",
"/ran/assets/src_types_TS类型.md.CagEpLNA.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BuVpreFX.lean.js",
"/ran/assets/src_article_sort_insert_index.md.XuG-Pugj.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Cn4s7FCS.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BfI2-bNS.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CQB8Ht4I.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Dfmep83K.lean.js",
"/ran/assets/cn_src_article_bundle.md.D--9E8K4.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_heap_index.md.D8Stz9-S.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_tabs_index.md.CzarTtvp.lean.js",
"/ran/assets/src_types_高级类型.md.CQDLL1vu.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.U1Jh6XXE.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_checkbox_index.md.DlhtxHIh.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BDEulRkK.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranuts_bundler_index.md.BOYh6uFG.js",
"/ran/assets/src_types_TS类型.md.CagEpLNA.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DinPS3-F.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BgXEchLX.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BxUkiR84.js",
"/ran/assets/cn_src_article_design_mode.md.BeI5nshP.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_sort_bucket_index.md.9fEtNlse.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DXYOKQce.js",
"/ran/assets/cn_index.md.CuOtlxQZ.js",
"/ran/assets/src_article_sort_count_index.md.kUGa0eyU.js",
"/ran/assets/cn_src_article_sort_select_index.md.-2MlIngK.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BWqDU3ub.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Btb8bhCu.lean.js",
"/ran/assets/cn_src_article_system_design.md.8axGbTlW.js",
"/ran/assets/src_ranui_tab_index.md.BQuxA06h.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.C-OmWDXh.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.8iPmgq9I.js",
"/ran/assets/cn_src_types_类型运算.md.B5K7hgi9.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DHYQ4dP7.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.drsslgGN.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.N4uLNFFP.js",
"/ran/assets/src_ranuts_index.md.B0BpypW9.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DHYQ4dP7.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_utils_filter_obj.md.Dptf5fgv.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CyXmKzEO.lean.js",
"/ran/assets/cn_src_article_babel.md.BHtH4ffc.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CEUGxUed.lean.js",
"/ran/assets/src_ranui_player_index.md.4U2-blNx.js",
"/ran/assets/cn_index.md.CuOtlxQZ.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_design_mode.md.CshMN-rP.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CWfMWQzQ.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_article_sort_index.md.CXUSsJmZ.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CpM1DFoJ.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/index.md.Cyjn71m9.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.BRHNLvaT.lean.js",
"/ran/assets/src_article_sort_index.md.IHg1sAQS.js",
"/ran/assets/src_types_高级类型.md.CQDLL1vu.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BgXEchLX.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_insert_index.md.XuG-Pugj.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/@localSearchIndexroot.grkvHOgc.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/index-D6nXg_bb.kb2jJ-4C.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/theme.DJkDGpeA.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.aJu9e5fm.js",
"/ran/assets/chunks/jszip.min--o3_SgQz.CiS0z4ab.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/index.DzUvnNAe.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index-CVkJ_Xlh.BFb2SL1a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.BN8QfUnw.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/@localSearchIndexcn.Cxzijh60.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/docx-D5t6JtVt.BnsCdyQq.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/VPLocalSearchBox.Cnfsf5Nt.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-HhqG7SJg.B9lKsKkd.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BrLA-z5h.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.j85RvZJ1.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_preview_index.md.D-ZNp4Re.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_typescript_calculate.md.c2vewJZg.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DkNAYd72.lean.js",
"/ran/assets/src_article_sort_quick_index.md.D-Oft3e5.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.BaYK2V35.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.qtCjmma7.js",
"/ran/assets/cn_src_note_ubuntu.md.Bmh4RwhD.js",
"/ran/assets/src_ranui_input_index.md.Bu7mzQN_.js",
"/ran/assets/cn_src_article_system_design.md.8axGbTlW.lean.js",
"/ran/assets/src_article_sort_select_index.md.HyO0tmrq.js",
"/ran/assets/src_article_sort_shell_index.md.wupfbyiu.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_types_模式匹配.md.D9Tx5Vxt.lean.js",
"/ran/assets/src_types_类型运算.md.BXZmJEbH.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_article_typescript_reconstruction.md.drsslgGN.js",
"/ran/assets/cn_src_ranui_tab_index.md.B9BhdzGz.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.9VhEKnpy.js",
"/ran/assets/src_ranui_radar_index.md.C11mDNR_.lean.js",
"/ran/assets/src_article_bundle.md.Djx6jOk0.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Bmh4RwhD.lean.js",
"/ran/assets/index.md.Cyjn71m9.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CFTc3Q0g.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranuts_utils_get_cookie.md.C7J1JrN_.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Dfmep83K.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.Dptf5fgv.js",
"/ran/assets/cn_src_ranui_input_index.md.CGzKkDEb.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_sort_count_index.md.DWp06ClF.js",
"/ran/assets/src_ranuts_binary_tree_index.md.9VhEKnpy.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.CekLLtFP.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BhsZ5UnC.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_file_read_dir.md.ji9IcK3n.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_article_sort_bubble_index.md.CAzDi3q7.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_modal_index.md.DAJsf5Rm.lean.js",
"/ran/assets/src_ranuts_utils_task.md.EErFDnNF.lean.js",
"/ran/assets/src_article_imagemin.md.D3PHD-Pt.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B2VmeOZY.lean.js",
"/ran/assets/cn_src_note_centos.md.BPHXk6bx.lean.js",
"/ran/assets/src_article_typescript_recursion.md.D9GkmjQ1.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BxUkiR84.lean.js",
"/ran/assets/src_ranui_player_index.md.4U2-blNx.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranui_message_index.md.B7WHoJwI.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_article_javascript_dom_load.md.BuS1SzoV.js",
"/ran/assets/src_article_bundle.md.Djx6jOk0.js",
"/ran/assets/cn_src_note_docker.md.BJD-He5c.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranui_index.md.BvH1TSZ3.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_utils_format_json.md.3o7NSbi_.js",
"/ran/assets/src_ranuts_file_write_file.md.EfJtsrIS.js",
"/ran/assets/cn_src_ranui_modal_index.md.BL1Z3pig.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_skeleton_index.md.1MvZOeO_.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Btb8bhCu.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1741496599.js",
];
const VERSION = "1741496599";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



