const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/babel.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/icon_72.png",
"/ran/404.html",
"/ran/home.svg",
"/ran/assets/src_ranuts_utils_str2xml.md.B5vdQXxS.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.CpVYyZep.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.IdNAat6o.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.NZRFyarg.js",
"/ran/assets/src_article_typescript_calculate.md.BhVfR7oM.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Co3Jeapx.lean.js",
"/ran/assets/src_types_高级类型.md.ObRwkLSw.js",
"/ran/assets/src_types_TS类型.md.lT0VsYJX.js",
"/ran/assets/src_article_javascript_domLoad.md.Jm-CCFhD.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranuts_bundler_index.md.BYnXw-1l.js",
"/ran/assets/src_article_sort_shell_index.md.B-t4RyGV.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BJ0t93Mv.js",
"/ran/assets/src_article_sort_bubble_index.md.DfD0B21f.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DlSKPz3z.js",
"/ran/assets/cn_src_ranui_message_index.md.Dl1UUk4M.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.Jm-CCFhD.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Dypkbs3Z.lean.js",
"/ran/assets/src_article_typescript_unionType.md.DOlhRVtQ.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranui_select_index.md.C9AWoPzE.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.hhkc5g8R.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Bo8P6it2.lean.js",
"/ran/assets/app.Bz9dt6dC.js",
"/ran/assets/src_ranui_message_index.md.BUJ4qKWa.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CqL7840a.js",
"/ran/assets/src_ranuts_file_appendFile.md.hfXTImhm.js",
"/ran/assets/cn_src_note_ubuntu.md.BewNf33t.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CMe-VzGw.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BYnXw-1l.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C-WQQige.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_note_centos.md.CU-schbT.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DfD0B21f.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DDH9qH__.js",
"/ran/assets/cn_src_types_模式匹配.md.D84CR-S3.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranui_modal_index.md.ROhgbVya.lean.js",
"/ran/assets/src_article_sort_index.md.BmzSFd6J.lean.js",
"/ran/assets/src_ranui_progress_index.md.BU24n0CS.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CM_teb7b.js",
"/ran/assets/src_ranui_checkbox_index.md.DybUso6k.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.eohhlC_9.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.DTgZFp_f.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DoILvF6h.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranuts_bundler_index.md.BjmgKj3T.js",
"/ran/assets/index.md.BZLM9Chw.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CkwR8CzF.lean.js",
"/ran/assets/src_ranui_button_index.md.BaUgyz1X.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Di5Zqr25.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.LaYyZzsR.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BJ0t93Mv.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranuts_file_appendFile.md.hfXTImhm.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BlvODCUG.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.g5IL69Vn.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_babel.md.xaxyHusU.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.eRlIqRbm.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_utils_task.md.CqL7840a.lean.js",
"/ran/assets/cn_src_note_centos.md.CU-schbT.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_article_sort_heap_index.md.DGIzMQ7N.lean.js",
"/ran/assets/src_ranui_icon_index.md.Bvj_eNS6.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.B-SPlDpn.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Dl1UUk4M.js",
"/ran/assets/cn_src_ranui_math_index.md.CjCDE9Oj.lean.js",
"/ran/assets/src_types_高级类型.md.ObRwkLSw.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CvCkfz55.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_tabs_index.md.Bjpl0LRi.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bryk074c.lean.js",
"/ran/assets/src_ranui_icon_index.md.Bvj_eNS6.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bryk074c.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_article_astParse_tokenizer.md.Car-pAMT.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_visual.md.B3gz4QSG.js",
"/ran/assets/cn_src_article_sort_select_index.md.DDSMK22b.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BlvODCUG.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.IdNAat6o.js",
"/ran/assets/src_ranuts_utils_ocr.md.DhQDcBDd.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Dypkbs3Z.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_file_readFile.md.JXaeq4Af.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranuts_file_fileInfo.md.DVvOqvMC.js",
"/ran/assets/cn_src_article_typescript_unionType.md.sgwIQe9O.js",
"/ran/assets/cn_src_ranui_radar_index.md.BVW8avVs.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.K8GN9NYw.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.yZp3GoEd.js",
"/ran/assets/src_ranui_math_index.md.BftjvSU7.lean.js",
"/ran/assets/src_types_TS类型.md.lT0VsYJX.lean.js",
"/ran/assets/src_ranui_player_index.md.Bd3V6uX9.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Cz5uvgFp.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DGSoctCe.lean.js",
"/ran/assets/src_ranui_tabs_index.md.Bjpl0LRi.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_ranuts_file_watchFile.md.C834AKpV.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_utils_str2xml.md.B5vdQXxS.js",
"/ran/assets/cn_src_ranui_image_index.md.DPIPyUFH.js",
"/ran/assets/cn_index.md.2fj_5uQF.js",
"/ran/assets/src_article_typescript_reconstruction.md.CB-miSsQ.js",
"/ran/assets/cn_src_ranuts_index.md.0mHndMC0.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.yZp3GoEd.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BpfTWeN-.lean.js",
"/ran/assets/cn_src_article_babel.md.xL16z9Xt.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranuts_utils_getCookie.md.D9hAw1Ai.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_utils_getCookie.md.D9hAw1Ai.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DVvOqvMC.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_types_类型运算.md.tyGWinyV.js",
"/ran/assets/src_ranui_math_index.md.BftjvSU7.js",
"/ran/assets/src_types_类型运算.md.BJCnK19u.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DMpLzTqZ.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BDAAwEzn.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.C834AKpV.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_typescript_index.md.DnIyuKM2.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.C_uTd0oA.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DDH9qH__.lean.js",
"/ran/assets/src_article_bundle.md.BJTDBmRN.lean.js",
"/ran/assets/src_ranui_modal_index.md.DlMLUKFB.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_sort_merge_index.md.BCheUYDq.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.ROhgbVya.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_visual.md.B3gz4QSG.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CjCDE9Oj.js",
"/ran/assets/src_ranui_progress_index.md.BU24n0CS.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.f9CTuyiF.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CH3b01-9.js",
"/ran/assets/cn_src_ranui_tab_index.md.CK7MDF2U.lean.js",
"/ran/assets/src_types_模式匹配.md.aW8hDFrm.js",
"/ran/assets/cn_src_ranui_popover_index.md.BZnwkTfa.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.9O2AZ8pn.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.YgICEvQ2.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_typescript_recursion.md.CM_teb7b.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_sort_count_index.md.D-lG8j-V.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.DyT8Zi-G.lean.js",
"/ran/assets/src_article_sort_radix_index.md.COn47ChC.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_note_docker.md.MMD7sGKQ.js",
"/ran/assets/cn_src_types_模式匹配.md.D84CR-S3.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.09pIylq7.lean.js",
"/ran/assets/src_ranui_loading_index.md.C0IwCYQJ.lean.js",
"/ran/assets/src_article_sort_shell_index.md.B-t4RyGV.js",
"/ran/assets/cn_src_ranui_tabs_index.md.BUakYUQI.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_imagemin.md.Ck9ficKK.js",
"/ran/assets/src_ranuts_utils_task.md.DkXOQ0Pm.js",
"/ran/assets/cn_src_types_类型运算.md.tyGWinyV.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_astParse_tokenizer.md.Car-pAMT.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BDAAwEzn.js",
"/ran/assets/cn_src_ranui_input_index.md.C_uTd0oA.js",
"/ran/assets/cn_src_types_TS类型.md.SadT65z1.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CLm0w2ze.js",
"/ran/assets/src_types_模式匹配.md.aW8hDFrm.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_skeleton_index.md.CvCkfz55.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.K8GN9NYw.js",
"/ran/assets/src_ranuts_file_readDir.md.DKqPkSiB.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.hhkc5g8R.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_bundle.md.DBdY72dw.js",
"/ran/assets/src_ranui_message_index.md.BUJ4qKWa.js",
"/ran/assets/cn_src_article_docPreview.md.M0JJQDka.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CQvppcmc.js",
"/ran/assets/chunks/index.CafPLwUV.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/theme.FPvZ3Ede.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/framework.eq-HTtE3.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/index-Co9E57uv.DM_Nu_-Q.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/pwa-install.es.DuMXkPrI.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CmQSFM5C.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Byf79MII.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/index-Ba501-HG.DLGTjfcz.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/src_article_functionalProgramming.md.CVkTjNep.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CkwR8CzF.js",
"/ran/assets/cn_src_types_高级类型.md.CB6Aa-fQ.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranuts_file_readDir.md.DKqPkSiB.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranuts_mimeType_mimeType.md.3GwZTr-n.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.DIBYZzGf.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.YgICEvQ2.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BVW8avVs.js",
"/ran/assets/cn_src_ranui_button_index.md.BTsF5_xn.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CLm0w2ze.lean.js",
"/ran/assets/src_article_designMode.md.BVyuKZfy.js",
"/ran/assets/cn_src_ranui_tabs_index.md.BUakYUQI.js",
"/ran/assets/src_ranui_input_index.md.D_iWTNWU.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_imagemin.md.BVBSzSq_.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DkXOQ0Pm.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.JXaeq4Af.js",
"/ran/assets/cn_src_ranui_image_index.md.DPIPyUFH.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.64tQAHz0.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CdZNzudF.js",
"/ran/assets/cn_src_ranui_preview_index.md.D8PW9V7b.lean.js",
"/ran/assets/src_article_typescript_index.md.DnIyuKM2.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_note_docker.md.MMD7sGKQ.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.DwvidFHw.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.NZRFyarg.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_sort_quick_index.md.CdZNzudF.lean.js",
"/ran/assets/src_article_functionalProgramming.md.CVkTjNep.js",
"/ran/assets/src_article_designMode.md.BVyuKZfy.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Cz5uvgFp.lean.js",
"/ran/assets/cn_src_article_bundle.md.DBdY72dw.lean.js",
"/ran/assets/style.D7_Ytddv.css",
"/ran/assets/src_ranuts_index.md.vgnne91o.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.wq3k5Yjy.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BZYF7luN.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BFnGWlo8.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.sgwIQe9O.lean.js",
"/ran/assets/src_ranui_popover_index.md.CJywCOk7.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DlSKPz3z.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DfwnUGyP.js",
"/ran/assets/src_article_sort_index.md.BmzSFd6J.js",
"/ran/assets/src_article_sort_heap_index.md.DGIzMQ7N.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.f9CTuyiF.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranui_radar_index.md.jEmkm03a.lean.js",
"/ran/assets/cn_src_article_babel.md.xL16z9Xt.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_index.md.2fj_5uQF.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.r1f6mQDV.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.B-SPlDpn.js",
"/ran/assets/cn_src_types_高级类型.md.CB6Aa-fQ.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.DDSMK22b.js",
"/ran/assets/src_ranui_image_index.md.ByPb9XPk.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.C5_Slj29.js",
"/ran/assets/cn_src_article_docPreview.md.M0JJQDka.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.BZnwkTfa.js",
"/ran/assets/cn_src_ranui_preview_index.md.D8PW9V7b.js",
"/ran/assets/src_ranui_index.md.DaW35dZO.js",
"/ran/assets/src_article_sort_count_index.md.D-lG8j-V.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CMe-VzGw.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.eohhlC_9.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.64tQAHz0.js",
"/ran/assets/src_ranui_popover_index.md.CJywCOk7.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_utils_ocr.md.DhQDcBDd.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.CH3b01-9.lean.js",
"/ran/assets/src_article_typescript_recursion.md.B4cwxN_H.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_checkbox_index.md.DybUso6k.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_article_bundle.md.BJTDBmRN.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_types_TS类型.md.SadT65z1.js",
"/ran/assets/src_types_类型运算.md.BJCnK19u.js",
"/ran/assets/src_ranuts_bundler_index.md.BjmgKj3T.lean.js",
"/ran/assets/src_ranui_player_index.md.Bd3V6uX9.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranui_loading_index.md.C0IwCYQJ.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_article_imagemin.md.BVBSzSq_.js",
"/ran/assets/src_article_imagemin.md.Ck9ficKK.lean.js",
"/ran/assets/src_article_babel.md.xaxyHusU.js",
"/ran/assets/cn_src_article_systemDesign.md.09pIylq7.js",
"/ran/assets/src_ranui_modal_index.md.DlMLUKFB.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.eRlIqRbm.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DoILvF6h.js",
"/ran/assets/src_ranui_preview_index.md.BerPxqap.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BFnGWlo8.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.wq3k5Yjy.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_loading_index.md.g5IL69Vn.js",
"/ran/assets/src_ranui_button_index.md.BaUgyz1X.js",
"/ran/assets/src_article_sort_bucket_index.md.r1f6mQDV.js",
"/ran/assets/src_article_typescript_calculate.md.BhVfR7oM.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BCheUYDq.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BpfTWeN-.js",
"/ran/assets/cn_src_article_designMode.md.BtsBYMyP.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BZYF7luN.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.DIBYZzGf.js",
"/ran/assets/cn_src_article_typescript_pattern.md.9O2AZ8pn.js",
"/ran/assets/src_ranui_preview_index.md.BerPxqap.js",
"/ran/assets/cn_src_ranui_button_index.md.BTsF5_xn.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DMvZ6n_5.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DE1WitAK.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranuts_index.md.0mHndMC0.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.DwvidFHw.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DGSoctCe.js",
"/ran/assets/src_article_typescript_unionType.md.DOlhRVtQ.lean.js",
"/ran/assets/src_article_typescript_recursion.md.B4cwxN_H.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_note_ubuntu.md.BewNf33t.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DE1WitAK.js",
"/ran/assets/src_article_sort_radix_index.md.COn47ChC.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_sort_merge_index.md.Di5Zqr25.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Co3Jeapx.js",
"/ran/assets/src_ranui_input_index.md.D_iWTNWU.lean.js",
"/ran/assets/src_article_sort_select_index.md.D08HIyUD.js",
"/ran/assets/src_ranui_select_index.md.C9AWoPzE.js",
"/ran/assets/cn_src_ranui_tab_index.md.CK7MDF2U.js",
"/ran/assets/src_ranui_tab_index.md.DYSeU5SX.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C-WQQige.lean.js",
"/ran/assets/index.md.BZLM9Chw.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_sort_select_index.md.D08HIyUD.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.C5_Slj29.lean.js",
"/ran/assets/src_ranui_image_index.md.ByPb9XPk.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Bo8P6it2.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranui_select_index.md.DTgZFp_f.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BbPWuLn7.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranuts_mimeType_mimeType.md.3GwZTr-n.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranuts_index.md.vgnne91o.js",
"/ran/assets/src_ranui_radar_index.md.jEmkm03a.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_sort_bucket_index.md.LaYyZzsR.lean.js",
"/ran/assets/cn_src_article_video.md.B93QLRnX.js",
"/ran/assets/cn_src_article_designMode.md.BtsBYMyP.js",
"/ran/assets/cn_src_ranui_index.md.C6TkvKZ5.js",
"/ran/assets/cn_src_article_sort_index.md.BbPWuLn7.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CB-miSsQ.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DMvZ6n_5.lean.js",
"/ran/assets/cn_src_ranui_index.md.C6TkvKZ5.lean.js",
"/ran/assets/src_ranui_index.md.DaW35dZO.lean.js",
"/ran/assets/cn_src_article_video.md.B93QLRnX.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CQvppcmc.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_insert_index.md.DfwnUGyP.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DMpLzTqZ.js",
"/ran/assets/src_ranui_tab_index.md.DYSeU5SX.js",
"/ran/assets/cn_src_article_typescript_index.md.DyT8Zi-G.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.CpVYyZep.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/icon_48.png",
"/ran/icon_144.png",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.zh-cn_25295ac6fc508.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind.en_5eb6d54e34.pf_meta",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/index/zh-cn_9bacfc2.pf_index",
"/ran/pagefind/index/en_bc39585.pf_index",
"/ran/pagefind/index/zh-cn_8d4814d.pf_index",
"/ran/pagefind/index/en_e8e8597.pf_index",
"/ran/pagefind/index/en_d22f299.pf_index",
"/ran/pagefind/index/zh-cn_64ecbb3.pf_index",
"/ran/pagefind/index/zh-cn_933a426.pf_index",
"/ran/pagefind/index/zh-cn_88a2748.pf_index",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/fragment/zh-cn_3aa282b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8338621.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95fa787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5b71249.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66f42e8.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f9c4333.pf_fragment",
"/ran/pagefind/fragment/zh-cn_489c27d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/en_a9c2374.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c1151c9.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e64f93e.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7d7b75a.pf_fragment",
"/ran/pagefind/fragment/en_c84c5e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d1b782.pf_fragment",
"/ran/pagefind/fragment/zh-cn_caddc62.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f09c929.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c82f3b2.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_50313a9.pf_fragment",
"/ran/pagefind/fragment/en_4cca5aa.pf_fragment",
"/ran/pagefind/fragment/zh-cn_75a264c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bab657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_67d6c7a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592cc95.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d98338a.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2e8f3b4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e88bc3f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3de2e5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5919.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_7a4ca4f.pf_fragment",
"/ran/pagefind/fragment/en_d792b8c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c11a8a7.pf_fragment",
"/ran/pagefind/fragment/en_c9c7c59.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f4f874.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac92f78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_edddd73.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bb9206.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_5f9a7eb.pf_fragment",
"/ran/pagefind/fragment/en_75d5dcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f379427.pf_fragment",
"/ran/pagefind/fragment/en_31bb7a6.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5df12ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2e89f3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e347438.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a47bf58.pf_fragment",
"/ran/pagefind/fragment/zh-cn_707d8fd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3e43b1f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_44fa7df.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c34a2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e7c7085.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8d53abb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ca356d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7edffe.pf_fragment",
"/ran/pagefind/fragment/en_4873c44.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_51f248e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_58279de.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/en_8e7817f.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_901e811.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f7dcce8.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_1d2a8f7.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59bdbd3.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d32fcee.pf_fragment",
"/ran/pagefind/fragment/en_2942c3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7b2564.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5190b59.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3fb29d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_aa1f32d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ee19938.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_715eacf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2ab4b75.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51dafe6.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_32113cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d04ce0b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5042f4c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_677ff04.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_25694d5.pf_fragment",
"/ran/pagefind/fragment/en_216410c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a3cd5f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a1e1243.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ef213d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ad6344.pf_fragment",
"/ran/icon_96.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/icon_168.png",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/index.html",
"/ran/sw1728206030.js",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/icon.png",
"/ran/manifest.json",
"/ran/icon_192.png",
];
const VERSION = "1728206030";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



