const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/sw1748148324.js",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/vp-icons.css",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/example.m3u8",
"/ran/assets/src_types_高级类型.md.B4kpjCyR.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranui_message_index.md.jD-L99aH.js",
"/ran/assets/cn_src_note_docker.md.WUjMhJCJ.js",
"/ran/assets/cn_src_article_sort_merge_index.md.COA7Z_P5.lean.js",
"/ran/assets/src_article_typescript_calculate.md.k2TGs9wM.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_article_typescript_union_type.md.Brx1crgS.js",
"/ran/assets/src_article_sort_count_index.md.pho-NIhx.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.B-x_v6Y2.js",
"/ran/assets/cn_src_ranui_player_index.md.D5QQYJ9n.js",
"/ran/assets/src_article_javascript_dom_load.md.BHoiCYA5.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranui_modal_index.md.DsJBQ-Pq.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.1ZCjcVz4.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/cn_src_ranui_progress_index.md.D-MCa7Q0.js",
"/ran/assets/src_article_javascript_dom_load.md.BHoiCYA5.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_note_centos.md.uh8iy_4Y.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Diam0Z4R.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.BhW1DQNk.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DsI1fwQI.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CUwL7oyB.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_typescript_recursion.md.DHoNCmC9.js",
"/ran/assets/cn_src_article_design_mode.md.DSV15CUH.js",
"/ran/assets/src_ranuts_bundler_index.md.BhW1DQNk.js",
"/ran/assets/src_article_sort_merge_index.md.DCVxCvyN.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.DsJBQ-Pq.js",
"/ran/assets/src_article_sort_bubble_index.md.CteHT-wc.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.D9M-yCyr.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.B73-ajIq.lean.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.Cnma9ZsX.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Yoz5WnDr.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_index.md.F3q-doei.lean.js",
"/ran/assets/src_article_design_mode.md.C9G_CYWL.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.fhInfk_W.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_article_typescript_reconstruction.md.DZsXoxCg.js",
"/ran/assets/src_ranuts_file_write_file.md.BXLPwuNz.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DZsXoxCg.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_sort_bubble_index.md.CF3i_S3v.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_sort_count_index.md.pho-NIhx.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/src_ranui_skeleton_index.md.nlpEdeIM.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_article_sort_merge_index.md.DCVxCvyN.js",
"/ran/assets/index.md.YnZ58RZa.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CwKWy1CC.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B9plneUy.lean.js",
"/ran/assets/src_ranuts_index.md.DApoFwjw.lean.js",
"/ran/assets/src_article_functional_programming.md.D_vgagEz.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.qtlpWIQb.js",
"/ran/assets/src_ranuts_file_read_file.md.pck3R6t_.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.DrKTscBU.lean.js",
"/ran/assets/src_ranui_modal_index.md.CIolBi_e.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CrIek9Xb.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DOn4NZH1.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_typescript_index.md.DxuwbhUI.js",
"/ran/assets/cn_src_article_system_design.md.BgY1_Iz4.lean.js",
"/ran/assets/cn_src_article_imagemin.md.BS_Ir1Tv.js",
"/ran/assets/src_article_design_mode.md.C9G_CYWL.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.BcJPy11k.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BKjdPoS9.js",
"/ran/assets/src_ranui_radar_index.md.D7xQG0WU.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_article_sort_shell_index.md.CFACFLqA.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CGOdiulL.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C8Q0XtyQ.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.CUwL7oyB.lean.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/framework.C25nBkpI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/@localSearchIndexroot.B-h6s0wL.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/@localSearchIndexcn.DfGU9qHs.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/VPLocalSearchBox.CCVoUtWa.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/pwa-install.es.BM1ku5fR.js",
"/ran/assets/chunks/index.D5BwptcT.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DYrt7xWJ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/theme.lEpts67x.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_babel.md.pI4yJIt6.lean.js",
"/ran/assets/cn_src_ranuts_index.md.VV2Ppk-4.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_insert_index.md.AE61f5ZX.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.BFm-_gqB.lean.js",
"/ran/assets/src_ranui_button_index.md.CE76qUH3.js",
"/ran/assets/cn_src_article_typescript_index.md.1ZCjcVz4.lean.js",
"/ran/assets/cn_src_article_sort_index.md.B5W8JFlX.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BCfqCrnm.lean.js",
"/ran/assets/src_ranui_icon_index.md.Baru2dHA.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_note_ubuntu.md.DeYc-xFE.lean.js",
"/ran/assets/src_ranui_preview_index.md.WnHt3Uuv.js",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/src_types_TS类型.md.Duw7wDEg.js",
"/ran/assets/src_article_sort_radix_index.md.CRuafY6t.lean.js",
"/ran/assets/cn_src_note_docker.md.WUjMhJCJ.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B-AM2Mck.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Rg0kp4u-.lean.js",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_file_file_info.md.DaHgwlxq.js",
"/ran/assets/src_ranui_tabs_index.md.C_8WhAPj.lean.js",
"/ran/assets/src_article_babel.md._oK0yEHx.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_types_TS类型.md.Duw7wDEg.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.R9xtQEof.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.fhInfk_W.js",
"/ran/assets/cn_src_article_system_design.md.BgY1_Iz4.js",
"/ran/assets/cn_src_article_typescript_union_type.md.ObbJheYf.lean.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_ranui_index.md.WhqwGGuZ.js",
"/ran/assets/src_ranui_button_index.md.CE76qUH3.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DDK0HjYH.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DMSsFdOb.js",
"/ran/assets/src_ranui_message_index.md.C3mLoB4j.lean.js",
"/ran/assets/src_article_imagemin.md.CB7VO43h.lean.js",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/cn_src_note_ubuntu.md.DeYc-xFE.js",
"/ran/assets/cn_src_types_TS类型.md.BGwDMVYC.js",
"/ran/assets/src_ranui_select_index.md.CQ-XRRUW.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_article_sort_select_index.md.D3QIiRZL.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranui_math_index.md.wRtm0mRI.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.Ci8sBFhX.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.1_PyUXM6.lean.js",
"/ran/assets/cn_src_ranui_index.md.WhqwGGuZ.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.DRVq0H2y.lean.js",
"/ran/assets/src_ranui_tab_index.md.CMuZvObe.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Cnma9ZsX.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.vFTPoY--.js",
"/ran/assets/src_ranui_player_index.md.DLzb5Lkc.js",
"/ran/assets/src_article_bundle.md.CkNCkisN.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_types_类型运算.md.CCHwG1z5.js",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/src_article_typescript_recursion.md.COVBVoYq.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_article_sort_select_index.md.CWae6Dct.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_note_centos.md.uh8iy_4Y.js",
"/ran/assets/cn_src_ranui_math_index.md.Sg1b7b42.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Cs72qCpi.lean.js",
"/ran/assets/src_types_类型运算.md.CCHwG1z5.lean.js",
"/ran/assets/src_ranuts_index.md.DApoFwjw.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/src_ranuts_mime_type_mime_type.md.YCgzBeka.js",
"/ran/assets/cn_src_article_sort_count_index.md.t0PG7geP.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C8Q0XtyQ.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_binary_tree_index.md.D2_d-nEU.js",
"/ran/assets/src_article_typescript_calculate.md.k2TGs9wM.js",
"/ran/assets/cn_src_article_bundle.md.CgvnyVFl.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.D2_d-nEU.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_sort_index.md.C7WoGgBM.js",
"/ran/assets/cn_index.md.F3q-doei.js",
"/ran/assets/src_article_sort_index.md.C7WoGgBM.lean.js",
"/ran/assets/src_article_sort_select_index.md.D3QIiRZL.lean.js",
"/ran/assets/src_article_sort_heap_index.md.ba3pwdxE.js",
"/ran/assets/cn_src_ranui_player_index.md.D5QQYJ9n.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_sort_shell_index.md.CvsC3XGc.js",
"/ran/assets/src_article_sort_bubble_index.md.CteHT-wc.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Diam0Z4R.js",
"/ran/assets/cn_src_ranui_loading_index.md.uapaJI_A.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BhMYuLli.lean.js",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/cn_src_ranui_input_index.md.CbTR3sgn.lean.js",
"/ran/assets/cn_src_types_TS类型.md.BGwDMVYC.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CWae6Dct.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_sort_radix_index.md.CRuafY6t.js",
"/ran/assets/cn_src_article_typescript_union_type.md.ObbJheYf.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Dh4KHh0C.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_icon_index.md.D2Dv3ZIW.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_message_index.md.jD-L99aH.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.qtlpWIQb.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.B73-ajIq.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_sort_shell_index.md.CFACFLqA.lean.js",
"/ran/assets/src_types_模式匹配.md.4mVyAGuy.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.ZgqrJyUv.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DMSsFdOb.lean.js",
"/ran/assets/src_ranui_math_index.md.wRtm0mRI.js",
"/ran/assets/cn_src_blockchain_web3.md.ijQ96T2p.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_imagemin.md.BS_Ir1Tv.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DUQ99xf6.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.vFTPoY--.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B-AM2Mck.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.j3jwOBSp.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.D4__1vad.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_icon_index.md.Baru2dHA.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BhMYuLli.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_types_模式匹配.md.C8dC5kb2.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Rg0kp4u-.js",
"/ran/assets/cn_src_ranui_button_index.md.DsI1fwQI.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_article_sort_insert_index.md.CrIek9Xb.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/cn_src_article_doc_preview.md.DvjBb3eG.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.CF3i_S3v.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.CoxMLg7V.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DKrd3tAf.js",
"/ran/assets/cn_src_ranui_tabs_index.md.CoxMLg7V.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.CUKCeIvl.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Bu-9_YmF.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DVbUy6Ja.js",
"/ran/assets/src_ranuts_file_watch_file.md.D9M-yCyr.lean.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/cn_src_ranuts_file_read_dir.md.C0ejN8WG.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DUQ99xf6.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.B-x_v6Y2.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_index.md.CIZPJcZi.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BKjdPoS9.lean.js",
"/ran/assets/src_types_高级类型.md.B4kpjCyR.lean.js",
"/ran/assets/src_ranui_message_index.md.C3mLoB4j.js",
"/ran/assets/cn_src_types_模式匹配.md.C8dC5kb2.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.D7GtRidx.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.BFm-_gqB.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Yoz5WnDr.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.D4__1vad.js",
"/ran/assets/index.md.YnZ58RZa.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.CUKCeIvl.js",
"/ran/assets/cn_src_ranui_math_index.md.Sg1b7b42.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranui_input_index.md.BrhU5YtQ.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.C1G4mMzj.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_ranui_tab_index.md.CMuZvObe.js",
"/ran/assets/src_article_bundle.md.CkNCkisN.js",
"/ran/assets/src_ranui_modal_index.md.CIolBi_e.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.Cq_NN5lW.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_article_typescript_recursion.md.COVBVoYq.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.B7eaIcw4.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Cs72qCpi.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_babel.md.pI4yJIt6.js",
"/ran/assets/cn_src_article_doc_preview.md.DvjBb3eG.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_progress_index.md.CP0A1ghj.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Dh4KHh0C.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_tab_index.md.DhzTGyjw.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CvsC3XGc.lean.js",
"/ran/assets/src_article_typescript_index.md.DxuwbhUI.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranui_radar_index.md.D7xQG0WU.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/cn_src_blockchain_index.md.3YKUVent.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.1_PyUXM6.js",
"/ran/assets/cn_src_types_类型运算.md.B9plneUy.js",
"/ran/assets/cn_src_article_sort_count_index.md.t0PG7geP.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_file_read_file.md.Bu-9_YmF.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_sort_quick_index.md.Bf_t8GOG.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CGOdiulL.lean.js",
"/ran/assets/src_article_typescript_union_type.md.Brx1crgS.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.BwgFS_T_.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.VSEargwC.lean.js",
"/ran/assets/src_ranui_image_index.md.Crpk7JsM.js",
"/ran/assets/style.xOo_NRHt.css",
"/ran/assets/cn_src_ranuts_file_read_dir.md.C0ejN8WG.lean.js",
"/ran/assets/src_article_sort_insert_index.md.AE61f5ZX.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/src_ranui_index.md.CIZPJcZi.js",
"/ran/assets/src_article_sort_heap_index.md.ba3pwdxE.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.R9xtQEof.js",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/src_ranuts_file_write_file.md.BXLPwuNz.js",
"/ran/assets/src_ranui_skeleton_index.md.nlpEdeIM.js",
"/ran/assets/src_ranui_tabs_index.md.C_8WhAPj.js",
"/ran/assets/src_ranui_player_index.md.DLzb5Lkc.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.C1G4mMzj.js",
"/ran/assets/src_ranui_select_index.md.CQ-XRRUW.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DHoNCmC9.lean.js",
"/ran/assets/src_ranui_input_index.md.BrhU5YtQ.js",
"/ran/assets/src_article_imagemin.md.CB7VO43h.js",
"/ran/assets/src_ranuts_file_read_dir.md.D7GtRidx.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranuts_utils_ocr.md.Bd5TVSrJ.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_loading_index.md.l0EdfryV.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.B7eaIcw4.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.0npiRKqJ.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.uapaJI_A.js",
"/ran/assets/src_ranui_loading_index.md.l0EdfryV.js",
"/ran/assets/cn_src_article_video.md.B_puP2Xm.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.9t2S8Ifo.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C79FLET1.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DaHgwlxq.lean.js",
"/ran/assets/src_ranui_popover_index.md.C3z_Cr-A.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DOn4NZH1.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.Ci8sBFhX.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.DrKTscBU.js",
"/ran/assets/src_types_模式匹配.md.4mVyAGuy.js",
"/ran/assets/cn_src_article_video.md.B_puP2Xm.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BKEpBWE9.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BCfqCrnm.js",
"/ran/assets/cn_src_ranui_image_index.md.BKEpBWE9.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_radar_index.md.aZxL2IfY.lean.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/src_ranuts_utils_get_cookie.md.j3jwOBSp.js",
"/ran/assets/cn_src_ranui_progress_index.md.D-MCa7Q0.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DVbUy6Ja.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BwgFS_T_.js",
"/ran/assets/src_article_functional_programming.md.D_vgagEz.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DDK0HjYH.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/cn_src_ranui_icon_index.md.D2Dv3ZIW.lean.js",
"/ran/assets/src_ranui_image_index.md.Crpk7JsM.lean.js",
"/ran/assets/src_article_sort_quick_index.md.Bf_t8GOG.lean.js",
"/ran/assets/cn_src_article_bundle.md.CgvnyVFl.js",
"/ran/assets/src_ranuts_utils_ocr.md.Bd5TVSrJ.js",
"/ran/assets/src_ranui_popover_index.md.C3z_Cr-A.js",
"/ran/assets/src_ranui_progress_index.md.CP0A1ghj.js",
"/ran/assets/src_ranuts_file_file_info.md.BcJPy11k.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_sort_index.md.B5W8JFlX.js",
"/ran/assets/app.CzanQKo-.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_article_babel.md._oK0yEHx.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C79FLET1.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_ranui_input_index.md.CbTR3sgn.js",
"/ran/assets/src_ranuts_file_read_file.md.pck3R6t_.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_mime_type_mime_type.md.YCgzBeka.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DhzTGyjw.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.DRVq0H2y.js",
"/ran/assets/cn_src_article_visual.md.D0bbYzdu.js",
"/ran/assets/cn_src_ranuts_utils_task.md.VSEargwC.js",
"/ran/assets/cn_src_ranuts_index.md.VV2Ppk-4.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.ZgqrJyUv.js",
"/ran/assets/cn_src_article_design_mode.md.DSV15CUH.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.C_zZ8WyD.js",
"/ran/assets/cn_src_blockchain_index.md.3YKUVent.js",
"/ran/assets/src_ranui_preview_index.md.WnHt3Uuv.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.aZxL2IfY.js",
"/ran/assets/cn_src_ranui_select_index.md.Cq_NN5lW.js",
"/ran/assets/src_ranuts_utils_str2xml.md.9t2S8Ifo.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CwKWy1CC.js",
"/ran/assets/cn_src_article_visual.md.D0bbYzdu.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_blockchain_web3.md.ijQ96T2p.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.0npiRKqJ.js",
"/ran/assets/src_article_sort_bucket_index.md.C_zZ8WyD.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DKrd3tAf.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.COA7Z_P5.js",
"/ran/manifest.json",
"/ran/404.html",
"/ran/icon_192.png",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/index.html",
"/ran/icon_48.png",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/babel.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/icon.png",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/home.svg",
"/ran/icon_72.png",
"/ran/logo.png",
"/ran/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
];
const VERSION = "1748148324";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



