const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/assets/cn_src_types_类型运算.md.COtlEd3U.js",
"/ran/assets/cn_src_ranui_message_index.md.BCxfkWSb.js",
"/ran/assets/src_article_sort_bubble_index.md.BoojhtcJ.js",
"/ran/assets/cn_src_article_typescript_union_type.md.ysEhgt8A.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/cn_src_ranui_button_index.md.0EHKp7fc.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.g3zKs9tC.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.DexTCGcL.js",
"/ran/assets/cn_src_article_sort_quick_index.md.O-cIBsdF.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BVRQaGR9.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.HEjG5Y9B.lean.js",
"/ran/assets/src_article_typescript_union_type.md.eHh-m34-.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Fa_3MvTR.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BlV0oBIf.lean.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_sort_index.md.Dnu_a3FA.lean.js",
"/ran/assets/src_types_TS类型.md.BjN6U7in.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_blockchain_web3.md.rdwNzFiB.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.NJBt9d2M.js",
"/ran/assets/src_ranuts_binary_tree_index.md.Dl-1Sajz.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BpkOP5na.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_tabs_index.md.DzkHCNtE.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_file_write_file.md.Ssi8igj6.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BDPs007M.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_types_模式匹配.md.Bp9Mdrsr.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.CvBUfttj.js",
"/ran/assets/src_ranuts_file_read_file.md.CRqVz8ih.js",
"/ran/assets/cn_src_article_visual.md.Csw6G2r3.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.D-AH_Tco.js",
"/ran/assets/src_ranui_image_index.md.CVTGwYT4.lean.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_article_sort_heap_index.md.C0t3B7Qp.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CqdDqwYL.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranui_math_index.md.D-AH_Tco.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_functional_programming.md.CJ_yKIPo.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Dtkfwylf.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.Fa_3MvTR.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.vQQE7UD3.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/index.md.Bdsb3ccw.js",
"/ran/assets/cn_src_note_centos.md.C8QDxU8_.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.DGSjj3RF.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranui_skeleton_index.md.CW4EyiqK.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.g3zKs9tC.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BLLh_v5y.lean.js",
"/ran/assets/src_ranuts_index.md.D6Nd6-zH.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.BoojhtcJ.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_utils_task.md.DlLQi9zH.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_article_visual.md.Csw6G2r3.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_article_system_design.md.DEVCvaBl.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_article_sort_shell_index.md.DexTCGcL.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.v9dTKuaw.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.vQQE7UD3.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BVRQaGR9.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_article_bundle.md.BUdmlOdD.js",
"/ran/assets/src_article_sort_count_index.md.DdgyTqf9.lean.js",
"/ran/assets/src_ranui_modal_index.md.BJPo3dH0.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BfeCL8b_.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CtjjKhdv.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_sort_select_index.md.s_W0qN6y.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/src_article_sort_merge_index.md.kwFlpjUT.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BCT4kRwA.js",
"/ran/assets/src_ranui_math_index.md.BZlfQpy5.lean.js",
"/ran/assets/src_article_typescript_pattern.md.4t2Y3juI.js",
"/ran/assets/src_article_sort_heap_index.md.DeuiWtss.js",
"/ran/assets/cn_src_ranui_radar_index.md.Cxv6wjpp.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DAt7WRCq.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CqdDqwYL.js",
"/ran/assets/src_ranuts_file_read_file.md.CRqVz8ih.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DGSjj3RF.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.CsJuc9VK.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.sKlQQe0Y.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CvBUfttj.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/cn_src_note_ubuntu.md.BAx7Crte.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Z81zaQP3.lean.js",
"/ran/assets/src_article_sort_index.md.Dnu_a3FA.js",
"/ran/assets/src_types_TS类型.md.BjN6U7in.lean.js",
"/ran/assets/src_article_typescript_union_type.md.eHh-m34-.js",
"/ran/assets/cn_src_ranui_select_index.md.C-YkeCE3.js",
"/ran/assets/src_ranui_checkbox_index.md.Bm9NV-_g.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_note_docker.md.CgnurhIi.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.CFjvTFGC.lean.js",
"/ran/assets/src_types_高级类型.md.DDRSHpNi.js",
"/ran/assets/cn_src_ranui_index.md.r7K-J68C.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.BOs-wE3m.js",
"/ran/assets/cn_src_article_design_mode.md.BRIA4dGP.lean.js",
"/ran/assets/app.Cgl5yHgl.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.D__Xfcyl.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BfeCL8b_.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.BzfCMmOc.lean.js",
"/ran/assets/cn_src_blockchain_index.md.DuSRW_Wr.lean.js",
"/ran/assets/src_ranui_button_index.md.CSCMGfAr.lean.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BCYHWiq-.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/src_ranui_icon_index.md.DJJhp263.lean.js",
"/ran/assets/cn_src_article_bundle.md.Dumv1jI_.js",
"/ran/assets/src_ranui_progress_index.md.C2Yms430.lean.js",
"/ran/assets/index.md.Bdsb3ccw.lean.js",
"/ran/assets/src_ranui_progress_index.md.C2Yms430.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranui_progress_index.md.DwCxcJTx.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CDKSdVnR.js",
"/ran/assets/src_ranui_preview_index.md.D75D31jY.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BzfCMmOc.js",
"/ran/assets/src_article_typescript_pattern.md.4t2Y3juI.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.CKU62NcR.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranui_popover_index.md.BFpYgUch.lean.js",
"/ran/assets/src_article_design_mode.md.B707oAJj.js",
"/ran/assets/src_types_类型运算.md.ByusUoEk.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_ranui_input_index.md.vcT7CU__.lean.js",
"/ran/assets/cn_index.md.DVjGtFJz.lean.js",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/src_article_ast_parse_tokenizer.md.sKlQQe0Y.js",
"/ran/assets/cn_src_ranui_preview_index.md.CS2N3rBm.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.gKtqfRWJ.lean.js",
"/ran/assets/src_article_sort_radix_index.md.D8HkD2bD.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.WI_z2Wo9.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_select_index.md.mvUXOTCl.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranui_icon_index.md.DJJhp263.js",
"/ran/assets/src_ranui_index.md.CywAK39D.js",
"/ran/assets/cn_src_article_design_mode.md.BRIA4dGP.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BDPs007M.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.C6DVjS2m.js",
"/ran/assets/src_article_design_mode.md.B707oAJj.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BmxS5sFb.js",
"/ran/assets/cn_src_note_docker.md.CgnurhIi.js",
"/ran/assets/src_article_sort_quick_index.md.d1vEuWyk.js",
"/ran/assets/cn_src_ranui_message_index.md.BCxfkWSb.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_article_typescript_index.md.Cxd8b6bI.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BmxS5sFb.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.Bp9Mdrsr.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BCYHWiq-.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranui_loading_index.md.BljJeNK5.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.ho6FmgmO.js",
"/ran/assets/cn_src_article_typescript_calculate.md.bzFEHBhM.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranuts_utils_task.md.DlLQi9zH.lean.js",
"/ran/assets/cn_src_ranuts_index.md.rRxebZlD.js",
"/ran/assets/src_ranuts_file_read_dir.md.D9IOZhbd.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_sort_select_index.md.s_W0qN6y.js",
"/ran/assets/src_article_sort_merge_index.md.kwFlpjUT.js",
"/ran/assets/cn_src_article_typescript_index.md.Cxd8b6bI.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.WI_z2Wo9.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/src_ranui_radar_index.md.DOnkrLJK.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranuts_file_file_info.md.lzKvJ7Xb.js",
"/ran/assets/src_ranui_tabs_index.md.DzkHCNtE.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_blockchain_web3.md.rdwNzFiB.lean.js",
"/ran/assets/src_article_typescript_recursion.md.B-3mU2YD.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.NJBt9d2M.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.CNRSfXxd.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CulEbheO.lean.js",
"/ran/assets/src_ranui_math_index.md.BZlfQpy5.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_sort_insert_index.md.V8CQ40Bv.lean.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.Dl-1Sajz.js",
"/ran/assets/style.B51h211J.css",
"/ran/assets/src_ranuts_file_write_file.md.Ssi8igj6.js",
"/ran/assets/cn_src_ranui_progress_index.md.DwCxcJTx.lean.js",
"/ran/assets/src_ranui_select_index.md.BLplUkrO.lean.js",
"/ran/assets/cn_src_article_babel.md.Bh6Hwv7y.js",
"/ran/assets/cn_src_note_ubuntu.md.BAx7Crte.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D1n3XP8w.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CulEbheO.js",
"/ran/assets/cn_src_ranui_image_index.md.HEjG5Y9B.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Hbp0eWMk.js",
"/ran/assets/src_ranui_modal_index.md.BJPo3dH0.lean.js",
"/ran/assets/cn_src_article_video.md.BNV9QLYT.js",
"/ran/assets/src_article_functional_programming.md.CJ_yKIPo.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_button_index.md.CSCMGfAr.js",
"/ran/assets/cn_index.md.DVjGtFJz.js",
"/ran/assets/src_ranuts_utils_format_json.md.CKU62NcR.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BLLh_v5y.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.lzKvJ7Xb.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DVN48Loj.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_typescript_calculate.md.bzFEHBhM.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/cn_src_ranui_modal_index.md.v9dTKuaw.js",
"/ran/assets/src_ranuts_file_watch_file.md.D6quHq8P.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/index.D5grTCvU.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/@localSearchIndexroot.DUjkMleV.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/theme.Cd17q-Td.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.B9n-JBrB.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/VPLocalSearchBox.D1jTWDVt.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/framework.CApOETg9.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/pdf-DRw1818j.BszTcE-_.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/@localSearchIndexcn.C01D70di.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/pwa-install.es.CyliIjjp.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/index.wd9EqAUk.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranui_checkbox_index.md.Bm9NV-_g.lean.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranui_input_index.md.B9eWqSWb.lean.js",
"/ran/assets/src_article_imagemin.md.DTTkhp2s.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BYCnzYT7.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.CvWV2I-M.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranui_preview_index.md.CS2N3rBm.js",
"/ran/assets/cn_src_blockchain_index.md.DuSRW_Wr.js",
"/ran/assets/cn_src_types_高级类型.md.Cc9ftlC-.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_article_typescript_index.md.aKv3AQsg.lean.js",
"/ran/assets/src_article_babel.md.Bseh7wz8.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.C9OXjyLr.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.Pld2dynD.js",
"/ran/assets/src_ranuts_utils_ocr.md.CFjvTFGC.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Pld2dynD.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BPY0zNkG.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CdheGCh0.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CyzLXXyj.js",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/src_ranuts_index.md.D6Nd6-zH.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_shell_index.md.DtZNhEMK.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BlV0oBIf.js",
"/ran/assets/src_ranuts_file_file_info.md.B6RKGXgE.js",
"/ran/assets/cn_src_types_TS类型.md.jhgHOkKg.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_ranui_image_index.md.CVTGwYT4.js",
"/ran/assets/src_article_imagemin.md.DTTkhp2s.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_types_类型运算.md.ByusUoEk.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Hbp0eWMk.lean.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/src_article_sort_insert_index.md.CHosLUuJ.js",
"/ran/assets/cn_src_article_imagemin.md.Bq_99PuC.js",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/cn_src_article_math_linear_algebra.md.Dtkfwylf.lean.js",
"/ran/assets/cn_src_types_类型运算.md.COtlEd3U.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.pNUXWXol.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_system_design.md.DEVCvaBl.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_file_write_file.md.DAJ7xVK8.js",
"/ran/assets/src_article_typescript_recursion.md.B-3mU2YD.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranuts_index.md.rRxebZlD.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DAJ7xVK8.lean.js",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/src_ranui_tab_index.md.DrVoNTyr.lean.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.BOs-wE3m.lean.js",
"/ran/assets/src_article_babel.md.Bseh7wz8.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.V8CQ40Bv.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.ysEhgt8A.lean.js",
"/ran/assets/src_types_高级类型.md.DDRSHpNi.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_article_sort_count_index.md.ho6FmgmO.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.mvUXOTCl.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CdheGCh0.lean.js",
"/ran/assets/cn_src_note_centos.md.C8QDxU8_.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Z81zaQP3.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D1n3XP8w.js",
"/ran/assets/cn_src_ranui_player_index.md.HAK_SrYi.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_sort_radix_index.md.D8HkD2bD.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_sort_insert_index.md.CHosLUuJ.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.CsJuc9VK.lean.js",
"/ran/assets/src_ranui_tab_index.md.DrVoNTyr.js",
"/ran/assets/src_article_sort_quick_index.md.d1vEuWyk.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.C-YkeCE3.lean.js",
"/ran/assets/cn_src_article_babel.md.Bh6Hwv7y.lean.js",
"/ran/assets/cn_src_article_bundle.md.Dumv1jI_.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.O-cIBsdF.lean.js",
"/ran/assets/src_article_sort_heap_index.md.DeuiWtss.lean.js",
"/ran/assets/src_ranui_player_index.md.hlVHszXr.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranui_radar_index.md.Cxv6wjpp.lean.js",
"/ran/assets/src_article_sort_count_index.md.DdgyTqf9.js",
"/ran/assets/src_ranuts_file_watch_file.md.D6quHq8P.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.C7MCz5c3.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CW4EyiqK.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranui_index.md.r7K-J68C.lean.js",
"/ran/assets/src_ranui_message_index.md.Dzyefwav.js",
"/ran/assets/cn_src_article_imagemin.md.Bq_99PuC.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DVN48Loj.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranuts_file_read_dir.md.D9IOZhbd.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DjUJhjWf.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CuS57cw_.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BYCnzYT7.js",
"/ran/assets/src_types_模式匹配.md.C-71Gxuc.js",
"/ran/assets/cn_src_article_functional_programming.md.C6DVjS2m.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.PyyJ5nTR.lean.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CtjjKhdv.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CDKSdVnR.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.B6RKGXgE.lean.js",
"/ran/assets/src_ranui_select_index.md.BLplUkrO.js",
"/ran/assets/src_ranui_index.md.CywAK39D.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BKDlpZxE.js",
"/ran/assets/cn_src_ranui_icon_index.md.C7MCz5c3.js",
"/ran/assets/src_ranui_player_index.md.hlVHszXr.lean.js",
"/ran/assets/src_article_typescript_index.md.aKv3AQsg.js",
"/ran/assets/cn_src_ranui_loading_index.md.BPY0zNkG.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DAt7WRCq.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CuS57cw_.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BCT4kRwA.lean.js",
"/ran/assets/cn_src_types_高级类型.md.Cc9ftlC-.js",
"/ran/assets/cn_src_ranui_tab_index.md.PyyJ5nTR.js",
"/ran/assets/cn_src_ranui_input_index.md.vcT7CU__.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranui_player_index.md.HAK_SrYi.js",
"/ran/assets/src_types_模式匹配.md.C-71Gxuc.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DtZNhEMK.js",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/src_ranui_popover_index.md.BFpYgUch.js",
"/ran/assets/src_ranui_loading_index.md.BljJeNK5.js",
"/ran/assets/src_ranui_preview_index.md.D75D31jY.js",
"/ran/assets/cn_src_ranui_button_index.md.0EHKp7fc.js",
"/ran/assets/cn_src_article_video.md.BNV9QLYT.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.D__Xfcyl.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.CNRSfXxd.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.C384CfJe.lean.js",
"/ran/assets/cn_src_types_TS类型.md.jhgHOkKg.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.gKtqfRWJ.js",
"/ran/assets/cn_src_article_sort_heap_index.md.C0t3B7Qp.js",
"/ran/assets/src_article_typescript_calculate.md.DHAPcW5B.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DjUJhjWf.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BpkOP5na.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranui_input_index.md.B9eWqSWb.js",
"/ran/assets/src_ranui_radar_index.md.DOnkrLJK.lean.js",
"/ran/assets/src_ranui_message_index.md.Dzyefwav.lean.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/src_article_javascript_dom_load.md.CvWV2I-M.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CyzLXXyj.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_typescript_reconstruction.md.C384CfJe.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.C9OXjyLr.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BKDlpZxE.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_typescript_reconstruction.md.pNUXWXol.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DHAPcW5B.lean.js",
"/ran/assets/src_article_bundle.md.BUdmlOdD.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/babel.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/index.html",
"/ran/icon_168.png",
"/ran/manifest.json",
"/ran/sw1753596276.js",
"/ran/icon.png",
"/ran/icon_96.png",
"/ran/icon_192.png",
"/ran/icon_48.png",
"/ran/404.html",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/example.m3u8",
"/ran/home.svg",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_144.png",
"/ran/logo.png",
"/ran/vp-icons.css",
"/ran/icon_72.png",
"/ran/hashmap.json",
"/ran/screenshots_748x1340.jpg",
];
const VERSION = "1753596276";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



