const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_72.png",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/pagefind/pagefind.zh-cn_cec62d9926548.pf_meta",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_263135b.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/en_b110a5b.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_43904cb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/en_b24f7ef.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/en_5c725ae.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f1dffb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b3f5111.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_3df5c5f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_88e2f5c.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b528423.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cd3f426.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4560a64.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_38d8359.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3825a1a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_706591e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a5ca0e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_c2412d4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c97ee2.pf_fragment",
"/ran/pagefind/fragment/en_5094588.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_63cffab.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_45519b7.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_5eef384.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b2546fd.pf_fragment",
"/ran/pagefind/fragment/en_5861ab4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f186863.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5194d6f.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/en_df9b444.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/en_7118fbe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_beea2f2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ed4e4b0.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_6a9915b.pf_fragment",
"/ran/pagefind/fragment/en_30709d8.pf_fragment",
"/ran/pagefind/fragment/en_815cbc8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/en_2d1fbc2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e05d21d.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9b4ff84.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.en_c2b22186b3.pf_meta",
"/ran/pagefind/index/zh-cn_89a5478.pf_index",
"/ran/pagefind/index/zh-cn_3c29486.pf_index",
"/ran/pagefind/index/zh-cn_67e9a65.pf_index",
"/ran/pagefind/index/en_8c6f89f.pf_index",
"/ran/pagefind/index/en_23c08af.pf_index",
"/ran/pagefind/index/zh-cn_fcfffac.pf_index",
"/ran/pagefind/index/en_be21caa.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/cn/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/manifest.json",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/sw1713078868.js",
"/ran/assets/cn_src_ranui_icon_index.md.utVaiXvN.js",
"/ran/assets/cn_src_article_imagemin.md.DIvaeidK.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DZUYSiDh.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DVJqZcoQ.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CwbGDr7Q.js",
"/ran/assets/src_ranui_select_index.md.-EnXcTPS.js",
"/ran/assets/src_ranui_image_index.md.BOXyipYE.js",
"/ran/assets/src_ranui_radar_index.md.CiRwBBzO.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DhszjEno.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranui_input_index.md.B-A6TlIH.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DIvaeidK.js",
"/ran/assets/cn_src_ranui_player_index.md.DNIBoMeW.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_index.md.D-TR_fam.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.BZ6tdIDU.js",
"/ran/assets/src_ranuts_utils_task.md.wLc360Mr.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranuts_index.md.DFQanzIH.js",
"/ran/assets/src_article_sort_radix_index.md.DAGaKDHn.lean.js",
"/ran/assets/src_article_designMode.md.DCbOiQFv.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_types_TS类型.md.C_3Ll0ZC.js",
"/ran/assets/src_ranuts_utils_task.md.wLc360Mr.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DxoK2fEn.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranui_button_index.md.8ZdREDpv.js",
"/ran/assets/src_ranuts_file_watchFile.md.ym-qZxmy.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DWBHqNg5.js",
"/ran/assets/src_ranui_preview_index.md.DhpCBOKP.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_image_index.md.DaEv1uqD.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C5-Uy9uF.js",
"/ran/assets/src_article_typescript_reconstruction.md.CoyHLOy0.js",
"/ran/assets/cn_src_article_babel.md.C1A86W_p.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_article_sort_select_index.md.FLtAzPRl.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.BVpK8_F1.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_sort_select_index.md.DJUSTVN-.js",
"/ran/assets/src_ranui_checkbox_index.md.DDmXBWuQ.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CUqb4rfC.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CTUPeDZO.lean.js",
"/ran/assets/src_ranui_tabs_index.md.UVUj2e1_.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_index.md.D9iXpjGm.js",
"/ran/assets/src_ranui_index.md.D9iXpjGm.lean.js",
"/ran/assets/src_types_类型运算.md.ThCNgLdl.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.FTbYITfS.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CuInTI1T.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.BVpK8_F1.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CvfwH1O9.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.EYhUW_U-.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Drl_U3L_.lean.js",
"/ran/assets/src_types_TS类型.md.CXvVJUJd.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.tAOan1JN.js",
"/ran/assets/src_ranui_player_index.md.m8ROO5MI.js",
"/ran/assets/cn_src_ranui_button_index.md.DZ3Nm-04.lean.js",
"/ran/assets/src_article_babel.md.Bb6xdzXn.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DNIBoMeW.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranuts_utils_formatJson.md.D5pzhOJb.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BM-1Q3H0.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CpxrFWDO.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.DJUSTVN-.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CxEC5Ql_.js",
"/ran/assets/cn_src_ranui_modal_index.md.CPN1xxfK.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DVJqZcoQ.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CuInTI1T.js",
"/ran/assets/cn_src_article_typescript_index.md.CT1Rzres.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Dp6cN-4W.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.DqZYRLwZ.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranuts_file_readDir.md.CTUPeDZO.js",
"/ran/assets/cn_src_ranui_message_index.md.Cvbi-GK6.lean.js",
"/ran/assets/cn_src_article_designMode.md.DflJXmBO.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CVpKmTrj.js",
"/ran/assets/src_ranui_select_index.md.-EnXcTPS.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DCpdwtx7.lean.js",
"/ran/assets/src_article_imagemin.md.DanAEDqQ.js",
"/ran/assets/cn_src_ranuts_index.md.BC72zlkt.js",
"/ran/assets/cn_src_ranui_progress_index.md.DoRGs7Zj.js",
"/ran/assets/src_ranui_preview_index.md.DhpCBOKP.js",
"/ran/assets/cn_src_ranui_message_index.md.Cvbi-GK6.js",
"/ran/assets/src_article_sort_index.md.DWy-UUuP.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranuts_mimeType_mimeType.md.KtqzWFg7.lean.js",
"/ran/assets/src_ranui_message_index.md.fbl2Zhai.js",
"/ran/assets/src_ranui_image_index.md.BOXyipYE.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.FTbYITfS.js",
"/ran/assets/src_ranuts_utils_ocr.md.D4L85GXj.js",
"/ran/assets/src_ranuts_index.md.DFQanzIH.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DDmXBWuQ.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_types_类型运算.md.ThCNgLdl.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.BZ6tdIDU.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.DoRGs7Zj.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.tdyo00ZK.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.8BOO_F7r.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.DqZYRLwZ.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.B1QK8itN.lean.js",
"/ran/assets/src_types_模式匹配.md.vMgBjt4R.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.BZk-bV0F.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BVBtL6sZ.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DCpdwtx7.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_ranui_skeleton_index.md.BxEPrP6h.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.Dm1hu3B2.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Com1F-Vc.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DlOraLO0.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DZUYSiDh.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CEV-gOas.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DrNeTAcn.js",
"/ran/assets/src_ranui_progress_index.md.MmXXIX9E.js",
"/ran/assets/src_article_astParse_tokenizer.md.DxoK2fEn.js",
"/ran/assets/src_types_高级类型.md.Clsz_Z7R.js",
"/ran/assets/cn_src_ranui_tab_index.md.DlOraLO0.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranui_input_index.md.B-A6TlIH.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CwbGDr7Q.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C3x2JEOo.lean.js",
"/ran/assets/cn_src_ranui_index.md.DmARjv0p.js",
"/ran/assets/src_article_typescript_unionType.md.DzvevQS5.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.MPc4rprH.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C0h0Rcdk.lean.js",
"/ran/assets/src_ranui_popover_index.md.DJN0umo1.js",
"/ran/assets/src_article_typescript_recursion.md.-jGvqfiP.js",
"/ran/assets/cn_src_ranui_image_index.md.DaEv1uqD.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_sort_quick_index.md.CXiZJZ5y.js",
"/ran/assets/cn_src_article_sort_index.md.DSZxDtvV.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Dp6cN-4W.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Wr-DZzLp.lean.js",
"/ran/assets/src_article_sort_heap_index.md.B6FrKqdT.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.wa-MB6y6.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_file_readDir.md.CulpFBx1.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BxEPrP6h.js",
"/ran/assets/src_article_sort_shell_index.md.Q4Zi9iOH.lean.js",
"/ran/assets/src_article_sort_count_index.md.BAkz-KBT.js",
"/ran/assets/src_article_typescript_pattern.md.CpxrFWDO.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_types_TS类型.md.CXvVJUJd.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DEx_zmCK.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BC72zlkt.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CSvSchrF.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BVBtL6sZ.lean.js",
"/ran/assets/cn_src_ranui_index.md.DmARjv0p.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.B2EdbMVe.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/app.S9ZTNqfN.js",
"/ran/assets/src_ranui_icon_index.md.7b3J8AqM.js",
"/ran/assets/src_article_typescript_calculate.md.DrNeTAcn.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.D9EQu3Mb.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DWDsc2nE.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CoyHLOy0.lean.js",
"/ran/assets/src_article_imagemin.md.DanAEDqQ.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.FKnYlUKF.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranui_tab_index.md.BBfl1Uh2.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C5-Uy9uF.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.D4L85GXj.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_sort_index.md.DWy-UUuP.js",
"/ran/assets/style.iPsj3zFY.css",
"/ran/assets/cn_src_article_typescript_index.md.CT1Rzres.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CXiZJZ5y.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.B5jw1ccp.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CVpKmTrj.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CVc6pu-S.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Wr-DZzLp.js",
"/ran/assets/src_article_typescript_recursion.md.-jGvqfiP.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DEx_zmCK.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CLXYQKC9.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C3x2JEOo.js",
"/ran/assets/src_ranuts_file_watchFile.md.ym-qZxmy.js",
"/ran/assets/cn_index.md.D8foH-3z.js",
"/ran/assets/src_article_sort_heap_index.md.B6FrKqdT.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BTBrTnal.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_babel.md.C1A86W_p.js",
"/ran/assets/src_ranuts_bundler_index.md.Bdq1F4Tn.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.tdyo00ZK.js",
"/ran/assets/src_article_babel.md.Bb6xdzXn.js",
"/ran/assets/src_ranuts_bundler_index.md.Bdq1F4Tn.js",
"/ran/assets/index.md.BV_Xpe4z.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_file_writeFile.md.C7-Y1qsx.lean.js",
"/ran/assets/cn_src_types_TS类型.md.C_3Ll0ZC.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BTBrTnal.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CkyULSID.js",
"/ran/assets/src_article_sort_select_index.md.FLtAzPRl.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_sort_heap_index.md.DWBHqNg5.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CVc6pu-S.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.CJgZ3DnS.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranuts_utils_task.md.DpyR0MP0.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.B5jw1ccp.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_ranuts_utils_getCookie.md._XDlWqhv.lean.js",
"/ran/assets/cn_src_types_类型运算.md.iqbLPDe6.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_count_index.md.BAkz-KBT.lean.js",
"/ran/assets/src_article_sort_insert_index.md.qcfQ_ejJ.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.C7-Y1qsx.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranui_player_index.md.m8ROO5MI.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranuts_binaryTree_index.md.XRMrEeLU.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DWDsc2nE.js",
"/ran/assets/cn_src_ranui_preview_index.md.Bpkpt9YD.js",
"/ran/assets/cn_src_ranui_tabs_index.md.EdrPz_hI.js",
"/ran/assets/src_ranui_tab_index.md.BBfl1Uh2.lean.js",
"/ran/assets/src_types_模式匹配.md.vMgBjt4R.js",
"/ran/assets/src_ranui_modal_index.md.q8UCxz7k.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.Bpkpt9YD.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Com1F-Vc.js",
"/ran/assets/cn_src_ranui_radar_index.md.Drl_U3L_.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.CE_QoNxn.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.hxx2MV1o.js",
"/ran/assets/src_article_bundle.md.Brp9AJja.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CEV-gOas.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DpyR0MP0.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranuts_binaryTree_index.md.XRMrEeLU.lean.js",
"/ran/assets/src_ranui_message_index.md.fbl2Zhai.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/index.md.BV_Xpe4z.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_skeleton_index.md.B2EdbMVe.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.CulpFBx1.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BPQCzeyK.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CkyULSID.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.tAOan1JN.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DZ3Nm-04.js",
"/ran/assets/src_ranui_popover_index.md.DJN0umo1.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.CE_QoNxn.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranui_tabs_index.md.UVUj2e1_.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.hxx2MV1o.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.utVaiXvN.lean.js",
"/ran/assets/src_types_高级类型.md.Clsz_Z7R.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BM-1Q3H0.js",
"/ran/assets/src_ranuts_file_writeFile.md.Dm1hu3B2.js",
"/ran/assets/src_article_typescript_index.md.D-TR_fam.js",
"/ran/assets/src_article_designMode.md.DCbOiQFv.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Cr0cIOjF.lean.js",
"/ran/assets/src_article_sort_merge_index.md.BgurEgdn.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CxEC5Ql_.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.D9EQu3Mb.js",
"/ran/assets/src_article_sort_shell_index.md.Q4Zi9iOH.js",
"/ran/assets/cn_src_types_类型运算.md.iqbLPDe6.js",
"/ran/assets/src_ranuts_utils_getCookie.md._XDlWqhv.js",
"/ran/assets/cn_src_article_sort_index.md.DSZxDtvV.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.CJgZ3DnS.js",
"/ran/assets/src_ranuts_file_readFile.md.FKnYlUKF.js",
"/ran/assets/cn_index.md.D8foH-3z.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_article_bundle.md.D3UORAcm.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DhszjEno.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_article_bundle.md.D3UORAcm.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BPQCzeyK.js",
"/ran/assets/cn_src_ranui_input_index.md.B1QK8itN.js",
"/ran/assets/src_article_sort_bucket_index.md.wa-MB6y6.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_progress_index.md.MmXXIX9E.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.EYhUW_U-.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/theme.BiFNn_7A.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/index-BTiPI7ou.D7wPIxCW.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/en.m1bAnvv_.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/framework.uTpxwq_I.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/pdf-B2a6ll8f.lVr-YjCg.js",
"/ran/assets/chunks/index-CZlEoE62.BH9TDfQd.js",
"/ran/assets/chunks/index.CV-dxUKH.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/src_article_javascript_domLoad.md.BZk-bV0F.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CvfwH1O9.js",
"/ran/assets/src_article_functionalProgramming.md.DKBFxJMz.lean.js",
"/ran/assets/src_article_typescript_unionType.md.DzvevQS5.js",
"/ran/assets/src_article_sort_radix_index.md.DAGaKDHn.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C0h0Rcdk.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Cr0cIOjF.js",
"/ran/assets/src_article_bundle.md.Brp9AJja.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranui_modal_index.md.q8UCxz7k.js",
"/ran/assets/cn_src_ranui_select_index.md.8BOO_F7r.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CLXYQKC9.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.KtqzWFg7.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CSvSchrF.js",
"/ran/assets/src_ranuts_utils_formatJson.md.D5pzhOJb.js",
"/ran/assets/cn_src_ranui_tabs_index.md.EdrPz_hI.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.MPc4rprH.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_button_index.md.8ZdREDpv.lean.js",
"/ran/assets/src_article_sort_insert_index.md.qcfQ_ejJ.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_designMode.md.DflJXmBO.lean.js",
"/ran/assets/src_ranui_icon_index.md.7b3J8AqM.lean.js",
"/ran/assets/src_ranui_radar_index.md.CiRwBBzO.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_functionalProgramming.md.DKBFxJMz.js",
"/ran/assets/src_article_sort_quick_index.md.CUqb4rfC.js",
"/ran/assets/src_article_sort_merge_index.md.BgurEgdn.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_modal_index.md.CPN1xxfK.js",
"/ran/screenshots_2560x1440.jpg",
"/ran/home.svg",
"/ran/icon.png",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/icon_48.png",
];
const VERSION = "1713078868";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
    // google 上报不需要缓存
    'google',
    // 插件请求不用缓存
    'chrome-extension',
    // 百度的请求不用缓存
    'baidu.com',
    'blob:',
    'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
    GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
    SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
    INSTALL: 'install',
    FETCH: 'fetch',
    ACTIVATE: 'activate',
    MESSAGE: 'message',
    SYNC: 'sync',
    PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url } = request
    const { status } = fetchedResponse
    // 只缓存状态码为 200 的请求
    if (status !== RESPONSE_STATUS.SUCCESS) return
    if (filterRequest(request)) {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service worker update cache error:', error, request)
        })
    }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
    const { url, method } = request
    return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const { url } = request
        const responseFromCache = await caches.match(url);
        // 如果缓存中有，返回已经缓存的资源
        if (responseFromCache) return responseFromCache
        // 如果缓存中没有，就从网络中请求，并更新到缓存中
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        // 当缓存中也没有，请求也不可用的时候
        // 始终需要一个一个响应
        // 甚至可以设置回落的请求，在catch中继续发起请求
        console.log('service worker cacheFirst error:', error, request)
        return new Response("Network error happened", {
            status: 408,
            headers: { "Content-Type": "text/plain" },
        });
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('service worker deleteCache error:', error, key)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
    }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
            // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
            // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service worker fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service worker self installed error:', url, error);
                })
            )
        })
    );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
    // 拦截请求
    try {
        const { request } = event
        // 忽略 IGNORE_REQUEST_LIST 中的请求，不进行拦截
        if (filterRequest(request)) {
            const responseFromServer = cacheFirst(request)
            if (responseFromServer?.clone) {
                event.respondWith(responseFromServer);
            }
        }
    } catch (error) {
        console.log('service worker self fetch error:', error, event)
    }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
    event.waitUntil(deleteOldCaches());
});



