const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranui_loading_index.md.Bd9Q7gUl.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranui_message_index.md.DNvgQQx-.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CwSsQz64.js",
"/ran/assets/cn_src_article_sort_count_index.md.NFduNg7W.js",
"/ran/assets/cn_src_article_sort_index.md.C04koSlQ.js",
"/ran/assets/src_ranui_index.md.CBJLrmT0.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Byuqfc5o.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.qP21nl3n.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DYHyevto.js",
"/ran/assets/cn_src_article_typescript_union_type.md.DKS89RY-.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_sort_shell_index.md.BG8uKRZG.js",
"/ran/assets/src_ranui_progress_index.md.DNzCZ5yu.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranuts_utils_get_cookie.md.Ds877qWd.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_types_TS类型.md.CpyRGQcR.js",
"/ran/assets/cn_src_ranui_button_index.md.C_b1vlDO.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.R5Sn_sGc.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_article_sort_bubble_index.md.Dtr_IPyZ.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B9FJzz1F.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_loading_index.md.lIUKjg7R.js",
"/ran/assets/cn_src_types_高级类型.md.CNHcWMXU.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_sort_quick_index.md.BdbdUT0c.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.D30K4ssd.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranui_loading_index.md.Bd9Q7gUl.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.BuLf2l71.js",
"/ran/assets/src_types_TS类型.md.CpyRGQcR.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DXeZAEHj.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_video.md.BIGwSFGc.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.wM-LzGM4.js",
"/ran/assets/src_article_typescript_pattern.md.BbXdTPcD.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.CBLCwa64.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B9FJzz1F.lean.js",
"/ran/assets/cn_src_ranui_index.md.4JUoGl7M.lean.js",
"/ran/assets/cn_src_article_visual.md.DOWWiHU9.lean.js",
"/ran/assets/src_ranui_player_index.md.1aI2SxSO.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.C9sKXSIv.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_types_类型运算.md.3AufVbu5.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.Dtr_IPyZ.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.BkeKb_gA.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BFd40dmG.js",
"/ran/assets/src_ranui_button_index.md.DixW0aCa.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CBf0WxWL.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.2rkO_gRf.lean.js",
"/ran/assets/src_ranui_image_index.md.CNNH1vyP.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.R5Sn_sGc.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DKqKFIl6.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.B9-cKrio.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_typescript_reconstruction.md.CizQof2I.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BrF0bSKH.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.DKS89RY-.js",
"/ran/assets/src_article_javascript_dom_load.md.DIvsMf_8.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_typescript_calculate.md.CVKKJmS4.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.DX6hp35_.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BG8uKRZG.lean.js",
"/ran/assets/src_article_sort_index.md.Bs-HH6gT.js",
"/ran/assets/cn_src_note_ubuntu.md.8jA8K21s.js",
"/ran/assets/src_ranuts_utils_ocr.md.DRqiIQsh.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.3_KvbNyY.js",
"/ran/assets/src_article_sort_radix_index.md.Ce1VYxro.lean.js",
"/ran/assets/src_article_babel.md.D26WFEAF.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BLdkL82k.lean.js",
"/ran/assets/src_ranui_preview_index.md.se9feot3.lean.js",
"/ran/assets/cn_src_ranuts_index.md.Cmex-X6I.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.PSiObRX1.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.qnx93y8v.js",
"/ran/assets/src_ranuts_file_read_file.md.Cy_xjfI3.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CJY1p241.js",
"/ran/assets/src_ranui_select_index.md.iah9cJZ5.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CYF0D6tp.lean.js",
"/ran/assets/cn_src_article_imagemin.md.D4FK24Vk.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.CEXn97dp.js",
"/ran/assets/src_ranuts_mode_subscribe.md.lk9hPQkh.lean.js",
"/ran/assets/index.md.Dg8uykRJ.js",
"/ran/assets/src_article_typescript_calculate.md.CVKKJmS4.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_note_docker.md.MqyGpZ-a.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.wM-LzGM4.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CLk28lMG.lean.js",
"/ran/assets/src_article_bundle.md.7L0M-XWD.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranui_tab_index.md.JxTPf0zo.js",
"/ran/assets/src_ranui_message_index.md.DNvgQQx-.js",
"/ran/assets/cn_src_article_system_design.md.UH_pRPIo.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMgOiyIt.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CJY1p241.lean.js",
"/ran/assets/src_ranui_button_index.md.DixW0aCa.js",
"/ran/assets/src_ranui_player_index.md.1aI2SxSO.js",
"/ran/assets/cn_src_ranui_icon_index.md.B1K6rFgW.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_article_sort_radix_index.md.Ce1VYxro.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_babel.md.D26WFEAF.js",
"/ran/assets/cn_src_article_video.md.BIGwSFGc.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CE26fSQV.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DlzYcbmF.lean.js",
"/ran/assets/src_ranui_icon_index.md.izbKvzXX.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CfO1YqMu.lean.js",
"/ran/assets/src_ranui_select_index.md.iah9cJZ5.lean.js",
"/ran/assets/src_ranui_radar_index.md.BupCQY_T.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.DX6hp35_.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_types_模式匹配.md.jiaJgKPv.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_article_typescript_index.md.DjuFfJNJ.lean.js",
"/ran/assets/cn_src_article_sort_index.md.C04koSlQ.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_ranui_preview_index.md.se9feot3.js",
"/ran/assets/src_article_bundle.md.7L0M-XWD.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_types_类型运算.md.Bz35Vwy1.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BMoji0bt.lean.js",
"/ran/assets/cn_src_ranui_index.md.4JUoGl7M.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_utils_str2xml.md.BuLf2l71.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_note_ubuntu.md.8jA8K21s.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BMMVW8dk.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_ranui_tabs_index.md.CF4JI0Kr.js",
"/ran/assets/cn_src_types_高级类型.md.CNHcWMXU.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.CJYCCWoZ.js",
"/ran/assets/src_ranuts_index.md.cqUBpC8d.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_sort_count_index.md.Dmfh0Msy.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_sort_shell_index.md.BrF0bSKH.js",
"/ran/assets/src_article_sort_index.md.Bs-HH6gT.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.D30K4ssd.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.D8ctojKU.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_file_write_file.md.DlOJyrN4.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DKqKFIl6.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CGLa8hSy.lean.js",
"/ran/assets/src_types_模式匹配.md.CdXe6u4o.js",
"/ran/assets/cn_src_ranui_tab_index.md.BkeKb_gA.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.D1Xjb08V.lean.js",
"/ran/assets/cn_src_note_centos.md.CAlgNjoP.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.CEXn97dp.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BMoji0bt.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B8qV1t9Y.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_sort_radix_index.md.DYHyevto.lean.js",
"/ran/assets/cn_src_article_babel.md.gFPjXaFe.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.2rkO_gRf.js",
"/ran/assets/src_ranuts_bundler_index.md.GuA4jpAS.js",
"/ran/assets/cn_src_types_TS类型.md.DTgPm3w9.js",
"/ran/assets/src_article_sort_select_index.md.BW6M3eGJ.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CE26fSQV.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.PSiObRX1.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Byuqfc5o.js",
"/ran/assets/src_ranui_index.md.CBJLrmT0.lean.js",
"/ran/assets/src_ranui_modal_index.md.BFi6jd7M.js",
"/ran/assets/src_article_typescript_pattern.md.BbXdTPcD.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_bundle.md.DV8LmfsH.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DBUSH41Q.js",
"/ran/assets/cn_index.md.BRKHYexd.js",
"/ran/assets/src_ranui_tab_index.md.JxTPf0zo.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.Bd4xPnOs.js",
"/ran/assets/src_article_sort_quick_index.md.BdbdUT0c.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DyV1QmYy.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DmVhm--Q.js",
"/ran/assets/cn_src_article_babel.md.gFPjXaFe.js",
"/ran/assets/src_article_typescript_union_type.md.BZ6NKAMc.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B8MgwUHx.js",
"/ran/assets/src_ranui_image_index.md.CNNH1vyP.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DyV1QmYy.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.DmVhm--Q.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CsB3Eap_.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_skeleton_index.md.CEKKHAzH.lean.js",
"/ran/assets/src_ranuts_utils_task.md.foBeg_ZJ.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranui_input_index.md.Bj6HpgM-.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.C6pCXLAW.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/app.D0a7USwW.js",
"/ran/assets/cn_src_ranui_progress_index.md.DZ79cW9g.lean.js",
"/ran/assets/cn_src_article_design_mode.md.ppD5RjtN.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Vr7_imrj.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DouaFDGa.js",
"/ran/assets/cn_index.md.BRKHYexd.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_functional_programming.md.BKkkS-9K.lean.js",
"/ran/assets/src_ranui_modal_index.md.BFi6jd7M.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_sort_merge_index.md.CsB3Eap_.lean.js",
"/ran/assets/src_ranui_input_index.md.Bj6HpgM-.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DBUSH41Q.lean.js",
"/ran/assets/src_article_sort_count_index.md.Dmfh0Msy.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CxFQOoXb.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CLk28lMG.js",
"/ran/assets/src_ranui_tabs_index.md.CF4JI0Kr.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CDpPa8tL.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.8N2EWwmy.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.B1K6rFgW.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CYF0D6tp.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.D1Xjb08V.js",
"/ran/assets/cn_src_article_bundle.md.DV8LmfsH.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_imagemin.md.DT2aCLvO.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.oX7X8hqF.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B8qV1t9Y.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_ranui_skeleton_index.md.C6pCXLAW.js",
"/ran/assets/index.md.Dg8uykRJ.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DxktOURY.lean.js",
"/ran/assets/cn_src_article_imagemin.md.D4FK24Vk.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CV8LboEb.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_article_imagemin.md.DT2aCLvO.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B8MgwUHx.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.D5PsiI32.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranuts_utils_format_json.md.D8ctojKU.js",
"/ran/assets/cn_src_ranui_select_index.md.CwSsQz64.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CV8LboEb.js",
"/ran/assets/cn_src_ranui_input_index.md.CDpPa8tL.js",
"/ran/assets/src_article_sort_select_index.md.BW6M3eGJ.js",
"/ran/assets/cn_src_ranui_popover_index.md.8N2EWwmy.js",
"/ran/assets/src_ranuts_file_append_file.md.DxktOURY.js",
"/ran/assets/src_types_模式匹配.md.CdXe6u4o.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CBf0WxWL.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DO3xK5r2.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.Da__W1oX.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BLdkL82k.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DlOJyrN4.js",
"/ran/assets/cn_src_ranui_radar_index.md.Lms9r6pP.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_typescript_union_type.md.BZ6NKAMc.js",
"/ran/assets/cn_src_ranui_player_index.md.BS178Tmh.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DouaFDGa.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_types_类型运算.md.3AufVbu5.js",
"/ran/assets/src_ranuts_mode_subscribe.md.lk9hPQkh.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.DAsjG5i4.js",
"/ran/assets/cn_src_note_centos.md.CAlgNjoP.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.ClTfflRL.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_article_system_design.md.UH_pRPIo.js",
"/ran/assets/src_article_typescript_recursion.md.B3o6cjK5.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranuts_utils_task.md.foBeg_ZJ.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_functional_programming.md.Be7Sm052.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_index.md.cqUBpC8d.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Lms9r6pP.js",
"/ran/assets/src_article_typescript_reconstruction.md.CizQof2I.lean.js",
"/ran/assets/src_ranui_progress_index.md.DNzCZ5yu.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.Ds877qWd.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_image_index.md.BIrxcHiK.js",
"/ran/assets/cn_src_ranui_progress_index.md.DZ79cW9g.js",
"/ran/assets/cn_src_ranui_math_index.md.DIqHmXLt.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BIrxcHiK.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.C_b1vlDO.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_article_design_mode.md.C48qOUJi.lean.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.UmsLlfP-.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/VPLocalSearchBox.D7wxRsfQ.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/@localSearchIndexroot.-jA4N9Ec.js",
"/ran/assets/chunks/index.B8mYliZ2.js",
"/ran/assets/chunks/theme.DISV1XAE.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/@localSearchIndexcn.DxxXuw0s.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/src_ranui_math_index.md.2Ej_b3N8.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_types_模式匹配.md.jiaJgKPv.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranuts_mime_type_mime_type.md.oX7X8hqF.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_types_TS类型.md.DTgPm3w9.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.DAsjG5i4.lean.js",
"/ran/assets/src_types_高级类型.md.BGscPVjy.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D_MRgFcT.js",
"/ran/assets/cn_src_ranuts_index.md.Cmex-X6I.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DcogTOnU.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BMMVW8dk.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.Bd4xPnOs.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.D5PsiI32.js",
"/ran/assets/cn_src_article_sort_count_index.md.NFduNg7W.lean.js",
"/ran/assets/src_article_functional_programming.md.Be7Sm052.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CEKKHAzH.js",
"/ran/assets/src_ranuts_file_read_file.md.Cy_xjfI3.js",
"/ran/assets/src_ranui_icon_index.md.izbKvzXX.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_select_index.md.Da__W1oX.js",
"/ran/assets/src_ranui_math_index.md.2Ej_b3N8.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.lIUKjg7R.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.3_KvbNyY.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_bundler_index.md.GuA4jpAS.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DO3xK5r2.js",
"/ran/assets/src_types_类型运算.md.Bz35Vwy1.js",
"/ran/assets/style.zTfaa9RN.css",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMgOiyIt.js",
"/ran/assets/src_types_高级类型.md.BGscPVjy.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D_MRgFcT.lean.js",
"/ran/assets/src_ranui_popover_index.md.DSohnxsJ.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.D2JPxenX.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_ranuts_utils_ocr.md.DRqiIQsh.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_math_linear_algebra.md.D2JPxenX.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_typescript_recursion.md.B3o6cjK5.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.DIqHmXLt.js",
"/ran/assets/src_ranuts_file_file_info.md.CBLCwa64.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Vr7_imrj.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DlzYcbmF.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_functional_programming.md.BKkkS-9K.js",
"/ran/assets/cn_src_article_sort_heap_index.md.ClTfflRL.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_checkbox_index.md.qP21nl3n.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.DIvsMf_8.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_design_mode.md.C48qOUJi.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BFd40dmG.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DcogTOnU.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.CJYCCWoZ.lean.js",
"/ran/assets/src_ranui_radar_index.md.BupCQY_T.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_article_sort_bucket_index.md.C9sKXSIv.js",
"/ran/assets/src_ranui_popover_index.md.DSohnxsJ.lean.js",
"/ran/assets/cn_src_article_visual.md.DOWWiHU9.js",
"/ran/assets/cn_src_article_design_mode.md.ppD5RjtN.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CGLa8hSy.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.CxFQOoXb.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_sort_insert_index.md.DXeZAEHj.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_typescript_index.md.DjuFfJNJ.js",
"/ran/assets/cn_src_ranui_player_index.md.BS178Tmh.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_file_watch_file.md.qnx93y8v.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_note_docker.md.MqyGpZ-a.js",
"/ran/assets/cn_src_ranui_modal_index.md.B9-cKrio.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CfO1YqMu.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1742109080.js",
];
const VERSION = "1742109080";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



