const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/hashmap.json",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/manifest.json",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/favicon.ico",
"/ran/pagefind/pagefind.zh-cn_d218f5d2869fb.pf_meta",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7be51c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/en_2727185.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_6a4c97c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b0cd6bd.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c45892d.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_393fd51.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_94b27bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind.en_61b0e522de.pf_meta",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/index/zh-cn_36f18f8.pf_index",
"/ran/pagefind/index/en_6f446a6.pf_index",
"/ran/pagefind/index/zh-cn_2314426.pf_index",
"/ran/pagefind/index/en_eb558a5.pf_index",
"/ran/pagefind/index/zh-cn_34cf86b.pf_index",
"/ran/pagefind/index/en_a96803f.pf_index",
"/ran/pagefind/index/zh-cn_8bbd46c.pf_index",
"/ran/index.html",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/assets/src_article_sort_quick_index.md.IY2GMfa_.lean.js",
"/ran/assets/src_ranui_input_index.md.CJrZFBxn.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_sort_insert_index.md.-X-qiKwq.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CGYxGcFA.js",
"/ran/assets/cn_src_ranui_tabs_index.md.CFMwimsJ.js",
"/ran/assets/cn_src_ranui_select_index.md.UClwWgIK.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranui_button_index.md.Ch6qY2B8.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_tab_index.md.JJFNQnKd.lean.js",
"/ran/assets/src_types_高级类型.md.BwEYsU7_.js",
"/ran/assets/src_ranuts_utils_ocr.md.CNCkZxmJ.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.D5_ArDQ7.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CSPh6jc4.js",
"/ran/assets/src_article_sort_heap_index.md.BJiQth_8.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BtELClfF.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CboqnDoi.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.4MdmIvEh.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.mi04_gNv.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.CQffbHNx.js",
"/ran/assets/cn_src_article_sort_count_index.md.BotnxSuN.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CE3EiVZW.lean.js",
"/ran/assets/style.CqLoqpUb.css",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DKp_g2K8.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranui_modal_index.md.znFbggUK.lean.js",
"/ran/assets/src_ranui_preview_index.md.CkEBgJy1.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.ClofueA_.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DA_tu31S.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.0z0Kb_F1.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DhGJrCtt.js",
"/ran/assets/src_article_sort_radix_index.md.BQoVugOI.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.UbEDjF3J.lean.js",
"/ran/assets/cn_src_article_babel.md.BJvN_uj6.js",
"/ran/assets/cn_src_article_sort_select_index.md.BQddqVfO.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.Bt4bji55.js",
"/ran/assets/src_ranui_icon_index.md.Cb7ua3JJ.js",
"/ran/assets/src_ranui_button_index.md.rcx4p-S1.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CsZwfiud.lean.js",
"/ran/assets/src_ranui_player_index.md.DIndefJg.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_popover_index.md.C9rUwpCN.lean.js",
"/ran/assets/src_article_typescript_index.md.Bbk74UF9.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.QT-Mo2CJ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B3Ae7rEa.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CS2fmKRV.js",
"/ran/assets/src_ranuts_utils_ocr.md.CNCkZxmJ.js",
"/ran/assets/src_article_sort_heap_index.md.BJiQth_8.js",
"/ran/assets/src_article_typescript_reconstruction.md.yj9OFp9k.js",
"/ran/assets/src_ranui_index.md.ChE-165T.js",
"/ran/assets/src_ranui_select_index.md.DY_JInX4.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BrvXZU2c.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DA_tu31S.js",
"/ran/assets/src_ranuts_utils_task.md.DIheCP51.lean.js",
"/ran/assets/src_article_designMode.md.TBRenxQP.js",
"/ran/assets/cn_src_types_TS类型.md.Ced8vm0U.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DZ1sRd4C.js",
"/ran/assets/src_article_typescript_calculate.md.Bna9dA9C.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.UYw9CsFg.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_typescript_recursion.md.B2KPn-V0.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.ClofueA_.js",
"/ran/assets/cn_src_ranuts_index.md.Cui2pqwa.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DHxfWS4r.lean.js",
"/ran/assets/src_ranui_message_index.md.CjBCOO7u.js",
"/ran/assets/src_ranui_progress_index.md.FwpcGMSe.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_types_TS类型.md.OekOhiJD.js",
"/ran/assets/src_article_designMode.md.TBRenxQP.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.B5UumojW.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CpkU78_E.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.Dwdd99am.js",
"/ran/assets/src_article_javascript_domLoad.md.oC5Qprys.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.DWkMq0SS.js",
"/ran/assets/cn_src_ranui_index.md.BFllVjL9.js",
"/ran/assets/cn_src_article_bundle.md.3MyHRe6-.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_bundle.md.C_SvCX96.js",
"/ran/assets/src_types_TS类型.md.OekOhiJD.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.g80WPeX7.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranui_tabs_index.md.DeYB7exT.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_article_sort_select_index.md.Dl3OR3QI.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Dkm-0bhV.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_types_模式匹配.md.Cf4HA94V.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.jH58vwzW.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_sort_insert_index.md.D6PsJ4hU.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.4M9gxHJ0.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.TvwEoQqO.js",
"/ran/assets/src_article_typescript_index.md.Bbk74UF9.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BVwwj5Gj.js",
"/ran/assets/cn_src_article_bundle.md.3MyHRe6-.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.D5_ArDQ7.js",
"/ran/assets/src_article_sort_count_index.md.CNdIv14X.js",
"/ran/assets/src_article_sort_select_index.md.Dl3OR3QI.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CsZwfiud.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_index.md.BINFhsaW.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CFRRD8_W.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.BacVZZ8n.js",
"/ran/assets/index.md.BOu92k3C.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.Ch6qY2B8.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Dq2_Xq-2.js",
"/ran/assets/cn_src_article_sort_shell_index.md.jH58vwzW.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.TC3WA2is.js",
"/ran/assets/cn_src_article_typescript_index.md.BacVZZ8n.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.C7mi8hUe.js",
"/ran/assets/src_ranuts_bundler_index.md.XgbQLucP.js",
"/ran/assets/src_ranui_radar_index.md.CBJjVi4F.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DE1AFwG0.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_message_index.md.CjBCOO7u.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BlMN6uiC.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.CQffbHNx.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BcLciOUa.js",
"/ran/assets/cn_src_article_sort_heap_index.md.g80WPeX7.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.Bgf8y5G6.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CSPh6jc4.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DqsXtJZi.lean.js",
"/ran/assets/cn_index.md.Cmxm4RFk.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.CTQn1j2H.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranuts_bundler_index.md.w6ZlAmm-.js",
"/ran/assets/cn_src_article_sort_radix_index.md.PmuqDb6X.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_utils_task.md.CGYxGcFA.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BlMN6uiC.js",
"/ran/assets/src_ranuts_bundler_index.md.XgbQLucP.lean.js",
"/ran/assets/cn_src_article_designMode.md.TeI8UFOg.js",
"/ran/assets/src_ranuts_file_readDir.md.DWkMq0SS.lean.js",
"/ran/assets/src_ranui_popover_index.md.C9rUwpCN.js",
"/ran/assets/src_article_sort_merge_index.md.DxzfRKzD.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CboqnDoi.js",
"/ran/assets/src_article_sort_bubble_index.md.CksZ-eHf.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.UYw9CsFg.js",
"/ran/assets/cn_src_ranui_modal_index.md.znFbggUK.js",
"/ran/assets/src_article_typescript_unionType.md.CAARCWVP.lean.js",
"/ran/assets/src_ranui_button_index.md.rcx4p-S1.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BotnxSuN.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.QT-Mo2CJ.js",
"/ran/assets/cn_src_types_模式匹配.md.Cf4HA94V.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranui_checkbox_index.md.DZ1sRd4C.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_article_typescript_unionType.md.D7bEfv2c.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Dkm-0bhV.js",
"/ran/assets/cn_src_ranui_popover_index.md.Cz21SAQ3.lean.js",
"/ran/assets/cn_src_ranui_index.md.BFllVjL9.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.CUsn3_29.js",
"/ran/assets/src_ranui_image_index.md.BdvQ8y-l.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CE3EiVZW.js",
"/ran/assets/src_ranuts_file_appendFile.md.Crfg0SkF.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.4MdmIvEh.lean.js",
"/ran/assets/src_article_babel.md.CtW3ByJ8.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_article_typescript_unionType.md.CAARCWVP.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_babel.md.CtW3ByJ8.js",
"/ran/assets/src_article_functionalProgramming.md.ZfQXvbqh.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranui_modal_index.md.Cz4HNYEi.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_javascript_domLoad.md.oC5Qprys.js",
"/ran/assets/src_ranui_radar_index.md.CBJjVi4F.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DKp_g2K8.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_icon_index.md.Cb7ua3JJ.lean.js",
"/ran/assets/src_ranui_tabs_index.md.DeYB7exT.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_bundle.md.C_SvCX96.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.CFMwimsJ.lean.js",
"/ran/assets/src_ranui_modal_index.md.Cz4HNYEi.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.B7Zb3f6Y.js",
"/ran/assets/src_ranui_skeleton_index.md.CFROTnkI.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_utils_task.md.DIheCP51.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_typescript_recursion.md.BHZNje36.lean.js",
"/ran/assets/src_ranui_image_index.md.BdvQ8y-l.lean.js",
"/ran/assets/src_ranui_progress_index.md.FwpcGMSe.js",
"/ran/assets/cn_src_ranui_message_index.md.B7Zb3f6Y.lean.js",
"/ran/assets/src_types_类型运算.md.DRtdJYbo.js",
"/ran/assets/src_article_sort_bucket_index.md.Brj5QTIe.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DIo-Uch6.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.Dwdd99am.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.mi04_gNv.js",
"/ran/assets/src_article_sort_bubble_index.md.CksZ-eHf.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_typescript_calculate.md.CpkU78_E.js",
"/ran/assets/cn_src_ranui_radar_index.md.COzvXZ7M.js",
"/ran/assets/src_ranui_preview_index.md.CkEBgJy1.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_file_readFile.md.TC3WA2is.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DxzfRKzD.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.4M9gxHJ0.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_sort_quick_index.md.IY2GMfa_.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.CTQn1j2H.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/index.Bol6qi2P.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/index-DUQ13h42.c6D3EbfT.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/theme.BNBnCL66.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index-DSFfwC9e.RkPMzg7f.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/pdf-B2a6ll8f.CmK-CylF.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/pwa-install.es.BZyo4fnY.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/docx-CChZ5Ycr.NiVSZbPW.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/framework.DU63L2vM.js",
"/ran/assets/chunks/jszip.min-DD9Dc6z4.BsDI-Ugu.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_article_sort_merge_index.md.Dq2_Xq-2.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CPGZQKeI.js",
"/ran/assets/cn_src_article_imagemin.md.B0CUIvpF.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CHRTZNvR.js",
"/ran/assets/index.md.BOu92k3C.js",
"/ran/assets/cn_src_article_imagemin.md.B0CUIvpF.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CFRRD8_W.js",
"/ran/assets/src_article_sort_index.md.BINFhsaW.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DEmcHCyD.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_types_高级类型.md.uvSh5ebl.js",
"/ran/assets/cn_src_article_typescript_recursion.md.B2KPn-V0.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_article_typescript_recursion.md.BHZNje36.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CjK5-qt_.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.v6Sj14nT.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.nqTTOX7h.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.B5UumojW.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.nqTTOX7h.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.w6ZlAmm-.lean.js",
"/ran/assets/src_article_sort_count_index.md.CNdIv14X.lean.js",
"/ran/assets/src_ranui_player_index.md.DIndefJg.js",
"/ran/assets/src_article_typescript_calculate.md.Bna9dA9C.js",
"/ran/assets/cn_src_article_sort_insert_index.md.-X-qiKwq.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.COzvXZ7M.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.v6Sj14nT.lean.js",
"/ran/assets/src_types_高级类型.md.BwEYsU7_.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CQKLUWmB.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Brj5QTIe.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.TvwEoQqO.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_types_TS类型.md.Ced8vm0U.lean.js",
"/ran/assets/src_article_sort_shell_index.md.B1azo77f.js",
"/ran/assets/src_article_typescript_pattern.md.BcLciOUa.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_types_高级类型.md.uvSh5ebl.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B3Ae7rEa.js",
"/ran/assets/src_ranuts_utils_filterObj.md.CUsn3_29.lean.js",
"/ran/assets/src_article_imagemin.md.BueKfLUI.lean.js",
"/ran/assets/cn_src_ranuts_index.md.Cui2pqwa.lean.js",
"/ran/assets/src_article_functionalProgramming.md.ZfQXvbqh.lean.js",
"/ran/assets/src_ranui_input_index.md.CJrZFBxn.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.C7mi8hUe.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.BVBxGOmM.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.0z0Kb_F1.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.UbEDjF3J.js",
"/ran/assets/src_ranuts_index.md.tru1psJr.js",
"/ran/assets/app.BJrWqgrO.js",
"/ran/assets/cn_src_article_sort_radix_index.md.PmuqDb6X.js",
"/ran/assets/src_article_sort_insert_index.md.D6PsJ4hU.lean.js",
"/ran/assets/cn_src_article_babel.md.BJvN_uj6.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Cz21SAQ3.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BhtpKkqE.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DHxfWS4r.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_article_imagemin.md.BueKfLUI.js",
"/ran/assets/src_article_astParse_tokenizer.md.Bt4bji55.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BtELClfF.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.BQddqVfO.js",
"/ran/assets/src_types_类型运算.md.DRtdJYbo.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_article_functionalProgramming.md.DEmcHCyD.js",
"/ran/assets/cn_src_article_designMode.md.TeI8UFOg.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CS2fmKRV.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BVwwj5Gj.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranuts_binaryTree_index.md.CQKLUWmB.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DIo-Uch6.js",
"/ran/assets/src_article_typescript_reconstruction.md.yj9OFp9k.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.D7bEfv2c.js",
"/ran/assets/cn_index.md.Cmxm4RFk.js",
"/ran/assets/cn_src_ranui_select_index.md.UClwWgIK.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_types_模式匹配.md.BONKA5Vx.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CHRTZNvR.lean.js",
"/ran/assets/src_ranui_tab_index.md.JJFNQnKd.js",
"/ran/assets/src_article_sort_shell_index.md.B1azo77f.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BhtpKkqE.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_sort_radix_index.md.BQoVugOI.js",
"/ran/assets/cn_src_ranui_player_index.md.Bgf8y5G6.lean.js",
"/ran/assets/src_ranuts_index.md.tru1psJr.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CPGZQKeI.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CFROTnkI.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.BVBxGOmM.js",
"/ran/assets/src_ranuts_file_appendFile.md.Crfg0SkF.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DqsXtJZi.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CjK5-qt_.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DhGJrCtt.lean.js",
"/ran/assets/src_ranui_select_index.md.DY_JInX4.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DE1AFwG0.js",
"/ran/assets/src_ranui_index.md.ChE-165T.lean.js",
"/ran/assets/src_types_模式匹配.md.BONKA5Vx.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BrvXZU2c.js",
"/ran/sw1715523364.js",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/icon_48.png",
"/ran/icon.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/bundle.html",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/bundle.html",
"/ran/icon_144.png",
];
const VERSION = "1715523364";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
  // 拦截请求
    const { request, respondWith } = event
    respondWith(cacheFirst(request))
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



