const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/cn/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/404.html",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/example.m3u8",
"/ran/icon_96.png",
"/ran/manifest.json",
"/ran/icon_48.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/icon_72.png",
"/ran/icon_144.png",
"/ran/index.html",
"/ran/screenshots_748x1340.jpg",
"/ran/sw1718521856.js",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bdf8a5d.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_345875a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59dbda6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_232a577.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_78b0843.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e56b682.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95d5d46.pf_fragment",
"/ran/pagefind/fragment/en_dc61586.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bdf92be.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_43e1883.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_786dd1d.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a56d4b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1748c31.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_45694f5.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_5d7564e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3f12c13.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_41329e8.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_976d864.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_fa9896c.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e7387aa.pf_fragment",
"/ran/pagefind/fragment/en_cf8161e.pf_fragment",
"/ran/pagefind/fragment/en_2f66cb4.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9d31b8f.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_4126fd6.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_53bdf9f.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_c3245b6.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9bbac8e.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f482cc6.pf_fragment",
"/ran/pagefind/fragment/en_3af9583.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6969c9a.pf_fragment",
"/ran/pagefind/fragment/en_cc6a6d2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b8ae423.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cd6ddc6.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_4bc9db8.pf_fragment",
"/ran/pagefind/fragment/en_fc842d8.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_1e22c06.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_909c711.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/pagefind.zh-cn_5181cad97f5d8.pf_meta",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/index/en_a5f290c.pf_index",
"/ran/pagefind/index/zh-cn_bbd3785.pf_index",
"/ran/pagefind/index/zh-cn_56e8f9b.pf_index",
"/ran/pagefind/index/en_8cf7197.pf_index",
"/ran/pagefind/index/zh-cn_ea4f908.pf_index",
"/ran/pagefind/index/en_ef88261.pf_index",
"/ran/pagefind/index/zh-cn_bff3193.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind.en_82225633e2.pf_meta",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/assets/src_types_TS类型.md.eGcmqCtE.js",
"/ran/assets/src_article_typescript_calculate.md.BwbnrWH2.js",
"/ran/assets/cn_src_ranui_message_index.md.DBRaIFtm.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_sort_bucket_index.md.CJx3XzXg.js",
"/ran/assets/src_article_sort_heap_index.md.cMCf7xJQ.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CPcRgbib.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranuts_utils_ocr.md.DJilltBf.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CAlr4Vlp.js",
"/ran/assets/cn_src_ranuts_utils_task.md.B--N-moD.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BLqU2ENp.lean.js",
"/ran/assets/index.md.DbfZVNgZ.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_index.md.BYcBnjsp.js",
"/ran/assets/src_ranuts_utils_filterObj.md.D1bJTYY4.js",
"/ran/assets/src_ranui_index.md.peTB5nfn.js",
"/ran/assets/cn_src_article_bundle.md.CzysHR7H.js",
"/ran/assets/src_article_sort_select_index.md.C4E0h3cP.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_index.md.peTB5nfn.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BqA03_ig.lean.js",
"/ran/assets/src_ranui_image_index.md.RwHRS9QM.js",
"/ran/assets/cn_src_ranui_icon_index.md.DgGohpYm.js",
"/ran/assets/cn_index.md.D78v8JyG.lean.js",
"/ran/assets/src_types_模式匹配.md.9011byme.lean.js",
"/ran/assets/src_article_typescript_index.md.9rx_ZmbA.lean.js",
"/ran/assets/src_ranui_progress_index.md.BN0XDmFS.js",
"/ran/assets/src_ranuts_utils_str2xml.md.6M7TqaWG.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_loading_index.md.BRHael-a.js",
"/ran/assets/src_ranui_popover_index.md.B86SkVnE.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.G7OKzhad.js",
"/ran/assets/cn_src_ranui_image_index.md.La_8F0O4.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BqA03_ig.js",
"/ran/assets/cn_src_ranui_select_index.md.Dhqg-Shp.lean.js",
"/ran/assets/src_ranui_icon_index.md.IUZbUaIZ.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DrNgah11.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D0qde2y0.js",
"/ran/assets/src_ranui_message_index.md.C7I1JAwP.js",
"/ran/assets/cn_src_ranui_modal_index.md.C7NPT5is.js",
"/ran/assets/src_article_sort_merge_index.md.P9D9VbIv.js",
"/ran/assets/cn_src_article_sort_count_index.md.BLqU2ENp.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DltrrKfH.js",
"/ran/assets/src_article_functionalProgramming.md.RFxxOpGc.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CKsltxUE.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CUZnY5zj.js",
"/ran/assets/src_article_sort_select_index.md.C4E0h3cP.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_types_高级类型.md.BBU9USel.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_types_高级类型.md.BBU9USel.js",
"/ran/assets/cn_src_ranui_tab_index.md.FqnYIDas.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_types_类型运算.md.DPWqXKyx.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_sort_bucket_index.md.CJx3XzXg.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DbaW3tEk.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.Njno-_xZ.js",
"/ran/assets/cn_src_ranui_player_index.md.BIcUFhbA.lean.js",
"/ran/assets/src_ranui_modal_index.md.B-ultrsE.js",
"/ran/assets/src_article_babel.md.DuDIADQp.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.BcSfOtHA.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranui_skeleton_index.md.BiWgbxHn.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.Dc0MrlPx.js",
"/ran/assets/cn_src_ranui_input_index.md.CQ90yjHM.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_radar_index.md.C1hCWSBV.lean.js",
"/ran/assets/src_article_sort_quick_index.md.Cpmz4pMu.js",
"/ran/assets/src_article_sort_count_index.md.DhR4zlw6.js",
"/ran/assets/src_ranuts_utils_getCookie.md.4hp1MEPT.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DfX-imbR.js",
"/ran/assets/cn_src_article_sort_select_index.md.DM_5SuZz.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.BiUnx9OR.js",
"/ran/assets/src_article_typescript_unionType.md.AzLAzA6c.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CLgZQ4fj.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CUZnY5zj.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DnOFIstz.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BG1Lfyhd.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BG71jM76.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BRHael-a.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BQ5Dm5nv.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ck2Ql4qw.js",
"/ran/assets/cn_src_ranui_preview_index.md.cRaedOBn.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CH3d_GuB.js",
"/ran/assets/src_article_astParse_tokenizer.md.BcSfOtHA.lean.js",
"/ran/assets/cn_src_article_bundle.md.CzysHR7H.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DBdmTvCX.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DnUtl6Ip.js",
"/ran/assets/cn_src_types_高级类型.md.5lnoxCC5.lean.js",
"/ran/assets/src_ranui_player_index.md.DU3X2RX0.js",
"/ran/assets/src_ranui_preview_index.md.C1UBomfy.js",
"/ran/assets/src_article_javascript_domLoad.md.CRTBU2Fp.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CPcRgbib.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_typescript_calculate.md.CjwQ2vfX.lean.js",
"/ran/assets/cn_src_ranui_index.md.BSHFzcC7.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.qf1011-1.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranui_tabs_index.md.fCRVPvDG.js",
"/ran/assets/cn_src_ranui_select_index.md.Dhqg-Shp.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BlNjAv9V.lean.js",
"/ran/assets/src_article_sort_quick_index.md.Cpmz4pMu.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CLgZQ4fj.js",
"/ran/assets/src_ranuts_utils_ocr.md.DJilltBf.js",
"/ran/assets/src_ranuts_bundler_index.md.DUXyYU8e.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranuts_index.md.BlkUiA5B.js",
"/ran/assets/src_ranui_select_index.md.Dwqq509g.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.BvXFelik.lean.js",
"/ran/assets/src_ranui_loading_index.md.soNFh9LB.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.cRaedOBn.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Bbqzd90E.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_utils_filterObj.md.D1bJTYY4.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.CRTBU2Fp.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.XKlvBOVe.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_index.md.BlkUiA5B.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Ccbnls4_.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md._t7Mfubv.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranui_button_index.md.C8ZmU7XX.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_radar_index.md.BQ5Dm5nv.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_index.md.CljD6ebZ.lean.js",
"/ran/assets/cn_src_article_babel.md.CmF15HcQ.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Bbqzd90E.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_designMode.md.RVGA-inm.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DltrrKfH.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CDYCKHha.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ck2Ql4qw.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CDYCKHha.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DrNgah11.js",
"/ran/assets/index.md.DbfZVNgZ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DfX-imbR.lean.js",
"/ran/assets/cn_index.md.D78v8JyG.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CbITKzml.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DnUtl6Ip.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C4LC602q.js",
"/ran/assets/src_ranuts_file_appendFile.md.D-SI9n6A.js",
"/ran/assets/cn_src_article_imagemin.md.Ba8CNlYc.js",
"/ran/assets/cn_src_ranui_progress_index.md.BomW5Agg.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_utils_task.md.b_7Gbbn2.js",
"/ran/assets/src_article_functionalProgramming.md.RFxxOpGc.js",
"/ran/assets/src_ranuts_utils_str2xml.md.6M7TqaWG.lean.js",
"/ran/assets/src_article_typescript_pattern.md.kdZeCeQf.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CH3d_GuB.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Ccbnls4_.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BG71jM76.js",
"/ran/assets/src_article_typescript_recursion.md.6Kstg-06.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.DQDhXWiz.js",
"/ran/assets/src_ranui_icon_index.md.IUZbUaIZ.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D6S6tIoe.js",
"/ran/assets/src_ranui_select_index.md.Dwqq509g.js",
"/ran/assets/src_article_babel.md.DuDIADQp.js",
"/ran/assets/src_types_模式匹配.md.9011byme.js",
"/ran/assets/src_article_imagemin.md.C_VeCcOQ.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DWgKDi9c.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.Cctmmi1y.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DbaW3tEk.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.BMcHWA5q.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CUjUKsid.lean.js",
"/ran/assets/src_types_类型运算.md.DPWqXKyx.js",
"/ran/assets/src_ranui_popover_index.md.B86SkVnE.js",
"/ran/assets/src_ranui_tab_index.md.CZ_L4-D_.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DmK7alAc.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BiWgbxHn.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.XKlvBOVe.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_typescript_recursion.md.6Kstg-06.js",
"/ran/assets/cn_src_ranui_index.md.BSHFzcC7.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_insert_index.md.DnOFIstz.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.Cctmmi1y.js",
"/ran/assets/src_article_sort_heap_index.md.cMCf7xJQ.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C4LC602q.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_types_模式匹配.md.G7OKzhad.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BIcUFhbA.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_designMode.md.RVGA-inm.lean.js",
"/ran/assets/src_article_bundle.md.DEM-GMBz.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DWgKDi9c.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CAlr4Vlp.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BPv1wzi7.lean.js",
"/ran/assets/src_article_sort_radix_index.md.B4WzLP7J.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_modal_index.md.C7NPT5is.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.Njno-_xZ.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.nu9PdfuU.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_sort_select_index.md.DM_5SuZz.js",
"/ran/assets/src_ranui_preview_index.md.C1UBomfy.lean.js",
"/ran/assets/app.-t-CG-e4.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CURy9IWp.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CbITKzml.js",
"/ran/assets/src_ranuts_file_writeFile.md.DQgihI7g.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.ky4jHpVY.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BlNjAv9V.js",
"/ran/assets/cn_src_ranui_message_index.md.DBRaIFtm.js",
"/ran/assets/cn_src_article_imagemin.md.Ba8CNlYc.lean.js",
"/ran/assets/src_ranuts_utils_task.md.b_7Gbbn2.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranuts_file_readDir.md.ky4jHpVY.js",
"/ran/assets/src_article_sort_shell_index.md.CJ8HQAy9.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.7_Vz63kz.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.D-SI9n6A.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_checkbox_index.md.BEOOqyxr.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.Dc0MrlPx.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.BiUnx9OR.lean.js",
"/ran/assets/src_ranui_progress_index.md.BN0XDmFS.lean.js",
"/ran/assets/src_article_typescript_pattern.md.kdZeCeQf.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.7_Vz63kz.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.xuvnjwuX.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.-1VC4Y6j.lean.js",
"/ran/assets/src_ranui_image_index.md.RwHRS9QM.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BuE1CihU.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.BvXFelik.js",
"/ran/assets/cn_src_article_sort_heap_index.md._t7Mfubv.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.-1VC4Y6j.js",
"/ran/assets/src_ranui_skeleton_index.md.COEOiuEq.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.qf1011-1.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.CvumKBa9.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_radar_index.md.C1hCWSBV.js",
"/ran/assets/src_ranuts_file_writeFile.md.DQgihI7g.js",
"/ran/assets/src_article_typescript_unionType.md.AzLAzA6c.js",
"/ran/assets/src_ranui_message_index.md.C7I1JAwP.lean.js",
"/ran/assets/src_ranui_loading_index.md.soNFh9LB.js",
"/ran/assets/src_ranui_player_index.md.DU3X2RX0.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.La_8F0O4.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_bundler_index.md.DUXyYU8e.js",
"/ran/assets/src_ranui_input_index.md.BAar1RTR.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CQ90yjHM.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_types_TS类型.md.eGcmqCtE.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.CKsltxUE.js",
"/ran/assets/src_ranui_modal_index.md.B-ultrsE.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CjwQ2vfX.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BaOlfAfT.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DBdmTvCX.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D6S6tIoe.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.WJ0Z3cxW.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_typescript_index.md.9rx_ZmbA.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.WJ0Z3cxW.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BaOlfAfT.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_input_index.md.BAar1RTR.js",
"/ran/assets/src_article_sort_merge_index.md.P9D9VbIv.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.xuvnjwuX.lean.js",
"/ran/assets/src_ranuts_index.md.CljD6ebZ.js",
"/ran/assets/src_article_sort_index.md.CZyHH93M.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_sort_radix_index.md.B4WzLP7J.js",
"/ran/assets/cn_src_ranui_progress_index.md.BomW5Agg.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_utils_getCookie.md.4hp1MEPT.js",
"/ran/assets/src_article_designMode.md.T01szVWn.js",
"/ran/assets/src_ranui_button_index.md.C8ZmU7XX.js",
"/ran/assets/cn_src_article_typescript_index.md.DQDhXWiz.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BwbnrWH2.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CqJqM3hu.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.COEOiuEq.js",
"/ran/assets/cn_src_ranui_tab_index.md.FqnYIDas.js",
"/ran/assets/style.DxMSLhj5.css",
"/ran/assets/cn_src_ranui_checkbox_index.md.DmK7alAc.js",
"/ran/assets/src_ranui_tabs_index.md.fCRVPvDG.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.B--N-moD.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/framework.BZEwi-oL.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/index.mdtRk-B9.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/index-CGEx9VOA.kxSojsaB.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/index-DtOAyqJt.D6h6GHgv.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/theme.B_DO20sU.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.LQ4vZ6MR.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_insert_index.md.BG1Lfyhd.lean.js",
"/ran/assets/src_article_sort_index.md.CZyHH93M.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_article_bundle.md.DEM-GMBz.js",
"/ran/assets/src_ranui_tab_index.md.CZ_L4-D_.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.BMcHWA5q.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranui_tabs_index.md.nu9PdfuU.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BYcBnjsp.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CUjUKsid.js",
"/ran/assets/cn_src_ranui_icon_index.md.DgGohpYm.lean.js",
"/ran/assets/src_article_imagemin.md.C_VeCcOQ.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BuE1CihU.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CURy9IWp.js",
"/ran/assets/src_article_sort_shell_index.md.CJ8HQAy9.js",
"/ran/assets/cn_src_types_高级类型.md.5lnoxCC5.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_sort_count_index.md.DhR4zlw6.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BPv1wzi7.js",
"/ran/assets/cn_src_ranui_button_index.md.CvumKBa9.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D0qde2y0.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CqJqM3hu.js",
"/ran/assets/cn_src_article_babel.md.CmF15HcQ.js",
"/ran/assets/src_ranui_checkbox_index.md.BEOOqyxr.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_article_designMode.md.T01szVWn.lean.js",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/hashmap.json",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/designMode.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/functionalProgramming.html",
"/ran/icon.png",
];
const VERSION = "1718521856";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



