const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_72.png",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_7649855.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3f88e5d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b0cd6bd.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c45892d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_6a4c97c.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_94b27bd.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7be51c9.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/index/zh-cn_1626818.pf_index",
"/ran/pagefind/index/zh-cn_89a5478.pf_index",
"/ran/pagefind/index/zh-cn_3c29486.pf_index",
"/ran/pagefind/index/en_cb351b3.pf_index",
"/ran/pagefind/index/en_215eebe.pf_index",
"/ran/pagefind/index/zh-cn_755bf9f.pf_index",
"/ran/pagefind/index/en_5327832.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.en_5a5f8e202b.pf_meta",
"/ran/pagefind/pagefind.zh-cn_acc8d5fe282de.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/cn/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/manifest.json",
"/ran/sw1713063753.js",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Z33b9bLT.js",
"/ran/assets/index.md.Cw_aG1tG.lean.js",
"/ran/assets/cn_index.md.DM_NCeDY.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_imagemin.md.s9hrxZsv.js",
"/ran/assets/src_ranui_select_index.md.EZ6jdtTs.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DopBzXiI.js",
"/ran/assets/src_ranui_message_index.md.CAYOu1-l.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_mode_subscribe.md.BQIZVJWM.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_sort_bucket_index.md.xzsgi8RL.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.B8UI05WH.js",
"/ran/assets/cn_src_article_typescript_recursion.md.C25nfkd7.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B8Y7cToZ.js",
"/ran/assets/cn_src_article_bundle.md.DDgSXIhq.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.D7HCy3Ou.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.RXXUagv8.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DmDjlyoj.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_article_sort_select_index.md.DQLw5MeK.js",
"/ran/assets/src_ranui_player_index.md.DuXbJ7QR.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B8Y7cToZ.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_player_index.md.DuXbJ7QR.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.TadQjito.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bp-0gElb.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_file_appendFile.md.uAxlli2l.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranui_modal_index.md.EEgf4xKk.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BQIZVJWM.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_article_javascript_domLoad.md.BlF4EKY9.js",
"/ran/assets/cn_src_article_sort_count_index.md.lmV_5TCH.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.Ds_WBVWN.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DpQ5vEtc.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CoNPhRd2.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_bucket_index.md.z70VOm-u.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.ZL6ozSKE.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.C_HCxw03.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_sort_index.md.BsmHrOJG.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DfhxASol.js",
"/ran/assets/cn_src_types_TS类型.md.Bdnl4hI7.js",
"/ran/assets/cn_src_ranui_icon_index.md.BFhfTfHJ.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.tcPJJ-qv.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CsFoqiur.js",
"/ran/assets/src_ranuts_utils_ocr.md.sZpLuE9v.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CGR3apqB.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.zlaEUphW.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_checkbox_index.md.Br9Z-3Je.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Cjpj846k.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D3dqUSAH.lean.js",
"/ran/assets/src_ranui_progress_index.md.CvYK_qU_.lean.js",
"/ran/assets/src_article_typescript_index.md.Cc1XxwGn.lean.js",
"/ran/assets/src_article_imagemin.md.zB1QexZ_.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.z70VOm-u.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CGYX5Eps.js",
"/ran/assets/src_ranui_button_index.md.BUv0pStn.js",
"/ran/assets/cn_src_article_typescript_index.md.DlyBA40l.js",
"/ran/assets/src_article_sort_index.md.58aIwInN.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DAn68KBu.lean.js",
"/ran/assets/src_types_模式匹配.md.C9LirEcb.lean.js",
"/ran/assets/src_ranuts_index.md.DlwGTr58.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DxUKyZN3.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.lmV_5TCH.js",
"/ran/assets/src_article_typescript_unionType.md.CnTInUdg.js",
"/ran/assets/cn_src_article_designMode.md.N3F2ykEH.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_typescript_pattern.md.PFACQIxC.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DIxiNh1_.js",
"/ran/assets/src_article_sort_radix_index.md.D58wYCWO.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B_-fePai.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.Cjpj846k.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CR7rRsat.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_typescript_calculate.md.BYks8bZf.js",
"/ran/assets/src_ranuts_file_writeFile.md.g9gFqBBN.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.rgMtz1Fs.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DzDyzkGa.js",
"/ran/assets/cn_src_article_sort_index.md.BsmHrOJG.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranuts_bundler_index.md.BHfPmjW9.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CdDizcpS.lean.js",
"/ran/assets/src_ranui_image_index.md.BCKWJjXZ.lean.js",
"/ran/assets/src_article_typescript_recursion.md.Cjk5N2iM.lean.js",
"/ran/assets/src_ranuts_index.md.DlwGTr58.js",
"/ran/assets/src_ranui_icon_index.md.BDcLyLTT.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DAn68KBu.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.tcPJJ-qv.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.B1XCIkZD.lean.js",
"/ran/assets/src_ranui_input_index.md.BMACy8WP.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranui_index.md.C34grK8J.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranuts_file_readDir.md.Ds_WBVWN.js",
"/ran/assets/src_article_sort_shell_index.md.BjJ6gdhl.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_count_index.md.BXbL37V5.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CGYX5Eps.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_radar_index.md.DhqazFl8.js",
"/ran/assets/src_article_sort_shell_index.md.BjJ6gdhl.js",
"/ran/assets/src_ranuts_file_writeFile.md.g9gFqBBN.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.Don6NFVW.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BkcuCPQl.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_index.md.CipgD2hC.js",
"/ran/assets/src_ranui_tabs_index.md.C18H2DDQ.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DopBzXiI.lean.js",
"/ran/assets/src_ranui_input_index.md.BMACy8WP.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DxUKyZN3.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B_-fePai.js",
"/ran/assets/src_ranuts_bundler_index.md.Bq_nA0Fm.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BKhZ6jIT.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_javascript_domLoad.md.ZL6ozSKE.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CoNPhRd2.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DIxiNh1_.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Bv6rvCJJ.js",
"/ran/assets/cn_src_ranui_radar_index.md.C_yruK1p.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.cTzaUvvQ.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranui_button_index.md.BUv0pStn.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DNQotK7u.lean.js",
"/ran/assets/cn_src_ranui_index.md.1cVkjZSa.js",
"/ran/assets/cn_src_ranui_tab_index.md.BR5zi5Kt.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_types_TS类型.md.CVFu09Bm.lean.js",
"/ran/assets/src_article_functionalProgramming.md.B4tmf72s.lean.js",
"/ran/assets/src_article_sort_quick_index.md.BF-mJv8P.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BIbRPOfJ.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_checkbox_index.md.Bh5cLtoA.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.RXXUagv8.lean.js",
"/ran/assets/src_ranui_index.md.C34grK8J.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.Don6NFVW.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_article_sort_insert_index.md.CdDizcpS.js",
"/ran/assets/src_article_sort_quick_index.md.BF-mJv8P.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.xzsgi8RL.js",
"/ran/assets/cn_src_ranui_icon_index.md.BFhfTfHJ.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_designMode.md.N3F2ykEH.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_file_writeFile.md.C_HCxw03.js",
"/ran/assets/cn_src_article_babel.md.Cdka-Ygp.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DsmURWgK.js",
"/ran/assets/src_article_typescript_index.md.Cc1XxwGn.js",
"/ran/assets/cn_src_article_typescript_index.md.DlyBA40l.lean.js",
"/ran/assets/src_ranui_icon_index.md.BDcLyLTT.js",
"/ran/assets/cn_index.md.DM_NCeDY.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DLEAXQDH.lean.js",
"/ran/assets/index.md.Cw_aG1tG.js",
"/ran/assets/src_ranuts_bundler_index.md.Bq_nA0Fm.lean.js",
"/ran/assets/src_article_imagemin.md.zB1QexZ_.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Cp17y_yn.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BIbRPOfJ.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DzDyzkGa.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.rgMtz1Fs.js",
"/ran/assets/src_ranuts_binaryTree_index.md.D7HCy3Ou.js",
"/ran/assets/src_types_类型运算.md.BCV8SB8c.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.CNdgzD_m.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DsmURWgK.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BHfPmjW9.js",
"/ran/assets/src_ranuts_file_readFile.md.CtWorqVC.js",
"/ran/assets/src_article_sort_bubble_index.md.cTzaUvvQ.js",
"/ran/assets/cn_src_ranui_select_index.md.D4d_vb0R.js",
"/ran/assets/src_article_sort_heap_index.md.63UoN9PQ.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CWp09OhW.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.TUlvp1ZA.js",
"/ran/assets/src_ranui_progress_index.md.CvYK_qU_.js",
"/ran/assets/src_types_高级类型.md.BwAhmsE7.js",
"/ran/assets/src_ranui_select_index.md.EZ6jdtTs.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.CNdgzD_m.js",
"/ran/assets/cn_src_ranui_index.md.1cVkjZSa.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_typescript_reconstruction.md.B1eTcfkY.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.C5_yzoKr.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_designMode.md.DFWdSWr3.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DmDjlyoj.lean.js",
"/ran/assets/cn_src_types_TS类型.md.Bdnl4hI7.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranui_message_index.md.TadQjito.lean.js",
"/ran/assets/src_article_functionalProgramming.md.B4tmf72s.js",
"/ran/assets/src_ranuts_file_readDir.md.C5_yzoKr.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_radar_index.md.C_yruK1p.js",
"/ran/assets/cn_src_ranui_modal_index.md.DlieRLNr.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Z33b9bLT.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.uAxlli2l.lean.js",
"/ran/assets/src_article_designMode.md.DFWdSWr3.lean.js",
"/ran/assets/cn_src_article_babel.md.Cdka-Ygp.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_index.md.58aIwInN.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BJtdXaHa.lean.js",
"/ran/assets/src_ranui_tabs_index.md.C18H2DDQ.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.DlieRLNr.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_popover_index.md.BSh-Wg45.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D6SrvsTw.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.-bRy3K02.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_javascript_domLoad.md.BlF4EKY9.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Br9Z-3Je.js",
"/ran/assets/src_ranui_skeleton_index.md.B8UI05WH.lean.js",
"/ran/assets/src_types_类型运算.md.BCV8SB8c.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CQ5oEK8s.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_typescript_calculate.md.BYks8bZf.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.C1_3GwJl.lean.js",
"/ran/assets/src_article_sort_radix_index.md.D58wYCWO.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D4d_vb0R.lean.js",
"/ran/assets/src_article_babel.md.DodbE9T_.js",
"/ran/assets/src_ranuts_utils_filterObj.md.CN9eT0rl.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.CtU7Lw4T.js",
"/ran/assets/cn_src_types_类型运算.md.DNQotK7u.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Cp17y_yn.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranui_popover_index.md.DWVG3aD3.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranuts_file_watchFile.md.MuahUSGO.lean.js",
"/ran/assets/src_ranui_radar_index.md.DhqazFl8.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_utils_task.md.DyEc66qm.js",
"/ran/assets/src_article_sort_heap_index.md.63UoN9PQ.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.sZpLuE9v.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BkcuCPQl.js",
"/ran/assets/cn_src_ranuts_index.md.CipgD2hC.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BKhZ6jIT.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CWp09OhW.js",
"/ran/assets/src_types_模式匹配.md.C9LirEcb.js",
"/ran/assets/src_ranui_tab_index.md.DdMWzpzz.js",
"/ran/assets/cn_src_ranui_tab_index.md.BR5zi5Kt.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bco2OXfH.lean.js",
"/ran/assets/src_article_sort_count_index.md.BXbL37V5.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_types_TS类型.md.CVFu09Bm.js",
"/ran/assets/src_article_typescript_reconstruction.md.B1eTcfkY.js",
"/ran/assets/src_article_bundle.md.m92HvVLS.lean.js",
"/ran/assets/cn_src_article_bundle.md.DDgSXIhq.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Bh5cLtoA.js",
"/ran/assets/cn_src_ranui_popover_index.md.BSh-Wg45.js",
"/ran/assets/src_ranui_image_index.md.BCKWJjXZ.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DeNtRBwq.lean.js",
"/ran/assets/src_article_typescript_unionType.md.CnTInUdg.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CGapK9Af.lean.js",
"/ran/assets/src_article_sort_select_index.md.DQLw5MeK.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D3dqUSAH.js",
"/ran/assets/src_ranuts_file_watchFile.md.MuahUSGO.js",
"/ran/assets/src_ranui_preview_index.md.BEhqWt0B.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DeNtRBwq.js",
"/ran/assets/src_article_typescript_recursion.md.Cjk5N2iM.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_tab_index.md.DdMWzpzz.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.TUlvp1ZA.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DyEc66qm.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.-bRy3K02.js",
"/ran/assets/src_article_bundle.md.m92HvVLS.js",
"/ran/assets/cn_src_article_typescript_pattern.md.PFACQIxC.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CGR3apqB.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_types_高级类型.md.DLEAXQDH.js",
"/ran/assets/src_ranui_popover_index.md.DWVG3aD3.lean.js",
"/ran/assets/src_ranui_message_index.md.CAYOu1-l.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CGapK9Af.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/index-BTiPI7ou.D7wPIxCW.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/framework.uTpxwq_I.js",
"/ran/assets/chunks/theme.BW9dbD2F.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/zh-CN.CbUipQUT.js",
"/ran/assets/chunks/pdf-B2a6ll8f.lVr-YjCg.js",
"/ran/assets/chunks/index-CZlEoE62.BH9TDfQd.js",
"/ran/assets/chunks/index.CV-dxUKH.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/en.B393XAL4.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DfhxASol.lean.js",
"/ran/assets/src_ranui_preview_index.md.BEhqWt0B.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CR7rRsat.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Bp-0gElb.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.BEfAm6sW.js",
"/ran/assets/src_ranuts_file_fileInfo.md.C1_3GwJl.js",
"/ran/assets/cn_src_ranui_input_index.md.BEfAm6sW.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CQ5oEK8s.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_file_readFile.md.CtWorqVC.lean.js",
"/ran/assets/src_ranui_modal_index.md.EEgf4xKk.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D6SrvsTw.js",
"/ran/assets/cn_src_article_sort_select_index.md.zlaEUphW.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.C25nfkd7.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BUzMY7he.js",
"/ran/assets/app.BVgp8UL1.js",
"/ran/assets/src_types_高级类型.md.BwAhmsE7.lean.js",
"/ran/assets/src_article_babel.md.DodbE9T_.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BUzMY7he.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CsFoqiur.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_sort_insert_index.md.DpQ5vEtc.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_types_模式匹配.md.CtU7Lw4T.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.B1XCIkZD.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bco2OXfH.js",
"/ran/assets/src_ranuts_utils_filterObj.md.CN9eT0rl.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BJtdXaHa.js",
"/ran/assets/src_ranuts_utils_task.md.Bv6rvCJJ.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/style.C1z-TwTH.css",
"/ran/assets/cn_src_article_imagemin.md.s9hrxZsv.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/screenshots_2560x1440.jpg",
"/ran/home.svg",
"/ran/icon.png",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/icon_48.png",
];
const VERSION = "1713063753";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
    // google 上报不需要缓存
    'google',
    // 插件请求不用缓存
    'chrome-extension',
    // 百度的请求不用缓存
    'baidu.com',
    'blob:',
    'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
    GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
    SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
    INSTALL: 'install',
    FETCH: 'fetch',
    ACTIVATE: 'activate',
    MESSAGE: 'message',
    SYNC: 'sync',
    PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url } = request
    const { status } = fetchedResponse
    // 只缓存状态码为 200 的请求
    if (status !== RESPONSE_STATUS.SUCCESS) return
    if (filterRequest(request)) {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service worker update cache error:', error, request)
        })
    }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
    const { url, method } = request
    return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const { url } = request
        const responseFromCache = await caches.match(url);
        // 如果缓存中有，返回已经缓存的资源
        if (responseFromCache) return responseFromCache
        // 如果缓存中没有，就从网络中请求，并更新到缓存中
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        // 当缓存中也没有，请求也不可用的时候
        // 始终需要一个一个响应
        // 甚至可以设置回落的请求，在catch中继续发起请求
        console.log('service worker cacheFirst error:', error, request)
        return new Response("Network error happened", {
            status: 408,
            headers: { "Content-Type": "text/plain" },
        });
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('service worker deleteCache error:', error, key)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
    }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
            // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
            // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service worker fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service worker self installed error:', url, error);
                })
            )
        })
    );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
    // 拦截请求
    try {
        const { request } = event
        // 忽略 IGNORE_REQUEST_LIST 中的请求，不进行拦截
        if (filterRequest(request)) {
            const responseFromServer = cacheFirst(request)
            if (responseFromServer?.clone) {
                event.respondWith(responseFromServer);
            }
        }
    } catch (error) {
        console.log('service worker self fetch error:', error, event)
    }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
    event.waitUntil(deleteOldCaches());
});



