const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/index.html",
"/ran/icon_192.png",
"/ran/cn/index.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/designMode.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/babel.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/favicon.ico",
"/ran/manifest.json",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/example.m3u8",
"/ran/home.svg",
"/ran/hashmap.json",
"/ran/icon_144.png",
"/ran/assets/src_ranuts_utils_formatJson.md.cx0-ZGCF.js",
"/ran/assets/cn_src_types_高级类型.md.Dl4rhXCK.lean.js",
"/ran/assets/src_types_TS类型.md.EYbuADCh.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_note_centos.md.TGii9ZIr.js",
"/ran/assets/src_ranuts_index.md.Cxa_cgfm.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.achO3I-b.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BUhnI0l8.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.nZaAZwqp.js",
"/ran/assets/cn_src_article_visual.md.cjyYzAy6.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_typescript_calculate.md.DJYaHd4V.js",
"/ran/assets/cn_src_article_docPreview.md.BkDQBks4.js",
"/ran/assets/src_article_sort_heap_index.md.BuJv5z7m.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranuts_binaryTree_index.md.DCOpbhwH.js",
"/ran/assets/src_ranui_modal_index.md.Dvt65Jk_.lean.js",
"/ran/assets/src_ranui_progress_index.md.C3S8t2me.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranui_index.md.s-_Z4OoP.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_article_typescript_recursion.md.CGH4Ppn4.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_types_高级类型.md.C0p0zCdD.js",
"/ran/assets/cn_src_ranui_math_index.md.DkHbp39v.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.C2yYzEu9.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DjheQOcu.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_tabs_index.md.gRF7nVPW.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_babel.md.BLkbuATi.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.Ch6qDf84.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DmzFiqHp.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.C30_84dO.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_quick_index.md.B-riHh6Z.js",
"/ran/assets/cn_src_article_docPreview.md.BkDQBks4.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.B2pkjFs9.lean.js",
"/ran/assets/src_ranui_message_index.md.e14yc4Hx.js",
"/ran/assets/src_ranui_popover_index.md.CvToWTL-.js",
"/ran/assets/src_ranuts_bundler_index.md.DsmJnUjg.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BiogW0qg.js",
"/ran/assets/src_ranui_skeleton_index.md.9YMAJiL0.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BvAUhQB4.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.achO3I-b.lean.js",
"/ran/assets/src_ranui_input_index.md.Cr4mmKcB.lean.js",
"/ran/assets/index.md.B8KRjS7P.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.2ltUfS1l.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_article_sort_bucket_index.md.CzTFmbcp.js",
"/ran/assets/src_ranui_math_index.md.Ce-8TrSi.js",
"/ran/assets/src_ranuts_file_readFile.md.HcZvIcK4.lean.js",
"/ran/assets/src_ranui_popover_index.md.CvToWTL-.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.B7sQmxEv.js",
"/ran/assets/cn_src_ranui_select_index.md.BGQJKq9-.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.UMWyW1It.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.2ltUfS1l.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_math_index.md.Ce-8TrSi.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_imagemin.md.CQ0uiuYY.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.D-1lTDqI.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.UMWyW1It.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.fbx8aETr.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_sort_bubble_index.md.CjWZpQ3p.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_bundle.md.CWvCd7H5.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.DogT3jQl.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DnkVQB6S.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DHfxC0E2.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BNK0IW5q.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Bn5IoQd2.lean.js",
"/ran/assets/src_article_typescript_unionType.md.DumucMQs.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CMtOhGJG.js",
"/ran/assets/src_ranuts_utils_getCookie.md.DbyRX1UU.lean.js",
"/ran/assets/src_ranui_tab_index.md.BN8Vf7Eg.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BOjGrVlR.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_ranui_icon_index.md.f-o96QkA.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CKRth4D8.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BgGSRd5H.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranui_preview_index.md.CbUO5bs8.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_sort_shell_index.md.BDA7MarL.js",
"/ran/assets/cn_src_types_类型运算.md.BgGSRd5H.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_index.md.Cxa_cgfm.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.cx0-ZGCF.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CGLyKCgl.js",
"/ran/assets/cn_src_note_centos.md.TGii9ZIr.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.HcZvIcK4.js",
"/ran/assets/cn_src_ranuts_utils_task.md.lDk3rsvx.lean.js",
"/ran/assets/src_article_designMode.md.BwrfQdUT.js",
"/ran/assets/cn_src_article_sort_count_index.md.CK9KanAW.js",
"/ran/assets/src_ranuts_file_appendFile.md.TCGdeAO4.lean.js",
"/ran/assets/src_article_babel.md.CPlenUd-.js",
"/ran/assets/src_ranuts_utils_filterObj.md.HbKEUR_B.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_article_sort_bucket_index.md.B6QGR00t.lean.js",
"/ran/assets/src_article_bundle.md.3cA7usJB.lean.js",
"/ran/assets/src_article_functionalProgramming.md.cBvp-DHy.js",
"/ran/assets/src_article_sort_insert_index.md.BPXiJ6-4.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_note_docker.md.DidNCJLo.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_sort_count_index.md.DVFuExI4.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_article_sort_shell_index.md.BDA7MarL.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.HbKEUR_B.js",
"/ran/assets/cn_src_article_typescript_index.md.BdZk769B.js",
"/ran/assets/cn_src_ranui_button_index.md.DH1vlFsC.lean.js",
"/ran/assets/src_article_sort_index.md.CqXVwy2e.js",
"/ran/assets/src_article_sort_count_index.md.DVFuExI4.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Cs5ClDve.lean.js",
"/ran/assets/cn_src_ranui_index.md.jrGtUSHu.lean.js",
"/ran/assets/src_ranui_image_index.md.CxnU8ykT.lean.js",
"/ran/assets/src_article_typescript_pattern.md.B0A5r8tH.lean.js",
"/ran/assets/src_types_类型运算.md.DqViYjAk.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_types_模式匹配.md.B9HmahCH.js",
"/ran/assets/src_article_sort_radix_index.md.Bxp20LYd.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DjheQOcu.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BiogW0qg.lean.js",
"/ran/assets/cn_src_article_video.md.CRHKrKK3.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CvxawEcz.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DHxzRj0g.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DH1vlFsC.js",
"/ran/assets/cn_src_ranui_image_index.md.C30_84dO.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_article_typescript_reconstruction.md.C2yYzEu9.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.DquVYGDZ.js",
"/ran/assets/cn_src_types_TS类型.md.BbQTLMVb.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BfOjPWLv.js",
"/ran/assets/cn_src_types_模式匹配.md.B9vUzeek.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_radix_index.md.Qzh7vc3X.js",
"/ran/assets/cn_src_ranui_preview_index.md.CbUO5bs8.js",
"/ran/assets/cn_src_article_designMode.md.DrN54Dt2.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.DCOpbhwH.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Kiv9VNl6.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_article_imagemin.md.CQ0uiuYY.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CvxawEcz.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_sort_select_index.md.yFP-mlLz.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Ce_GADxg.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranuts_file_writeFile.md.55cwGCj9.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DvxfXoFD.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.p-Jr-4Et.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.Zm0qjeOl.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.B4Yk8rxI.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Ce_GADxg.lean.js",
"/ran/assets/index.md.B8KRjS7P.lean.js",
"/ran/assets/cn_src_article_designMode.md.DrN54Dt2.js",
"/ran/assets/cn_index.md.9XCI8sav.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranuts_file_readDir.md.CygkArwC.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.Kiv9VNl6.js",
"/ran/assets/cn_src_article_video.md.CRHKrKK3.js",
"/ran/assets/src_ranui_select_index.md.C9LlZZfq.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BfOjPWLv.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BGrxNEge.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_astParse_tokenizer.md.CBILlgU8.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B7-_k17t.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DqbIv1zt.js",
"/ran/assets/cn_src_ranui_radar_index.md.qfgvGyEW.lean.js",
"/ran/assets/src_ranui_icon_index.md.DcBJ6tRN.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_utils_task.md.Bc55yPrX.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Cs5ClDve.js",
"/ran/assets/src_ranui_loading_index.md.Cq-CyfeN.lean.js",
"/ran/assets/src_article_sort_index.md.CqXVwy2e.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.lDk3rsvx.js",
"/ran/assets/src_article_sort_select_index.md.yFP-mlLz.js",
"/ran/assets/src_article_sort_insert_index.md.BPXiJ6-4.lean.js",
"/ran/assets/cn_src_note_docker.md.DidNCJLo.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranuts_index.md.C5B7rtek.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.3SmC2ft6.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_article_functionalProgramming.md.cBvp-DHy.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_sort_index.md.BuQKQf8Z.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_radar_index.md.CWY8H-Q7.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.B9vUzeek.js",
"/ran/assets/src_article_typescript_recursion.md.CGH4Ppn4.js",
"/ran/assets/cn_index.md.9XCI8sav.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranui_player_index.md.BGrxNEge.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.BGQJKq9-.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D3pvT5wW.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_tab_index.md.DHfxC0E2.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.D3pvT5wW.js",
"/ran/assets/src_ranuts_file_readDir.md.wHnGEq6w.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.UyTMA2xr.lean.js",
"/ran/assets/src_article_designMode.md.BwrfQdUT.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.UZfK_fKG.js",
"/ran/assets/src_article_typescript_pattern.md.B0A5r8tH.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DSI8Bqgy.lean.js",
"/ran/assets/cn_src_types_高级类型.md.Dl4rhXCK.js",
"/ran/assets/cn_src_ranui_index.md.jrGtUSHu.js",
"/ran/assets/src_ranui_player_index.md.B3GUm3Na.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DzKymR2L.js",
"/ran/assets/src_types_类型运算.md.DqViYjAk.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CGLyKCgl.lean.js",
"/ran/assets/src_ranui_player_index.md.B3GUm3Na.lean.js",
"/ran/assets/app.BdCz2uAc.js",
"/ran/assets/src_article_babel.md.CPlenUd-.lean.js",
"/ran/assets/src_ranui_button_index.md.zokLvbs1.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DmhtStbs.lean.js",
"/ran/assets/cn_src_ranuts_index.md.C5B7rtek.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.qfgvGyEW.js",
"/ran/assets/src_ranui_skeleton_index.md.9YMAJiL0.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.UZfK_fKG.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DsmJnUjg.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.B2VSZS0N.js",
"/ran/assets/src_ranui_icon_index.md.DcBJ6tRN.js",
"/ran/assets/src_types_TS类型.md.EYbuADCh.lean.js",
"/ran/assets/src_article_typescript_unionType.md.DumucMQs.js",
"/ran/assets/cn_src_ranui_popover_index.md.B7sQmxEv.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.D7ttQNv6.js",
"/ran/assets/src_ranui_tabs_index.md.gRF7nVPW.js",
"/ran/assets/cn_src_article_sort_index.md.BuQKQf8Z.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BmLA1YTa.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CbUr_JRu.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.nZaAZwqp.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BNK0IW5q.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_article_sort_merge_index.md.D7ttQNv6.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DzKymR2L.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.ClHQGpGi.js",
"/ran/assets/src_ranuts_utils_ocr.md.Bzlrxs3I.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_preview_index.md.B0r84xYd.lean.js",
"/ran/assets/cn_src_article_visual.md.cjyYzAy6.js",
"/ran/assets/src_ranui_input_index.md.Cr4mmKcB.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/index-Ba501-HG.B2dmFVYQ.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/index-Co9E57uv.COGQj8Hy.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/framework.BYE6xntm.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/theme.C4Wqe4YE.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.C3U38o45.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DqjXTuVA.js",
"/ran/assets/chunks/index.h_46bJa8.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/pwa-install.es.DI7OvJx5.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.fbx8aETr.lean.js",
"/ran/assets/style.0WEJ_Nz4.css",
"/ran/assets/cn_src_ranuts_bundler_index.md.DUTKmd_D.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranui_checkbox_index.md.DnkVQB6S.js",
"/ran/assets/src_ranui_select_index.md.C9LlZZfq.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.D-1lTDqI.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.UyTMA2xr.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Qzh7vc3X.lean.js",
"/ran/assets/src_ranui_image_index.md.CxnU8ykT.js",
"/ran/assets/src_ranui_index.md.s-_Z4OoP.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranui_button_index.md.zokLvbs1.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.Zm0qjeOl.js",
"/ran/assets/src_ranui_preview_index.md.B0r84xYd.js",
"/ran/assets/src_article_sort_heap_index.md.BuJv5z7m.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_sort_radix_index.md.Bxp20LYd.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranuts_file_writeFile.md.55cwGCj9.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.TCGdeAO4.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_tab_index.md.BN8Vf7Eg.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranuts_file_writeFile.md.SSubiGJL.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BUhnI0l8.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DUTKmd_D.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DmzFiqHp.js",
"/ran/assets/src_ranuts_utils_ocr.md.Bzlrxs3I.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.DSI8Bqgy.js",
"/ran/assets/src_article_imagemin.md.r9NVfIkd.lean.js",
"/ran/assets/src_article_imagemin.md.r9NVfIkd.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.ARSB3tXT.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.3SmC2ft6.js",
"/ran/assets/src_article_typescript_calculate.md.DJYaHd4V.lean.js",
"/ran/assets/src_article_sort_merge_index.md.BE8kQqy1.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DHxzRj0g.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranui_message_index.md.e14yc4Hx.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_sort_merge_index.md.BE8kQqy1.lean.js",
"/ran/assets/cn_src_article_bundle.md.CWvCd7H5.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_article_sort_quick_index.md.BOjGrVlR.js",
"/ran/assets/src_article_sort_bubble_index.md.CjWZpQ3p.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.CK9KanAW.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_modal_index.md.Ch6qDf84.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.p-Jr-4Et.js",
"/ran/assets/cn_src_ranui_loading_index.md.DogT3jQl.js",
"/ran/assets/cn_src_types_TS类型.md.BbQTLMVb.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CzTFmbcp.lean.js",
"/ran/assets/src_ranui_radar_index.md.CWY8H-Q7.js",
"/ran/assets/src_ranuts_utils_getCookie.md.DbyRX1UU.js",
"/ran/assets/cn_src_ranui_icon_index.md.f-o96QkA.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B7-_k17t.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.ClHQGpGi.lean.js",
"/ran/assets/src_article_bundle.md.3cA7usJB.js",
"/ran/assets/cn_src_note_ubuntu.md.DmhtStbs.js",
"/ran/assets/cn_src_ranui_math_index.md.DkHbp39v.js",
"/ran/assets/src_ranui_progress_index.md.C3S8t2me.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_utils_task.md.Bc55yPrX.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.DquVYGDZ.lean.js",
"/ran/assets/src_article_typescript_index.md.ZEx2s50B.js",
"/ran/assets/src_article_astParse_tokenizer.md.CBILlgU8.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.B4Yk8rxI.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_sort_quick_index.md.B-riHh6Z.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.CygkArwC.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BmLA1YTa.js",
"/ran/assets/cn_src_article_babel.md.BLkbuATi.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BvAUhQB4.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B6QGR00t.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CbUr_JRu.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranui_modal_index.md.Dvt65Jk_.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CKRth4D8.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DvxfXoFD.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_systemDesign.md.B2pkjFs9.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranuts_mode_subscribe.md.DqbIv1zt.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranui_loading_index.md.Cq-CyfeN.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Bn5IoQd2.js",
"/ran/assets/src_article_typescript_index.md.ZEx2s50B.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.wHnGEq6w.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_javascript_domLoad.md.B2VSZS0N.lean.js",
"/ran/assets/src_types_高级类型.md.C0p0zCdD.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_article_typescript_index.md.BdZk769B.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.SSubiGJL.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.ARSB3tXT.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CMtOhGJG.lean.js",
"/ran/assets/src_types_模式匹配.md.B9HmahCH.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/icon.png",
"/ran/pagefind/pagefind.zh-cn_f598755496cab.pf_meta",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.en_648a50c9d6.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/index/zh-cn_bb272b7.pf_index",
"/ran/pagefind/index/zh-cn_5d1d145.pf_index",
"/ran/pagefind/index/zh-cn_16af6ef.pf_index",
"/ran/pagefind/index/zh-cn_181dded.pf_index",
"/ran/pagefind/index/en_318ec34.pf_index",
"/ran/pagefind/index/en_396d347.pf_index",
"/ran/pagefind/index/en_58c6189.pf_index",
"/ran/pagefind/index/zh-cn_4f900ab.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3fb29d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3e43b1f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a1e1243.pf_fragment",
"/ran/pagefind/fragment/en_45b0a69.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_98546ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ef213d.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c82f3b2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_87504f6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f83f580.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20bbef4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_58279de.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51dafe6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_44fa7df.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_c24a847.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7355cce.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d1b782.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f4f874.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8df5615.pf_fragment",
"/ran/pagefind/fragment/en_ee118c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95fa787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7edffe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1f33c04.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e64f93e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfc7c79.pf_fragment",
"/ran/pagefind/fragment/en_9573fab.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bb9206.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2e89f3.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d32fcee.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e88bc3f.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5df12ef.pf_fragment",
"/ran/pagefind/fragment/en_b0cf238.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f9c4333.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3de2e5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bc7914.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_32113cf.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7d7b75a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e41081e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac92f78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6cc6a8.pf_fragment",
"/ran/pagefind/fragment/en_cb594e2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9968bf4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5919.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a3cd5f.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_715eacf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/en_c485c6f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_677ff04.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1ec4ddb.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f379427.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5042f4c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ca356d.pf_fragment",
"/ran/pagefind/fragment/en_2ac4367.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a66a688.pf_fragment",
"/ran/pagefind/fragment/zh-cn_67d6c7a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ad6344.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e347438.pf_fragment",
"/ran/pagefind/fragment/en_a4a4e1c.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66f42e8.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_75a264c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59bdbd3.pf_fragment",
"/ran/pagefind/fragment/en_33bec34.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f7dcce8.pf_fragment",
"/ran/pagefind/fragment/en_706f2f9.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_489c27d.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/en_58e1be6.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_539d75f.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_a79eb77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5190b59.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6ea83e5.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_58cb4c9.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_a8a649f.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c1151c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7e8750b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4595ab.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7b2564.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_50313a9.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f09c929.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d98338a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bab657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_af6cbe1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/sw1728828383.js",
"/ran/404.html",
"/ran/icon_72.png",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_96.png",
"/ran/screenshots_748x1340.jpg",
"/ran/icon_168.png",
"/ran/icon_48.png",
"/ran/screenshots_2560x1440.jpg",
];
const VERSION = "1728828383";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



