const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/favicon.ico",
"/ran/logo.png",
"/ran/sw1751086117.js",
"/ran/vp-icons.css",
"/ran/manifest.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/icon.png",
"/ran/icon_48.png",
"/ran/icon_168.png",
"/ran/src/article/babel.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/icon_144.png",
"/ran/screenshots_748x1340.jpg",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/example.m3u8",
"/ran/icon_72.png",
"/ran/hashmap.json",
"/ran/404.html",
"/ran/index.html",
"/ran/assets/src_article_sort_shell_index.md.BoFcpDx9.lean.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/src_article_sort_bubble_index.md.CfWwmUQU.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.FfSAag0K.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CP7dT0rl.js",
"/ran/assets/src_article_sort_radix_index.md.BMXDc2Xo.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DVXDttfj.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_file_append_file.md.Cc4o1Q05.js",
"/ran/assets/src_article_typescript_recursion.md.B3-KdCwH.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BKHU5Noz.lean.js",
"/ran/assets/cn_src_types_TS类型.md.7tgg_XKD.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_icon_index.md.BopSKN45.js",
"/ran/assets/cn_src_ranui_input_index.md.GO5_qNe_.js",
"/ran/assets/src_ranui_skeleton_index.md.DT7kqLxn.js",
"/ran/assets/cn_src_article_system_design.md.D2-zXXgZ.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CERrFPpm.js",
"/ran/assets/src_article_javascript_dom_load.md.CM7gIbJr.lean.js",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/src_ranui_popover_index.md.CnTm6CMs.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_design_mode.md.CY1UoHdY.lean.js",
"/ran/assets/cn_src_ranuts_index.md.DCD_A_tC.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DAGz9rPJ.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BACmMvx8.js",
"/ran/assets/src_article_typescript_reconstruction.md.CRRwVTU8.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_typescript_index.md.Gfzm41pX.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.BsCibQMp.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BKHU5Noz.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.0tL8rygE.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_article_sort_count_index.md.CWQ5RpeZ.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BZdlDoiG.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BZdlDoiG.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranuts_bundler_index.md.BOE6MvmR.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.mZBXkSS8.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CgDgfoZD.lean.js",
"/ran/assets/src_ranui_select_index.md.DVdWss7M.js",
"/ran/assets/src_article_typescript_calculate.md.DuBZISgK.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BACmMvx8.lean.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/pdf-iO-7tssN.BW_KHC9N.js",
"/ran/assets/chunks/index.CBVxPXTV.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CQ12jEiZ.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/theme.CDMBEv2-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/pwa-install.es.DLByzKTx.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/framework.CQmC_4em.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/@localSearchIndexroot.p7DcGEUk.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/VPLocalSearchBox.BV75saTV.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/@localSearchIndexcn.CZRyrgmb.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Cs1tTOdw.lean.js",
"/ran/assets/src_ranui_icon_index.md.CXOM9KfE.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.RlMqzThp.js",
"/ran/assets/app.ClTIHJtI.js",
"/ran/assets/src_ranui_player_index.md.B-Hi9v6c.js",
"/ran/assets/src_article_typescript_union_type.md.Cm_KldsZ.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DIDhBdXU.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BrigeOrM.js",
"/ran/assets/src_ranui_preview_index.md.Ddvl9fZN.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.COfy9_pV.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.BiZp3T6b.js",
"/ran/assets/src_ranuts_utils_task.md.Nc3BEl7f.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_imagemin.md.2g38YyP2.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_design_mode.md.CY1UoHdY.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.r-9rpaXe.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BJN640rT.js",
"/ran/assets/cn_src_article_typescript_recursion.md.YHD4wnN8.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.TQcVaccv.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CsTcshs0.js",
"/ran/assets/cn_src_article_sort_count_index.md.D0s2Z-Is.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CcMSDeFJ.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CX6YOcIU.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DS28L8fg.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.VUBQiG5F.js",
"/ran/assets/src_ranuts_file_read_dir.md.CqVqt57k.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_index.md.BjvqgIaD.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_article_imagemin.md.DZzI6vdO.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BVnJ3TvY.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_article_design_mode.md.CONG7gdL.lean.js",
"/ran/assets/cn_src_article_babel.md.Cw8GXYNz.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.JFDl-h5J.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/src_types_模式匹配.md.XwWR8ybV.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.Bezgh6h_.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.COfy9_pV.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Cs1tTOdw.js",
"/ran/assets/cn_src_blockchain_index.md.Dlna71Fu.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DsLogMwX.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.BopSKN45.lean.js",
"/ran/assets/src_ranui_math_index.md.C8NDIkzp.lean.js",
"/ran/assets/src_article_typescript_pattern.md.CI86dK0y.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CERrFPpm.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_note_centos.md.DEN2eTG8.js",
"/ran/assets/src_article_sort_quick_index.md.DYXxgUKM.lean.js",
"/ran/assets/src_types_模式匹配.md.XwWR8ybV.js",
"/ran/assets/cn_index.md.BjvqgIaD.lean.js",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/src_ranui_message_index.md.Cc20yRvA.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_math_index.md.C8NDIkzp.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/src_article_typescript_union_type.md.Cm_KldsZ.lean.js",
"/ran/assets/src_ranui_message_index.md.Cc20yRvA.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_file_append_file.md.DQHOL6yn.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BzPmIZ02.js",
"/ran/assets/src_article_sort_count_index.md.CWQ5RpeZ.js",
"/ran/assets/src_article_typescript_calculate.md.DuBZISgK.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranui_loading_index.md.D7NbucHc.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_ranui_progress_index.md.FfSAag0K.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_file_watch_file.md.feLfL7j5.js",
"/ran/assets/cn_src_article_babel.md.Cw8GXYNz.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.C8RTW9ia.js",
"/ran/assets/src_ranui_skeleton_index.md.DT7kqLxn.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.D1feDl9x.lean.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/style.BYJ92txg.css",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.06Pw6O-2.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Np5m4eBy.js",
"/ran/assets/src_ranuts_utils_format_json.md.nci1r_6k.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/cn_src_types_模式匹配.md.C2akPDm0.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.EMdr708K.lean.js",
"/ran/assets/cn_src_ranuts_index.md.DCD_A_tC.js",
"/ran/assets/cn_src_ranui_modal_index.md.DGKWqjcP.js",
"/ran/assets/src_ranui_button_index.md.DSFqJLMp.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Cwv58txT.lean.js",
"/ran/assets/cn_src_article_system_design.md.D2-zXXgZ.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CgDgfoZD.js",
"/ran/assets/cn_src_ranui_message_index.md.Bcr0j5vE.js",
"/ran/assets/src_article_sort_insert_index.md.pkK6Qmge.js",
"/ran/assets/src_article_sort_select_index.md.DF8vxmbo.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/cn_src_article_video.md.Cdbgc561.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CmWRb8XV.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DM2lM5so.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DQ-vtNPF.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/src_ranui_popover_index.md.CnTm6CMs.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranui_radar_index.md.BNL8G5jK.js",
"/ran/assets/src_article_sort_quick_index.md.DYXxgUKM.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_types_类型运算.md.DdZMi0yM.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DIDhBdXU.lean.js",
"/ran/assets/src_types_类型运算.md.CpucMdkR.js",
"/ran/assets/src_article_sort_index.md.D9WGd7WQ.js",
"/ran/assets/src_ranui_tab_index.md.Bh0b5hnh.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_typescript_pattern.md.CI86dK0y.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_ranuts_file_write_file.md.0tL8rygE.lean.js",
"/ran/assets/src_ranui_image_index.md.DSg1jJnV.js",
"/ran/assets/cn_src_blockchain_web3.md.CGVVAi4S.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.yJMWaZMt.js",
"/ran/assets/cn_src_article_functional_programming.md.D7gXQ1Uy.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.06Pw6O-2.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BOE6MvmR.js",
"/ran/assets/cn_src_ranui_tab_index.md.BQlY5ulf.lean.js",
"/ran/assets/cn_src_note_centos.md.DEN2eTG8.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Csb-fMmb.js",
"/ran/assets/src_article_functional_programming.md.CP6gbaIJ.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CspxdHj7.lean.js",
"/ran/assets/src_ranuts_index.md.CvORv2lq.js",
"/ran/assets/cn_src_ranui_select_index.md.CcMSDeFJ.lean.js",
"/ran/assets/src_types_高级类型.md.DEWxMOj8.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DQ-vtNPF.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BE2FfxYV.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranuts_file_file_info.md.BsCibQMp.js",
"/ran/assets/cn_src_ranui_input_index.md.GO5_qNe_.lean.js",
"/ran/assets/src_article_bundle.md.vcLnKq8G.js",
"/ran/assets/cn_src_article_sort_index.md.BzwdULHH.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.YHD4wnN8.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.pJr-RfGs.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/cn_src_ranui_popover_index.md.CsTcshs0.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranuts_utils_task.md.H_Aw-wep.lean.js",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.LnVIiPYe.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DVXDttfj.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.A_ALDO69.lean.js",
"/ran/assets/src_ranui_index.md.DpUVsZh8.js",
"/ran/assets/src_article_typescript_recursion.md.B3-KdCwH.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BUfp0qgA.lean.js",
"/ran/assets/src_article_imagemin.md.2g38YyP2.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.CcSS1b3f.js",
"/ran/assets/cn_src_ranui_image_index.md.BJxozRBM.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/cn_src_article_sort_index.md.BzwdULHH.js",
"/ran/assets/src_ranuts_utils_ocr.md.BpxnV-7W.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BVnJ3TvY.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranui_loading_index.md.DvKv1R0N.js",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranui_radar_index.md.mZBXkSS8.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_types_TS类型.md.CzBbG3O9.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.FsTGawbE.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_file_write_file.md.hH2v_ofG.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_doc_preview.md.Cs_4mddf.lean.js",
"/ran/assets/cn_src_blockchain_web3.md.CGVVAi4S.js",
"/ran/assets/src_ranui_icon_index.md.CXOM9KfE.js",
"/ran/assets/src_ranui_radar_index.md.BNL8G5jK.lean.js",
"/ran/assets/src_ranui_player_index.md.B-Hi9v6c.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranui_index.md.CSKZ6Yr5.js",
"/ran/assets/cn_src_ranui_preview_index.md.yJMWaZMt.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CmWRb8XV.js",
"/ran/assets/cn_src_ranui_tabs_index.md.LnVIiPYe.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.BivBpgvg.lean.js",
"/ran/assets/cn_src_article_visual.md.DklWmhQS.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.BQlY5ulf.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CX6YOcIU.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_types_高级类型.md.DEWxMOj8.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.4CZZsiGe.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Csb-fMmb.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_types_高级类型.md.BL0HyffN.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.pJr-RfGs.lean.js",
"/ran/assets/src_ranui_image_index.md.DSg1jJnV.lean.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/src_article_typescript_reconstruction.md.CRRwVTU8.lean.js",
"/ran/assets/src_ranui_progress_index.md.DGAR8vov.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_babel.md.ClM0GfFQ.js",
"/ran/assets/src_article_sort_select_index.md.DF8vxmbo.lean.js",
"/ran/assets/cn_src_article_visual.md.DklWmhQS.js",
"/ran/assets/cn_src_types_模式匹配.md.C2akPDm0.js",
"/ran/assets/src_ranuts_index.md.CvORv2lq.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CspxdHj7.js",
"/ran/assets/src_article_sort_insert_index.md.pkK6Qmge.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DAGz9rPJ.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranui_preview_index.md.Ddvl9fZN.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Bcr0j5vE.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_sort_select_index.md.CHWFtL06.lean.js",
"/ran/assets/src_ranui_input_index.md.BrjQADy7.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.FsTGawbE.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_sort_bucket_index.md.BlqoFRKt.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BiZp3T6b.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BE2FfxYV.js",
"/ran/assets/src_article_typescript_index.md.Gfzm41pX.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.r-9rpaXe.lean.js",
"/ran/assets/cn_src_blockchain_index.md.Dlna71Fu.js",
"/ran/assets/src_ranuts_file_write_file.md.hH2v_ofG.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.4CZZsiGe.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_ranui_index.md.CSKZ6Yr5.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BL0HyffN.js",
"/ran/assets/src_types_TS类型.md.CzBbG3O9.js",
"/ran/assets/src_article_babel.md.ClM0GfFQ.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Np5m4eBy.lean.js",
"/ran/assets/index.md.CzapfhVt.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/cn_src_article_sort_bucket_index.md.BlqoFRKt.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.JFDl-h5J.js",
"/ran/assets/cn_src_types_TS类型.md.7tgg_XKD.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_imagemin.md.DZzI6vdO.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BrigeOrM.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BJN640rT.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_sort_quick_index.md.CP7dT0rl.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.3CTtXPJw.lean.js",
"/ran/assets/cn_src_article_design_mode.md.CONG7gdL.js",
"/ran/assets/src_ranuts_bundler_index.md.DsLogMwX.js",
"/ran/assets/cn_src_article_typescript_calculate.md.3CTtXPJw.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DM2lM5so.lean.js",
"/ran/assets/src_ranui_index.md.DpUVsZh8.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.BivBpgvg.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.BvxuCcyq.lean.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/src_article_javascript_dom_load.md.CM7gIbJr.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_math_linear_algebra.md.BvxuCcyq.js",
"/ran/assets/src_article_sort_heap_index.md.BRZxNonk.js",
"/ran/assets/cn_src_ranui_image_index.md.BJxozRBM.lean.js",
"/ran/assets/src_ranui_tabs_index.md.D2luDP3W.js",
"/ran/assets/src_article_functional_programming.md.CP6gbaIJ.js",
"/ran/assets/src_ranui_button_index.md.DSFqJLMp.lean.js",
"/ran/assets/src_ranui_modal_index.md.UqDof0QY.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BRZxNonk.lean.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.Bezgh6h_.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.CfWwmUQU.js",
"/ran/assets/cn_src_article_sort_count_index.md.D0s2Z-Is.js",
"/ran/assets/cn_src_ranui_button_index.md.A_ALDO69.js",
"/ran/assets/cn_src_article_bundle.md.BQhrODfu.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranui_loading_index.md.D7NbucHc.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BzPmIZ02.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Nc3BEl7f.lean.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/cn_src_article_video.md.Cdbgc561.js",
"/ran/assets/cn_src_ranuts_utils_task.md.H_Aw-wep.js",
"/ran/assets/src_ranuts_file_read_dir.md.CqVqt57k.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.CcSS1b3f.lean.js",
"/ran/assets/cn_src_article_bundle.md.BQhrODfu.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.CF4TdBbd.js",
"/ran/assets/src_ranui_input_index.md.BrjQADy7.js",
"/ran/assets/cn_src_note_docker.md.BhnuBkQm.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/src_ranuts_utils_ocr.md.BpxnV-7W.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.DS28L8fg.js",
"/ran/assets/src_ranui_checkbox_index.md.EMdr708K.js",
"/ran/assets/src_article_sort_index.md.D9WGd7WQ.lean.js",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_player_index.md.BPIK8mKK.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BPIK8mKK.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_article_doc_preview.md.Cs_4mddf.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_note_docker.md.BhnuBkQm.lean.js",
"/ran/assets/index.md.CzapfhVt.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BUfp0qgA.js",
"/ran/assets/src_article_bundle.md.vcLnKq8G.lean.js",
"/ran/assets/src_ranui_modal_index.md.UqDof0QY.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.Cc4o1Q05.lean.js",
"/ran/assets/src_ranui_progress_index.md.DGAR8vov.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranuts_utils_format_json.md.nci1r_6k.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BoFcpDx9.js",
"/ran/assets/src_ranui_select_index.md.DVdWss7M.lean.js",
"/ran/assets/src_ranui_tab_index.md.Bh0b5hnh.js",
"/ran/assets/cn_src_ranui_modal_index.md.DGKWqjcP.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_types_类型运算.md.CpucMdkR.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_types_类型运算.md.DdZMi0yM.lean.js",
"/ran/assets/src_ranui_tabs_index.md.D2luDP3W.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CF4TdBbd.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.VUBQiG5F.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.TQcVaccv.js",
"/ran/assets/cn_src_ranui_math_index.md.RlMqzThp.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.C8RTW9ia.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_article_functional_programming.md.D7gXQ1Uy.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_sort_select_index.md.CHWFtL06.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranuts_file_append_file.md.DQHOL6yn.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Cwv58txT.js",
"/ran/assets/src_article_sort_radix_index.md.BMXDc2Xo.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranuts_file_watch_file.md.feLfL7j5.lean.js",
"/ran/assets/src_ranui_loading_index.md.DvKv1R0N.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.D1feDl9x.js",
"/ran/icon_96.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/index.html",
];
const VERSION = "1751086117";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



