const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/src_ranuts_utils_ocr.md.DgG697W5.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DiLGDzUn.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranuts_file_write_file.md.BzrZupCv.js",
"/ran/assets/cn_src_note_centos.md.EhwLNXz9.js",
"/ran/assets/index.md.B_3phyYr.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_ranui_checkbox_index.md.CDeaiKik.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_article_typescript_pattern.md.Bvg0mrKp.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranui_select_index.md.uhIpW2vo.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_typescript_recursion.md.FHkpBNR5.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.SSJIEWMG.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_article_sort_count_index.md.CeIMwoal.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.B9bNxQ36.lean.js",
"/ran/assets/src_ranuts_utils_task.md.gZ3y6djL.js",
"/ran/assets/src_article_sort_bucket_index.md.C-ju1hLL.js",
"/ran/assets/cn_src_article_sort_insert_index.md.XOTgQkbs.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_design_mode.md.DwWuv7ig.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.zNyWERJ0.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.CsCGHLBd.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_functional_programming.md.DavovwAF.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DSNZtC3i.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DQjmp_ak.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DSNZtC3i.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranui_radar_index.md.DCYjToi4.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.grOZ0KDh.lean.js",
"/ran/assets/cn_src_article_visual.md.DDvsl8lE.js",
"/ran/assets/src_ranui_popover_index.md.Bku4SqHw.lean.js",
"/ran/assets/app.ADXm49E6.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_types_高级类型.md.DCT2WT46.js",
"/ran/assets/cn_src_ranui_image_index.md.CNc2sQWD.js",
"/ran/assets/src_article_functional_programming.md.D737HJoz.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CBobRBM5.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.BKtkd9fH.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranuts_bundler_index.md.DyuK70PA.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DCJjIhgv.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_utils_task.md.Bidsz1Bo.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_ranui_message_index.md.BxhLI2Bq.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CBobRBM5.js",
"/ran/assets/src_article_typescript_union_type.md.BRn_XPQq.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CWgErnSN.lean.js",
"/ran/assets/src_ranui_index.md.BHZKNUxq.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.vvRhXzt7.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C5jg9zi8.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Dg7HHf0m.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.ClC717su.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CF7vKnLu.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_types_TS类型.md.B353gxKy.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CnRaZrGc.js",
"/ran/assets/cn_src_article_sort_insert_index.md.XOTgQkbs.js",
"/ran/assets/src_article_typescript_recursion.md.fhlv7q_d.js",
"/ran/assets/src_article_typescript_index.md.D2EtdzNA.lean.js",
"/ran/assets/src_article_design_mode.md.DwWuv7ig.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.C7hhLmNt.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranui_image_index.md.XQ_e1g9E.lean.js",
"/ran/assets/cn_src_ranuts_index.md.iluCF27Y.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CC1U064o.lean.js",
"/ran/assets/src_ranui_progress_index.md.DSWqyELF.lean.js",
"/ran/assets/src_ranui_message_index.md.CHBeJOkz.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.B0_TcZM3.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BIq-_o8l.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BeB2LQOB.lean.js",
"/ran/assets/cn_src_types_类型运算.md.ChIefnTx.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Ck3FTDt6.lean.js",
"/ran/assets/src_article_imagemin.md.B3Ewg3gR.js",
"/ran/assets/cn_src_ranui_index.md.DNgb2iNd.js",
"/ran/assets/cn_src_types_高级类型.md.Bd-t5ARL.lean.js",
"/ran/assets/cn_index.md.CWvCvBqh.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Bidsz1Bo.lean.js",
"/ran/assets/src_ranui_player_index.md.B5Wrgc2v.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.26M-ykdj.lean.js",
"/ran/assets/src_article_bundle.md.CehTMrVX.lean.js",
"/ran/assets/cn_src_types_TS类型.md.B353gxKy.js",
"/ran/assets/src_ranuts_file_file_info.md.B0_TcZM3.js",
"/ran/assets/cn_src_ranui_modal_index.md.KVuGteX6.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BQLplIwn.js",
"/ran/assets/src_ranui_icon_index.md.DbKXwG-c.js",
"/ran/assets/src_article_sort_shell_index.md.B1arQa-L.lean.js",
"/ran/assets/cn_src_ranui_index.md.DNgb2iNd.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CWgErnSN.js",
"/ran/assets/cn_src_article_sort_count_index.md.KVGnfvLW.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B70SaBkn.js",
"/ran/assets/cn_src_article_typescript_index.md.D1HUtQYk.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CF7vKnLu.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranuts_file_append_file.md.D5cB3OW-.js",
"/ran/assets/src_ranuts_utils_str2xml.md.ClC717su.lean.js",
"/ran/assets/src_article_sort_heap_index.md.Bmx8-zYe.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D7luN1K3.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_sort_count_index.md.KVGnfvLW.js",
"/ran/assets/cn_src_article_system_design.md.CvqsOiDe.js",
"/ran/assets/src_ranuts_file_read_dir.md.igFhiLTI.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Ck3FTDt6.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DJoy4DPL.js",
"/ran/assets/src_ranuts_file_append_file.md.D5cB3OW-.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CwwP-lV4.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.D0invOcR.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_babel.md.mDyMT0uK.js",
"/ran/assets/src_ranui_math_index.md.DtCBtRWf.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.BITZJPbT.js",
"/ran/assets/src_ranui_select_index.md.BFNpYG0v.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Dkn-kw8e.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.K_GROoZ8.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.DR6wOTnb.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_types_类型运算.md.BWooNhu4.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DCJjIhgv.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_note_centos.md.EhwLNXz9.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.DavovwAF.js",
"/ran/assets/src_article_bundle.md.CehTMrVX.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_types_类型运算.md.ChIefnTx.lean.js",
"/ran/assets/src_ranui_loading_index.md.Bq9KNig0.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranui_image_index.md.CNc2sQWD.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_input_index.md.BKtkd9fH.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.KD7u-ikI.lean.js",
"/ran/assets/src_ranui_math_index.md.DtCBtRWf.js",
"/ran/assets/cn_src_article_system_design.md.CvqsOiDe.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Dh9nr1Q8.js",
"/ran/assets/src_ranuts_file_write_file.md.C5SGDt7O.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BeB2LQOB.js",
"/ran/assets/cn_src_ranui_tab_index.md.EUTfuTF7.js",
"/ran/assets/cn_src_ranui_progress_index.md.Ddqva8WH.js",
"/ran/assets/src_types_模式匹配.md.DL9B8qEW.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_article_typescript_recursion.md.fhlv7q_d.lean.js",
"/ran/assets/cn_src_article_design_mode.md.B_s_O24B.js",
"/ran/assets/src_article_sort_select_index.md.CkX280xW.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Dg7HHf0m.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BtpdzbUi.js",
"/ran/assets/src_ranui_tabs_index.md.f4E7FbIP.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CnRaZrGc.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DyuK70PA.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.K_GROoZ8.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C5jg9zi8.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DoITCUh7.lean.js",
"/ran/assets/src_article_sort_index.md.DbTwCHE1.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_design_mode.md.B_s_O24B.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.CsCGHLBd.js",
"/ran/assets/cn_src_article_video.md.CgcR1i_L.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_sort_quick_index.md.nYMdXtvD.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.C57pUVT4.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.uhIpW2vo.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.B8R2QlzF.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.B70SaBkn.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.J9zu07Gb.js",
"/ran/assets/cn_src_article_sort_index.md.DhZXuA33.lean.js",
"/ran/assets/src_ranui_preview_index.md.DoPNwy5U.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DN8-gNnV.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_doc_preview.md.DAVFpxOx.lean.js",
"/ran/assets/src_ranui_tabs_index.md.f4E7FbIP.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.sg7JCrky.js",
"/ran/assets/src_types_类型运算.md.BWooNhu4.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.D0invOcR.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.FHkpBNR5.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranui_message_index.md.BxhLI2Bq.js",
"/ran/assets/src_ranui_input_index.md.Cylf8krb.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BRPDMfTp.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.C7hhLmNt.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranui_image_index.md.XQ_e1g9E.js",
"/ran/assets/src_ranui_tab_index.md.XeecnKQX.lean.js",
"/ran/assets/src_article_imagemin.md.B3Ewg3gR.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_sort_insert_index.md.Bd5XbfW8.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D7luN1K3.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.Dvi6qkYm.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.C0QgFmVI.js",
"/ran/assets/cn_src_note_docker.md.CQXCL4m1.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_button_index.md.CIyvJagI.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BMwGJuju.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_preview_index.md.DoPNwy5U.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_utils_format_json.md.DR6wOTnb.js",
"/ran/assets/src_ranui_radar_index.md.DCYjToi4.js",
"/ran/assets/src_ranuts_utils_format_json.md.BIq-_o8l.js",
"/ran/assets/src_ranui_button_index.md.CIyvJagI.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.032coHBr.js",
"/ran/assets/style.CfDWePi6.css",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.gzgXJ0wH.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DHy3pVdN.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CC2dbz0c.js",
"/ran/assets/cn_src_ranui_tab_index.md.EUTfuTF7.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.nYMdXtvD.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.pxt28MME.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.DYorhwce.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DHy3pVdN.lean.js",
"/ran/assets/src_article_sort_heap_index.md.Bmx8-zYe.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CTL2hYH0.js",
"/ran/assets/src_article_sort_merge_index.md.Dh9nr1Q8.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_types_模式匹配.md.C7-3W_cR.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.B8R2QlzF.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_note_docker.md.CQXCL4m1.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.032coHBr.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.KD7u-ikI.js",
"/ran/assets/src_article_typescript_reconstruction.md.BITZJPbT.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BrXnnreL.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DhZXuA33.js",
"/ran/assets/src_ranui_icon_index.md.DbKXwG-c.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.C7-3W_cR.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_article_sort_shell_index.md.B1arQa-L.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_modal_index.md.D0O2tYYh.js",
"/ran/assets/src_ranuts_index.md.DDUyMLIr.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.26M-ykdj.js",
"/ran/assets/src_ranuts_utils_ocr.md.DgG697W5.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_types_TS类型.md.BZgjTzAn.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.SSJIEWMG.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_skeleton_index.md.CC1U064o.js",
"/ran/assets/src_article_sort_index.md.DbTwCHE1.js",
"/ran/assets/src_ranui_checkbox_index.md.CDeaiKik.lean.js",
"/ran/assets/src_ranui_index.md.BHZKNUxq.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.DiLGDzUn.js",
"/ran/assets/src_article_sort_select_index.md.CkX280xW.js",
"/ran/assets/cn_src_ranui_math_index.md.Dvi6qkYm.js",
"/ran/assets/cn_src_ranui_progress_index.md.Ddqva8WH.lean.js",
"/ran/assets/src_article_typescript_pattern.md.Bvg0mrKp.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.B86SCCqh.js",
"/ran/assets/src_types_高级类型.md.DCT2WT46.lean.js",
"/ran/assets/cn_src_article_visual.md.DDvsl8lE.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BMwGJuju.lean.js",
"/ran/assets/cn_src_article_bundle.md.BKDsSNdN.js",
"/ran/assets/src_ranui_tab_index.md.XeecnKQX.js",
"/ran/assets/cn_src_types_高级类型.md.Bd-t5ARL.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_functional_programming.md.D737HJoz.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.igFhiLTI.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_article_video.md.CgcR1i_L.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.pxt28MME.js",
"/ran/assets/cn_index.md.CWvCvBqh.js",
"/ran/assets/cn_src_ranui_button_index.md.DoITCUh7.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.sg7JCrky.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.zNyWERJ0.js",
"/ran/assets/src_article_javascript_dom_load.md.J9zu07Gb.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_article_sort_insert_index.md.Bd5XbfW8.lean.js",
"/ran/assets/cn_src_article_bundle.md.BKDsSNdN.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranui_input_index.md.Cylf8krb.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranui_player_index.md.B5Wrgc2v.js",
"/ran/assets/src_ranui_loading_index.md.Bq9KNig0.js",
"/ran/assets/src_article_sort_bucket_index.md.C-ju1hLL.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.BQLplIwn.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_player_index.md.5AXNyoiD.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CEf5VWHd.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.mlx79WMc.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.COTOEVCX.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/theme.DIso6oRk.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/VPLocalSearchBox.ktwm_Mbl.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/@localSearchIndexroot.CTkQ7XOx.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/index.BXHq4Ba_.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/@localSearchIndexcn.BeBxzZwy.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/pwa-install.es._Hs-QQNl.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BRPDMfTp.js",
"/ran/assets/cn_src_ranui_icon_index.md.Dkn-kw8e.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_article_sort_bucket_index.md.C0QgFmVI.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_babel.md.3LDCFSZN.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.mlx79WMc.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DQjmp_ak.js",
"/ran/assets/src_ranui_popover_index.md.Bku4SqHw.js",
"/ran/assets/cn_src_ranui_player_index.md.5AXNyoiD.js",
"/ran/assets/cn_src_ranui_modal_index.md.KVuGteX6.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BKXdMfca.js",
"/ran/assets/cn_src_article_sort_select_index.md.CEf5VWHd.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.gzgXJ0wH.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DJoy4DPL.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BeJDHo69.lean.js",
"/ran/assets/src_ranui_message_index.md.CHBeJOkz.js",
"/ran/assets/index.md.B_3phyYr.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BtpdzbUi.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CG-eGAv6.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Bkf3xKYR.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.CTL2hYH0.lean.js",
"/ran/assets/src_ranui_progress_index.md.DSWqyELF.js",
"/ran/assets/src_article_sort_bubble_index.md.C57pUVT4.js",
"/ran/assets/cn_src_article_typescript_index.md.D1HUtQYk.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_article_babel.md.mDyMT0uK.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_ranuts_utils_task.md.gZ3y6djL.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_index.md.iluCF27Y.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_radix_index.md.BeJDHo69.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Bkf3xKYR.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CG-eGAv6.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BKXdMfca.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.vvRhXzt7.js",
"/ran/assets/cn_src_ranui_preview_index.md.grOZ0KDh.js",
"/ran/assets/src_ranuts_index.md.DDUyMLIr.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_count_index.md.CeIMwoal.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.B86SCCqh.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.C5SGDt7O.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.BzrZupCv.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_types_模式匹配.md.DL9B8qEW.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CC2dbz0c.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranuts_file_watch_file.md.DYorhwce.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_imagemin.md.CwwP-lV4.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DN8-gNnV.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.B9bNxQ36.js",
"/ran/assets/src_types_TS类型.md.BZgjTzAn.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_typescript_index.md.D2EtdzNA.js",
"/ran/assets/src_ranui_select_index.md.BFNpYG0v.js",
"/ran/assets/src_article_typescript_calculate.md.BrXnnreL.js",
"/ran/assets/cn_src_article_doc_preview.md.DAVFpxOx.js",
"/ran/assets/cn_src_article_babel.md.3LDCFSZN.js",
"/ran/assets/src_ranui_modal_index.md.D0O2tYYh.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_typescript_union_type.md.BRn_XPQq.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1744685340.js",
];
const VERSION = "1744685340";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



