const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/sw1721295776.js",
"/ran/manifest.json",
"/ran/icon_144.png",
"/ran/icon_48.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/404.html",
"/ran/cn/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/TS类型.html",
"/ran/assets/cn_src_article_sort_index.md.DJQBnlSl.lean.js",
"/ran/assets/src_ranuts_index.md.BScnA8w2.js",
"/ran/assets/src_ranuts_file_writeFile.md.D9I4vj9O.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CLr_pfqi.js",
"/ran/assets/src_article_sort_heap_index.md.Ce3Eb3m4.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.zHp6t7lq.lean.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.zaz0Sf6o.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/index-Bc2Bcl8D.BSWVYAdL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.DBopM22O.js",
"/ran/assets/chunks/theme.DCy0v3Ly.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/index.DbG1EuIE.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/framework.piCEMs4U.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/katex-es-B5r5vt3m.BDSjlQ-m.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/index-CGEx9VOA.DNu1Ssx2.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/cn_src_ranui_loading_index.md.cHjL6K1N.lean.js",
"/ran/assets/src_article_sort_select_index.md.COna5wDs.js",
"/ran/assets/style.BMkmUY6R.css",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_sort_shell_index.md.sWJjKPxT.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_ranui_index.md.D2FiZMRc.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DCkpglLw.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.Dt6m3eNy.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranuts_utils_task.md.D4mESQz9.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BTWCUoNV.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DpzaDmcI.js",
"/ran/assets/cn_src_article_sort_quick_index.md.zHp6t7lq.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CpVp0-wZ.js",
"/ran/assets/src_article_sort_shell_index.md.UKltWJ8c.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.Bxsg2MHD.js",
"/ran/assets/src_ranuts_file_readFile.md.Bt5T9Sro.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranuts_utils_ocr.md.mPu3zron.js",
"/ran/assets/index.md.CJDxf7iR.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D_jwFn3c.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.WVIH0qn6.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DIUAo8IT.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_article_designMode.md.u-G21qMH.js",
"/ran/assets/cn_src_article_designMode.md.CbrPYvKj.js",
"/ran/assets/src_article_sort_radix_index.md.B_UX1QEn.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranuts_file_fileInfo.md.BxXyDXnf.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DHKtX32-.lean.js",
"/ran/assets/src_ranui_preview_index.md.DUli-hwd.lean.js",
"/ran/assets/src_ranui_loading_index.md.DylYH66D.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cy2tiR_h.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_player_index.md.DtskktAT.js",
"/ran/assets/cn_src_article_typescript_index.md.38DC8DzX.js",
"/ran/assets/cn_src_ranui_progress_index.md.CX8Rf-fK.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.s-CUtHYe.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_icon_index.md.BsDUcVJQ.js",
"/ran/assets/cn_src_types_TS类型.md.tU4t9FfZ.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D4mESQz9.lean.js",
"/ran/assets/src_ranui_select_index.md.DIqG5C9L.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_ranuts_file_readFile.md.rzxu6TRZ.lean.js",
"/ran/assets/src_ranui_select_index.md.DIqG5C9L.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_sort_select_index.md.COna5wDs.lean.js",
"/ran/assets/src_article_functionalProgramming.md.BPw28spR.js",
"/ran/assets/cn_src_types_类型运算.md.C23qEpyt.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BKGdbV8Y.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.C2EOkB72.lean.js",
"/ran/assets/src_article_sort_shell_index.md.UKltWJ8c.js",
"/ran/assets/cn_src_types_模式匹配.md.CDmFnCG7.js",
"/ran/assets/src_article_sort_count_index.md.D58Iakf5.js",
"/ran/assets/cn_src_types_高级类型.md.ag1sYe0u.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_sort_select_index.md.CFFkH1u2.lean.js",
"/ran/assets/src_ranuts_index.md.BScnA8w2.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BWxHupAE.js",
"/ran/assets/src_types_高级类型.md.CyLyV7Wm.js",
"/ran/assets/src_article_sort_bubble_index.md.DyhNl4Ar.js",
"/ran/assets/cn_src_ranui_radar_index.md.C_wnqOQm.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DEV-cAfd.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_index.md.C7QVzBpi.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_utils_getCookie.md.BWxHupAE.lean.js",
"/ran/assets/src_ranui_loading_index.md.DylYH66D.js",
"/ran/assets/cn_src_types_模式匹配.md.CDmFnCG7.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.D0R2WyMC.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CaYLh0zT.js",
"/ran/assets/src_article_astParse_tokenizer.md.BoXbdT-5.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DURxh31c.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_mode_subscribe.md.DH0ddjy0.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.nksQ-NlH.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_sort_radix_index.md.B_UX1QEn.lean.js",
"/ran/assets/app.BC3lDR3I.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_functionalProgramming.md.BPw28spR.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BZ41eTJ6.js",
"/ran/assets/cn_src_article_babel.md.B9Pa0mbj.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CjGyw240.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_designMode.md.CbrPYvKj.lean.js",
"/ran/assets/src_ranui_button_index.md.BWNXHOEp.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BtNhh5oo.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_ranui_modal_index.md.QhxTqqEy.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CplVopcg.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CjGyw240.js",
"/ran/assets/src_ranui_image_index.md.CTp9gBy3.lean.js",
"/ran/assets/src_ranui_player_index.md.Dt0fikE-.js",
"/ran/assets/src_types_高级类型.md.CyLyV7Wm.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BZFbHpGW.js",
"/ran/assets/src_ranui_progress_index.md.lg6mNulD.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DIUAo8IT.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BBmFUo4X.js",
"/ran/assets/cn_src_ranui_icon_index.md.CqPhy2i8.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DjnQn4-_.lean.js",
"/ran/assets/src_types_类型运算.md.BQi-XM8h.js",
"/ran/assets/src_ranuts_file_watchFile.md.C1BkIWbl.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DpzaDmcI.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CjiUQun4.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.so128gXf.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.C2EOkB72.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BxXyDXnf.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CpVp0-wZ.lean.js",
"/ran/assets/src_article_bundle.md.yKxSUd5u.js",
"/ran/assets/src_ranuts_utils_ocr.md.UiAVyt1G.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.6lyF-WyM.lean.js",
"/ran/assets/src_ranui_popover_index.md.DUOKpGMK.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BKGdbV8Y.js",
"/ran/assets/cn_src_ranui_input_index.md.Bxsg2MHD.lean.js",
"/ran/assets/src_ranuts_utils_task.md.BW9Dh2XT.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_sort_quick_index.md.CplVopcg.js",
"/ran/assets/src_article_typescript_index.md.CnAoLkWg.lean.js",
"/ran/assets/cn_src_article_visual.md.BpHduFw5.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DU5RY-fK.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.Ks6szy-6.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_sort_bucket_index.md.Dk37BiAC.js",
"/ran/assets/src_types_TS类型.md.Cd2hC4-f.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DzTFexQU.lean.js",
"/ran/assets/src_types_类型运算.md.BQi-XM8h.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DQCcdKzu.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DQCcdKzu.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.Ks6szy-6.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.NxjHXKQy.js",
"/ran/assets/cn_src_types_TS类型.md.tU4t9FfZ.lean.js",
"/ran/assets/src_ranui_message_index.md.BryD4-T4.lean.js",
"/ran/assets/src_ranui_tabs_index.md.VoHVo9GN.js",
"/ran/assets/src_ranui_radar_index.md.BpyvTc1J.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DjnQn4-_.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_index.md.DVmBsGFG.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranui_index.md.DVmBsGFG.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BdgLk3FF.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranui_checkbox_index.md.DzTFexQU.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_count_index.md.C3VgWzo-.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_skeleton_index.md.DHKtX32-.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.rzxu6TRZ.js",
"/ran/assets/src_article_typescript_recursion.md.DjafpXPt.js",
"/ran/assets/src_article_sort_insert_index.md.LxfV8oVe.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BtNhh5oo.js",
"/ran/assets/cn_src_ranui_index.md.D2FiZMRc.js",
"/ran/assets/src_ranuts_file_appendFile.md.6t_01Z3I.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranui_preview_index.md.DUli-hwd.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Q1mkWmty.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranui_progress_index.md.CX8Rf-fK.lean.js",
"/ran/assets/src_ranui_modal_index.md.2VrZ-LBX.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_ranui_button_index.md.BDuuebqn.js",
"/ran/assets/src_article_designMode.md.u-G21qMH.lean.js",
"/ran/assets/index.md.CJDxf7iR.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_calculate.md.DkxOPPo9.lean.js",
"/ran/assets/src_article_babel.md.idKeNnhf.js",
"/ran/assets/src_article_sort_count_index.md.D58Iakf5.lean.js",
"/ran/assets/cn_src_article_visual.md.BpHduFw5.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranui_message_index.md.BryD4-T4.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_math_index.md.CHF7xsy5.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.V4RUWz5R.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.C_wnqOQm.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DCkpglLw.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CdeFM2CB.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B5sWqMWG.js",
"/ran/assets/src_article_sort_index.md.SUU3Y7-7.lean.js",
"/ran/assets/src_article_imagemin.md.sae_w8Sy.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.NxjHXKQy.lean.js",
"/ran/assets/src_article_bundle.md.yKxSUd5u.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.D9I4vj9O.js",
"/ran/assets/cn_src_ranuts_index.md.Bl2a980U.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BBmFUo4X.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CdeFM2CB.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DXMkFb2o.js",
"/ran/assets/cn_src_article_sort_insert_index.md.D3O083vo.js",
"/ran/assets/cn_src_ranui_loading_index.md.cHjL6K1N.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.mPu3zron.lean.js",
"/ran/assets/src_types_模式匹配.md.WrGn-wPt.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.C1M3vqxa.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_utils_str2xml.md.Cfip66rB.lean.js",
"/ran/assets/src_article_babel.md.idKeNnhf.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CaYLh0zT.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranui_image_index.md.BZ41eTJ6.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.BOyW_MSf.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BTWCUoNV.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CS5PH2bS.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D_jwFn3c.js",
"/ran/assets/src_article_typescript_unionType.md.DODRBjh9.js",
"/ran/assets/src_ranui_input_index.md.JHIUOSIB.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_typescript_recursion.md.DjafpXPt.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BdgLk3FF.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.nksQ-NlH.lean.js",
"/ran/assets/src_ranui_popover_index.md.DUOKpGMK.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_article_typescript_calculate.md.DkxOPPo9.js",
"/ran/assets/cn_src_ranui_tab_index.md.BOyW_MSf.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.s-CUtHYe.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Dk37BiAC.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.If5pBoSm.js",
"/ran/assets/cn_src_article_sort_insert_index.md.D3O083vo.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_types_类型运算.md.C23qEpyt.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranui_button_index.md.BWNXHOEp.lean.js",
"/ran/assets/src_ranui_tab_index.md.BA3Yu2Rv.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DC7B6Zc1.js",
"/ran/assets/cn_src_article_sort_count_index.md.C3VgWzo-.lean.js",
"/ran/assets/cn_index.md.C7QVzBpi.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DU5RY-fK.js",
"/ran/assets/src_article_typescript_pattern.md.DURxh31c.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BZFbHpGW.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_math_index.md.CjiUQun4.js",
"/ran/assets/cn_src_ranui_popover_index.md.CLr_pfqi.lean.js",
"/ran/assets/cn_src_article_babel.md.B9Pa0mbj.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Q1mkWmty.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.V4RUWz5R.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DYfdqyiw.js",
"/ran/assets/cn_src_article_typescript_index.md.38DC8DzX.lean.js",
"/ran/assets/src_ranui_tab_index.md.BA3Yu2Rv.lean.js",
"/ran/assets/cn_src_article_bundle.md.mUg_oJc5.js",
"/ran/assets/src_ranui_radar_index.md.BpyvTc1J.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.If5pBoSm.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.WVIH0qn6.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_article_sort_insert_index.md.LxfV8oVe.js",
"/ran/assets/src_article_typescript_unionType.md.DODRBjh9.lean.js",
"/ran/assets/src_ranui_input_index.md.JHIUOSIB.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.C1BkIWbl.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Bzs67kO3.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DnGiyGE-.js",
"/ran/assets/cn_src_ranui_modal_index.md.QhxTqqEy.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.UAqG3JD9.lean.js",
"/ran/assets/src_ranui_player_index.md.Dt0fikE-.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.Dt6m3eNy.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B5sWqMWG.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DVC0deTh.lean.js",
"/ran/assets/src_ranuts_utils_task.md.BW9Dh2XT.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DH0ddjy0.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DJQBnlSl.js",
"/ran/assets/src_ranuts_file_readDir.md.Cv83hc_K.js",
"/ran/assets/src_ranui_tabs_index.md.VoHVo9GN.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DVC0deTh.js",
"/ran/assets/src_ranui_progress_index.md.lg6mNulD.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DXMkFb2o.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Bzs67kO3.js",
"/ran/assets/src_article_typescript_index.md.CnAoLkWg.js",
"/ran/assets/src_ranui_modal_index.md.2VrZ-LBX.js",
"/ran/assets/src_ranuts_file_readDir.md.Cv83hc_K.lean.js",
"/ran/assets/cn_src_ranuts_index.md.Bl2a980U.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.BoXbdT-5.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DYfdqyiw.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BDuuebqn.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CS5PH2bS.js",
"/ran/assets/src_ranuts_utils_filterObj.md.C1M3vqxa.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cy2tiR_h.js",
"/ran/assets/cn_src_ranui_select_index.md.BBztdSnH.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_bundle.md.mUg_oJc5.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CFFkH1u2.js",
"/ran/assets/src_article_imagemin.md.sae_w8Sy.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CqPhy2i8.js",
"/ran/assets/src_ranuts_file_readFile.md.Bt5T9Sro.lean.js",
"/ran/assets/src_ranui_math_index.md.CHF7xsy5.js",
"/ran/assets/src_types_模式匹配.md.WrGn-wPt.js",
"/ran/assets/src_article_sort_bubble_index.md.DyhNl4Ar.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DEV-cAfd.lean.js",
"/ran/assets/cn_src_types_高级类型.md.ag1sYe0u.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DtskktAT.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.so128gXf.lean.js",
"/ran/assets/src_ranui_icon_index.md.BsDUcVJQ.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.D0R2WyMC.js",
"/ran/assets/cn_src_ranui_select_index.md.BBztdSnH.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.6t_01Z3I.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_sort_heap_index.md.Ce3Eb3m4.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DnGiyGE-.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.UiAVyt1G.lean.js",
"/ran/assets/src_ranui_image_index.md.CTp9gBy3.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranuts_bundler_index.md.UAqG3JD9.js",
"/ran/assets/src_article_sort_index.md.SUU3Y7-7.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Cfip66rB.js",
"/ran/assets/cn_src_article_sort_shell_index.md.sWJjKPxT.js",
"/ran/assets/src_types_TS类型.md.Cd2hC4-f.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.6lyF-WyM.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DC7B6Zc1.lean.js",
"/ran/screenshots_748x1340.jpg",
"/ran/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/babel.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/TS类型.html",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/home.svg",
"/ran/icon.png",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_63e4374.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e3e8d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a247d1d.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e385a7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9f70d46.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6ea04b2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_142eff8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_8adcb28.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e176acb.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_628da55.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d9728cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_255c544.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_7738ff7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.en_7a1f95d03b.pf_meta",
"/ran/pagefind/index/zh-cn_d0f5d6e.pf_index",
"/ran/pagefind/index/zh-cn_489feb3.pf_index",
"/ran/pagefind/index/en_031a886.pf_index",
"/ran/pagefind/index/en_85eb4b1.pf_index",
"/ran/pagefind/index/en_5d80bc4.pf_index",
"/ran/pagefind/index/zh-cn_6351def.pf_index",
"/ran/pagefind/index/zh-cn_ff2d63c.pf_index",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.zh-cn_78ef9ca0f59c5.pf_meta",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/icon_72.png",
"/ran/hashmap.json",
];
const VERSION = "1721295776";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



