const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/favicon.ico",
"/ran/logo.png",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/example.m3u8",
"/ran/icon_168.png",
"/ran/assets/cn_src_note_docker.md.Cp9lWfkk.js",
"/ran/assets/src_article_imagemin.md.CUsjwAmI.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.Dp5uqFfs.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_typescript_recursion.md.B39qbkBd.js",
"/ran/assets/cn_src_ranui_radar_index.md.BHXTaLSU.js",
"/ran/assets/cn_src_ranui_input_index.md.Dp5uqFfs.lean.js",
"/ran/assets/cn_src_article_visual.md.Dgwg-HhR.js",
"/ran/assets/src_ranui_modal_index.md.BowPnwrC.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranui_loading_index.md.D5FEd-p_.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BJ2nzOKt.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BZSVekWd.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Bzk7U7nC.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Co6LQWns.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BeIxMkZf.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/chunks/theme.DQ7wRcBc.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/index.lAMYtFho.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/@localSearchIndexcn.Dz8_Kc9b.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/pwa-install.es.BM1ku5fR.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.B4owDQ6x.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/@localSearchIndexroot.DbmVtiHl.js",
"/ran/assets/chunks/VPLocalSearchBox.By315YS8.js",
"/ran/assets/cn_src_note_docker.md.Cp9lWfkk.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C96DGZJp.lean.js",
"/ran/assets/src_types_高级类型.md.CZblIi0v.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BeIxMkZf.lean.js",
"/ran/assets/src_ranui_loading_index.md.D5FEd-p_.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.O2bO0Tv8.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.DVbPt6PL.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BkzdcMKM.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CZ97NKNl.js",
"/ran/assets/cn_src_article_sort_count_index.md.QbQsr6S0.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CMdzKRKa.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DiiF3m9E.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_article_math_linear_algebra.md.DtEtQ5dD.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_ranuts_index.md.DccSFRWV.js",
"/ran/assets/src_article_sort_radix_index.md.BhCFOY-L.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranui_select_index.md.DhEywZaK.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_article_typescript_index.md.B433fqsX.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranui_index.md.CW1lyw-I.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_types_模式匹配.md.Cv45CbsS.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.C9fDsRNA.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.cOpgMpv3.js",
"/ran/assets/cn_src_article_typescript_calculate.md.Cq4n7eV2.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_article_functional_programming.md.DVbPt6PL.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.um2KVYsp.js",
"/ran/assets/src_ranui_tab_index.md.BdZbNHQM.js",
"/ran/assets/src_ranui_icon_index.md.Cuk4y7tG.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_input_index.md.eRMjUTiv.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CArzD8mD.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BfZE9nXB.js",
"/ran/assets/src_article_typescript_calculate.md.DE_hYemu.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DwvcIFen.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Cz_GpD8E.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.C0pEdq0O.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.Cq4n7eV2.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_imagemin.md.CUsjwAmI.js",
"/ran/assets/src_ranuts_file_read_dir.md.wZh3YM67.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DmXGsQqD.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_article_sort_select_index.md.OBR0YLNk.lean.js",
"/ran/assets/src_ranui_message_index.md.BJ1D0PkQ.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DiiF3m9E.js",
"/ran/assets/src_ranuts_file_file_info.md.CT7NvEqP.js",
"/ran/assets/src_ranuts_binary_tree_index.md.D3eNNIj7.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_utils_task.md.DwvcIFen.js",
"/ran/assets/src_ranui_image_index.md.CUbUXUMq.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.4pmOxGww.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_sort_index.md.CV7xwzz5.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BZSVekWd.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CGaUOiNu.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BhCFOY-L.js",
"/ran/assets/src_ranuts_index.md.CAUIreNs.js",
"/ran/assets/cn_src_ranui_preview_index.md.CaJavXRX.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DisBhJpQ.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_bundle.md.CDqwrMwa.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CTycE4bf.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Ce3gYJPG.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_typescript_union_type.md.Y1DGckN0.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DTS3HkzQ.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.O2bO0Tv8.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.SBf7snDY.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CD1z3IkE.lean.js",
"/ran/assets/src_ranui_popover_index.md.CaAe6N8Q.js",
"/ran/assets/src_ranui_math_index.md.dV27VDxt.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BHnj78Cl.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_merge_index.md.Dfk6XcGc.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.D--DPM7X.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.cOpgMpv3.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.wZh3YM67.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DrpKBm6A.js",
"/ran/assets/src_article_typescript_index.md.B433fqsX.js",
"/ran/assets/cn_src_ranui_loading_index.md.C0pEdq0O.js",
"/ran/assets/cn_src_ranui_message_index.md.4pmOxGww.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.BB2Ko-A8.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranui_preview_index.md.DBz6q8ma.js",
"/ran/assets/src_article_typescript_union_type.md.BFnLOTp8.lean.js",
"/ran/assets/cn_src_article_system_design.md.CGtWS0Aj.js",
"/ran/assets/cn_src_article_design_mode.md.BT8NRYSr.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_typescript_calculate.md.DE_hYemu.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_progress_index.md.lJDYkRsI.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CSB-_g4Q.js",
"/ran/assets/src_article_sort_shell_index.md.Dmv7AcNb.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Bx7O9GRe.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BkzdcMKM.js",
"/ran/assets/src_ranui_input_index.md.eRMjUTiv.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_ranuts_utils_format_json.md.CG1k-2rp.lean.js",
"/ran/assets/cn_src_article_design_mode.md.BT8NRYSr.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_design_mode.md.BZD4D_8K.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_file_append_file.md.CD6zP7AX.js",
"/ran/assets/cn_src_ranui_tabs_index.md.jtJkaqCx.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_javascript_dom_load.md.DmXGsQqD.lean.js",
"/ran/assets/src_ranui_math_index.md.dV27VDxt.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DisBhJpQ.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CTxz3P_x.js",
"/ran/assets/cn_src_note_ubuntu.md.D4_N1Ejh.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CMdzKRKa.js",
"/ran/assets/src_article_design_mode.md.BZD4D_8K.lean.js",
"/ran/assets/style.BogOoltj.css",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.0AZtfcTz.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.jtJkaqCx.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.DotwFZ_s.js",
"/ran/assets/cn_src_article_system_design.md.CGtWS0Aj.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BRKzgdtZ.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_player_index.md.BUP0l_xm.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_types_类型运算.md.BGzQsTne.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.D0_l2Iho.js",
"/ran/assets/src_article_typescript_recursion.md.B39qbkBd.lean.js",
"/ran/assets/src_article_babel.md.ClVMHacy.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.DhIss1o2.lean.js",
"/ran/assets/src_ranui_button_index.md.CpZfhslt.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Dfk6XcGc.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.Y1DGckN0.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CExwQ52c.js",
"/ran/assets/cn_src_article_sort_index.md.luhdokOk.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_sort_select_index.md.CZfK7Spg.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_message_index.md.BJ1D0PkQ.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DtEtQ5dD.lean.js",
"/ran/assets/src_types_模式匹配.md.VB-oxjBB.lean.js",
"/ran/assets/cn_src_ranuts_index.md.DccSFRWV.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranui_tab_index.md.BdZbNHQM.lean.js",
"/ran/assets/cn_src_ranui_index.md.HulhNol2.js",
"/ran/assets/src_ranuts_utils_task.md.o975joEG.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_article_functional_programming.md.CBml2rJz.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_preview_index.md.DBz6q8ma.lean.js",
"/ran/assets/cn_src_ranui_index.md.HulhNol2.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DD9Mll9P.js",
"/ran/assets/cn_src_ranui_select_index.md.4dS01T0c.lean.js",
"/ran/assets/src_article_bundle.md.CDqwrMwa.js",
"/ran/assets/src_article_typescript_pattern.md.Dzsnto5e.js",
"/ran/assets/cn_src_types_TS类型.md.CD5duK0-.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BUT55iDn.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BJ2nzOKt.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranui_tabs_index.md.CTycE4bf.js",
"/ran/assets/src_article_sort_heap_index.md.B0k9mckh.js",
"/ran/assets/src_article_sort_bucket_index.md.BUT55iDn.js",
"/ran/assets/cn_src_ranui_icon_index.md.C83clEVI.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.D1b_M6nO.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.Cv45CbsS.js",
"/ran/assets/src_ranuts_file_append_file.md.PZMqrzKw.js",
"/ran/assets/cn_src_ranui_button_index.md.BiNru7Vq.js",
"/ran/assets/src_ranuts_file_watch_file.md.BN3Gx2EW.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_bundler_index.md.DlbkWazD.js",
"/ran/assets/src_types_模式匹配.md.VB-oxjBB.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DEGRtfPC.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.OtVLxCQK.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_types_TS类型.md.DNKOITuW.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.OtVLxCQK.js",
"/ran/assets/src_ranuts_file_write_file.md.Db3MJKcO.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D1eQ9Q_s.lean.js",
"/ran/assets/cn_src_types_高级类型.md.C0V632zv.js",
"/ran/assets/src_ranuts_utils_format_json.md.CG1k-2rp.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.DhIss1o2.js",
"/ran/assets/src_article_javascript_dom_load.md.0EsGf9qV.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranui_checkbox_index.md.hBj744wO.js",
"/ran/assets/src_ranuts_bundler_index.md.DlbkWazD.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DtOlhFOL.js",
"/ran/assets/src_ranui_image_index.md.CUbUXUMq.js",
"/ran/assets/index.md.CL6mkFBA.js",
"/ran/assets/cn_src_article_sort_count_index.md.QbQsr6S0.js",
"/ran/assets/src_article_babel.md.ClVMHacy.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BN3Gx2EW.lean.js",
"/ran/assets/src_ranuts_index.md.CAUIreNs.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_ranui_progress_index.md.l5SSQcJA.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Co6LQWns.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BfZE9nXB.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.D--DPM7X.js",
"/ran/assets/src_article_sort_heap_index.md.B0k9mckh.lean.js",
"/ran/assets/cn_src_article_imagemin.md.CD1z3IkE.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.D1b_M6nO.js",
"/ran/assets/src_article_typescript_pattern.md.Dzsnto5e.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Ce3gYJPG.lean.js",
"/ran/assets/src_ranui_player_index.md.DMKrCjF_.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CExwQ52c.lean.js",
"/ran/assets/src_types_类型运算.md.BGzQsTne.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.4dS01T0c.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_file_write_file.md.DD9Mll9P.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.D0_l2Iho.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.6aISp2Kv.js",
"/ran/assets/cn_src_article_typescript_index.md.CmXAILmY.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BWErdmLF.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.0AZtfcTz.js",
"/ran/assets/src_ranui_radar_index.md.BM4Vd3t7.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CArzD8mD.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_ranui_math_index.md.BDZp-QE2.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.CD6zP7AX.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.CigvgTES.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.BDZp-QE2.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C96DGZJp.js",
"/ran/assets/src_ranui_radar_index.md.BM4Vd3t7.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.CHxS-bth.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DEGRtfPC.js",
"/ran/assets/cn_src_article_bundle.md.DqpQ6kuB.js",
"/ran/assets/src_ranuts_file_read_file.md.DrIN-0CW.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranuts_mime_type_mime_type.md.um2KVYsp.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.l5SSQcJA.js",
"/ran/assets/cn_src_ranui_popover_index.md.FnVNeovb.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BWErdmLF.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DrpKBm6A.lean.js",
"/ran/assets/src_ranui_progress_index.md.lJDYkRsI.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_sort_bubble_index.md.DtOlhFOL.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Bx7O9GRe.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.FnVNeovb.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_sort_heap_index.md.6aISp2Kv.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.SBf7snDY.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_note_centos.md.BynmB5bn.js",
"/ran/assets/src_article_sort_count_index.md.DtmMB3ez.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.D3eNNIj7.js",
"/ran/assets/cn_src_article_bundle.md.DqpQ6kuB.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BHXTaLSU.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranui_icon_index.md.C83clEVI.js",
"/ran/assets/cn_src_ranui_player_index.md.BUP0l_xm.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.BHnj78Cl.lean.js",
"/ran/assets/cn_src_types_TS类型.md.CD5duK0-.js",
"/ran/assets/cn_src_article_video.md.C22U7I3h.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.CceyrGwp.js",
"/ran/assets/src_article_sort_quick_index.md.CZ97NKNl.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.C9fDsRNA.lean.js",
"/ran/assets/src_article_sort_index.md.CV7xwzz5.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CZfK7Spg.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DTS3HkzQ.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CSB-_g4Q.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranui_skeleton_index.md.BB2Ko-A8.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_article_typescript_index.md.CmXAILmY.js",
"/ran/assets/cn_src_ranui_preview_index.md.CaJavXRX.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_typescript_union_type.md.BFnLOTp8.js",
"/ran/assets/src_ranui_button_index.md.CpZfhslt.js",
"/ran/assets/src_ranuts_file_write_file.md.Db3MJKcO.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D1eQ9Q_s.js",
"/ran/assets/cn_src_ranui_button_index.md.BiNru7Vq.lean.js",
"/ran/assets/src_ranui_index.md.CW1lyw-I.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_babel.md.CAIPSadU.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CigvgTES.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CGaUOiNu.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_file_read_file.md.DrIN-0CW.lean.js",
"/ran/assets/src_ranui_icon_index.md.Cuk4y7tG.lean.js",
"/ran/assets/src_article_functional_programming.md.CBml2rJz.js",
"/ran/assets/cn_src_ranui_image_index.md.CceyrGwp.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.0EsGf9qV.lean.js",
"/ran/assets/cn_src_types_高级类型.md.C0V632zv.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_note_ubuntu.md.D4_N1Ejh.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.-I2usGBc.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranuts_file_append_file.md.PZMqrzKw.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.-I2usGBc.js",
"/ran/assets/src_ranui_checkbox_index.md.hBj744wO.lean.js",
"/ran/assets/app.DVOvu3vF.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_sort_index.md.luhdokOk.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CptvONRl.js",
"/ran/assets/index.md.CL6mkFBA.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CptvONRl.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DotwFZ_s.lean.js",
"/ran/assets/src_ranuts_utils_task.md.o975joEG.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_index.md.BiGunw_S.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CHxS-bth.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Cz_GpD8E.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_article_video.md.C22U7I3h.js",
"/ran/assets/src_ranui_select_index.md.DhEywZaK.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_index.md.BiGunw_S.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CTxz3P_x.lean.js",
"/ran/assets/src_types_高级类型.md.CZblIi0v.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_article_visual.md.Dgwg-HhR.lean.js",
"/ran/assets/src_article_sort_count_index.md.DtmMB3ez.js",
"/ran/assets/src_ranui_popover_index.md.CaAe6N8Q.lean.js",
"/ran/assets/src_ranui_player_index.md.DMKrCjF_.js",
"/ran/assets/src_ranuts_file_file_info.md.CT7NvEqP.lean.js",
"/ran/assets/src_article_sort_select_index.md.OBR0YLNk.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranui_modal_index.md.BowPnwrC.js",
"/ran/assets/cn_src_article_babel.md.CAIPSadU.lean.js",
"/ran/assets/src_types_TS类型.md.DNKOITuW.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_sort_insert_index.md.BRKzgdtZ.js",
"/ran/assets/cn_src_note_centos.md.BynmB5bn.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Bzk7U7nC.lean.js",
"/ran/assets/src_article_sort_shell_index.md.Dmv7AcNb.js",
"/ran/manifest.json",
"/ran/hashmap.json",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon.png",
"/ran/src/article/imagemin.html",
"/ran/src/article/babel.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/screenshots_748x1340.jpg",
"/ran/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_192.png",
"/ran/vp-icons.css",
"/ran/home.svg",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/icon_48.png",
"/ran/sw1746460074.js",
"/ran/icon_72.png",
];
const VERSION = "1746460074";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



