const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_976d864.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c45892d.pf_fragment",
"/ran/pagefind/fragment/en_786dd1d.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_6a4c97c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7be51c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b0cd6bd.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_45694f5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/zh-cn_94b27bd.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/pagefind.zh-cn_6316b515b06cf.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/index/zh-cn_bbc0229.pf_index",
"/ran/pagefind/index/zh-cn_44ef41e.pf_index",
"/ran/pagefind/index/zh-cn_9b7a61c.pf_index",
"/ran/pagefind/index/en_b895e55.pf_index",
"/ran/pagefind/index/en_85b7a87.pf_index",
"/ran/pagefind/index/en_55128ca.pf_index",
"/ran/pagefind/index/zh-cn_6b9c5fe.pf_index",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.en_f4f324b3c4.pf_meta",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.js",
"/ran/404.html",
"/ran/icon_168.png",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/babel.html",
"/ran/src/article/bundle.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/icon_48.png",
"/ran/sw1718767587.js",
"/ran/assets/cn_src_types_模式匹配.md.vadgX0u4.js",
"/ran/assets/src_types_模式匹配.md.Cip8wF7X.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CJdJmdzp.js",
"/ran/assets/src_ranui_message_index.md.D5iNBpIw.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.DxPQQyWT.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Pl00JSZo.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Shk2JmVx.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_typescript_reconstruction.md.CQNI1GGo.js",
"/ran/assets/cn_src_ranui_message_index.md.DL3ctFTA.js",
"/ran/assets/cn_src_ranui_image_index.md.CWKY6Y5-.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Shk2JmVx.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranui_image_index.md.-NKE9frH.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DUzOJ13L.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.Tj_qfEIU.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_bundle.md.DmmUbab9.lean.js",
"/ran/assets/src_ranui_select_index.md.UxZatJGd.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DL3ctFTA.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DslUmd5b.js",
"/ran/assets/src_types_高级类型.md.xYT0zN17.js",
"/ran/assets/src_article_babel.md.OEBASi_t.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CR7BRkS-.js",
"/ran/assets/src_article_sort_merge_index.md.CZtRg4-M.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.Ba4FLLTG.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Bktv_LMC.js",
"/ran/assets/cn_src_ranui_input_index.md.CorHbiZU.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DUzOJ13L.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BqMYQbwl.js",
"/ran/assets/app.Bg-XJqAD.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_typescript_index.md.BFzdPt_J.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.BDlxHSaL.js",
"/ran/assets/cn_src_ranui_select_index.md.DKhTHLMS.lean.js",
"/ran/assets/cn_src_article_designMode.md.DQM4li9c.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_article_sort_quick_index.md.BBB6VawR.js",
"/ran/assets/src_ranui_tab_index.md.Wn__-3RV.js",
"/ran/assets/cn_src_article_typescript_recursion.md.fAAAAqCc.js",
"/ran/assets/cn_src_article_sort_count_index.md.B1iZaLdH.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.DNE9BE5z.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DFJRlSOO.js",
"/ran/assets/src_ranuts_binaryTree_index.md.-bQVkBlY.lean.js",
"/ran/assets/src_ranui_preview_index.md.CiGchDCh.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.D7PgKdV6.js",
"/ran/assets/cn_src_types_类型运算.md.Hf0xLSgZ.js",
"/ran/assets/src_types_类型运算.md.D5rJf8M_.lean.js",
"/ran/assets/cn_src_article_bundle.md.C480gcVS.js",
"/ran/assets/src_ranuts_utils_task.md.CLVLpoIB.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.kgPx0a0a.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.BDhqJXMe.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranuts_bundler_index.md.vuEWk5IJ.js",
"/ran/assets/cn_src_article_sort_index.md.sJnnjWdy.js",
"/ran/assets/src_article_sort_count_index.md.BgCyEtLs.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DaQJeyqE.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranuts_utils_getCookie.md.BPClcKdQ.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.B5LdTIXT.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Cj481Nme.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DHgZ6lu4.lean.js",
"/ran/assets/cn_index.md.D-MMT3HS.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_skeleton_index.md.FW1OZoqI.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_typescript_pattern.md.VybvYOx9.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.B5LdTIXT.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DZ6qri1B.lean.js",
"/ran/assets/src_ranui_tabs_index.md.NHSkZGCR.js",
"/ran/assets/src_ranui_popover_index.md.74HrIkbI.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.EJiAkM5z.lean.js",
"/ran/assets/src_article_functionalProgramming.md.S97fMIhg.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_index.md.D-MMT3HS.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_types_高级类型.md.BT_JUpJ1.js",
"/ran/assets/cn_src_article_sort_count_index.md.B1iZaLdH.js",
"/ran/assets/cn_src_article_sort_select_index.md.D6vmH_CT.js",
"/ran/assets/src_article_typescript_index.md.BFzdPt_J.js",
"/ran/assets/src_article_typescript_pattern.md.VybvYOx9.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Bktv_LMC.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_typescript_unionType.md.5UK-Qab7.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.D7PgKdV6.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BsCWnttK.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CR7BRkS-.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CcsiKS5F.js",
"/ran/assets/src_ranui_message_index.md.D5iNBpIw.js",
"/ran/assets/src_article_sort_select_index.md.CoU2lD5s.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cto0MfZK.js",
"/ran/assets/src_ranuts_bundler_index.md.vuEWk5IJ.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.C1zqtDx9.lean.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.DI0wzLeq.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/index.C4Mezt3q.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/index-_VGQJgcS.BO3uIude.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/theme.CkLcTMNZ.js",
"/ran/assets/chunks/framework.BZEwi-oL.js",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/index-CGEx9VOA.kxSojsaB.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/src_article_sort_shell_index.md.CGg9ZysP.js",
"/ran/assets/cn_src_article_babel.md.DEOGa2iu.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Bkn39DXh.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_file_readFile.md.B93KABRd.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.cOCGwoJZ.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/style.DxMSLhj5.css",
"/ran/assets/src_ranuts_binaryTree_index.md.-bQVkBlY.js",
"/ran/assets/src_ranuts_file_writeFile.md.Betu5zad.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_icon_index.md.C4V68JXA.js",
"/ran/assets/cn_src_article_sort_quick_index.md.D1wUG9lN.js",
"/ran/assets/cn_src_article_typescript_calculate.md.D7qRn7o1.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CEU29ZGd.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BrfkGqTg.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.DKhTHLMS.js",
"/ran/assets/cn_src_ranui_progress_index.md.BZAd_VTo.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.B1GdBlu0.js",
"/ran/assets/src_article_sort_bubble_index.md.26BXQSsS.js",
"/ran/assets/src_types_类型运算.md.D5rJf8M_.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.B93KABRd.js",
"/ran/assets/cn_src_types_高级类型.md.BT_JUpJ1.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.-oHWLMbF.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CL2Vnp8H.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_sort_shell_index.md.CGg9ZysP.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CXhbc4yE.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.EJiAkM5z.js",
"/ran/assets/src_ranui_select_index.md.UxZatJGd.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_imagemin.md.Buar7BTW.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_article_bundle.md.DmmUbab9.js",
"/ran/assets/src_ranui_tabs_index.md.NHSkZGCR.lean.js",
"/ran/assets/src_types_高级类型.md.xYT0zN17.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Cto0MfZK.lean.js",
"/ran/assets/src_article_sort_index.md.EMA8g4yu.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_progress_index.md.BZAd_VTo.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DQy2yttZ.js",
"/ran/assets/src_article_sort_heap_index.md.DAGli9ZR.js",
"/ran/assets/cn_src_ranui_radar_index.md.BkMfeEvT.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BNN3KLeT.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranuts_index.md.BK9dFs60.js",
"/ran/assets/cn_src_types_TS类型.md.0UM--JII.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_sort_insert_index.md.DwlUXMAa.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_radar_index.md.C_NOZAwP.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CXhbc4yE.js",
"/ran/assets/src_article_sort_quick_index.md.BBB6VawR.lean.js",
"/ran/assets/src_article_typescript_unionType.md.5UK-Qab7.js",
"/ran/assets/src_ranui_tab_index.md.Wn__-3RV.lean.js",
"/ran/assets/cn_src_ranui_index.md.Cg7i6OON.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CcsiKS5F.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BySHqrOy.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B80WV7iv.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_utils_ocr.md.gI12CWwd.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranui_preview_index.md.DNE9BE5z.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B80WV7iv.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_utils_task.md.DhrHvq3j.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_progress_index.md.DVppTD-U.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DuhJEkRF.lean.js",
"/ran/assets/src_types_TS类型.md.CZowKnVd.lean.js",
"/ran/assets/index.md.CqvSZphE.js",
"/ran/assets/src_ranuts_file_writeFile.md.Betu5zad.lean.js",
"/ran/assets/src_article_sort_select_index.md.CoU2lD5s.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_sort_radix_index.md.Ddg8iLhl.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_checkbox_index.md.DuhJEkRF.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_typescript_calculate.md.BfrpwoQp.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BySHqrOy.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.D849f0Vk.js",
"/ran/assets/src_types_模式匹配.md.Cip8wF7X.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BPClcKdQ.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranuts_utils_formatJson.md.Pl00JSZo.js",
"/ran/assets/cn_src_article_babel.md.DEOGa2iu.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.m3Wq-wzF.lean.js",
"/ran/assets/src_article_designMode.md.8WqRBbdQ.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DDiBqndj.js",
"/ran/assets/src_article_sort_radix_index.md.DV_2c9On.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Ddg8iLhl.js",
"/ran/assets/src_article_sort_count_index.md.BgCyEtLs.lean.js",
"/ran/assets/src_ranui_modal_index.md.B2zYBR4y.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DFJRlSOO.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.ByIx95EA.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.D1wUG9lN.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CRVDirQK.lean.js",
"/ran/assets/cn_src_types_TS类型.md.0UM--JII.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.YKMax5nc.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.m3Wq-wzF.js",
"/ran/assets/src_article_javascript_domLoad.md.CJpa9LgZ.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_sort_bubble_index.md.26BXQSsS.lean.js",
"/ran/assets/cn_src_article_bundle.md.C480gcVS.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_file_watchFile.md.BDhqJXMe.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_typescript_pattern.md.BsCWnttK.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DQy2yttZ.lean.js",
"/ran/assets/src_article_sort_index.md.EMA8g4yu.js",
"/ran/assets/cn_src_ranui_radar_index.md.BkMfeEvT.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Bkn39DXh.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DDiBqndj.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DwlUXMAa.js",
"/ran/assets/cn_src_article_imagemin.md.DqBqzNRW.lean.js",
"/ran/assets/src_ranui_image_index.md.-NKE9frH.js",
"/ran/assets/src_ranui_modal_index.md.B2zYBR4y.js",
"/ran/assets/src_ranui_input_index.md.BpRRbmtr.js",
"/ran/assets/src_article_typescript_calculate.md.BfrpwoQp.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CsriMrfj.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.Cj481Nme.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_checkbox_index.md.BthPvU1I.js",
"/ran/assets/src_ranui_progress_index.md.DVppTD-U.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_loading_index.md.hxun687v.js",
"/ran/assets/src_ranuts_utils_ocr.md.gI12CWwd.js",
"/ran/assets/src_ranuts_file_appendFile.md.DxPQQyWT.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.Ba4FLLTG.js",
"/ran/assets/cn_src_types_模式匹配.md.vadgX0u4.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.kgPx0a0a.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Bh2UrjxD.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BvNhkjai.lean.js",
"/ran/assets/cn_src_ranui_index.md.Cg7i6OON.js",
"/ran/assets/src_ranui_preview_index.md.CiGchDCh.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CQNI1GGo.lean.js",
"/ran/assets/src_ranui_button_index.md.CwW-vyD3.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DslUmd5b.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.BDlxHSaL.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.D849f0Vk.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranui_button_index.md.CwW-vyD3.js",
"/ran/assets/cn_src_ranui_modal_index.md.Tj_qfEIU.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_heap_index.md.DAGli9ZR.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BqMYQbwl.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_image_index.md.CWKY6Y5-.lean.js",
"/ran/assets/src_ranuts_utils_task.md.CLVLpoIB.js",
"/ran/assets/cn_src_ranuts_index.md.CRVDirQK.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.C1zqtDx9.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_shell_index.md.DoAB8KzA.lean.js",
"/ran/assets/src_ranui_index.md.B28Qr6Zk.js",
"/ran/assets/cn_src_ranui_input_index.md.CorHbiZU.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranui_icon_index.md.CL2Vnp8H.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranuts_utils_task.md.DhrHvq3j.lean.js",
"/ran/assets/index.md.CqvSZphE.lean.js",
"/ran/assets/src_ranui_radar_index.md.C_NOZAwP.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranui_loading_index.md.B7n4EMZj.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BNN3KLeT.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DaQJeyqE.lean.js",
"/ran/assets/src_ranui_player_index.md.DvuzPeSU.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_checkbox_index.md.BthPvU1I.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CZtRg4-M.js",
"/ran/assets/cn_src_article_sort_select_index.md.D6vmH_CT.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.FW1OZoqI.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BrfkGqTg.js",
"/ran/assets/src_article_babel.md.OEBASi_t.js",
"/ran/assets/src_ranuts_utils_filterObj.md.KAnJOXqH.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.YKMax5nc.js",
"/ran/assets/src_ranuts_file_readFile.md.-oHWLMbF.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CJdJmdzp.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.fAAAAqCc.lean.js",
"/ran/assets/src_ranui_popover_index.md.74HrIkbI.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CmQGuSsg.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DoAB8KzA.js",
"/ran/assets/src_types_TS类型.md.CZowKnVd.js",
"/ran/assets/src_article_imagemin.md.Buar7BTW.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.D7qRn7o1.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.cOCGwoJZ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.Hf0xLSgZ.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.ByIx95EA.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranui_icon_index.md.C4V68JXA.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BvNhkjai.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_loading_index.md.hxun687v.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.DZ6qri1B.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_player_index.md.CsriMrfj.js",
"/ran/assets/cn_src_ranui_loading_index.md.B7n4EMZj.js",
"/ran/assets/cn_src_article_designMode.md.DQM4li9c.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DV_2c9On.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CmQGuSsg.lean.js",
"/ran/assets/src_ranui_player_index.md.DvuzPeSU.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BUWZepp6.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CEU29ZGd.lean.js",
"/ran/assets/src_ranui_input_index.md.BpRRbmtr.lean.js",
"/ran/assets/src_ranui_index.md.B28Qr6Zk.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DqBqzNRW.js",
"/ran/assets/src_article_designMode.md.8WqRBbdQ.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranuts_mode_subscribe.md.B1GdBlu0.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_utils_filterObj.md.KAnJOXqH.lean.js",
"/ran/assets/src_article_functionalProgramming.md.S97fMIhg.lean.js",
"/ran/assets/cn_src_article_sort_index.md.sJnnjWdy.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.BUWZepp6.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Bh2UrjxD.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DHgZ6lu4.js",
"/ran/assets/src_article_javascript_domLoad.md.CJpa9LgZ.lean.js",
"/ran/assets/src_ranuts_index.md.BK9dFs60.lean.js",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/example.m3u8",
"/ran/icon_144.png",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/index.html",
"/ran/hashmap.json",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_96.png",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/home.svg",
"/ran/icon.png",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/manifest.json",
];
const VERSION = "1718767587";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



