const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranuts_index.md.kpJ4u0pd.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_file_read_file.md.Cb2Dbxag.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_article_typescript_reconstruction.md.D2B0Ly0Q.js",
"/ran/assets/src_ranuts_file_append_file.md.BuR3xS2T.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BS833DEe.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.Den-rHa2.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_image_index.md.C4iPJAoj.js",
"/ran/assets/src_ranuts_utils_str2xml.md.1wD8QtGk.lean.js",
"/ran/assets/src_ranui_modal_index.md.B92VsoL9.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_select_index.md.Bnfsmtzi.lean.js",
"/ran/assets/src_ranui_image_index.md.DtVIrWnJ.lean.js",
"/ran/assets/cn_src_article_system_design.md.B-8KtH0d.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9boIafd.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.C4iPJAoj.lean.js",
"/ran/assets/cn_src_article_visual.md.BR2dMy_Y.js",
"/ran/assets/src_article_sort_quick_index.md.kezvMW3h.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BW8FTDFT.js",
"/ran/assets/src_article_sort_insert_index.md.CA9dLxvJ.js",
"/ran/assets/src_ranui_math_index.md.CNXwmORy.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.Dkv8T0J-.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C8ht4tGG.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_types_TS类型.md.CZFSdhP2.lean.js",
"/ran/assets/src_article_babel.md.D-7bjJm2.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BKRJJbb-.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_popover_index.md.UlnjmATk.js",
"/ran/assets/cn_src_ranui_index.md.BtaRoXNi.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_types_高级类型.md.BruNHXO-.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_article_sort_quick_index.md.BgvKSHaQ.js",
"/ran/assets/src_article_bundle.md.BJ6oh9Uc.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CfggCKUv.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranui_icon_index.md.eFtduk_f.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.59gTmmNy.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DfVv0hGi.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BDADh4UD.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.BBsg0GDa.js",
"/ran/assets/src_ranui_message_index.md.B3tTZGG8.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BoQ20aO9.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.T-krbS74.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_article_javascript_dom_load.md.1hedv02K.js",
"/ran/assets/index.md.BfZebtDl.js",
"/ran/assets/src_article_sort_shell_index.md.CtEUoE2z.lean.js",
"/ran/assets/src_ranui_icon_index.md.MAkePo6C.js",
"/ran/assets/src_article_sort_radix_index.md.1Kyfb7wm.lean.js",
"/ran/assets/src_ranui_input_index.md.oHo1kN0S.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_typescript_pattern.md.CammNTR6.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DVuXb4Bi.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranui_message_index.md.B3tTZGG8.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BcFtj5D0.js",
"/ran/assets/src_ranui_skeleton_index.md.Den-rHa2.lean.js",
"/ran/assets/src_article_functional_programming.md.CRUO8BCf.lean.js",
"/ran/assets/src_article_imagemin.md.0FgsOhYK.js",
"/ran/assets/cn_src_ranui_loading_index.md.9IBFfU9m.js",
"/ran/assets/cn_src_article_imagemin.md.DOSlz0Wx.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.Vu2s5BOz.lean.js",
"/ran/assets/src_article_functional_programming.md.CRUO8BCf.js",
"/ran/assets/src_ranui_tabs_index.md.Crwp7D86.js",
"/ran/assets/src_ranuts_file_read_dir.md.CpqK6FaN.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_index.md.BtaRoXNi.js",
"/ran/assets/cn_src_ranui_preview_index.md.DzIUlaRg.js",
"/ran/assets/cn_src_types_类型运算.md.CpJPaDmJ.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CCECA4_e.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BmR8fV7N.js",
"/ran/assets/src_article_typescript_union_type.md.VkY9bFMj.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DOSlz0Wx.js",
"/ran/assets/cn_src_article_typescript_index.md.CF4ds91_.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.eFtduk_f.js",
"/ran/assets/cn_src_article_sort_count_index.md.BuyjJwKQ.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BcFtj5D0.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Cf7RkW14.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_article_visual.md.BR2dMy_Y.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.DkJymR0A.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_typescript_pattern.md.DkJymR0A.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CPATfHNA.lean.js",
"/ran/assets/src_article_sort_select_index.md.C8EA3lpe.js",
"/ran/assets/cn_src_ranui_player_index.md.CpsIuOW4.js",
"/ran/assets/cn_src_article_sort_count_index.md.BuyjJwKQ.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_sort_quick_index.md.kezvMW3h.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.1hedv02K.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.PSwtK7lG.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_article_sort_heap_index.md.CTGFw7v1.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B-hYjXic.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_sort_heap_index.md.CTGFw7v1.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BDADh4UD.js",
"/ran/assets/cn_src_article_bundle.md.DjRt0tWh.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.wXdd_T5u.js",
"/ran/assets/cn_src_ranuts_index.md.cDV91jOw.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.RaIUap8g.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.D-gfK9hb.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9boIafd.js",
"/ran/assets/cn_src_ranui_button_index.md.DrzJsrJS.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.HxOpVA5X.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BmR8fV7N.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.gViSbZ_R.lean.js",
"/ran/assets/src_ranui_select_index.md.BzUpuzCa.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DwXuPI0g.js",
"/ran/assets/cn_src_article_functional_programming.md.duV-IXZT.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DgHQ5aWl.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.16jpT9NN.js",
"/ran/assets/src_types_TS类型.md.BhD28OW7.js",
"/ran/assets/src_article_design_mode.md.Bdwxnd7q.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_sort_merge_index.md.DBbJWEeR.js",
"/ran/assets/src_article_typescript_pattern.md.CammNTR6.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranui_loading_index.md.B0ePR4Dn.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.D62o46JF.lean.js",
"/ran/assets/cn_src_types_TS类型.md.CZFSdhP2.js",
"/ran/assets/cn_src_ranui_popover_index.md.UlnjmATk.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_file_write_file.md.DF2EgE9w.lean.js",
"/ran/assets/src_types_类型运算.md.2BMSGgKb.lean.js",
"/ran/assets/src_ranui_button_index.md.tE-l7F8S.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_file_read_dir.md.xIB3tl5M.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.T-krbS74.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.CIM9-as9.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DVli328v.js",
"/ran/assets/cn_index.md.C51wmmsr.js",
"/ran/assets/src_ranui_popover_index.md.vjTKc5fX.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B7JpLJLa.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B_oAW6ie.js",
"/ran/assets/cn_src_article_babel.md.C1-LJ9RT.js",
"/ran/assets/src_ranuts_utils_task.md.MyAe2Cvp.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CTRrF1v4.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CcjggxMu.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.B-hYjXic.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DVli328v.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.59gTmmNy.lean.js",
"/ran/assets/src_types_TS类型.md.BhD28OW7.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.D7xURF0W.js",
"/ran/assets/src_article_sort_select_index.md.C8EA3lpe.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DgHQ5aWl.js",
"/ran/assets/cn_src_types_模式匹配.md.DKHA_R4q.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranuts_file_append_file.md.BuR3xS2T.js",
"/ran/assets/cn_src_ranuts_index.md.cDV91jOw.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BaEkdFFU.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_system_design.md.B-8KtH0d.js",
"/ran/assets/src_ranui_image_index.md.DtVIrWnJ.js",
"/ran/assets/src_article_bundle.md.BJ6oh9Uc.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.C2xSaedz.js",
"/ran/assets/src_article_imagemin.md.0FgsOhYK.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_sort_select_index.md.CZFFuwSK.js",
"/ran/assets/src_article_sort_count_index.md.HEjSv_Ky.lean.js",
"/ran/assets/src_article_sort_index.md.BdtxKAc2.js",
"/ran/assets/cn_src_ranui_message_index.md.DwXuPI0g.lean.js",
"/ran/assets/src_article_typescript_index.md.D2KYke90.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DdYwaaCz.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Diplds70.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.1wD8QtGk.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranui_checkbox_index.md.Cz7W6HhR.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Cf7RkW14.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BkP54nAO.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.y_c9ICNL.js",
"/ran/assets/cn_index.md.C51wmmsr.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.wXdd_T5u.lean.js",
"/ran/assets/src_ranui_preview_index.md.Bn7PI4Eg.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_mime_type_mime_type.md.Dkv8T0J-.js",
"/ran/assets/src_types_类型运算.md.2BMSGgKb.js",
"/ran/assets/src_ranui_popover_index.md.vjTKc5fX.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CHYlB4zx.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_sort_bubble_index.md.D-gfK9hb.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.VclYirSl.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.D2B0Ly0Q.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.DdYwaaCz.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.D7xURF0W.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_types_类型运算.md.CpJPaDmJ.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_sort_index.md.BdtxKAc2.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CF4ds91_.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_babel.md.C1-LJ9RT.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B_oAW6ie.lean.js",
"/ran/assets/src_ranui_tab_index.md.C3nis4tD.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.9IBFfU9m.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DA23YfuY.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.xIB3tl5M.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Dx17rTki.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranui_button_index.md.DrzJsrJS.js",
"/ran/assets/cn_src_ranui_player_index.md.CpsIuOW4.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.bETTXL55.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CMu_gHfc.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DBM_tFOL.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_article_typescript_calculate.md.CcjggxMu.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BKRJJbb-.js",
"/ran/assets/cn_src_ranui_radar_index.md.VclYirSl.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_progress_index.md.BY4kP0TR.js",
"/ran/assets/src_ranuts_binary_tree_index.md.BBsg0GDa.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DDMoDfig.js",
"/ran/assets/src_ranuts_bundler_index.md.DBM_tFOL.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.CIM9-as9.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BkP54nAO.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_index.md.xpOd0-i7.lean.js",
"/ran/assets/src_article_sort_shell_index.md.CtEUoE2z.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_tabs_index.md.Crwp7D86.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.C6MExfnv.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.CMu_gHfc.js",
"/ran/assets/src_article_typescript_recursion.md.DUi_rW39.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_file_read_file.md.Cb2Dbxag.lean.js",
"/ran/assets/src_ranui_modal_index.md.B92VsoL9.js",
"/ran/assets/index.md.BfZebtDl.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.bETTXL55.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CFnwzS6b.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.D62o46JF.js",
"/ran/assets/cn_src_types_高级类型.md.BruNHXO-.js",
"/ran/assets/src_ranui_index.md.xpOd0-i7.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BaEkdFFU.js",
"/ran/assets/src_types_高级类型.md.Bktno9oi.js",
"/ran/assets/src_article_sort_count_index.md.HEjSv_Ky.js",
"/ran/assets/src_ranui_radar_index.md.BHT-7pzb.js",
"/ran/assets/src_types_模式匹配.md.BsBWZhT0.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B7JpLJLa.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranui_select_index.md.BzUpuzCa.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CHYlB4zx.js",
"/ran/assets/cn_src_note_centos.md.BiyzCcND.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.D5k5PuES.js",
"/ran/assets/src_article_typescript_union_type.md.VkY9bFMj.js",
"/ran/assets/cn_src_types_模式匹配.md.DKHA_R4q.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CfggCKUv.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranui_preview_index.md.DzIUlaRg.lean.js",
"/ran/assets/src_article_sort_radix_index.md.1Kyfb7wm.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_sort_radix_index.md.DVuXb4Bi.lean.js",
"/ran/assets/cn_src_note_docker.md.CeswuNNp.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranui_tab_index.md.C3nis4tD.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.16jpT9NN.lean.js",
"/ran/assets/src_article_typescript_index.md.D2KYke90.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/VPLocalSearchBox.BoOMOC_R.js",
"/ran/assets/chunks/index.CjFtvR4w.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/@localSearchIndexcn.1ARZjASi.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/@localSearchIndexroot.C3zfcnYF.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DtvRDIcb.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/theme.CRj9aRZB.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/cn_src_note_docker.md.CeswuNNp.js",
"/ran/assets/src_ranuts_file_write_file.md.DF2EgE9w.js",
"/ran/assets/cn_src_ranui_modal_index.md.gViSbZ_R.js",
"/ran/assets/src_ranui_checkbox_index.md.Cz7W6HhR.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CTRrF1v4.lean.js",
"/ran/assets/src_ranui_loading_index.md.B0ePR4Dn.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.PSwtK7lG.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_tab_index.md.BxE4QcRx.lean.js",
"/ran/assets/src_article_design_mode.md.Bdwxnd7q.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_utils_format_json.md.C5FXSGBi.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DUi_rW39.lean.js",
"/ran/assets/src_ranuts_index.md.kpJ4u0pd.js",
"/ran/assets/src_ranui_player_index.md.Ba1EoGZd.lean.js",
"/ran/assets/src_ranuts_utils_task.md.MyAe2Cvp.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.y_c9ICNL.lean.js",
"/ran/assets/src_types_高级类型.md.Bktno9oi.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BW8FTDFT.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.C5FXSGBi.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_sort_quick_index.md.BgvKSHaQ.lean.js",
"/ran/assets/src_ranui_progress_index.md.BY4kP0TR.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DfVv0hGi.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_types_模式匹配.md.BsBWZhT0.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_bundler_index.md.C8ht4tGG.lean.js",
"/ran/assets/src_article_babel.md.D-7bjJm2.js",
"/ran/assets/style.zTfaa9RN.css",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranui_icon_index.md.MAkePo6C.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BS833DEe.js",
"/ran/assets/cn_src_article_bundle.md.DjRt0tWh.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_video.md.Bl7J-8ds.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.CFnwzS6b.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_input_index.md.C2xSaedz.lean.js",
"/ran/assets/src_ranui_preview_index.md.Bn7PI4Eg.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DDMoDfig.lean.js",
"/ran/assets/cn_src_article_design_mode.md.C4n7Ereu.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.HxOpVA5X.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.D5k5PuES.lean.js",
"/ran/assets/app.DPI_Dhuf.js",
"/ran/assets/cn_src_article_sort_index.md.DGtIo46F.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.BoQ20aO9.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranuts_utils_get_cookie.md.Vu2s5BOz.js",
"/ran/assets/cn_src_article_sort_index.md.DGtIo46F.js",
"/ran/assets/cn_src_article_video.md.Bl7J-8ds.js",
"/ran/assets/cn_src_ranui_select_index.md.Bnfsmtzi.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.Dx17rTki.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DA23YfuY.lean.js",
"/ran/assets/src_ranui_math_index.md.CNXwmORy.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_player_index.md.Ba1EoGZd.js",
"/ran/assets/src_ranuts_file_read_dir.md.CpqK6FaN.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.RaIUap8g.js",
"/ran/assets/src_ranui_radar_index.md.BHT-7pzb.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_typescript_union_type.md.Ci81visl.js",
"/ran/assets/cn_src_article_sort_select_index.md.CZFFuwSK.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.C6MExfnv.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranuts_utils_task.md.CCECA4_e.lean.js",
"/ran/assets/cn_src_note_centos.md.BiyzCcND.js",
"/ran/assets/src_article_sort_insert_index.md.CA9dLxvJ.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.duV-IXZT.js",
"/ran/assets/src_ranui_input_index.md.oHo1kN0S.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_design_mode.md.C4n7Ereu.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CPATfHNA.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_button_index.md.tE-l7F8S.js",
"/ran/assets/cn_src_note_ubuntu.md.Diplds70.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.BxE4QcRx.js",
"/ran/assets/src_article_sort_merge_index.md.DBbJWEeR.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_typescript_union_type.md.Ci81visl.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/sw1742482186.js",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1742482186";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



