const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_note_docker.md.CaS5j7ZV.lean.js",
"/ran/assets/src_article_imagemin.md.D3BgXweN.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_sort_radix_index.md.E0CTuSSz.js",
"/ran/assets/src_article_sort_shell_index.md.Du05VXY8.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_bundler_index.md.Cd3AVpyL.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_merge_index.md.CZ4fpPcU.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BmqXD49X.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranuts_utils_filter_obj.md.CrsxmWhp.lean.js",
"/ran/assets/src_types_高级类型.md.wDiENn-Z.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DxF5K5eI.lean.js",
"/ran/assets/src_ranui_index.md.DcpTNtV9.js",
"/ran/assets/src_ranui_checkbox_index.md.Mmh-zSl0.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.pyxwmU3o.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_math_linear_algebra.md.C_aqKMrK.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.DjtF5Ff7.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.B3gSReA_.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_doc_preview.md.piLHkhMH.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.B4hF64yP.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DDKu7-3n.js",
"/ran/assets/src_article_sort_count_index.md.qiPwZEWW.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.BJDvJxD_.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_article_typescript_calculate.md.Dee8YjGk.lean.js",
"/ran/assets/src_article_functional_programming.md.as4ZLPL1.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CA1Eyxqb.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.GNsr9FsY.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_types_类型运算.md.HOQXqGdk.lean.js",
"/ran/assets/cn_src_ranui_index.md.DaoBoxNM.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranuts_file_write_file.md.CA1Eyxqb.js",
"/ran/assets/src_ranui_player_index.md.mk_a-syq.js",
"/ran/assets/cn_src_article_sort_count_index.md.zMqJ4uwC.lean.js",
"/ran/assets/app.DSHTkuNZ.js",
"/ran/assets/cn_src_article_visual.md.BoaB5KU6.js",
"/ran/assets/src_types_模式匹配.md.ChDIIizY.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.jnLL5v42.js",
"/ran/assets/src_types_类型运算.md.BuTg1Onf.js",
"/ran/assets/src_article_sort_bucket_index.md.DHPjG8Wn.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Dx9QK_XV.js",
"/ran/assets/src_article_sort_count_index.md.qiPwZEWW.js",
"/ran/assets/cn_src_ranui_popover_index.md.CLtsLuPC.js",
"/ran/assets/cn_src_ranuts_index.md.DreZb6Xy.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.5aJLNns8.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranuts_binary_tree_index.md.DdD0W6LN.js",
"/ran/assets/cn_src_article_system_design.md.CTfNmm-J.lean.js",
"/ran/assets/cn_src_article_bundle.md.C-KLhJvq.js",
"/ran/assets/src_article_typescript_index.md.DNxFSKE0.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CrsxmWhp.js",
"/ran/assets/cn_src_article_typescript_pattern.md.kMP9MtV7.js",
"/ran/assets/cn_src_article_sort_radix_index.md.E0CTuSSz.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CbuGoH0O.js",
"/ran/assets/src_article_sort_radix_index.md.DvXeuNS7.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Mmh-zSl0.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_javascript_dom_load.md.Di6qcs_e.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_article_typescript_index.md.BtIA8RxL.js",
"/ran/assets/cn_src_article_sort_insert_index.md.B0Eb5OYO.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CD-RGd4K.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DGcP_ZND.js",
"/ran/assets/src_article_typescript_union_type.md.DUpLMoHh.js",
"/ran/assets/src_ranuts_utils_task.md.DxSHpv3b.lean.js",
"/ran/assets/index.md.Ccp41rqs.lean.js",
"/ran/assets/src_ranui_modal_index.md.Svg2U5Z0.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CiTkwalm.lean.js",
"/ran/assets/src_ranui_progress_index.md.Ccc64Vwa.js",
"/ran/assets/src_ranui_input_index.md.CAVmhef9.js",
"/ran/assets/cn_src_article_typescript_index.md.BtIA8RxL.lean.js",
"/ran/assets/src_article_sort_insert_index.md.aKOiChOe.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_index.md.CEVOLwbc.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CI_hELTF.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C7-9-ob0.lean.js",
"/ran/assets/cn_src_ranui_index.md.DaoBoxNM.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DDKu7-3n.lean.js",
"/ran/assets/src_article_functional_programming.md.as4ZLPL1.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CD-RGd4K.js",
"/ran/assets/src_types_TS类型.md.5G4CMNDt.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Bw2j3TW_.js",
"/ran/assets/src_article_sort_shell_index.md.Du05VXY8.lean.js",
"/ran/assets/cn_src_note_centos.md.C12VIRpl.js",
"/ran/assets/src_ranui_select_index.md.D_kDTT5S.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Db6jlQp_.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DvXeuNS7.js",
"/ran/assets/cn_src_article_imagemin.md.DTEXm7pu.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CkieqT5m.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranui_loading_index.md.CbSjX4iT.lean.js",
"/ran/assets/src_article_sort_insert_index.md.aKOiChOe.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CR65TxtZ.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DOSaWBwG.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.rHXAE7Ip.js",
"/ran/assets/cn_src_ranui_button_index.md.CjC45WuS.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BmWUuG6n.js",
"/ran/assets/cn_src_ranui_tabs_index.md.5aJLNns8.js",
"/ran/assets/cn_src_types_模式匹配.md.DjtF5Ff7.lean.js",
"/ran/assets/cn_src_types_高级类型.md.CyrCRbdb.js",
"/ran/assets/src_ranui_skeleton_index.md.CrONi6tw.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BWkO4WIM.lean.js",
"/ran/assets/src_ranui_loading_index.md.CbSjX4iT.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.DdD0W6LN.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.tZ9Qc-LF.js",
"/ran/assets/cn_src_article_typescript_pattern.md.kMP9MtV7.lean.js",
"/ran/assets/cn_src_types_TS类型.md.CjDS0QQU.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Bw2j3TW_.lean.js",
"/ran/assets/src_ranuts_index.md.8yUMTMPG.js",
"/ran/assets/cn_src_ranuts_index.md.DreZb6Xy.js",
"/ran/assets/src_article_typescript_reconstruction.md.fuLTeIwy.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranuts_file_read_dir.md.BZio46sq.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_heap_index.md.BMOkVhzP.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_article_design_mode.md.D_dktEiW.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_design_mode.md.D_dktEiW.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CkieqT5m.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.rHXAE7Ip.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_index.md.BKekGLMb.lean.js",
"/ran/assets/cn_src_article_system_design.md.CTfNmm-J.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_sort_heap_index.md.DAlCGyNP.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.f7YGnx4D.lean.js",
"/ran/assets/cn_src_article_babel.md.BY9s_sHa.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.DGcP_ZND.lean.js",
"/ran/assets/src_ranui_radar_index.md.n9iUi5iz.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.B0Eb5OYO.js",
"/ran/assets/src_types_TS类型.md.5G4CMNDt.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranui_tab_index.md.BJDvJxD_.lean.js",
"/ran/assets/src_ranui_image_index.md.DbH6rqKB.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.Dw54hXWn.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_sort_quick_index.md.CTZMjW3N.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_sort_select_index.md.B7jtePBO.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CiTkwalm.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.tZ9Qc-LF.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_index.md.DcpTNtV9.lean.js",
"/ran/assets/src_article_typescript_index.md.DNxFSKE0.js",
"/ran/assets/src_ranui_image_index.md.DbH6rqKB.js",
"/ran/assets/cn_src_types_类型运算.md.HOQXqGdk.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BVFFwKmf.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_typescript_recursion.md.n7eYVCy7.js",
"/ran/assets/src_ranui_skeleton_index.md.CrONi6tw.js",
"/ran/assets/src_ranui_select_index.md.D_kDTT5S.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_types_高级类型.md.CyrCRbdb.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_file_file_info.md.3XhRagLL.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.90OgqYmv.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BWkO4WIM.js",
"/ran/assets/src_types_模式匹配.md.ChDIIizY.js",
"/ran/assets/cn_src_ranui_player_index.md.BqQxL3uC.js",
"/ran/assets/src_ranuts_file_watch_file.md.CTonZjHS.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.CTonZjHS.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_functional_programming.md.DYwIPshP.lean.js",
"/ran/assets/src_article_typescript_union_type.md.DUpLMoHh.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.hO7I1At4.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_utils_ocr.md.jnLL5v42.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_append_file.md.GNsr9FsY.js",
"/ran/assets/src_ranuts_file_read_file.md.DdFcFRUM.lean.js",
"/ran/assets/cn_src_article_sort_index.md.pzIyfDTV.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranui_math_index.md.CDIsqte7.lean.js",
"/ran/assets/src_ranui_button_index.md.DHvVLi61.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.DdFcFRUM.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_sort_heap_index.md.DAlCGyNP.js",
"/ran/assets/cn_src_ranui_math_index.md.BncytMSU.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DhY6DVAT.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.f7YGnx4D.js",
"/ran/assets/cn_src_article_typescript_calculate.md.Dw54hXWn.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.DOSaWBwG.js",
"/ran/assets/src_ranui_tab_index.md.e9YSqB6P.lean.js",
"/ran/assets/src_ranui_popover_index.md.B8dsprKy.js",
"/ran/assets/src_ranuts_utils_task.md.DxSHpv3b.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_math_linear_algebra.md.C_aqKMrK.js",
"/ran/assets/src_ranui_progress_index.md.Ccc64Vwa.lean.js",
"/ran/assets/src_ranui_preview_index.md.cM8sX0Yf.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranui_tabs_index.md.CmoS7nXL.js",
"/ran/assets/src_article_sort_index.md.BKekGLMb.js",
"/ran/assets/src_ranui_radar_index.md.n9iUi5iz.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.3XhRagLL.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.VaLbOFIs.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.B3gSReA_.lean.js",
"/ran/assets/src_ranui_input_index.md.CAVmhef9.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.DYwIPshP.js",
"/ran/assets/src_article_sort_quick_index.md.CTZMjW3N.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Cklg11Iu.js",
"/ran/assets/src_article_babel.md.BwTbG3vg.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.zMqJ4uwC.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.DbvF4smn.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_ranui_player_index.md.BqQxL3uC.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Bly27UG2.lean.js",
"/ran/assets/index.md.Ccp41rqs.js",
"/ran/assets/cn_src_ranui_progress_index.md.CCuojTTT.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DbvF4smn.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_article_typescript_pattern.md.CiYmnk8P.lean.js",
"/ran/assets/src_ranuts_index.md.8yUMTMPG.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DlCIgMjW.js",
"/ran/assets/src_ranuts_file_append_file.md.QpToDRIr.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.hO7I1At4.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_ranui_preview_index.md.B4ZqRnmS.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.pyxwmU3o.js",
"/ran/assets/src_ranui_message_index.md.zKqNP4-H.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DlCIgMjW.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.90OgqYmv.lean.js",
"/ran/assets/src_ranui_icon_index.md.CR4VWmcG.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.B8R5QfKI.js",
"/ran/assets/src_ranui_math_index.md.CDIsqte7.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DZHtmYdA.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_loading_index.md.C5hLKWuj.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Biu4B4uW.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BY4CUC_N.lean.js",
"/ran/assets/src_ranui_tab_index.md.e9YSqB6P.js",
"/ran/assets/src_ranui_player_index.md.mk_a-syq.lean.js",
"/ran/assets/src_article_design_mode.md.Dx5G32ng.lean.js",
"/ran/assets/cn_index.md.CEVOLwbc.lean.js",
"/ran/assets/cn_src_note_centos.md.C12VIRpl.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BmWUuG6n.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_design_mode.md.Dx5G32ng.js",
"/ran/assets/cn_src_ranui_progress_index.md.CCuojTTT.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CWYQsp_j.js",
"/ran/assets/src_ranui_button_index.md.DHvVLi61.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranui_loading_index.md.C5hLKWuj.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DBRnq8w9.lean.js",
"/ran/assets/cn_src_article_video.md.Boz_VeKr.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.q1ydDfpU.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_article_visual.md.BoaB5KU6.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BkhScs0F.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranuts_file_file_info.md.B4hF64yP.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DBRnq8w9.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_types_类型运算.md.BuTg1Onf.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Cklg11Iu.lean.js",
"/ran/assets/src_article_bundle.md.BthYEpQz.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.DhY6DVAT.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_types_TS类型.md.CjDS0QQU.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Db6jlQp_.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index.CjFtvR4w.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/theme.CmwYdiXV.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DtvRDIcb.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/VPLocalSearchBox.WNKWjPk9.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/@localSearchIndexcn.DBBsy-Pb.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/@localSearchIndexroot.CqjpAILE.js",
"/ran/assets/src_ranuts_utils_format_json.md.6ulW_1Wg.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.Bly27UG2.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_button_index.md.CjC45WuS.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_note_docker.md.CaS5j7ZV.js",
"/ran/assets/cn_src_article_video.md.Boz_VeKr.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.DHPjG8Wn.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.Di6qcs_e.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CmoS7nXL.lean.js",
"/ran/assets/src_ranui_preview_index.md.cM8sX0Yf.lean.js",
"/ran/assets/src_article_bundle.md.BthYEpQz.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.piLHkhMH.js",
"/ran/assets/src_article_sort_bubble_index.md.Ce9scwB4.js",
"/ran/assets/cn_src_article_sort_select_index.md.BdF9QFJb.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CWYQsp_j.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CR65TxtZ.js",
"/ran/assets/cn_src_ranui_image_index.md.BY4CUC_N.js",
"/ran/assets/cn_src_ranui_math_index.md.BncytMSU.lean.js",
"/ran/assets/cn_src_article_sort_index.md.pzIyfDTV.js",
"/ran/assets/cn_src_article_typescript_union_type.md.C--P3Zue.lean.js",
"/ran/assets/src_types_高级类型.md.wDiENn-Z.js",
"/ran/assets/src_ranui_icon_index.md.CR4VWmcG.js",
"/ran/assets/cn_src_ranui_popover_index.md.CLtsLuPC.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BkhScs0F.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_file_write_file.md.VaLbOFIs.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.Ce9scwB4.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CZ4fpPcU.lean.js",
"/ran/assets/src_article_sort_select_index.md.B7jtePBO.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_article_imagemin.md.D3BgXweN.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.BiPW6YH2.js",
"/ran/assets/cn_src_ranui_icon_index.md.B8R5QfKI.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_file_read_file.md.DxF5K5eI.js",
"/ran/assets/cn_src_article_sort_select_index.md.BdF9QFJb.lean.js",
"/ran/assets/style.zTfaa9RN.css",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.q1ydDfpU.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CI_hELTF.js",
"/ran/assets/cn_src_ranui_modal_index.md.BiPW6YH2.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.fuLTeIwy.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.B4ZqRnmS.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.Biu4B4uW.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.C--P3Zue.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_ranuts_file_append_file.md.QpToDRIr.lean.js",
"/ran/assets/src_article_typescript_calculate.md.Dee8YjGk.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranui_message_index.md.zKqNP4-H.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C7-9-ob0.js",
"/ran/assets/src_ranuts_utils_format_json.md.6ulW_1Wg.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.BmqXD49X.js",
"/ran/assets/src_article_typescript_recursion.md.n7eYVCy7.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_sort_merge_index.md.BVFFwKmf.js",
"/ran/assets/src_ranui_modal_index.md.Svg2U5Z0.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DZHtmYdA.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_ranuts_utils_task.md.Dx9QK_XV.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_typescript_pattern.md.CiYmnk8P.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_bundle.md.C-KLhJvq.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.zohbfB89.js",
"/ran/assets/cn_src_article_babel.md.BY9s_sHa.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_select_index.md.CbuGoH0O.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DTEXm7pu.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_bundler_index.md.Cd3AVpyL.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.zohbfB89.lean.js",
"/ran/assets/src_ranui_popover_index.md.B8dsprKy.lean.js",
"/ran/assets/src_article_babel.md.BwTbG3vg.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranuts_file_read_dir.md.BZio46sq.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BMOkVhzP.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1742487008.js",
];
const VERSION = "1742487008";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



