const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/cn/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/404.html",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/example.m3u8",
"/ran/icon_96.png",
"/ran/manifest.json",
"/ran/icon_48.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/icon_72.png",
"/ran/icon_144.png",
"/ran/index.html",
"/ran/sw1718465114.js",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/en_b52b4a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/en_8e7817f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_1d2a8f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fc196ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5b9af99.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_51f248e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6655e03.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_a56cec5.pf_fragment",
"/ran/pagefind/fragment/en_786dd1d.pf_fragment",
"/ran/pagefind/fragment/en_d792b8c.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/en_c84c5e7.pf_fragment",
"/ran/pagefind/fragment/en_31bb7a6.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_45694f5.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1becf92.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2f9227.pf_fragment",
"/ran/pagefind/fragment/en_4873c44.pf_fragment",
"/ran/pagefind/fragment/zh-cn_89d34e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_976d864.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/zh-cn_279c02b.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f6f6ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65103c8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_d810afe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_c9c7c59.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_75d5dcb.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bf95b6d.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_7a4ca4f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_ca77806.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cab01af.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d9642ae.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/en_5f9a7eb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c37ca1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_77ed13c.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7ba21c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_77e0291.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_216410c.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_2942c3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_41cce7e.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/index/en_a5f290c.pf_index",
"/ran/pagefind/index/zh-cn_bbd3785.pf_index",
"/ran/pagefind/index/zh-cn_56e8f9b.pf_index",
"/ran/pagefind/index/en_8cf7197.pf_index",
"/ran/pagefind/index/zh-cn_ea4f908.pf_index",
"/ran/pagefind/index/en_ef88261.pf_index",
"/ran/pagefind/index/zh-cn_bff3193.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.en_b63ee56576.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind.zh-cn_f716a3ab6082e.pf_meta",
"/ran/assets/src_article_sort_count_index.md.w4RLwXn9.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CAVZl7Y_.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranui_radar_index.md.GxDhXkZp.lean.js",
"/ran/assets/src_types_高级类型.md.LlJLP5Xt.js",
"/ran/assets/index.md.C8HNx4o2.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.hpRpK1e-.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.4Bw7o9gz.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_file_readFile.md.DhPVF-ny.lean.js",
"/ran/assets/src_ranui_radar_index.md.COv63p04.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranui_modal_index.md.4HPdxNqn.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.yzQtKItz.lean.js",
"/ran/assets/src_article_typescript_unionType.md.BzjMOVr3.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.IB7DsYA9.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_mode_subscribe.md.C2hm_ZHQ.js",
"/ran/assets/src_article_typescript_calculate.md.DKB_SdSe.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.OKDIuogZ.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.Bqr-llFV.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.DweRDYVm.js",
"/ran/assets/src_types_TS类型.md.WQNMnEan.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DtBt-QXa.js",
"/ran/assets/src_ranuts_binaryTree_index.md.pbCkU2A8.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_types_类型运算.md.Chd37ewS.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.CZERQJfK.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DjbHSoh7.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_radix_index.md.DoO_dlEU.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CYvxlVzY.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BGrfwCH6.lean.js",
"/ran/assets/src_ranuts_index.md.DjBrNF7z.js",
"/ran/assets/src_article_javascript_domLoad.md.RxXZy0wx.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_typescript_recursion.md.CfmWNeDU.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CH4gut2l.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.EeP9KSKl.js",
"/ran/assets/cn_src_ranui_loading_index.md.CUZUcX8g.js",
"/ran/assets/src_ranuts_file_fileInfo.md.Ca9UhuOd.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.prqt8F2o.js",
"/ran/assets/src_article_typescript_index.md.Dg06BwYz.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Do9kclvb.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_article_sort_merge_index.md.BGn-dHK0.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.Cnawfdke.js",
"/ran/assets/src_ranui_icon_index.md.D6IVzw1H.js",
"/ran/assets/cn_src_ranui_tab_index.md.DrVzTwbH.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DTpyU90y.lean.js",
"/ran/assets/src_types_TS类型.md.WQNMnEan.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.COoQ8rwl.js",
"/ran/assets/src_article_javascript_domLoad.md.RxXZy0wx.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DwK0sySO.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_imagemin.md.11QMxfS4.js",
"/ran/assets/cn_src_article_sort_merge_index.md.eK7crvq-.js",
"/ran/assets/cn_index.md.CKclqiI1.js",
"/ran/assets/app.Dlib4JPs.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DsPfHHGv.js",
"/ran/assets/src_article_functionalProgramming.md.BT2UdUG1.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.CUZUcX8g.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.DTpyU90y.js",
"/ran/assets/src_article_sort_index.md.CQmfEO7W.lean.js",
"/ran/assets/src_article_sort_index.md.CQmfEO7W.js",
"/ran/assets/src_ranuts_bundler_index.md.Bqr-llFV.lean.js",
"/ran/assets/src_ranui_tabs_index.md.NPNWZOGP.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.TxI4dE7B.js",
"/ran/assets/src_article_typescript_recursion.md.CfmWNeDU.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.B--byXa2.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_tabs_index.md.Ddtv51mr.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_sort_index.md.CZgp_Eeu.js",
"/ran/assets/src_ranuts_utils_task.md.9Ime0BNN.lean.js",
"/ran/assets/src_ranui_icon_index.md.D6IVzw1H.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BBu4zkWN.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_article_designMode.md.DiWalWJY.js",
"/ran/assets/src_ranui_radar_index.md.COv63p04.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.Bq_c86LF.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CxmmMKku.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.IB7DsYA9.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.WJt-3w2X.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C-VG2im0.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Byef8wZI.lean.js",
"/ran/assets/cn_src_types_高级类型.md.D3O-OvOF.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_imagemin.md.nt2VHlF_.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DrVzTwbH.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_message_index.md.BOs49XaL.js",
"/ran/assets/cn_src_types_类型运算.md.D6N5bN6q.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.Byef8wZI.js",
"/ran/assets/cn_src_ranuts_index.md.BoTNc2jj.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_article_babel.md.DJ9P1WT8.js",
"/ran/assets/src_ranuts_file_appendFile.md.lJTgHv-o.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.CeDHtGVS.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CeDHtGVS.js",
"/ran/assets/src_article_sort_insert_index.md.mpyuQOw9.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DoO_dlEU.lean.js",
"/ran/assets/src_article_typescript_pattern.md.FbU37Til.js",
"/ran/assets/src_ranui_modal_index.md.4HPdxNqn.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.Bs3Ab_Oy.js",
"/ran/assets/src_article_typescript_index.md.Dg06BwYz.js",
"/ran/assets/src_article_bundle.md.DSNtD-N8.lean.js",
"/ran/assets/src_ranui_index.md.uxOtMtph.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranui_loading_index.md.DPmgJNuw.js",
"/ran/assets/src_types_模式匹配.md.CweO1bo4.lean.js",
"/ran/assets/src_ranui_loading_index.md.DPmgJNuw.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Bs9lQ1VT.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.hpRpK1e-.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DsPfHHGv.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/index.md.C8HNx4o2.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CWZjSGBs.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.ZcQMzy1O.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_imagemin.md.11QMxfS4.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CX7rCMil.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.9w2fpoEh.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C8_Kgsoy.js",
"/ran/assets/src_ranui_image_index.md.CuV_uPiY.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C-VG2im0.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranui_player_index.md.CPdtzicz.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.Bq_c86LF.js",
"/ran/assets/src_ranuts_file_readFile.md.DhPVF-ny.js",
"/ran/assets/cn_src_ranui_player_index.md.8dgylXY5.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.C8_Kgsoy.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CYie7tE-.js",
"/ran/assets/src_article_babel.md.DxZCmN3S.lean.js",
"/ran/assets/src_article_typescript_unionType.md.BzjMOVr3.js",
"/ran/assets/src_article_sort_shell_index.md.CbX0XO4f.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.gpxwpgl8.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BYZMIxvZ.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_fileInfo.md.Ca9UhuOd.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BRyJTeOs.lean.js",
"/ran/assets/cn_src_article_babel.md.DJ9P1WT8.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.CZERQJfK.js",
"/ran/assets/src_ranuts_index.md.DjBrNF7z.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.r7E8Rhvr.js",
"/ran/assets/cn_src_ranui_player_index.md.8dgylXY5.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_select_index.md.CCqni0Jr.lean.js",
"/ran/assets/src_ranui_input_index.md.CiGoXnss.js",
"/ran/assets/cn_src_ranuts_index.md.BoTNc2jj.js",
"/ran/assets/src_ranuts_file_writeFile.md.DJJxAkxz.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.PPe_eu3A.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CFtHk-jL.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.Bqv0-WN-.lean.js",
"/ran/assets/cn_index.md.CKclqiI1.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BwppleZB.js",
"/ran/assets/src_ranui_input_index.md.CiGoXnss.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DwK0sySO.lean.js",
"/ran/assets/src_article_typescript_pattern.md.FbU37Til.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_popover_index.md.BdhY8IP6.js",
"/ran/assets/cn_src_ranui_progress_index.md.Cnawfdke.lean.js",
"/ran/assets/src_article_sort_insert_index.md.mpyuQOw9.js",
"/ran/assets/src_article_sort_bubble_index.md.BNCb-4vu.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.a6zbbBH-.js",
"/ran/assets/src_article_babel.md.DxZCmN3S.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DbwI3CwZ.js",
"/ran/assets/src_ranuts_file_readDir.md.BU0HdDa1.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BXM-7_RF.lean.js",
"/ran/assets/src_ranui_message_index.md.BOs49XaL.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DbwI3CwZ.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Q4JGFAJo.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_checkbox_index.md.Ds0bffB2.js",
"/ran/assets/src_article_sort_bubble_index.md.BNCb-4vu.js",
"/ran/assets/cn_src_ranui_input_index.md.DjbHSoh7.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BGrfwCH6.js",
"/ran/assets/cn_src_types_类型运算.md.D6N5bN6q.js",
"/ran/assets/src_article_sort_select_index.md.u2633RNq.js",
"/ran/assets/src_ranui_player_index.md.CPdtzicz.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Ds0bffB2.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.a6zbbBH-.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CfPDGRpX.js",
"/ran/assets/src_ranuts_binaryTree_index.md.pbCkU2A8.js",
"/ran/assets/cn_src_types_TS类型.md.Yjt30_LN.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.B-Blqpo_.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C2hm_ZHQ.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_sort_count_index.md.w4RLwXn9.js",
"/ran/assets/src_ranui_skeleton_index.md.CfPDGRpX.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BBWooU6E.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.DDoC6pZh.lean.js",
"/ran/assets/src_ranui_tab_index.md.D-dbVgmM.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.CX7rCMil.js",
"/ran/assets/cn_src_ranui_button_index.md.EeP9KSKl.lean.js",
"/ran/assets/src_ranui_image_index.md.CuV_uPiY.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.z5_IjhAQ.js",
"/ran/assets/src_ranui_tabs_index.md.NPNWZOGP.js",
"/ran/assets/src_article_designMode.md.DMcOQIB4.js",
"/ran/assets/src_ranuts_file_writeFile.md.DJJxAkxz.js",
"/ran/assets/src_types_模式匹配.md.CweO1bo4.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BGpQtrGA.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.DDoC6pZh.js",
"/ran/assets/src_ranui_button_index.md.CkyUwFfa.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_merge_index.md.BGn-dHK0.js",
"/ran/assets/src_ranui_preview_index.md.DAi1tno5.lean.js",
"/ran/assets/src_types_高级类型.md.LlJLP5Xt.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.eK7crvq-.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_index.md.0HL2F_dZ.lean.js",
"/ran/assets/src_article_imagemin.md.nt2VHlF_.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CYvxlVzY.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.9w2fpoEh.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Ddtv51mr.lean.js",
"/ran/assets/src_ranuts_utils_task.md.9Ime0BNN.js",
"/ran/assets/cn_src_ranui_icon_index.md.z5_IjhAQ.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DKB_SdSe.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_sort_shell_index.md.CbX0XO4f.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_javascript_domLoad.md.DweRDYVm.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CAVZl7Y_.js",
"/ran/assets/src_ranui_button_index.md.CkyUwFfa.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CH4gut2l.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.WJt-3w2X.lean.js",
"/ran/assets/src_ranui_tab_index.md.D-dbVgmM.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BYZMIxvZ.js",
"/ran/assets/src_article_sort_bucket_index.md.BXpLpjuS.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.BBWooU6E.js",
"/ran/assets/cn_src_article_sort_index.md.CZgp_Eeu.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BBu4zkWN.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.yzQtKItz.js",
"/ran/assets/src_article_designMode.md.DMcOQIB4.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_popover_index.md.BdhY8IP6.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_sort_quick_index.md.Do9kclvb.lean.js",
"/ran/assets/src_ranui_index.md.uxOtMtph.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.r7E8Rhvr.lean.js",
"/ran/assets/cn_src_ranui_index.md.0HL2F_dZ.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_sort_heap_index.md.BXM-7_RF.js",
"/ran/assets/src_ranui_select_index.md.CCqni0Jr.js",
"/ran/assets/cn_src_types_TS类型.md.Yjt30_LN.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranui_message_index.md.CFtHk-jL.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.Bs9lQ1VT.js",
"/ran/assets/src_ranui_progress_index.md.DpgOaz7b.js",
"/ran/assets/src_ranuts_file_watchFile.md.C3E--gZw.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_bundle.md.Dufowpol.js",
"/ran/assets/src_types_类型运算.md.Chd37ewS.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.ZcQMzy1O.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_file_readFile.md.DtBt-QXa.lean.js",
"/ran/assets/src_article_sort_select_index.md.u2633RNq.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BXpLpjuS.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.GxDhXkZp.js",
"/ran/assets/cn_src_article_bundle.md.Dufowpol.lean.js",
"/ran/assets/style.DxMSLhj5.css",
"/ran/assets/cn_src_ranui_popover_index.md.OKDIuogZ.js",
"/ran/assets/cn_src_types_高级类型.md.D3O-OvOF.js",
"/ran/assets/cn_src_article_designMode.md.DiWalWJY.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.prqt8F2o.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.tIwjdUhA.js",
"/ran/assets/src_article_typescript_reconstruction.md.Bs3Ab_Oy.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.tIwjdUhA.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/framework.BZEwi-oL.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/index.tKTBWNy8.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/theme.Bbg9ip_e.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/index-CGEx9VOA.kxSojsaB.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/index-DtOAyqJt.DT2avMAZ.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CYB0uYMT.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/src_ranui_preview_index.md.DAi1tno5.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.COoQ8rwl.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.lJTgHv-o.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_bubble_index.md.B-_byGKo.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranuts_utils_getCookie.md.B--byXa2.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_ranui_preview_index.md.BRyJTeOs.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.B-Blqpo_.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.gpxwpgl8.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_typescript_calculate.md.BehuE_1A.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.Bqv0-WN-.js",
"/ran/assets/src_article_functionalProgramming.md.BT2UdUG1.js",
"/ran/assets/src_article_bundle.md.DSNtD-N8.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.B-_byGKo.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.4Bw7o9gz.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.BU72q3fA.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.TxI4dE7B.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.PPe_eu3A.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_astParse_tokenizer.md.BU72q3fA.js",
"/ran/assets/src_ranuts_file_readDir.md.BU0HdDa1.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Q4JGFAJo.js",
"/ran/assets/src_ranui_progress_index.md.DpgOaz7b.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.C3E--gZw.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BwppleZB.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CWZjSGBs.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BGpQtrGA.js",
"/ran/assets/src_article_sort_quick_index.md.CxmmMKku.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BehuE_1A.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_article_sort_select_index.md.CYie7tE-.lean.js",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/hashmap.json",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/designMode.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/functionalProgramming.html",
"/ran/icon.png",
];
const VERSION = "1718465114";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



