const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/hashmap.json",
"/ran/index.html",
"/ran/icon_168.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/icon_96.png",
"/ran/manifest.json",
"/ran/404.html",
"/ran/screenshots_748x1340.jpg",
"/ran/icon.png",
"/ran/icon_144.png",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D_6AHj0O.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranuts_file_fileInfo.md.GDtoFXIC.js",
"/ran/assets/cn_src_article_designMode.md.1GV_5LM4.lean.js",
"/ran/assets/src_article_bundle.md.D9KCB6vB.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_utils_ocr.md.lw04gmmW.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranuts_file_writeFile.md.AFuWB7T8.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.B0fchGpy.js",
"/ran/assets/src_ranui_icon_index.md.DvvhvscP.js",
"/ran/assets/src_article_bundle.md.D9KCB6vB.lean.js",
"/ran/assets/src_ranui_player_index.md.DArFQZJL.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranui_checkbox_index.md.DZqaENra.js",
"/ran/assets/src_article_astParse_tokenizer.md.C3DjP8GE.lean.js",
"/ran/assets/src_article_typescript_index.md.CL-3f6Rg.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CFGXvqCA.js",
"/ran/assets/cn_src_ranui_button_index.md.Drxp8I9I.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranuts_utils_ocr.md.D2miG0cW.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DGglrmKf.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.8qBVn1fD.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.C0QWD-zv.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DO_50ng9.lean.js",
"/ran/assets/cn_src_article_bundle.md.5QC00bQP.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Dvibk72V.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DuuwQFvY.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.D_JiiPQq.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.BOfIIZcF.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.AFuWB7T8.js",
"/ran/assets/src_ranui_radar_index.md.CHB5adkV.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DrAPlV1q.lean.js",
"/ran/assets/src_types_高级类型.md.BFR9e3NA.lean.js",
"/ran/assets/src_article_sort_heap_index.md.CjR7l3IQ.js",
"/ran/assets/cn_src_types_模式匹配.md.D0k01RHi.lean.js",
"/ran/assets/src_article_typescript_pattern.md.B4JC53l6.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.BPh_ahIB.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DMsrTC-a.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_skeleton_index.md.B9T9_qzq.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.Cx0OvUNN.js",
"/ran/assets/cn_src_ranui_modal_index.md.CFGXvqCA.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BQKX9KeJ.js",
"/ran/assets/src_ranuts_utils_filterObj.md.B4H2c7ki.js",
"/ran/assets/src_ranui_preview_index.md.C17ou3Jr.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranui_modal_index.md.DwLB76MK.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/src_ranuts_utils_task.md.DZ3knGzV.js",
"/ran/assets/cn_src_ranui_index.md.C4ARjuNO.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Gmh0BlmF.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_types_TS类型.md.jdUAAfai.js",
"/ran/assets/src_article_sort_shell_index.md.BlL5DEXD.js",
"/ran/assets/src_article_babel.md.OvNUHIlS.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_sort_merge_index.md.C8RPfU3e.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DgTsznmx.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_note_docker.md.BjQWZUQ1.js",
"/ran/assets/src_ranuts_index.md.CT1AVl_W.js",
"/ran/assets/src_ranuts_file_readFile.md.w-jpGQAa.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CWcp1j2X.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_checkbox_index.md.CNiBkIUS.js",
"/ran/assets/cn_src_note_ubuntu.md.g8ILwA1P.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DWdrFzvK.js",
"/ran/assets/cn_src_ranui_radar_index.md.Q_wVv8sk.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.8qBVn1fD.js",
"/ran/assets/cn_src_ranui_button_index.md.Drxp8I9I.lean.js",
"/ran/assets/src_article_sort_radix_index.md.CHWtAmBh.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_types_TS类型.md.jdUAAfai.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_javascript_domLoad.md.B5x4JjIv.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_article_typescript_unionType.md.CKp_x3vz.lean.js",
"/ran/assets/src_ranui_popover_index.md.Bds-j7kR.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.HnrLyEHb.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.oVEcNcqm.js",
"/ran/assets/app.By-F1flO.js",
"/ran/assets/src_ranuts_file_readDir.md.k3CEmhCC.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DrAPlV1q.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BwwbE4GC.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.mryFP0HF.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CWs7JSe9.lean.js",
"/ran/assets/src_article_typescript_index.md.CL-3f6Rg.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.D6HwzTOC.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_ranuts_file_readDir.md.M38QLohN.js",
"/ran/assets/src_ranui_button_index.md.Bmk5JcH2.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_ranui_icon_index.md.DvvhvscP.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.B4H2c7ki.lean.js",
"/ran/assets/src_article_sort_count_index.md.SkuVfGsz.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_video.md.W7nsmCzp.js",
"/ran/assets/src_article_sort_select_index.md.BQH7dB6Z.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BWza0iEW.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DXvaGeBA.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DQXtf27Q.js",
"/ran/assets/cn_src_types_模式匹配.md.D0k01RHi.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.CNdd1FJ7.js",
"/ran/assets/src_ranuts_utils_ocr.md.D2miG0cW.js",
"/ran/assets/src_article_sort_insert_index.md.DgTsznmx.lean.js",
"/ran/assets/src_article_sort_index.md.D1Qc0d-6.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_sort_heap_index.md.DWdrFzvK.lean.js",
"/ran/assets/cn_src_types_类型运算.md.BEI2IHI7.js",
"/ran/assets/src_article_imagemin.md.DTB6ztBW.js",
"/ran/assets/src_types_模式匹配.md.CIdJrIXP.js",
"/ran/assets/cn_src_article_typescript_unionType.md.WjHBV5dq.js",
"/ran/assets/cn_src_ranui_loading_index.md.Cqok1wOU.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.7IvJAWai.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C4s84_J7.js",
"/ran/assets/cn_src_ranui_popover_index.md.BZLLwMpJ.lean.js",
"/ran/assets/src_ranui_progress_index.md.B_hZKHyj.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_article_sort_merge_index.md.C8RPfU3e.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B3YWH8bN.js",
"/ran/assets/cn_src_article_sort_radix_index.md.C0QWD-zv.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_article_visual.md.CjNSYUuP.js",
"/ran/assets/src_ranui_index.md.ByjWIda5.lean.js",
"/ran/assets/src_types_TS类型.md.C2L4AFjd.lean.js",
"/ran/assets/src_article_typescript_calculate.md.FMFBV68e.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DTzJ9Y1A.js",
"/ran/assets/src_article_typescript_unionType.md.CKp_x3vz.js",
"/ran/assets/src_article_sort_merge_index.md.CkBA4Dhf.js",
"/ran/assets/cn_src_article_typescript_pattern.md.B3PEOXoj.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_calculate.md.FMFBV68e.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.CWocx0VM.lean.js",
"/ran/assets/cn_src_note_centos.md.BNf1rA2I.js",
"/ran/assets/src_ranui_modal_index.md.DwLB76MK.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BrRn0h58.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BnUwNUUZ.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C85ZoMKA.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.YYQ46eRG.js",
"/ran/assets/src_ranui_preview_index.md.C17ou3Jr.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.7IvJAWai.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.BOkX4m3M.lean.js",
"/ran/assets/src_ranui_message_index.md.Bh-JJIuS.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_docPreview.md.DcEmBtUQ.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BlVoI9f3.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CP3kAXPQ.js",
"/ran/assets/src_ranui_image_index.md.DhchqwuH.js",
"/ran/assets/cn_src_ranuts_index.md.BFYkqN-8.js",
"/ran/assets/src_ranuts_file_readDir.md.k3CEmhCC.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_article_javascript_domLoad.md.B5x4JjIv.js",
"/ran/assets/cn_src_ranui_input_index.md.D6qjgx43.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.B9T9_qzq.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.DxafENGS.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DQXtf27Q.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_article_sort_bucket_index.md.DxafENGS.js",
"/ran/assets/src_ranuts_file_fileInfo.md.GDtoFXIC.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Cp5zYNN8.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BwwbE4GC.js",
"/ran/assets/cn_src_ranui_select_index.md.DIaZFk9m.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_sort_quick_index.md.BFbuxKtO.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Dt9rt8c6.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CTVcZjSK.lean.js",
"/ran/assets/src_types_类型运算.md.B5XfzPgy.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C85ZoMKA.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_sort_shell_index.md.BlL5DEXD.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.CNiBkIUS.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CWs7JSe9.js",
"/ran/assets/src_article_sort_select_index.md.BQH7dB6Z.js",
"/ran/assets/src_ranui_progress_index.md.B_hZKHyj.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_article_typescript_reconstruction.md.BrdMJ76t.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_functionalProgramming.md.BdRyO6SV.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_article_astParse_tokenizer.md.C3DjP8GE.js",
"/ran/assets/src_ranui_select_index.md.ydfIhlcr.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CTVcZjSK.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.Cx0OvUNN.lean.js",
"/ran/assets/src_article_sort_count_index.md.SkuVfGsz.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_file_appendFile.md.BjwHcfRP.lean.js",
"/ran/assets/src_article_designMode.md.DTKFMcM0.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_types_高级类型.md.BFR9e3NA.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranui_tabs_index.md.B3YWH8bN.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Cp5zYNN8.js",
"/ran/assets/index.md.BBDJ19r_.lean.js",
"/ran/assets/src_article_sort_heap_index.md.CjR7l3IQ.lean.js",
"/ran/assets/index.md.BBDJ19r_.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C4s84_J7.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BsyspW62.js",
"/ran/assets/cn_src_note_centos.md.BNf1rA2I.lean.js",
"/ran/assets/src_ranui_player_index.md.DArFQZJL.js",
"/ran/assets/cn_src_note_ubuntu.md.g8ILwA1P.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.BrdMJ76t.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_tab_index.md.CTme9ukW.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.lw04gmmW.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.B0fchGpy.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.yEhyIyFO.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CWcp1j2X.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranuts_index.md.CT1AVl_W.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_astParse_tokenizer.md.mryFP0HF.js",
"/ran/assets/src_ranui_select_index.md.ydfIhlcr.js",
"/ran/assets/src_types_类型运算.md.B5XfzPgy.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_sort_index.md.D0mPfRNH.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Dnr2CyoH.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.D6qjgx43.js",
"/ran/assets/cn_src_article_typescript_unionType.md.WjHBV5dq.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BWza0iEW.js",
"/ran/assets/cn_src_article_video.md.W7nsmCzp.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.BjwHcfRP.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BPktc0Fl.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.HnrLyEHb.js",
"/ran/assets/cn_src_types_高级类型.md.BgwfjBDO.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.BrRn0h58.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_sort_index.md.D1Qc0d-6.js",
"/ran/assets/src_ranuts_utils_task.md.DZ3knGzV.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BsyspW62.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_article_functionalProgramming.md.DMsrTC-a.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_systemDesign.md.BPh_ahIB.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_sort_select_index.md.CG_CghlW.js",
"/ran/assets/cn_src_ranui_message_index.md.DKq7QDxn.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_article_sort_index.md.D0mPfRNH.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CP3kAXPQ.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranui_message_index.md.Bh-JJIuS.lean.js",
"/ran/assets/src_article_designMode.md.DTKFMcM0.js",
"/ran/assets/src_ranui_radar_index.md.CHB5adkV.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_input_index.md.4HwlWlTk.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_popover_index.md.BZLLwMpJ.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.B5r-nqlW.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.BnUwNUUZ.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_sort_insert_index.md.Dt9rt8c6.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BHjo511R.lean.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DmWYrN_w.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/index-Co9E57uv.Czqdfb-6.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/index.Dk0BAPAJ.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/framework.BvvoErfm.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/pwa-install.es.m5I_sFSJ.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.vFVhhboz.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index-Ba501-HG.KUGejqxr.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/theme.LQmiANFO.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/cn_src_article_babel.md.ClgUYTkO.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_typescript_recursion.md.DO_50ng9.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BlVoI9f3.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.DGglrmKf.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.1ZNaUerB.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_babel.md.ClgUYTkO.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_sort_count_index.md.YYQ46eRG.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.1ZNaUerB.js",
"/ran/assets/src_article_imagemin.md.DTB6ztBW.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Btx9e9c5.js",
"/ran/assets/src_article_typescript_pattern.md.B4JC53l6.js",
"/ran/assets/src_ranuts_bundler_index.md.NT9ZA6px.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_ranui_math_index.md.CnRzCHaS.js",
"/ran/assets/cn_src_ranui_select_index.md.DIaZFk9m.js",
"/ran/assets/src_ranui_input_index.md.4HwlWlTk.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Q_wVv8sk.js",
"/ran/assets/src_types_TS类型.md.C2L4AFjd.js",
"/ran/assets/cn_src_ranuts_utils_task.md.Dvibk72V.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.M38QLohN.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_note_docker.md.BjQWZUQ1.lean.js",
"/ran/assets/style.ENRbqgO1.css",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_article_sort_radix_index.md.CHWtAmBh.js",
"/ran/assets/src_article_functionalProgramming.md.BdRyO6SV.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BQKX9KeJ.lean.js",
"/ran/assets/src_ranui_button_index.md.Bmk5JcH2.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_image_index.md.BOfIIZcF.js",
"/ran/assets/cn_src_ranui_index.md.C4ARjuNO.js",
"/ran/assets/cn_src_ranui_math_index.md.C4402wiE.js",
"/ran/assets/src_ranui_image_index.md.DhchqwuH.lean.js",
"/ran/assets/cn_src_article_designMode.md.1GV_5LM4.js",
"/ran/assets/cn_src_article_visual.md.CjNSYUuP.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.B3PEOXoj.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DuuwQFvY.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DTzJ9Y1A.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_sort_shell_index.md.Gmh0BlmF.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.D_JiiPQq.js",
"/ran/assets/src_ranui_loading_index.md.B80w_cpA.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_ranui_checkbox_index.md.DZqaENra.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B5r-nqlW.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_ranui_message_index.md.DKq7QDxn.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_babel.md.OvNUHIlS.js",
"/ran/assets/src_ranui_index.md.ByjWIda5.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.D6HwzTOC.js",
"/ran/assets/cn_src_article_imagemin.md.DXvaGeBA.js",
"/ran/assets/src_ranui_tab_index.md.CTme9ukW.js",
"/ran/assets/cn_src_types_类型运算.md.BEI2IHI7.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Cqok1wOU.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Btx9e9c5.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Dnr2CyoH.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_article_typescript_index.md.BOkX4m3M.js",
"/ran/assets/src_article_sort_merge_index.md.CkBA4Dhf.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BEOuePxD.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BHjo511R.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranui_loading_index.md.B80w_cpA.js",
"/ran/assets/src_types_模式匹配.md.CIdJrIXP.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranuts_file_watchFile.md.CWocx0VM.js",
"/ran/assets/src_article_sort_quick_index.md.BFbuxKtO.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.yEhyIyFO.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_sort_select_index.md.CG_CghlW.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BgwfjBDO.js",
"/ran/assets/cn_src_ranuts_index.md.BFYkqN-8.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BEOuePxD.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.NT9ZA6px.lean.js",
"/ran/assets/src_ranui_popover_index.md.Bds-j7kR.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.D_6AHj0O.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.BPktc0Fl.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.w-jpGQAa.lean.js",
"/ran/assets/cn_src_article_docPreview.md.DcEmBtUQ.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CNdd1FJ7.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_article_bundle.md.5QC00bQP.js",
"/ran/assets/src_ranuts_utils_formatJson.md.oVEcNcqm.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranui_math_index.md.CnRzCHaS.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_math_index.md.C4402wiE.lean.js",
"/ran/assets/cn_index.md.TSuB4k_G.js",
"/ran/assets/cn_index.md.TSuB4k_G.lean.js",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/article/designMode.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/favicon.ico",
"/ran/cn/index.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/icon_48.png",
"/ran/home.svg",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_72.png",
"/ran/icon_192.png",
"/ran/sw1726478824.js",
"/ran/pagefind/pagefind.zh-cn_81a6a78ee4397.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.en_2d70772b75.pf_meta",
"/ran/pagefind/fragment/zh-cn_67d6c7a.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d98338a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac92f78.pf_fragment",
"/ran/pagefind/fragment/en_aab3547.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ad77d75.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7edffe.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e64f93e.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_44fa7df.pf_fragment",
"/ran/pagefind/fragment/en_dccebd7.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_82b59c2.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ec79f02.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2e89f3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5190b59.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7b2564.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7d7b75a.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b2e449c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f9c4333.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_489c27d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3e43b1f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a3cd5f.pf_fragment",
"/ran/pagefind/fragment/en_3541bef.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bc27649.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d32fcee.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/en_af4a67a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_99e62b8.pf_fragment",
"/ran/pagefind/fragment/en_edda142.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_32113cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bb9206.pf_fragment",
"/ran/pagefind/fragment/en_6b4c4a9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e88bc3f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_964a4fd.pf_fragment",
"/ran/pagefind/fragment/en_78f477e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8c8e8be.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c82f3b2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66f42e8.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_af6e5c4.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c1151c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_217f9f1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ef213d.pf_fragment",
"/ran/pagefind/fragment/en_324b2ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95fa787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8dcd37a.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5042f4c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_715eacf.pf_fragment",
"/ran/pagefind/fragment/en_63f4b5c.pf_fragment",
"/ran/pagefind/fragment/en_1f28c1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_622d568.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5919.pf_fragment",
"/ran/pagefind/fragment/en_f575e71.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d1b782.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f3328b.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ad6344.pf_fragment",
"/ran/pagefind/fragment/en_16d01f2.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/en_6e7d47a.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2bc07af.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20933c3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a1e1243.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_83d923f.pf_fragment",
"/ran/pagefind/fragment/en_70bee3b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_88af4d0.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c999918.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3de2e5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ca356d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_50313a9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f7dcce8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5df12ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3fb29d3.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f260254.pf_fragment",
"/ran/pagefind/fragment/en_34b032a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51dafe6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_75a264c.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59bdbd3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e347438.pf_fragment",
"/ran/pagefind/fragment/zh-cn_677ff04.pf_fragment",
"/ran/pagefind/fragment/zh-cn_69610a7.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a5f5d9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f379427.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bab657.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_58279de.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f09c929.pf_fragment",
"/ran/pagefind/fragment/en_7fffa0e.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/index/en_4e472e0.pf_index",
"/ran/pagefind/index/en_6af7abf.pf_index",
"/ran/pagefind/index/zh-cn_629cfe2.pf_index",
"/ran/pagefind/index/zh-cn_c7671ec.pf_index",
"/ran/pagefind/index/zh-cn_db15dcf.pf_index",
"/ran/pagefind/index/zh-cn_6e146a8.pf_index",
"/ran/pagefind/index/zh-cn_f5ed6e5.pf_index",
"/ran/pagefind/index/en_4c9d511.pf_index",
"/ran/pagefind/pagefind-ui.js",
];
const VERSION = "1726478824";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



