const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/favicon.ico",
"/ran/logo.png",
"/ran/vp-icons.css",
"/ran/manifest.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/icon.png",
"/ran/icon_48.png",
"/ran/icon_168.png",
"/ran/src/article/babel.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/icon_144.png",
"/ran/screenshots_748x1340.jpg",
"/ran/sw1751295437.js",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/example.m3u8",
"/ran/icon_72.png",
"/ran/hashmap.json",
"/ran/404.html",
"/ran/index.html",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/src_article_sort_select_index.md.CF1e1gxP.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B7xgwaJh.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_javascript_dom_load.md.DB0OCjos.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.DKpX5Vnj.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_message_index.md.CjFowXwe.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DUi8S8Hp.lean.js",
"/ran/assets/src_article_sort_quick_index.md._yBQefDH.js",
"/ran/assets/src_article_sort_merge_index.md.BSTPjzaO.js",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/cn_src_ranui_message_index.md.CjFowXwe.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.C72lvwjS.js",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/cn_src_types_类型运算.md.Cng7KonY.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_popover_index.md.DUMdOo3M.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.p_COVKt4.lean.js",
"/ran/assets/src_ranui_image_index.md.B9EC7REY.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CBbh53Iu.lean.js",
"/ran/assets/cn_src_article_video.md.C6teEB_N.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.cbCkCbv5.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.CTkCQOn7.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_types_模式匹配.md.DE1RKEZI.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.YhfNzxwn.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_sort_bucket_index.md.DhoeDNbs.lean.js",
"/ran/assets/src_ranui_input_index.md.82qiKDeS.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.cbCkCbv5.js",
"/ran/assets/cn_src_blockchain_index.md.D5SG0Ghz.js",
"/ran/assets/src_ranui_loading_index.md.qHmTVH8e.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_types_模式匹配.md.DE1RKEZI.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/app.oMOxFRxn.js",
"/ran/assets/src_types_TS类型.md.BHCdA8yo.js",
"/ran/assets/src_article_babel.md.BF3pVPhx.js",
"/ran/assets/src_ranui_tab_index.md.p0KQd0aQ.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/pdf-DRw1818j.CDLbKYIq.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/pwa-install.es.C3gxbW8l.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/VPLocalSearchBox.e2AVAkyw.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/framework.CQmC_4em.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/index.GTQyCuNX.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/index.vUljFQlm.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CUKnpuHM.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/@localSearchIndexcn.tOsT5LRP.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/@localSearchIndexroot.6af2O5jo.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/theme.yiQDYYVO.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/src_ranui_index.md.BElS69kp.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C07F9V82.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DXrW0_xA.js",
"/ran/assets/src_ranui_image_index.md.B9EC7REY.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CpYTqS5j.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.Bck-pU_v.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BGCu-1Wt.js",
"/ran/assets/src_ranui_radar_index.md.2DDNOY7R.lean.js",
"/ran/assets/src_ranui_tab_index.md.p0KQd0aQ.lean.js",
"/ran/assets/src_article_typescript_union_type.md.DOVP4GSu.lean.js",
"/ran/assets/src_ranui_input_index.md.82qiKDeS.js",
"/ran/assets/src_article_functional_programming.md.WzO_JwPZ.lean.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.DB0OCjos.js",
"/ran/assets/cn_src_article_bundle.md.DP9dleXi.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranui_radar_index.md.UNLolQw8.js",
"/ran/assets/src_article_sort_heap_index.md.CiZSL4bN.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranuts_utils_filter_obj.md.DzjvGfAo.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.CVkQ4H6f.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_ranui_popover_index.md.BK6FMVLU.js",
"/ran/assets/cn_src_types_高级类型.md.DTvFsZxz.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranuts_file_write_file.md.C51BDmUy.js",
"/ran/assets/src_article_javascript_dom_load.md.CVkQ4H6f.lean.js",
"/ran/assets/cn_src_article_imagemin.md.NDi_MaG_.lean.js",
"/ran/assets/src_article_sort_radix_index.md.9aFzs97D.js",
"/ran/assets/cn_src_article_visual.md.4K2Lj3_A.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_ast_parse_tokenizer.md.Cq9ZWwOi.js",
"/ran/assets/src_article_design_mode.md.ckrA52pP.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranuts_bundler_index.md.DKvbLm61.js",
"/ran/assets/cn_src_article_babel.md.B28RL5mw.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BoimLrue.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_sort_heap_index.md.C7246hnw.lean.js",
"/ran/assets/cn_src_blockchain_web3.md.BbtYoHq4.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.Bck-pU_v.js",
"/ran/assets/src_article_sort_insert_index.md.WkZMMIgl.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_article_sort_quick_index.md.DTeleEw1.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.4LEJ3cTY.js",
"/ran/assets/src_article_sort_quick_index.md._yBQefDH.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CVtk-Ry3.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CX2cjCYO.js",
"/ran/assets/cn_src_ranui_progress_index.md.gkOxbvr6.js",
"/ran/assets/cn_src_note_docker.md.DP9t0Rk3.js",
"/ran/assets/cn_src_types_TS类型.md.DEzjuHZv.js",
"/ran/assets/src_article_typescript_reconstruction.md.C7grPn5T.lean.js",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/src_article_functional_programming.md.WzO_JwPZ.js",
"/ran/assets/cn_src_note_centos.md.DcffSPuw.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.p_COVKt4.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/src_ranuts_index.md.D2s4eTly.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BHWPkWIu.js",
"/ran/assets/src_article_sort_index.md.9U9UDMWy.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DUi8S8Hp.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_typescript_calculate.md.BUOKAP8j.js",
"/ran/assets/cn_src_article_visual.md.4K2Lj3_A.lean.js",
"/ran/assets/src_article_sort_insert_index.md.WkZMMIgl.js",
"/ran/assets/index.md.C36nNgYQ.js",
"/ran/assets/cn_src_article_sort_radix_index.md.lwG0xG7e.lean.js",
"/ran/assets/src_ranui_message_index.md.espDkkgx.lean.js",
"/ran/assets/cn_src_article_design_mode.md.DFA2cWVF.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_skeleton_index.md.BEquOIjh.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_types_高级类型.md.DTvFsZxz.js",
"/ran/assets/cn_src_ranui_input_index.md.BeUndyCs.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_article_sort_count_index.md.C7EOFvP0.js",
"/ran/assets/src_ranuts_bundler_index.md.DKvbLm61.lean.js",
"/ran/assets/src_ranuts_index.md.D2s4eTly.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_article_typescript_calculate.md.DfDHf4ha.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_bundle.md.D5MKydet.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.BB8l27JD.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CBO7B4Ep.js",
"/ran/assets/src_ranui_loading_index.md.qHmTVH8e.lean.js",
"/ran/assets/src_ranui_preview_index.md.CUAjwv0r.lean.js",
"/ran/assets/cn_src_note_centos.md.DcffSPuw.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranuts_utils_get_cookie.md.DKpX5Vnj.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_insert_index.md.J8_yuSok.lean.js",
"/ran/assets/src_article_typescript_index.md.xC5_f_mW.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/cn_src_ranui_math_index.md.BE8C78Bj.js",
"/ran/assets/src_ranuts_file_read_file.md.CvdchvSF.js",
"/ran/assets/cn_src_ranui_button_index.md.XcHebeVR.lean.js",
"/ran/assets/style.DK0_zZBI.css",
"/ran/assets/src_ranui_modal_index.md.CitHpkQw.js",
"/ran/assets/src_ranuts_file_read_dir.md.D5U3WvU7.js",
"/ran/assets/cn_src_article_sort_select_index.md.1a_Jo8l9.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CpYTqS5j.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.IxJD-rRO.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.BiR_izD3.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Bdqm2Ba1.js",
"/ran/assets/cn_src_ranui_select_index.md.DeftNDEf.js",
"/ran/assets/src_article_bundle.md.D5MKydet.lean.js",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/src_article_typescript_union_type.md.DOVP4GSu.js",
"/ran/assets/src_ranuts_utils_ocr.md.BiR_izD3.js",
"/ran/assets/cn_src_ranui_radar_index.md.UNLolQw8.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_sort_index.md.9U9UDMWy.lean.js",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.C7246hnw.js",
"/ran/assets/src_ranuts_file_file_info.md.YhfNzxwn.lean.js",
"/ran/assets/cn_src_note_docker.md.DP9t0Rk3.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.B21w7tn1.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/src_article_typescript_calculate.md.DfDHf4ha.lean.js",
"/ran/assets/cn_src_article_video.md.C6teEB_N.lean.js",
"/ran/assets/src_ranui_button_index.md.zRTU4gIC.lean.js",
"/ran/assets/src_ranui_tabs_index.md.D3SJKvTb.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CX2cjCYO.lean.js",
"/ran/assets/src_ranui_player_index.md.BPwz3DwL.js",
"/ran/assets/cn_src_ranui_loading_index.md.BWuCCL5q.js",
"/ran/assets/src_article_sort_shell_index.md.Bo7fJcL2.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranui_math_index.md.BE8C78Bj.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.gkOxbvr6.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_index.md.CoXmsZHF.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranui_icon_index.md.OxvP6qjY.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.CRyMNvwL.js",
"/ran/assets/src_article_imagemin.md.Bf7NdnpU.js",
"/ran/assets/cn_src_ranui_input_index.md.BeUndyCs.lean.js",
"/ran/assets/cn_src_article_design_mode.md.DFA2cWVF.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.D5U3WvU7.lean.js",
"/ran/assets/src_ranui_message_index.md.espDkkgx.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_note_ubuntu.md.D5Gd9avW.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranui_checkbox_index.md.C72lvwjS.lean.js",
"/ran/assets/src_article_typescript_index.md.xC5_f_mW.js",
"/ran/assets/src_ranuts_file_append_file.md.DvcCCaNP.js",
"/ran/assets/cn_src_ranui_tab_index.md.qWn8WEry.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.GWOd-z53.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_tabs_index.md.D3SJKvTb.js",
"/ran/assets/src_article_sort_merge_index.md.BSTPjzaO.lean.js",
"/ran/assets/cn_index.md.DxgodoWj.js",
"/ran/assets/src_ranuts_file_write_file.md.C51BDmUy.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DPeAukaa.lean.js",
"/ran/assets/cn_src_blockchain_index.md.D5SG0Ghz.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_ranuts_file_watch_file.md.Cfxd1K6R.js",
"/ran/assets/cn_src_article_sort_radix_index.md.lwG0xG7e.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_note_libreoffice2wasm.md.QHcUAkEl.lean.js",
"/ran/assets/cn_src_types_类型运算.md.Cng7KonY.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Cq9ZWwOi.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.DUMdOo3M.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_binary_tree_index.md.BPxi989z.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranui_skeleton_index.md.BEquOIjh.lean.js",
"/ran/assets/cn_src_article_bundle.md.DP9dleXi.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.COLfERfv.js",
"/ran/assets/cn_src_ranui_modal_index.md.9ySADVbv.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_select_index.md.DeftNDEf.lean.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/cn_src_ranui_preview_index.md.B21w7tn1.js",
"/ran/assets/src_types_类型运算.md.KlByFXln.js",
"/ran/assets/src_ranuts_utils_format_json.md.CiU904H6.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_ranui_player_index.md.LQhbOlQI.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.TFIBicFd.js",
"/ran/assets/src_article_imagemin.md.Bf7NdnpU.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DPIMmmzB.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_ranuts_utils_str2xml.md.Ctj-dQR2.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.QHcUAkEl.js",
"/ran/assets/src_ranui_select_index.md.C5kU_pFe.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.BLotqPN5.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DbVnBfMM.lean.js",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.QTg8aeDJ.lean.js",
"/ran/assets/src_article_sort_select_index.md.CF1e1gxP.js",
"/ran/assets/src_types_高级类型.md.0cDffUjl.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.DbVnBfMM.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BG6-zZaZ.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_typescript_union_type.md.CBO7B4Ep.lean.js",
"/ran/assets/cn_src_article_sort_index.md.sI04WXZv.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/cn_src_ranui_icon_index.md.OxvP6qjY.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/cn_src_ranuts_index.md.BHWPkWIu.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_types_模式匹配.md.DIK9_xws.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_preview_index.md.CUAjwv0r.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.D8u-oY74.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.BB8l27JD.js",
"/ran/assets/src_article_sort_shell_index.md.Bo7fJcL2.js",
"/ran/assets/src_ranuts_file_read_file.md.CvdchvSF.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DXrW0_xA.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_typescript_calculate.md.BUOKAP8j.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.C7EOFvP0.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BoXd6wD6.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_article_sort_insert_index.md.J8_yuSok.js",
"/ran/assets/cn_src_ranui_index.md.CoXmsZHF.js",
"/ran/assets/src_article_babel.md.BF3pVPhx.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_sort_index.md.sI04WXZv.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Bdqm2Ba1.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C07F9V82.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranui_icon_index.md.Dez8Z5x-.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BjkDGv8V.js",
"/ran/assets/src_ranui_radar_index.md.2DDNOY7R.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/cn_src_ranuts_utils_format_json.md.TFIBicFd.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.VAllQy6x.js",
"/ran/assets/cn_src_ranui_tab_index.md.qWn8WEry.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Ctj-dQR2.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.1a_Jo8l9.lean.js",
"/ran/assets/cn_src_article_system_design.md.Z7sB7SS2.lean.js",
"/ran/assets/index.md.C36nNgYQ.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.Cfxd1K6R.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_types_TS类型.md.DEzjuHZv.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.GWOd-z53.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_file_watch_file.md.IxJD-rRO.js",
"/ran/assets/cn_src_blockchain_web3.md.BbtYoHq4.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_sort_quick_index.md.DTeleEw1.js",
"/ran/assets/src_article_sort_count_index.md.BcphlU1P.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.CTkCQOn7.lean.js",
"/ran/assets/src_ranui_select_index.md.C5kU_pFe.js",
"/ran/assets/src_article_sort_radix_index.md.9aFzs97D.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.COLfERfv.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DhoeDNbs.js",
"/ran/assets/cn_src_ranui_image_index.md.DVDxBcVn.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_types_TS类型.md.BHCdA8yo.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_typescript_reconstruction.md.C7grPn5T.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B7xgwaJh.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.BlyJUR64.js",
"/ran/assets/cn_src_ranui_image_index.md.DVDxBcVn.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DvcCCaNP.lean.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/cn_src_ranuts_file_append_file.md.BLotqPN5.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_system_design.md.Z7sB7SS2.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BG6-zZaZ.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BMf250St.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.XcHebeVR.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/src_article_sort_bucket_index.md.CBbh53Iu.js",
"/ran/assets/src_types_高级类型.md.0cDffUjl.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.BPxi989z.js",
"/ran/assets/src_ranui_player_index.md.BPwz3DwL.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_babel.md.B28RL5mw.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C5zzyUvu.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DPIMmmzB.lean.js",
"/ran/assets/src_ranui_progress_index.md.WBEGarwG.js",
"/ran/assets/src_ranui_math_index.md.DDn6rzZv.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/src_types_模式匹配.md.DIK9_xws.js",
"/ran/assets/src_ranui_index.md.BElS69kp.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BoXd6wD6.js",
"/ran/assets/src_article_typescript_recursion.md.CeKpCYnG.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.4LEJ3cTY.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DPeAukaa.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.D8u-oY74.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DzjvGfAo.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.BVQDgH80.lean.js",
"/ran/assets/src_article_sort_heap_index.md.CiZSL4bN.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BMf250St.js",
"/ran/assets/src_article_design_mode.md.ckrA52pP.js",
"/ran/assets/cn_index.md.DxgodoWj.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_ranui_player_index.md.LQhbOlQI.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/src_ranui_button_index.md.zRTU4gIC.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_utils_format_json.md.CiU904H6.js",
"/ran/assets/cn_src_note_ubuntu.md.D5Gd9avW.js",
"/ran/assets/src_ranui_modal_index.md.CitHpkQw.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CVtk-Ry3.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C5zzyUvu.js",
"/ran/assets/src_article_typescript_pattern.md.BGCu-1Wt.lean.js",
"/ran/assets/src_ranui_icon_index.md.Dez8Z5x-.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BWuCCL5q.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_article_sort_count_index.md.BcphlU1P.lean.js",
"/ran/assets/src_types_类型运算.md.KlByFXln.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranuts_utils_task.md.Bg6LSGpX.js",
"/ran/assets/src_article_sort_bubble_index.md.CRyMNvwL.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranui_popover_index.md.BK6FMVLU.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Bg6LSGpX.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.VPmprauo.js",
"/ran/assets/src_ranui_progress_index.md.WBEGarwG.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_typescript_recursion.md.CeKpCYnG.lean.js",
"/ran/assets/src_ranui_math_index.md.DDn6rzZv.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_article_typescript_pattern.md.BlyJUR64.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranuts_file_read_file.md.BVQDgH80.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.BjkDGv8V.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.VAllQy6x.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BoimLrue.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_imagemin.md.NDi_MaG_.js",
"/ran/assets/cn_src_ranui_tabs_index.md.QTg8aeDJ.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.VPmprauo.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranui_modal_index.md.9ySADVbv.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/icon_96.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/index.html",
];
const VERSION = "1751295437";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



