const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_ranui_image_index.md.tM7qeKBA.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_javascript_dom_load.md.BFmeo2Kr.js",
"/ran/assets/cn_src_article_sort_select_index.md.x_ZyrQ1D.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_sort_quick_index.md.DvaFtyey.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B230-5II.js",
"/ran/assets/src_types_类型运算.md.DqX50E5F.js",
"/ran/assets/src_article_sort_insert_index.md.DrDRua9t.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_select_index.md.BAznUfF8.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_article_doc_preview.md.CilyC96U.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DrFTz1vt.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_image_index.md.tM7qeKBA.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BJR_pWcj.js",
"/ran/assets/src_ranui_popover_index.md.DuUyf4JS.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BnC1Dr9U.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BkBJAoj1.lean.js",
"/ran/assets/src_article_sort_index.md.cojGx8LD.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_design_mode.md.vH0JYHON.lean.js",
"/ran/assets/src_article_bundle.md.VruNLm5T.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.8mPxjr_f.js",
"/ran/assets/cn_src_article_sort_insert_index.md.d-7ITM2n.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_article_sort_select_index.md.DjD11rps.js",
"/ran/assets/cn_src_ranui_index.md.DfPHtPpO.js",
"/ran/assets/cn_src_article_design_mode.md.BoGe1V8c.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.X-BR8b5D.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Wc6O5IAb.lean.js",
"/ran/assets/src_article_babel.md.BlA-_2pR.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DJf_FgPs.js",
"/ran/assets/src_ranui_message_index.md.Dl4UimnA.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_sort_shell_index.md.DvgqY8PD.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DLyoi0d5.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.DrtXurw5.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.C-OPEEDX.js",
"/ran/assets/cn_src_article_functional_programming.md.CiNG3AZ-.lean.js",
"/ran/assets/cn_src_article_visual.md.D9wuHgdO.js",
"/ran/assets/cn_src_ranui_icon_index.md.p_r4uNzU.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BZenB7I9.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BZenB7I9.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.DvgqY8PD.js",
"/ran/assets/src_article_bundle.md.VruNLm5T.js",
"/ran/assets/cn_src_ranui_button_index.md.BkBJAoj1.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.Bh-DxiVu.lean.js",
"/ran/assets/src_types_高级类型.md.Cqd9hgd2.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DiVQcBjl.lean.js",
"/ran/assets/src_ranui_tab_index.md.BJau6FUU.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.BFmeo2Kr.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CY9QR8Ex.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_message_index.md.Dl4UimnA.js",
"/ran/assets/src_ranui_player_index.md.Bd3rv3hF.js",
"/ran/assets/src_article_sort_bubble_index.md.07hDv_OR.js",
"/ran/assets/cn_src_ranui_modal_index.md.DmfSfkob.js",
"/ran/assets/src_ranuts_file_read_dir.md.BrswjHSu.js",
"/ran/assets/cn_src_ranui_player_index.md.BtT3liLG.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_article_sort_insert_index.md.DrDRua9t.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.IvCxs2g9.js",
"/ran/assets/cn_src_article_video.md.Dm3SFM4a.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CHatrGd_.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranui_player_index.md.Bd3rv3hF.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B230-5II.lean.js",
"/ran/assets/src_ranui_popover_index.md.DuUyf4JS.js",
"/ran/assets/src_ranuts_index.md.BdNr7G5F.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BnKcIPdx.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.S3-fBLlb.lean.js",
"/ran/assets/cn_index.md.CeHdGfXe.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.PXJoLho5.lean.js",
"/ran/assets/src_article_functional_programming.md.th7VP8lg.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.SflgmnUU.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C-OPEEDX.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BHgYxjSR.js",
"/ran/assets/cn_src_note_centos.md.WaMGd7h2.js",
"/ran/assets/cn_src_ranui_player_index.md.BtT3liLG.lean.js",
"/ran/assets/src_article_sort_count_index.md.CQgrVJEl.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.PcB4M0Ce.lean.js",
"/ran/assets/cn_src_note_docker.md.CpCFs-M9.js",
"/ran/assets/cn_src_article_sort_count_index.md.CN8OS-1H.js",
"/ran/assets/src_article_typescript_index.md.Da7Y61_0.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BI3oiLai.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DXj0b-lJ.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_types_类型运算.md.jYHEenVf.js",
"/ran/assets/src_ranuts_file_read_dir.md.BrswjHSu.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.E1UZKvqQ.js",
"/ran/assets/src_article_sort_merge_index.md.Cog11UKT.lean.js",
"/ran/assets/style.CVPVLIRO.css",
"/ran/assets/cn_src_article_functional_programming.md.CiNG3AZ-.js",
"/ran/assets/cn_src_article_sort_heap_index.md.8mPxjr_f.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BHBaQE91.lean.js",
"/ran/assets/src_article_functional_programming.md.th7VP8lg.js",
"/ran/assets/cn_src_article_sort_select_index.md.x_ZyrQ1D.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.D3O1Q6lH.js",
"/ran/assets/cn_src_article_typescript_pattern.md.SflgmnUU.lean.js",
"/ran/assets/src_ranui_loading_index.md.BqavKzjQ.js",
"/ran/assets/src_ranui_checkbox_index.md.CMI7jNXH.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.C6vJ23WD.js",
"/ran/assets/cn_src_ranui_loading_index.md.BNcOyGsq.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BH00Mp6H.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DgNROcmL.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_utils_task.md.BSCOZedZ.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BdfIUoBL.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_types_高级类型.md.Cqd9hgd2.js",
"/ran/assets/cn_src_ranui_popover_index.md.DpU6CEGi.lean.js",
"/ran/assets/src_article_typescript_union_type.md.Bao0q6DT.js",
"/ran/assets/cn_src_ranui_input_index.md.DMEKzWPG.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CUFR_R5k.lean.js",
"/ran/assets/src_ranui_modal_index.md.pEla2vh2.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BSCOZedZ.js",
"/ran/assets/src_article_sort_count_index.md.CQgrVJEl.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_typescript_reconstruction.md.DIsG2shU.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BoH1fqsB.js",
"/ran/assets/src_article_sort_quick_index.md.DvaFtyey.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranuts_file_watch_file.md.DgAN0poI.js",
"/ran/assets/src_ranui_index.md.R8HUJlvR.js",
"/ran/assets/cn_src_article_sort_quick_index.md.DhXqkbvm.js",
"/ran/assets/cn_src_ranui_message_index.md.D6NvZESE.js",
"/ran/assets/src_types_TS类型.md.DaLbgwug.lean.js",
"/ran/assets/cn_src_article_system_design.md.DylqDHXn.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.n6puD9od.js",
"/ran/assets/cn_src_ranui_select_index.md.BGzxEV4D.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DJ-0uuQn.lean.js",
"/ran/assets/src_ranui_modal_index.md.pEla2vh2.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranui_preview_index.md.n6puD9od.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_merge_index.md.DiQRRB0N.js",
"/ran/assets/cn_src_ranui_math_index.md.QxBBR2_g.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DByUiHAO.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_article_sort_quick_index.md.DhXqkbvm.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_typescript_index.md.Ddo3Yb8M.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_utils_get_cookie.md.D3JT1Yvi.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.BJR_pWcj.lean.js",
"/ran/assets/index.md.Cs_Mjy4L.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_sort_index.md.BV1cHKat.js",
"/ran/assets/src_ranuts_file_file_info.md.CNbam66Q.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.ecgGzoYU.js",
"/ran/assets/src_ranui_index.md.R8HUJlvR.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.DIsG2shU.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DzJ-23j_.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.TMo9JUfI.js",
"/ran/assets/cn_src_article_bundle.md.akFADTFV.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ol5me19t.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_typescript_union_type.md.ByCiVne6.js",
"/ran/assets/src_ranui_progress_index.md.Cgpo1zK_.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_article_imagemin.md.DFFxuMYQ.js",
"/ran/assets/src_article_sort_index.md.cojGx8LD.lean.js",
"/ran/assets/src_article_typescript_index.md.Da7Y61_0.js",
"/ran/assets/src_article_sort_heap_index.md.D5aqBZfX.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_math_linear_algebra.md.DJf_FgPs.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DnXaGZAP.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.De7g-GSF.js",
"/ran/assets/cn_src_ranui_tab_index.md.ecgGzoYU.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.DiVQcBjl.js",
"/ran/assets/src_ranui_radar_index.md.hcKAOHE4.js",
"/ran/assets/cn_src_types_TS类型.md.BkRPNjyo.js",
"/ran/assets/src_ranuts_utils_task.md.DATAwWWv.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranui_tabs_index.md.B2DetCgu.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BnC1Dr9U.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.BbZigStF.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranui_radar_index.md.hcKAOHE4.lean.js",
"/ran/assets/src_article_design_mode.md.vH0JYHON.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Wc6O5IAb.js",
"/ran/assets/src_ranui_tabs_index.md.Cb9IqdEx.lean.js",
"/ran/assets/src_types_模式匹配.md.CLYzO-ZT.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.CMI7jNXH.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_article_design_mode.md.BoGe1V8c.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_sort_merge_index.md.DiQRRB0N.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.p_r4uNzU.js",
"/ran/assets/cn_src_article_visual.md.D9wuHgdO.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Cog11UKT.js",
"/ran/assets/src_article_typescript_calculate.md.HF8jDDsw.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BSgMTEsD.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_math_index.md.QxBBR2_g.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DXj0b-lJ.lean.js",
"/ran/assets/src_article_sort_radix_index.md.Bn-tN3Pl.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_sort_select_index.md.DjD11rps.lean.js",
"/ran/assets/src_article_imagemin.md.DFFxuMYQ.lean.js",
"/ran/assets/index.md.Cs_Mjy4L.lean.js",
"/ran/assets/cn_src_article_bundle.md.akFADTFV.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranui_radar_index.md.DrEVusRO.js",
"/ran/assets/src_types_模式匹配.md.CLYzO-ZT.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_typescript_calculate.md.BI3oiLai.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.TMo9JUfI.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DBuwWSK1.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.Bg1-A6v2.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B2DetCgu.js",
"/ran/assets/app.CXMJVpBg.js",
"/ran/assets/cn_src_article_video.md.Dm3SFM4a.lean.js",
"/ran/assets/src_ranui_icon_index.md.eAHujCdE.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.C6vJ23WD.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_note_docker.md.CpCFs-M9.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BHBaQE91.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranuts_utils_get_cookie.md.D3JT1Yvi.js",
"/ran/assets/src_ranui_icon_index.md.eAHujCdE.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.UmYfjFjh.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DLyoi0d5.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.PXJoLho5.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_select_index.md.BGzxEV4D.js",
"/ran/assets/src_ranuts_file_file_info.md.CNbam66Q.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_ranuts_file_read_dir.md.7KiTOUCR.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_file_append_file.md.aLxLFJy7.js",
"/ran/assets/src_article_typescript_pattern.md.DgNROcmL.js",
"/ran/assets/src_ranuts_file_write_file.md.VyhsEJg3.js",
"/ran/assets/src_article_typescript_union_type.md.Bao0q6DT.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.mkVC_ofY.lean.js",
"/ran/assets/cn_src_ranuts_index.md.unqdX543.lean.js",
"/ran/assets/cn_src_ranuts_index.md.unqdX543.js",
"/ran/assets/cn_src_article_doc_preview.md.CilyC96U.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_article_sort_shell_index.md.DJ-0uuQn.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CHatrGd_.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.De7g-GSF.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.DrEVusRO.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.Ddo3Yb8M.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BdfIUoBL.lean.js",
"/ran/assets/src_article_sort_radix_index.md.Bn-tN3Pl.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DMEKzWPG.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranui_skeleton_index.md.Bg1-A6v2.js",
"/ran/assets/cn_src_article_typescript_union_type.md.ByCiVne6.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_file_read_file.md.PcB4M0Ce.js",
"/ran/assets/cn_src_ranui_modal_index.md.DmfSfkob.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_ranui_select_index.md.BAznUfF8.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranui_tabs_index.md.Cb9IqdEx.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_sort_index.md.BV1cHKat.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CY9QR8Ex.js",
"/ran/assets/src_ranuts_utils_format_json.md.S3-fBLlb.js",
"/ran/assets/cn_src_article_imagemin.md.DKEeOpz8.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BHgYxjSR.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.E1UZKvqQ.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranuts_file_file_info.md.Bh-DxiVu.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.DnXaGZAP.js",
"/ran/assets/src_article_sort_bubble_index.md.07hDv_OR.lean.js",
"/ran/assets/src_article_sort_heap_index.md.D5aqBZfX.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BoH1fqsB.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/index-D6nXg_bb.kb2jJ-4C.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.aJu9e5fm.js",
"/ran/assets/chunks/jszip.min--o3_SgQz.CiS0z4ab.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/index.DzUvnNAe.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index-CVkJ_Xlh.BFb2SL1a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/VPLocalSearchBox.hrcrQvHW.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.BN8QfUnw.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/theme.CTTH9JdA.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/docx-D5t6JtVt.BnsCdyQq.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/@localSearchIndexroot.zc2HiKXB.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-HhqG7SJg.B9lKsKkd.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/@localSearchIndexcn.B8EAiXlr.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CGbEuAKP.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BSgMTEsD.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_types_类型运算.md.DqX50E5F.lean.js",
"/ran/assets/src_article_typescript_calculate.md.HF8jDDsw.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.mkVC_ofY.js",
"/ran/assets/src_ranuts_binary_tree_index.md.DByUiHAO.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_utils_filter_obj.md.BH00Mp6H.js",
"/ran/assets/src_ranui_button_index.md.ko5BqwaN.js",
"/ran/assets/src_ranuts_file_watch_file.md.DgAN0poI.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BtCnMYcQ.js",
"/ran/assets/cn_src_note_centos.md.WaMGd7h2.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DrFTz1vt.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.BbZigStF.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.DzJ-23j_.js",
"/ran/assets/src_ranui_math_index.md.-muJj65W.js",
"/ran/assets/cn_src_article_sort_insert_index.md.d-7ITM2n.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.X-BR8b5D.lean.js",
"/ran/assets/src_ranuts_index.md.BdNr7G5F.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranui_popover_index.md.DpU6CEGi.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_preview_index.md.Cn43Neqk.js",
"/ran/assets/cn_src_ranui_message_index.md.D6NvZESE.lean.js",
"/ran/assets/cn_src_article_imagemin.md.DKEeOpz8.js",
"/ran/assets/src_ranui_math_index.md.-muJj65W.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranui_preview_index.md.Cn43Neqk.lean.js",
"/ran/assets/cn_index.md.CeHdGfXe.js",
"/ran/assets/cn_src_article_sort_count_index.md.CN8OS-1H.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_ranui_loading_index.md.BNcOyGsq.js",
"/ran/assets/src_ranui_input_index.md.DtRKpQA5.js",
"/ran/assets/src_ranuts_file_append_file.md.IvCxs2g9.lean.js",
"/ran/assets/cn_src_article_babel.md.DR9JFZbJ.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ol5me19t.js",
"/ran/assets/src_ranui_tab_index.md.BJau6FUU.js",
"/ran/assets/cn_src_types_TS类型.md.BkRPNjyo.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranui_checkbox_index.md.CGbEuAKP.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranui_loading_index.md.BqavKzjQ.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranui_button_index.md.ko5BqwaN.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_types_类型运算.md.jYHEenVf.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranui_input_index.md.DtRKpQA5.lean.js",
"/ran/assets/src_types_TS类型.md.DaLbgwug.js",
"/ran/assets/src_ranui_progress_index.md.Cgpo1zK_.lean.js",
"/ran/assets/src_article_babel.md.BlA-_2pR.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_bucket_index.md.CUFR_R5k.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_types_高级类型.md.DBuwWSK1.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_ranuts_file_read_dir.md.7KiTOUCR.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.BnKcIPdx.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.DrtXurw5.lean.js",
"/ran/assets/src_ranui_image_index.md.C8taAW0E.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.aLxLFJy7.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BtCnMYcQ.lean.js",
"/ran/assets/cn_src_article_system_design.md.DylqDHXn.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_index.md.DfPHtPpO.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.D3O1Q6lH.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranuts_file_write_file.md.VyhsEJg3.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DATAwWWv.lean.js",
"/ran/assets/src_ranui_image_index.md.C8taAW0E.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_article_babel.md.DR9JFZbJ.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.UmYfjFjh.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/sw1741496915.js",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1741496915";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



