const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/sw1748155440.js",
"/ran/vp-icons.css",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/example.m3u8",
"/ran/assets/src_article_sort_heap_index.md.BfuKTNKw.js",
"/ran/assets/cn_src_types_高级类型.md.Bc3TDeYD.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_pattern.md.DUgdKHrC.lean.js",
"/ran/assets/src_types_类型运算.md.BiHq-upd.lean.js",
"/ran/assets/src_article_sort_select_index.md.DCuyIdg8.lean.js",
"/ran/assets/src_ranui_preview_index.md.D82tb4sg.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BZy9woX6.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_typescript_index.md.CDQSQ7zZ.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DVHIwGp_.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CkIk_umJ.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_article_sort_select_index.md.D2XTvpB4.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_note_docker.md.BCJQxUJg.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/src_ranui_message_index.md.DptWn0rw.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_bundle.md.CIRLcK0f.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_ranui_loading_index.md.BEmmn__l.lean.js",
"/ran/assets/cn_src_ranui_index.md.LhjOprQE.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_sort_bucket_index.md.B8H3G-MJ.js",
"/ran/assets/cn_src_ranui_player_index.md.CBoRO9EU.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.ChDrnD_Y.js",
"/ran/assets/cn_src_article_sort_index.md.CPp90seI.js",
"/ran/assets/src_ranuts_index.md.DyW65US1.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Cs1NQV2e.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.dez9VHg0.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.YJc32IDe.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Jzh9FYMV.js",
"/ran/assets/src_ranui_popover_index.md.CwhFIIH4.lean.js",
"/ran/assets/src_article_functional_programming.md.BJ-IuAMD.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_blockchain_web3.md.DZNgzjHQ.lean.js",
"/ran/assets/cn_src_ranuts_index.md.M-WPKQsB.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.B0t_Bo0L.js",
"/ran/assets/src_ranui_loading_index.md.BhIuvM9y.lean.js",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BemXcFJA.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DuP62MBL.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_typescript_recursion.md.CDjnH_h6.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_ranui_button_index.md.UeIzSHdv.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bo9cp5hQ.lean.js",
"/ran/assets/src_ranui_radar_index.md.B9Y-mOtX.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Dw0NtHEM.lean.js",
"/ran/assets/cn_src_blockchain_index.md.xNU7gymN.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.YJc32IDe.lean.js",
"/ran/assets/src_article_sort_count_index.md.C8z10an8.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_types_模式匹配.md.B2nsXDoL.js",
"/ran/assets/src_article_javascript_dom_load.md.Byo7AS__.lean.js",
"/ran/assets/src_ranui_math_index.md.Dir_fiou.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.9pt1gUmX.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranui_select_index.md.DaVduqO5.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.B0t_Bo0L.lean.js",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C8Boj9VO.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DjNZzKsv.js",
"/ran/assets/src_article_design_mode.md.BhUQVnjL.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CXmab15F.js",
"/ran/assets/src_ranuts_file_file_info.md.DHDgQYQQ.js",
"/ran/assets/src_ranuts_file_watch_file.md.DXLAIsA7.lean.js",
"/ran/assets/index.md.Dj3WCkzI.js",
"/ran/assets/src_ranuts_file_append_file.md.DjNZzKsv.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DuP62MBL.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C8Boj9VO.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BZy9woX6.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DDE6QeJT.lean.js",
"/ran/assets/src_types_模式匹配.md.B2nsXDoL.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.BjiSV1Xr.lean.js",
"/ran/assets/cn_src_article_video.md.C-yumded.js",
"/ran/assets/cn_src_article_sort_select_index.md.D2XTvpB4.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_file_read_file.md.B6OXJmeR.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_ranui_skeleton_index.md.CVpARLJm.js",
"/ran/assets/cn_src_ranui_tab_index.md.BTk4rynx.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_types_TS类型.md.BY7dkIAT.js",
"/ran/assets/src_ranui_loading_index.md.BhIuvM9y.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/framework.C25nBkpI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/@localSearchIndexcn.-oOqGuiW.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/VPLocalSearchBox.CHqEnEIN.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/theme.C_sqdk_f.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CmrImyI8.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/katex-es-CGqSCDjs.BDSjlQ-m.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/pwa-install.es.BM1ku5fR.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/index.DTePfKla.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/@localSearchIndexroot.BuGC8jMv.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B1GTqZJ_.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.CEQRVOrS.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CKQwzn58.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.BMNnKO9Q.lean.js",
"/ran/assets/src_article_sort_quick_index.md.uGZUB7Kc.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BMNnKO9Q.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/index.md.Dj3WCkzI.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BfuKTNKw.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.DXLAIsA7.js",
"/ran/assets/cn_src_article_visual.md.lE42NeNi.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.qoF_nKVJ.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DO7nBAFQ.lean.js",
"/ran/assets/cn_src_blockchain_index.md.xNU7gymN.js",
"/ran/assets/src_article_babel.md.BH6O13hA.lean.js",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/app.Bp_YLsp8.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.qoF_nKVJ.js",
"/ran/assets/src_article_sort_index.md.B-5Mz-cP.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.kRN3FkjA.lean.js",
"/ran/assets/src_ranui_button_index.md.Dny1BZus.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_index.md.BBMGsRBd.js",
"/ran/assets/cn_src_types_模式匹配.md.DQ3tla3s.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_article_sort_insert_index.md.BRbLdIWN.js",
"/ran/assets/src_types_TS类型.md.B-77dj0G.lean.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.CKQwzn58.js",
"/ran/assets/cn_src_ranui_math_index.md.dez9VHg0.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DepBkYYx.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_sort_select_index.md.DCuyIdg8.js",
"/ran/assets/src_ranuts_utils_task.md.CKtzFtLD.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B8H3G-MJ.lean.js",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_progress_index.md.C2dlayEW.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.B6OXJmeR.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.DSFkwRYO.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BE_YQBAl.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BeOoS5FR.js",
"/ran/assets/cn_src_ranuts_index.md.M-WPKQsB.js",
"/ran/assets/src_article_typescript_reconstruction.md.4rHFIeCp.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CQt_fc4F.js",
"/ran/assets/src_article_typescript_union_type.md.DRncsIqW.lean.js",
"/ran/assets/src_article_typescript_union_type.md.DRncsIqW.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DoBp0XRf.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DQG-fzmG.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_image_index.md.9pt1gUmX.lean.js",
"/ran/assets/cn_src_types_TS类型.md.BY7dkIAT.lean.js",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DuMLsTv3.js",
"/ran/assets/src_article_sort_insert_index.md.BRbLdIWN.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_article_imagemin.md.CdnSp_zR.lean.js",
"/ran/assets/src_article_babel.md.BH6O13hA.js",
"/ran/assets/src_article_typescript_calculate.md.DcExNMuy.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BEyayPDK.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CQt_fc4F.lean.js",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/cn_src_ranui_progress_index.md.CzkN_Sg5.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_quick_index.md.uGZUB7Kc.js",
"/ran/assets/cn_src_ranui_tab_index.md.BTk4rynx.js",
"/ran/assets/src_ranui_math_index.md.Dir_fiou.js",
"/ran/assets/cn_src_article_babel.md.B4cyhKTG.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DepBkYYx.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_ranuts_file_append_file.md.CGr0xH-D.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BEmmn__l.js",
"/ran/assets/src_article_sort_merge_index.md.rj673foR.js",
"/ran/assets/src_article_sort_radix_index.md.BL89JeVJ.js",
"/ran/assets/cn_src_article_sort_merge_index.md.zOk2yEb5.js",
"/ran/assets/cn_src_article_babel.md.B4cyhKTG.js",
"/ran/assets/cn_src_article_visual.md.lE42NeNi.lean.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_article_sort_insert_index.md.CnfFni9C.lean.js",
"/ran/assets/src_article_typescript_index.md.5DvA_u60.lean.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_ranui_input_index.md.XD3aE3WR.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BoLD9Dzn.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.fF4LUU30.js",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.ChDrnD_Y.lean.js",
"/ran/assets/src_ranui_index.md.BBMGsRBd.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C-v4Pg8G.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DO7nBAFQ.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_ast_parse_tokenizer.md.BeOoS5FR.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.DNAFGWEh.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CBoRO9EU.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_article_sort_count_index.md.CwYSFKqd.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranuts_file_read_dir.md.BZfXhPia.js",
"/ran/assets/src_ranui_popover_index.md.CwhFIIH4.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranui_input_index.md.Ccmbuhjh.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DpvXazaC.js",
"/ran/assets/src_article_sort_bubble_index.md.DNAFGWEh.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Jzh9FYMV.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranuts_utils_str2xml.md.BgmXlCUV.js",
"/ran/assets/cn_src_ranui_preview_index.md.DPKay7oK.js",
"/ran/assets/src_ranui_select_index.md.DaVduqO5.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranui_message_index.md.DptWn0rw.js",
"/ran/assets/cn_src_ranui_modal_index.md.DteG3f4H.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_checkbox_index.md.D5HVlcaf.js",
"/ran/assets/src_article_sort_index.md.B-5Mz-cP.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_design_mode.md.BnyFYHfU.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/cn_src_ranui_preview_index.md.DPKay7oK.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.XD3aE3WR.js",
"/ran/assets/src_article_sort_shell_index.md.BEyayPDK.lean.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/cn_src_ranui_select_index.md.BO-w5gfT.js",
"/ran/assets/src_ranuts_binary_tree_index.md.QRG96H81.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.C35Zovdc.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.B9rWKl0k.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_utils_get_cookie.md.CoxJqpnz.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CEQRVOrS.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DxLObE1X.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_article_typescript_index.md.5DvA_u60.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_article_typescript_index.md.CDQSQ7zZ.js",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_article_doc_preview.md.BLOF180Q.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DA5nyEvw.lean.js",
"/ran/assets/src_article_bundle.md.CIRLcK0f.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CGr0xH-D.js",
"/ran/assets/src_ranuts_file_read_dir.md.BZfXhPia.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bo9cp5hQ.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranui_modal_index.md.VoCoL1aQ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B2CW4TA7.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_ranuts_bundler_index.md.C35Zovdc.js",
"/ran/assets/src_ranui_image_index.md.FZiQS44R.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CDjnH_h6.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BL89JeVJ.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/cn_src_article_bundle.md.QFFqkJ5S.js",
"/ran/assets/cn_src_article_imagemin.md.CdnSp_zR.js",
"/ran/assets/cn_src_note_centos.md.CF9qZ7pH.lean.js",
"/ran/assets/src_ranui_tab_index.md.rAiIaOA0.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranui_radar_index.md.CvPN3wL4.js",
"/ran/assets/cn_src_article_system_design.md.dSKZfE5C.lean.js",
"/ran/assets/cn_src_types_高级类型.md.Bc3TDeYD.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_icon_index.md.DNMnOerz.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BemXcFJA.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranuts_file_write_file.md.CEu80-P8.lean.js",
"/ran/assets/src_ranui_modal_index.md.VoCoL1aQ.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_types_模式匹配.md.DQ3tla3s.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranui_popover_index.md.BEE9-W8p.js",
"/ran/assets/cn_src_article_functional_programming.md.fF4LUU30.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CAVnDkOC.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/src_article_javascript_dom_load.md.Byo7AS__.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_button_index.md.Dny1BZus.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.2BtXh7EU.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.DA5nyEvw.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_note_centos.md.CF9qZ7pH.js",
"/ran/assets/src_types_高级类型.md.Bp22qQC7.js",
"/ran/assets/cn_src_ranui_modal_index.md.DteG3f4H.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DxLObE1X.lean.js",
"/ran/assets/src_ranui_radar_index.md.B9Y-mOtX.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_article_imagemin.md.CEtOyccM.js",
"/ran/assets/src_article_typescript_pattern.md.DUgdKHrC.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BgmXlCUV.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.B-YzVmFZ.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/cn_src_article_typescript_union_type.md.DSFkwRYO.lean.js",
"/ran/assets/cn_index.md.Bl_rNrxO.js",
"/ran/assets/src_types_类型运算.md.BiHq-upd.js",
"/ran/assets/src_article_sort_count_index.md.C8z10an8.js",
"/ran/assets/style.xOo_NRHt.css",
"/ran/assets/cn_src_ranuts_utils_task.md.DQG-fzmG.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_sort_index.md.CPp90seI.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.BEE9-W8p.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.CzkN_Sg5.js",
"/ran/assets/cn_src_article_sort_heap_index.md.C3Cye002.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.kRN3FkjA.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/cn_src_article_system_design.md.dSKZfE5C.js",
"/ran/assets/src_ranui_image_index.md.FZiQS44R.js",
"/ran/assets/cn_src_note_ubuntu.md.DDE6QeJT.js",
"/ran/assets/src_article_sort_merge_index.md.rj673foR.lean.js",
"/ran/assets/src_ranuts_index.md.DyW65US1.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B1GTqZJ_.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DuMLsTv3.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CkIk_umJ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.B2CW4TA7.js",
"/ran/assets/src_article_functional_programming.md.BJ-IuAMD.lean.js",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/src_ranui_tab_index.md.rAiIaOA0.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.CXmab15F.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DHDgQYQQ.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CVpARLJm.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_article_typescript_calculate.md.C-v4Pg8G.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_imagemin.md.CEtOyccM.lean.js",
"/ran/assets/cn_src_note_docker.md.BCJQxUJg.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.BO-w5gfT.lean.js",
"/ran/assets/src_types_高级类型.md.Bp22qQC7.lean.js",
"/ran/assets/src_ranui_preview_index.md.D82tb4sg.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BE_YQBAl.lean.js",
"/ran/assets/src_ranui_player_index.md.BEUDAEkb.js",
"/ran/assets/src_ranui_tabs_index.md.CVGu5ISd.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Cs1NQV2e.js",
"/ran/assets/cn_src_article_typescript_recursion.md.2BtXh7EU.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BN2JBymx.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.B9rWKl0k.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.QRG96H81.js",
"/ran/assets/src_ranuts_utils_ocr.md.B-YzVmFZ.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.4rHFIeCp.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.D5HVlcaf.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_design_mode.md.BhUQVnjL.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DVHIwGp_.js",
"/ran/assets/cn_src_article_design_mode.md.BnyFYHfU.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.CAyKMWXv.js",
"/ran/assets/cn_src_article_sort_quick_index.md.Dw0NtHEM.js",
"/ran/assets/cn_src_article_bundle.md.QFFqkJ5S.lean.js",
"/ran/assets/src_types_TS类型.md.B-77dj0G.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/cn_src_article_sort_merge_index.md.zOk2yEb5.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/src_article_sort_bucket_index.md.CoRkPqg5.lean.js",
"/ran/assets/cn_index.md.Bl_rNrxO.lean.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/src_ranuts_file_write_file.md.CEu80-P8.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BN2JBymx.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_file_write_file.md.BjiSV1Xr.js",
"/ran/assets/cn_src_article_video.md.C-yumded.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DcExNMuy.js",
"/ran/assets/cn_src_article_doc_preview.md.BLOF180Q.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_blockchain_web3.md.DZNgzjHQ.js",
"/ran/assets/cn_src_ranui_button_index.md.UeIzSHdv.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DpvXazaC.lean.js",
"/ran/assets/src_ranui_progress_index.md.C2dlayEW.lean.js",
"/ran/assets/cn_src_ranui_index.md.LhjOprQE.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_radar_index.md.CvPN3wL4.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.CAVnDkOC.js",
"/ran/assets/src_ranui_player_index.md.BEUDAEkb.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.CAyKMWXv.lean.js",
"/ran/assets/src_ranui_icon_index.md.DNMnOerz.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.CoxJqpnz.lean.js",
"/ran/assets/src_ranui_input_index.md.Ccmbuhjh.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CoRkPqg5.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DoBp0XRf.js",
"/ran/assets/src_ranuts_utils_format_json.md.BoLD9Dzn.js",
"/ran/assets/src_ranui_tabs_index.md.CVGu5ISd.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CnfFni9C.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/src_ranuts_utils_task.md.CKtzFtLD.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_sort_heap_index.md.C3Cye002.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.CwYSFKqd.lean.js",
"/ran/manifest.json",
"/ran/404.html",
"/ran/icon_192.png",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/index.html",
"/ran/icon_48.png",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/babel.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/icon.png",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/home.svg",
"/ran/icon_72.png",
"/ran/logo.png",
"/ran/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
];
const VERSION = "1748155440";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



