const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_192.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/icon_96.png",
"/ran/hashmap.json",
"/ran/icon.png",
"/ran/sw1729749271.js",
"/ran/screenshots_748x1340.jpg",
"/ran/assets/cn_src_ranui_player_index.md.BvO-ZPUB.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.Bv80vbDr.lean.js",
"/ran/assets/src_ranui_radar_index.md.BSpXJKz9.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CORH3AVv.js",
"/ran/assets/src_ranui_input_index.md.B9JC-rZF.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CR97UVoR.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CR97UVoR.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Dupwx_46.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_article_docPreview.md.BVX_6-uD.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranuts_bundler_index.md.CzK9fGAV.js",
"/ran/assets/cn_src_article_sort_index.md.BWSyOxNi.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_article_sort_count_index.md.ByJjT6Pm.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BcdJkkzH.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranui_preview_index.md.CzMJoaXZ.lean.js",
"/ran/assets/src_article_bundle.md.DfORQREl.js",
"/ran/assets/src_ranui_popover_index.md.DMTBoYRO.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CtX-3EGD.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.vFi-t3ID.js",
"/ran/assets/cn_src_ranui_math_index.md.Dm7u2TBg.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_types_高级类型.md.C802O0og.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BNoMYUrr.lean.js",
"/ran/assets/cn_src_ranui_index.md.BZskbsxs.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.-xlJ8TJp.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.xNy_A-VH.js",
"/ran/assets/src_article_javascript_domLoad.md.DtqaOXwc.js",
"/ran/assets/cn_src_note_ubuntu.md.CCeZauTL.js",
"/ran/assets/src_ranuts_utils_filterObj.md.DYIMAQuR.js",
"/ran/assets/src_article_astParse_tokenizer.md.GTPkiLVl.js",
"/ran/assets/cn_src_article_docPreview.md.BVX_6-uD.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranui_tab_index.md.DiuVEbUk.js",
"/ran/assets/src_ranui_select_index.md.DNjPQH94.lean.js",
"/ran/assets/cn_src_article_visual.md.B-XOjl6b.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.Tlw2krAI.lean.js",
"/ran/assets/src_article_sort_select_index.md.DEFaVGwT.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_message_index.md.CDLU3VjS.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranuts_file_writeFile.md.BQWyoqGt.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.DVhr9dM3.js",
"/ran/assets/cn_src_article_typescript_recursion.md.FlMWh47v.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BnwcakHK.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CQAT4yXf.js",
"/ran/assets/src_ranuts_utils_formatJson.md.B8wheGFR.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_math_index.md.Dm7u2TBg.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BguvAA-h.lean.js",
"/ran/assets/src_types_模式匹配.md.BhGRRfSh.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.D9MI4-Rr.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_typescript_unionType.md.CVgGXdwK.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DtqYhwzQ.js",
"/ran/assets/src_ranuts_index.md.wEYUhvdc.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.CzMJoaXZ.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_bundle.md.bnyO-Xx5.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.52SjANpH.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BwHlmer5.js",
"/ran/assets/src_article_astParse_tokenizer.md.GTPkiLVl.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.JKr3cf5C.js",
"/ran/assets/cn_src_ranui_button_index.md.U4jqLa72.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/app.CkEC-l1-.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_ranui_loading_index.md.BANSW8CB.lean.js",
"/ran/assets/src_ranuts_index.md.wEYUhvdc.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BRPh8zQZ.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/index.md.Dnl_fP6i.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.Bv80vbDr.js",
"/ran/assets/cn_src_ranui_modal_index.md.pIFGJFcF.lean.js",
"/ran/assets/src_article_typescript_unionType.md.84KYTUfh.js",
"/ran/assets/src_article_babel.md.DPjLANas.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_modal_index.md.BwX6o5rJ.lean.js",
"/ran/assets/cn_src_ranuts_index.md.gUaBtuTh.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_ranui_preview_index.md.BZDv3wiH.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BRPh8zQZ.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_note_centos.md.BuzVjvZX.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranuts_utils_ocr.md.B_29Pl2g.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranuts_bundler_index.md.CzK9fGAV.lean.js",
"/ran/assets/cn_src_article_babel.md.COZcOklu.js",
"/ran/assets/src_article_typescript_calculate.md.CvMu_j8y.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranuts_utils_getCookie.md.Cp59N19W.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CVPVcX5s.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranui_input_index.md.CQcgv3zA.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_article_sort_index.md.BWSyOxNi.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_index.md.AOL1CUk6.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.GX6OsX0j.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.C6pL4kT_.lean.js",
"/ran/assets/cn_src_ranui_index.md.BZskbsxs.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B9b0UzC3.lean.js",
"/ran/assets/cn_src_note_centos.md.BuzVjvZX.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Bmhrd36x.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_heap_index.md.CAvPBDVl.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BOiTvIlY.js",
"/ran/assets/src_article_babel.md.DPjLANas.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DYXjia-d.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_loading_index.md.C-yFQjTs.lean.js",
"/ran/assets/src_article_sort_insert_index.md.N13WIRxh.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.Bta82Emh.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_imagemin.md.kk4ILZnD.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DOhN7_-8.lean.js",
"/ran/assets/src_article_sort_merge_index.md.Dupwx_46.lean.js",
"/ran/assets/index.md.Dnl_fP6i.lean.js",
"/ran/assets/src_ranui_popover_index.md.DMTBoYRO.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CYoI3e0m.lean.js",
"/ran/assets/cn_src_note_docker.md.BvEZj3JL.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CA9dUDcd.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.bhQUctIu.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CQcgv3zA.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D4TJA2Pm.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.K1q_y9BL.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ct6CWSH9.lean.js",
"/ran/assets/src_ranui_progress_index.md.CpGzRBPW.js",
"/ran/assets/src_types_类型运算.md.CLvtE3Cz.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CORH3AVv.lean.js",
"/ran/assets/src_ranui_message_index.md.jtWrlycK.lean.js",
"/ran/assets/cn_src_article_visual.md.B-XOjl6b.js",
"/ran/assets/src_ranui_index.md.BjMEC1b7.lean.js",
"/ran/assets/src_ranuts_utils_task.md.D1MZ7yb1.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BnwcakHK.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_typescript_pattern.md.8Qq9h-Dq.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_typescript_calculate.md.CvMu_j8y.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DOhN7_-8.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BNoMYUrr.js",
"/ran/assets/cn_src_article_systemDesign.md.DNYzlzez.js",
"/ran/assets/cn_src_ranui_button_index.md.U4jqLa72.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_sort_radix_index.md.DYXjia-d.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.CtX-3EGD.js",
"/ran/assets/src_article_typescript_recursion.md.B7ku97vf.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DwhR4L4w.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Dtwk_5ZM.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.8Qq9h-Dq.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Byj3E6z-.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranui_icon_index.md.LmUCT7p3.js",
"/ran/assets/cn_src_note_ubuntu.md.CCeZauTL.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_progress_index.md.CpGzRBPW.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.D9MI4-Rr.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_article_typescript_recursion.md.B7ku97vf.js",
"/ran/assets/cn_src_article_sort_count_index.md.ByJjT6Pm.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.BwHlmer5.lean.js",
"/ran/assets/src_article_sort_select_index.md.DEFaVGwT.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranui_player_index.md.CW6LWhZh.js",
"/ran/assets/src_ranui_message_index.md.jtWrlycK.js",
"/ran/assets/src_ranui_skeleton_index.md.Bta82Emh.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_typescript_unionType.md.84KYTUfh.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BcdJkkzH.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_utils_task.md.B2Qy8taO.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_checkbox_index.md.jrcbKI3r.js",
"/ran/assets/src_article_sort_index.md.teCO1Zl9.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CYETO48j.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_file_readFile.md.DdpfnxUN.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CA9dUDcd.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranui_preview_index.md.BZDv3wiH.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranui_popover_index.md.Bv3ly7uM.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_article_typescript_index.md.eEEBzLkL.lean.js",
"/ran/assets/src_ranui_tab_index.md.DiuVEbUk.lean.js",
"/ran/assets/style.Cyvf57FJ.css",
"/ran/assets/cn_src_types_模式匹配.md.BwE3GBAX.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_ranui_player_index.md.CW6LWhZh.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.CB7TCOic.js",
"/ran/assets/src_ranuts_file_writeFile.md.BQWyoqGt.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BOiTvIlY.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_ranui_icon_index.md.JKr3cf5C.lean.js",
"/ran/assets/src_article_functionalProgramming.md.UxBXZNJ3.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.DVhr9dM3.lean.js",
"/ran/assets/cn_src_types_TS类型.md.BTfGE68o.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_tabs_index.md.Bmhrd36x.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.vFi-t3ID.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.bhQUctIu.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CBTBY_EC.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranuts_binaryTree_index.md.Bnu-3MO3.lean.js",
"/ran/assets/src_ranui_button_index.md.CnhegMf9.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BTWtegf2.js",
"/ran/assets/src_ranui_image_index.md.4k5r5xH6.lean.js",
"/ran/assets/src_article_typescript_index.md.1kFpCdFR.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BYufiJcM.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CYoI3e0m.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_file_readFile.md.C6pL4kT_.js",
"/ran/assets/src_ranuts_utils_task.md.D1MZ7yb1.js",
"/ran/assets/src_article_sort_count_index.md.BhgdAx8c.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_designMode.md.Kr1-vob-.js",
"/ran/assets/cn_src_article_functionalProgramming.md.CYETO48j.js",
"/ran/assets/src_article_typescript_index.md.1kFpCdFR.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.GX6OsX0j.js",
"/ran/assets/cn_src_types_高级类型.md.CHF9InRL.js",
"/ran/assets/cn_src_ranui_radar_index.md.Byj3E6z-.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.DYIMAQuR.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_article_sort_shell_index.md.DCDYXBZM.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.jrcbKI3r.lean.js",
"/ran/assets/src_ranui_select_index.md.DNjPQH94.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_tabs_index.md.Ch0X-BTK.js",
"/ran/assets/src_article_sort_insert_index.md.N13WIRxh.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BWxrKtpv.lean.js",
"/ran/assets/cn_src_article_bundle.md.bnyO-Xx5.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranui_loading_index.md.BANSW8CB.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.52SjANpH.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B0wU2XKV.js",
"/ran/assets/src_article_sort_bucket_index.md.Cad3vf8u.js",
"/ran/assets/src_ranui_button_index.md.CnhegMf9.js",
"/ran/assets/src_ranui_index.md.BjMEC1b7.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_player_index.md.BvO-ZPUB.js",
"/ran/assets/src_ranuts_utils_ocr.md.B_29Pl2g.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BWxrKtpv.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_types_类型运算.md.DpVYGLfr.js",
"/ran/assets/cn_src_ranuts_index.md.gUaBtuTh.lean.js",
"/ran/assets/cn_src_article_designMode.md.Kr1-vob-.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DjJtxuOS.js",
"/ran/assets/src_ranui_radar_index.md.BSpXJKz9.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_types_类型运算.md.DpVYGLfr.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DdpfnxUN.js",
"/ran/assets/cn_src_article_sort_select_index.md.GubMS7bH.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.K1q_y9BL.js",
"/ran/assets/src_article_functionalProgramming.md.UxBXZNJ3.js",
"/ran/assets/cn_src_article_typescript_unionType.md.CVgGXdwK.js",
"/ran/assets/chunks/framework.Dtt2e6Oj.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/pwa-install.es.DxPypONK.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/theme.BzNT_Wat.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/index-Co9E57uv.b4L0fBlj.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/@localSearchIndexcn.D1n4CQS6.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.BoNPjlB6.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/index.BIc2vuKw.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/VPLocalSearchBox.DHkk9WSb.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/@localSearchIndexroot.B-YtsjLm.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CnVjqjpl.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/index-Ba501-HG.D-o3KsZG.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/src_article_designMode.md.T4uXpwR4.js",
"/ran/assets/src_ranuts_binaryTree_index.md.Bnu-3MO3.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DtqYhwzQ.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.eEEBzLkL.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_utils_formatJson.md.B8wheGFR.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Ct6CWSH9.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B9b0UzC3.js",
"/ran/assets/src_article_typescript_reconstruction.md.h8DD3mHZ.js",
"/ran/assets/cn_src_types_高级类型.md.CHF9InRL.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_types_高级类型.md.C802O0og.js",
"/ran/assets/cn_src_article_video.md.D_UFuNFZ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.FlMWh47v.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DjJtxuOS.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.B0wU2XKV.lean.js",
"/ran/assets/cn_src_article_babel.md.COZcOklu.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DvrCbunu.js",
"/ran/assets/src_article_javascript_domLoad.md.DtqaOXwc.lean.js",
"/ran/assets/src_article_imagemin.md.C2uPdTTw.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Cqsp_re2.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Dtwk_5ZM.js",
"/ran/assets/src_article_sort_heap_index.md.CAvPBDVl.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D4TJA2Pm.js",
"/ran/assets/cn_src_article_systemDesign.md.DNYzlzez.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.GubMS7bH.js",
"/ran/assets/cn_src_ranui_loading_index.md.C-yFQjTs.js",
"/ran/assets/cn_src_ranui_image_index.md.DvrCbunu.lean.js",
"/ran/assets/src_ranui_math_index.md.CnPhTYaw.js",
"/ran/assets/src_article_sort_shell_index.md.DCDYXBZM.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_article_imagemin.md.kk4ILZnD.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_article_designMode.md.T4uXpwR4.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_article_sort_quick_index.md.D36P2Wen.lean.js",
"/ran/assets/src_article_sort_radix_index.md.9YTSd7z8.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CVPVcX5s.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.-xlJ8TJp.js",
"/ran/assets/src_article_sort_bucket_index.md.Cad3vf8u.lean.js",
"/ran/assets/src_types_模式匹配.md.BhGRRfSh.js",
"/ran/assets/cn_src_ranui_modal_index.md.pIFGJFcF.js",
"/ran/assets/src_ranui_math_index.md.CnPhTYaw.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.CB7TCOic.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_javascript_domLoad.md.CmEBWIvv.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_article_bundle.md.DfORQREl.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranuts_mimeType_mimeType.md.CQAT4yXf.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Tlw2krAI.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_note_docker.md.BvEZj3JL.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BYufiJcM.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CBTBY_EC.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DZiy3jsf.lean.js",
"/ran/assets/src_article_sort_index.md.teCO1Zl9.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.Cp59N19W.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_ranui_message_index.md.CDLU3VjS.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DZiy3jsf.js",
"/ran/assets/src_ranui_tabs_index.md.Ch0X-BTK.lean.js",
"/ran/assets/src_article_sort_radix_index.md.9YTSd7z8.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.BTWtegf2.lean.js",
"/ran/assets/src_ranui_input_index.md.B9JC-rZF.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_typescript_reconstruction.md.h8DD3mHZ.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Bv3ly7uM.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_modal_index.md.BwX6o5rJ.js",
"/ran/assets/src_article_sort_count_index.md.BhgdAx8c.lean.js",
"/ran/assets/cn_src_types_TS类型.md.BTfGE68o.lean.js",
"/ran/assets/src_article_imagemin.md.C2uPdTTw.js",
"/ran/assets/src_types_TS类型.md.BicJqbUC.js",
"/ran/assets/cn_index.md.AOL1CUk6.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.B2Qy8taO.js",
"/ran/assets/src_ranuts_file_readDir.md.xNy_A-VH.lean.js",
"/ran/assets/src_ranui_icon_index.md.LmUCT7p3.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.CmEBWIvv.js",
"/ran/assets/cn_src_types_模式匹配.md.BwE3GBAX.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DwhR4L4w.lean.js",
"/ran/assets/src_types_TS类型.md.BicJqbUC.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_video.md.D_UFuNFZ.js",
"/ran/assets/src_types_类型运算.md.CLvtE3Cz.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranui_image_index.md.4k5r5xH6.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BguvAA-h.js",
"/ran/assets/src_article_sort_quick_index.md.D36P2Wen.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Cqsp_re2.js",
"/ran/screenshots_2560x1440.jpg",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/manifest.json",
"/ran/favicon.ico",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/icon_72.png",
"/ran/cn/index.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/icon_168.png",
"/ran/home.svg",
"/ran/icon_48.png",
"/ran/404.html",
];
const VERSION = "1729749271";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



