const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/hashmap.json",
"/ran/sw1715764226.js",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/manifest.json",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/home.svg",
"/ran/favicon.ico",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_786dd1d.pf_fragment",
"/ran/pagefind/fragment/en_c9c7c59.pf_fragment",
"/ran/pagefind/fragment/en_2942c3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bf95b6d.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2f9227.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_c84c5e7.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f6f6ef.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fc196ed.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/en_51f248e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_75d5dcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_41cce7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_77ed13c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cab01af.pf_fragment",
"/ran/pagefind/fragment/en_216410c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_a56cec5.pf_fragment",
"/ran/pagefind/fragment/en_4afe46f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_4873c44.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_31bb7a6.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_89d34e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_8e7817f.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1becf92.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_5f9a7eb.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d9642ae.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6655e03.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_d792b8c.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_7a4ca4f.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/en_d810afe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7ba21c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2a97201.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_77e0291.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_ca77806.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_279c02b.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_b52b4a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_976d864.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_45694f5.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5b9af99.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c37ca1c.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind.zh-cn_f47482fe15130.pf_meta",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.en_413ace86cd.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/index/zh-cn_b9c3d44.pf_index",
"/ran/pagefind/index/en_23e2aa6.pf_index",
"/ran/pagefind/index/zh-cn_8fcac3c.pf_index",
"/ran/pagefind/index/en_db315e8.pf_index",
"/ran/pagefind/index/zh-cn_88dd18a.pf_index",
"/ran/pagefind/index/en_d9aa498.pf_index",
"/ran/pagefind/index/zh-cn_a712671.pf_index",
"/ran/index.html",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/assets/cn_src_article_sort_select_index.md.ZCWAk3-H.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BVLqeBLp.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.6dQn426O.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_bubble_index.md.Col1GLMV.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.Bt7mpz96.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_checkbox_index.md.CQiFKElf.js",
"/ran/assets/cn_src_ranui_message_index.md.CaJkIwmI.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BrEQK95o.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.XwNaAvue.js",
"/ran/assets/src_ranuts_utils_str2xml.md.6dQn426O.js",
"/ran/assets/src_ranuts_file_readDir.md.W8Oz8LWA.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CBcp5l39.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_javascript_domLoad.md.BMxMVTf2.lean.js",
"/ran/assets/src_ranui_icon_index.md.DHW2RQQ9.lean.js",
"/ran/assets/src_article_sort_heap_index.md.0syfn6Es.js",
"/ran/assets/src_ranui_tab_index.md.D6kmrQL4.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranui_radar_index.md.CbPH-Ll2.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.wz67klbC.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_types_高级类型.md.Br8jpmEH.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.CiQTOYo8.js",
"/ran/assets/src_ranui_tab_index.md.D6kmrQL4.js",
"/ran/assets/cn_src_article_typescript_index.md.4Rp9pJR0.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_article_astParse_tokenizer.md.BchejQ_2.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranuts_file_appendFile.md.Cbc9IiOX.lean.js",
"/ran/assets/src_article_typescript_pattern.md.z21_uWbS.js",
"/ran/assets/src_article_sort_bucket_index.md.CAHgx3hn.lean.js",
"/ran/assets/cn_src_article_bundle.md.BYmLZV3W.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DgTtsdks.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.C2Rg_UDw.js",
"/ran/assets/src_ranui_modal_index.md.C11OXG6Q.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.BCS9gxR1.js",
"/ran/assets/src_ranuts_file_readDir.md.W8Oz8LWA.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_astParse_tokenizer.md.BCS9gxR1.lean.js",
"/ran/assets/src_article_typescript_pattern.md.z21_uWbS.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B2-F3jM5.js",
"/ran/assets/cn_src_ranui_popover_index.md.BKOKdxfZ.js",
"/ran/assets/src_ranui_button_index.md.D3RsleUR.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md._-Hx9tLj.js",
"/ran/assets/cn_src_ranui_tab_index.md.rsyWZ2OH.lean.js",
"/ran/assets/src_article_typescript_calculate.md.BrEQK95o.js",
"/ran/assets/src_ranui_message_index.md.BtVAiAqq.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CO9oth0k.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B7fVCz6U.js",
"/ran/assets/src_ranuts_utils_formatJson.md.TK4WfN4i.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CFq2jUQn.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.PYb4v7dD.js",
"/ran/assets/cn_src_ranui_loading_index.md.BZ9JB45g.lean.js",
"/ran/assets/src_article_sort_quick_index.md.ChxWvu2u.js",
"/ran/assets/src_ranui_progress_index.md.C3cPgqUj.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CBcp5l39.js",
"/ran/assets/src_article_sort_index.md.BY1uNuI9.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_ranuts_utils_task.md.CIEsEixO.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BOmuPCzn.lean.js",
"/ran/assets/cn_src_types_高级类型.md.Br8jpmEH.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BKIPR-_F.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_index.md.W0guJFQZ.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.C0Fva9oi.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BkkM-OIP.lean.js",
"/ran/assets/src_article_sort_index.md.BY1uNuI9.js",
"/ran/assets/src_article_sort_radix_index.md.DZEceG5j.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/index.md.CRPo-R4q.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BKIPR-_F.lean.js",
"/ran/assets/src_article_typescript_index.md.CfA-E8uN.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_utils_ocr.md.CiQTOYo8.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Bkf9kTag.js",
"/ran/assets/src_ranui_radar_index.md.CIb6jeM8.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_sort_count_index.md.xmEspuny.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.BGml5oYO.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_types_模式匹配.md.CYaqlY6I.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranuts_file_readDir.md.BLrB46p0.lean.js",
"/ran/assets/src_ranui_radar_index.md.CIb6jeM8.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BOmuPCzn.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CLiUndYk.js",
"/ran/assets/src_article_sort_select_index.md.BWzBGdQT.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.C-yweqH9.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_readFile.md.BLNG7IQi.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.7HxwKjnp.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DtTfM4JO.js",
"/ran/assets/src_ranuts_bundler_index.md.Bs5dChVc.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BbHB5kPS.js",
"/ran/assets/src_ranui_preview_index.md.CCxEwrtH.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C56hL-wd.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BUvAKF5H.js",
"/ran/assets/app.BHNpcixZ.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.C0Fva9oi.lean.js",
"/ran/assets/src_types_TS类型.md.BF6QyHb8.js",
"/ran/assets/cn_src_article_sort_count_index.md.XbDOlFNp.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BDfghy_a.js",
"/ran/assets/cn_src_ranui_radar_index.md.CbPH-Ll2.js",
"/ran/assets/src_article_sort_radix_index.md.DZEceG5j.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BkjojaXW.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.KelF2awp.js",
"/ran/assets/src_types_类型运算.md.-22jdKRP.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.CAHgx3hn.js",
"/ran/assets/cn_src_article_sort_index.md.B67by2HT.lean.js",
"/ran/assets/src_ranui_button_index.md.D3RsleUR.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BLrB46p0.js",
"/ran/assets/cn_src_ranui_index.md.Z4xw9R2O.js",
"/ran/assets/cn_src_article_sort_shell_index.md.kvxhPFvC.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BG_m7hJT.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.BKOKdxfZ.lean.js",
"/ran/assets/src_ranui_preview_index.md.CCxEwrtH.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_image_index.md.2nMskqDb.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CC5V9E_l.js",
"/ran/assets/src_ranui_select_index.md.DvnlfjsK.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.BF4cRoEs.js",
"/ran/assets/cn_src_ranui_player_index.md.DrAUxDjD.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BfgRzSPF.lean.js",
"/ran/assets/cn_src_article_designMode.md.B6cC8bej.lean.js",
"/ran/assets/src_ranuts_index.md.Mkt-ZPve.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_ranui_message_index.md.BtVAiAqq.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.KelF2awp.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_designMode.md.BpNZQVB6.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.D73H5G3I.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BMxMVTf2.js",
"/ran/assets/cn_src_article_imagemin.md.D-srEpzd.js",
"/ran/assets/cn_src_types_类型运算.md.Dpog5a1B.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BWSz1fE0.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.ChK4GBAL.js",
"/ran/assets/src_ranuts_file_readFile.md.DcYKZn9w.js",
"/ran/assets/src_ranui_progress_index.md.C3cPgqUj.js",
"/ran/assets/src_ranui_select_index.md.DvnlfjsK.js",
"/ran/assets/src_ranuts_utils_filterObj.md.C2Rg_UDw.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.1iyG_NrT.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DGWUxfFo.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_article_typescript_index.md.CfA-E8uN.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BfgRzSPF.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_types_TS类型.md.DXHPwTC_.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DRC18Kkv.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BkkM-OIP.js",
"/ran/assets/src_ranuts_mode_subscribe.md.ChK4GBAL.lean.js",
"/ran/assets/src_article_sort_insert_index.md.k3BrrtMz.js",
"/ran/assets/cn_src_ranui_button_index.md.BUvAKF5H.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.NnML78n3.lean.js",
"/ran/assets/src_types_模式匹配.md.BgQC7EIR.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.Bkf9kTag.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BgQDUkQH.lean.js",
"/ran/assets/style.CEZ6NMd9.css",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_article_javascript_domLoad.md.Cfxm_7Rn.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_babel.md.D0xA2k4P.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_ranui_select_index.md.BGml5oYO.lean.js",
"/ran/assets/src_article_sort_insert_index.md.k3BrrtMz.lean.js",
"/ran/assets/cn_src_article_designMode.md.B6cC8bej.js",
"/ran/assets/cn_src_ranui_loading_index.md.BZ9JB45g.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Ck34eB-G.js",
"/ran/assets/src_article_sort_quick_index.md.ChxWvu2u.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_imagemin.md.D-srEpzd.lean.js",
"/ran/assets/src_ranui_loading_index.md.ucfmJC12.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B7fVCz6U.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Cw6neCCD.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.Cbc9IiOX.js",
"/ran/assets/cn_src_types_类型运算.md.Dpog5a1B.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.4Rp9pJR0.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DGWUxfFo.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_article_bundle.md.BYmLZV3W.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_article_sort_shell_index.md.kvxhPFvC.js",
"/ran/assets/src_ranui_index.md.Bee2zIH1.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_player_index.md.Qa6-izXs.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.7HxwKjnp.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DLGoNR2E.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.DcYKZn9w.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.BchejQ_2.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.wz67klbC.lean.js",
"/ran/assets/src_ranuts_utils_task.md.CJ2aKhmK.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_babel.md.D0xA2k4P.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BG_m7hJT.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.TYC5vPxZ.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BbHB5kPS.lean.js",
"/ran/assets/src_ranui_tabs_index.md.Dkng4hGm.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_index.md.W0guJFQZ.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/index.IX-AS0Fn.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index-Dapt713u.CjjppSYq.js",
"/ran/assets/chunks/theme.CBqr-ZZr.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/index-BHmWrPCW.C9ftDjGd.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/pwa-install.es.BZyo4fnY.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/docx-CChZ5Ycr.NiVSZbPW.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/pdf-DpNqCylD.5f58SJ1a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/framework.DU63L2vM.js",
"/ran/assets/chunks/jszip.min-DD9Dc6z4.BsDI-Ugu.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/src_ranuts_utils_getCookie.md.D73H5G3I.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.C56hL-wd.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DLGoNR2E.js",
"/ran/assets/cn_src_types_TS类型.md.DXHPwTC_.js",
"/ran/assets/src_ranui_checkbox_index.md.CQiFKElf.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.XbDOlFNp.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_input_index.md.Dzb1htdr.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.1iyG_NrT.js",
"/ran/assets/src_ranui_modal_index.md.C11OXG6Q.js",
"/ran/assets/src_article_babel.md.r59ABdaj.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_article_typescript_recursion.md.CliMcH-C.lean.js",
"/ran/assets/src_ranui_player_index.md.Qa6-izXs.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.B2-F3jM5.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.B-wSLsnw.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CliMcH-C.js",
"/ran/assets/cn_src_ranui_progress_index.md.NR2Vb16q.lean.js",
"/ran/assets/src_article_bundle.md.CKZAx6pb.lean.js",
"/ran/assets/src_article_sort_count_index.md.xmEspuny.js",
"/ran/assets/src_article_typescript_reconstruction.md.NnML78n3.js",
"/ran/assets/src_ranui_image_index.md.2nMskqDb.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BLNG7IQi.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C0ZSIXtQ.lean.js",
"/ran/assets/src_article_imagemin.md.B3anyYCX.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CE6nR7gB.js",
"/ran/assets/src_types_类型运算.md.-22jdKRP.js",
"/ran/assets/src_article_sort_merge_index.md.CO9oth0k.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CdlvVfDY.js",
"/ran/assets/src_ranui_popover_index.md.C77tXCd1.js",
"/ran/assets/cn_src_ranui_player_index.md.DrAUxDjD.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DgTtsdks.js",
"/ran/assets/cn_src_article_sort_index.md.B67by2HT.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranuts_utils_task.md.CJ2aKhmK.lean.js",
"/ran/assets/src_ranui_index.md.Bee2zIH1.lean.js",
"/ran/assets/src_ranui_tabs_index.md.Dkng4hGm.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.BgQDUkQH.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.Ck34eB-G.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_modal_index.md.C-yweqH9.js",
"/ran/assets/src_article_sort_heap_index.md.0syfn6Es.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CC5V9E_l.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.PYb4v7dD.lean.js",
"/ran/assets/src_types_高级类型.md.DLWejwah.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.Bt7mpz96.js",
"/ran/assets/src_ranui_loading_index.md.ucfmJC12.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.TK4WfN4i.lean.js",
"/ran/assets/src_ranui_icon_index.md.DHW2RQQ9.js",
"/ran/assets/src_article_sort_select_index.md.BWzBGdQT.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DtTfM4JO.lean.js",
"/ran/assets/src_types_高级类型.md.DLWejwah.js",
"/ran/assets/src_article_sort_shell_index.md.dQE-fG5j.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Cw6neCCD.js",
"/ran/assets/src_article_babel.md.r59ABdaj.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_ranuts_binaryTree_index.md.ZO72QbNi.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.CYaqlY6I.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CaJkIwmI.js",
"/ran/assets/cn_src_ranui_index.md.Z4xw9R2O.lean.js",
"/ran/assets/src_article_functionalProgramming.md.BynBXDCa.js",
"/ran/assets/src_types_模式匹配.md.BgQC7EIR.js",
"/ran/assets/src_article_typescript_unionType.md.C937f1pd.js",
"/ran/assets/src_ranuts_bundler_index.md.Bs5dChVc.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_article_sort_shell_index.md.dQE-fG5j.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.ZCWAk3-H.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.CFq2jUQn.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BDfghy_a.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BkjojaXW.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.B-wSLsnw.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BVLqeBLp.lean.js",
"/ran/assets/src_article_typescript_unionType.md.C937f1pd.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranui_popover_index.md.C77tXCd1.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_typescript_calculate.md.XwNaAvue.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.Col1GLMV.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_input_index.md.Dzb1htdr.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.CE6nR7gB.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.ZO72QbNi.js",
"/ran/assets/src_article_functionalProgramming.md.BynBXDCa.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md._-Hx9tLj.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.NR2Vb16q.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CIEsEixO.js",
"/ran/assets/index.md.CRPo-R4q.js",
"/ran/assets/src_article_imagemin.md.B3anyYCX.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CLiUndYk.lean.js",
"/ran/assets/src_ranuts_index.md.Mkt-ZPve.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C0ZSIXtQ.js",
"/ran/assets/src_article_bundle.md.CKZAx6pb.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_javascript_domLoad.md.Cfxm_7Rn.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CdlvVfDY.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DRC18Kkv.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.TYC5vPxZ.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.BWSz1fE0.js",
"/ran/assets/src_ranui_skeleton_index.md.BF4cRoEs.lean.js",
"/ran/assets/src_article_designMode.md.BpNZQVB6.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_tab_index.md.rsyWZ2OH.js",
"/ran/assets/src_types_TS类型.md.BF6QyHb8.lean.js",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/icon_48.png",
"/ran/icon.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/babel.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/bundle.html",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/bundle.html",
"/ran/icon_144.png",
];
const VERSION = "1715764226";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



