const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_types_类型运算.md.gXFBnQrF.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.eb9QgrQA.js",
"/ran/assets/cn_src_article_bundle.md.B6nYyb54.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.Dc1XBRRO.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_note_centos.md.CavCjYTu.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.D1XgkN19.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_index.md.CcWAVaMJ.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CNwTIu6x.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_note_docker.md.B0ip4CsC.js",
"/ran/assets/cn_src_ranui_index.md.PZ05JZyQ.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BWvHgopA.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranuts_file_file_info.md.6mmCg5sH.lean.js",
"/ran/assets/src_ranui_image_index.md.ClH5QClZ.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_imagemin.md.DpghQG0N.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.D5yDYO1h.lean.js",
"/ran/assets/index.md.GD-HrXAd.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranui_player_index.md.BTbIaoZW.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.Cu2kiRsj.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DRbw0377.lean.js",
"/ran/assets/src_ranui_progress_index.md.DlcPZg9_.js",
"/ran/assets/src_article_sort_shell_index.md.DGTKYE0H.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.BSQIbKLE.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DJyh-OUw.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Wyq18d0f.lean.js",
"/ran/assets/src_article_sort_index.md.Ceb36WDh.lean.js",
"/ran/assets/src_ranuts_utils_task.md.BahA7WhB.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DJyh-OUw.lean.js",
"/ran/assets/src_article_typescript_union_type.md.C7l44Z4_.js",
"/ran/assets/app.BPyhD7ep.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_babel.md.C4WNR9Sq.js",
"/ran/assets/src_ranuts_file_append_file.md.D5xOR6R9.js",
"/ran/assets/cn_src_article_sort_select_index.md.BmhhDD3_.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_article_sort_heap_index.md.pTUxtPLd.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_typescript_pattern.md.6piAPtVh.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DAZC8cih.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CSaYXTYK.js",
"/ran/assets/src_types_模式匹配.md.mzX7T0AS.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.D2n2ds-m.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_article_design_mode.md.CgdrH4IR.js",
"/ran/assets/cn_src_note_docker.md.B0ip4CsC.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.pTUxtPLd.js",
"/ran/assets/cn_src_article_sort_count_index.md.BhxIFXmr.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DUhQ2-Uf.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.7iMIYo4l.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Wyq18d0f.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_functional_programming.md.Bci-dMeP.js",
"/ran/assets/src_article_javascript_dom_load.md.Bz6_EXgr.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CzCHOU-0.lean.js",
"/ran/assets/cn_src_ranui_index.md.PZ05JZyQ.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.exv8Mt4M.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DRqCv8y2.js",
"/ran/assets/src_ranuts_file_read_dir.md.BSQIbKLE.js",
"/ran/assets/src_ranuts_binary_tree_index.md.Cq5XUpGZ.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.D5yDYO1h.js",
"/ran/assets/cn_src_ranui_progress_index.md.BHJIkJSA.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_math_index.md.C1JiHesz.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.6mmCg5sH.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_ranuts_file_append_file.md.D5xOR6R9.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BWvHgopA.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Dn_zUPzX.lean.js",
"/ran/assets/src_article_imagemin.md.DpghQG0N.js",
"/ran/assets/src_ranui_button_index.md.BS9t0uDe.js",
"/ran/assets/src_ranui_checkbox_index.md.KV-fZbW4.js",
"/ran/assets/cn_src_article_sort_index.md.DkMyJzkO.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DES57pjC.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DXJGHCl0.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.D1XgkN19.lean.js",
"/ran/assets/src_ranui_tab_index.md.wUq3fyon.lean.js",
"/ran/assets/src_article_typescript_union_type.md.C7l44Z4_.lean.js",
"/ran/assets/src_ranui_tab_index.md.wUq3fyon.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DfTRAyOW.js",
"/ran/assets/src_ranui_loading_index.md.BYDSirai.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_article_typescript_recursion.md.D87imvm8.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.7iMIYo4l.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.D2rsuPdB.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BHJIkJSA.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.-tfDAE3V.js",
"/ran/assets/src_article_sort_bubble_index.md.fo1xk9I_.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.Dj-LSAgs.js",
"/ran/assets/src_article_sort_select_index.md.BaHRpGx4.js",
"/ran/assets/cn_src_ranui_tab_index.md.CKCZdNKL.js",
"/ran/assets/src_types_TS类型.md.BUi0Xfr7.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_loading_index.md.Bemjs37b.js",
"/ran/assets/src_ranui_skeleton_index.md.-tfDAE3V.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.D5rR5inq.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_doc_preview.md.CgfGP8ic.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CKCZdNKL.lean.js",
"/ran/assets/src_article_typescript_pattern.md.6piAPtVh.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CE29ClZR.js",
"/ran/assets/src_types_高级类型.md.V4Wq5rvn.lean.js",
"/ran/assets/cn_src_article_video.md.Bojm0Rkw.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_typescript_recursion.md.DP2hm35a.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CSeKSBdR.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BpTpbhQe.lean.js",
"/ran/assets/cn_index.md.CcWAVaMJ.lean.js",
"/ran/assets/src_article_typescript_index.md.D2Bi9xcT.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C0gPG7y1.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DuoGKtW7.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BcdRc44j.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BJDrx3sT.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranuts_file_file_info.md.CSeKSBdR.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_types_TS类型.md.BUi0Xfr7.js",
"/ran/assets/src_types_模式匹配.md.mzX7T0AS.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_sort_insert_index.md.DDjKfESn.lean.js",
"/ran/assets/cn_src_types_类型运算.md.gXFBnQrF.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_javascript_dom_load.md.Bz6_EXgr.js",
"/ran/assets/cn_src_ranui_modal_index.md.CSaYXTYK.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.D-zFlea-.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_file_write_file.md.BNWk6I2Y.js",
"/ran/assets/cn_src_article_babel.md.DRUtH-37.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DnTvmksF.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.C0_lhadB.lean.js",
"/ran/assets/src_ranui_icon_index.md.DKeE9Bfs.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DP2hm35a.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_ranui_tabs_index.md.3KZgVrIN.js",
"/ran/assets/src_ranuts_bundler_index.md.DUhQ2-Uf.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.D7aJu8Q-.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.BmdP1864.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D6s0wOwz.lean.js",
"/ran/assets/src_ranui_button_index.md.BS9t0uDe.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.C5iB86ih.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Dn_zUPzX.js",
"/ran/assets/src_ranui_image_index.md.ClH5QClZ.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.C_6tnxyw.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Diop-eJW.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.Cxi5gbxR.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DRbw0377.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BqKlD0qs.js",
"/ran/assets/src_article_sort_radix_index.md.2D2np87L.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_image_index.md._9zTJMRO.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.C-oAAakF.js",
"/ran/assets/src_ranui_preview_index.md.Cr1oi_47.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.D4qjBP0c.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bdnp84kL.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_system_design.md.DWScNB72.js",
"/ran/assets/cn_src_article_visual.md.DSfWQ5G0.js",
"/ran/assets/src_article_sort_insert_index.md.BIusM5KE.js",
"/ran/assets/src_ranui_modal_index.md.AMRU5JL7.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.VYpA9YIP.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranuts_utils_get_cookie.md.Dj-LSAgs.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.D2rsuPdB.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.Diop-eJW.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CNwTIu6x.js",
"/ran/assets/src_ranui_progress_index.md.DlcPZg9_.lean.js",
"/ran/assets/src_types_类型运算.md.DSc4mgw6.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_article_doc_preview.md.CgfGP8ic.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CsI4_UtH.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_article_sort_insert_index.md.BIusM5KE.lean.js",
"/ran/assets/src_ranui_radar_index.md.BRbM0L7E.lean.js",
"/ran/assets/src_ranui_input_index.md.95YOSnUl.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.Bcof8buA.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_types_类型运算.md.DSc4mgw6.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BODe3mSr.js",
"/ran/assets/cn_src_ranui_input_index.md.Bt96Yimi.js",
"/ran/assets/cn_src_article_sort_index.md.DkMyJzkO.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B2SXKV-F.js",
"/ran/assets/cn_src_types_高级类型.md.w33HOLqS.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DnTvmksF.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DRqCv8y2.lean.js",
"/ran/assets/cn_src_types_高级类型.md.w33HOLqS.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranui_skeleton_index.md.D7aJu8Q-.js",
"/ran/assets/src_article_sort_bubble_index.md.fo1xk9I_.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bdnp84kL.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_bundle.md.B6nYyb54.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BhxIFXmr.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.Cu2kiRsj.lean.js",
"/ran/assets/src_article_typescript_index.md.D2Bi9xcT.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.VYpA9YIP.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DYsWnms9.js",
"/ran/assets/cn_src_ranui_icon_index.md.BYb5556N.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BfczAy-J.lean.js",
"/ran/assets/cn_src_ranui_image_index.md._9zTJMRO.lean.js",
"/ran/assets/src_ranuts_index.md.BfWz_HQM.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.DuoGKtW7.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_math_linear_algebra.md.C-oAAakF.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.B2SXKV-F.lean.js",
"/ran/assets/src_ranui_tabs_index.md.3KZgVrIN.lean.js",
"/ran/assets/src_ranui_input_index.md.95YOSnUl.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.CE29ClZR.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D0QpiR4n.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D87imvm8.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BE6rhiMx.js",
"/ran/assets/style.C7EChmqX.css",
"/ran/assets/src_article_sort_heap_index.md.Dt_Qd9Xb.js",
"/ran/assets/src_ranui_modal_index.md.AMRU5JL7.js",
"/ran/assets/src_article_bundle.md.Dg_F7NXd.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_ranui_radar_index.md.Cxi5gbxR.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_design_mode.md.CgdrH4IR.lean.js",
"/ran/assets/src_article_sort_count_index.md.BnA2s2J2.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_select_index.md.CoQo_waO.js",
"/ran/assets/cn_src_article_sort_select_index.md.BmhhDD3_.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BZFTkK6e.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.C0gPG7y1.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_math_index.md.DReoARd5.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DGTKYE0H.js",
"/ran/assets/src_ranuts_utils_task.md.BahA7WhB.js",
"/ran/assets/index.md.GD-HrXAd.js",
"/ran/assets/src_ranui_message_index.md.CZyv7t1b.lean.js",
"/ran/assets/cn_src_article_system_design.md.DWScNB72.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_preview_index.md.BE6rhiMx.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.C1JiHesz.js",
"/ran/assets/cn_src_ranui_icon_index.md.BYb5556N.lean.js",
"/ran/assets/src_article_babel.md.C4WNR9Sq.lean.js",
"/ran/assets/src_article_sort_quick_index.md.Cgde9fN-.js",
"/ran/assets/cn_src_article_imagemin.md.DX1OBlxR.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CtNeLWAM.lean.js",
"/ran/assets/cn_src_types_TS类型.md.D6s0wOwz.js",
"/ran/assets/src_article_design_mode.md.DJoX65ow.js",
"/ran/assets/cn_src_article_imagemin.md.DX1OBlxR.lean.js",
"/ran/assets/src_ranui_radar_index.md.BRbM0L7E.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BODe3mSr.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.BNWk6I2Y.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Bemjs37b.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.D-zFlea-.lean.js",
"/ran/assets/cn_src_article_video.md.Bojm0Rkw.js",
"/ran/assets/src_types_高级类型.md.V4Wq5rvn.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_index.md.BfWz_HQM.js",
"/ran/assets/src_ranui_preview_index.md.Cr1oi_47.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CtNeLWAM.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_article_sort_radix_index.md.2D2np87L.js",
"/ran/assets/src_article_sort_quick_index.md.Cgde9fN-.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BZFTkK6e.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_sort_heap_index.md.Dt_Qd9Xb.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.Bcof8buA.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.DXJGHCl0.js",
"/ran/assets/cn_src_ranuts_index.md.DkfT83qg.js",
"/ran/assets/cn_src_note_centos.md.CavCjYTu.js",
"/ran/assets/src_article_typescript_calculate.md.DW8G5g1X.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CsI4_UtH.js",
"/ran/assets/cn_src_article_typescript_union_type.md.C5iB86ih.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B-XwLjVH.js",
"/ran/assets/cn_src_ranui_button_index.md.eb9QgrQA.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.C_6tnxyw.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/theme.CfrhcQ-0.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/VPLocalSearchBox.CStcX096.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/@localSearchIndexroot.D5rsjEpj.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/index.B4NMFtci.js",
"/ran/assets/chunks/@localSearchIndexcn.CtfNLTiS.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.C_H7P7tY.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/pwa-install.es.CzNsYKNf.js",
"/ran/assets/src_ranui_index.md.ByjPbERg.lean.js",
"/ran/assets/src_article_sort_index.md.Ceb36WDh.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_input_index.md.Bt96Yimi.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D3-arM1U.js",
"/ran/assets/src_ranui_message_index.md.CZyv7t1b.js",
"/ran/assets/src_ranui_popover_index.md.CBjMzAmO.js",
"/ran/assets/cn_src_ranui_message_index.md.D5rR5inq.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BfczAy-J.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranui_math_index.md.DReoARd5.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_typescript_calculate.md.BcdRc44j.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.DfTRAyOW.lean.js",
"/ran/assets/src_article_design_mode.md.DJoX65ow.lean.js",
"/ran/assets/src_article_functional_programming.md.BjE1fJJT.lean.js",
"/ran/assets/src_article_sort_count_index.md.BnA2s2J2.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.BmdP1864.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BJDrx3sT.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.KV-fZbW4.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.D3-arM1U.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DYsWnms9.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_note_libreoffice2wasm.md.BqKlD0qs.lean.js",
"/ran/assets/src_ranui_icon_index.md.DKeE9Bfs.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_article_sort_shell_index.md.C0_lhadB.js",
"/ran/assets/src_ranui_player_index.md.BTbIaoZW.js",
"/ran/assets/cn_src_article_sort_quick_index.md.DR4R0uPp.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DW8G5g1X.js",
"/ran/assets/src_article_functional_programming.md.BjE1fJJT.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.Cq5XUpGZ.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_babel.md.DRUtH-37.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranui_select_index.md.D0QpiR4n.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_sort_merge_index.md.exv8Mt4M.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CzCHOU-0.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_javascript_dom_load.md.D2n2ds-m.lean.js",
"/ran/assets/cn_src_ranuts_index.md.DkfT83qg.lean.js",
"/ran/assets/src_ranui_select_index.md.CoQo_waO.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DAZC8cih.js",
"/ran/assets/src_ranuts_utils_ocr.md.H3n1NqYS.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranuts_utils_str2xml.md.DES57pjC.js",
"/ran/assets/src_ranui_index.md.ByjPbERg.js",
"/ran/assets/cn_src_article_functional_programming.md.Bci-dMeP.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_popover_index.md.CBjMzAmO.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.DR4R0uPp.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_visual.md.DSfWQ5G0.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranuts_utils_ocr.md.H3n1NqYS.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_article_sort_insert_index.md.DDjKfESn.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_article_sort_select_index.md.BaHRpGx4.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.D4qjBP0c.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.Dc1XBRRO.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranuts_utils_format_json.md.BpTpbhQe.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_loading_index.md.BYDSirai.js",
"/ran/assets/cn_src_ranui_tabs_index.md.B-XwLjVH.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_bundle.md.Dg_F7NXd.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/sw1743739247.js",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1743739247";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



