const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_note_libreoffice2wasm.md.su9li_Wo.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_modal_index.md.iTw0FSlc.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D184gZzJ.js",
"/ran/assets/cn_src_note_docker.md.D2TRVpDl.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_sort_index.md.DyfzEuVj.js",
"/ran/assets/cn_src_ranuts_index.md.Cx_oqped.lean.js",
"/ran/assets/src_ranuts_index.md.D_H93Pro.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_ranui_tab_index.md.B_eP9fdW.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_file_watch_file.md.74TKtcfU.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Db6BHsjv.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.C7XLq9kB.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.CB4a9zEv.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranui_skeleton_index.md.C7XLq9kB.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_typescript_calculate.md.DyAe0UJs.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DxFO7yDq.lean.js",
"/ran/assets/src_ranui_tabs_index.md.DUTrlUXB.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_article_typescript_reconstruction.md.uDmdmSNe.lean.js",
"/ran/assets/style.hH0-qZET.css",
"/ran/assets/src_article_babel.md.DuQw4dgY.lean.js",
"/ran/assets/cn_src_article_babel.md.D2qQHzlw.lean.js",
"/ran/assets/src_article_typescript_calculate.md.DyAe0UJs.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranuts_file_read_file.md.BXLuSeja.js",
"/ran/assets/cn_src_article_imagemin.md.HWLl8MTN.js",
"/ran/assets/cn_src_ranui_progress_index.md.C3XE0E-u.lean.js",
"/ran/assets/src_article_typescript_union_type.md.CFI42FnJ.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BxbWmHFv.js",
"/ran/assets/cn_src_ranui_button_index.md.DGvYFR0p.js",
"/ran/assets/src_ranuts_bundler_index.md.DyOHp0r7.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.ThSA9zuo.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.C4I9mlWH.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranui_progress_index.md.C3XE0E-u.js",
"/ran/assets/src_ranuts_file_watch_file.md.C_QnAwkT.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.RlKC78KH.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BSljVHQX.js",
"/ran/assets/cn_src_types_类型运算.md.YOFI7DPU.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_read_dir.md.1214KxzM.js",
"/ran/assets/src_article_javascript_dom_load.md.CwACBH_6.js",
"/ran/assets/src_ranui_message_index.md.CCMP3aJo.js",
"/ran/assets/cn_src_note_ubuntu.md.CZECdRCR.js",
"/ran/assets/src_article_babel.md.DuQw4dgY.js",
"/ran/assets/src_ranui_loading_index.md.Bpaz8F2s.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BK7iKecd.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.LYNeYz1Y.lean.js",
"/ran/assets/src_ranui_button_index.md.BkZ8-haa.js",
"/ran/assets/cn_src_article_functional_programming.md.C1_ge-xm.lean.js",
"/ran/assets/src_ranui_popover_index.md.BCQ34AWM.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranui_index.md.B69aq9Bi.js",
"/ran/assets/src_article_sort_insert_index.md.Bw6vsWkb.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.ytYOxmqe.js",
"/ran/assets/src_ranuts_bundler_index.md.DyOHp0r7.js",
"/ran/assets/src_article_typescript_recursion.md.C3_wqYN_.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.su9li_Wo.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Dhc4NZIo.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CRdVVeNg.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.rmzoISYn.lean.js",
"/ran/assets/src_types_类型运算.md.Co9c9kmo.js",
"/ran/assets/src_ranuts_utils_task.md.D9saVHPV.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B3f3ajgj.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranui_select_index.md.Devhny4S.lean.js",
"/ran/assets/index.md.D6U0vTF8.lean.js",
"/ran/assets/cn_src_types_TS类型.md.CVauAyIb.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.C_IsC_5P.lean.js",
"/ran/assets/src_ranui_radar_index.md.CGXR6upD.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_functional_programming.md.B19qqmri.js",
"/ran/assets/cn_src_ranui_math_index.md.n_eRaJG3.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CRjMu7lt.lean.js",
"/ran/assets/src_types_模式匹配.md.8Ubj-NJI.js",
"/ran/assets/cn_src_article_visual.md.DCSAogEy.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.2H0emn21.js",
"/ran/assets/cn_src_article_system_design.md.BLuDVEQT.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.ThSA9zuo.js",
"/ran/assets/src_article_bundle.md.CYi7n-It.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_message_index.md.CyuCkqQW.lean.js",
"/ran/assets/cn_src_article_sort_index.md.qtVcNBsr.js",
"/ran/assets/cn_src_ranui_player_index.md.LYNeYz1Y.js",
"/ran/assets/src_ranui_checkbox_index.md.DDUYyoww.js",
"/ran/assets/cn_src_ranui_modal_index.md.iTw0FSlc.lean.js",
"/ran/assets/src_ranui_index.md.C13Toi_y.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.BDXQVfSV.js",
"/ran/assets/cn_src_ranui_preview_index.md.Z1iILcIH.js",
"/ran/assets/src_ranui_input_index.md.BUf9Jq6V.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BnqZ7pEe.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.B6mHGcAm.lean.js",
"/ran/assets/src_types_TS类型.md.ZQF-IpHt.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_checkbox_index.md.DMcsva5o.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.8Pn_Aljs.js",
"/ran/assets/src_article_typescript_recursion.md.C3_wqYN_.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_sort_insert_index.md.Bw6vsWkb.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.C8WrpttU.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BChIkixD.js",
"/ran/assets/src_article_sort_quick_index.md.CSLrbdot.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.B6mHGcAm.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.C4I9mlWH.lean.js",
"/ran/assets/src_article_sort_count_index.md.qzP0b82S.js",
"/ran/assets/src_article_sort_radix_index.md.DbRvaX-r.js",
"/ran/assets/src_ranuts_file_file_info.md.Z4Ty_VCV.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranui_progress_index.md.ACB9DRU8.js",
"/ran/assets/src_ranui_modal_index.md.BFj0QVx7.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.D7YZi0xD.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_index.md.Crs7jZ0r.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.C13Kir38.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranuts_utils_filter_obj.md.BqiAKnez.js",
"/ran/assets/src_article_javascript_dom_load.md.CwACBH_6.lean.js",
"/ran/assets/src_article_sort_quick_index.md.CSLrbdot.js",
"/ran/assets/src_ranuts_utils_str2xml.md.tYMsh19G.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DawLCi-o.lean.js",
"/ran/assets/src_article_imagemin.md.CXdU5tSz.js",
"/ran/assets/cn_src_article_video.md.CHRxGstt.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DCCy-ngY.lean.js",
"/ran/assets/src_article_typescript_index.md.DzfVENHK.js",
"/ran/assets/src_ranui_button_index.md.BkZ8-haa.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DpfKV3YV.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranui_preview_index.md.B9lQfSEZ.js",
"/ran/assets/cn_src_ranui_popover_index.md.B06z5xH2.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DBAoF5gb.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_types_高级类型.md.CmCg1DnQ.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_article_sort_bubble_index.md.DRpAJUij.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_sort_count_index.md.C9URUlFj.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CCXuWt8v.lean.js",
"/ran/assets/src_ranui_tab_index.md.B_eP9fdW.js",
"/ran/assets/src_types_模式匹配.md.8Ubj-NJI.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BxbWmHFv.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.B_fUyNgW.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DIapDvz0.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.B1Qn-SYs.js",
"/ran/assets/cn_src_ranui_icon_index.md.TRJuw-I4.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Cpsfo9sk.js",
"/ran/assets/src_ranuts_file_file_info.md.Z4Ty_VCV.js",
"/ran/assets/cn_src_article_design_mode.md.D2XZUFSh.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BChIkixD.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CCXuWt8v.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_index.md.D_H93Pro.lean.js",
"/ran/assets/src_ranui_preview_index.md.B9lQfSEZ.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/app.CSFzWmnv.js",
"/ran/assets/src_ranui_player_index.md.D1PmHg2S.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_ranuts_utils_str2xml.md.tYMsh19G.js",
"/ran/assets/src_ranuts_file_read_dir.md.1214KxzM.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.Dn0MVnCR.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.C_QnAwkT.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B3f3ajgj.js",
"/ran/assets/src_article_sort_merge_index.md.DycVSt94.lean.js",
"/ran/assets/cn_index.md.Crs7jZ0r.js",
"/ran/assets/cn_src_note_ubuntu.md.CZECdRCR.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.Cpsfo9sk.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.ytYOxmqe.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.D-iYsstg.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranui_radar_index.md.C_IsC_5P.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranui_select_index.md.Devhny4S.js",
"/ran/assets/cn_src_types_高级类型.md.CmCg1DnQ.lean.js",
"/ran/assets/src_article_sort_select_index.md.B48Fab3-.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_sort_select_index.md.M32xrxKz.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_bundle.md.CYi7n-It.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_ranui_math_index.md.n_eRaJG3.js",
"/ran/assets/src_ranui_index.md.C13Toi_y.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_ranui_preview_index.md.Z1iILcIH.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.C13Kir38.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.BK7iKecd.js",
"/ran/assets/src_ranui_tabs_index.md.DUTrlUXB.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CyuCkqQW.js",
"/ran/assets/src_article_design_mode.md.BlSSZT1d.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_types_高级类型.md.DhhhSA1z.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BSljVHQX.lean.js",
"/ran/assets/cn_src_ranuts_index.md.Cx_oqped.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_visual.md.DCSAogEy.js",
"/ran/assets/src_ranuts_file_read_file.md.BXLuSeja.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.BDXQVfSV.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.rmzoISYn.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DMcsva5o.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.DcG0T2ie.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranui_image_index.md.OfwlkkZ-.js",
"/ran/assets/cn_src_article_typescript_union_type.md.QvUhabD4.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_sort_shell_index.md.D-iYsstg.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.CB4a9zEv.js",
"/ran/assets/src_article_sort_bucket_index.md.KCiCxFJv.lean.js",
"/ran/assets/src_ranui_player_index.md.D1PmHg2S.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CRdVVeNg.js",
"/ran/assets/cn_src_ranui_index.md.B69aq9Bi.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranui_icon_index.md.DojFsCCa.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.BbzyLddp.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Db6BHsjv.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.B1Qn-SYs.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_input_index.md.BUf9Jq6V.js",
"/ran/assets/src_ranuts_binary_tree_index.md.B_fUyNgW.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_image_index.md.8HOEvRt7.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_note_centos.md.siuCLR3u.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DCCy-ngY.js",
"/ran/assets/cn_src_article_sort_count_index.md.C9URUlFj.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Dhc4NZIo.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.uDmdmSNe.js",
"/ran/assets/src_article_sort_merge_index.md.DycVSt94.js",
"/ran/assets/cn_src_article_sort_heap_index.md.0xKj8yOX.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranuts_utils_format_json.md.D_39HwxT.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.RNxxpaVS.lean.js",
"/ran/assets/cn_src_note_centos.md.siuCLR3u.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.0xKj8yOX.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.QvUhabD4.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Cd0nSS5r.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.C9khJpKb.lean.js",
"/ran/assets/src_article_sort_heap_index.md.DXJ9dNSC.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.B8N0wt54.lean.js",
"/ran/assets/src_ranui_loading_index.md.Bpaz8F2s.lean.js",
"/ran/assets/src_ranuts_utils_task.md.D9saVHPV.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.reprGMBO.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.RlKC78KH.lean.js",
"/ran/assets/cn_src_types_类型运算.md.YOFI7DPU.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.C8WrpttU.js",
"/ran/assets/src_types_TS类型.md.ZQF-IpHt.lean.js",
"/ran/assets/cn_src_article_babel.md.D2qQHzlw.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranuts_utils_filter_obj.md.BqiAKnez.lean.js",
"/ran/assets/src_ranui_icon_index.md.DojFsCCa.js",
"/ran/assets/src_article_sort_bucket_index.md.KCiCxFJv.js",
"/ran/assets/cn_src_article_imagemin.md.HWLl8MTN.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_radar_index.md.CGXR6upD.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D184gZzJ.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.vEL71ZeR.js",
"/ran/assets/cn_src_types_TS类型.md.CVauAyIb.js",
"/ran/assets/cn_src_ranui_tabs_index.md.C9khJpKb.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_ranuts_file_write_file.md.BSjRQsWF.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cab6GmO6.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.C1_ge-xm.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_ranui_select_index.md.Dn0MVnCR.js",
"/ran/assets/src_article_sort_bubble_index.md.oah_6jyM.lean.js",
"/ran/assets/cn_src_article_bundle.md.DIctpnyi.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CGBuqE5X.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.DIapDvz0.js",
"/ran/assets/cn_src_article_typescript_pattern.md.8Pn_Aljs.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.B8N0wt54.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DBAoF5gb.js",
"/ran/assets/cn_src_article_sort_select_index.md.M32xrxKz.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_message_index.md.CCMP3aJo.lean.js",
"/ran/assets/cn_src_article_bundle.md.DIctpnyi.js",
"/ran/assets/src_article_imagemin.md.CXdU5tSz.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/index.CPEnXEJx.js",
"/ran/assets/chunks/@localSearchIndexroot.BQois17M.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.8OCKO1s-.js",
"/ran/assets/chunks/VPLocalSearchBox.BNXAvNCk.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/theme.vlSZUHl1.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/@localSearchIndexcn.DibTpiE1.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_file_append_file.md.DawLCi-o.js",
"/ran/assets/src_article_sort_heap_index.md.DXJ9dNSC.js",
"/ran/assets/cn_src_ranui_image_index.md.OfwlkkZ-.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DxFO7yDq.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.DRpAJUij.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Z_QVi1RU.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.74TKtcfU.js",
"/ran/assets/cn_src_note_docker.md.D2TRVpDl.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DDUYyoww.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.B06z5xH2.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.vEL71ZeR.lean.js",
"/ran/assets/src_ranui_progress_index.md.ACB9DRU8.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.BbzyLddp.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.2H0emn21.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Cd0nSS5r.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CRjMu7lt.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranui_skeleton_index.md.CGBuqE5X.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_article_system_design.md.BLuDVEQT.js",
"/ran/assets/cn_src_article_typescript_index.md.DcG0T2ie.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DcmHFK3V.js",
"/ran/assets/cn_src_article_sort_index.md.qtVcNBsr.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranui_modal_index.md.BFj0QVx7.js",
"/ran/assets/src_ranui_math_index.md.DR10Td9j.js",
"/ran/assets/src_article_typescript_index.md.DzfVENHK.lean.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranui_popover_index.md.BCQ34AWM.lean.js",
"/ran/assets/src_article_sort_index.md.DyfzEuVj.lean.js",
"/ran/assets/src_types_高级类型.md.DhhhSA1z.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_design_mode.md.D2XZUFSh.lean.js",
"/ran/assets/src_article_functional_programming.md.B19qqmri.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_video.md.CHRxGstt.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_bubble_index.md.oah_6jyM.js",
"/ran/assets/cn_src_ranui_icon_index.md.TRJuw-I4.js",
"/ran/assets/src_ranui_math_index.md.DR10Td9j.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.DcmHFK3V.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cab6GmO6.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranuts_utils_format_json.md.D_39HwxT.js",
"/ran/assets/cn_src_article_typescript_recursion.md.BnqZ7pEe.js",
"/ran/assets/src_article_sort_count_index.md.qzP0b82S.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.reprGMBO.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DbRvaX-r.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Z_QVi1RU.lean.js",
"/ran/assets/index.md.D6U0vTF8.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranuts_file_write_file.md.BSjRQsWF.lean.js",
"/ran/assets/src_article_sort_select_index.md.B48Fab3-.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranui_image_index.md.8HOEvRt7.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.D7YZi0xD.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_article_typescript_union_type.md.CFI42FnJ.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.RNxxpaVS.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_design_mode.md.BlSSZT1d.js",
"/ran/assets/src_article_typescript_pattern.md.DpfKV3YV.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.DGvYFR0p.lean.js",
"/ran/assets/src_types_类型运算.md.Co9c9kmo.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1742638969.js",
];
const VERSION = "1742638969";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



