const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/sw1713085829.js",
"/ran/icon_72.png",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_f8cf77f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b0cd6bd.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c45892d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_6a4c97c.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_d8f3a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_94b27bd.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7be51c9.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/index/zh-cn_89a5478.pf_index",
"/ran/pagefind/index/zh-cn_3c29486.pf_index",
"/ran/pagefind/index/en_f913c82.pf_index",
"/ran/pagefind/index/en_d6385dc.pf_index",
"/ran/pagefind/index/en_ff90c43.pf_index",
"/ran/pagefind/index/zh-cn_316d51d.pf_index",
"/ran/pagefind/index/zh-cn_f5766ac.pf_index",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.zh-cn_6e759b18c8d31.pf_meta",
"/ran/pagefind/pagefind.en_44eade61ce.pf_meta",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/cn/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/manifest.json",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/icon_96.png",
"/ran/404.html",
"/ran/assets/src_article_babel.md.UgSRTMtf.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DbyhlVVH.js",
"/ran/assets/src_article_bundle.md.3oo5m-lw.js",
"/ran/assets/cn_src_article_typescript_recursion.md.C06RvW9W.js",
"/ran/assets/src_ranui_image_index.md.COZnasue.js",
"/ran/assets/src_ranuts_file_watchFile.md.CBL0jJfO.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BAAUoHji.js",
"/ran/assets/src_ranui_index.md.-Qt8DPDp.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DJmsSNNW.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BJixCFmt.js",
"/ran/assets/src_article_imagemin.md.D_PT0Mmf.js",
"/ran/assets/src_ranui_player_index.md.Swih88Ly.js",
"/ran/assets/cn_src_article_typescript_calculate.md.O9QUcWyI.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_skeleton_index.md.vQXxBD06.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BYJfTfBy.js",
"/ran/assets/cn_src_ranui_preview_index.md.oWo6gZgi.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.o1v1iNfc.js",
"/ran/assets/src_ranui_skeleton_index.md.DXQRu-ST.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranuts_index.md.wnIoPcd3.js",
"/ran/assets/src_ranui_radar_index.md.BYJLhmNh.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.vIbv7wos.js",
"/ran/assets/src_types_类型运算.md.DwLRSUgj.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BWRL0p29.js",
"/ran/assets/cn_src_ranui_radar_index.md.CnOT2AI8.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BJixCFmt.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranui_icon_index.md.BU4ViQfI.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.qDSZ_8Xl.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_tab_index.md.CJ_TqSoN.lean.js",
"/ran/assets/src_article_designMode.md.DhNRKBe-.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_imagemin.md.DQPXPUip.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_message_index.md.Vo4LsiW2.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.qDSZ_8Xl.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_javascript_domLoad.md.BW-rJz7A.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.vQXxBD06.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BwtMHGZx.js",
"/ran/assets/src_article_imagemin.md.D_PT0Mmf.lean.js",
"/ran/assets/src_article_sort_insert_index.md.D0Tmqbsh.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_shell_index.md.BpOP2yre.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DT3WS8Mf.lean.js",
"/ran/assets/src_article_sort_merge_index.md.DoHwDM_T.js",
"/ran/assets/src_article_typescript_reconstruction.md.CME_1Lu7.js",
"/ran/assets/cn_src_article_typescript_index.md.HZ0eNXyx.lean.js",
"/ran/assets/cn_src_article_bundle.md.CAV2D43A.js",
"/ran/assets/cn_src_article_sort_merge_index.md.D-058bbi.js",
"/ran/assets/src_ranui_icon_index.md.BU4ViQfI.js",
"/ran/assets/src_ranui_button_index.md.V_0kYOiL.js",
"/ran/assets/src_ranui_progress_index.md.VSETKr9Z.lean.js",
"/ran/assets/cn_index.md.CdxdC9Zz.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Dt1yJS0n.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.D5uZ3ZvK.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BcfY_CKn.js",
"/ran/assets/cn_src_article_sort_select_index.md.Ht0PHiGD.js",
"/ran/assets/src_types_类型运算.md.DwLRSUgj.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BrCP_hDu.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_sort_count_index.md.KeBWElDg.lean.js",
"/ran/assets/src_ranui_preview_index.md.B-NJGDew.lean.js",
"/ran/assets/cn_src_article_babel.md.BeE2h9rm.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.CBL0jJfO.js",
"/ran/assets/src_article_sort_count_index.md.B_RuEzBp.lean.js",
"/ran/assets/cn_src_article_designMode.md.DMRtMtNN.lean.js",
"/ran/assets/cn_src_article_designMode.md.DMRtMtNN.js",
"/ran/assets/cn_src_article_typescript_index.md.HZ0eNXyx.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BGdsJ5e0.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_ranui_image_index.md.C8GgQ0Ij.js",
"/ran/assets/src_ranui_select_index.md.B5mhFnZv.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranui_popover_index.md.DSX1O9h0.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.O9QUcWyI.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.vMhQrdQX.js",
"/ran/assets/src_article_typescript_reconstruction.md.CME_1Lu7.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.vC-9Runq.js",
"/ran/assets/src_article_typescript_index.md.Di4JXikk.js",
"/ran/assets/src_article_bundle.md.3oo5m-lw.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_typescript_recursion.md.CHEF43MZ.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.B9_TsZp5.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.BPEA2CZI.js",
"/ran/assets/src_ranuts_utils_ocr.md.BfmswGtg.js",
"/ran/assets/src_ranui_tabs_index.md.9D5UR6lS.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DQzXrXVB.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.B8p77Tbn.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.hn2fEJQt.js",
"/ran/assets/src_article_typescript_unionType.md.DTTuE7ZD.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DDCsEevY.lean.js",
"/ran/assets/src_ranui_input_index.md.BttkCd_D.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_sort_heap_index.md.DRwa1Aod.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.zUmwWJKp.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_sort_heap_index.md.DRwa1Aod.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_article_sort_insert_index.md.CO0iGSuh.js",
"/ran/assets/src_article_designMode.md.DhNRKBe-.js",
"/ran/assets/src_ranuts_binaryTree_index.md.yw9ErnYL.js",
"/ran/assets/cn_src_article_sort_quick_index.md.ChTbO9gr.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.c6KTXHNZ.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BFxIIyWk.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BK-jHxK6.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.Cw7hroSY.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BLUEquQM.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_progress_index.md.VSETKr9Z.js",
"/ran/assets/cn_src_ranui_input_index.md.B3PoKWwI.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_sort_select_index.md.Dinr7wQK.js",
"/ran/assets/src_ranui_select_index.md.B5mhFnZv.js",
"/ran/assets/cn_src_ranui_progress_index.md.BiOqtrqm.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_index.md.C-nHDNAY.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranui_index.md.-Qt8DPDp.lean.js",
"/ran/assets/src_article_sort_select_index.md.Dinr7wQK.lean.js",
"/ran/assets/cn_src_article_babel.md.BeE2h9rm.js",
"/ran/assets/src_ranui_player_index.md.Swih88Ly.lean.js",
"/ran/assets/src_ranuts_index.md.wnIoPcd3.lean.js",
"/ran/assets/src_article_typescript_pattern.md.UMVnQvdx.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DZhblE5v.js",
"/ran/assets/cn_src_types_模式匹配.md.Cw7hroSY.js",
"/ran/assets/src_types_TS类型.md.BAi1nID6.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.DQzXrXVB.js",
"/ran/assets/src_article_typescript_calculate.md.CnSA14LQ.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_ranui_progress_index.md.BiOqtrqm.js",
"/ran/assets/cn_src_ranui_index.md.C9Dxky8O.js",
"/ran/assets/src_article_typescript_unionType.md.DTTuE7ZD.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.w73VvlpV.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.gUd2I4NN.lean.js",
"/ran/assets/src_ranui_preview_index.md.B-NJGDew.js",
"/ran/assets/src_article_sort_bubble_index.md.CqcQ01bz.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DT3WS8Mf.js",
"/ran/assets/cn_src_types_类型运算.md.963HiY_C.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Y8tHv27J.lean.js",
"/ran/assets/src_types_高级类型.md.D4hQegYF.js",
"/ran/assets/src_ranuts_file_appendFile.md.Dd7skmg0.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.vC-9Runq.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BcfY_CKn.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DSYrXWP8.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_index.md.CdxdC9Zz.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bp1OKDIE.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.CnOT2AI8.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BWRL0p29.lean.js",
"/ran/assets/cn_src_article_bundle.md.CAV2D43A.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BFxIIyWk.lean.js",
"/ran/assets/src_article_sort_insert_index.md.D0Tmqbsh.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CW0NQ-NT.js",
"/ran/assets/src_article_typescript_calculate.md.CnSA14LQ.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.L9_yXnN_.js",
"/ran/assets/cn_src_article_imagemin.md.DQPXPUip.lean.js",
"/ran/assets/app.CBt6PpVr.js",
"/ran/assets/src_ranui_radar_index.md.BYJLhmNh.js",
"/ran/assets/src_types_模式匹配.md.zOpE_TvX.js",
"/ran/assets/src_ranui_image_index.md.COZnasue.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.zUmwWJKp.js",
"/ran/assets/cn_src_article_sort_quick_index.md.ChTbO9gr.js",
"/ran/assets/cn_src_ranui_icon_index.md.Bp1OKDIE.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.D0I1h0I-.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.e8sEKYpJ.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.BrCP_hDu.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.L9_yXnN_.lean.js",
"/ran/assets/src_article_typescript_pattern.md.UMVnQvdx.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_sort_bucket_index.md.B8-0CjJW.js",
"/ran/assets/src_article_javascript_domLoad.md.p7344XtJ.lean.js",
"/ran/assets/index.md.D90YF4OC.lean.js",
"/ran/assets/src_ranuts_utils_task.md.Dt1yJS0n.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BltZu0HC.lean.js",
"/ran/assets/src_article_sort_quick_index.md.DmJueGGk.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CdNgb1n3.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.vMhQrdQX.lean.js",
"/ran/assets/cn_src_ranui_index.md.C9Dxky8O.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.B8p77Tbn.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.CYSj8IkP.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_article_sort_merge_index.md.DoHwDM_T.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_ranui_button_index.md.vIbv7wos.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranui_tab_index.md.CJ_TqSoN.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_image_index.md.C8GgQ0Ij.lean.js",
"/ran/assets/src_article_babel.md.UgSRTMtf.js",
"/ran/assets/src_ranui_modal_index.md.D4CuG_ae.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_bucket_index.md.B8-0CjJW.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.p7344XtJ.js",
"/ran/assets/src_types_高级类型.md.D4hQegYF.lean.js",
"/ran/assets/cn_src_types_类型运算.md.963HiY_C.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.o1v1iNfc.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_functionalProgramming.md.imCr0vk0.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Y8tHv27J.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CH1Y5iA4.lean.js",
"/ran/assets/src_article_sort_count_index.md.B_RuEzBp.js",
"/ran/assets/cn_src_ranui_tab_index.md.D-hsy-2f.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranui_tabs_index.md.IeCDksGK.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BLUEquQM.lean.js",
"/ran/assets/src_ranui_tabs_index.md.9D5UR6lS.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CW0NQ-NT.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DZhblE5v.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.gUd2I4NN.js",
"/ran/assets/cn_src_article_sort_heap_index.md.s6igeDQC.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranuts_file_appendFile.md.D0I1h0I-.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_javascript_domLoad.md.BW-rJz7A.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DLf6Rh3n.js",
"/ran/assets/cn_src_article_sort_shell_index.md.D5uZ3ZvK.js",
"/ran/assets/src_ranuts_bundler_index.md.bzmD_0G9.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.BwtMHGZx.lean.js",
"/ran/assets/src_ranui_button_index.md.V_0kYOiL.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.C06RvW9W.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.BYJfTfBy.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DDCsEevY.js",
"/ran/assets/src_ranuts_file_appendFile.md.Dd7skmg0.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranui_select_index.md.CpM4Rz1G.lean.js",
"/ran/assets/src_ranui_modal_index.md.D4CuG_ae.js",
"/ran/assets/src_ranui_message_index.md.CkmMnWjE.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BltZu0HC.js",
"/ran/assets/cn_src_ranui_input_index.md.B3PoKWwI.js",
"/ran/assets/src_article_typescript_recursion.md.CHEF43MZ.js",
"/ran/assets/src_article_sort_shell_index.md.BpOP2yre.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DXQRu-ST.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.hn2fEJQt.lean.js",
"/ran/assets/src_article_sort_index.md.C-nHDNAY.lean.js",
"/ran/assets/src_types_模式匹配.md.zOpE_TvX.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DbyhlVVH.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.oWo6gZgi.js",
"/ran/assets/cn_src_ranui_player_index.md.B9_TsZp5.js",
"/ran/assets/src_article_sort_quick_index.md.DmJueGGk.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/style.CFvsqX0l.css",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.c6KTXHNZ.js",
"/ran/assets/src_ranui_message_index.md.CkmMnWjE.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_typescript_index.md.Di4JXikk.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.CmdrbODL.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DJmsSNNW.js",
"/ran/assets/cn_src_ranui_message_index.md.Vo4LsiW2.js",
"/ran/assets/src_types_TS类型.md.BAi1nID6.js",
"/ran/assets/cn_src_article_sort_merge_index.md.D-058bbi.lean.js",
"/ran/assets/src_ranui_popover_index.md.DSX1O9h0.js",
"/ran/assets/index.md.D90YF4OC.js",
"/ran/assets/src_ranuts_utils_str2xml.md.RSp0sSjO.js",
"/ran/assets/src_ranuts_binaryTree_index.md.yw9ErnYL.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.BfmswGtg.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.iXwUGeli.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CMN-8-W9.js",
"/ran/assets/cn_src_types_TS类型.md.BCoF7Bap.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DLf6Rh3n.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BAAUoHji.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.w73VvlpV.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/index-BTiPI7ou.D7wPIxCW.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/framework.uTpxwq_I.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/pdf-B2a6ll8f.lVr-YjCg.js",
"/ran/assets/chunks/index-CZlEoE62.BH9TDfQd.js",
"/ran/assets/chunks/index.CV-dxUKH.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/theme.COw_KRb8.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/src_ranui_checkbox_index.md.CmdrbODL.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DI0-E3en.js",
"/ran/assets/cn_src_ranui_tab_index.md.D-hsy-2f.js",
"/ran/assets/cn_src_ranui_popover_index.md.BPEA2CZI.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CH1Y5iA4.js",
"/ran/assets/src_article_functionalProgramming.md.imCr0vk0.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_sort_radix_index.md.BRdxh5TW.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.CqcQ01bz.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.iXwUGeli.js",
"/ran/assets/src_ranuts_bundler_index.md.bzmD_0G9.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.BGdsJ5e0.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DI0-E3en.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.s6igeDQC.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.KeBWElDg.js",
"/ran/assets/src_ranuts_file_readFile.md.CYSj8IkP.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CMN-8-W9.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranui_tabs_index.md.IeCDksGK.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BK-jHxK6.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DSYrXWP8.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.RSp0sSjO.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.e8sEKYpJ.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_types_TS类型.md.BCoF7Bap.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.Ht0PHiGD.lean.js",
"/ran/assets/src_article_sort_radix_index.md.BRdxh5TW.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_ranui_input_index.md.BttkCd_D.js",
"/ran/assets/cn_src_ranui_select_index.md.CpM4Rz1G.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CO0iGSuh.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CdNgb1n3.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/screenshots_2560x1440.jpg",
"/ran/home.svg",
"/ran/icon.png",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/article/babel.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/icon_48.png",
];
const VERSION = "1713085829";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
    // google 上报不需要缓存
    'google',
    // 插件请求不用缓存
    'chrome-extension',
    // 百度的请求不用缓存
    'baidu.com',
    'blob:',
    'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
    GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
    SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
    INSTALL: 'install',
    FETCH: 'fetch',
    ACTIVATE: 'activate',
    MESSAGE: 'message',
    SYNC: 'sync',
    PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url } = request
    const { status } = fetchedResponse
    // 只缓存状态码为 200 的请求
    if (status !== RESPONSE_STATUS.SUCCESS) return
    if (filterRequest(request)) {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service worker update cache error:', error, request)
        })
    }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
    const { url, method } = request
    return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const { url } = request
        const responseFromCache = await caches.match(url);
        // 如果缓存中有，返回已经缓存的资源
        if (responseFromCache) return responseFromCache
        // 如果缓存中没有，就从网络中请求，并更新到缓存中
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        // 当缓存中也没有，请求也不可用的时候
        // 始终需要一个一个响应
        // 甚至可以设置回落的请求，在catch中继续发起请求
        console.log('service worker cacheFirst error:', error, request)
        return new Response("Network error happened", {
            status: 408,
            headers: { "Content-Type": "text/plain" },
        });
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('service worker deleteCache error:', error, key)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
    }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
            // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
            // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service worker fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service worker self installed error:', url, error);
                })
            )
        })
    );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
    // 拦截请求
    try {
        const { request } = event
        // 忽略 IGNORE_REQUEST_LIST 中的请求，不进行拦截
        if (filterRequest(request)) {
            const responseFromServer = cacheFirst(request)
            if (responseFromServer?.clone) {
                event.respondWith(responseFromServer);
            }
        }
    } catch (error) {
        console.log('service worker self fetch error:', error, event)
    }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
    event.waitUntil(deleteOldCaches());
});



