const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/manifest.json",
"/ran/icon_144.png",
"/ran/icon_48.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/404.html",
"/ran/cn/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/TS类型.html",
"/ran/assets/src_ranui_player_index.md.CmaXDLgM.js",
"/ran/assets/src_ranui_tab_index.md.DByJund3.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.d8dez1Kc.js",
"/ran/assets/cn_src_article_sort_count_index.md.ByReCgta.lean.js",
"/ran/assets/src_ranui_progress_index.md.CeDZ4O1E.js",
"/ran/assets/cn_src_ranui_preview_index.md.MRcpY4ge.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CMJEF2fC.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.D8v81B0j.lean.js",
"/ran/assets/src_ranui_loading_index.md.-6F8Ahv0.js",
"/ran/assets/src_article_designMode.md.cjolTJ_l.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CoE5E2pj.js",
"/ran/assets/cn_index.md.CSGUS3ij.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/theme.C-wF0psH.js",
"/ran/assets/chunks/index-CGEx9VOA.D_JSPS2d.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.UKkuQFux.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/framework.BHXmBVOg.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/index-Bl6-5Hp8.BoqmeQw7.js",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CIl6VDAV.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/index.R2KlXi5a.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/katex-es-B5r5vt3m.BDSjlQ-m.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/cn_src_ranuts_index.md.B6mC9oFa.lean.js",
"/ran/assets/cn_src_article_sort_index.md.3q6hmdj9.js",
"/ran/assets/src_article_sort_radix_index.md.uCAFtCNg.lean.js",
"/ran/assets/src_ranui_progress_index.md.CeDZ4O1E.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_ranui_checkbox_index.md.BIQGaYgV.js",
"/ran/assets/src_ranui_skeleton_index.md.C8c79H6U.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_article_sort_merge_index.md.Baxb5jaX.lean.js",
"/ran/assets/src_ranui_index.md.BbfptNvY.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_math_index.md.CFn8S76U.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CFn8S76U.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranuts_file_writeFile.md.D8v81B0j.js",
"/ran/assets/src_article_typescript_reconstruction.md.objlsxAH.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DaMlb8Ii.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DeVhWEgh.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranui_radar_index.md.R2APT-_e.js",
"/ran/assets/src_ranui_radar_index.md.R2APT-_e.lean.js",
"/ran/assets/src_article_sort_select_index.md.C4dv1s8F.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_article_javascript_domLoad.md.BsTgD1Zb.js",
"/ran/assets/src_article_bundle.md.B0B6UBJW.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BHFFafte.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DueXW_W7.js",
"/ran/assets/src_ranui_tabs_index.md.BGFjCn1j.lean.js",
"/ran/assets/src_article_sort_merge_index.md.D0pGt4GL.lean.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_article_sort_index.md.Gw6Zz5UV.js",
"/ran/assets/src_ranui_select_index.md.DpNcW8Qy.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DTw_mvzY.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranui_loading_index.md.-6F8Ahv0.lean.js",
"/ran/assets/src_ranui_index.md.BbfptNvY.lean.js",
"/ran/assets/src_types_TS类型.md.NvqeZNtO.js",
"/ran/assets/cn_src_ranui_loading_index.md.BDVgrmT5.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_types_模式匹配.md.CjFgLZeq.js",
"/ran/assets/src_ranui_skeleton_index.md.C8c79H6U.js",
"/ran/assets/src_article_astParse_tokenizer.md.c0cwSd4Q.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_icon_index.md.DiePmvqz.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CwnRYQIi.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Cl4nb6ER.js",
"/ran/assets/cn_src_ranui_popover_index.md.Cn1f1fjP.lean.js",
"/ran/assets/cn_src_ranui_index.md.AT9xqs5P.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Cn1f1fjP.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_select_index.md.DpNcW8Qy.js",
"/ran/assets/cn_src_types_TS类型.md.C2u2ZkfM.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.CBQl4DuG.js",
"/ran/assets/src_ranuts_utils_getCookie.md.D3s0jW0S.js",
"/ran/assets/style.dbX_n9PM.css",
"/ran/assets/cn_src_article_bundle.md.8vQLEEo9.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_article_typescript_recursion.md.B8hqt72S.js",
"/ran/assets/cn_src_article_sort_radix_index.md.xRLwN-Cu.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.b2bnVN-b.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_sort_quick_index.md.D1f3w8DC.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranui_image_index.md.CnOWnm-E.lean.js",
"/ran/assets/cn_src_ranuts_index.md.B6mC9oFa.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BvwwEC5O.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DaMlb8Ii.js",
"/ran/assets/src_article_functionalProgramming.md.DxXNPnnm.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranui_tab_index.md.DByJund3.js",
"/ran/assets/cn_src_article_bundle.md.8vQLEEo9.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.d8dez1Kc.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DywFpyqW.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BXllSoB0.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_binaryTree_index.md.jzWLkanl.lean.js",
"/ran/assets/src_article_sort_insert_index.md._IU8csEn.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CMdEUl51.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranui_select_index.md.C8irEeMm.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_button_index.md.C_ZeqkG6.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.xfRoVzNG.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.BXllSoB0.js",
"/ran/assets/cn_src_article_sort_insert_index.md.D53MGHaK.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_article_sort_bubble_index.md.CYKl2eE1.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DeVhWEgh.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_article_functionalProgramming.md.BYLIj0Hg.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BOuwXPzS.js",
"/ran/assets/cn_src_ranui_index.md.AT9xqs5P.js",
"/ran/assets/src_article_javascript_domLoad.md.BsTgD1Zb.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D5-wBfyr.js",
"/ran/assets/src_types_高级类型.md.B3wICZh9.js",
"/ran/assets/src_article_sort_count_index.md.6ZznYGyP.js",
"/ran/assets/src_article_typescript_pattern.md.CWQ14vIT.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.DywFpyqW.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DTw_mvzY.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BOuwXPzS.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BR0-1N-b.js",
"/ran/assets/cn_src_article_sort_count_index.md.ByReCgta.js",
"/ran/assets/src_ranuts_index.md.CyWqhiux.js",
"/ran/assets/cn_src_article_imagemin.md.l5mgMQqv.lean.js",
"/ran/assets/cn_index.md.CSGUS3ij.lean.js",
"/ran/assets/src_article_typescript_index.md.BtNJONb_.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D5-wBfyr.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.RE5lcrOu.lean.js",
"/ran/assets/cn_src_article_designMode.md.DIFNsgwa.lean.js",
"/ran/assets/src_article_sort_quick_index.md.BdD4tfYA.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9coCZMV.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.Cl4nb6ER.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.D926MTJp.js",
"/ran/assets/src_ranuts_file_readFile.md.BDlP2u7H.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DDOku6Ld.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_sort_merge_index.md.Baxb5jaX.js",
"/ran/assets/src_ranui_math_index.md.Dtm9QZKf.js",
"/ran/assets/cn_src_article_sort_shell_index.md.9ieQDSn6.js",
"/ran/assets/cn_src_ranui_select_index.md.C8irEeMm.js",
"/ran/assets/src_ranui_image_index.md.CnOWnm-E.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_typescript_reconstruction.md.objlsxAH.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.D0heFkhu.lean.js",
"/ran/assets/src_ranui_popover_index.md.C-sBJ8h2.js",
"/ran/assets/src_ranuts_index.md.CyWqhiux.lean.js",
"/ran/assets/src_ranui_modal_index.md.BPTDApNR.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CMJEF2fC.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Bcc1Hd6x.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_utils_str2xml.md.BvwwEC5O.lean.js",
"/ran/assets/index.md.KRuY7Dxb.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_sort_quick_index.md.BdD4tfYA.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9coCZMV.js",
"/ran/assets/cn_src_article_babel.md.DwWdgWMt.js",
"/ran/assets/src_ranuts_binaryTree_index.md.jzWLkanl.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_typescript_calculate.md.CKhcz8YO.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D9msSzXM.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.D1f3w8DC.js",
"/ran/assets/src_ranuts_file_readFile.md.BDlP2u7H.js",
"/ran/assets/src_article_astParse_tokenizer.md.c0cwSd4Q.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranui_modal_index.md.BPTDApNR.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B3zQ6153.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_article_typescript_unionType.md.DT305YLR.lean.js",
"/ran/assets/cn_src_article_visual.md.Ml-GmMm8.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_checkbox_index.md.BBqALIQC.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.BcyyWp__.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranui_message_index.md.XX7L_S96.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.D926MTJp.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CTakTgcd.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_article_sort_select_index.md.C4dv1s8F.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CtErkH5d.lean.js",
"/ran/assets/src_article_designMode.md.cjolTJ_l.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_types_类型运算.md.B935M7sh.js",
"/ran/assets/src_ranuts_utils_ocr.md.DIHWaPc-.js",
"/ran/assets/src_article_typescript_calculate.md.vANIILEl.lean.js",
"/ran/assets/index.md.KRuY7Dxb.js",
"/ran/assets/src_article_typescript_recursion.md.B8hqt72S.lean.js",
"/ran/assets/src_ranui_icon_index.md.DiePmvqz.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Bcc1Hd6x.js",
"/ran/assets/src_ranuts_file_watchFile.md.BWqWwXkb.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BIQGaYgV.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranui_checkbox_index.md.BBqALIQC.js",
"/ran/assets/src_article_sort_bucket_index.md.3RSiWt6x.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.B1kev4AP.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Db4HHRvm.js",
"/ran/assets/cn_src_ranuts_utils_task.md.B1kev4AP.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_types_类型运算.md.DbRYdWBm.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CwnRYQIi.js",
"/ran/assets/cn_src_ranui_loading_index.md.BDVgrmT5.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_article_sort_shell_index.md.q7cjzw46.js",
"/ran/assets/src_ranuts_file_fileInfo.md.B2sXZzC9.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_article_typescript_unionType.md.bJU3vxR5.js",
"/ran/assets/src_ranuts_file_readDir.md.Dgm4c9WM.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DfkXcWLj.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.B3owrKWc.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CtErkH5d.js",
"/ran/assets/cn_src_types_TS类型.md.C2u2ZkfM.lean.js",
"/ran/assets/src_article_sort_count_index.md.6ZznYGyP.lean.js",
"/ran/assets/src_article_sort_merge_index.md.D0pGt4GL.js",
"/ran/assets/src_ranuts_file_appendFile.md.Di6LSEuJ.js",
"/ran/assets/src_ranui_player_index.md.CmaXDLgM.lean.js",
"/ran/assets/src_article_imagemin.md.BhyZiuYB.js",
"/ran/assets/cn_src_article_typescript_recursion.md.G7Nt93Co.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CBQl4DuG.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DDOku6Ld.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BYLIj0Hg.js",
"/ran/assets/src_article_sort_shell_index.md.q7cjzw46.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.Di6LSEuJ.lean.js",
"/ran/assets/cn_src_article_imagemin.md.l5mgMQqv.js",
"/ran/assets/cn_src_article_designMode.md.DIFNsgwa.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_article_typescript_unionType.md.bJU3vxR5.lean.js",
"/ran/assets/src_ranui_input_index.md.D14tHRME.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B3zQ6153.js",
"/ran/assets/cn_src_article_typescript_unionType.md.DT305YLR.js",
"/ran/assets/src_types_TS类型.md.NvqeZNtO.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/src_ranuts_utils_filterObj.md.BR0-1N-b.lean.js",
"/ran/assets/src_types_模式匹配.md.CjFgLZeq.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BHFFafte.js",
"/ran/assets/src_article_sort_heap_index.md.BVFHSnDc.js",
"/ran/assets/cn_src_article_typescript_index.md.IPSi7PTn.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.BEMxTiEG.js",
"/ran/assets/cn_src_ranui_radar_index.md.7mkBOEOM.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.xfRoVzNG.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Dmo-Gh35.js",
"/ran/assets/cn_src_article_sort_index.md.3q6hmdj9.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.DIHWaPc-.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_imagemin.md.BhyZiuYB.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.C6087q5_.js",
"/ran/assets/cn_src_ranui_radar_index.md.7mkBOEOM.js",
"/ran/assets/src_article_sort_radix_index.md.uCAFtCNg.js",
"/ran/assets/src_ranui_tabs_index.md.BGFjCn1j.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.B3owrKWc.js",
"/ran/assets/src_ranui_input_index.md.D14tHRME.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_preview_index.md.U41Xs5x0.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_typescript_recursion.md.G7Nt93Co.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_sort_heap_index.md.BVFHSnDc.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.B2sXZzC9.js",
"/ran/assets/src_ranuts_bundler_index.md.HM6rEic_.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DxuUxyGX.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.xRLwN-Cu.lean.js",
"/ran/assets/src_ranui_popover_index.md.C-sBJ8h2.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_article_typescript_pattern.md.CWQ14vIT.js",
"/ran/assets/cn_src_ranui_preview_index.md.MRcpY4ge.js",
"/ran/assets/src_types_类型运算.md.B935M7sh.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CTakTgcd.js",
"/ran/assets/cn_src_article_sort_shell_index.md.9ieQDSn6.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CgH3AmKI.js",
"/ran/assets/cn_src_types_模式匹配.md.DSjgc6tH.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.ZdUTkANC.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_article_typescript_calculate.md.vANIILEl.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.D9msSzXM.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.D0heFkhu.js",
"/ran/assets/src_ranui_math_index.md.Dtm9QZKf.lean.js",
"/ran/assets/src_article_bundle.md.B0B6UBJW.js",
"/ran/assets/cn_src_types_模式匹配.md.DSjgc6tH.js",
"/ran/assets/cn_src_article_babel.md.DwWdgWMt.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.3RSiWt6x.js",
"/ran/assets/src_ranuts_file_readDir.md.Dgm4c9WM.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.RE5lcrOu.js",
"/ran/assets/cn_src_ranui_modal_index.md.BEMxTiEG.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.ZdUTkANC.lean.js",
"/ran/assets/src_article_babel.md.jjhEs_53.lean.js",
"/ran/assets/src_types_高级类型.md.B3wICZh9.lean.js",
"/ran/assets/src_article_functionalProgramming.md.DxXNPnnm.js",
"/ran/assets/cn_src_types_类型运算.md.DbRYdWBm.js",
"/ran/assets/src_ranuts_bundler_index.md.HM6rEic_.js",
"/ran/assets/cn_src_types_高级类型.md.DBcmZ44J.js",
"/ran/assets/src_article_sort_insert_index.md._IU8csEn.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranuts_utils_getCookie.md.D3s0jW0S.lean.js",
"/ran/assets/src_article_typescript_index.md.BtNJONb_.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CKhcz8YO.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.7Zzf8QNj.js",
"/ran/assets/src_ranuts_utils_formatJson.md.Db4HHRvm.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.DueXW_W7.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DvEQaypk.lean.js",
"/ran/assets/app.DfJswugP.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.b2bnVN-b.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CgH3AmKI.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.CoE5E2pj.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.C6087q5_.lean.js",
"/ran/assets/src_article_babel.md.jjhEs_53.js",
"/ran/assets/src_ranui_message_index.md.XX7L_S96.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DvEQaypk.js",
"/ran/assets/cn_src_article_sort_insert_index.md.D53MGHaK.lean.js",
"/ran/assets/src_ranui_button_index.md.C_ZeqkG6.js",
"/ran/assets/cn_src_ranui_tab_index.md.7Zzf8QNj.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.IPSi7PTn.js",
"/ran/assets/cn_src_article_visual.md.Ml-GmMm8.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_sort_bubble_index.md.CYKl2eE1.js",
"/ran/assets/src_ranuts_file_writeFile.md.CMdEUl51.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.DfkXcWLj.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.Dmo-Gh35.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranui_message_index.md.BcyyWp__.lean.js",
"/ran/assets/src_ranui_preview_index.md.U41Xs5x0.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.BWqWwXkb.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.DxuUxyGX.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_article_sort_index.md.Gw6Zz5UV.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DBcmZ44J.lean.js",
"/ran/screenshots_748x1340.jpg",
"/ran/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/babel.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/TS类型.html",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/home.svg",
"/ran/icon.png",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_63e4374.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e3e8d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a247d1d.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e385a7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9f70d46.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6ea04b2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_142eff8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_8adcb28.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e176acb.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/en_628da55.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d9728cf.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_77fd1d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_7738ff7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.en_7a1f95d03b.pf_meta",
"/ran/pagefind/index/zh-cn_3129ee0.pf_index",
"/ran/pagefind/index/zh-cn_92174b1.pf_index",
"/ran/pagefind/index/zh-cn_d6b2a8e.pf_index",
"/ran/pagefind/index/zh-cn_bb1cc93.pf_index",
"/ran/pagefind/index/en_031a886.pf_index",
"/ran/pagefind/index/en_85eb4b1.pf_index",
"/ran/pagefind/index/en_5d80bc4.pf_index",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind.zh-cn_4dab80e3b91e9.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/icon_72.png",
"/ran/sw1721098786.js",
"/ran/hashmap.json",
];
const VERSION = "1721098786";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



