const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/src_article_babel.md.BqFOZhpK.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BtpSP2yx.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_functional_programming.md.pruRFZgz.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.5Gj5sm4Z.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_design_mode.md.DyQ3JEvJ.js",
"/ran/assets/cn_src_article_system_design.md.D3wLRZfm.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_design_mode.md.DyQ3JEvJ.lean.js",
"/ran/assets/cn_src_ranui_index.md._yopX5KA.js",
"/ran/assets/src_ranui_select_index.md.DxS-EP8B.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.D-iOFujB.js",
"/ran/assets/src_ranui_preview_index.md.D3Swjfor.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.djk8Ex_G.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.D6bOQbs5.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranui_popover_index.md.D1HArK-6.lean.js",
"/ran/assets/app.C-AAf2lp.js",
"/ran/assets/cn_src_ranui_tab_index.md.5DeuF_w3.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranui_checkbox_index.md.5szr0Xj6.js",
"/ran/assets/src_ranuts_bundler_index.md.C9gFUtx-.lean.js",
"/ran/assets/src_ranui_button_index.md.BL89F2EK.js",
"/ran/assets/src_ranui_message_index.md.DpXGWGsb.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.5szr0Xj6.lean.js",
"/ran/assets/src_types_TS类型.md.CjxltWkO.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranuts_file_read_dir.md.BVBdu_5K.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.CgM5HcuB.lean.js",
"/ran/assets/cn_src_ranui_index.md._yopX5KA.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.D-VdPJEa.lean.js",
"/ran/assets/src_article_sort_insert_index.md.CCEUHYDx.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_article_sort_bucket_index.md.CvXCsdvS.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.Cqaqbsvb.js",
"/ran/assets/cn_src_ranui_player_index.md.C7sdddG3.lean.js",
"/ran/assets/src_article_sort_select_index.md.MHd_VYtV.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranui_radar_index.md.Dopa2-rC.js",
"/ran/assets/src_ranuts_utils_task.md.60XfeSuE.lean.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_typescript_pattern.md.DYMsbUDa.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.BtpSP2yx.js",
"/ran/assets/cn_src_ranuts_index.md.Dpe474YW.lean.js",
"/ran/assets/src_ranui_button_index.md.BL89F2EK.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DYMsbUDa.js",
"/ran/assets/src_ranuts_utils_task.md.60XfeSuE.js",
"/ran/assets/src_article_javascript_dom_load.md.DYGDesPv.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranuts_utils_task.md.0ni026Ly.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CXOmfhr7.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.CpLBXeEe.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DsDdkFGS.js",
"/ran/assets/src_types_高级类型.md.BwU4cSez.js",
"/ran/assets/cn_src_ranui_select_index.md.D-JL221_.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cyiosx-V.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.C_NUa5Gg.lean.js",
"/ran/assets/src_article_sort_select_index.md.MHd_VYtV.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CZdPQOFX.js",
"/ran/assets/cn_src_article_sort_select_index.md.BpFMGHr_.js",
"/ran/assets/src_ranui_image_index.md.CFTuKI5t.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DbfCOj6o.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Cw2NleLj.js",
"/ran/assets/src_ranui_math_index.md.CEbWQVJk.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_ranui_progress_index.md.BI8ZVgOw.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.B-RTSbNX.js",
"/ran/assets/cn_src_article_doc_preview.md.WfkbZ12a.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_sort_heap_index.md.gtNVkS07.js",
"/ran/assets/cn_src_ranui_preview_index.md.DmwHCzLT.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.D1nIjMz3.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.0CxFhkgI.lean.js",
"/ran/assets/cn_src_types_高级类型.md.Bp-mA6ii.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_types_类型运算.md.C_-asFnV.lean.js",
"/ran/assets/cn_src_article_bundle.md.LOzs7cAB.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.5Gj5sm4Z.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.CaPA0Z-8.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.HRz6K853.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_sort_heap_index.md.gtNVkS07.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_system_design.md.D3wLRZfm.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.D1HArK-6.js",
"/ran/assets/src_article_sort_radix_index.md.DwymvXu3.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.7UEkbpQU.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_types_类型运算.md.DkWaLOg4.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CuzhB1BN.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.D-bu_m-o.js",
"/ran/assets/src_ranuts_file_read_file.md.CGPeYBdL.js",
"/ran/assets/cn_src_article_video.md.DS63ZSyv.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.C_NUa5Gg.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_article_sort_count_index.md.DaeC9a9h.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DFpeZLdj.js",
"/ran/assets/src_ranui_skeleton_index.md.D4p_-08X.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.Cb0nAMRM.js",
"/ran/assets/cn_src_ranui_select_index.md.D-JL221_.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CPV9ShWR.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DoP3x1pr.js",
"/ran/assets/src_article_sort_shell_index.md.gFC2yDPq.js",
"/ran/assets/src_ranuts_file_write_file.md.DrD1dQQA.js",
"/ran/assets/cn_src_ranui_input_index.md.B0u_8A6t.lean.js",
"/ran/assets/src_article_sort_merge_index.md.l_avmK25.lean.js",
"/ran/assets/src_ranui_loading_index.md.CVzSzudi.js",
"/ran/assets/src_article_sort_quick_index.md.Be8HjHWc.js",
"/ran/assets/src_article_bundle.md.PmCnemfM.lean.js",
"/ran/assets/src_ranui_progress_index.md.DUH9oxnD.js",
"/ran/assets/src_ranui_player_index.md.D6_xplp5.js",
"/ran/assets/cn_src_types_TS类型.md.VgdPV3ch.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BTDjL8TY.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BgrordLZ.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_insert_index.md.DnzUCZu3.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_sort_bucket_index.md.CvXCsdvS.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranui_button_index.md.CKki9R4w.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Dqv4X95m.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BI8ZVgOw.js",
"/ran/assets/src_article_typescript_index.md.wd0o5ypm.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Dl8L0WCQ.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.D-iOFujB.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DKzCVMRG.js",
"/ran/assets/cn_src_ranui_player_index.md.C7sdddG3.js",
"/ran/assets/cn_src_article_sort_radix_index.md.C71q4D8z.js",
"/ran/assets/cn_src_article_sort_select_index.md.BpFMGHr_.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_types_模式匹配.md.Dzw-32Fp.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DrCEmUIN.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.Cb0nAMRM.lean.js",
"/ran/assets/src_ranui_tabs_index.md.DFKoYyEt.lean.js",
"/ran/assets/src_article_sort_shell_index.md.gFC2yDPq.lean.js",
"/ran/assets/src_ranui_player_index.md.D6_xplp5.lean.js",
"/ran/assets/src_types_模式匹配.md.Dzw-32Fp.lean.js",
"/ran/assets/cn_src_article_babel.md.DKUouRfQ.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_article_imagemin.md.DV8ZhaCX.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.D6bOQbs5.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranuts_binary_tree_index.md.B-RTSbNX.lean.js",
"/ran/assets/src_article_imagemin.md.TnD-lTN6.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.eDu6zwn0.lean.js",
"/ran/assets/src_types_类型运算.md.C_-asFnV.js",
"/ran/assets/cn_src_article_sort_heap_index.md.CuzhB1BN.js",
"/ran/assets/src_article_functional_programming.md.DDmCGeBt.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.DoP3x1pr.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.CDWH2YDu.js",
"/ran/assets/cn_src_types_高级类型.md.Bp-mA6ii.js",
"/ran/assets/cn_src_types_模式匹配.md.BqHsO98Q.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D8L3QJ-_.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Cw2NleLj.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_sort_bubble_index.md.D1nIjMz3.lean.js",
"/ran/assets/src_article_sort_insert_index.md.CCEUHYDx.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DrCEmUIN.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.djk8Ex_G.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_utils_task.md.0ni026Ly.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BgrordLZ.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DkWaLOg4.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.Cyiosx-V.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.Cqaqbsvb.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.upOENX2J.lean.js",
"/ran/assets/src_ranui_input_index.md._VlRvmKI.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_typescript_union_type.md.Bp07Vorq.js",
"/ran/assets/src_ranui_tab_index.md.D2CbQkLN.js",
"/ran/assets/src_ranui_progress_index.md.DUH9oxnD.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DsDdkFGS.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CPV9ShWR.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_article_functional_programming.md.pruRFZgz.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.CaPA0Z-8.js",
"/ran/assets/src_ranui_icon_index.md.DJReZMAb.lean.js",
"/ran/assets/cn_src_article_visual.md.BtCqipYO.js",
"/ran/assets/cn_src_note_centos.md.C9ejkw9J.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_sort_merge_index.md.l_avmK25.js",
"/ran/assets/cn_src_article_video.md.DS63ZSyv.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_ranui_modal_index.md.Bii4MI8l.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.B0u_8A6t.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BTDjL8TY.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.BavqQXFQ.js",
"/ran/assets/src_ranuts_file_append_file.md.CpLBXeEe.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cin69Ma8.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CDWH2YDu.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.DrD1dQQA.lean.js",
"/ran/assets/src_article_sort_index.md.CTcgvrda.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DHFSl3oo.js",
"/ran/assets/src_article_typescript_union_type.md.CS1AyAm8.js",
"/ran/assets/cn_src_article_typescript_index.md.DxfEtKwO.js",
"/ran/assets/cn_src_types_模式匹配.md.BqHsO98Q.lean.js",
"/ran/assets/src_article_sort_quick_index.md.Be8HjHWc.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.DDjfDEUw.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.DFpeZLdj.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranuts_utils_get_cookie.md.CgM5HcuB.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_imagemin.md.TnD-lTN6.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.Bp07Vorq.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BPgnywu2.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.DmwHCzLT.js",
"/ran/assets/src_ranui_preview_index.md.D3Swjfor.js",
"/ran/assets/src_article_babel.md.BqFOZhpK.js",
"/ran/assets/cn_src_ranuts_index.md.Dpe474YW.js",
"/ran/assets/src_ranuts_index.md.BhD3SziA.js",
"/ran/assets/src_ranui_tab_index.md.D2CbQkLN.lean.js",
"/ran/assets/style.B_vNQ4Pc.css",
"/ran/assets/cn_src_article_typescript_pattern.md.CXOmfhr7.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B6A0pJJj.lean.js",
"/ran/assets/cn_src_note_docker.md.DNjZNtPh.lean.js",
"/ran/assets/src_ranui_tabs_index.md.DFKoYyEt.js",
"/ran/assets/src_ranui_index.md.BdF0r5lK.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DHFSl3oo.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranui_skeleton_index.md.D4p_-08X.js",
"/ran/assets/cn_src_ranui_button_index.md.CKki9R4w.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_imagemin.md.DV8ZhaCX.js",
"/ran/assets/src_article_sort_count_index.md.oxaXeO38.js",
"/ran/assets/src_ranuts_file_watch_file.md.BavqQXFQ.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BIa0rw-S.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.upOENX2J.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranuts_file_read_dir.md.eDu6zwn0.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DKzCVMRG.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.Dl8L0WCQ.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranui_modal_index.md.Bii4MI8l.js",
"/ran/assets/src_article_typescript_reconstruction.md.Bye9wGuJ.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BhNbcdyo.js",
"/ran/assets/src_ranuts_file_read_file.md.CGPeYBdL.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.CAzb7aBJ.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.7UEkbpQU.lean.js",
"/ran/assets/cn_src_article_design_mode.md.C_KUQ2Eb.lean.js",
"/ran/assets/cn_src_note_centos.md.C9ejkw9J.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.BPgnywu2.js",
"/ran/assets/src_ranui_message_index.md.DpXGWGsb.js",
"/ran/assets/cn_index.md.CqGj0HiU.js",
"/ran/assets/index.md.lJfdeLFW.js",
"/ran/assets/src_ranuts_utils_ocr.md.DDjfDEUw.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.BIa0rw-S.js",
"/ran/assets/src_article_sort_radix_index.md.DwymvXu3.js",
"/ran/assets/cn_src_ranui_message_index.md.Bxrby0gX.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.DYGDesPv.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B6A0pJJj.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_article_functional_programming.md.DDmCGeBt.js",
"/ran/assets/cn_src_article_sort_index.md.D_gu59z7.js",
"/ran/assets/src_article_typescript_calculate.md.U1vBDa9D.js",
"/ran/assets/cn_src_article_visual.md.BtCqipYO.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cin69Ma8.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/index.md.lJfdeLFW.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CNMuvZvI.js",
"/ran/assets/cn_src_note_ubuntu.md.D4RfOtH5.lean.js",
"/ran/assets/cn_src_article_bundle.md.LOzs7cAB.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_note_docker.md.DNjZNtPh.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_article_sort_bubble_index.md.HRz6K853.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.jyLDK8Gv.lean.js",
"/ran/assets/cn_index.md.CqGj0HiU.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/VPLocalSearchBox.BeNqYHgB.js",
"/ran/assets/chunks/index-BPr9h4Hv.CXta4E5w.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/@localSearchIndexroot.B0BjwHUs.js",
"/ran/assets/chunks/jszip.min--o3_SgQz.CiS0z4ab.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index-CVkJ_Xlh.BFb2SL1a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CSKV0Byf.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/docx-D5t6JtVt.BnsCdyQq.js",
"/ran/assets/chunks/index.SzMjWDrZ.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/theme.DwuHKqYp.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CU_zipUL.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/commonjs-dynamic-modules-HhqG7SJg.B9lKsKkd.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/@localSearchIndexcn.B8EAiXlr.js",
"/ran/assets/src_ranuts_bundler_index.md.C9gFUtx-.js",
"/ran/assets/cn_src_ranui_radar_index.md.Dopa2-rC.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_ranui_math_index.md.ChFnX_M2.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DnzUCZu3.lean.js",
"/ran/assets/src_article_bundle.md.PmCnemfM.js",
"/ran/assets/cn_src_ranui_message_index.md.Bxrby0gX.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CNMuvZvI.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.jyLDK8Gv.js",
"/ran/assets/src_ranui_radar_index.md.CKktN0OZ.js",
"/ran/assets/src_ranui_popover_index.md.CxuMg93R.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.CZdPQOFX.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.DxfEtKwO.lean.js",
"/ran/assets/src_ranui_radar_index.md.CKktN0OZ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D8L3QJ-_.lean.js",
"/ran/assets/src_ranui_popover_index.md.CxuMg93R.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/src_ranui_loading_index.md.CVzSzudi.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranui_image_index.md.CFTuKI5t.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_index.md.BhD3SziA.lean.js",
"/ran/assets/src_types_TS类型.md.CjxltWkO.lean.js",
"/ran/assets/src_ranui_icon_index.md.DJReZMAb.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_sort_index.md.D_gu59z7.lean.js",
"/ran/assets/src_ranui_index.md.BdF0r5lK.lean.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.Dqv4X95m.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.0CxFhkgI.js",
"/ran/assets/cn_src_article_doc_preview.md.WfkbZ12a.js",
"/ran/assets/src_ranui_math_index.md.CEbWQVJk.js",
"/ran/assets/src_article_typescript_calculate.md.U1vBDa9D.lean.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.ldkymFbG.js",
"/ran/assets/cn_src_ranui_icon_index.md.B3X316ey.js",
"/ran/assets/cn_src_article_sort_radix_index.md.C71q4D8z.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.D-bu_m-o.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_typescript_index.md.wd0o5ypm.js",
"/ran/assets/src_ranui_input_index.md._VlRvmKI.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_sort_count_index.md.oxaXeO38.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DbfCOj6o.js",
"/ran/assets/cn_src_types_TS类型.md.VgdPV3ch.lean.js",
"/ran/assets/cn_src_article_design_mode.md.C_KUQ2Eb.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranui_select_index.md.DxS-EP8B.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranui_math_index.md.ChFnX_M2.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_typescript_calculate.md.CAzb7aBJ.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_article_typescript_union_type.md.CS1AyAm8.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DaeC9a9h.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranuts_file_write_file.md.ldkymFbG.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BhNbcdyo.lean.js",
"/ran/assets/src_article_sort_index.md.CTcgvrda.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_note_ubuntu.md.D4RfOtH5.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.Br7Xt-oV.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranuts_bundler_index.md.Br7Xt-oV.lean.js",
"/ran/assets/src_types_高级类型.md.BwU4cSez.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_typescript_reconstruction.md.Bye9wGuJ.js",
"/ran/assets/cn_src_ranui_tab_index.md.5DeuF_w3.js",
"/ran/assets/cn_src_ranui_loading_index.md.D-VdPJEa.js",
"/ran/assets/cn_src_ranui_icon_index.md.B3X316ey.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.BVBdu_5K.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/cn_src_article_babel.md.DKUouRfQ.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/sw1741878553.js",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1741878553";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



