const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/src_ranui_popover_index.md.CDEMiJgB.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CX1nggkk.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.s8QUjn6p.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.CCydGAEq.js",
"/ran/assets/src_ranuts_file_watch_file.md.D5EoocGO.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_count_index.md.BSdjtI6t.js",
"/ran/assets/src_ranui_radar_index.md.BpsDCpym.js",
"/ran/assets/cn_src_types_类型运算.md.DAqBTpWR.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CNWG3EEZ.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_article_sort_bubble_index.md.iR7Avg9n.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_types_类型运算.md.BvITLQQo.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_article_sort_count_index.md.BUs928e1.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_ranui_loading_index.md.Bf7XSugM.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_input_index.md.DcySICEl.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DxPB7rtO.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranui_math_index.md.D41wwRfk.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BUs928e1.js",
"/ran/assets/src_ranui_message_index.md.Jt7FF9fi.js",
"/ran/assets/cn_index.md.3WNtJJnx.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_file_write_file.md.CJ3jQfZJ.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_article_sort_bubble_index.md.BsuYGmJ2.js",
"/ran/assets/cn_src_ranui_tab_index.md.Cc_NNSXv.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/src_ranui_button_index.md.DUn1dp3k.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.PNv0ttbm.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BoGmSkVk.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranui_preview_index.md.CyvEolRB.js",
"/ran/assets/src_ranui_radar_index.md.BpsDCpym.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_sort_index.md.C8rpQg9i.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.C8r4C80J.lean.js",
"/ran/assets/cn_src_ranui_math_index.md.CQ_7iyxT.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CNWG3EEZ.js",
"/ran/assets/src_types_类型运算.md.BvITLQQo.js",
"/ran/assets/cn_src_types_类型运算.md.DAqBTpWR.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_write_file.md.CDnYIzzg.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.XtsG5wrJ.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DT7kC7JG.js",
"/ran/assets/src_ranuts_index.md.BLJbeBeh.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B8NHSdtN.js",
"/ran/assets/src_ranuts_binary_tree_index.md.BRIiHm7_.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BQ9Hjme6.js",
"/ran/assets/src_ranui_loading_index.md.DILiw7gi.lean.js",
"/ran/assets/cn_src_article_design_mode.md.B1hoSLWD.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.B8-yurtQ.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BNoLMl3c.js",
"/ran/assets/src_article_sort_insert_index.md.ANbrV4M6.js",
"/ran/assets/src_ranui_player_index.md.Xmko93aG.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/cn_src_article_system_design.md.BZTHpxIV.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BQYz_Pqk.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BoGmSkVk.js",
"/ran/assets/cn_src_types_高级类型.md.D76K0N8l.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DFrGPapN.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.BkuNLCPl.js",
"/ran/assets/src_ranuts_file_write_file.md.CDnYIzzg.js",
"/ran/assets/cn_src_note_docker.md.Oh2FKu63.js",
"/ran/assets/src_article_sort_count_index.md.BSdjtI6t.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DkQ5DWWM.js",
"/ran/assets/src_article_sort_index.md.C8rpQg9i.js",
"/ran/assets/src_ranuts_file_read_file.md.DMwDf7MD.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DkQ5DWWM.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Ppc8kJdX.lean.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.CX1nggkk.js",
"/ran/assets/src_article_bundle.md.D1-HiZwl.lean.js",
"/ran/assets/cn_src_article_bundle.md.ChH_5AJW.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.B8-yurtQ.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Btsq2ipP.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.DGANhFlA.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranui_radar_index.md.CFRQ75dY.lean.js",
"/ran/assets/src_ranuts_utils_task.md.B7DEqE24.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.DFrGPapN.js",
"/ran/assets/cn_src_article_design_mode.md.B1hoSLWD.js",
"/ran/assets/src_article_typescript_union_type.md.Pg6yA14j.lean.js",
"/ran/assets/src_ranui_input_index.md.DpAjNz0m.js",
"/ran/assets/src_ranui_progress_index.md.pNRNggFB.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DUY8Nii7.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DxPB7rtO.lean.js",
"/ran/assets/src_article_functional_programming.md.DdDsJILg.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_skeleton_index.md.ZQrm-i9p.lean.js",
"/ran/assets/cn_src_note_centos.md.DNt8M2nM.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranui_image_index.md.C8dMQtQ3.js",
"/ran/assets/src_article_sort_quick_index.md.LCz-6DX4.js",
"/ran/assets/cn_src_article_typescript_index.md.B-rAEkWf.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.CBv2VmFR.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.DXxxH7gm.lean.js",
"/ran/assets/cn_src_ranui_index.md.Bj4a_3Lt.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_ranuts_utils_format_json.md.DUXoeNih.lean.js",
"/ran/assets/src_ranuts_utils_task.md.B7DEqE24.lean.js",
"/ran/assets/src_types_高级类型.md.D3PpsK5R.js",
"/ran/assets/src_article_typescript_pattern.md.DVy601-A.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.ozh4GEZZ.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_types_TS类型.md.DT_lQ_3s.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.CTmNxG87.js",
"/ran/assets/src_ranuts_file_read_dir.md.XtsG5wrJ.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_typescript_reconstruction.md.hVfD4oQn.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CGc6UEy0.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CGc6UEy0.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D41bch6B.lean.js",
"/ran/assets/src_article_typescript_index.md.CtLRoJCK.js",
"/ran/assets/cn_src_ranui_tab_index.md.Cc_NNSXv.js",
"/ran/assets/src_article_babel.md.TIDYdCYE.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CK8wSoBv.js",
"/ran/assets/cn_src_article_imagemin.md.B-7iXdBX.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.D0jTO7Dt.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_ranuts_utils_task.md.D4P8k-EC.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranuts_utils_get_cookie.md.CBv2VmFR.js",
"/ran/assets/src_ranui_input_index.md.DpAjNz0m.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_sort_radix_index.md.DbEuR-Tg.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranuts_file_append_file.md.CCydGAEq.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranui_checkbox_index.md.Cx0huGcO.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_article_system_design.md.BZTHpxIV.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.DcySICEl.js",
"/ran/assets/src_types_模式匹配.md.DkV6UuGD.lean.js",
"/ran/assets/src_ranui_modal_index.md.Dt6yqlua.js",
"/ran/assets/src_article_sort_bucket_index.md.DT5VcyVb.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CvrURoFh.js",
"/ran/assets/cn_src_types_模式匹配.md.LmeJpWtU.lean.js",
"/ran/assets/src_article_sort_select_index.md.BiKWN93H.js",
"/ran/assets/src_ranuts_file_file_info.md.0QMjXKzx.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranui_message_index.md.Cg-AiGZP.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.c0vYccmq.lean.js",
"/ran/assets/index.md.DyB-K2DE.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.CWm5HOPi.js",
"/ran/assets/src_ranui_select_index.md.C35U_pf6.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.LmeJpWtU.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.BkuNLCPl.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.Btsq2ipP.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_player_index.md.CwjOQ3xv.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.C8r4C80J.js",
"/ran/assets/cn_src_ranui_index.md.Bj4a_3Lt.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.mOekk_nW.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BW_R0Wci.js",
"/ran/assets/cn_src_article_sort_radix_index.md.D3GR-GJ0.js",
"/ran/assets/cn_src_ranui_modal_index.md.CUmrFREV.js",
"/ran/assets/cn_src_note_ubuntu.md.CA21VQyd.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.D41bch6B.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_sort_radix_index.md.D3GR-GJ0.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BN-4tW6N.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_article_babel.md.D1tFKrRT.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BA-q3s0s.lean.js",
"/ran/assets/cn_src_article_sort_index.md.vIctvChO.lean.js",
"/ran/assets/src_ranui_image_index.md.BNcGjszE.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D4P8k-EC.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.yR-7Eyq1.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_article_sort_bubble_index.md.BsuYGmJ2.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DFXfBr3z.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_article_sort_heap_index.md.BlKknAJi.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.BW_R0Wci.lean.js",
"/ran/assets/src_article_design_mode.md.GMlky6s2.js",
"/ran/assets/cn_src_ranui_player_index.md.CwjOQ3xv.js",
"/ran/assets/src_article_sort_insert_index.md.ANbrV4M6.lean.js",
"/ran/assets/src_article_imagemin.md.BSFsPicX.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranui_icon_index.md.BnOhnls2.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranuts_index.md.BLyttybl.lean.js",
"/ran/assets/src_ranui_tabs_index.md.TEpYda2T.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMYwnp_e.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Cg4--GRn.js",
"/ran/assets/src_article_bundle.md.D1-HiZwl.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_ranui_math_index.md.D41wwRfk.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BQYz_Pqk.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranui_select_index.md.C35U_pf6.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranuts_file_append_file.md.Bweohi3-.lean.js",
"/ran/assets/cn_src_article_video.md.8tD62BC-.js",
"/ran/assets/src_ranui_tabs_index.md.TEpYda2T.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranuts_file_file_info.md.CMYwnp_e.js",
"/ran/assets/src_ranui_tab_index.md.BHnvauP2.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/cn_src_article_babel.md.D1tFKrRT.js",
"/ran/assets/src_types_高级类型.md.D3PpsK5R.lean.js",
"/ran/assets/cn_src_types_TS类型.md.DT_lQ_3s.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Cnj8Y6C5.js",
"/ran/assets/cn_src_article_functional_programming.md.s8QUjn6p.js",
"/ran/assets/src_ranuts_utils_str2xml.md.C9l43Zyn.js",
"/ran/assets/cn_src_article_visual.md.1ZT9gQW7.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_shell_index.md.DOFLOwZN.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/app.EWEzrFn9.js",
"/ran/assets/src_article_sort_radix_index.md.DbEuR-Tg.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CvrURoFh.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_ranuts_file_read_file.md.DMwDf7MD.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_doc_preview.md.CWm5HOPi.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Suj7Htu7.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_typescript_calculate.md.Ad0CdSE1.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Cg-AiGZP.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_ranuts_mode_subscribe.md.CTmNxG87.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.ZQrm-i9p.js",
"/ran/assets/src_article_babel.md.TIDYdCYE.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Cg4--GRn.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_article_imagemin.md.B-7iXdBX.js",
"/ran/assets/src_ranuts_utils_ocr.md.9gyv_JQP.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.Cx0huGcO.lean.js",
"/ran/assets/src_types_TS类型.md.UB9IDdfj.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_sort_bubble_index.md.iR7Avg9n.lean.js",
"/ran/assets/cn_index.md.3WNtJJnx.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_image_index.md.C8dMQtQ3.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BNoLMl3c.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.D0jTO7Dt.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BN-4tW6N.js",
"/ran/assets/cn_src_article_sort_shell_index.md.Cnj8Y6C5.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Suj7Htu7.lean.js",
"/ran/assets/cn_src_note_centos.md.DNt8M2nM.lean.js",
"/ran/assets/cn_src_note_docker.md.Oh2FKu63.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.mOekk_nW.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranuts_file_write_file.md.CJ3jQfZJ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DCbrhGaP.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.B9YYD6yB.js",
"/ran/assets/cn_src_ranuts_index.md.BLyttybl.js",
"/ran/assets/src_ranui_tab_index.md.BHnvauP2.lean.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/src_types_TS类型.md.UB9IDdfj.js",
"/ran/assets/cn_src_article_sort_insert_index.md.CK8wSoBv.lean.js",
"/ran/assets/src_ranui_button_index.md.DUn1dp3k.lean.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.Bweohi3-.js",
"/ran/assets/src_ranui_index.md.BX8RXJib.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranui_button_index.md.B9YYD6yB.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DVy601-A.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_ranui_math_index.md.CQ_7iyxT.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_ranui_loading_index.md.DILiw7gi.js",
"/ran/assets/src_article_typescript_calculate.md.Ad0CdSE1.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DoCBSgMy.js",
"/ran/assets/cn_src_ranui_radar_index.md.CFRQ75dY.js",
"/ran/assets/index.md.DyB-K2DE.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BQ9Hjme6.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BYY5NTCk.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_ast_parse_tokenizer.md.B2BBalbU.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.UmsLlfP-.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/@localSearchIndexcn.DNvXfDGk.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/theme.D7nNfggH.js",
"/ran/assets/chunks/index.B8mYliZ2.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/@localSearchIndexroot.VE5G8ivT.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/VPLocalSearchBox.DPalbrIu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranuts_utils_ocr.md.PFG0JUv0.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Ppc8kJdX.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranui_player_index.md.Xmko93aG.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.DUXoeNih.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.PFG0JUv0.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.CUmrFREV.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.DT7kC7JG.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BlKknAJi.lean.js",
"/ran/assets/src_article_design_mode.md.GMlky6s2.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.hVfD4oQn.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Bf7XSugM.js",
"/ran/assets/cn_src_article_sort_select_index.md.DGANhFlA.js",
"/ran/assets/src_article_sort_merge_index.md.BNZoMT2d.js",
"/ran/assets/cn_src_article_sort_index.md.vIctvChO.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DtNLEkU2.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.DUY8Nii7.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_article_sort_shell_index.md.DOFLOwZN.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BYY5NTCk.js",
"/ran/assets/src_ranui_icon_index.md.CK9aJYcA.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.c0vYccmq.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranui_index.md.BX8RXJib.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.ozh4GEZZ.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.BRIiHm7_.lean.js",
"/ran/assets/style.zTfaa9RN.css",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_article_typescript_union_type.md.Pg6yA14j.js",
"/ran/assets/src_ranuts_index.md.BLJbeBeh.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.9gyv_JQP.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.X3K-tjPk.js",
"/ran/assets/src_ranui_image_index.md.BNcGjszE.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.B2BBalbU.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_ranui_modal_index.md.Dt6yqlua.lean.js",
"/ran/assets/src_ranui_message_index.md.Jt7FF9fi.lean.js",
"/ran/assets/src_article_sort_merge_index.md.BNZoMT2d.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DFXfBr3z.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_types_模式匹配.md.DkV6UuGD.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_article_sort_quick_index.md.LCz-6DX4.lean.js",
"/ran/assets/cn_src_article_video.md.8tD62BC-.lean.js",
"/ran/assets/src_article_sort_select_index.md.BiKWN93H.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_typescript_index.md.B-rAEkWf.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.DtNLEkU2.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.yR-7Eyq1.js",
"/ran/assets/src_ranui_preview_index.md.CyvEolRB.lean.js",
"/ran/assets/cn_src_article_bundle.md.ChH_5AJW.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_ranui_popover_index.md.X3K-tjPk.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.0QMjXKzx.js",
"/ran/assets/src_article_sort_bucket_index.md.DT5VcyVb.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.B8NHSdtN.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.DXxxH7gm.js",
"/ran/assets/src_ranui_progress_index.md.pNRNggFB.js",
"/ran/assets/cn_src_note_ubuntu.md.CA21VQyd.js",
"/ran/assets/src_article_imagemin.md.BSFsPicX.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.DCbrhGaP.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BA-q3s0s.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranui_icon_index.md.CK9aJYcA.js",
"/ran/assets/src_article_typescript_index.md.CtLRoJCK.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.BnOhnls2.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.PNv0ttbm.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranuts_file_watch_file.md.D5EoocGO.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DoCBSgMy.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_types_高级类型.md.D76K0N8l.js",
"/ran/assets/src_ranuts_utils_str2xml.md.C9l43Zyn.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_functional_programming.md.DdDsJILg.lean.js",
"/ran/assets/cn_src_article_visual.md.1ZT9gQW7.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranui_popover_index.md.CDEMiJgB.lean.js",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/sw1742108612.js",
];
const VERSION = "1742108612";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



