const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/404.html",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/index.html",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_192.png",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/babel.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/bundle.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/fragment/zh-cn_ba2e37c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_4c54dcd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_edafda8.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_b0cf238.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_a4a4e1c.pf_fragment",
"/ran/pagefind/fragment/en_a8a649f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5835175.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e15bfdf.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_c485c6f.pf_fragment",
"/ran/pagefind/fragment/en_f917c1c.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/en_4962517.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2f53ac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/en_706f2f9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3862569.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b4a3160.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d652bdc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/en_e97d778.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_33bec34.pf_fragment",
"/ran/pagefind/fragment/en_b977a71.pf_fragment",
"/ran/pagefind/fragment/en_ee118c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_34ea4ae.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c22a2f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/en_c24a847.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac26bd2.pf_fragment",
"/ran/pagefind/fragment/en_26f681b.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c8f5515.pf_fragment",
"/ran/pagefind/fragment/en_2ac4367.pf_fragment",
"/ran/pagefind/fragment/en_9573fab.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5140bbc.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fe2afc5.pf_fragment",
"/ran/pagefind/fragment/en_3536b8f.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/en_b81d242.pf_fragment",
"/ran/pagefind/fragment/zh-cn_40d4cec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7a59efb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d4a11a0.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/en_a79eb77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ecda14a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_45b0a69.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66421a2.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_58e1be6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2271c8e.pf_fragment",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/index/zh-cn_46ba44f.pf_index",
"/ran/pagefind/index/zh-cn_d3d649f.pf_index",
"/ran/pagefind/index/zh-cn_6dc31cf.pf_index",
"/ran/pagefind/index/en_22ed417.pf_index",
"/ran/pagefind/index/zh-cn_9d20e76.pf_index",
"/ran/pagefind/index/en_921f893.pf_index",
"/ran/pagefind/index/en_5215296.pf_index",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind.en_3225b794d0.pf_meta",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/pagefind.zh-cn_b2218f75ea18a.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.js",
"/ran/icon_96.png",
"/ran/icon_48.png",
"/ran/assets/cn_src_article_sort_index.md.ozv7P1UH.lean.js",
"/ran/assets/src_types_模式匹配.md.CYWa6aGu.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Coivzg4q.js",
"/ran/assets/src_article_typescript_reconstruction.md.C9FWgslf.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Bi4eJ3hy.js",
"/ran/assets/src_ranuts_file_appendFile.md.BygyH7pi.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CFUrviTV.lean.js",
"/ran/assets/src_ranui_tabs_index.md.BDP6BkpL.js",
"/ran/assets/src_article_typescript_index.md.j77LZI3o.js",
"/ran/assets/src_ranuts_utils_formatJson.md.C7LX8ZbB.js",
"/ran/assets/src_ranuts_file_watchFile.md.CK9XyHBc.lean.js",
"/ran/assets/src_article_bundle.md.Bp9C61uC.js",
"/ran/assets/src_ranui_checkbox_index.md.DYjbvU6t.js",
"/ran/assets/src_article_typescript_calculate.md.C9eRjRrc.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DHPcXRVa.js",
"/ran/assets/src_ranui_modal_index.md.ZRyI-y2K.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.CFUrviTV.js",
"/ran/assets/inter-roman-latin.Bu8hRsVA.woff2",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DclocTho.js",
"/ran/assets/inter-italic-latin-ext.BGcWXLrn.woff2",
"/ran/assets/src_ranui_message_index.md.CuUD0YT0.lean.js",
"/ran/assets/src_article_sort_select_index.md.mkDYp3ut.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CZkKwvn0.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BkNQWrrO.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.wvpDjpkF.js",
"/ran/assets/cn_src_ranui_tab_index.md.qPjTrtFm.js",
"/ran/assets/src_article_typescript_pattern.md.NvNwDQhf.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/src_ranui_popover_index.md.DahAvrwq.lean.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_article_sort_index.md.Dp_mDeun.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BkNQWrrO.js",
"/ran/assets/src_ranuts_bundler_index.md.y4jJErG5.lean.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C6hwnryM.lean.js",
"/ran/assets/src_ranui_preview_index.md.D-9c0ggs.js",
"/ran/assets/src_article_imagemin.md.BedyiB4M.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.C7LX8ZbB.lean.js",
"/ran/assets/src_ranui_icon_index.md.DnzhPh68.js",
"/ran/assets/src_article_typescript_recursion.md.CsvbrTIb.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.C0y8LUDs.js",
"/ran/assets/inter-italic-cyrillic.D6csxwjC.woff2",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_ranuts_file_fileInfo.md.DGkmqBNj.js",
"/ran/assets/src_article_sort_bubble_index.md.C7CrpY7J.js",
"/ran/assets/src_ranui_tabs_index.md.BDP6BkpL.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.0XiDfXto.js",
"/ran/assets/src_ranuts_utils_str2xml.md.CYyjQ2ld.js",
"/ran/assets/cn_src_ranui_progress_index.md.CnqTlXTQ.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.DD1mJpi4.js",
"/ran/assets/src_ranui_button_index.md.CdO4CI_k.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_index.md.Dp_mDeun.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D7Bi8zfA.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.B99LnlBU.js",
"/ran/assets/src_article_sort_count_index.md.C6sTnbgv.js",
"/ran/assets/src_ranuts_file_readFile.md.d81Ha1YY.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.B--qmCgx.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CSisJe03.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.BygyH7pi.js",
"/ran/assets/src_types_TS类型.md.CX4xf_P0.lean.js",
"/ran/assets/src_types_模式匹配.md.CYWa6aGu.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BY9PFuDr.js",
"/ran/assets/src_ranuts_file_readDir.md.6SROja99.js",
"/ran/assets/src_article_designMode.md.BhzHFSJr.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_article_sort_quick_index.md.BPZ92_E3.js",
"/ran/assets/cn_src_ranui_modal_index.md.K1yiGVve.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DYXkUdPt.js",
"/ran/assets/src_ranui_skeleton_index.md.DQ97cL_s.js",
"/ran/assets/app.BAaZiV2Z.js",
"/ran/assets/src_ranuts_utils_ocr.md.RL_ejIgl.lean.js",
"/ran/assets/src_article_sort_insert_index.md.By0ObsNT.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.BF__zNb4.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/cn_src_ranui_input_index.md.o9kfNFWg.js",
"/ran/assets/src_ranui_radar_index.md.tPmcoAhJ.lean.js",
"/ran/assets/src_article_typescript_unionType.md.BiPBPMaY.js",
"/ran/assets/src_article_astParse_tokenizer.md.DsEATUeE.lean.js",
"/ran/assets/inter-italic-greek.9J96vYpw.woff2",
"/ran/assets/src_article_functionalProgramming.md.Dqh5EJaE.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranui_player_index.md.CAkVogCE.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_bundle.md.B1dKEg7I.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.Bi4eJ3hy.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.0o6WwvtL.js",
"/ran/assets/src_article_typescript_unionType.md.BiPBPMaY.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DLICBHmv.lean.js",
"/ran/assets/cn_src_article_imagemin.md.8wrHcYmw.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_ranui_button_index.md.Mh2ZGoDA.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C7j8MFZd.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.YWmUtU-w.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.CYsVrsPR.lean.js",
"/ran/assets/src_types_高级类型.md.C-LMDFSr.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.BbN9Eny2.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.BY9PFuDr.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.C9kZTVh_.js",
"/ran/assets/cn_src_article_typescript_pattern.md.B--qmCgx.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.o9kfNFWg.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.jsaPfTPp.js",
"/ran/assets/cn_src_types_类型运算.md.DwOghwdT.js",
"/ran/assets/src_ranui_input_index.md.GEP-J1lq.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.CZkKwvn0.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.jsaPfTPp.lean.js",
"/ran/assets/cn_src_types_TS类型.md.Dn3L3NHK.js",
"/ran/assets/src_ranui_select_index.md.DEecKmuc.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.xV77se0d.lean.js",
"/ran/assets/src_article_sort_radix_index.md.WGke8TYG.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DYXkUdPt.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranuts_file_readDir.md.6SROja99.lean.js",
"/ran/assets/cn_src_article_babel.md.DwA9o5-w.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DB-Sl8ga.js",
"/ran/assets/cn_src_types_高级类型.md.C95uVinu.js",
"/ran/assets/cn_src_ranui_select_index.md.6xlJzpw4.lean.js",
"/ran/assets/cn_src_article_sort_index.md.ozv7P1UH.js",
"/ran/assets/src_article_typescript_calculate.md.C9eRjRrc.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BoZEnsPt.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DDS5TUNU.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CaLSXkkj.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.B99LnlBU.lean.js",
"/ran/assets/cn_src_ranuts_index.md.lOeRimaJ.lean.js",
"/ran/assets/src_ranui_modal_index.md.ZRyI-y2K.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.qQQ8vIN3.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DOjJr7f_.lean.js",
"/ran/assets/src_ranui_message_index.md.CuUD0YT0.js",
"/ran/assets/src_article_sort_count_index.md.C6sTnbgv.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/inter-italic-vietnamese.DHNAd7Wr.woff2",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DHPcXRVa.lean.js",
"/ran/assets/src_ranui_image_index.md.D9iHoerd.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_article_typescript_index.md.j77LZI3o.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.xV77se0d.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_designMode.md.D6ScpOZX.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.B7xihypU.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.Mh2ZGoDA.js",
"/ran/assets/cn_src_article_sort_count_index.md.BbN9Eny2.js",
"/ran/assets/src_article_sort_insert_index.md.By0ObsNT.js",
"/ran/assets/cn_src_article_typescript_unionType.md.GEPdSeqn.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DaGDrE_j.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C7j8MFZd.js",
"/ran/assets/cn_src_ranui_tab_index.md.qPjTrtFm.lean.js",
"/ran/assets/src_ranui_radar_index.md.tPmcoAhJ.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranui_button_index.md.CdO4CI_k.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_binaryTree_index.md.C7-Dg19m.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CQ0_11Y4.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D7Bi8zfA.js",
"/ran/assets/cn_src_ranui_message_index.md.qQQ8vIN3.lean.js",
"/ran/assets/src_ranui_player_index.md.jsfTCN-m.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranui_skeleton_index.md.CUfsjaAg.lean.js",
"/ran/assets/src_article_sort_radix_index.md.WGke8TYG.lean.js",
"/ran/assets/src_ranui_preview_index.md.D-9c0ggs.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranuts_file_readDir.md.C5C0c5B6.js",
"/ran/assets/cn_src_ranui_radar_index.md.C0y8LUDs.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.C5C0c5B6.lean.js",
"/ran/assets/src_ranui_index.md.BC8K7uga.js",
"/ran/assets/src_ranui_popover_index.md.DahAvrwq.js",
"/ran/assets/src_article_bundle.md.Bp9C61uC.lean.js",
"/ran/assets/cn_src_article_imagemin.md.8wrHcYmw.lean.js",
"/ran/assets/src_ranui_tab_index.md.CTQSlEiW.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_file_watchFile.md.mB01ZyOb.js",
"/ran/assets/inter-roman-greek-ext.D0mI3NpI.woff2",
"/ran/assets/cn_src_ranui_index.md.C45sByI0.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_sort_heap_index.md.CkFZKPPg.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.xGF4mIoF.lean.js",
"/ran/assets/src_ranui_player_index.md.jsfTCN-m.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BoZEnsPt.js",
"/ran/assets/index.md.B4dZVP9o.js",
"/ran/assets/src_article_astParse_tokenizer.md.DsEATUeE.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_file_writeFile.md.B1oS36Ds.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.DGkmqBNj.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.DD1mJpi4.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_functionalProgramming.md.Dqh5EJaE.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DsJrrA1Y.lean.js",
"/ran/assets/cn_src_types_高级类型.md.C95uVinu.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.0XiDfXto.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.d81Ha1YY.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/docx-ajDUtnbM.p4g6Uing.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/theme.dlElyEsX.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/colz-CRDozfZA.DvkPXySn.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/pdf-B2a6ll8f.Be-ad9qj.js",
"/ran/assets/chunks/jszip.min-Ca6PjkYs.DD0071KX.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/framework.A_XI1Ui1.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/index.CZ1tdOOT.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/index-ByJ7zZdQ.yYIBMgFO.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/index-CZlEoE62.DjYDx5Id.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DclocTho.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BMcrtfb-.js",
"/ran/assets/src_ranuts_utils_task.md.CuSav3D2.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.BIVhUaTz.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.D1OcnJrQ.js",
"/ran/assets/cn_src_article_sort_select_index.md.BF__zNb4.js",
"/ran/assets/cn_src_article_typescript_unionType.md.GEPdSeqn.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranuts_index.md.ROHxYV5t.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.DYjbvU6t.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.CK9XyHBc.js",
"/ran/assets/cn_src_ranui_icon_index.md.CAm10wCM.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_tabs_index.md.D1UAUlQ8.js",
"/ran/assets/inter-roman-cyrillic.CMhn1ESj.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.DGB8Pd-L.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.C7-Dg19m.lean.js",
"/ran/assets/src_article_babel.md.DpJNGKv1.js",
"/ran/assets/cn_src_ranui_index.md.C45sByI0.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.D9hLNyj4.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/cn_src_ranui_select_index.md.6xlJzpw4.js",
"/ran/assets/src_article_sort_heap_index.md.CkFZKPPg.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DOjJr7f_.js",
"/ran/assets/cn_src_ranui_icon_index.md.CAm10wCM.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_article_bundle.md.B1dKEg7I.js",
"/ran/assets/cn_src_ranui_preview_index.md.BIVhUaTz.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_index.md.C5p8sR02.js",
"/ran/assets/src_ranuts_bundler_index.md.y4jJErG5.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranui_icon_index.md.DnzhPh68.lean.js",
"/ran/assets/src_article_sort_merge_index.md.CaLSXkkj.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_ranui_modal_index.md.K1yiGVve.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.BMcrtfb-.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.DaGDrE_j.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranui_popover_index.md.CpkhoSnN.js",
"/ran/assets/src_article_designMode.md.BhzHFSJr.js",
"/ran/assets/style.Di5pl0Hz.css",
"/ran/assets/src_article_babel.md.DpJNGKv1.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_sort_radix_index.md.DsJrrA1Y.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_types_高级类型.md.C-LMDFSr.js",
"/ran/assets/src_article_javascript_domLoad.md.NtWNg6Xy.lean.js",
"/ran/assets/src_article_imagemin.md.BedyiB4M.js",
"/ran/assets/src_ranuts_utils_getCookie.md.0o6WwvtL.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D1UAUlQ8.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.CpkhoSnN.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DQ97cL_s.lean.js",
"/ran/assets/cn_index.md.C5p8sR02.lean.js",
"/ran/assets/inter-roman-latin-ext.ZlYT4o7i.woff2",
"/ran/assets/cn_src_article_sort_quick_index.md.vG9f5f4w.lean.js",
"/ran/assets/inter-roman-greek.JvnBZ4YD.woff2",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.B7xihypU.js",
"/ran/assets/src_ranuts_utils_filterObj.md.Coivzg4q.lean.js",
"/ran/assets/src_types_TS类型.md.CX4xf_P0.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.CQ0_11Y4.lean.js",
"/ran/assets/cn_src_ranuts_index.md.lOeRimaJ.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_sort_bubble_index.md.DGB8Pd-L.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_ranuts_utils_str2xml.md.CYyjQ2ld.lean.js",
"/ran/assets/src_article_sort_shell_index.md.DDS5TUNU.js",
"/ran/assets/cn_src_types_TS类型.md.Dn3L3NHK.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_article_sort_bubble_index.md.C7CrpY7J.lean.js",
"/ran/assets/src_ranui_index.md.BC8K7uga.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.B1oS36Ds.js",
"/ran/assets/cn_src_types_模式匹配.md.CYsVrsPR.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DM4hlcWw.js",
"/ran/assets/src_ranui_tab_index.md.CTQSlEiW.js",
"/ran/assets/src_ranuts_index.md.ROHxYV5t.js",
"/ran/assets/src_ranui_progress_index.md.RHcm44fU.js",
"/ran/assets/src_article_sort_quick_index.md.BPZ92_E3.lean.js",
"/ran/assets/cn_src_article_designMode.md.D6ScpOZX.lean.js",
"/ran/assets/cn_src_types_类型运算.md.DwOghwdT.lean.js",
"/ran/assets/cn_src_article_babel.md.DwA9o5-w.js",
"/ran/assets/cn_src_ranui_progress_index.md.CnqTlXTQ.js",
"/ran/assets/cn_src_ranui_player_index.md.CAkVogCE.js",
"/ran/assets/src_article_javascript_domLoad.md.NtWNg6Xy.js",
"/ran/assets/inter-italic-latin.DbsTr1gm.woff2",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C6hwnryM.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C6ZP_DLJ.lean.js",
"/ran/assets/src_article_sort_select_index.md.mkDYp3ut.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_functionalProgramming.md.DB-Sl8ga.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CUfsjaAg.js",
"/ran/assets/src_types_类型运算.md.Bn8fAiYn.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DM4hlcWw.lean.js",
"/ran/assets/src_ranui_input_index.md.GEP-J1lq.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.mB01ZyOb.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.wvpDjpkF.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.RL_ejIgl.js",
"/ran/assets/index.md.B4dZVP9o.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.C9FWgslf.js",
"/ran/assets/src_article_typescript_recursion.md.CsvbrTIb.js",
"/ran/assets/cn_src_ranui_image_index.md.C9kZTVh_.lean.js",
"/ran/assets/src_ranui_progress_index.md.RHcm44fU.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/inter-roman-cyrillic-ext.DxP3Awbn.woff2",
"/ran/assets/src_ranui_image_index.md.D9iHoerd.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C6ZP_DLJ.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.D9hLNyj4.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_typescript_reconstruction.md.xGF4mIoF.js",
"/ran/assets/src_ranuts_utils_task.md.CuSav3D2.js",
"/ran/assets/src_types_类型运算.md.Bn8fAiYn.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/inter-italic-greek-ext.CHOfFY1k.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.YWmUtU-w.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/inter-roman-vietnamese.ClpjcLMQ.woff2",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CSisJe03.js",
"/ran/assets/src_ranui_select_index.md.DEecKmuc.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.5XJwZIOp.woff2",
"/ran/assets/cn_src_article_astParse_tokenizer.md.D1OcnJrQ.lean.js",
"/ran/assets/src_article_typescript_pattern.md.NvNwDQhf.js",
"/ran/assets/cn_src_article_sort_quick_index.md.vG9f5f4w.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DLICBHmv.js",
"/ran/screenshots_748x1340.jpg",
"/ran/home.svg",
"/ran/sw1712411280.js",
"/ran/icon_144.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/favicon.ico",
"/ran/manifest.json",
"/ran/cn/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/icon.png",
"/ran/icon_72.png",
"/ran/icon_168.png",
"/ran/hashmap.json",
];
const VERSION = "1712411280";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
    // google 上报不需要缓存
    'google',
    // 插件请求不用缓存
    'chrome-extension',
    // 百度的请求不用缓存
    'baidu.com',
    'blob:',
    'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
    GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
    SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
    INSTALL: 'install',
    FETCH: 'fetch',
    ACTIVATE: 'activate',
    MESSAGE: 'message',
    SYNC: 'sync',
    PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
    const { url } = request
    const { status } = fetchedResponse
    // 只缓存状态码为 200 的请求
    if (status !== RESPONSE_STATUS.SUCCESS) return
    if (filterRequest(request)) {
        caches.open(CACHE_NAME).then(cache => {
            // 将请求到的资源添加到缓存中
            // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
            if (fetchedResponse?.clone) {
                cache.put(url, fetchedResponse.clone());
            }
        }).catch(error => {
            console.log('service worker update cache error:', error, request)
        })
    }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
    const { url, method } = request
    return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
    // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
    try {
        const { url } = request
        const responseFromCache = await caches.match(url);
        // 如果缓存中有，返回已经缓存的资源
        if (responseFromCache) return responseFromCache
        // 如果缓存中没有，就从网络中请求，并更新到缓存中
        const responseFromServer = await fetch(request);
        updateCache(responseFromServer, request)
        return responseFromServer
    } catch (error) {
        // 当缓存中也没有，请求也不可用的时候
        // 始终需要一个一个响应
        // 甚至可以设置回落的请求，在catch中继续发起请求
        console.log('service worker cacheFirst error:', error, request)
        return new Response("Network error happened", {
            status: 408,
            headers: { "Content-Type": "text/plain" },
        });
    }
}


const deleteCache = async (key) => {
    try {
        await caches.delete(key);
    } catch (error) {
        console.log('service worker deleteCache error:', error, key)
    }
};

const deleteOldCaches = async () => {
    const cacheKeepList = [CACHE_NAME];
    try {
        const keyList = await caches.keys();
        const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
        await Promise.all(cachesToDelete.map(deleteCache));
    } catch (error) {
        console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
    }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
    // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
    event.waitUntil(
        // 创建了叫做 chaxus_ran 的新缓存
        caches.open(CACHE_NAME).then(function (cache) {
            // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
            // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
            // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
            // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
            return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
                fetch(url).then(response => {
                    // 检查响应是否成功
                    if (!response.ok) {
                        console.log('service worker fetch response error:', url)
                    }
                    // 将响应添加到缓存
                    return cache.put(url, response);
                }).catch(error => {
                    console.log('service worker self installed error:', url, error);
                })
            )
        })
    );
});

this.addEventListener(SERVICE_WORK.FETCH, (event) => {
    // 拦截请求
    try {
        const { request } = event
        // 忽略 IGNORE_REQUEST_LIST 中的请求，不进行拦截
        if (filterRequest(request)) {
            const responseFromServer = cacheFirst(request)
            if (responseFromServer?.clone) {
                event.respondWith(responseFromServer);
            }
        }
    } catch (error) {
        console.log('service worker self fetch error:', error, event)
    }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
    event.waitUntil(deleteOldCaches());
});



