const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/en_6623363.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_45b0a69.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c8f5515.pf_fragment",
"/ran/pagefind/fragment/en_26f681b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_976d864.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_58e1be6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_edafda8.pf_fragment",
"/ran/pagefind/fragment/en_e97d778.pf_fragment",
"/ran/pagefind/fragment/en_ab5b7c1.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_bad2bb4.pf_fragment",
"/ran/pagefind/fragment/en_3536b8f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ecda14a.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_ac97cd9.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3862569.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5140bbc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_33bec34.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ba2e37c.pf_fragment",
"/ran/pagefind/fragment/en_9573fab.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2271c8e.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5835175.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/en_a4a4e1c.pf_fragment",
"/ran/pagefind/fragment/en_4962517.pf_fragment",
"/ran/pagefind/fragment/en_c485c6f.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5888cbb.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_ee118c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_c24a847.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fe2afc5.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/en_75d1df3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/en_a8a649f.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_a79eb77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_1e31265.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac26bd2.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_2ac4367.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66421a2.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d652bdc.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d4a11a0.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_45694f5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b4a3160.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_3bfb6f7.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_706f2f9.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/en_b0cf238.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eaf0e54.pf_fragment",
"/ran/pagefind/fragment/zh-cn_34ea4ae.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e15bfdf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c22a2f.pf_fragment",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/index/en_b73cc6a.pf_index",
"/ran/pagefind/index/zh-cn_bbc0229.pf_index",
"/ran/pagefind/index/en_7219282.pf_index",
"/ran/pagefind/index/en_cb44d31.pf_index",
"/ran/pagefind/index/zh-cn_44ef41e.pf_index",
"/ran/pagefind/index/zh-cn_9b7a61c.pf_index",
"/ran/pagefind/index/zh-cn_6b9c5fe.pf_index",
"/ran/pagefind/pagefind.zh-cn_293dbe38db673.pf_meta",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind.en_afdf36aa0b.pf_meta",
"/ran/404.html",
"/ran/icon_168.png",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/babel.html",
"/ran/src/article/bundle.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/icon_48.png",
"/ran/assets/cn_src_ranui_tabs_index.md.BhYWPhD2.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranui_button_index.md.aoyjt9rl.js",
"/ran/assets/src_types_TS类型.md.HggmYzpN.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DDGAafgv.js",
"/ran/assets/src_ranui_tab_index.md.DAh_M6w5.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.D-wyG8UB.js",
"/ran/assets/src_ranuts_index.md.CIza8hrV.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DkNr_dwf.js",
"/ran/assets/cn_src_article_sort_heap_index.md.MaVrE4Pl.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CuyaMYUi.js",
"/ran/assets/src_ranui_progress_index.md.D3NOhGmT.lean.js",
"/ran/assets/src_article_imagemin.md.CU3I20bN.js",
"/ran/assets/cn_src_ranui_button_index.md.aoyjt9rl.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.46Px7Bh-.js",
"/ran/assets/src_article_astParse_tokenizer.md.V2cdeRuM.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranuts_utils_formatJson.md.JCf7qlJq.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_skeleton_index.md.CJp_W3O7.js",
"/ran/assets/cn_src_article_typescript_index.md.D-wyG8UB.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.O3j5DoKo.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.joyXVhRm.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CP997vwA.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CP997vwA.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.Dykft9eG.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Czd_wL8r.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DF8vKG7q.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.wls28QOT.js",
"/ran/assets/cn_src_ranui_message_index.md.D5zlBUfX.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.C3N76vD-.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.qHC7rJvE.js",
"/ran/assets/cn_src_ranui_select_index.md.Bahqc2xP.lean.js",
"/ran/assets/cn_src_article_imagemin.md.4M4aTYBL.lean.js",
"/ran/assets/src_ranui_preview_index.md.DqYveP_g.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.46Px7Bh-.lean.js",
"/ran/assets/src_article_sort_quick_index.md.DITPxWsi.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.TuK1fF6l.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CGKyUYc3.js",
"/ran/assets/style.CPb1w6Q3.css",
"/ran/assets/cn_src_ranui_tabs_index.md.BhYWPhD2.js",
"/ran/assets/src_ranui_loading_index.md.kJxQ08e6.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_ranui_index.md.BNtbM1QY.js",
"/ran/assets/cn_src_article_sort_count_index.md.DJZ0hQy8.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CrQRayBu.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BNhw-lni.js",
"/ran/assets/src_article_typescript_index.md.DXwZo0ZE.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_article_sort_index.md.xzIte1VU.js",
"/ran/assets/src_article_typescript_pattern.md.ZJ54QIDW.lean.js",
"/ran/assets/cn_src_article_designMode.md.CM6a5vve.lean.js",
"/ran/assets/index.md.CbvtxL3l.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CY1DzLh_.js",
"/ran/assets/cn_src_types_TS类型.md.ryA_1bZO.js",
"/ran/assets/src_article_sort_select_index.md.BZKswzCU.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_article_sort_bubble_index.md.CGKyUYc3.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/cn_src_ranuts_bundler_index.md.RaFkMio9.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DlC_-h5M.js",
"/ran/assets/src_article_sort_radix_index.md.DA6WEU55.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_types_高级类型.md.Drc0x8lH.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_ranuts_utils_filterObj.md.D4pnYSez.lean.js",
"/ran/assets/src_ranuts_index.md.CIza8hrV.js",
"/ran/assets/src_ranui_message_index.md.CULrudMH.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DLyKYcSy.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BJh6Ee2q.lean.js",
"/ran/assets/cn_src_ranuts_index.md.ClQVZG2S.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DIXeXOex.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_article_javascript_domLoad.md.BDrOlXj7.js",
"/ran/assets/src_article_sort_count_index.md.CPg51XI9.js",
"/ran/assets/src_ranui_image_index.md.CetV1Qn6.js",
"/ran/assets/src_ranuts_utils_ocr.md.QPJp6_pb.js",
"/ran/assets/src_ranui_radar_index.md.BGU5DaSl.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.q7iQIBAQ.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Ls8XzYqa.lean.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/framework.2G9cXQ-T.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CcerIMu-.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/index-CkaNwcpF.YT6dpSX_.js",
"/ran/assets/chunks/index.CgrYiQEI.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/theme.CuxyTdme.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/index-CGEx9VOA.nPGv-hKH.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/src_article_sort_merge_index.md.C3816vI8.js",
"/ran/assets/src_ranuts_mode_subscribe.md.a82Ag72q.js",
"/ran/assets/cn_src_ranui_radar_index.md.BU4TY_eW.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Da2XYnLc.js",
"/ran/assets/src_ranuts_utils_getCookie.md.BNhw-lni.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranui_tab_index.md.DAh_M6w5.js",
"/ran/assets/src_article_designMode.md.CFhFfr5K.lean.js",
"/ran/assets/src_article_sort_count_index.md.CPg51XI9.lean.js",
"/ran/assets/src_article_sort_insert_index.md.DF8vKG7q.js",
"/ran/assets/cn_index.md.DCwWfP1B.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranuts_binaryTree_index.md.CTLhnynd.js",
"/ran/assets/src_article_typescript_recursion.md.Cq_k7H8k.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranui_image_index.md.CetV1Qn6.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CUZkMmxK.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.7mXp9Ng2.lean.js",
"/ran/assets/src_types_TS类型.md.HggmYzpN.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CgDNzEhO.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CJp_W3O7.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.ivphXN-j.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CMzntt4Z.js",
"/ran/assets/src_ranuts_utils_task.md.DUIYVMB3.lean.js",
"/ran/assets/cn_src_ranui_index.md.DBDLwY6u.js",
"/ran/assets/src_article_bundle.md.DzbsqUP_.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.CeZgDKmZ.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.HeThnj2F.js",
"/ran/assets/cn_src_types_TS类型.md.ryA_1bZO.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_ranui_player_index.md.fMojsMnA.lean.js",
"/ran/assets/src_article_sort_shell_index.md.BJh6Ee2q.js",
"/ran/assets/cn_src_article_typescript_calculate.md.zflCy0ju.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_sort_index.md.T81Xxpdo.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.qHC7rJvE.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.RaFkMio9.lean.js",
"/ran/assets/src_article_sort_quick_index.md.DITPxWsi.js",
"/ran/assets/src_article_typescript_reconstruction.md.CQddNYZM.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_babel.md.tI74V4DE.js",
"/ran/assets/cn_src_ranui_modal_index.md.HeThnj2F.lean.js",
"/ran/assets/src_article_functionalProgramming.md.ByUvsF5Z.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranui_skeleton_index.md.DslWmLGF.js",
"/ran/assets/src_ranui_popover_index.md.D6y4lhLP.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CEv3qUp7.lean.js",
"/ran/assets/src_ranuts_utils_task.md.DUIYVMB3.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_typescript_unionType.md.B9Khl-Z8.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BWXW5_7_.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DkNr_dwf.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.CuyaMYUi.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.fMojsMnA.js",
"/ran/assets/cn_src_ranui_index.md.DBDLwY6u.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.C3N76vD-.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DPELk7r5.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_types_模式匹配.md.6fNG0SSi.js",
"/ran/assets/src_ranui_preview_index.md.DqYveP_g.js",
"/ran/assets/src_article_designMode.md.CFhFfr5K.js",
"/ran/assets/src_article_sort_merge_index.md.C3816vI8.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.BDMnaPNt.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.CQddNYZM.js",
"/ran/assets/src_ranuts_bundler_index.md.joyXVhRm.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranuts_file_readFile.md.CWDIjZae.js",
"/ran/assets/src_ranui_checkbox_index.md.q0Kw_loi.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BcWWiHUi.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranuts_file_fileInfo.md.TL_wTcTa.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Dq_7PwwC.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.opNnqxaO.js",
"/ran/assets/cn_src_ranui_message_index.md.D5zlBUfX.js",
"/ran/assets/cn_src_article_sort_radix_index.md.CgDNzEhO.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.opNnqxaO.lean.js",
"/ran/assets/src_article_typescript_calculate.md.hTrQl2PS.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_article_sort_index.md.xzIte1VU.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BPya_mOr.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.wls28QOT.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/cn_src_article_sort_index.md.T81Xxpdo.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranui_message_index.md.CULrudMH.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DZJ7u-Ek.js",
"/ran/assets/src_ranuts_utils_formatJson.md.JCf7qlJq.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.D5ABokah.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.DuLGKzuR.js",
"/ran/assets/src_ranuts_mode_subscribe.md.a82Ag72q.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/src_ranui_select_index.md.nmVWH9re.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.MQgS64GF.lean.js",
"/ran/assets/src_ranui_select_index.md.nmVWH9re.js",
"/ran/assets/cn_src_ranui_popover_index.md.BCUSa9fX.lean.js",
"/ran/assets/src_article_functionalProgramming.md.ByUvsF5Z.lean.js",
"/ran/assets/src_article_sort_radix_index.md.DA6WEU55.lean.js",
"/ran/assets/src_ranui_radar_index.md.BGU5DaSl.js",
"/ran/assets/cn_src_ranui_loading_index.md.BPRyjl1P.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.TuK1fF6l.js",
"/ran/assets/cn_src_article_typescript_pattern.md.O3j5DoKo.js",
"/ran/assets/src_article_babel.md.CQVMx4lJ.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DZgdX9Dk.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Dse_de8n.js",
"/ran/assets/index.md.CbvtxL3l.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.TL_wTcTa.js",
"/ran/assets/src_article_typescript_index.md.DXwZo0ZE.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BWXW5_7_.lean.js",
"/ran/assets/src_ranui_button_index.md.DZUKzHFv.lean.js",
"/ran/assets/src_article_typescript_calculate.md.hTrQl2PS.js",
"/ran/assets/src_article_bundle.md.DzbsqUP_.js",
"/ran/assets/src_ranuts_file_watchFile.md.CusouMJm.lean.js",
"/ran/assets/src_ranui_player_index.md.DWgCA2Ov.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.CTLhnynd.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BPRyjl1P.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.BDrOlXj7.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_modal_index.md.S2d95_Z5.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/src_ranui_input_index.md.Bj17zp69.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_file_writeFile.md.D0JZGOlj.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CrQRayBu.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DIXeXOex.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.Czd_wL8r.js",
"/ran/assets/cn_src_ranui_tab_index.md.MN8Oa-d1.js",
"/ran/assets/cn_src_types_高级类型.md.BPya_mOr.js",
"/ran/assets/src_ranui_index.md.BNtbM1QY.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.DJZ0hQy8.js",
"/ran/assets/src_ranui_progress_index.md.D3NOhGmT.js",
"/ran/assets/cn_src_article_sort_heap_index.md.MaVrE4Pl.js",
"/ran/assets/cn_src_ranui_progress_index.md.IUe1Wwsz.js",
"/ran/assets/src_article_sort_select_index.md.BZKswzCU.js",
"/ran/assets/src_ranuts_utils_filterObj.md.D4pnYSez.js",
"/ran/assets/src_types_高级类型.md.Drc0x8lH.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DLyKYcSy.js",
"/ran/assets/src_ranui_skeleton_index.md.DslWmLGF.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/cn_src_article_bundle.md.CvSDn_St.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/cn_src_ranuts_index.md.ClQVZG2S.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_article_sort_heap_index.md.DcqLTu4H.lean.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BQ3ETw8_.lean.js",
"/ran/assets/cn_src_article_bundle.md.CvSDn_St.js",
"/ran/assets/cn_src_article_imagemin.md.4M4aTYBL.js",
"/ran/assets/cn_src_ranui_preview_index.md.CeZgDKmZ.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Cx5IYbbW.js",
"/ran/assets/app.BzzNoyVr.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.Cx5IYbbW.lean.js",
"/ran/assets/src_article_typescript_recursion.md.Cq_k7H8k.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Da2XYnLc.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.7mXp9Ng2.js",
"/ran/assets/src_article_babel.md.CQVMx4lJ.js",
"/ran/assets/src_article_imagemin.md.CU3I20bN.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.BcWWiHUi.lean.js",
"/ran/assets/src_ranui_loading_index.md.kJxQ08e6.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.V2cdeRuM.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_ranuts_file_watchFile.md.DZJ7u-Ek.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/cn_src_ranui_icon_index.md.Db2uZ80f.js",
"/ran/assets/src_article_sort_bucket_index.md.Ls8XzYqa.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/src_ranui_button_index.md.DZUKzHFv.js",
"/ran/assets/src_ranui_icon_index.md.Cil5NvnK.lean.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_ranui_select_index.md.Bahqc2xP.js",
"/ran/assets/cn_index.md.DCwWfP1B.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.DlC_-h5M.lean.js",
"/ran/assets/cn_src_types_类型运算.md.CW7-RuRl.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DZgdX9Dk.js",
"/ran/assets/src_ranuts_file_readFile.md.CWDIjZae.lean.js",
"/ran/assets/src_ranui_player_index.md.DWgCA2Ov.js",
"/ran/assets/cn_src_article_babel.md.tI74V4DE.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_types_模式匹配.md.ivphXN-j.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.Dse_de8n.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/src_ranui_popover_index.md.D6y4lhLP.js",
"/ran/assets/cn_src_ranui_popover_index.md.BCUSa9fX.js",
"/ran/assets/src_ranuts_file_watchFile.md.CusouMJm.js",
"/ran/assets/src_ranui_input_index.md.Bj17zp69.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BQ3ETw8_.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.D5ABokah.js",
"/ran/assets/src_ranuts_file_writeFile.md.D0JZGOlj.js",
"/ran/assets/src_types_类型运算.md.BkJ878YS.js",
"/ran/assets/src_ranui_checkbox_index.md.q0Kw_loi.js",
"/ran/assets/cn_src_article_sort_quick_index.md.CUZkMmxK.js",
"/ran/assets/cn_src_ranui_radar_index.md.BU4TY_eW.js",
"/ran/assets/src_article_sort_heap_index.md.DcqLTu4H.js",
"/ran/assets/cn_src_article_sort_select_index.md.DuLGKzuR.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CFrNPX0f.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.MN8Oa-d1.lean.js",
"/ran/assets/src_article_typescript_unionType.md.B9Khl-Z8.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.q7iQIBAQ.js",
"/ran/assets/cn_src_article_typescript_calculate.md.zflCy0ju.lean.js",
"/ran/assets/src_article_typescript_pattern.md.ZJ54QIDW.js",
"/ran/assets/src_ranui_modal_index.md.S2d95_Z5.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.CY1DzLh_.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CMzntt4Z.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DDGAafgv.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DPELk7r5.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.BDMnaPNt.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/src_ranuts_file_appendFile.md.UThqrVip.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/cn_src_ranui_progress_index.md.IUe1Wwsz.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.Dykft9eG.js",
"/ran/assets/src_types_类型运算.md.BkJ878YS.lean.js",
"/ran/assets/cn_src_article_designMode.md.CM6a5vve.js",
"/ran/assets/cn_src_ranui_input_index.md.CFrNPX0f.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.Dq_7PwwC.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_icon_index.md.Db2uZ80f.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.QPJp6_pb.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_file_appendFile.md.UThqrVip.lean.js",
"/ran/assets/src_types_模式匹配.md.6fNG0SSi.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CEv3qUp7.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_types_类型运算.md.CW7-RuRl.lean.js",
"/ran/assets/src_ranui_icon_index.md.Cil5NvnK.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.MQgS64GF.js",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/example.m3u8",
"/ran/sw1719153834.js",
"/ran/icon_144.png",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/index.html",
"/ran/hashmap.json",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/icon_96.png",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/home.svg",
"/ran/icon.png",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/manifest.json",
];
const VERSION = "1719153834";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



