const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/babel.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/icon_72.png",
"/ran/404.html",
"/ran/home.svg",
"/ran/assets/cn_src_article_sort_select_index.md.CNQ5RK20.js",
"/ran/assets/cn_src_article_visual.md.tGcGmuhs.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_sort_shell_index.md.D0ibuta2.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.DVmKH2sV.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.DKVNEl0-.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.BjCvQF16.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Cy97xYh2.lean.js",
"/ran/assets/cn_src_article_designMode.md.D2VYQEGP.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.B92URr3N.lean.js",
"/ran/assets/src_article_typescript_unionType.md.BxNtKVLv.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/src_ranui_message_index.md.Yzxbby3X.js",
"/ran/assets/cn_src_ranui_image_index.md.BlFtl7fG.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.D5jKyjr1.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DGoxYW36.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.C6f5SmrE.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DHYiuXep.lean.js",
"/ran/assets/cn_src_article_visual.md.tGcGmuhs.lean.js",
"/ran/assets/src_article_functionalProgramming.md.CST4B-Cb.lean.js",
"/ran/assets/cn_index.md.Bt_QpXYX.js",
"/ran/assets/src_ranuts_file_fileInfo.md.Bk8Vl8xZ.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DpZJrQ9c.lean.js",
"/ran/assets/src_ranui_button_index.md.6oAPtDv1.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranuts_utils_ocr.md.C7iMWTz0.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_ranuts_bundler_index.md.DFKChRuR.lean.js",
"/ran/assets/app.BN0mb3GM.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_types_模式匹配.md.D3jDsXM7.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.BztnjodR.lean.js",
"/ran/assets/src_ranui_index.md.D2tnx2iQ.lean.js",
"/ran/assets/cn_src_ranuts_index.md.VPP0tgi_.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_imagemin.md.C-V0sXIq.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_imagemin.md.Cchln95d.js",
"/ran/assets/cn_src_article_docPreview.md.qIF8TGPc.js",
"/ran/assets/src_ranui_math_index.md.DfUjxfrU.js",
"/ran/assets/src_ranui_player_index.md.D8TDjyVJ.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.B6sd1I-d.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BVEen2IR.lean.js",
"/ran/assets/cn_src_note_centos.md.Qt78n5Js.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CDs7hSK-.lean.js",
"/ran/assets/src_ranui_message_index.md.Yzxbby3X.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CjOn8JHR.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranui_select_index.md.Cx6VzdeO.js",
"/ran/assets/cn_src_article_systemDesign.md.D5jKyjr1.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/src_ranuts_index.md.CQaoRmlY.js",
"/ran/assets/cn_src_ranui_image_index.md.BlFtl7fG.js",
"/ran/assets/cn_src_article_typescript_unionType.md.D4bwegXM.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.cgzDBcZo.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/src_article_astParse_tokenizer.md.BZS9LMho.js",
"/ran/assets/src_article_sort_merge_index.md.D3HCLPV4.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DBVjNtXQ.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.lEcWK1bl.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.DBVjNtXQ.js",
"/ran/assets/src_ranui_checkbox_index.md.Ctef0Ivx.js",
"/ran/assets/src_article_sort_bubble_index.md.Dv05ScpU.js",
"/ran/assets/cn_src_ranui_radar_index.md.DO38afme.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.lEcWK1bl.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BMuk2fIv.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranui_math_index.md.CDv2yJvm.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.D0ibuta2.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_typescript_unionType.md.BxNtKVLv.js",
"/ran/assets/src_ranui_image_index.md.Bh-3Gocp.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/src_types_高级类型.md.Cs_OraYa.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DwPXuMaM.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_astParse_tokenizer.md.BZS9LMho.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.Dv05ScpU.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.CRmJ7hYh.js",
"/ran/assets/src_ranui_loading_index.md.DHwZpDQp.js",
"/ran/assets/cn_src_types_模式匹配.md.BrNYXumg.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranuts_file_readDir.md.DCCRjebv.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DFKChRuR.js",
"/ran/assets/src_ranui_input_index.md.BuVNXLSe.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DRt8uTe9.lean.js",
"/ran/assets/cn_src_article_imagemin.md.Cchln95d.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.CDs7hSK-.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DRjncSSo.js",
"/ran/assets/cn_src_ranui_index.md.Da8SIRMP.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BSK7G1JV.lean.js",
"/ran/assets/src_article_sort_quick_index.md.qZX4nWcO.lean.js",
"/ran/assets/src_article_bundle.md.DX0y23Gh.lean.js",
"/ran/assets/cn_src_article_sort_count_index.md.CYE4xcdP.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_ranui_popover_index.md.D_MStnhj.lean.js",
"/ran/assets/cn_src_article_sort_index.md.BDePVknZ.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.DGoxYW36.lean.js",
"/ran/assets/src_article_sort_radix_index.md.C41P6LvB.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Dq4R1SRw.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CdXzf7gt.js",
"/ran/assets/src_ranuts_utils_getCookie.md.F97eNLlY.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.Cy97xYh2.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_functionalProgramming.md.CST4B-Cb.js",
"/ran/assets/cn_src_article_sort_index.md.BDePVknZ.js",
"/ran/assets/cn_src_article_video.md.BFiBkSPx.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_types_高级类型.md.BYvaFsdZ.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_article_astParse_tokenizer.md.SRzAXahU.lean.js",
"/ran/assets/cn_src_types_类型运算.md.xARDxk4i.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.Ba83aF-G.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_ranui_modal_index.md.CdAgBk0f.lean.js",
"/ran/assets/index.md.Dg3dR-yJ.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.m-KItjxJ.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C1jxi_ZM.js",
"/ran/assets/src_article_sort_count_index.md.B75uMbEv.js",
"/ran/assets/src_ranui_progress_index.md.DinTrIQU.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.BKNuuTDq.js",
"/ran/assets/src_ranuts_index.md.CQaoRmlY.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BVEen2IR.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/cn_src_article_video.md.BFiBkSPx.js",
"/ran/assets/src_ranuts_mode_subscribe.md.M8j5RpVf.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_article_sort_quick_index.md.DPato8LE.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.DRt8uTe9.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.C6f5SmrE.js",
"/ran/assets/src_types_高级类型.md.Cs_OraYa.js",
"/ran/assets/cn_src_article_bundle.md.Cbyi_uFT.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.DwPXuMaM.lean.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_sort_merge_index.md.D3HCLPV4.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CZXa-jbJ.js",
"/ran/assets/cn_src_ranui_popover_index.md.D4ZxjEJ9.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DIVZl_g0.js",
"/ran/assets/cn_src_ranuts_index.md.VPP0tgi_.js",
"/ran/assets/cn_src_article_babel.md.CC71exoN.lean.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.DIVZl_g0.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.BjCvQF16.lean.js",
"/ran/assets/cn_src_note_centos.md.Qt78n5Js.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranui_button_index.md.6oAPtDv1.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.M8j5RpVf.js",
"/ran/assets/src_ranuts_utils_ocr.md.C7iMWTz0.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.22Wavw7V.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.Ba83aF-G.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C5dKCj7N.js",
"/ran/assets/cn_src_types_TS类型.md.CLKSykSG.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.Be-9lHmS.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BE_GbejJ.js",
"/ran/assets/src_article_sort_count_index.md.B75uMbEv.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_article_typescript_calculate.md.DRnQwUN5.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/src_ranui_radar_index.md.DA5X4b9r.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_ranui_image_index.md.Bh-3Gocp.js",
"/ran/assets/cn_src_note_ubuntu.md.plQUSwYP.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.DHYiuXep.js",
"/ran/assets/cn_src_ranui_player_index.md.22Wavw7V.js",
"/ran/assets/src_ranuts_file_writeFile.md.CRmJ7hYh.lean.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_ranui_input_index.md.BuVNXLSe.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.Df7bE905.lean.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.Df7bE905.js",
"/ran/assets/src_ranui_icon_index.md.di-XPR5Q.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Ghlae-ud.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Bc0IL3cT.lean.js",
"/ran/assets/cn_src_note_docker.md.BSzVmVKY.js",
"/ran/assets/cn_src_ranui_radar_index.md.DO38afme.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CGU32Mz7.js",
"/ran/assets/index.md.Dg3dR-yJ.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.C1jxi_ZM.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DXqe-Cl0.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Dfrxvhui.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.BE_GbejJ.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.avWFJE_V.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BAkrovMV.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.hbksEDw8.js",
"/ran/assets/chunks/index.CafPLwUV.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/framework.eq-HTtE3.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/index-Co9E57uv.DM_Nu_-Q.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/theme.DbZz0xHr.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/pwa-install.es.DuMXkPrI.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CmQSFM5C.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Byf79MII.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/index-Ba501-HG.DLGTjfcz.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/src_ranuts_utils_task.md.B3Hu7e7A.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.7lDNSGC3.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_article_sort_radix_index.md.tScBAjGa.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BItwzht9.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_ranuts_binaryTree_index.md.wpq1IuQ7.lean.js",
"/ran/assets/cn_index.md.Bt_QpXYX.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BIIDB6ih.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.Cr1whhWt.js",
"/ran/assets/src_ranui_checkbox_index.md.Ctef0Ivx.lean.js",
"/ran/assets/src_ranui_preview_index.md.DnCXoewR.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_types_模式匹配.md.D3jDsXM7.js",
"/ran/assets/src_ranui_radar_index.md.DA5X4b9r.js",
"/ran/assets/src_ranui_tab_index.md.C_4gV-im.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/src_ranui_popover_index.md.D_MStnhj.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.D_uzzQVr.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_article_typescript_index.md.BZWQmL-X.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_ranuts_file_appendFile.md.7lDNSGC3.js",
"/ran/assets/cn_src_types_模式匹配.md.BrNYXumg.lean.js",
"/ran/assets/style.D7_Ytddv.css",
"/ran/assets/cn_src_ranui_message_index.md.Be-9lHmS.lean.js",
"/ran/assets/src_article_typescript_index.md.BZWQmL-X.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.yZD99FXy.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_article_sort_index.md.wol_PffW.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.6pp-tyNF.lean.js",
"/ran/assets/src_ranui_tab_index.md.C_4gV-im.js",
"/ran/assets/src_article_sort_heap_index.md.BVztWsFF.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.CdXzf7gt.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CmGYaSaG.js",
"/ran/assets/src_article_javascript_domLoad.md.Cr1whhWt.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.DPato8LE.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.B6sd1I-d.js",
"/ran/assets/src_ranui_player_index.md.D8TDjyVJ.js",
"/ran/assets/src_article_sort_select_index.md.b4ueSfo_.lean.js",
"/ran/assets/src_ranui_preview_index.md.DnCXoewR.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranui_icon_index.md.di-XPR5Q.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BMuk2fIv.lean.js",
"/ran/assets/src_ranui_progress_index.md.DinTrIQU.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_types_TS类型.md.Cs8y_B17.js",
"/ran/assets/src_article_bundle.md.DX0y23Gh.js",
"/ran/assets/cn_src_note_ubuntu.md.plQUSwYP.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.Cbnn_-0x.js",
"/ran/assets/src_ranui_index.md.D2tnx2iQ.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Ghlae-ud.js",
"/ran/assets/src_article_imagemin.md.C-V0sXIq.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_article_typescript_unionType.md.D4bwegXM.js",
"/ran/assets/src_ranuts_file_readDir.md.DCCRjebv.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_typescript_calculate.md.DRnQwUN5.js",
"/ran/assets/cn_src_article_sort_merge_index.md.DRjncSSo.lean.js",
"/ran/assets/src_article_sort_insert_index.md.CAsRW6pg.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.CNQ5RK20.lean.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.6pp-tyNF.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_ranui_modal_index.md.hOOuh2-0.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_babel.md.CC71exoN.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranuts_utils_formatJson.md.DVmKH2sV.js",
"/ran/assets/src_article_designMode.md.BCIrU_2o.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.Dfrxvhui.js",
"/ran/assets/cn_src_ranui_tab_index.md.CmGYaSaG.lean.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.SRzAXahU.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.Dq4R1SRw.js",
"/ran/assets/cn_src_article_functionalProgramming.md.cgzDBcZo.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CF2D3XWN.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.D4ZxjEJ9.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/src_ranui_math_index.md.DfUjxfrU.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CTNzOIes.js",
"/ran/assets/src_article_typescript_reconstruction.md.BztnjodR.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.Bc0IL3cT.js",
"/ran/assets/src_ranuts_utils_task.md.B3Hu7e7A.js",
"/ran/assets/cn_src_ranui_math_index.md.CDv2yJvm.js",
"/ran/assets/src_article_designMode.md.BCIrU_2o.js",
"/ran/assets/cn_src_article_designMode.md.D2VYQEGP.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.avWFJE_V.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.C5dKCj7N.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.D_uzzQVr.js",
"/ran/assets/src_ranui_tabs_index.md.CZXa-jbJ.lean.js",
"/ran/assets/src_article_sort_insert_index.md.CAsRW6pg.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DXqe-Cl0.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.BAkrovMV.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.CjOn8JHR.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.v7ZMz_73.lean.js",
"/ran/assets/cn_src_ranui_index.md.Da8SIRMP.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_ranuts_file_readFile.md.DKVNEl0-.js",
"/ran/assets/cn_src_article_sort_count_index.md.CYE4xcdP.lean.js",
"/ran/assets/src_article_typescript_pattern.md.FZctwQFP.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/src_ranui_select_index.md.Cx6VzdeO.lean.js",
"/ran/assets/cn_src_types_高级类型.md.BYvaFsdZ.js",
"/ran/assets/src_ranuts_binaryTree_index.md.wpq1IuQ7.js",
"/ran/assets/src_ranuts_file_watchFile.md.B92URr3N.js",
"/ran/assets/src_article_sort_heap_index.md.BVztWsFF.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CGU32Mz7.lean.js",
"/ran/assets/src_article_sort_radix_index.md.C41P6LvB.lean.js",
"/ran/assets/cn_src_article_docPreview.md.qIF8TGPc.lean.js",
"/ran/assets/src_ranuts_utils_filterObj.md.BItwzht9.lean.js",
"/ran/assets/src_types_类型运算.md.aRU6YhuI.js",
"/ran/assets/cn_src_ranui_select_index.md.Cqc9IrE2.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.v7ZMz_73.js",
"/ran/assets/cn_src_ranui_select_index.md.Cqc9IrE2.js",
"/ran/assets/src_article_typescript_recursion.md.CTNzOIes.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_note_docker.md.BSzVmVKY.lean.js",
"/ran/assets/src_article_sort_select_index.md.b4ueSfo_.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.CF2D3XWN.js",
"/ran/assets/cn_src_article_bundle.md.Cbyi_uFT.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.BIIDB6ih.js",
"/ran/assets/src_ranui_modal_index.md.hOOuh2-0.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranui_modal_index.md.CdAgBk0f.js",
"/ran/assets/src_article_sort_shell_index.md.BJUozPCR.lean.js",
"/ran/assets/src_types_TS类型.md.Cs8y_B17.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_article_babel.md.CgNusvp6.lean.js",
"/ran/assets/cn_src_types_类型运算.md.xARDxk4i.lean.js",
"/ran/assets/src_article_sort_quick_index.md.qZX4nWcO.js",
"/ran/assets/src_article_sort_shell_index.md.BJUozPCR.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.yZD99FXy.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BSK7G1JV.js",
"/ran/assets/cn_src_article_typescript_pattern.md.DpZJrQ9c.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_ranuts_file_readDir.md.BKNuuTDq.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_ranuts_file_fileInfo.md.Bk8Vl8xZ.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/cn_src_ranui_preview_index.md.Caoc4Rzu.js",
"/ran/assets/cn_src_ranui_button_index.md.Cbnn_-0x.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.Caoc4Rzu.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.tScBAjGa.js",
"/ran/assets/src_article_typescript_pattern.md.FZctwQFP.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_ranui_loading_index.md.DHwZpDQp.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_babel.md.CgNusvp6.js",
"/ran/assets/cn_src_types_TS类型.md.CLKSykSG.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_article_javascript_domLoad.md.m-KItjxJ.js",
"/ran/assets/src_ranuts_utils_getCookie.md.F97eNLlY.js",
"/ran/assets/src_article_sort_index.md.wol_PffW.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_typescript_calculate.md.hbksEDw8.lean.js",
"/ran/assets/src_types_类型运算.md.aRU6YhuI.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/sw1728187712.js",
"/ran/icon_48.png",
"/ran/icon_144.png",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind.zh-cn_b71a7d8847108.pf_meta",
"/ran/pagefind/pagefind.en_853ef581ec.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/index/zh-cn_9bacfc2.pf_index",
"/ran/pagefind/index/en_bc39585.pf_index",
"/ran/pagefind/index/zh-cn_8d4814d.pf_index",
"/ran/pagefind/index/en_e8e8597.pf_index",
"/ran/pagefind/index/en_d22f299.pf_index",
"/ran/pagefind/index/zh-cn_64ecbb3.pf_index",
"/ran/pagefind/index/zh-cn_933a426.pf_index",
"/ran/pagefind/index/zh-cn_88a2748.pf_index",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95fa787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66f42e8.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f9c4333.pf_fragment",
"/ran/pagefind/fragment/zh-cn_489c27d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c1151c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5584627.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e64f93e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ea6667.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6df03b5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7d7b75a.pf_fragment",
"/ran/pagefind/fragment/en_b7c8c16.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d1b782.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f09c929.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c82f3b2.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/zh-cn_50313a9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_75a264c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_154849c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bab657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_67d6c7a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d388141.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2c21dbd.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d98338a.pf_fragment",
"/ran/pagefind/fragment/en_7118fbe.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_449b12a.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/en_38d8359.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e88bc3f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3de2e5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5919.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_565fd27.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f4f874.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6dde39.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac92f78.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/zh-cn_27c99c4.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bb9206.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9879172.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f379427.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5df12ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2e89f3.pf_fragment",
"/ran/pagefind/fragment/en_b110a5b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e347438.pf_fragment",
"/ran/pagefind/fragment/en_b24f7ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e831ca8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3e43b1f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_44fa7df.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ab33e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/en_5eef384.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/en_30709d8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ca356d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7edffe.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_58279de.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_39da2fe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_68b3659.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f7dcce8.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_815cbc8.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59bdbd3.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d32fcee.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7b2564.pf_fragment",
"/ran/pagefind/fragment/en_3df5c5f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5190b59.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f2527de.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3fb29d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/en_c2412d4.pf_fragment",
"/ran/pagefind/fragment/en_5094588.pf_fragment",
"/ran/pagefind/fragment/en_6a9915b.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_715eacf.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c5d845d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8998463.pf_fragment",
"/ran/pagefind/fragment/en_5861ab4.pf_fragment",
"/ran/pagefind/fragment/en_ee9f170.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51dafe6.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_32113cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51bdb63.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5042f4c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_677ff04.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a3cd5f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a1e1243.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_63cffab.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ef213d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ad6344.pf_fragment",
"/ran/icon_96.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/icon_168.png",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/index.html",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/icon.png",
"/ran/manifest.json",
"/ran/icon_192.png",
];
const VERSION = "1728187712";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



