const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/assets/src_article_typescript_reconstruction.md.fQBDzFcb.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BB8CNUnI.lean.js",
"/ran/assets/src_article_typescript_pattern.md.8R7SJQ1i.js",
"/ran/assets/src_article_sort_heap_index.md.CAsfsEpC.lean.js",
"/ran/assets/src_article_sort_select_index.md.DGGl0t3T.lean.js",
"/ran/assets/create-wallet.BL5Ekg1Q.webp",
"/ran/assets/cn_src_types_类型运算.md.CcOsFnIk.js",
"/ran/assets/src_ranuts_mode_subscribe.md.D3E9aIEQ.js",
"/ran/assets/cn_src_article_sort_merge_index.md.BB8CNUnI.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_article_typescript_index.md.Bp4OQBdS.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranuts_file_watch_file.md.rSvUblrs.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CHzkwFAJ.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.4x6BXoZk.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DJgrBltC.js",
"/ran/assets/src_ranuts_file_file_info.md.C2t3ysne.lean.js",
"/ran/assets/src_article_sort_radix_index.md.o6OejVrr.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BqlVG8GX.js",
"/ran/assets/cn_index.md.DKMOQ9RX.lean.js",
"/ran/assets/metamask.vkbli3xR.webp",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_ranuts_file_append_file.md.C6OxFV-I.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/pancake-swap.Dw8g9TCO.webp",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_typescript_index.md.Bp4OQBdS.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.dDEhuato.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/src_ranui_math_index.md.CUYCz611.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BipJ8L_P.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_article_sort_quick_index.md.C0vVVeH4.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_types_类型运算.md.CcOsFnIk.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/src_article_typescript_pattern.md.8R7SJQ1i.lean.js",
"/ran/assets/cn_src_article_imagemin.md.ChsbHiFO.js",
"/ran/assets/cn_src_article_doc_preview.md.DIywIIrY.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.C8KKA7Mp.lean.js",
"/ran/assets/metamask-nft.hqrCF68r.webp",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_file_file_info.md.BA8Wl9CZ.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.DGag0hkT.lean.js",
"/ran/assets/cn_src_article_bundle.md.CEg7f3Mf.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.tiKqPGrl.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.BAXBgMIb.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_article_typescript_union_type.md.DCC7nrPU.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_article_sort_bubble_index.md.CsaFLbBW.js",
"/ran/assets/src_article_design_mode.md.B4Zw5rf-.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_ranuts_file_append_file.md.C6OxFV-I.lean.js",
"/ran/assets/cn_src_article_visual.md.B6UvAXpd.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CiKdPmgU.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CU87MdjF.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.Bd4ipluz.js",
"/ran/assets/src_ranui_tabs_index.md.DuwKchB1.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DO6iMQjL.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_bundle.md.D0yvULKW.js",
"/ran/assets/cn_src_blockchain_index.md.FVyOIQPR.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.r3xvo3Se.lean.js",
"/ran/assets/metamask-key.CF8M4nrY.webp",
"/ran/assets/src_ranuts_bundler_index.md.DwSN1H0Q.lean.js",
"/ran/assets/metamask-protect.DEAh_p5D.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.Cs4sRCSM.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Cvlrr0Oi.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_types_类型运算.md.CjtQoASq.js",
"/ran/assets/cn_src_article_sort_radix_index.md.DX526C3W.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranui_radar_index.md.Cije2A2d.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_ranui_popover_index.md.DT_EpZR8.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.CHzkwFAJ.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/blockchain-swap.D5C4r3T0.webp",
"/ran/assets/cn_src_ranuts_file_write_file.md.CU87MdjF.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranui_skeleton_index.md.CRMtvtjR.js",
"/ran/assets/src_article_functional_programming.md.BXyI4MMb.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_article_javascript_dom_load.md.DdJ2WdbN.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.COxxsf4E.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.B8ZA0G_p.js",
"/ran/assets/src_ranui_loading_index.md.-Ohvj6H4.js",
"/ran/assets/src_ranui_player_index.md.wkX-gZOq.js",
"/ran/assets/element-metamask.yERy34tY.webp",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_select_index.md.DN9768x0.lean.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/src_article_sort_bubble_index.md.CsaFLbBW.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.DO6iMQjL.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BqlVG8GX.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_article_sort_count_index.md.C26JDD2Z.js",
"/ran/assets/cn_src_blockchain_index.md.FVyOIQPR.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.DdJ2WdbN.js",
"/ran/assets/cn_src_ranui_tabs_index.md.BCWdgd1q.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_sort_radix_index.md.DX526C3W.js",
"/ran/assets/cn_src_article_babel.md.D1LxR1J5.lean.js",
"/ran/assets/element-success.BZn-bEtt.webp",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_popover_index.md.tiKqPGrl.js",
"/ran/assets/cn_src_article_sort_count_index.md.CtfImvqq.lean.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CTJlyN-i.lean.js",
"/ran/assets/src_ranui_progress_index.md.B9WJtmfK.lean.js",
"/ran/assets/src_ranui_index.md.xRcNHaXW.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_article_functional_programming.md.BXyI4MMb.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.DwSN1H0Q.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BN5j-nB-.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.CrKktQrD.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.CTJlyN-i.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_article_sort_heap_index.md.Cs4sRCSM.lean.js",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/metamask-createsuccess._7aicP-j.webp",
"/ran/assets/src_ranuts_index.md.wKlBIq4z.lean.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.CrKktQrD.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.fQBDzFcb.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/cn_src_ranui_loading_index.md.Az3j1tN4.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_article_sort_insert_index.md.Bd4ipluz.lean.js",
"/ran/assets/src_ranuts_file_read_dir.md.DEIGuuet.js",
"/ran/assets/src_article_sort_select_index.md.DGGl0t3T.js",
"/ran/assets/src_ranuts_utils_ocr.md.B_N1X8Iy.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.BhyQ3OTj.js",
"/ran/assets/src_ranui_index.md.xRcNHaXW.js",
"/ran/assets/src_article_sort_merge_index.md.COM6MfnV.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BGyrIY_J.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.Z_5Wz7UU.js",
"/ran/assets/src_article_javascript_dom_load.md.B8sqWjFs.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DmRWTqg6.lean.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_article_babel.md.oqlXtsL7.lean.js",
"/ran/assets/src_article_sort_insert_index.md.Du1pdAR7.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DFuvietB.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Dcuup3t3.js",
"/ran/assets/metamask-confirm.DU60OsfQ.webp",
"/ran/assets/src_ranuts_file_read_file.md.COxxsf4E.js",
"/ran/assets/src_ranui_icon_index.md.CxBXqimi.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_article_system_design.md.DYMc6cF8.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DaCDW0VB.js",
"/ran/assets/blockchain-content.CmHz4_fp.webp",
"/ran/assets/cn_src_ranui_button_index.md.BZ1WEZ0x.js",
"/ran/assets/cn_src_ranui_radar_index.md.ESA7tcWZ.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/src_ranui_image_index.md.3EqjqP6t.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.BhyQ3OTj.lean.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.dDEhuato.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.Bu_F8Svy.js",
"/ran/assets/src_types_高级类型.md.imIZa45J.lean.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CajLy6fm.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.fQIDwCkG.js",
"/ran/assets/src_article_sort_heap_index.md.CAsfsEpC.js",
"/ran/assets/src_types_TS类型.md.DzjWbcIu.lean.js",
"/ran/assets/src_ranui_modal_index.md.DKmCiwAm.js",
"/ran/assets/cn_src_ranui_input_index.md.DsDAzUb4.js",
"/ran/assets/cn_src_ranui_radar_index.md.ESA7tcWZ.lean.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/cn_src_article_video.md.WkG9I8UA.lean.js",
"/ran/assets/cn_src_article_design_mode.md.TbuHxNiA.js",
"/ran/assets/pancake-detail.DYLxc6tE.webp",
"/ran/assets/cn_src_article_visual.md.B6UvAXpd.lean.js",
"/ran/assets/src_article_sort_index.md.BUljoQ2B.lean.js",
"/ran/assets/cn_src_ranui_index.md.DDJYAHe7.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranuts_utils_get_cookie.md.RCCWRw9N.lean.js",
"/ran/assets/src_ranuts_utils_format_json.md.D_z68N2F.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranui_math_index.md.BOyB_6tT.lean.js",
"/ran/assets/src_ranui_input_index.md.CvI4kefb.js",
"/ran/assets/cn_src_types_模式匹配.md.BuKHoyNb.js",
"/ran/assets/cn_src_blockchain_web3.md.BPUbRg0W.js",
"/ran/assets/cn_src_article_system_design.md.DYMc6cF8.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranuts_file_file_info.md.BA8Wl9CZ.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranuts_file_write_file.md.4x6BXoZk.lean.js",
"/ran/assets/src_article_typescript_calculate.md.gUoFJiw3.js",
"/ran/assets/src_ranuts_utils_format_json.md.D_z68N2F.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DMG4792f.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.CspquIUs.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.C8x0RPr1.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/cn_src_ranui_preview_index.md.DdHSsorf.js",
"/ran/assets/cn_src_note_centos.md.C9GghHdA.js",
"/ran/assets/src_article_sort_count_index.md.C26JDD2Z.lean.js",
"/ran/assets/src_ranui_preview_index.md.DiFCql49.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranui_progress_index.md.Qf12E7a7.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.Drnl618k.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_ranui_tab_index.md.Cllbgt61.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DKrIBakP.lean.js",
"/ran/assets/cn_src_article_video.md.WkG9I8UA.js",
"/ran/assets/cn_src_article_sort_select_index.md.C2yxuPhn.js",
"/ran/assets/element-polyhedra.CB9OXus7.webp",
"/ran/assets/cn_src_ranuts_file_read_file.md.CspquIUs.lean.js",
"/ran/assets/src_ranui_checkbox_index.md.Dcuup3t3.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.B6yHMyOf.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_typescript_pattern.md.9IT2UC1L.js",
"/ran/assets/cn_src_article_doc_preview.md.DIywIIrY.js",
"/ran/assets/cn_src_types_TS类型.md.BDBNDht7.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.r3xvo3Se.js",
"/ran/assets/cn_src_blockchain_web3.md.BPUbRg0W.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_ranuts_utils_ocr.md.B_N1X8Iy.lean.js",
"/ran/assets/blockchain-tree.A7z-d9nO.webp",
"/ran/assets/style.B51h211J.css",
"/ran/assets/src_ranui_skeleton_index.md.CDuivcWj.lean.js",
"/ran/assets/src_article_imagemin.md.B1oI1PE6.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CRmxVZvX.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.CBz72JOh.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.CRMtvtjR.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.RCCWRw9N.js",
"/ran/assets/cn_src_types_模式匹配.md.BuKHoyNb.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/pancake-metamask.B6Zhf4O6.webp",
"/ran/assets/cn_src_ranui_message_index.md.CBz72JOh.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.DKrIBakP.js",
"/ran/assets/src_ranuts_file_append_file.md.DsYZSbqi.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.C8x0RPr1.js",
"/ran/assets/cn_src_ranui_icon_index.md.C1msyt9c.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DmRWTqg6.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/cn_src_ranui_math_index.md.BOyB_6tT.js",
"/ran/assets/app.D78o20vc.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_typescript_union_type.md.DCC7nrPU.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_index.md.DKMOQ9RX.js",
"/ran/assets/src_ranuts_utils_str2xml.md.DJgrBltC.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_types_类型运算.md.CjtQoASq.lean.js",
"/ran/assets/src_ranui_radar_index.md.Cije2A2d.js",
"/ran/assets/metamask-token.B7WJfZiv.webp",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3-DAY0DgPh.DcQ9QdGJ.js",
"/ran/assets/chunks/index.D5grTCvU.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/theme.C-kiz8_X.js",
"/ran/assets/chunks/book-nTEFXU2x-BvY35CMb.DPEdiL1I.js",
"/ran/assets/chunks/home-BUQ4USMk-C2nbhvtZ.BqTharGj.js",
"/ran/assets/chunks/index.uzNxw7c1.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/check-circle-szyAJiap-ClZivfVI.CM_vbBX5.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/unlock-CeU74z9n-BxB2opdV.58atcEuH.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/power-off-lQRbiBak-DcHnxku-.r13EH4bb.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/framework.CApOETg9.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/close-CFnkhudp-DInt_GS9.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO-DnoXuzit.C8N16-9H.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/eye-D_mEt17f-CVTb40Hq.DJFa_ttF.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/search-BWdfjyP8-CLaimEXc.CdFUVZ0R.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/pdf-DRw1818j.BszTcE-_.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/@localSearchIndexcn.Rw3pf135.js",
"/ran/assets/chunks/without-content-CdJw7vHM.CYK1qjz_.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/@localSearchIndexroot.Hhug-zhH.js",
"/ran/assets/chunks/VPLocalSearchBox.CAEKN7KD.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs-Bm7ZHLU4.Dxgzakn4.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ-CxNFZEW5.B9YJorcw.js",
"/ran/assets/chunks/setting-DemlgzVC-DLC7fxEX.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i-Y2_L3s2r.7RyGfSeR.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/katex-es-9DCIED1s.CGTSaMxD.js",
"/ran/assets/chunks/sprite-CH2zLtZy-CVdmSPKr.Djo3sTkk.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/sort-DWqiUONr-BHkxnzb7.C56fs5Gu.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i-dWW7Jy4a.BsLXh5-a.js",
"/ran/assets/chunks/pwa-install.es.CyliIjjp.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/message-D36_Zo2l-CjpTcvt4.CR8K3LhI.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/team-tl4NJXPC-C1YuKw_w.D7881a1v.js",
"/ran/assets/chunks/lock-Cr7BnmWN-BHb11yDM.0WfYXC2j.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg-DC1RKLuy.DsdsDDgX.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv-Df6_CD0s.1BX6MOiy.js",
"/ran/assets/chunks/user-B-eVXwuk-B-jF4D1U.DyoYYAjs.js",
"/ran/assets/chunks/add-user-BN1JlY7e-BbH6gvZe.D6YNNzf8.js",
"/ran/assets/chunks/without-content-CdJw7vHM-DirXp6SF.CYK1qjz_.js",
"/ran/assets/chunks/loading-Dcc5RApI-78qa8Z8G.D3l74EUI.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.DLJtTP9o.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/close-circle-CwmuN2C6-CHbRWPjt.D612j4KD.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm-Uorz2TPs.Di19NrRU.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/cn_src_ranui_input_index.md.DsDAzUb4.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.Z_5Wz7UU.lean.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_types_高级类型.md.B_h5etBI.js",
"/ran/assets/metamask-password.DhQJZ4k3.webp",
"/ran/assets/cn_src_ranui_modal_index.md.DGag0hkT.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_babel.md.D1LxR1J5.js",
"/ran/assets/src_ranui_preview_index.md.DiFCql49.lean.js",
"/ran/assets/src_ranui_button_index.md.BUK6QVVn.js",
"/ran/assets/cn_src_note_ubuntu.md.BLt2o5jO.lean.js",
"/ran/assets/cn_src_article_typescript_union_type.md.Dd0M1k_g.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.6ZrD786-.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CRmxVZvX.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_sort_index.md.DjvmyGV5.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_ranui_select_index.md.DN9768x0.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.C-_zDFm4.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/blockchain-end.BakOYMF8.webp",
"/ran/assets/cn_src_ranui_icon_index.md.C1msyt9c.js",
"/ran/assets/src_ranui_loading_index.md.-Ohvj6H4.lean.js",
"/ran/assets/src_types_高级类型.md.imIZa45J.js",
"/ran/assets/metamask-writekey.BtyjY5oN.webp",
"/ran/assets/blockchain-trip.c0zeNxFx.webp",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_types_TS类型.md.BDBNDht7.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DaCDW0VB.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D8Fg_Q2E.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CsovuWOz.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_note_docker.md.CioN0K6X.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_ranui_tab_index.md.BibDZRe-.js",
"/ran/assets/blockchain.DJmrX8UH.webp",
"/ran/assets/cn_src_article_typescript_recursion.md.DWyfno_J.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Cvlrr0Oi.lean.js",
"/ran/assets/element-market.Dg1BawJr.webp",
"/ran/assets/cn_src_article_sort_quick_index.md.BAXBgMIb.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranui_tabs_index.md.DuwKchB1.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.C-_zDFm4.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CajLy6fm.js",
"/ran/assets/src_article_sort_bucket_index.md.C8KKA7Mp.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_file_read_dir.md.DEIGuuet.lean.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.Bu_F8Svy.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.9IT2UC1L.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.CiKdPmgU.lean.js",
"/ran/assets/src_ranui_player_index.md.wkX-gZOq.lean.js",
"/ran/assets/src_article_sort_insert_index.md.Du1pdAR7.js",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/pancake-confirm.BLEEyGPD.webp",
"/ran/assets/pancake-receipt.BowKqIf8.webp",
"/ran/assets/cn_src_article_imagemin.md.ChsbHiFO.lean.js",
"/ran/assets/cn_src_article_bundle.md.CEg7f3Mf.js",
"/ran/assets/src_ranui_progress_index.md.B9WJtmfK.js",
"/ran/assets/pancake-pot.DeOf5pf2.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_utils_task.md.D8Fg_Q2E.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CZnAY1Qy.js",
"/ran/assets/cn_src_article_typescript_union_type.md.Dd0M1k_g.js",
"/ran/assets/src_ranuts_file_append_file.md.DsYZSbqi.js",
"/ran/assets/src_types_模式匹配.md.Cvfs5Idm.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.BLt2o5jO.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/src_ranuts_file_file_info.md.C2t3ysne.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.6ZrD786-.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.CsovuWOz.lean.js",
"/ran/assets/src_ranuts_file_watch_file.md.rSvUblrs.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_sort_count_index.md.CtfImvqq.js",
"/ran/assets/src_article_sort_shell_index.md.B5PVG5fy.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.DWyfno_J.lean.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.DFuvietB.js",
"/ran/assets/src_article_sort_quick_index.md.C0vVVeH4.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CKGWCjgE.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/src_ranui_message_index.md.Bt0SWlet.lean.js",
"/ran/assets/cn_src_article_design_mode.md.TbuHxNiA.lean.js",
"/ran/assets/src_ranui_button_index.md.BUK6QVVn.lean.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_ranui_tabs_index.md.BCWdgd1q.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.B8ZA0G_p.lean.js",
"/ran/assets/cn_src_article_sort_index.md.DjvmyGV5.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Az3j1tN4.js",
"/ran/assets/src_ranui_message_index.md.Bt0SWlet.js",
"/ran/assets/cn_src_ranuts_index.md.CKGWCjgE.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.BGyrIY_J.js",
"/ran/assets/src_article_typescript_calculate.md.gUoFJiw3.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.CDuivcWj.js",
"/ran/assets/src_ranui_image_index.md.3EqjqP6t.js",
"/ran/assets/src_article_design_mode.md.B4Zw5rf-.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BipJ8L_P.lean.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_bundle.md.D0yvULKW.lean.js",
"/ran/assets/pancake.OylPBT8F.webp",
"/ran/assets/src_ranuts_utils_task.md.Vwkvwqk_.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.DMG4792f.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.Qf12E7a7.lean.js",
"/ran/assets/src_article_sort_merge_index.md.COM6MfnV.js",
"/ran/assets/index.md.CbYCUL1v.lean.js",
"/ran/assets/src_types_模式匹配.md.Cvfs5Idm.js",
"/ran/assets/src_ranui_modal_index.md.DKmCiwAm.lean.js",
"/ran/assets/src_article_imagemin.md.B1oI1PE6.js",
"/ran/assets/cn_src_ranui_index.md.DDJYAHe7.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/src_ranuts_utils_task.md.Vwkvwqk_.lean.js",
"/ran/assets/cn_src_note_centos.md.C9GghHdA.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/metamask-account.uAdblpcL.webp",
"/ran/assets/src_ranui_tab_index.md.BibDZRe-.lean.js",
"/ran/assets/cn_src_note_docker.md.CioN0K6X.lean.js",
"/ran/assets/src_ranui_input_index.md.CvI4kefb.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.CZnAY1Qy.lean.js",
"/ran/assets/src_types_TS类型.md.DzjWbcIu.js",
"/ran/assets/src_article_typescript_index.md.W8Bl50Sg.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.fQIDwCkG.lean.js",
"/ran/assets/src_ranuts_index.md.wKlBIq4z.js",
"/ran/assets/src_ranui_popover_index.md.DT_EpZR8.js",
"/ran/assets/src_article_sort_radix_index.md.o6OejVrr.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_shell_index.md.B5PVG5fy.js",
"/ran/assets/index.md.CbYCUL1v.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BN5j-nB-.lean.js",
"/ran/assets/src_ranui_math_index.md.CUYCz611.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_ranuts_binary_tree_index.md.B6yHMyOf.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.D3E9aIEQ.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.C2yxuPhn.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.Cllbgt61.js",
"/ran/assets/element-confirm.BcVMDo9L.webp",
"/ran/assets/cn_src_ranui_button_index.md.BZ1WEZ0x.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_article_sort_index.md.BUljoQ2B.js",
"/ran/assets/cn_src_ranui_preview_index.md.DdHSsorf.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.Drnl618k.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_babel.md.oqlXtsL7.js",
"/ran/assets/src_article_typescript_index.md.W8Bl50Sg.js",
"/ran/assets/cn_src_types_高级类型.md.B_h5etBI.lean.js",
"/ran/assets/src_ranui_icon_index.md.CxBXqimi.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_javascript_dom_load.md.B8sqWjFs.js",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/babel.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/bundle.html",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/blockchain/web3.html",
"/ran/cn/src/blockchain/index.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/index.html",
"/ran/icon_168.png",
"/ran/manifest.json",
"/ran/icon.png",
"/ran/icon_96.png",
"/ran/icon_192.png",
"/ran/icon_48.png",
"/ran/404.html",
"/ran/index.html",
"/ran/sw1753623367.js",
"/ran/favicon.ico",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/example.m3u8",
"/ran/home.svg",
"/ran/screenshots_2560x1440.jpg",
"/ran/icon_144.png",
"/ran/logo.png",
"/ran/vp-icons.css",
"/ran/icon_72.png",
"/ran/hashmap.json",
"/ran/screenshots_748x1340.jpg",
];
const VERSION = "1753623367";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非 GET 方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在 catch 中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似 Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



