const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon_168.png",
"/ran/icon_192.png",
"/ran/cn/index.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/assets/src_ranuts_index.md.B1lZzKMg.lean.js",
"/ran/assets/cn_src_article_imagemin.md.D17GhuO2.lean.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_article_astParse_tokenizer.md.BHmXsSf6.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BictYW0K.lean.js",
"/ran/assets/src_article_babel.md.Dwp4q4LC.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/cn_src_article_astParse_tokenizer.md.ogdOuiZK.lean.js",
"/ran/assets/src_ranui_button_index.md.C2wjRzU7.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/cn_src_article_bundle.md.GKN2vM0S.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.Cz89iwUK.js",
"/ran/assets/src_article_sort_bubble_index.md.BlcJ7OlR.lean.js",
"/ran/assets/src_ranui_select_index.md.D2nTsi0Y.js",
"/ran/assets/cn_index.md.BJgy4QAH.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranui_tab_index.md.C2EetDWK.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C-y7O1iu.js",
"/ran/assets/cn_src_article_visual.md.cWuDSJ79.lean.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/cn_src_ranui_math_index.md.Co_4aXAT.lean.js",
"/ran/assets/src_article_sort_bubble_index.md.BlcJ7OlR.js",
"/ran/assets/index.md.URc4pCpn.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/cn_src_ranui_radar_index.md.f8_gTjaC.js",
"/ran/assets/src_types_模式匹配.md.CV1FOM33.lean.js",
"/ran/assets/src_ranui_loading_index.md.Pk_nv3Wx.js",
"/ran/assets/src_article_sort_radix_index.md.siSqBiHq.js",
"/ran/assets/src_article_typescript_index.md.CjUGm1E0.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_sort_quick_index.md.C28tMffl.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/cn_src_article_sort_bubble_index.md.D2OL5wNT.lean.js",
"/ran/assets/src_article_typescript_calculate.md.Dt-ii_pB.js",
"/ran/assets/src_article_sort_heap_index.md.DGw_UQjk.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_ranui_index.md.Bmu77gUE.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.g6BAqcV8.js",
"/ran/assets/cn_src_ranui_image_index.md.DMYhbPC1.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.C1gcFbKU.js",
"/ran/assets/src_article_sort_select_index.md.DA-X-MSf.js",
"/ran/assets/src_ranui_skeleton_index.md.DiIGF0Cp.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.tZbNpEEJ.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.D4AFcDFM.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Bbrqi6Ef.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.K4weakjl.js",
"/ran/assets/src_ranui_skeleton_index.md.DiIGF0Cp.js",
"/ran/assets/src_ranuts_file_writeFile.md.Cw8ncP7d.lean.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranuts_file_readFile.md.BsiLc0H0.lean.js",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_ranui_button_index.md.Bo8Eunb8.js",
"/ran/assets/src_ranui_checkbox_index.md.BhQm2Mvb.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.DTuNAMLK.js",
"/ran/assets/src_ranui_math_index.md.Bw6EMeP8.js",
"/ran/assets/cn_src_ranui_progress_index.md.DqvEA1DO.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranui_preview_index.md.DVcmez3z.lean.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/cn_src_article_typescript_pattern.md.CmlhYtIv.js",
"/ran/assets/cn_src_ranui_loading_index.md.DsSOqC6w.js",
"/ran/assets/cn_src_article_sort_quick_index.md.C28tMffl.js",
"/ran/assets/cn_src_article_sort_index.md.ByZMwD9N.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DIGFNHgJ.lean.js",
"/ran/assets/src_ranui_index.md.BUndUWDa.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.C_YEm9yx.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BOsjYMqc.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.Co24Jm8p.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranui_math_index.md.Bw6EMeP8.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.BOsjYMqc.js",
"/ran/assets/src_ranui_tabs_index.md.BpnQHwwz.js",
"/ran/assets/cn_src_types_TS类型.md.ku82sttZ.lean.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_file_fileInfo.md.mCMabFd5.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_article_typescript_index.md.D9agpp78.lean.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_article_sort_select_index.md.DA-X-MSf.lean.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/cn_src_ranuts_file_readDir.md.DJYH_Enr.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/src_ranui_tab_index.md.C2EetDWK.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BmIn5LiX.lean.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/cn_src_article_video.md.C1V0oXFo.js",
"/ran/assets/src_article_bundle.md.ylqa9PGO.lean.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranui_checkbox_index.md.BhQm2Mvb.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.BictYW0K.js",
"/ran/assets/cn_src_article_sort_shell_index.md.BEmndUsQ.lean.js",
"/ran/assets/src_article_sort_insert_index.md.Dct8nPJ8.lean.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_article_typescript_unionType.md.BJOmcPtq.js",
"/ran/assets/src_ranui_image_index.md.BPkjHBcc.js",
"/ran/assets/src_ranuts_bundler_index.md.DYhqfdR8.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_article_sort_insert_index.md.BvMD4dsm.lean.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/src_article_sort_index.md.DuxpILCa.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_utils_str2xml.md.PZLv1TDd.lean.js",
"/ran/assets/src_article_bundle.md.ylqa9PGO.js",
"/ran/assets/src_ranui_icon_index.md.GUlHsdje.js",
"/ran/assets/src_ranui_image_index.md.BPkjHBcc.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CYzYq_b1.js",
"/ran/assets/cn_src_article_typescript_recursion.md.tZbNpEEJ.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BSqR3z2y.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Duq1VFMb.lean.js",
"/ran/assets/cn_src_article_imagemin.md.D17GhuO2.js",
"/ran/assets/cn_src_ranui_icon_index.md.CfP3CI7p.js",
"/ran/assets/src_ranui_input_index.md.D_kfSJN-.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.CFguuMJ9.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DB5QaWXN.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.CFguuMJ9.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.r_gyyDcN.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/cn_src_article_functionalProgramming.md.DX_9Zru3.js",
"/ran/assets/cn_src_article_docPreview.md.DQmkV91s.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/cn_src_types_类型运算.md.D8a7fZMz.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_article_sort_shell_index.md.cD0jKscc.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.BHmXsSf6.lean.js",
"/ran/assets/cn_src_article_bundle.md.GKN2vM0S.js",
"/ran/assets/src_article_babel.md.Dwp4q4LC.lean.js",
"/ran/assets/src_ranuts_file_readDir.md.Co24Jm8p.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BSqR3z2y.js",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/src_ranuts_file_writeFile.md.Cw8ncP7d.js",
"/ran/assets/src_ranuts_utils_str2xml.md.PZLv1TDd.js",
"/ran/assets/src_article_functionalProgramming.md.DdMMvksq.js",
"/ran/assets/cn_src_ranuts_index.md.C6CiQJiD.js",
"/ran/assets/src_article_sort_merge_index.md.S2Bu_221.js",
"/ran/assets/src_ranui_player_index.md.DWD-gv2r.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.BmIn5LiX.js",
"/ran/assets/app.BqggbcgT.js",
"/ran/assets/cn_src_ranui_select_index.md.CmzIAbW3.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_types_TS类型.md.Cq5vyMdv.js",
"/ran/assets/cn_src_article_designMode.md.COd1-yYM.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BvMD4dsm.js",
"/ran/assets/src_article_typescript_reconstruction.md.-VTRYvjr.lean.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/cn_src_ranui_progress_index.md.DqvEA1DO.js",
"/ran/assets/src_article_typescript_pattern.md.BgaIl4gx.js",
"/ran/assets/src_article_imagemin.md.CZl194w7.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/src_article_sort_quick_index.md.oIExHjQF.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.CmlhYtIv.lean.js",
"/ran/assets/cn_src_article_docPreview.md.DQmkV91s.js",
"/ran/assets/cn_src_article_designMode.md.COd1-yYM.js",
"/ran/assets/cn_src_article_sort_heap_index.md.B69UUy2V.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Cn57DRYb.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.DNRjesa8.js",
"/ran/assets/src_ranui_tabs_index.md.BpnQHwwz.lean.js",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B3GAzUum.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.DoBvRJ9o.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.D4O9xJZk.lean.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/src_ranuts_utils_ocr.md.Cf_a5wpr.lean.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DV_oawzp.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/cn_src_article_sort_count_index.md.D74R3EkJ.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.ogdOuiZK.js",
"/ran/assets/cn_src_ranui_preview_index.md.DVcmez3z.js",
"/ran/assets/src_ranuts_utils_filterObj.md.tInzAuO8.lean.js",
"/ran/assets/cn_src_article_visual.md.cWuDSJ79.js",
"/ran/assets/src_ranui_icon_index.md.GUlHsdje.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/src_ranui_select_index.md.D2nTsi0Y.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/src_article_typescript_unionType.md.BaubE5cJ.lean.js",
"/ran/assets/src_ranui_progress_index.md.CElwZnPe.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.DsSOqC6w.lean.js",
"/ran/assets/src_article_sort_insert_index.md.Dct8nPJ8.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_ranui_message_index.md.D9PEJiMQ.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.r_gyyDcN.lean.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranui_radar_index.md.NyO_QDCT.js",
"/ran/assets/cn_src_ranui_player_index.md.bX2Y8w5E.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.B3GAzUum.js",
"/ran/assets/src_ranui_modal_index.md.BeSUIONk.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.RgxquexD.js",
"/ran/assets/cn_src_types_高级类型.md.CxiMAktq.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.B69UUy2V.js",
"/ran/assets/cn_src_ranui_radar_index.md.f8_gTjaC.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/cn_src_ranuts_file_readFile.md.BsiLc0H0.js",
"/ran/assets/cn_src_ranui_image_index.md.DMYhbPC1.lean.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.DIGFNHgJ.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_ranui_popover_index.md.KCjt9rL2.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_utils_getCookie.md.emODLqae.js",
"/ran/assets/src_article_sort_radix_index.md.siSqBiHq.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.C1gcFbKU.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CfP3CI7p.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.mCMabFd5.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.C-y7O1iu.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.g6BAqcV8.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cq19YPyw.lean.js",
"/ran/assets/cn_src_types_TS类型.md.ku82sttZ.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.enaSlCiH.js",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/cn_src_ranui_input_index.md.D7f9ZDQa.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Cf_a5wpr.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_types_类型运算.md.Br0evDRf.js",
"/ran/assets/src_ranui_input_index.md.D_kfSJN-.js",
"/ran/assets/src_article_typescript_reconstruction.md.-VTRYvjr.js",
"/ran/assets/cn_src_ranui_select_index.md.CmzIAbW3.lean.js",
"/ran/assets/src_ranui_player_index.md.DWD-gv2r.js",
"/ran/assets/cn_src_ranui_tabs_index.md.Ba0traun.js",
"/ran/assets/src_ranuts_file_readFile.md.DZR2k06g.js",
"/ran/assets/src_article_sort_index.md.DuxpILCa.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.DxFYu58I.lean.js",
"/ran/assets/cn_src_types_类型运算.md.D8a7fZMz.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.D4O9xJZk.js",
"/ran/assets/cn_src_article_functionalProgramming.md.DX_9Zru3.lean.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_article_sort_index.md.ByZMwD9N.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_ranui_tabs_index.md.Ba0traun.lean.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BJOmcPtq.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CydeNHU_.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bz1LFT7n.js",
"/ran/assets/cn_src_article_sort_select_index.md.DoBvRJ9o.js",
"/ran/assets/src_article_imagemin.md.CZl194w7.js",
"/ran/assets/src_ranuts_utils_task.md.dTe1-lmC.js",
"/ran/assets/src_ranui_button_index.md.C2wjRzU7.js",
"/ran/assets/cn_src_article_sort_merge_index.md.Cq19YPyw.js",
"/ran/assets/cn_src_ranui_input_index.md.D7f9ZDQa.js",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/index.md.URc4pCpn.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/src_article_sort_bucket_index.md.Cn57DRYb.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BYCW1dw2.lean.js",
"/ran/assets/src_ranui_modal_index.md.BeSUIONk.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.CXFVMnad.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.Ck_ZxXDa.js",
"/ran/assets/chunks/index-Bc2Bcl8D.Za2ZFfJZ.js",
"/ran/assets/chunks/pwa-install.es.Boqgbkxy.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/framework.Bda4bexJ.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/theme.CENgqdAQ.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/katex-es-B5r5vt3m.BDSjlQ-m.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/jszip.min-Dhs3nUkD.BsDI-Ugu.js",
"/ran/assets/chunks/index-CGEx9VOA.CbzSCoNs.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/index.DJu_DrSV.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/docx-CHkPTdGU.BUghc3NZ.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BMxl7YaZ.js",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C59U_8pp.js",
"/ran/assets/src_article_designMode.md.-rqdTRku.js",
"/ran/assets/src_ranuts_utils_getCookie.md.emODLqae.lean.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C0xhpVUJ.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.DB5QaWXN.js",
"/ran/assets/src_ranuts_utils_formatJson.md.CydeNHU_.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/src_article_typescript_unionType.md.BaubE5cJ.js",
"/ran/assets/src_article_typescript_calculate.md.Dt-ii_pB.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.DTuNAMLK.lean.js",
"/ran/assets/cn_src_article_babel.md.-0Z-WXWi.js",
"/ran/assets/src_types_高级类型.md.DYGDHYRc.lean.js",
"/ran/assets/src_article_sort_heap_index.md.DGw_UQjk.lean.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BzUHPvgc.js",
"/ran/assets/cn_src_article_sort_radix_index.md.Bz1LFT7n.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.Duq1VFMb.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_article_sort_quick_index.md.oIExHjQF.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.K4weakjl.lean.js",
"/ran/assets/cn_src_types_高级类型.md.CxiMAktq.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/src_article_functionalProgramming.md.DdMMvksq.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/cn_src_article_video.md.C1V0oXFo.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/src_ranuts_mode_subscribe.md.DNRjesa8.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/src_article_sort_merge_index.md.S2Bu_221.lean.js",
"/ran/assets/style.wXoydAGw.css",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.C0xhpVUJ.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DJYH_Enr.lean.js",
"/ran/assets/src_article_sort_count_index.md.BcOt4UQw.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.RgxquexD.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.C_Ml7y1-.js",
"/ran/assets/src_ranui_preview_index.md.C5GLKT3n.lean.js",
"/ran/assets/src_ranui_popover_index.md.KCjt9rL2.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.DV_oawzp.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/cn_index.md.BJgy4QAH.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/src_ranui_message_index.md.D9PEJiMQ.lean.js",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/src_ranuts_utils_filterObj.md.tInzAuO8.js",
"/ran/assets/cn_src_ranui_modal_index.md.CBz8KOGh.js",
"/ran/assets/cn_src_ranui_math_index.md.Co_4aXAT.js",
"/ran/assets/src_ranuts_index.md.B1lZzKMg.js",
"/ran/assets/src_types_模式匹配.md.CV1FOM33.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_designMode.md.-rqdTRku.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.enaSlCiH.lean.js",
"/ran/assets/src_ranui_loading_index.md.Pk_nv3Wx.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BMxl7YaZ.lean.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.D4AFcDFM.lean.js",
"/ran/assets/src_ranui_index.md.BUndUWDa.js",
"/ran/assets/src_article_sort_shell_index.md.cD0jKscc.js",
"/ran/assets/src_ranuts_bundler_index.md.DYhqfdR8.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.C_YEm9yx.js",
"/ran/assets/cn_src_article_sort_count_index.md.D74R3EkJ.lean.js",
"/ran/assets/src_ranuts_utils_task.md.dTe1-lmC.lean.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.C59U_8pp.lean.js",
"/ran/assets/src_ranui_progress_index.md.CElwZnPe.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_typescript_index.md.D9agpp78.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_ranui_button_index.md.Bo8Eunb8.lean.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Bbrqi6Ef.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/cn_src_ranui_index.md.Bmu77gUE.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CdxzSWe0.js",
"/ran/assets/src_ranuts_file_readFile.md.DZR2k06g.lean.js",
"/ran/assets/src_article_sort_count_index.md.BcOt4UQw.lean.js",
"/ran/assets/src_types_类型运算.md.Br0evDRf.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.DxFYu58I.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CdxzSWe0.lean.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/src_article_typescript_index.md.CjUGm1E0.lean.js",
"/ran/assets/src_types_TS类型.md.Cq5vyMdv.lean.js",
"/ran/assets/src_ranuts_file_watchFile.md.Cz89iwUK.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_article_sort_shell_index.md.BEmndUsQ.js",
"/ran/assets/src_types_高级类型.md.DYGDHYRc.js",
"/ran/assets/cn_src_ranui_modal_index.md.CBz8KOGh.lean.js",
"/ran/assets/src_article_typescript_pattern.md.BgaIl4gx.lean.js",
"/ran/assets/src_ranuts_file_appendFile.md.C_Ml7y1-.lean.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_ranui_radar_index.md.NyO_QDCT.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.BYCW1dw2.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.BzUHPvgc.lean.js",
"/ran/assets/src_article_typescript_recursion.md.CYzYq_b1.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_index.md.C6CiQJiD.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.D2OL5wNT.js",
"/ran/assets/cn_src_article_babel.md.-0Z-WXWi.lean.js",
"/ran/assets/src_ranui_preview_index.md.C5GLKT3n.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/cn_src_ranui_player_index.md.bX2Y8w5E.lean.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/icon.png",
"/ran/ocr/eng.png",
"/ran/ocr/chi_sim.png",
"/ran/pagefind/pagefind.en_d247f913c6.pf_meta",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1bea5ca.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20acdfe.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6ea04b2.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/en_d01c729.pf_fragment",
"/ran/pagefind/fragment/en_447484b.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_11911b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_332b751.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b6ea2e8.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dae632.pf_fragment",
"/ran/pagefind/fragment/en_7738ff7.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_42963a4.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4e4f462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_1795edd.pf_fragment",
"/ran/pagefind/fragment/en_9d386dc.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/zh-cn_fd3e42d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e766c87.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d9728cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3c14389.pf_fragment",
"/ran/pagefind/fragment/zh-cn_656a0e3.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_366c379.pf_fragment",
"/ran/pagefind/fragment/zh-cn_592ddc8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3d94e9d.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e3e8d1b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f983bac.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7c1b50b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2af2d9c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_652a379.pf_fragment",
"/ran/pagefind/fragment/en_173a22b.pf_fragment",
"/ran/pagefind/fragment/en_67164e3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9f70d46.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8294a4e.pf_fragment",
"/ran/pagefind/fragment/en_9c45c89.pf_fragment",
"/ran/pagefind/fragment/en_94cd0a8.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ff2cca3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e385a7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_48435ad.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ddfae39.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_939c493.pf_fragment",
"/ran/pagefind/fragment/zh-cn_993b46b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_734282c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_255c544.pf_fragment",
"/ran/pagefind/fragment/en_fef81bf.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_65bc9fe.pf_fragment",
"/ran/pagefind/fragment/en_d6fd44d.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_8adcb28.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8e7c3a8.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a6f04b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8cf4d26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_65d3893.pf_fragment",
"/ran/pagefind/fragment/en_ac6abbe.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4277cd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_30665f7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_6791f1c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d219c18.pf_fragment",
"/ran/pagefind/fragment/zh-cn_97a46e6.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cbf0f26.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e176acb.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9dfa903.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ab1d4dc.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e360895.pf_fragment",
"/ran/pagefind/fragment/zh-cn_62e4d07.pf_fragment",
"/ran/pagefind/fragment/zh-cn_92f9f77.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4c180fb.pf_fragment",
"/ran/pagefind/fragment/zh-cn_142eff8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_eb8b47c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d86a2d3.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cad67b8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_63e4374.pf_fragment",
"/ran/pagefind/fragment/zh-cn_549f216.pf_fragment",
"/ran/pagefind/fragment/en_c2b6cbd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a247d1d.pf_fragment",
"/ran/pagefind/fragment/en_628da55.pf_fragment",
"/ran/pagefind/fragment/en_baf552f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_2f08da6.pf_fragment",
"/ran/pagefind/fragment/en_34522ba.pf_fragment",
"/ran/pagefind/fragment/zh-cn_daef69b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_171a750.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4a2aae7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_18e65ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5056dc5.pf_fragment",
"/ran/pagefind/fragment/zh-cn_9c8fd1c.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c9a69c4.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3775faf.pf_fragment",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/index/zh-cn_81e043a.pf_index",
"/ran/pagefind/index/en_56c79d6.pf_index",
"/ran/pagefind/index/en_c0c314f.pf_index",
"/ran/pagefind/index/zh-cn_4e3971e.pf_index",
"/ran/pagefind/index/zh-cn_5712ee9.pf_index",
"/ran/pagefind/index/en_89c1c30.pf_index",
"/ran/pagefind/index/zh-cn_e64b422.pf_index",
"/ran/pagefind/index/zh-cn_83771c4.pf_index",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind.zh-cn_d391524363328.pf_meta",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind-entry.json",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/icon_96.png",
"/ran/index.html",
"/ran/screenshots_2560x1440.jpg",
"/ran/home.svg",
"/ran/sw1722671330.js",
"/ran/favicon.ico",
"/ran/icon_144.png",
"/ran/icon_72.png",
"/ran/screenshots_748x1340.jpg",
"/ran/404.html",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/类型运算.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/bundle.html",
"/ran/src/article/babel.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/designMode.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/hashmap.json",
];
const VERSION = "1722671330";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



