const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/TS类型.html",
"/ran/src/article/javascript/domLoad.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/unionType.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/babel.html",
"/ran/src/article/designMode.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/bundle.html",
"/ran/src/article/functionalProgramming.html",
"/ran/src/article/astParse/tokenizer.html",
"/ran/src/article/imagemin.html",
"/ran/src/ranuts/utils/filterObj.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/convertImageToBase64.html",
"/ran/src/ranuts/utils/getCookie.html",
"/ran/src/ranuts/utils/formatJson.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mimeType/mimeType.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/binaryTree/index.html",
"/ran/src/ranuts/file/readFile.html",
"/ran/src/ranuts/file/writeFile.html",
"/ran/src/ranuts/file/fileInfo.html",
"/ran/src/ranuts/file/readDir.html",
"/ran/src/ranuts/file/watchFile.html",
"/ran/src/ranuts/file/appendFile.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/icon_72.png",
"/ran/404.html",
"/ran/home.svg",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/cn_src_article_designMode.md.z78YjNtx.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BsITLfMA.js",
"/ran/assets/src_ranuts_file_watchFile.md.CZW4SB-I.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.rxZ2QxLr.lean.js",
"/ran/assets/cn_src_ranui_icon_index.md.CU5ey-Id.js",
"/ran/assets/cn_src_article_babel.md.C0mFpfWk.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_ranui_input_index.md.BL4T793J.js",
"/ran/assets/cn_src_article_sort_heap_index.md.jaqs0S3Q.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Z-t3Vd84.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DuuoT0vI.js",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/src_article_sort_quick_index.md.orYr5tlz.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/cn_src_ranui_skeleton_index.md.BzFQBx5L.js",
"/ran/assets/src_ranuts_mimeType_mimeType.md.B4X0pi8_.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.BaeQvJ6N.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/src_ranuts_file_readDir.md.B3FruKUi.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.C8a4yWeK.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/app.BN0mb3GM.js",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/cn_src_article_sort_count_index.md.DVYKRMnQ.lean.js",
"/ran/assets/src_article_sort_bucket_index.md.Cz2lclNp.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_note_docker.md.DoLaaxyk.js",
"/ran/assets/src_article_imagemin.md.CuGmxVPh.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_ranui_player_index.md.D7a3EuSD.lean.js",
"/ran/assets/cn_src_types_类型运算.md.CSGIuIbN.lean.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CYnOTHs6.js",
"/ran/assets/cn_src_ranui_message_index.md.bzvXoO0h.lean.js",
"/ran/assets/src_ranui_input_index.md.BEXe-Yxr.js",
"/ran/assets/src_article_bundle.md.Bwvc5JPR.lean.js",
"/ran/assets/src_ranui_button_index.md.CVhVgdVU.lean.js",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_types_类型运算.md.DOiBeqTX.lean.js",
"/ran/assets/cn_src_article_sort_quick_index.md.MVzD9mWA.lean.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BXkgG0SF.js",
"/ran/assets/src_article_sort_count_index.md.6m2VN4BB.js",
"/ran/assets/src_article_sort_bubble_index.md.ee8P4HvV.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/cn_src_ranui_radar_index.md.BaO_czYM.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_article_docPreview.md.MsbpaTpr.js",
"/ran/assets/src_article_typescript_calculate.md.q9kptJ2g.lean.js",
"/ran/assets/src_ranui_modal_index.md.C2luKJ2a.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.B2Pd1ptL.js",
"/ran/assets/src_ranui_preview_index.md.A6HGNXuM.js",
"/ran/assets/src_article_astParse_tokenizer.md.qhN4xPrx.js",
"/ran/assets/src_ranui_math_index.md.-N3DLD-8.lean.js",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/src_types_高级类型.md.CCaAh36_.js",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_note_ubuntu.md.CWaXQAge.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.BV9a80U2.lean.js",
"/ran/assets/src_types_高级类型.md.CCaAh36_.lean.js",
"/ran/assets/cn_src_article_systemDesign.md.Cww5IcJX.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C64Ti9aa.lean.js",
"/ran/assets/src_article_sort_index.md.BCIBstxt.js",
"/ran/assets/cn_index.md.DE6eXPbK.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/src_article_sort_merge_index.md.hS66J05l.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BaO_czYM.js",
"/ran/assets/cn_src_article_systemDesign.md.Cww5IcJX.lean.js",
"/ran/assets/src_ranui_loading_index.md.C3j9NROg.lean.js",
"/ran/assets/src_types_模式匹配.md.y6gEjLCP.lean.js",
"/ran/assets/src_article_sort_radix_index.md.B9QLa3nq.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_article_sort_insert_index.md.CzcC8P8D.lean.js",
"/ran/assets/cn_src_article_visual.md.BB7JAXp6.js",
"/ran/assets/cn_src_article_typescript_unionType.md.BEYDzCle.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Dz_gFx1d.js",
"/ran/assets/cn_src_article_sort_index.md.C1L-l4gW.js",
"/ran/assets/src_article_babel.md.DqF8c_0g.lean.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_designMode.md.HT3hF3gt.lean.js",
"/ran/assets/cn_src_article_sort_shell_index.md.D7WNu33w.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B28DvwOL.lean.js",
"/ran/assets/src_ranui_radar_index.md.LIwgVrwO.lean.js",
"/ran/assets/src_ranui_index.md.B9gPGSxb.lean.js",
"/ran/assets/src_article_sort_count_index.md.6m2VN4BB.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.DbVwKL5l.lean.js",
"/ran/assets/cn_index.md.DE6eXPbK.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.D3cFBULM.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CxLjIL4q.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.rxZ2QxLr.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/src_ranuts_file_appendFile.md.D47ZZzJq.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/src_ranui_message_index.md.DYx-2fZN.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.D1-an8C2.lean.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/cn_src_ranuts_file_appendFile.md.8dh6GnGH.js",
"/ran/assets/src_ranui_tab_index.md.ZpjqvUCL.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DDRZmbEF.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_article_functionalProgramming.md.geNFBUIk.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/cn_src_article_imagemin.md.Dvgu-IZc.lean.js",
"/ran/assets/cn_src_types_TS类型.md.DQsKpD9B.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.CWaXQAge.js",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_ranuts_utils_filterObj.md.CJSuST09.js",
"/ran/assets/cn_src_article_bundle.md.Bh_iLlt7.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.D7a3EuSD.js",
"/ran/assets/cn_src_ranui_image_index.md.CfWBYPjT.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/src_article_sort_heap_index.md.obtoQvzM.js",
"/ran/assets/src_ranuts_utils_convertImageToBase64.md.B28DvwOL.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DElVrLQI.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.p16mXVvv.js",
"/ran/assets/cn_src_ranuts_binaryTree_index.md.B2Pd1ptL.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.C9g0MIjZ.js",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_types_模式匹配.md.y6gEjLCP.js",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_ranui_progress_index.md.buvQxs4m.lean.js",
"/ran/assets/src_article_sort_shell_index.md.B2ExKZKt.lean.js",
"/ran/assets/src_ranui_progress_index.md.BEapeVOG.js",
"/ran/assets/cn_src_article_visual.md.BB7JAXp6.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.CfP2pqzz.lean.js",
"/ran/assets/src_ranuts_utils_getCookie.md.CYXKwmbl.js",
"/ran/assets/src_ranui_checkbox_index.md.BUs6fFzR.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.BzFQBx5L.lean.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_article_typescript_index.md.CXGrcIjT.lean.js",
"/ran/assets/src_article_typescript_unionType.md.DbJjUwhe.js",
"/ran/assets/cn_src_article_bundle.md.Bh_iLlt7.js",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/src_ranuts_utils_formatJson.md.COw2QYya.js",
"/ran/assets/src_article_typescript_index.md.D5saSAsn.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/src_article_sort_shell_index.md.B2ExKZKt.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/src_article_sort_insert_index.md.CzcC8P8D.js",
"/ran/assets/cn_src_ranui_progress_index.md.buvQxs4m.js",
"/ran/assets/src_ranui_checkbox_index.md.BUs6fFzR.lean.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BB0a7C0Q.js",
"/ran/assets/src_ranuts_file_appendFile.md.D47ZZzJq.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DCF8LHi-.js",
"/ran/assets/src_ranuts_file_watchFile.md.CZW4SB-I.js",
"/ran/assets/cn_src_types_模式匹配.md.C9g0MIjZ.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CewtD-Un.lean.js",
"/ran/assets/src_article_bundle.md.Bwvc5JPR.js",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/cn_src_article_typescript_calculate.md.BNH_WEhG.lean.js",
"/ran/assets/cn_src_article_javascript_domLoad.md.D1-an8C2.js",
"/ran/assets/cn_src_ranui_input_index.md.BL4T793J.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CUv9JnBK.lean.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/cn_src_ranui_button_index.md.BurzXl__.lean.js",
"/ran/assets/src_ranuts_binaryTree_index.md.DHCX4qKa.js",
"/ran/assets/cn_src_ranuts_file_watchFile.md.BXkgG0SF.lean.js",
"/ran/assets/src_article_sort_heap_index.md.obtoQvzM.lean.js",
"/ran/assets/chunks/index.CafPLwUV.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/framework.eq-HTtE3.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/index-Co9E57uv.DM_Nu_-Q.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/theme.DbZz0xHr.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/commonjs-dynamic-modules-DLbDWi6a.CRNIONdy.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/chunks/katex-es-DoRbtDCO.BDSjlQ-m.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/pwa-install.es.DuMXkPrI.js",
"/ran/assets/chunks/info-circle-fill-CFeVMdci.CUxFtRNn.js",
"/ran/assets/chunks/docx-VUApAnRr.Cl4GUa7G.js",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.CmQSFM5C.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/jszip.min-BIf20mgf.BsDI-Ugu.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.Byf79MII.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/index-Ba501-HG.DLGTjfcz.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/cn_src_ranuts_file_writeFile.md.Dz_gFx1d.lean.js",
"/ran/assets/src_ranui_modal_index.md.C2luKJ2a.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BN96tFmY.lean.js",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.DDRZmbEF.js",
"/ran/assets/src_article_sort_merge_index.md.hS66J05l.js",
"/ran/assets/cn_src_note_docker.md.DoLaaxyk.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/cn_src_article_sort_select_index.md.B42HR89y.lean.js",
"/ran/assets/cn_src_ranuts_utils_formatJson.md.DElVrLQI.lean.js",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_article_typescript_recursion.md.C3r1SVwX.js",
"/ran/assets/src_ranui_message_index.md.DYx-2fZN.js",
"/ran/assets/cn_src_article_babel.md.C0mFpfWk.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DVL1JBos.js",
"/ran/assets/src_ranui_icon_index.md.CVUgd-M5.js",
"/ran/assets/src_ranui_icon_index.md.CVUgd-M5.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.C7nxecf8.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BNH_WEhG.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.D3iIKOoO.js",
"/ran/assets/src_article_designMode.md.HT3hF3gt.js",
"/ran/assets/src_ranui_tab_index.md.ZpjqvUCL.lean.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BsuwEadz.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.bzvXoO0h.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.3UkVLOVl.js",
"/ran/assets/src_ranui_loading_index.md.C3j9NROg.js",
"/ran/assets/cn_src_article_sort_count_index.md.DVYKRMnQ.js",
"/ran/assets/cn_src_ranui_select_index.md.lbBXv97h.lean.js",
"/ran/assets/cn_src_ranui_index.md.D2b8gdmY.lean.js",
"/ran/assets/src_article_javascript_domLoad.md.DBNfi5Xx.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/index.md.MgCTrBZJ.js",
"/ran/assets/src_ranuts_utils_task.md.BwfO_3Ro.lean.js",
"/ran/assets/index.md.MgCTrBZJ.lean.js",
"/ran/assets/src_article_typescript_recursion.md.C3r1SVwX.lean.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.afvlN1Z2.lean.js",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_typescript_unionType.md.BEYDzCle.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/cn_src_article_video.md.6RwC75dY.lean.js",
"/ran/assets/cn_src_article_typescript_reconstruction.md.BsITLfMA.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.rg8PcLzN.js",
"/ran/assets/cn_src_ranuts_index.md.CBlezAo6.js",
"/ran/assets/src_ranui_radar_index.md.LIwgVrwO.js",
"/ran/assets/cn_src_article_sort_merge_index.md.ROj5-wtO.js",
"/ran/assets/cn_src_article_designMode.md.z78YjNtx.js",
"/ran/assets/cn_src_note_centos.md.DS7zpsQ9.js",
"/ran/assets/cn_src_ranuts_bundler_index.md.CYnOTHs6.lean.js",
"/ran/assets/style.D7_Ytddv.css",
"/ran/assets/src_article_imagemin.md.CuGmxVPh.js",
"/ran/assets/cn_src_article_imagemin.md.Dvgu-IZc.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/src_ranuts_mimeType_mimeType.md.B4X0pi8_.js",
"/ran/assets/src_ranuts_utils_task.md.BwfO_3Ro.js",
"/ran/assets/src_article_typescript_index.md.D5saSAsn.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BHgylsLg.js",
"/ran/assets/src_ranui_player_index.md.Degke8MC.lean.js",
"/ran/assets/cn_src_ranuts_file_appendFile.md.8dh6GnGH.lean.js",
"/ran/assets/src_article_typescript_calculate.md.q9kptJ2g.js",
"/ran/assets/src_ranuts_file_writeFile.md.BlEd8z9h.lean.js",
"/ran/assets/cn_src_note_centos.md.DS7zpsQ9.lean.js",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/cn_src_article_sort_merge_index.md.ROj5-wtO.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.C7nxecf8.lean.js",
"/ran/assets/src_ranuts_file_writeFile.md.BlEd8z9h.js",
"/ran/assets/src_article_sort_quick_index.md.orYr5tlz.lean.js",
"/ran/assets/cn_src_types_TS类型.md.DQsKpD9B.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/cn_src_ranui_math_index.md.DkMF1vR5.js",
"/ran/assets/src_article_typescript_reconstruction.md.Dj3IsseX.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DzIrnXCv.js",
"/ran/assets/src_ranui_button_index.md.CVhVgdVU.js",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/src_article_sort_bubble_index.md.ee8P4HvV.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/src_ranui_select_index.md.BV1a0Xjz.lean.js",
"/ran/assets/src_article_typescript_pattern.md.DuBkRKMe.lean.js",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.D5FyATjq.js",
"/ran/assets/src_article_sort_select_index.md.bVI-J-8I.js",
"/ran/assets/cn_src_article_typescript_index.md.CXGrcIjT.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_ranuts_binaryTree_index.md.DHCX4qKa.lean.js",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/src_ranui_progress_index.md.BEapeVOG.lean.js",
"/ran/assets/cn_src_article_sort_select_index.md.B42HR89y.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.DCF8LHi-.lean.js",
"/ran/assets/src_article_sort_radix_index.md.B9QLa3nq.lean.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/src_article_functionalProgramming.md.geNFBUIk.lean.js",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/cn_src_article_sort_shell_index.md.D7WNu33w.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/cn_src_ranuts_file_readFile.md.DQSWUKkh.js",
"/ran/assets/cn_src_article_astParse_tokenizer.md.D3iIKOoO.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.CfWBYPjT.lean.js",
"/ran/assets/cn_src_ranuts_file_fileInfo.md.BHgylsLg.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BxIZFj-v.js",
"/ran/assets/cn_src_ranui_select_index.md.lbBXv97h.js",
"/ran/assets/src_article_sort_bucket_index.md.Cz2lclNp.js",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.V8TGsu50.js",
"/ran/assets/src_ranuts_index.md.Bw9wjXSi.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.e4OmCGCX.js",
"/ran/assets/src_article_sort_index.md.BCIBstxt.lean.js",
"/ran/assets/src_article_babel.md.DqF8c_0g.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/cn_src_ranui_preview_index.md.C8a4yWeK.js",
"/ran/assets/src_ranuts_utils_getCookie.md.CYXKwmbl.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranuts_mimeType_mimeType.md.V8TGsu50.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.p16mXVvv.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.3UkVLOVl.lean.js",
"/ran/assets/cn_src_article_docPreview.md.MsbpaTpr.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.jaqs0S3Q.lean.js",
"/ran/assets/cn_src_ranuts_index.md.CBlezAo6.lean.js",
"/ran/assets/src_ranuts_file_fileInfo.md.CxLjIL4q.lean.js",
"/ran/assets/cn_src_types_高级类型.md.DVL1JBos.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.C64Ti9aa.js",
"/ran/assets/cn_src_ranui_math_index.md.DkMF1vR5.lean.js",
"/ran/assets/src_ranui_player_index.md.Degke8MC.js",
"/ran/assets/cn_src_ranuts_utils_getCookie.md.afvlN1Z2.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BB0a7C0Q.lean.js",
"/ran/assets/src_ranui_popover_index.md.vwjfFH3Z.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.C9dBnmGf.js",
"/ran/assets/src_ranui_tabs_index.md.CewtD-Un.js",
"/ran/assets/cn_src_article_functionalProgramming.md.BsuwEadz.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/src_ranui_image_index.md.wfkokBVc.js",
"/ran/assets/cn_src_ranui_icon_index.md.CU5ey-Id.lean.js",
"/ran/assets/cn_src_types_类型运算.md.CSGIuIbN.js",
"/ran/assets/src_types_TS类型.md.B9jCa8Oe.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D6mxTOeu.lean.js",
"/ran/assets/src_ranui_preview_index.md.A6HGNXuM.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BxIZFj-v.lean.js",
"/ran/assets/src_article_astParse_tokenizer.md.qhN4xPrx.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BurzXl__.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CqkFto9S.js",
"/ran/assets/cn_src_ranuts_utils_convertImageToBase64.md.CqkFto9S.lean.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.D3cFBULM.js",
"/ran/assets/cn_src_ranuts_file_readDir.md.DzIrnXCv.lean.js",
"/ran/assets/src_ranui_image_index.md.wfkokBVc.lean.js",
"/ran/assets/cn_src_ranui_tab_index.md.CUv9JnBK.js",
"/ran/assets/cn_src_ranuts_file_readFile.md.DQSWUKkh.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BJtZrKIP.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.Z-t3Vd84.js",
"/ran/assets/src_types_类型运算.md.DOiBeqTX.js",
"/ran/assets/src_ranuts_bundler_index.md.e4OmCGCX.lean.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/src_article_typescript_unionType.md.DbJjUwhe.lean.js",
"/ran/assets/src_ranuts_file_readFile.md.CfP2pqzz.js",
"/ran/assets/src_ranui_index.md.B9gPGSxb.js",
"/ran/assets/src_types_TS类型.md.B9jCa8Oe.lean.js",
"/ran/assets/src_article_sort_select_index.md.bVI-J-8I.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.DbVwKL5l.js",
"/ran/assets/src_ranuts_utils_filterObj.md.CJSuST09.lean.js",
"/ran/assets/src_ranui_math_index.md.-N3DLD-8.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/src_ranuts_file_readDir.md.B3FruKUi.js",
"/ran/assets/src_ranuts_index.md.Bw9wjXSi.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/cn_src_ranui_loading_index.md.BaeQvJ6N.js",
"/ran/assets/src_article_javascript_domLoad.md.DBNfi5Xx.lean.js",
"/ran/assets/src_ranui_select_index.md.BV1a0Xjz.js",
"/ran/assets/src_ranuts_utils_ocr.md.BV9a80U2.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/cn_src_article_sort_quick_index.md.MVzD9mWA.js",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/src_ranui_input_index.md.BEXe-Yxr.lean.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.BN96tFmY.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/cn_src_article_video.md.6RwC75dY.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/src_article_typescript_pattern.md.DuBkRKMe.js",
"/ran/assets/cn_src_article_typescript_pattern.md.rg8PcLzN.lean.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/cn_src_ranuts_utils_filterObj.md.D5FyATjq.lean.js",
"/ran/assets/src_ranuts_utils_formatJson.md.COw2QYya.lean.js",
"/ran/assets/cn_src_ranuts_utils_task.md.D6mxTOeu.js",
"/ran/assets/cn_src_article_sort_index.md.C1L-l4gW.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.DuuoT0vI.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.BJtZrKIP.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/cn_src_article_typescript_recursion.md.C9dBnmGf.lean.js",
"/ran/assets/cn_src_ranui_index.md.D2b8gdmY.js",
"/ran/assets/src_ranui_popover_index.md.vwjfFH3Z.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/src_article_typescript_reconstruction.md.Dj3IsseX.lean.js",
"/ran/sw1728125010.js",
"/ran/icon_48.png",
"/ran/icon_144.png",
"/ran/pagefind/pagefind-entry.json",
"/ran/pagefind/pagefind-modular-ui.js",
"/ran/pagefind/pagefind-ui.js",
"/ran/pagefind/pagefind-modular-ui.css",
"/ran/pagefind/wasm.unknown.pagefind",
"/ran/pagefind/pagefind.js",
"/ran/pagefind/pagefind.zh-cn_e4218cef68405.pf_meta",
"/ran/pagefind/pagefind-ui.css",
"/ran/pagefind/pagefind.en_1ca6756a02.pf_meta",
"/ran/pagefind/index/zh-cn_9bacfc2.pf_index",
"/ran/pagefind/index/en_bc39585.pf_index",
"/ran/pagefind/index/zh-cn_8d4814d.pf_index",
"/ran/pagefind/index/en_e8e8597.pf_index",
"/ran/pagefind/index/en_d22f299.pf_index",
"/ran/pagefind/index/zh-cn_64ecbb3.pf_index",
"/ran/pagefind/index/zh-cn_933a426.pf_index",
"/ran/pagefind/index/zh-cn_88a2748.pf_index",
"/ran/pagefind/wasm.en.pagefind",
"/ran/pagefind/pagefind-highlight.js",
"/ran/pagefind/fragment/zh-cn_e1f4a79.pf_fragment",
"/ran/pagefind/fragment/en_a116508.pf_fragment",
"/ran/pagefind/fragment/en_1f67d37.pf_fragment",
"/ran/pagefind/fragment/zh-cn_95fa787.pf_fragment",
"/ran/pagefind/fragment/zh-cn_66f42e8.pf_fragment",
"/ran/pagefind/fragment/en_3bf4f84.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f9c4333.pf_fragment",
"/ran/pagefind/fragment/zh-cn_489c27d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4152685.pf_fragment",
"/ran/pagefind/fragment/zh-cn_20f66b3.pf_fragment",
"/ran/pagefind/fragment/en_349bd7e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c1151c9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d4d42a.pf_fragment",
"/ran/pagefind/fragment/en_4bc9db8.pf_fragment",
"/ran/pagefind/fragment/en_9755f3c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e64f93e.pf_fragment",
"/ran/pagefind/fragment/en_c8893d7.pf_fragment",
"/ran/pagefind/fragment/en_7b5a911.pf_fragment",
"/ran/pagefind/fragment/en_7a4eb73.pf_fragment",
"/ran/pagefind/fragment/zh-cn_7d7b75a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a2ee62c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ad41a4b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5a83ae9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5d1b782.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f09c929.pf_fragment",
"/ran/pagefind/fragment/en_2771bf1.pf_fragment",
"/ran/pagefind/fragment/en_c3245b6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c82f3b2.pf_fragment",
"/ran/pagefind/fragment/en_27ced55.pf_fragment",
"/ran/pagefind/fragment/en_345875a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_50313a9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_75a264c.pf_fragment",
"/ran/pagefind/fragment/en_6414c8f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bab657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_67d6c7a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a57d6ee.pf_fragment",
"/ran/pagefind/fragment/zh-cn_544fd92.pf_fragment",
"/ran/pagefind/fragment/en_c2a5686.pf_fragment",
"/ran/pagefind/fragment/en_43e1883.pf_fragment",
"/ran/pagefind/fragment/en_e34b39a.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d98338a.pf_fragment",
"/ran/pagefind/fragment/en_fba3fcb.pf_fragment",
"/ran/pagefind/fragment/en_7755d1b.pf_fragment",
"/ran/pagefind/fragment/en_229996f.pf_fragment",
"/ran/pagefind/fragment/en_65ccfe9.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e88bc3f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3de2e5c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4a5919.pf_fragment",
"/ran/pagefind/fragment/en_738928a.pf_fragment",
"/ran/pagefind/fragment/en_4126fd6.pf_fragment",
"/ran/pagefind/fragment/en_12451bd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_921768f.pf_fragment",
"/ran/pagefind/fragment/en_a034a97.pf_fragment",
"/ran/pagefind/fragment/en_78b0843.pf_fragment",
"/ran/pagefind/fragment/en_9ee4c46.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5f4f874.pf_fragment",
"/ran/pagefind/fragment/en_b7a3e23.pf_fragment",
"/ran/pagefind/fragment/en_f5a1553.pf_fragment",
"/ran/pagefind/fragment/en_3af9583.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ac92f78.pf_fragment",
"/ran/pagefind/fragment/en_dc61586.pf_fragment",
"/ran/pagefind/fragment/en_b1c2dff.pf_fragment",
"/ran/pagefind/fragment/en_91e701d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5bb9206.pf_fragment",
"/ran/pagefind/fragment/en_39ca4e7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f379427.pf_fragment",
"/ran/pagefind/fragment/zh-cn_512ca2c.pf_fragment",
"/ran/pagefind/fragment/en_bc653ea.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5df12ef.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c2e89f3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_87d72ec.pf_fragment",
"/ran/pagefind/fragment/zh-cn_ce1d5fd.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e347438.pf_fragment",
"/ran/pagefind/fragment/zh-cn_542bc65.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3e43b1f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_44fa7df.pf_fragment",
"/ran/pagefind/fragment/en_a3a3739.pf_fragment",
"/ran/pagefind/fragment/en_422fcc1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4856140.pf_fragment",
"/ran/pagefind/fragment/zh-cn_cfbcb39.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c4f682e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ba45b7.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f4e426e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5ca356d.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a7edffe.pf_fragment",
"/ran/pagefind/fragment/en_6a66788.pf_fragment",
"/ran/pagefind/fragment/zh-cn_58279de.pf_fragment",
"/ran/pagefind/fragment/zh-cn_61c329a.pf_fragment",
"/ran/pagefind/fragment/en_cf8161e.pf_fragment",
"/ran/pagefind/fragment/en_1d9d6e5.pf_fragment",
"/ran/pagefind/fragment/en_3f75462.pf_fragment",
"/ran/pagefind/fragment/en_1fd6515.pf_fragment",
"/ran/pagefind/fragment/zh-cn_f7dcce8.pf_fragment",
"/ran/pagefind/fragment/en_106ee7d.pf_fragment",
"/ran/pagefind/fragment/en_7322c43.pf_fragment",
"/ran/pagefind/fragment/en_b2b1326.pf_fragment",
"/ran/pagefind/fragment/en_19ba7e6.pf_fragment",
"/ran/pagefind/fragment/zh-cn_59bdbd3.pf_fragment",
"/ran/pagefind/fragment/en_e8f3a9e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d32fcee.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5b28b42.pf_fragment",
"/ran/pagefind/fragment/zh-cn_c551e89.pf_fragment",
"/ran/pagefind/fragment/en_b46590e.pf_fragment",
"/ran/pagefind/fragment/zh-cn_b7b2564.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5190b59.pf_fragment",
"/ran/pagefind/fragment/en_e2846bf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3fb29d3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_e6b1657.pf_fragment",
"/ran/pagefind/fragment/zh-cn_15c35e9.pf_fragment",
"/ran/pagefind/fragment/en_fc842d8.pf_fragment",
"/ran/pagefind/fragment/en_919ab78.pf_fragment",
"/ran/pagefind/fragment/zh-cn_715eacf.pf_fragment",
"/ran/pagefind/fragment/en_b5a7787.pf_fragment",
"/ran/pagefind/fragment/en_27a0b4a.pf_fragment",
"/ran/pagefind/fragment/en_222d98b.pf_fragment",
"/ran/pagefind/fragment/zh-cn_51dafe6.pf_fragment",
"/ran/pagefind/fragment/en_55a7cf9.pf_fragment",
"/ran/pagefind/fragment/en_13157a1.pf_fragment",
"/ran/pagefind/fragment/zh-cn_32113cf.pf_fragment",
"/ran/pagefind/fragment/zh-cn_308bdca.pf_fragment",
"/ran/pagefind/fragment/zh-cn_5042f4c.pf_fragment",
"/ran/pagefind/fragment/en_41329e8.pf_fragment",
"/ran/pagefind/fragment/zh-cn_677ff04.pf_fragment",
"/ran/pagefind/fragment/en_dd6246f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_4ceb97f.pf_fragment",
"/ran/pagefind/fragment/en_1bf5586.pf_fragment",
"/ran/pagefind/fragment/zh-cn_8a3cd5f.pf_fragment",
"/ran/pagefind/fragment/zh-cn_a1e1243.pf_fragment",
"/ran/pagefind/fragment/en_2f66cb4.pf_fragment",
"/ran/pagefind/fragment/en_346b990.pf_fragment",
"/ran/pagefind/fragment/en_b5741b3.pf_fragment",
"/ran/pagefind/fragment/zh-cn_d63ee7f.pf_fragment",
"/ran/pagefind/fragment/en_5ff5133.pf_fragment",
"/ran/pagefind/fragment/zh-cn_0ef213d.pf_fragment",
"/ran/pagefind/fragment/en_fa9896c.pf_fragment",
"/ran/pagefind/fragment/zh-cn_3ad6344.pf_fragment",
"/ran/icon_96.png",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/icon_168.png",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/article/javascript/domLoad.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/unionType.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/designMode.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/systemDesign.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/docPreview.html",
"/ran/cn/src/article/functionalProgramming.html",
"/ran/cn/src/article/astParse/tokenizer.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/ranuts/utils/filterObj.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/convertImageToBase64.html",
"/ran/cn/src/ranuts/utils/getCookie.html",
"/ran/cn/src/ranuts/utils/formatJson.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mimeType/mimeType.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/binaryTree/index.html",
"/ran/cn/src/ranuts/file/readFile.html",
"/ran/cn/src/ranuts/file/writeFile.html",
"/ran/cn/src/ranuts/file/fileInfo.html",
"/ran/cn/src/ranuts/file/readDir.html",
"/ran/cn/src/ranuts/file/watchFile.html",
"/ran/cn/src/ranuts/file/appendFile.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/modal/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/index.html",
"/ran/index.html",
"/ran/favicon.ico",
"/ran/hls/example.m3u8",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/icon.png",
"/ran/manifest.json",
"/ran/icon_192.png",
];
const VERSION = "1728125010";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



