const SERVICE_WORK_CACHE_FILE_PATHS = [
"/ran/icon.png",
"/ran/index.html",
"/ran/icon_144.png",
"/ran/assets/原型.DYbH0CSA.jpg",
"/ran/assets/src_types_类型运算.md.DmyK782L.js",
"/ran/assets/cn_src_article_typescript_union_type.md.CS12QWmw.lean.js",
"/ran/assets/Declaration.CplvpFd-.jpeg",
"/ran/assets/src_article_sort_count_index.md.BdMhZyw7.js",
"/ran/assets/tiktok_video.DuwKyIdt.webp",
"/ran/assets/cn_src_ranuts_bundler_index.md.DNQ8Wwtz.js",
"/ran/assets/cn_src_article_sort_shell_index.md.CB_R9CPk.js",
"/ran/assets/cn_src_ranui_tab_index.md.1qqDbUxG.lean.js",
"/ran/assets/桥接.DX0mO5JC.png",
"/ran/assets/Literal.Dl-JxujV.jpeg",
"/ran/assets/cn_src_types_高级类型.md.CNsPW640.lean.js",
"/ran/assets/File.BiH2GpuW.jpeg",
"/ran/assets/ow365.CXWyYekS.webp",
"/ran/assets/src_ranuts_bundler_index.md.COc5w2Up.lean.js",
"/ran/assets/cn_src_article_typescript_recursion.md.D2kPAmZk.js",
"/ran/assets/bundle.bky0NmdF.png",
"/ran/assets/src_ranuts_file_watch_file.md.hbtE0Iju.lean.js",
"/ran/assets/select.B8GwndZy.gif",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.r5VIA6OC.lean.js",
"/ran/assets/cn_src_article_design_mode.md.CCRbTJPz.js",
"/ran/assets/cn_src_ranui_math_index.md.DLlNLZRm.js",
"/ran/assets/src_article_bundle.md.CSg8HUKB.js",
"/ran/assets/src_article_typescript_index.md.7CsfvTPF.js",
"/ran/assets/kkfile_des.CENUMtpY.webp",
"/ran/assets/cn_src_ranui_button_index.md.BUdAEoWl.js",
"/ran/assets/src_ranui_preview_index.md.qMe0JDHZ.lean.js",
"/ran/assets/src_article_typescript_reconstruction.md.D06ogTuC.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.CjV3PxER.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.Cf6dEkfl.lean.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.D8WeHyU9.lean.js",
"/ran/assets/ms_answer.Cgv6ylFF.webp",
"/ran/assets/cn_src_ranui_tabs_index.md.BujElwZ8.js",
"/ran/assets/src_article_imagemin.md.DpHZFC_i.js",
"/ran/assets/cn_src_note_ubuntu.md.BKn7ScZq.lean.js",
"/ran/assets/cn_src_ranui_message_index.md.RbdCty2n.lean.js",
"/ran/assets/ms_support.CaZSSiRt.webp",
"/ran/assets/cn_src_article_system_design.md.BCmsGf9n.js",
"/ran/assets/insert.gf3GhDvq.gif",
"/ran/assets/src_article_typescript_recursion.md.DsOkQ9z_.js",
"/ran/assets/wps_office.DiET-U8x.webp",
"/ran/assets/xml.NyzOyhr4.webp",
"/ran/assets/src_article_sort_insert_index.md.D6-3VwZV.lean.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.D6i0YDT5.lean.js",
"/ran/assets/src_ranuts_mode_subscribe.md.Cpdzg0XJ.lean.js",
"/ran/assets/inter-roman-vietnamese.BjW4sHH5.woff2",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BRLYv1tS.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9sv1qZw.js",
"/ran/assets/cn_src_ranui_select_index.md.CC3N3pHf.js",
"/ran/assets/cn_src_article_video.md.fIIlnqT_.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CBJ_uso6.js",
"/ran/assets/src_ranuts_utils_task.md.WWHcEnXW.js",
"/ran/assets/inter-italic-vietnamese.BSbpV94h.woff2",
"/ran/assets/src_ranuts_file_watch_file.md.hbtE0Iju.js",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DLcUfH1e.js",
"/ran/assets/src_article_sort_bubble_index.md.CTFt5QxH.lean.js",
"/ran/assets/src_ranui_icon_index.md.CXgRPzgJ.js",
"/ran/assets/src_ranuts_file_file_info.md.DoLtTvNK.lean.js",
"/ran/assets/cn_src_ranui_popover_index.md.BLOOUchp.lean.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CRqXu_Se.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BXsen3Di.lean.js",
"/ran/assets/cn_src_ranui_radar_index.md.BEjpxARy.lean.js",
"/ran/assets/cn_src_article_typescript_index.md.CBJ_uso6.lean.js",
"/ran/assets/src_article_typescript_recursion.md.DsOkQ9z_.lean.js",
"/ran/assets/cn_src_note_ubuntu.md.BKn7ScZq.js",
"/ran/assets/red_book.DiBEvryP.webp",
"/ran/assets/ts_demo.D_l_mv9k.webp",
"/ran/assets/src_article_typescript_calculate.md.Bmso-WTu.js",
"/ran/assets/cn_src_types_类型运算.md.DTnV4x92.js",
"/ran/assets/src_ranui_input_index.md.BRsN7qcT.js",
"/ran/assets/src_ranui_checkbox_index.md.CtrntZhH.lean.js",
"/ran/assets/cn_src_article_bundle.md.Co6q4l2G.js",
"/ran/assets/cn_src_article_sort_count_index.md.iYmt-nll.lean.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DEZncuP1.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BXdOlOBP.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Ds4P8fNk.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B8sZviye.js",
"/ran/assets/src_article_sort_select_index.md.C1t2d11H.lean.js",
"/ran/assets/Identifier.lJSxyFTe.jpeg",
"/ran/assets/src_ranuts_index.md.DYqOeqAF.lean.js",
"/ran/assets/src_article_javascript_dom_load.md.BIkTJG4P.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B_SiPmXw.js",
"/ran/assets/style.CVPVLIRO.css",
"/ran/assets/cn_src_article_sort_shell_index.md.CB_R9CPk.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BnAbCeif.js",
"/ran/assets/src_ranui_player_index.md.BYoxyUDK.lean.js",
"/ran/assets/src_article_typescript_union_type.md.BSB_cwUR.lean.js",
"/ran/assets/src_article_bundle.md.CSg8HUKB.lean.js",
"/ran/assets/cn_src_ranui_select_index.md.CC3N3pHf.lean.js",
"/ran/assets/src_ranui_progress_index.md.CGbCQhzE.lean.js",
"/ran/assets/src_article_typescript_union_type.md.BSB_cwUR.js",
"/ran/assets/cn_src_types_TS类型.md.CuGMBV1-.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Db5rD-Yt.lean.js",
"/ran/assets/src_article_babel.md.C3YbZgPe.js",
"/ran/assets/解释器.DymUKGTa.jpg",
"/ran/assets/src_ranuts_utils_filter_obj.md.BHe9-nvs.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.WenunBHN.js",
"/ran/assets/kkfile.X1tAqvNa.webp",
"/ran/assets/状态.Bt_a2OKX.png",
"/ran/assets/cn_src_article_sort_heap_index.md.BG-orbZV.lean.js",
"/ran/assets/cn_src_ranui_preview_index.md.ANM2YYca.js",
"/ran/assets/cn_src_note_centos.md.30sDv6dM.js",
"/ran/assets/src_ranui_skeleton_index.md.ClHOoJeM.js",
"/ran/assets/cn_src_article_imagemin.md.CfXxDbX_.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DMx4Pi0M.lean.js",
"/ran/assets/src_ranuts_file_append_file.md.DMx4Pi0M.js",
"/ran/assets/src_article_sort_merge_index.md.VEKh572q.lean.js",
"/ran/assets/src_ranui_message_index.md.DuVCscnP.lean.js",
"/ran/assets/kkfile_doc.CPfEUxoD.webp",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DON38605.js",
"/ran/assets/cn_src_ranuts_binary_tree_index.md.BXdOlOBP.js",
"/ran/assets/google_doc_view.BknjnOKw.webp",
"/ran/assets/bilibili_video_m4s.BccuY7bk.webp",
"/ran/assets/cn_src_ranui_image_index.md.CiILNDeP.js",
"/ran/assets/src_ranui_preview_index.md.qMe0JDHZ.js",
"/ran/assets/cn_src_article_visual.md.C4e7nvJJ.js",
"/ran/assets/src_article_sort_shell_index.md.B9MVSXAo.lean.js",
"/ran/assets/cn_src_ranui_progress_index.md.D9sv1qZw.lean.js",
"/ran/assets/cn_src_article_sort_radix_index.md.BnAbCeif.lean.js",
"/ran/assets/cn_index.md.RZ4fI9Xw.lean.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BKoQHYLN.lean.js",
"/ran/assets/cn_src_note_libreoffice2wasm.md.WenunBHN.lean.js",
"/ran/assets/src_ranui_message_index.md.DuVCscnP.js",
"/ran/assets/src_article_design_mode.md.Dk-0IM0F.js",
"/ran/assets/src_article_sort_heap_index.md.BIwZAjvO.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ckn8gcjq.js",
"/ran/assets/ms_excel.CJXFi2bf.webp",
"/ran/assets/src_ranui_radar_index.md.C969AfM2.lean.js",
"/ran/assets/cn_src_ranui_index.md.CRdVao-7.lean.js",
"/ran/assets/适配器.C2VH4lXy.png",
"/ran/assets/src_ranui_icon_index.md.CXgRPzgJ.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.BcQOph7G.lean.js",
"/ran/assets/src_article_typescript_pattern.md.C4yxydd_.lean.js",
"/ran/assets/complexity.DSLVsjHt.png",
"/ran/assets/src_ranui_select_index.md.CWxhn6mW.lean.js",
"/ran/assets/cn_src_types_高级类型.md.CNsPW640.js",
"/ran/assets/inter-roman-cyrillic-ext.BBPuwvHQ.woff2",
"/ran/assets/inter-roman-greek-ext.CqjqNYQ-.woff2",
"/ran/assets/享元.EIifVVTy.png",
"/ran/assets/src_ranuts_utils_format_json.md.BKX27c7W.lean.js",
"/ran/assets/balanceTree.DP_9yIkO.png",
"/ran/assets/src_article_javascript_dom_load.md.BIkTJG4P.lean.js",
"/ran/assets/cn_src_article_doc_preview.md.7_svtsxU.js",
"/ran/assets/cn_src_ranui_modal_index.md.H-d8vJpP.lean.js",
"/ran/assets/src_ranui_skeleton_index.md.ClHOoJeM.lean.js",
"/ran/assets/src_article_imagemin.md.DpHZFC_i.lean.js",
"/ran/assets/cn_src_types_模式匹配.md.B72gQc_P.js",
"/ran/assets/ms_word.3k-0mjp0.webp",
"/ran/assets/cn_src_ranuts_file_write_file.md.CNBud208.lean.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.RpAWJHBJ.js",
"/ran/assets/src_ranui_button_index.md.DhDo98IB.lean.js",
"/ran/assets/src_ranui_button_index.md.DhDo98IB.js",
"/ran/assets/src_ranuts_mime_type_mime_type.md.BRLYv1tS.js",
"/ran/assets/Comment.BYtNY-L1.jpeg",
"/ran/assets/src_article_sort_radix_index.md.BwlZtksv.lean.js",
"/ran/assets/bilibili_video_code.DgWtgAEf.webp",
"/ran/assets/quick.DD28bswc.gif",
"/ran/assets/cn_src_article_sort_merge_index.md.CBjmc9Qw.js",
"/ran/assets/cn_src_article_typescript_pattern.md.v51iYz1l.lean.js",
"/ran/assets/cn_src_article_functional_programming.md.BcQOph7G.js",
"/ran/assets/访问者.aEI4m-5a.png",
"/ran/assets/axtexplorer.D7PG-3cx.jpeg",
"/ran/assets/src_article_typescript_reconstruction.md.D06ogTuC.js",
"/ran/assets/src_ranuts_utils_format_json.md.BKX27c7W.js",
"/ran/assets/src_ranui_popover_index.md.BZuCbq7c.js",
"/ran/assets/cn_src_ranuts_utils_filter_obj.md.RpAWJHBJ.lean.js",
"/ran/assets/cn_src_ranui_button_index.md.BUdAEoWl.lean.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.C5y7FauX.lean.js",
"/ran/assets/cn_src_article_babel.md.DgHFpIbJ.js",
"/ran/assets/cn_src_article_sort_quick_index.md.B_SiPmXw.lean.js",
"/ran/assets/heap.D4myjC6C.gif",
"/ran/assets/src_ranui_select_index.md.CWxhn6mW.js",
"/ran/assets/src_article_sort_bubble_index.md.CTFt5QxH.js",
"/ran/assets/cn_src_ranui_player_index.md.BbkStnzG.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BGIWhkVj.lean.js",
"/ran/assets/inter-italic-cyrillic.By2_1cv3.woff2",
"/ran/assets/inter-roman-cyrillic.C5lxZ8CY.woff2",
"/ran/assets/index.md.UmsegAm3.lean.js",
"/ran/assets/src_ranui_input_index.md.BRsN7qcT.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BQbEuaiK.js",
"/ran/assets/cn_src_ranuts_file_watch_file.md.D6i0YDT5.js",
"/ran/assets/cn_src_ranui_skeleton_index.md.C5y7FauX.js",
"/ran/assets/cn_src_article_video.md.fIIlnqT_.js",
"/ran/assets/src_types_高级类型.md.DPVV12Db.lean.js",
"/ran/assets/Class.Cx5QD1OX.jpeg",
"/ran/assets/src_article_babel.md.C3YbZgPe.lean.js",
"/ran/assets/src_article_sort_quick_index.md.DEAVNV7w.lean.js",
"/ran/assets/Expression.DczLaznn.jpeg",
"/ran/assets/cn_src_article_javascript_dom_load.md.CW-AiUge.lean.js",
"/ran/assets/cn_index.md.RZ4fI9Xw.js",
"/ran/assets/src_ranui_image_index.md.BIUVzJWj.js",
"/ran/assets/cn_src_article_sort_bucket_index.md.6J6kmsOe.lean.js",
"/ran/assets/inter-italic-greek-ext.1u6EdAuj.woff2",
"/ran/assets/cn_src_types_类型运算.md.DTnV4x92.lean.js",
"/ran/assets/src_article_sort_heap_index.md.BIwZAjvO.lean.js",
"/ran/assets/ms_ppt.C2zYd_IC.webp",
"/ran/assets/组合.StqZ1pDc.png",
"/ran/assets/src_article_typescript_index.md.7CsfvTPF.lean.js",
"/ran/assets/装饰.CuuWN9YK.jpg",
"/ran/assets/inter-roman-latin.Di8DUHzh.woff2",
"/ran/assets/cn_src_article_typescript_recursion.md.D2kPAmZk.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BOqafci0.lean.js",
"/ran/assets/inter-italic-latin-ext.CN1xVJS-.woff2",
"/ran/assets/src_article_sort_insert_index.md.D6-3VwZV.js",
"/ran/assets/src_ranui_progress_index.md.CGbCQhzE.js",
"/ran/assets/src_ranuts_file_read_file.md.DGbxiWEO.lean.js",
"/ran/assets/xgplayer_docs.CpHb1Wan.webp",
"/ran/assets/index.md.UmsegAm3.js",
"/ran/assets/src_ranui_player_index.md.BYoxyUDK.js",
"/ran/assets/cn_src_article_sort_index.md.LSlOjIWb.js",
"/ran/assets/src_article_typescript_pattern.md.C4yxydd_.js",
"/ran/assets/cn_src_ranui_popover_index.md.BLOOUchp.js",
"/ran/assets/单例.B4dKFqxx.jpg",
"/ran/assets/src_article_functional_programming.md.BZLWEnOd.lean.js",
"/ran/assets/cn_src_article_javascript_dom_load.md.CW-AiUge.js",
"/ran/assets/cn_src_ranuts_utils_ocr.md.DEZncuP1.lean.js",
"/ran/assets/备忘录.meL0YZxn.jpg",
"/ran/assets/app.DXOk6kuN.js",
"/ran/assets/src_types_类型运算.md.DmyK782L.lean.js",
"/ran/assets/cn_src_ranui_loading_index.md.Bh7HC8k4.lean.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.QvyZalpj.lean.js",
"/ran/assets/cn_src_ranui_input_index.md.7533NkBL.lean.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CVFLBQV3.lean.js",
"/ran/assets/cn_src_ranuts_index.md.BOqafci0.js",
"/ran/assets/cn_src_types_模式匹配.md.B72gQc_P.lean.js",
"/ran/assets/src_ranuts_utils_str2xml.md.B8sZviye.lean.js",
"/ran/assets/src_ranui_math_index.md.DYrpI0sU.lean.js",
"/ran/assets/inter-italic-latin.C2AdPX0b.woff2",
"/ran/assets/cn_src_note_docker.md.DSxp9l74.js",
"/ran/assets/src_article_sort_index.md.BA7OVFbZ.lean.js",
"/ran/assets/Statement.9lGuRes5.jpeg",
"/ran/assets/抽象工厂.DlwNEriZ.png",
"/ran/assets/src_article_sort_bucket_index.md.7ZSJCZqo.lean.js",
"/ran/assets/src_ranui_index.md.B6mMJQGk.js",
"/ran/assets/策略.BAijEgGz.png",
"/ran/assets/cn_src_ranui_math_index.md.DLlNLZRm.lean.js",
"/ran/assets/src_article_functional_programming.md.BZLWEnOd.js",
"/ran/assets/src_article_design_mode.md.Dk-0IM0F.lean.js",
"/ran/assets/cn_src_ranui_tabs_index.md.BujElwZ8.lean.js",
"/ran/assets/cn_src_ranui_modal_index.md.H-d8vJpP.js",
"/ran/assets/cn_src_ranuts_file_file_info.md.CRqXu_Se.lean.js",
"/ran/assets/inter-roman-greek.BBVDIX6e.woff2",
"/ran/assets/cn_src_ranuts_utils_str2xml.md.r5VIA6OC.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.qQbKcH-r.lean.js",
"/ran/assets/src_ranui_image_index.md.BIUVzJWj.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CtBth00F.js",
"/ran/assets/cn_src_article_sort_index.md.LSlOjIWb.lean.js",
"/ran/assets/bubble.Csp5B4TH.gif",
"/ran/assets/cn_src_ranui_radar_index.md.BEjpxARy.js",
"/ran/assets/cn_src_ranui_message_index.md.RbdCty2n.js",
"/ran/assets/src_article_sort_bucket_index.md.7ZSJCZqo.js",
"/ran/assets/cn_src_ranui_loading_index.md.Bh7HC8k4.js",
"/ran/assets/cn_src_article_sort_insert_index.md.BXsen3Di.js",
"/ran/assets/bili_demo.CI8Ur8IA.webp",
"/ran/assets/cn_src_article_doc_preview.md.7_svtsxU.lean.js",
"/ran/assets/src_ranuts_bundler_index.md.COc5w2Up.js",
"/ran/assets/cn_src_article_math_linear_algebra.md.qQbKcH-r.js",
"/ran/assets/src_ranui_math_index.md.DYrpI0sU.js",
"/ran/assets/cn_src_ranuts_mode_subscribe.md.BKoQHYLN.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.DsBFRd9M.js",
"/ran/assets/cn_src_ranui_icon_index.md.DfSONHVl.js",
"/ran/assets/src_article_sort_radix_index.md.BwlZtksv.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CSriO4Oi.lean.js",
"/ran/assets/input-input.1X1aE5oH.jpg",
"/ran/assets/cn_src_ranui_preview_index.md.ANM2YYca.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.B7UMypCJ.js",
"/ran/assets/src_article_sort_quick_index.md.DEAVNV7w.js",
"/ran/assets/cn_src_article_imagemin.md.CfXxDbX_.js",
"/ran/assets/src_ranui_modal_index.md.Cl1YF-4V.js",
"/ran/assets/cn_src_article_system_design.md.BCmsGf9n.lean.js",
"/ran/assets/src_ranuts_file_read_file.md.DGbxiWEO.js",
"/ran/assets/import.BTsVI5Tc.jpeg",
"/ran/assets/cn_src_note_docker.md.DSxp9l74.lean.js",
"/ran/assets/cn_src_ranuts_file_read_file.md.Ds4P8fNk.js",
"/ran/assets/src_ranuts_index.md.DYqOeqAF.js",
"/ran/assets/src_ranuts_utils_filter_obj.md.BHe9-nvs.js",
"/ran/assets/cn_src_ranui_checkbox_index.md.QvyZalpj.js",
"/ran/assets/src_article_sort_select_index.md.C1t2d11H.js",
"/ran/assets/cn_src_article_sort_select_index.md.B530W5MY.js",
"/ran/assets/rplayer_demo.CoJ7kuJt.webp",
"/ran/assets/cn_src_ranuts_utils_convert_image_to_base64.md.DLcUfH1e.lean.js",
"/ran/assets/src_ranuts_utils_convert_image_to_base64.md.B7UMypCJ.lean.js",
"/ran/assets/src_ranui_popover_index.md.BZuCbq7c.lean.js",
"/ran/assets/bili_demo_url.BQDGtHUp.webp",
"/ran/assets/shell.CZ-z1IVg.gif",
"/ran/assets/tiktik_video_demo.mxxBzLay.webp",
"/ran/assets/cn_src_article_design_mode.md.CCRbTJPz.lean.js",
"/ran/assets/src_types_高级类型.md.DPVV12Db.js",
"/ran/assets/cn_src_ranui_tab_index.md.1qqDbUxG.js",
"/ran/assets/Program.BBf_t-me.jpeg",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CBAF_xWq.lean.js",
"/ran/assets/src_ranui_radar_index.md.C969AfM2.js",
"/ran/assets/src_article_sort_index.md.BA7OVFbZ.js",
"/ran/assets/firefox_pdf.BWQR-ogn.webp",
"/ran/assets/chunks/preview-CJbz9GjO.C8N16-9H.js",
"/ran/assets/chunks/complexity.CSkvDr7k.js",
"/ran/assets/chunks/loading-Dcc5RApI.D3l74EUI.js",
"/ran/assets/chunks/radix.CHOmrmB0.js",
"/ran/assets/chunks/index-D6nXg_bb.kb2jJ-4C.js",
"/ran/assets/chunks/loading-scene-BMc2wqKm.Di19NrRU.js",
"/ran/assets/chunks/loading.vue_vue_type_style_index_0_lang.aJu9e5fm.js",
"/ran/assets/chunks/jszip.min--o3_SgQz.CiS0z4ab.js",
"/ran/assets/chunks/katex-es-B7keY1LJ.BDSjlQ-m.js",
"/ran/assets/chunks/index.DzUvnNAe.js",
"/ran/assets/chunks/quick.WcLzRUPH.js",
"/ran/assets/chunks/index-CVkJ_Xlh.BFb2SL1a.js",
"/ran/assets/chunks/eye-close-BVr3NJtg.DsdsDDgX.js",
"/ran/assets/chunks/bubble.Dg5jgvyl.js",
"/ran/assets/chunks/user-B-eVXwuk.DyoYYAjs.js",
"/ran/assets/chunks/merge.D_M4N_iU.js",
"/ran/assets/chunks/pdf-Cx0VWKFo.BN8QfUnw.js",
"/ran/assets/chunks/team-tl4NJXPC.D7881a1v.js",
"/ran/assets/chunks/check-circle-fill-B_pd8ZSs.Dxgzakn4.js",
"/ran/assets/chunks/zh-CN.PUkQxDBJ.js",
"/ran/assets/chunks/framework.BOE7hEeL.js",
"/ran/assets/chunks/balanceTree.CCEoBiag.js",
"/ran/assets/chunks/warning-circle-DDUgEDIv.1BX6MOiy.js",
"/ran/assets/chunks/search-BWdfjyP8.CdFUVZ0R.js",
"/ran/assets/chunks/@localSearchIndexcn.B3fPHyFW.js",
"/ran/assets/chunks/@localSearchIndexroot.DrmEkCYs.js",
"/ran/assets/chunks/访问者._0swtoJg.js",
"/ran/assets/chunks/sort-DWqiUONr.C56fs5Gu.js",
"/ran/assets/chunks/heap.xduQWyUN.js",
"/ran/assets/chunks/info-circle-COnL5bTJ.B9YJorcw.js",
"/ran/assets/chunks/docx-D5t6JtVt.BnsCdyQq.js",
"/ran/assets/chunks/customElements.qitHOM3M.js",
"/ran/assets/chunks/en.Bkn4-Vvy.js",
"/ran/assets/chunks/VPLocalSearchBox.5eJs8w9T.js",
"/ran/assets/chunks/setting-DemlgzVC.DkD4YPwp.js",
"/ran/assets/chunks/book-nTEFXU2x.DPEdiL1I.js",
"/ran/assets/chunks/extra.Cu56q3CZ.js",
"/ran/assets/chunks/input-input.MnARRJC6.js",
"/ran/assets/chunks/insert.Bde3uDH4.js",
"/ran/assets/chunks/warning-circle-fill-lODUKz0i.7RyGfSeR.js",
"/ran/assets/chunks/close-CFnkhudp.IMqD2L1-.js",
"/ran/assets/chunks/unlock-CeU74z9n.58atcEuH.js",
"/ran/assets/chunks/bundle.BxrzsuA1.js",
"/ran/assets/chunks/pwa-install.es.Bhs9vARM.js",
"/ran/assets/chunks/select.BGReufCV.js",
"/ran/assets/chunks/shell.CGEkKxrp.js",
"/ran/assets/chunks/home-BUQ4USMk.BqTharGj.js",
"/ran/assets/chunks/sprite-CH2zLtZy.Djo3sTkk.js",
"/ran/assets/chunks/add-user-BN1JlY7e.D6YNNzf8.js",
"/ran/assets/chunks/colz-DJZvo_8B.DBiU5Tau.js",
"/ran/assets/chunks/count.CcfK-WL7.js",
"/ran/assets/chunks/theme.CGefJmKl.js",
"/ran/assets/chunks/commonjs-dynamic-modules-HhqG7SJg.B9lKsKkd.js",
"/ran/assets/chunks/lock-Cr7BnmWN.0WfYXC2j.js",
"/ran/assets/chunks/eye-D_mEt17f.DJFa_ttF.js",
"/ran/assets/chunks/check-circle-szyAJiap.CM_vbBX5.js",
"/ran/assets/chunks/message-D36_Zo2l.CR8K3LhI.js",
"/ran/assets/chunks/info-circle-fill-DjI8gXS3.DcQ9QdGJ.js",
"/ran/assets/chunks/close-circle-fill-jSqPPw9i.BsLXh5-a.js",
"/ran/assets/chunks/close-circle-CwmuN2C6.D612j4KD.js",
"/ran/assets/chunks/power-off-lQRbiBak.r13EH4bb.js",
"/ran/assets/cn_src_ranui_input_index.md.7533NkBL.js",
"/ran/assets/cn_src_ranuts_utils_task.md.CSriO4Oi.js",
"/ran/assets/src_types_模式匹配.md.DcXzrG7R.lean.js",
"/ran/assets/ali_doc.CYo30EHy.webp",
"/ran/assets/src_article_sort_count_index.md.BdMhZyw7.lean.js",
"/ran/assets/src_types_TS类型.md.D73qe7Ep.lean.js",
"/ran/assets/cn_src_article_ast_parse_tokenizer.md.BGIWhkVj.js",
"/ran/assets/aqiyi_demo.s0swGzvF.webp",
"/ran/assets/customElements.DbqgaaNb.png",
"/ran/assets/src_ranuts_file_write_file.md.D9xjOfEq.lean.js",
"/ran/assets/cn_src_ranuts_utils_format_json.md.Cf6dEkfl.js",
"/ran/assets/cn_src_article_sort_bubble_index.md.D8WeHyU9.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BM4pdUlf.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CP-SRyOA.js",
"/ran/assets/src_ranui_checkbox_index.md.CtrntZhH.js",
"/ran/assets/src_ranui_index.md.B6mMJQGk.lean.js",
"/ran/assets/src_ranuts_utils_get_cookie.md.DsBFRd9M.lean.js",
"/ran/assets/src_ranui_modal_index.md.Cl1YF-4V.lean.js",
"/ran/assets/cn_src_article_typescript_pattern.md.v51iYz1l.js",
"/ran/assets/cn_src_ranuts_utils_get_cookie.md.CVFLBQV3.js",
"/ran/assets/radix.Bwrylu8F.gif",
"/ran/assets/cn_src_ranuts_bundler_index.md.DNQ8Wwtz.lean.js",
"/ran/assets/cn_src_article_sort_merge_index.md.CBjmc9Qw.lean.js",
"/ran/assets/cn_src_ranuts_mime_type_mime_type.md.DON38605.lean.js",
"/ran/assets/wps_office_price.ler9htjh.webp",
"/ran/assets/建造者.B6neb_7R.jpeg",
"/ran/assets/src_ranuts_mode_subscribe.md.Cpdzg0XJ.js",
"/ran/assets/ms_file_not.DgOrkG3n.webp",
"/ran/assets/src_ranuts_file_read_dir.md.C1YO3dzC.js",
"/ran/assets/src_ranuts_utils_task.md.WWHcEnXW.lean.js",
"/ran/assets/cn_src_article_bundle.md.Co6q4l2G.lean.js",
"/ran/assets/src_ranuts_utils_ocr.md.Ckn8gcjq.lean.js",
"/ran/assets/mdn_pdf.DbNmeC8H.webp",
"/ran/assets/cn_src_article_sort_select_index.md.B530W5MY.lean.js",
"/ran/assets/kkfile_output.DD8iZdbo.webp",
"/ran/assets/inter-italic-cyrillic-ext.r48I6akx.woff2",
"/ran/assets/cn_src_article_typescript_union_type.md.CS12QWmw.js",
"/ran/assets/video_format.CRMCTmKB.webp",
"/ran/assets/cn_src_article_typescript_reconstruction.md.CBAF_xWq.js",
"/ran/assets/src_article_sort_shell_index.md.B9MVSXAo.js",
"/ran/assets/src_types_TS类型.md.D73qe7Ep.js",
"/ran/assets/extra.Da45cF33.jpeg",
"/ran/assets/cn_src_article_visual.md.C4e7nvJJ.lean.js",
"/ran/assets/cn_src_article_typescript_calculate.md.BQbEuaiK.lean.js",
"/ran/assets/cn_src_article_babel.md.DgHFpIbJ.lean.js",
"/ran/assets/src_ranui_tabs_index.md.CtBth00F.lean.js",
"/ran/assets/src_types_模式匹配.md.DcXzrG7R.js",
"/ran/assets/cn_src_ranuts_file_read_dir.md.BM4pdUlf.lean.js",
"/ran/assets/inter-roman-latin-ext.4ZJIpNVo.woff2",
"/ran/assets/export.ne8l5ppO.jpeg",
"/ran/assets/cn_src_article_sort_bucket_index.md.6J6kmsOe.js",
"/ran/assets/外观.Cm0-J0eF.png",
"/ran/assets/xdoc.CeowcMPq.webp",
"/ran/assets/firefox_support_media.BLmSeBNy.webp",
"/ran/assets/cn_src_article_sort_count_index.md.iYmt-nll.js",
"/ran/assets/cn_src_ranuts_file_write_file.md.CNBud208.js",
"/ran/assets/cn_src_types_TS类型.md.CuGMBV1-.js",
"/ran/assets/safari_support_media.Bafr23bR.webp",
"/ran/assets/inter-italic-greek.DJ8dCoTZ.woff2",
"/ran/assets/sort.CSVZS1AV.png",
"/ran/assets/src_ranui_loading_index.md.Cgfy_CDg.lean.js",
"/ran/assets/src_ranuts_binary_tree_index.md.CjV3PxER.lean.js",
"/ran/assets/cn_src_ranui_image_index.md.CiILNDeP.lean.js",
"/ran/assets/src_ranuts_file_file_info.md.DoLtTvNK.js",
"/ran/assets/src_ranui_tab_index.md.gfsPApKI.lean.js",
"/ran/assets/ms_answer_2.D-D9H1v0.webp",
"/ran/assets/src_article_sort_merge_index.md.VEKh572q.js",
"/ran/assets/继承.Dta6_xdc.png",
"/ran/assets/cn_src_note_centos.md.30sDv6dM.lean.js",
"/ran/assets/src_ranuts_file_write_file.md.D9xjOfEq.js",
"/ran/assets/count.CWSWBe_h.gif",
"/ran/assets/src_ranuts_file_read_dir.md.C1YO3dzC.lean.js",
"/ran/assets/cn_src_ranui_player_index.md.BbkStnzG.lean.js",
"/ran/assets/cn_src_article_sort_heap_index.md.BG-orbZV.js",
"/ran/assets/ExpressionStatement.zaIHlhIF.jpeg",
"/ran/assets/merge.Bguw-KQu.gif",
"/ran/assets/src_article_typescript_calculate.md.Bmso-WTu.lean.js",
"/ran/assets/src_ranui_tab_index.md.gfsPApKI.js",
"/ran/assets/cn_src_ranuts_file_append_file.md.CP-SRyOA.lean.js",
"/ran/assets/src_article_ast_parse_tokenizer.md.Db5rD-Yt.js",
"/ran/assets/cn_src_ranui_index.md.CRdVao-7.js",
"/ran/assets/src_ranui_loading_index.md.Cgfy_CDg.js",
"/ran/assets/cn_src_ranui_icon_index.md.DfSONHVl.lean.js",
"/ran/assets/axtexplorerSave.a5hTrvd2.jpeg",
"/ran/home.svg",
"/ran/icon_168.png",
"/ran/favicon.ico",
"/ran/icon_96.png",
"/ran/src/article/babel.html",
"/ran/src/article/ast_parse/tokenizer.html",
"/ran/src/article/bundle.html",
"/ran/src/article/javascript/dom_load.html",
"/ran/src/article/design_mode.html",
"/ran/src/article/imagemin.html",
"/ran/src/article/sort/heap/index.html",
"/ran/src/article/sort/index.html",
"/ran/src/article/sort/bucket/index.html",
"/ran/src/article/sort/count/index.html",
"/ran/src/article/sort/quick/index.html",
"/ran/src/article/sort/radix/index.html",
"/ran/src/article/sort/shell/index.html",
"/ran/src/article/sort/insert/index.html",
"/ran/src/article/sort/select/index.html",
"/ran/src/article/sort/bubble/index.html",
"/ran/src/article/sort/merge/index.html",
"/ran/src/article/functional_programming.html",
"/ran/src/article/typescript/pattern.html",
"/ran/src/article/typescript/index.html",
"/ran/src/article/typescript/calculate.html",
"/ran/src/article/typescript/reconstruction.html",
"/ran/src/article/typescript/union_type.html",
"/ran/src/article/typescript/recursion.html",
"/ran/src/ranuts/file/read_dir.html",
"/ran/src/ranuts/file/file_info.html",
"/ran/src/ranuts/file/write_file.html",
"/ran/src/ranuts/file/watch_file.html",
"/ran/src/ranuts/file/append_file.html",
"/ran/src/ranuts/file/read_file.html",
"/ran/src/ranuts/index.html",
"/ran/src/ranuts/utils/ocr.html",
"/ran/src/ranuts/utils/task.html",
"/ran/src/ranuts/utils/str2xml.html",
"/ran/src/ranuts/utils/filter_obj.html",
"/ran/src/ranuts/utils/format_json.html",
"/ran/src/ranuts/utils/convert_image_to_base64.html",
"/ran/src/ranuts/utils/get_cookie.html",
"/ran/src/ranuts/binary_tree/index.html",
"/ran/src/ranuts/bundler/index.html",
"/ran/src/ranuts/mime_type/mime_type.html",
"/ran/src/ranuts/mode/subscribe.html",
"/ran/src/types/TS类型.html",
"/ran/src/types/模式匹配.html",
"/ran/src/types/高级类型.html",
"/ran/src/types/类型运算.html",
"/ran/src/ranui/skeleton/index.html",
"/ran/src/ranui/radar/index.html",
"/ran/src/ranui/message/index.html",
"/ran/src/ranui/loading/index.html",
"/ran/src/ranui/popover/index.html",
"/ran/src/ranui/progress/index.html",
"/ran/src/ranui/index.html",
"/ran/src/ranui/player/index.html",
"/ran/src/ranui/button/index.html",
"/ran/src/ranui/input/index.html",
"/ran/src/ranui/preview/index.html",
"/ran/src/ranui/math/index.html",
"/ran/src/ranui/tab/index.html",
"/ran/src/ranui/checkbox/index.html",
"/ran/src/ranui/image/index.html",
"/ran/src/ranui/select/index.html",
"/ran/src/ranui/tabs/index.html",
"/ran/src/ranui/icon/index.html",
"/ran/src/ranui/modal/index.html",
"/ran/logo.png",
"/ran/sw1741496855.js",
"/ran/icon_72.png",
"/ran/vp-icons.css",
"/ran/404.html",
"/ran/hls/5_1701577744714/5_00002.ts",
"/ran/hls/5_1701577744714/5_00000.ts",
"/ran/hls/5_1701577744714/5_00001.ts",
"/ran/hls/5_1701577744714/5_00004.ts",
"/ran/hls/5_1701577744714/5_00003.ts",
"/ran/hls/5_1701577744714/5.key",
"/ran/hls/5_1701577744714/5_00005.ts",
"/ran/hls/5_1701577744714/5_00006.ts",
"/ran/hls/5_1701577744714/5.m3u8",
"/ran/hls/5_1701577771368/5_00002.ts",
"/ran/hls/5_1701577771368/5_00000.ts",
"/ran/hls/5_1701577771368/5_00001.ts",
"/ran/hls/5_1701577771368/5_00004.ts",
"/ran/hls/5_1701577771368/5_00003.ts",
"/ran/hls/5_1701577771368/5.key",
"/ran/hls/5_1701577771368/5_00005.ts",
"/ran/hls/5_1701577771368/5_00006.ts",
"/ran/hls/5_1701577771368/5.m3u8",
"/ran/hls/example.m3u8",
"/ran/icon_48.png",
"/ran/manifest.json",
"/ran/icon_192.png",
"/ran/screenshots_2560x1440.jpg",
"/ran/screenshots_748x1340.jpg",
"/ran/hashmap.json",
"/ran/ocr/chi_sim.png",
"/ran/ocr/eng.png",
"/ran/cn/index.html",
"/ran/cn/src/article/babel.html",
"/ran/cn/src/article/system_design.html",
"/ran/cn/src/article/doc_preview.html",
"/ran/cn/src/article/ast_parse/tokenizer.html",
"/ran/cn/src/article/visual.html",
"/ran/cn/src/article/math/linear_algebra.html",
"/ran/cn/src/article/video.html",
"/ran/cn/src/article/bundle.html",
"/ran/cn/src/article/javascript/dom_load.html",
"/ran/cn/src/article/design_mode.html",
"/ran/cn/src/article/imagemin.html",
"/ran/cn/src/article/sort/heap/index.html",
"/ran/cn/src/article/sort/index.html",
"/ran/cn/src/article/sort/bucket/index.html",
"/ran/cn/src/article/sort/count/index.html",
"/ran/cn/src/article/sort/quick/index.html",
"/ran/cn/src/article/sort/radix/index.html",
"/ran/cn/src/article/sort/shell/index.html",
"/ran/cn/src/article/sort/insert/index.html",
"/ran/cn/src/article/sort/select/index.html",
"/ran/cn/src/article/sort/bubble/index.html",
"/ran/cn/src/article/sort/merge/index.html",
"/ran/cn/src/article/functional_programming.html",
"/ran/cn/src/article/typescript/pattern.html",
"/ran/cn/src/article/typescript/index.html",
"/ran/cn/src/article/typescript/calculate.html",
"/ran/cn/src/article/typescript/reconstruction.html",
"/ran/cn/src/article/typescript/union_type.html",
"/ran/cn/src/article/typescript/recursion.html",
"/ran/cn/src/ranuts/file/read_dir.html",
"/ran/cn/src/ranuts/file/file_info.html",
"/ran/cn/src/ranuts/file/write_file.html",
"/ran/cn/src/ranuts/file/watch_file.html",
"/ran/cn/src/ranuts/file/append_file.html",
"/ran/cn/src/ranuts/file/read_file.html",
"/ran/cn/src/ranuts/index.html",
"/ran/cn/src/ranuts/utils/ocr.html",
"/ran/cn/src/ranuts/utils/task.html",
"/ran/cn/src/ranuts/utils/str2xml.html",
"/ran/cn/src/ranuts/utils/filter_obj.html",
"/ran/cn/src/ranuts/utils/format_json.html",
"/ran/cn/src/ranuts/utils/convert_image_to_base64.html",
"/ran/cn/src/ranuts/utils/get_cookie.html",
"/ran/cn/src/ranuts/binary_tree/index.html",
"/ran/cn/src/ranuts/bundler/index.html",
"/ran/cn/src/ranuts/mime_type/mime_type.html",
"/ran/cn/src/ranuts/mode/subscribe.html",
"/ran/cn/src/note/docker.html",
"/ran/cn/src/note/centos.html",
"/ran/cn/src/note/libreoffice2wasm.html",
"/ran/cn/src/note/ubuntu.html",
"/ran/cn/src/types/TS类型.html",
"/ran/cn/src/types/模式匹配.html",
"/ran/cn/src/types/高级类型.html",
"/ran/cn/src/types/类型运算.html",
"/ran/cn/src/ranui/skeleton/index.html",
"/ran/cn/src/ranui/radar/index.html",
"/ran/cn/src/ranui/message/index.html",
"/ran/cn/src/ranui/loading/index.html",
"/ran/cn/src/ranui/popover/index.html",
"/ran/cn/src/ranui/progress/index.html",
"/ran/cn/src/ranui/index.html",
"/ran/cn/src/ranui/player/index.html",
"/ran/cn/src/ranui/button/index.html",
"/ran/cn/src/ranui/input/index.html",
"/ran/cn/src/ranui/preview/index.html",
"/ran/cn/src/ranui/math/index.html",
"/ran/cn/src/ranui/tab/index.html",
"/ran/cn/src/ranui/checkbox/index.html",
"/ran/cn/src/ranui/image/index.html",
"/ran/cn/src/ranui/select/index.html",
"/ran/cn/src/ranui/tabs/index.html",
"/ran/cn/src/ranui/icon/index.html",
"/ran/cn/src/ranui/modal/index.html",
];
const VERSION = "1741496855";
const CACHE_NAME = 'chaxus_ran_' + VERSION

const IGNORE_REQUEST_LIST = [
  // google 上报不需要缓存
  'google',
  // 插件请求不用缓存
  'chrome-extension',
  // 百度的请求不用缓存
  'baidu.com',
  'blob:',
  'www.google-analytics.com'
]

// 请求方法
const REQUEST_METHOD = {
  GET: 'GET'
}
// 响应状态码
const RESPONSE_STATUS = {
  SUCCESS: 200
}
// service worker 可监听的事件
const SERVICE_WORK = {
  INSTALL: 'install',
  FETCH: 'fetch',
  ACTIVATE: 'activate',
  MESSAGE: 'message',
  SYNC: 'sync',
  PUSH: 'push'
}
/**
 * @description: 更新缓存
 * @param {*} fetchedResponse
 * @param {*} request
 * @return {*}
 */
const updateCache = (fetchedResponse, request) => {
  const { url } = request
  const { status } = fetchedResponse
  // 只缓存状态码为 200 的请求
  if (status !== RESPONSE_STATUS.SUCCESS) return
  if (filterRequest(request)) {
    caches.open(CACHE_NAME).then(cache => {
      // 将请求到的资源添加到缓存中
      // 判断下只有 fetch 的请求才有 clone 方法，才可以被缓存，从 cache 中获取的响应没有 clone
      if (fetchedResponse?.clone) {
        cache.put(url, fetchedResponse.clone());
      }
    }).catch(error => {
      console.log('service worker update cache error:', error, request)
    })
  }
}
/**
 * @description: 忽略 IGNORE_REQUEST_LIST 列表中的请求和非GET方法的请求
 * @param {*} request
 * @return {*}
 */
const filterRequest = (request) => {
  const { url, method } = request
  return !IGNORE_REQUEST_LIST.some(item => url.includes(item)) && method === REQUEST_METHOD.GET
}

/**
 * 缓存优先
 * @param {*} request
 * @returns
 */
const cacheFirst = async (request) => {
  // 从缓存中读取 respondWith 表示拦截请求并返回自定义的响应
  try {
    const { url } = request
    const responseFromCache = await caches.match(url);
    // 如果缓存中有，返回已经缓存的资源
    if (responseFromCache) return responseFromCache
    // 如果缓存中没有，就从网络中请求，并更新到缓存中
    const responseFromServer = await fetch(request);
    updateCache(responseFromServer, request)
    return responseFromServer
  } catch (error) {
    // 当缓存中也没有，请求也不可用的时候
    // 始终需要一个一个响应
    // 甚至可以设置回落的请求，在catch中继续发起请求
    console.log('service worker cacheFirst error:', error, request)
    return new Response("Network error happened", {
      status: 408,
      headers: { "Content-Type": "text/plain" },
    });
  }
}


const deleteCache = async (key) => {
  try {
    await caches.delete(key);
  } catch (error) {
    console.log('service worker deleteCache error:', error, key)
  }
};

const deleteOldCaches = async () => {
  const cacheKeepList = [CACHE_NAME];
  try {
    const keyList = await caches.keys();
    const cachesToDelete = keyList.filter((key) => !cacheKeepList.includes(key));
    await Promise.all(cachesToDelete.map(deleteCache));
  } catch (error) {
    console.log('service worker deleteOldCaches error:', deleteOldCaches, cacheKeepList)
  }

};

this.addEventListener(SERVICE_WORK.INSTALL, function (event) {
  // 确保 Service Worker 不会在 waitUntil() 里面的代码执行完毕之前安装完成
  event.waitUntil(
    // 创建了叫做 chaxus_ran 的新缓存
    caches.open(CACHE_NAME).then(function (cache) {
      // SERVICE_WORK_CACHE_FILE_PATHS 从 bin/build.sh 中生成注入，会去缓存所有的资源
      // 不用 cache.addAll 避免一个请求失败，全部缓存失败，类似Promise.all
      // 可以使用 cache.add 但 Cache.add/Cache.addAll 不会缓存 Response.status 值不在 200 范围内的响应，
      // 而 cache.put 允许你存储任何请求/响应对。因此，Cache.add/Cache.addAll 不能用于不透明的响应，而 Cache.put 可以。
      return SERVICE_WORK_CACHE_FILE_PATHS.map(url =>
        fetch(url).then(response => {
          // 检查响应是否成功
          if (!response.ok) {
            console.log('service worker fetch response error:', url)
          }
          // 将响应添加到缓存
          return cache.put(url, response);
        }).catch(error => {
          console.log('service worker self installed error:', url, error);
        })
      )
    })
  );
});

this.addEventListener(SERVICE_WORK.FETCH, async (event) => {
  // 拦截请求
  try {
    cacheFirst(event.request)
  } catch (error) {
    console.log('service worker self fetch error:', error, event)
  }
});

this.addEventListener(SERVICE_WORK.ACTIVATE, (event) => {
  event.waitUntil(deleteOldCaches());
});



