/** Copy shared by the server-rendered workbench and its progressive enhancement. */
const copy = {
  en: [
    'Try the components',
    'Buttons',
    'Progress',
    'Selection',
    'View code',
    'Reset example',
    'Disabled',
    'Progress',
    'Selected',
    'Not selected',
    '{label} clicked',
    'Try the controls, then copy the HTML.',
  ],
  zh: [
    '直接试用组件',
    '按钮',
    '进度',
    '选择',
    '查看代码',
    '重置示例',
    '禁用按钮',
    '进度',
    '已选择',
    '未选择',
    '点击了 {label}',
    '操作组件，查看并复制对应的 HTML。',
  ],
  ja: [
    'コンポーネントを試す',
    'ボタン',
    '進捗',
    '選択',
    'コードを見る',
    'リセット',
    '無効にする',
    '進捗',
    '選択済み',
    '未選択',
    '{label} をクリック',
    '操作して、対応する HTML をコピーできます。',
  ],
  es: [
    'Prueba los componentes',
    'Botones',
    'Progreso',
    'Selección',
    'Ver código',
    'Restablecer',
    'Desactivar',
    'Progreso',
    'Seleccionado',
    'Sin seleccionar',
    '{label} pulsado',
    'Prueba los controles y copia el HTML.',
  ],
  pt: [
    'Experimente os componentes',
    'Botões',
    'Progresso',
    'Seleção',
    'Ver código',
    'Redefinir',
    'Desativar',
    'Progresso',
    'Selecionado',
    'Não selecionado',
    '{label} clicado',
    'Experimente os controles e copie o HTML.',
  ],
  ko: [
    '컴포넌트 체험',
    '버튼',
    '진행률',
    '선택',
    '코드 보기',
    '초기화',
    '비활성화',
    '진행률',
    '선택됨',
    '선택 안 됨',
    '{label} 클릭됨',
    '컴포넌트를 조작하고 HTML 을 복사하세요.',
  ],
  de: [
    'Komponenten ausprobieren',
    'Buttons',
    'Fortschritt',
    'Auswahl',
    'Code ansehen',
    'Zurücksetzen',
    'Deaktivieren',
    'Fortschritt',
    'Ausgewählt',
    'Nicht ausgewählt',
    '{label} angeklickt',
    'Bediene die Komponenten und kopiere das HTML.',
  ],
  fa: [
    'کامپوننت‌ها را امتحان کنید',
    'دکمه‌ها',
    'پیشرفت',
    'انتخاب',
    'نمایش کد',
    'بازنشانی',
    'غیرفعال',
    'پیشرفت',
    'انتخاب‌شده',
    'انتخاب‌نشده',
    '{label} کلیک شد',
    'کنترل‌ها را امتحان کنید و HTML را رونوشت بگیرید.',
  ],
} as const;
export const playgroundCopy = (lang: string) => {
  const [title, buttons, progress, selection, code, reset, disabled, percent, selected, unselected, clicked, hint] =
    copy[lang.split('-')[0] as keyof typeof copy] ?? copy.en;
  return { title, buttons, progress, selection, code, reset, disabled, percent, selected, unselected, clicked, hint };
};
