import { SyncHook } from './subscribe';
import { Mathjs, addNumSym, mathjs, perToNum, range, transformNumber } from './number';
import {
  MessageCodec,
  changeHumpToLowerCase,
  checkEncoding,
  clearBr,
  clearStr,
  getMatchingSentences,
  getRandomString,
  isString,
  md5,
  randomString,
  str2Xml,
  strParse,
  toString,
  transformText,
} from './str';
import type { TransformText } from './str';
import {
  BridgeManager,
  Client,
  Platform,
  PostMessageBridge,
  appendUrl,
  bridgeManager,
  connection,
  createObjectURL,
  durationHandler,
  encodeUrl,
  getAllQueryString,
  getCookie,
  getCookieByName,
  getFrame,
  getHost,
  getPixelRatio,
  getQuery,
  getWindow,
  imageRequest,
  isSafari,
  networkSpeed,
  removeGhosting,
  requestUrlToBuffer,
  retain,
} from './bom';
import type {
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
  MessageData,
  MessageHandler,
  PendingRequest,
} from './bom';
import {
  cloneDeep,
  filterObj,
  formatJson,
  isEqual,
  merge,
  mergeExports,
  querystring,
  replaceOld,
  setAttributeByGlobal,
} from './obj';
import { MimeType, getExtensions, getMime, setMime } from './mimeType';
import { AudioRecorder } from './audioRecorder';
import { createSignal, subscribers } from './signal';
import { audioVendor, canvasVendor, webglVendor } from './behavior';
import { TOTP } from './totp/totp';
import { localStorageGetItem, localStorageSetItem } from './storage';
import { compose } from './compose';
import { handleConsole } from './console';
import { debounce } from './debounce';
import {
  Chain,
  addClassToElement,
  create,
  createDocumentFragment,
  escapeHtml,
  removeClassToElement,
  setFontSize2html,
} from './dom';
import { handleError } from './error';
import { convertImageToBase64, isImageSize } from './img';
import { memoize } from './memoize';
import { Monitor } from './monitor';
import { getStatus, status } from './network';
import { noop } from './noop';
import { getPerformance } from './performance';
import { QuestQueue } from './queue';
import { createData, report } from './report';
import { handleFetchHook } from './request';
import { scriptOnLoad } from './script';
import { generateThrottle, throttle } from './throttle';
import { performanceTime, timeFormat, timestampToTime } from './time';
import type { CurrentDevice } from './device';
import { currentDevice, isBangDevice, isClient, isMobile, isWeiXin } from './device';
import {
  Color,
  ColorScheme,
  FMT,
  Hsl,
  Hsla,
  Rgb,
  Rgba,
  componentToHex,
  hexToRgb,
  hsbToRgb,
  hslToRgb,
  hsvToHsl,
  hsvToRgb,
  hue2rgb,
  randomColor,
  rgbToHex,
  rgbToHsb,
  rgbToHsl,
} from '@/utils/color';
export {
  performanceTime,
  timeFormat,
  timestampToTime,
  generateThrottle,
  throttle,
  SyncHook,
  changeHumpToLowerCase,
  clearBr,
  clearStr,
  isString,
  randomString,
  str2Xml,
  strParse,
  scriptOnLoad,
  handleFetchHook,
  createData,
  report,
  QuestQueue,
  noop,
  getPerformance,
  querystring,
  formatJson,
  filterObj,
  merge,
  replaceOld,
  mergeExports,
  perToNum,
  range,
  Mathjs,
  mathjs,
  getStatus,
  status,
  Monitor,
  MimeType,
  getExtensions,
  setMime,
  getMime,
  memoize,
  isImageSize,
  convertImageToBase64,
  handleError,
  addClassToElement,
  removeClassToElement,
  createDocumentFragment,
  escapeHtml,
  isClient,
  isWeiXin,
  isMobile,
  debounce,
  currentDevice,
  handleConsole,
  compose,
  Color,
  FMT,
  Hsl,
  Hsla,
  Rgb,
  Rgba,
  randomColor,
  hexToRgb,
  componentToHex,
  rgbToHex,
  rgbToHsl,
  hue2rgb,
  hslToRgb,
  rgbToHsb,
  hsbToRgb,
  hsvToRgb,
  hsvToHsl,
  ColorScheme,
  AudioRecorder,
  webglVendor,
  canvasVendor,
  audioVendor,
  retain,
  getCookie,
  requestUrlToBuffer,
  getPixelRatio,
  createObjectURL,
  getFrame,
  getHost,
  getAllQueryString,
  appendUrl,
  removeGhosting,
  getCookieByName,
  getWindow,
  connection,
  encodeUrl,
  imageRequest,
  durationHandler,
  networkSpeed,
  TOTP,
  isBangDevice,
  localStorageGetItem,
  localStorageSetItem,
  setAttributeByGlobal,
  setFontSize2html,
  Chain,
  create,
  isEqual,
  cloneDeep,
  createSignal,
  subscribers,
  getMatchingSentences,
  transformNumber,
  toString,
  addNumSym,
  getQuery,
  checkEncoding,
  transformText,
  isSafari,
  md5,
  getRandomString,
  bridgeManager,
  Client,
  BridgeManager,
  PostMessageBridge,
  MessageCodec,
  Platform,
};

export type {
  CurrentDevice,
  TransformText,
  MessageHandler,
  MessageData,
  PendingRequest,
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
};
