import { SyncHook } from './subscribe';
import {
  Mathjs,
  addNumSym,
  mathjs,
  parseChineseNumber,
  parseEnglishNumber,
  parseRomanNumber,
  perToNum,
  range,
  transformNumber,
} from './number';
import {
  MessageCodec,
  arrayBufferToString,
  changeHumpToLowerCase,
  checkEncoding,
  clearBr,
  clearStr,
  getMatchingSentences,
  getRandomString,
  isString,
  md5,
  randomString,
  str2Xml,
  strParse,
  toFullWidth,
  toHalfWidth,
  toString,
  transformText,
} from './str';
import type { TransformText } from './str';
import {
  appendUrl,
  connection,
  createObjectURL,
  durationHandler,
  encodeUrl,
  getAllQueryString,
  getCookie,
  getCookieByName,
  getFrame,
  getPixelRatio,
  getQuery,
  getWindow,
  imageRequest,
  isSafari,
  networkSpeed,
  removeGhosting,
  requestUrlToBuffer,
  retain,
} from './bom';
import {
  BRIDGE_MARKER,
  BridgeManager,
  Client,
  DEFAULT_CHANNEL,
  Platform,
  PostMessageBridge,
  acceptPortBridge,
  bridgeManager,
  createPortBridge,
  openPortBridge,
} from './bridge';
import type {
  AcceptPortBridgeOptions,
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
  MessageData,
  MessageHandler,
  OpenPortBridgeOptions,
  PendingRequest,
  PortBridge,
} from './bridge';
import {
  cloneDeep,
  filterObj,
  formatJson,
  isEqual,
  merge,
  mergeExports,
  querystring,
  replaceOld,
  setAttributeByGlobal,
} from './obj';
import { MimeType, getExtensions, getMime, setMime } from './mimeType';
import { AudioRecorder } from './audioRecorder';
import { createSignal, subscribers } from './signal';
import { audioVendor, canvasVendor, webglVendor } from './behavior';
import { TOTP } from './totp/totp';
import { localStorageGetItem, localStorageSetItem } from './storage';
import { compose } from './compose';
import { handleConsole } from './console';
import { debounce } from './debounce';
import {
  Chain,
  addClassToElement,
  create,
  createDocumentFragment,
  escapeHtml,
  removeClassToElement,
  setFontSize2html,
} from './dom';
import { handleError } from './error';
import { convertImageToBase64, isImageSize } from './img';
import { memoize, once, singleFlight } from './memoize';
import type { SingleFlight } from './memoize';
import { WebDB } from './idb';
import type { IDBResult, IDBStoreSchema, WebDBOptions } from './idb';
import { buildOffsets, indexForOffset, segmentByRanges } from './segment';
import type { OffsetRange, Segment } from './segment';
import { detectLanguage, navigatorLanguage } from './lang';
import { createLocalePath } from './localePath';
import type { LocalePath, LocalePathConfig, LocaleRoute } from './localePath';
import type { TextLanguage } from './lang';
import { readFileAsArrayBuffer, readFileAsDataURL, readFileAsText, readFileAsUint8Array } from './file';
import { WorkerClient } from './worker';
import type { WorkerClientOptions, WorkerResponseBase } from './worker';
import { isUrlCached, networkAllowsDownload, prefetchUrl, prefetchUrls, prefetchWhenIdle, whenIdle } from './prefetch';
import type { NetworkAllowanceOptions, PrefetchOptions, WhenIdleOptions } from './prefetch';
import { Monitor } from './monitor';
import { getStatus, status } from './network';
import { noop } from './noop';
import { getPerformance } from './performance';
import { QuestQueue } from './queue';
import { createData, report } from './report';
import { handleFetchHook } from './request';
import { scriptOnLoad } from './script';
import { throttle } from './throttle';
import { performanceTime, timeFormat, timestampToTime } from './time';
import type { CurrentDevice } from './device';
import {
  MOBILE_MEDIA_QUERY,
  currentDevice,
  isBangDevice,
  isClient,
  isMobile,
  isWeiXin,
  matchMediaQuery,
  watchMediaQuery,
} from './device';
import {
  Color,
  ColorScheme,
  FMT,
  Hsl,
  Hsla,
  Rgb,
  Rgba,
  componentToHex,
  hexToRgb,
  hsbToRgb,
  hslToRgb,
  hsvToHsl,
  hsvToRgb,
  hue2rgb,
  randomColor,
  rgbToHex,
  rgbToHsb,
  rgbToHsl,
} from '@/utils/color';
export {
  performanceTime,
  timeFormat,
  timestampToTime,
  throttle,
  SyncHook,
  changeHumpToLowerCase,
  clearBr,
  clearStr,
  isString,
  randomString,
  str2Xml,
  strParse,
  scriptOnLoad,
  handleFetchHook,
  createData,
  report,
  QuestQueue,
  noop,
  getPerformance,
  querystring,
  formatJson,
  filterObj,
  merge,
  replaceOld,
  mergeExports,
  perToNum,
  range,
  Mathjs,
  mathjs,
  getStatus,
  status,
  Monitor,
  MimeType,
  getExtensions,
  setMime,
  getMime,
  memoize,
  once,
  isImageSize,
  convertImageToBase64,
  handleError,
  addClassToElement,
  removeClassToElement,
  createDocumentFragment,
  escapeHtml,
  isClient,
  isWeiXin,
  isMobile,
  debounce,
  currentDevice,
  handleConsole,
  compose,
  Color,
  FMT,
  Hsl,
  Hsla,
  Rgb,
  Rgba,
  randomColor,
  hexToRgb,
  componentToHex,
  rgbToHex,
  rgbToHsl,
  hue2rgb,
  hslToRgb,
  rgbToHsb,
  hsbToRgb,
  hsvToRgb,
  hsvToHsl,
  ColorScheme,
  AudioRecorder,
  webglVendor,
  canvasVendor,
  audioVendor,
  retain,
  getCookie,
  requestUrlToBuffer,
  getPixelRatio,
  createObjectURL,
  getFrame,
  getAllQueryString,
  appendUrl,
  removeGhosting,
  getCookieByName,
  getWindow,
  connection,
  encodeUrl,
  imageRequest,
  durationHandler,
  networkSpeed,
  TOTP,
  isBangDevice,
  localStorageGetItem,
  localStorageSetItem,
  setAttributeByGlobal,
  setFontSize2html,
  Chain,
  create,
  isEqual,
  cloneDeep,
  createSignal,
  subscribers,
  getMatchingSentences,
  transformNumber,
  toString,
  addNumSym,
  getQuery,
  checkEncoding,
  transformText,
  isSafari,
  md5,
  getRandomString,
  bridgeManager,
  Client,
  BridgeManager,
  PostMessageBridge,
  MessageCodec,
  Platform,
  openPortBridge,
  acceptPortBridge,
  createPortBridge,
  BRIDGE_MARKER,
  DEFAULT_CHANNEL,
  singleFlight,
  WebDB,
  buildOffsets,
  indexForOffset,
  segmentByRanges,
  detectLanguage,
  navigatorLanguage,
  readFileAsArrayBuffer,
  readFileAsUint8Array,
  readFileAsText,
  readFileAsDataURL,
  WorkerClient,
  whenIdle,
  networkAllowsDownload,
  isUrlCached,
  prefetchUrl,
  prefetchUrls,
  prefetchWhenIdle,
  arrayBufferToString,
  toHalfWidth,
  toFullWidth,
  parseChineseNumber,
  parseRomanNumber,
  parseEnglishNumber,
  MOBILE_MEDIA_QUERY,
  matchMediaQuery,
  watchMediaQuery,
  createLocalePath,
};

export type {
  LocalePath,
  LocalePathConfig,
  LocaleRoute,
  SingleFlight,
  IDBResult,
  IDBStoreSchema,
  WebDBOptions,
  OffsetRange,
  Segment,
  TextLanguage,
  WorkerClientOptions,
  WorkerResponseBase,
  WhenIdleOptions,
  NetworkAllowanceOptions,
  PrefetchOptions,
  CurrentDevice,
  TransformText,
  MessageHandler,
  MessageData,
  PendingRequest,
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
  PortBridge,
  OpenPortBridgeOptions,
  AcceptPortBridgeOptions,
};
