import { SyncHook } from './subscribe';
import {
  Mathjs,
  addNumSym,
  mathjs,
  parseChineseNumber,
  parseEnglishNumber,
  parseRomanNumber,
  perToNum,
  range,
  transformNumber,
} from './number';
import {
  MessageCodec,
  arrayBufferToString,
  changeHumpToLowerCase,
  checkEncoding,
  clearBr,
  clearStr,
  getMatchingSentences,
  getRandomString,
  isString,
  md5,
  randomString,
  str2Xml,
  strParse,
  toFullWidth,
  toHalfWidth,
  toString,
  transformText,
} from './str';
import type { TransformText } from './str';
import {
  appendUrl,
  connection,
  createObjectURL,
  durationHandler,
  encodeUrl,
  getAllQueryString,
  getCookie,
  getCookieByName,
  getFrame,
  getPixelRatio,
  getQuery,
  getWindow,
  imageRequest,
  isInIframe,
  isSafari,
  networkSpeed,
  queryFlag,
  removeGhosting,
  requestUrlToBuffer,
  retain,
} from './bom';
import {
  BRIDGE_MARKER,
  BridgeManager,
  Client,
  DEFAULT_CHANNEL,
  Platform,
  PostMessageBridge,
  acceptPortBridge,
  bridgeManager,
  createPortBridge,
  openPortBridge,
} from './bridge';
import type {
  AcceptPortBridgeOptions,
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
  MessageData,
  MessageHandler,
  OpenPortBridgeOptions,
  PendingRequest,
  PortBridge,
} from './bridge';
import {
  cloneDeep,
  filterObj,
  formatJson,
  isEqual,
  merge,
  mergeExports,
  querystring,
  replaceOld,
  setAttributeByGlobal,
} from './obj';
import { MimeType, getExtensions, getMime, setMime } from './mimeType';
import { AudioRecorder } from './audioRecorder';
import { createSignal, subscribers } from './signal';
import { audioVendor, canvasVendor, webglVendor } from './behavior';
import { TOTP } from './totp/totp';
import { createStore, localStorageGetItem, localStorageRemoveItem, localStorageSetItem } from './storage';
import type { JsonStore } from './storage';
import { compose } from './compose';
import { handleConsole } from './console';
import { debounce } from './debounce';
import type { Debounced } from './debounce';
import {
  Chain,
  addClassToElement,
  create,
  createDocumentFragment,
  escapeHtml,
  removeClassToElement,
  setFontSize2html,
} from './dom';
import { handleError } from './error';
import { EventManager } from './event';
import { circ, cubic, expo, quad, quart, quint, sine } from './tween';
import type { EasingFn, SpeedType } from './tween';
import { convertImageToBase64, cutRound, getImage, getMatrix, isImageSize, opacity } from './img';
import type { ImgSource } from './img';
import {
  fanShapedByArc,
  getAngle,
  getArcPointerByDeg,
  getLinearGradient,
  getTangentByPointer,
  roundRectByArc,
} from './canvas';
import { ADOPTED_SHEET_MARKER, ADOPTED_STYLE_MARKER, adoptSheetText, adoptStyles } from './style';
import { memoize, once, singleFlight } from './memoize';
import type { SingleFlight } from './memoize';
import { WebDB, createHandoff } from './idb';
import type { Handoff, HandoffOptions, IDBCollection, IDBResult, IDBStoreSchema, WebDBOptions } from './idb';
import { buildOffsets, indexForOffset, segmentByRanges } from './segment';
import { paginateText } from './paginate';
import type { PaginateOptions, PaginateResult, TextBox, TextGridMetrics, TextPage } from './paginate';
import type { OffsetRange, Segment } from './segment';
import { detectLanguage, navigatorLanguage, resolveLocale } from './lang';
import { I18nCore, createI18n, useI18n } from './i18n';
import type { I18nConfig, LocaleChangeHandler, LocaleMessages, MessageDict, TranslateParams } from './i18n';
import { createLocalePath } from './localePath';
import type { LocalePath, LocalePathConfig, LocaleRoute } from './localePath';
import type { ResolveLocaleOptions, TextLanguage } from './lang';
import { readFileAsArrayBuffer, readFileAsDataURL, readFileAsText, readFileAsUint8Array } from './file';
import { WorkerClient, serveWorker } from './worker';
import type {
  ServeWorkerOptions,
  WorkerClientOptions,
  WorkerHandlerContext,
  WorkerRequestBase,
  WorkerResponseBase,
} from './worker';
import { isUrlCached, networkAllowsDownload, prefetchUrl, prefetchUrls, prefetchWhenIdle, whenIdle } from './prefetch';
import type { NetworkAllowanceOptions, PrefetchOptions, WhenIdleOptions } from './prefetch';
import { TimeoutError, deferred, delay, withTimeout, withTimeoutFallback } from './async';
import type { Deferred } from './async';
import {
  ZIP_DEFLATE,
  ZIP_STORED,
  createZip,
  crc32,
  inflateRaw,
  readZipEntries,
  readZipEntry,
  rewriteZip,
  zipHasEntry,
} from './zip';
import type { RewriteZipOptions, ZipEntry } from './zip';
import { Monitor } from './monitor';
import { getStatus, status } from './network';
import { noop } from './noop';
import { getPerformance } from './performance';
import { QuestQueue } from './queue';
import { createData, getReportUrl, report, setReportUrl } from './report';
import type { BeaconPayload, ReportConfig } from './report';
import { handleFetchHook, handleXhrHook } from './request';
import { loadScript, scriptOnLoad } from './script';
import type { LoadScriptOptions } from './script';
import { throttle } from './throttle';
import type { Throttled } from './throttle';
import { formatDate, performanceTime, timeFormat, timestampToTime } from './time';
import type { CurrentDevice } from './device';
import {
  MOBILE_MEDIA_QUERY,
  currentDevice,
  isBangDevice,
  isClient,
  isMobile,
  isWeiXin,
  matchMediaQuery,
  watchMediaQuery,
} from './device';
import {
  Color,
  ColorScheme,
  FMT,
  HEX_COLOR_REGEX,
  Hsl,
  Hsla,
  RGBA_REGEX,
  RGB_REGEX,
  Rgb,
  Rgba,
  componentToHex,
  hexToAlpha,
  hexToHsb,
  hexToHsv,
  hexToRgb,
  hsbToHsl,
  hsbToRgb,
  hslToHsb,
  hslToHsv,
  hslToRgb,
  hsvToHsl,
  hsvToRgb,
  hue2rgb,
  randomColor,
  rgbToHex,
  rgbToHsb,
  rgbToHsl,
  rgbToHsv,
  rgbaString,
  rgbaToHex,
  rgbaToRgb,
} from '@/utils/color';
export {
  performanceTime,
  timeFormat,
  timestampToTime,
  throttle,
  SyncHook,
  changeHumpToLowerCase,
  clearBr,
  clearStr,
  isString,
  randomString,
  str2Xml,
  strParse,
  scriptOnLoad,
  handleFetchHook,
  createData,
  report,
  QuestQueue,
  noop,
  getPerformance,
  querystring,
  formatJson,
  filterObj,
  merge,
  replaceOld,
  mergeExports,
  perToNum,
  range,
  Mathjs,
  mathjs,
  getStatus,
  status,
  Monitor,
  MimeType,
  getExtensions,
  setMime,
  getMime,
  memoize,
  once,
  isImageSize,
  convertImageToBase64,
  handleError,
  addClassToElement,
  removeClassToElement,
  createDocumentFragment,
  escapeHtml,
  isClient,
  isWeiXin,
  isMobile,
  debounce,
  currentDevice,
  handleConsole,
  compose,
  Color,
  FMT,
  Hsl,
  Hsla,
  Rgb,
  Rgba,
  randomColor,
  hexToRgb,
  componentToHex,
  rgbToHex,
  rgbToHsl,
  hue2rgb,
  hslToRgb,
  rgbToHsb,
  hsbToRgb,
  hsvToRgb,
  hsvToHsl,
  ColorScheme,
  AudioRecorder,
  webglVendor,
  canvasVendor,
  audioVendor,
  retain,
  getCookie,
  requestUrlToBuffer,
  getPixelRatio,
  createObjectURL,
  getFrame,
  getAllQueryString,
  queryFlag,
  isInIframe,
  appendUrl,
  removeGhosting,
  getCookieByName,
  getWindow,
  connection,
  encodeUrl,
  imageRequest,
  durationHandler,
  networkSpeed,
  TOTP,
  isBangDevice,
  localStorageGetItem,
  localStorageSetItem,
  localStorageRemoveItem,
  createStore,
  setAttributeByGlobal,
  setFontSize2html,
  Chain,
  create,
  isEqual,
  cloneDeep,
  createSignal,
  subscribers,
  getMatchingSentences,
  transformNumber,
  toString,
  addNumSym,
  getQuery,
  checkEncoding,
  transformText,
  isSafari,
  md5,
  getRandomString,
  bridgeManager,
  Client,
  BridgeManager,
  PostMessageBridge,
  MessageCodec,
  Platform,
  openPortBridge,
  acceptPortBridge,
  createPortBridge,
  BRIDGE_MARKER,
  DEFAULT_CHANNEL,
  singleFlight,
  WebDB,
  createHandoff,
  buildOffsets,
  paginateText,
  indexForOffset,
  segmentByRanges,
  detectLanguage,
  navigatorLanguage,
  resolveLocale,
  readFileAsArrayBuffer,
  readFileAsUint8Array,
  readFileAsText,
  readFileAsDataURL,
  WorkerClient,
  serveWorker,
  whenIdle,
  networkAllowsDownload,
  isUrlCached,
  prefetchUrl,
  prefetchUrls,
  prefetchWhenIdle,
  deferred,
  withTimeout,
  withTimeoutFallback,
  delay,
  TimeoutError,
  crc32,
  inflateRaw,
  readZipEntries,
  readZipEntry,
  zipHasEntry,
  rewriteZip,
  createZip,
  ZIP_STORED,
  ZIP_DEFLATE,
  arrayBufferToString,
  toHalfWidth,
  toFullWidth,
  parseChineseNumber,
  parseRomanNumber,
  parseEnglishNumber,
  MOBILE_MEDIA_QUERY,
  matchMediaQuery,
  watchMediaQuery,
  createLocalePath,
  setReportUrl,
  getReportUrl,
  formatDate,
  handleXhrHook,
  EventManager,
  quad,
  cubic,
  quart,
  quint,
  sine,
  expo,
  circ,
  getImage,
  cutRound,
  opacity,
  getMatrix,
  getAngle,
  getArcPointerByDeg,
  getTangentByPointer,
  fanShapedByArc,
  roundRectByArc,
  getLinearGradient,
  adoptStyles,
  adoptSheetText,
  ADOPTED_STYLE_MARKER,
  ADOPTED_SHEET_MARKER,
  rgbToHsv,
  hexToHsb,
  hexToHsv,
  hsbToHsl,
  hslToHsb,
  hslToHsv,
  hexToAlpha,
  rgbaString,
  rgbaToRgb,
  rgbaToHex,
  HEX_COLOR_REGEX,
  RGB_REGEX,
  RGBA_REGEX,
  loadScript,
  I18nCore,
  createI18n,
  useI18n,
};

export type {
  EasingFn,
  SpeedType,
  ImgSource,
  LoadScriptOptions,
  I18nConfig,
  MessageDict,
  LocaleMessages,
  TranslateParams,
  LocaleChangeHandler,
  Debounced,
  Throttled,
  BeaconPayload,
  ReportConfig,
  LocalePath,
  LocalePathConfig,
  LocaleRoute,
  SingleFlight,
  IDBCollection,
  IDBResult,
  IDBStoreSchema,
  WebDBOptions,
  Handoff,
  HandoffOptions,
  JsonStore,
  Deferred,
  ZipEntry,
  RewriteZipOptions,
  ResolveLocaleOptions,
  OffsetRange,
  PaginateOptions,
  PaginateResult,
  TextBox,
  TextGridMetrics,
  TextPage,
  Segment,
  TextLanguage,
  ServeWorkerOptions,
  WorkerClientOptions,
  WorkerHandlerContext,
  WorkerRequestBase,
  WorkerResponseBase,
  WhenIdleOptions,
  NetworkAllowanceOptions,
  PrefetchOptions,
  CurrentDevice,
  TransformText,
  MessageHandler,
  MessageData,
  PendingRequest,
  BridgeManagerOptions,
  BroadcastPayload,
  CallToPayload,
  PortBridge,
  OpenPortBridgeOptions,
  AcceptPortBridgeOptions,
};
