import '../style';
import '../theme-packs/pixel-retro';
import '../theme-packs/windows-98';
import '../theme-packs/windows-xp';
import '../theme-packs/system-6';
import '../theme-packs/wired';
import '../theme-packs/paper';
import '../theme-packs/neo-brutalism';
import '../index';
