name: build to my github

on: # 触发条件
  push: # 每当 push 到 master 分支时触发部署
    branches:
      - feature/docs

jobs:
  deploy:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npx pnpm install 

      - name: Build
        run: npx pnpm -F docs build

      # - name: CreateTag
      #   run git tag -a
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: packages/docs/.vitepress/dist
